### ISSUE TITLE
[Bug] MSVSMON.EXE

### ISSUE THREAD

**Issue by xenu256** [QuantConnect/Lean#10]
Unable to start Lean.Engine.exe as: see image

![bug](https://cloud.githubusercontent.com/assets/7689499/5721553/baab6fd6-9b3b-11e4-8c47-53196010ff56.png)

**Comment by jaredbroad** [comment]
Strange; what Visual Studio/Windows version are you running? Can you create a new solution with a basic Hello World console application and try running that?

**Comment by xenu256** [comment]
Uhm, yep, does not run, it's Community VS, installed it today.

**Comment by jaredbroad** [comment]
Local issue with VS Installation
