### ISSUE TITLE
[Crypto] IHistoryProvider - GDAX 

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#1000]
As IDataDownloader - implementation to the GDAX API to fetch history for the GDAX exchange. Potentially reusing a GDaxBrokerage implementation to minimize code reuse.

**Comment by StefanoRaggi** [comment]
Currently `GDAXBrokerage` does not implement `IBrokerage.GetHistory`, so  `BrokerageHistoryProvider.GetHistory` always returns an empty result.

We should probably move the existing code in `GDAXDownloader.Get` to `GDAXBrokerage.GetHistory` and update `GDAXDownloader.Get` to call `GDAXBrokerage.GetHistory`.
