### ISSUE TITLE
Baseclass.Contrib... 2.2.0-xbuild02	not found with VS2017

### ISSUE THREAD

**Issue by zelenij** [QuantConnect/Lean#1018]
Hi everyone,

Is it expected that Windows build should use Baseclass.Contrib... 2.2.0-xbuild02?  A couple of projects in the solution reference it, however NuGet can't download it.  I've upgraded the projects to the more generic 2.3.0 version of the package, but would like to see why we are using the older one?

**Comment by jaredbroad** [comment]
Yes we require it due to the views cross platform GUI web browser library we're using in linux (Gecko). It has a dependency on that older Baseclass library.
