### ISSUE TITLE
F# stuff doesn't compile anymore

### ISSUE THREAD

**Issue by lloydmeta** [QuantConnect/Lean#1019]
My F# projects that compiled a few days ago no longer compile. I think this started happening ~2 days ago, and the compile error is 

```
Build Error: File: /QuantConnect.Compiler/bin/2e21703-b03a0ba/bin/Debug/main.fs Line:-56 Column:0 - The type 'ValueType' is required here and is unavailable. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=redacted| 02:43:19:
```

I've gotten this ` You must add a reference to assembly 'System.Runtime` error in my own projects as well as the QCU projects (e.g. `How Do I Filter Bad Data-Ticks? (F#)`)  thus far. There are also other errors that didn't happen before that follow this error, but I'm currently on the assumption that those are caused by this earlier one.

Are they perhaps related to the upgrade to FSharp 4.2 in bf2bc44d9af04c99ab0f0f1d585e17ee213b1e43 ?

**Comment by jaredbroad** [comment]
Thanks @lloydmeta we've resolved this in the cloud.
