### ISSUE TITLE
Don't use Suspicious ticks in fill models

### ISSUE THREAD

**Issue by 4real** [QuantConnect/Lean#1023]
Okay, so I found one algo I was using was making its profit from Suspicious ticks. Apparently, these aren't marked in the real time stream (so filtering them out altogether is a bad idea), but fill models in backtests shouldn't be using them.

**Comment by jaredbroad** [comment]
When we build the bars we filter many exchanges on top of the suspicious
ticks. This is a heuristic decision as we hope to make the data as close to
what you'd really get at the second and minute level.

Generally we expect people using ticks to understand them fully as they are
harder to use. Equally people could request fill models which only use the
suspicious or off exchange fills.

**Comment by 4real** [comment]
Pretty sure it's going to be a surprise for quite a few people writing their first tick algos. It's a trap for e.g. mean reversion algos. ML algos also love picking up signals like this.

**Comment by jaredbroad** [comment]
Implemented in https://github.com/QuantConnect/Lean/pull/1388/commits/c5da472abef61f898d85a99a41ac6a0f704988af
