### ISSUE TITLE
Document workflow with Docker

### ISSUE THREAD

**Issue by favetelinguis** [QuantConnect/Lean#1028]
I want to run my Python algorithms using the Docker image to avoid having to setup things locally. However I find the documentation lacking in the following regards.

In the bottom of the Dockerfile the following is documented:
```
# Usage:
# docker build -t quantconnect/lean:foundation -f DockerfileLeanFoundation .
# docker build -t quantconnect/lean:algorithm -f DockerfileLeanAlgorithm .
# docker run -v "(absolute to your data folder):/root/Lean/Data" quantconnect/lean:algorithm
```
`docker build -t quantconnect/lean:foundation -f DockerfileLeanFoundation .` works as expected and builds me the default platform to launch my algorithm on. 
However the second part `docker build -t quantconnect/lean:algorithm -f DockerfileLeanAlgorithm .` is not working since I cant find any file called DockerfileLeanAlgorithm. Would be nice with some more documentation on how this file is created and how a complete workflow using docker would look like in the same way there is a workflow for Linux/Mac/Windows.

**Comment by LiXiang618** [comment]
Hi @favetelinguis,
Thank you very much for this issue, as well as your nice suggestions.
In case you haven't yet run Lean in Docker, here are the correct commands you should follow:
After you install Docker on your computer, use "cd Lean" command to get into Lean. Then

docker build -t   quantconnect/lean:foundation   -f   DockerfileLeanFoundation .
(After this command, you can type "docker image" to check whether the image is built.)
docker run -i -t -v     ~/Lean:/root/Lean/     quantconnect/lean:foundation    /bin/bash

**~** means Home: "C:\Users\YourName\", and here I assume Lean is in "C:\Users\YourName\Lean".
The first command builds the docker environment based on DockerfileLeanFoundation.
The second command will get you inside the container **quantconnect/lean:foundation**, using **/bin/bash** as your terminal and mapping your Lean in Windows  **~/Lean** to Lean in the docker **/root/Lean/**

You are recommended to compile Lean with Visual Studio in **Windows**, and then in **Docker command** "cd ./Launcher/bin/Debug", "mono ./QuantConnect.Lean.Launcher.exe"
Then you can enjoy writing your algorithm.

After finishing everything, you can use 
**docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q) && docker rmi $(docker images -a -q)**
to clean up all the docker images.
(And again, you could use "docker image" command to check it is clean.) 

We appreciate your suggestion so much. If you have any question, please don't hesitate to tell us. And we will update the corresponding files in Github as soon as possible.

Xiang Li

**Comment by jaredbroad** [comment]
The Usage section is still accurate but the file name was changed to "Dockerfile" instead of "DockerfileLeanAlgorithm"

**Comment by shafaypro** [comment]
@LiXiang618 : the Docker prompts : "error response from daemon: Unknown instruction: &&", on the following command
docker build -t quantconnect/lean:foundation -f DockerfileLeanFoundation .

**Comment by shafaypro** [comment]
While using the docker to create directly through file I get Folder which is missing 
Step 3/5 : COPY ./Launcher/bin/Release /root/Lean/Launcher/bin/Release
lstat Launcher/bin/Release: no such file or directory
, so I tried to configure the docker file and uncomment the option1, I get 
"caution: filename not matched:  /root/Lean
The command '/bin/sh -c wget https://github.com/QuantConnect/Lean/archive/master.zip && unzip master.zip /root/Lean && cd /root/Lean' returned a non-zero code: 11"
