### ISSUE TITLE
Oanda Data Downloader >> ToolBox Project

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#103]
Create a Oanda data downloader tool to allow scraping the Oanda API for FX and CFD data. This would be a long running tool people could run in the background, start every time they login to windows etc.

-> Create a Console interface project following a similar format to ToolBox/QuantQuote project. 

-> Create a list of all Oanda symbols and their associated SecurityType with the project.

-> Scan configurable Lean/Data directory for Symbols-SecurityType and if they don't exist start downloading the symbol-type for the first time, download ALL the symbol data.

-> Once the download is done, sleep the console application for 24 hours.

-> In 24 hours wake up, rescan the directory for the latest date file, download the updated data from the Oanda API 

Save CFD's to a new "cfd" type directory, forex to the existing "forex" directory and metals to a new "commodity" folder. Symbols need to be stripped of slashes to keep working as directories.

**Comment by StefanoRaggi** [comment]
This is the full list of tradeable instruments with Oanda (downloaded with Oanda API):
[OandaSymbols.txt | uploaded via ZenHub](https://files.zenhub.io/557897d1f2e14dda725357ac)

We could store the list in a Dictionary or in an external file.

We'll also need a json configuration file with a few settings:

{
    lean-data-folder: "c:\Lean\Data",
    instruments: "EUR_USD,DE30_EUR,SPX500_USD",
    resolutions: "S5,M1,H1,D",
    ...
}

The minimum resolution for historical data is 5 sec. and there is no historical tick data available via API (I think you can request some via email to Oanda - if you have a funded account).
The alternative is to subscribe to requested symbols, and save the ticks as they are received; the problem with this is you need a very good connection, because a disconnect implies a hole in the saved data.

Thoughts ?

**Comment by jaredbroad** [comment]
Hmm thanks @StefanoRaggi - I'll reach out to Oanda and see what they say. I chatted with them a week or so ago and they had a historical API but maybe its private.

**Comment by bizcad** [comment]
I tried running the list through my Exchange Lookup routine, which looks up the Exchange from the symbol on GoogleFinance to no avail.  All of the entries came up with "UNKNOWN_EXCHANGE".  The convention I use for getting data from Google is a csv file Symbol, Exchange, Name {, extra columns}. 

Is there a way to get the Exchange from symbol in the oanda API?

I slightly disagree with putting the instruments and the resolutions in the config file.  I think that is better off in the algorithm.  For testing purposes, the instrument symbol is a folder under {lean-data-folder} and the daily files are under that with the first column being the start_time for the bar.  The first column, the date, is the number of milliseconds of the DateTime.

Here is how I format the csv line in my routine which reads minute data from GoogleFinance.<pre>
/// <summary>
/// Returns a "CSV" line with date, open, high, low, close and volume fields.
/// </summary>
private string formatData<T>(string dateFormat, DateTime date, T open, T high, T low, T close, T volume)
{
    var x = open.GetType();
    var o = System.Convert.ToSingle(open) * 10000;
    var h = System.Convert.ToSingle(high) * 10000;
    var l = System.Convert.ToSingle(low) * 10000;
    var c = System.Convert.ToSingle(close) * 10000;
    var v = System.Convert.ToInt32(volume);
    return String.Format("{0},{1},{2},{3},{4},{5},{6}", date.TimeOfDay.TotalMilliseconds, o, h, l, c, v, date.ToString("yyyy-MM-dd HH:mm:ss"));
}</pre>

**Comment by jaredbroad** [comment]
hey @bizcad, this is for a Toolbox project -- a oanda data downloader to start the process of fully supporting Oanda brokerage: https://github.com/QuantConnect/ToolBox

If you can I'd love to add a Google Finance Downloader as well! Can you please submit it as a PR to the ToolBox repo? Then save the daily files to the daily directory in Lean?

**Comment by StefanoRaggi** [comment]
@bizcad This issue is not referring to the Lean Engine, but to the downloaded program in the Toolbox (which I'm working on now).

The entry in the config file is to tell the downloader which symbols to download. I don't think all users would want to download all 124 instruments.

**Comment by StefanoRaggi** [comment]
@jared You beat me for a second :)

**Comment by jaredbroad** [comment]
@StefanoRaggi perhaps this could still be a separate text file list (defaulting to all) that people can reduce if they don't want all of them?

**Comment by StefanoRaggi** [comment]
We could put the complete list in the json file as commented lines (only symbol and description). So the user would copy to the "instruments:" json key only the ones desired. If the key is empty, it defaults to all.

**Comment by bizcad** [comment]
Oh sorry.  I misunderstood.  I will check out the toolbox. 

I was considering adding GoogleFinance to Lean for backtesting purposes.  I was thwarted in this effort because I could not access the compression object from the GetSource method.  The toolbox may be better.  I will take a look

**Comment by bizcad** [comment]
@StefanoRaggi If you like you can take a look at my GoogleFinance Downloader and see if there is anything there you can use.  https://github.com/bizcad/MarketData

Readme.md says where to see documentation.

**Comment by StefanoRaggi** [comment]
@bizcad Thanks for the link. I'll take a look before starting coding.

**Comment by jaredbroad** [comment]
Closed 
https://github.com/QuantConnect/ToolBox/commit/8754f28c9cca3bf685e0c37b285883042a676035
