### ISSUE TITLE
No OrderTickets for open orders when starting algo

### ISSUE THREAD

**Issue by 4real** [QuantConnect/Lean#1044]
I run into this, for example with one stop order left open:

QCAlgorithm.Transactions.GetOpenOrders().Count() == 1
&&
QCAlgorithm.Transactions.GetOrderTickets().Count() == 0

In general, while it appears you can modify the order without an OrderTicket, it's relatively inconvenient, especially if your existing code is built on OrderTickets.

Casually cancelling orders to avoid the above and submitting new ones is costly given $1 IB cancellation fees and the current crash frequency ;)

**Comment by jaredbroad** [comment]
Thank you @4real; we'll make sure the order tickets get initialized as well.

**Comment by jaredbroad** [comment]
Merged in #1097
