### ISSUE TITLE
Unable to import Tensorflow on Mac

### ISSUE THREAD

**Issue by cc07** [QuantConnect/Lean#1050]
I discovered when i use the Python.RunTime.DLL from Lean/packages, the python is running as 32 bit, hence cause an error for tensorflow as in below. However, if i try to compile the pythonnet on my own, it will get me an System.EntryPointNotFoundException: Py_IsInitialized. Please advise a solution.

With great thanks,
Chris

```
ImportError: dlopen(/Library/Python/2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): no suitable image found.  Did find:
	/Library/Python/2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture
```

**Comment by AlexCatarino** [comment]
Please install 64-bit python 2.7.

**Comment by cc07** [comment]
umm...the strange thing is either i run the mac's native python or the one i installed with anaconda, they are all in 64 bit. Just if i use mono to run the nPython.exe from the lean packages, it becomes 32 bit...

I've tried compile pythonnet with the above python version my own, still cant resolved the problem. BTW, i am using Mac Sierra 10.12.

**Comment by cc07** [comment]
I finally managed it to solve by re-installing the mono, the case was some old symbolic link not updated. Thanks for your help anyway.
