### ISSUE TITLE
International Markets Support

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#106]
Upgrade the SecurityExchange Class to support international exchange time zones and dynamic market hours.

See here for international market hours for each type:
http://fxtrade.oanda.co.uk/help/policies/weekend-exposure-limits  

Markets to support are: New York, Chicago, Amsterdam,Hong Kong, Germany, Paris, Switzerland, Sydney.

Each of these could be a data-class which we add in over time. The first implementation of this must simply support: NewYorkMarket : Market,

The market configuration should be something like this:
Country (and Holidays),
Days Open (Monday-Friday etc)
Hours Open UTC

Create a static Exchange Data Table class which exposes a method "GetExchangeData(Market.NewYork)" and returns a new data transfer object with the following parameters:

Market {
   PreMarketOpen,
   MarketOpen,
   MarketClose,
   PostMarketOpen,
   Holidays[],
   TimeZone
}

These should be used in the Exchange to determine if the market is open.

**Comment by mchandschuh** [comment]
The GetExchange function will probably also require the security type

**Comment by jaredbroad** [comment]
Could use C# Noda time to do the international timezone support to automatically account for day light saving etc.

**Comment by mchandschuh** [comment]
@dpavlenkov This was commited in https://github.com/QuantConnect/Lean/commit/6bd38ece7738b76d293515429d8d2c589a012082. I heard you had an interest in this issue and would certainly love any feedback you could offer. The more eyes on these kinds of changes the better :)

**Comment by dpavlenkov** [comment]
That's great Michael! If it rubs me the wrong way, I'll let you know.

**Comment by ammachado** [comment]
The Brazilian market could be included in this upgrade as well.

**Comment by mchandschuh** [comment]
@AlexCatarino has started looking into adding the brazilian market. Adding a market *should* be fairly simple. You'll need to add the correct data to the /Data/market-hours/market-hours-database.csv file and optionally provide a 'holidays-brazil.csv' holidays file. After that, you'll need some raw data for backtesting in the /Data/equity/brazil/ and/or /Data/forex/brazil/ folders, then you can specify to use that market via the AddSecurity method that accepts a market.

If you have any questions please let me know!

**Comment by AlexCatarino** [comment]
I will clone the exponential 50-10 moving average cross strategy and run it with an equity (and the e-mini futures contract for the index after that) from the Brazilian market. In the process, I will implement all the according changes enumerated by @mchandschuh. Wish me good luck!

**Comment by jaredbroad** [comment]
Completed in commit 28d8300e4
