### ISSUE TITLE
Schedule.On with similar trigger times map to same key/name

### ISSUE THREAD

**Issue by 4real** [QuantConnect/Lean#1061]
If you do something like this:
`Schedule.On(DateRules.EveryDay(Symbol), TimeRules.AfterMarketOpen(Symbol, 1), A);
Schedule.On(DateRules.EveryDay(Symbol), TimeRules.AfterMarketOpen(Symbol, 1), B);`

Either A or B (can't recall which takes predence) will be lost and not be called. This is very WTF behavior and user can lose a lot of time debugging it.

Similarly, TimeRules.Every has the following implementation:
`var name = "Every " + interval.TotalMinutes.ToString("0.##") + " min";`

Also in this case, it will cause similar WTFs if you dare to schedule with the same period on the same days.

Suggestion: Replace ConcurrentDictionary in real time handler with threadsafe multimap, e.g. https://www.codeproject.com/Articles/34013/A-Concurrent-Collection-a-MultiMap-Generic-Collect (I haven't looked at this particular implementation in detail, just bringing it up as an example, there are probably better alternatives).

I have a hard time seeing that lock contention would be an issue anyway, given that adding scheduled events is pretty rare and typically done during initialization.

**Comment by jaredbroad** [comment]
Good feedback thank you.

**Comment by mchandschuh** [comment]
The multi map is a great idea, easily done by making the storage
ConcurrentDictionary<Lazy<List<T>>>.

The lazy will guarantee that only one instance of list will be created.
Also, the reason it is concurrent is to slow enumeration and edit of the
collecting at same tune.

The whole reason for the name was only to allow people to remove them at a
later time.

Got any questions, feel free to reach out... I have a feeling my stench is
all over that code :D

-Michael
