### ISSUE TITLE
Add Indicator Acceleration Bands

### ISSUE THREAD

**Issue by LiXiang618** [QuantConnect/Lean#1066]
Acceleration Bands (Normally Period = 20, Width = 2)

The Acceleration Bands (ABANDS) created by Price Headley plots upper and lower envelope bands around a simple moving average. The width of the bands is based on the formula below.

Formula:
Upper Band = Simple Moving Average (High * ( 1 + Width * (High - Low) / (High + Low)))
Lower Band = Simple Moving Average (Low * (1 - Width * (High - Low)/ (High + Low)))

Notes:
High is the High value of each day.
Low is the Low value of each day.
Period is the number of days used to calculate Moving Average.
Width is the parameter to control the magnitude.

Test Data:
Lean/Test/TestData/spy_acceleration_bands_20_2.txt
[spy_acceleration_bands_20_2.txt](https://github.com/QuantConnect/Lean/files/1228816/spy_acceleration_bands_20_2.txt)

Reference:
https://www.tradingtechnologies.com/help/x-study/technical-indicator-definitions/acceleration-bands-abands/
https://traderstrategies.wordpress.com/2015/06/10/acceleration-bands/

**Comment by Jay-Jay-D** [comment]
I take it.

**Comment by jaredbroad** [comment]
Completed in #6a512e8
