### ISSUE TITLE
Add Indicator Detrended Price Oscillator

### ISSUE THREAD

**Issue by LiXiang618** [QuantConnect/Lean#1068]
Detrended Price Oscillator (In the sample N = 21)

The Detrended Price Oscillator (DPO) is an indicator designed to remove trend from price and make it easier to identify cycles.

Formula:
Price {N/2 + 1} periods ago less the N-period simple moving average.

Note:
N refers to the number of periods used to calculate the Detrended Price Oscillator. A 20-day DPO would use a 20-day SMA that is displaced by 11 periods {20/2 + 1 = 11}. This displacement shifts the 20-day SMA 11 days to the left, which actually puts it in the middle of the look-back period. The value of the 20-day SMA is then subtracted from the price in the middle of this look-back period. In short, DPO(20) equals price 11 days ago less the 20-day SMA. 

Sample Data:
[spy_detrended_price_oscillator_21.txt](https://github.com/QuantConnect/Lean/files/1229245/spy_detrended_price_oscillator_21.txt)

Reference:
http://www.stockcharts.com/school/doku.php?id=chart_school:technical_indicators:detrended_price_osci

**Comment by Jay-Jay-D** [comment]
This issue should be closed.
