### ISSUE TITLE
Add Indicator Mass Index

### ISSUE THREAD

**Issue by LiXiang618** [QuantConnect/Lean#1069]
Mass Index (Normally N1 = 25, N2 = 9)

Developed by Donald Dorsey, the Mass Index uses the high-low range to identify trend reversals based on range expansions. In this sense, the Mass Index is a volatility indicator that does not have a directional bias. Instead, the Mass Index identifies range bulges that can foreshadow a reversal of the current trend.

Formula:
Single EMA = N2-period exponential moving average (EMA) of the high-low differential  
Double EMA = N2-period EMA of the N2-period EMA of the high-low differential (i.e. N2-period EMA of Single EMA)
EMA Ratio = Single EMA divided by Double EMA 
Mass Index = N1-period sum of the EMA Ratio 

Note:
N1 in the sample data is 25.
N2 in the sample data is supposed to be 9, but needs verification.

Sample Data:
[spy_mass_index_25.txt](https://github.com/QuantConnect/Lean/files/1229400/spy_mass_index_25.txt)

Reference:
http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:mass_index

**Comment by Jay-Jay-D** [comment]
I take it

**Comment by Jay-Jay-D** [comment]
This issue should be closed.
