### ISSUE TITLE
Add Quote Currency Support for Base Security Class

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#107]
Assets are purchased in a currency. Currently in Lean this defaults to the Account Currency (USD). Add the ability for the quote currency to be changed to another currency. 

All the security properties should continue displaying their output in the Account currency of the algorithm.

**Comment by mchandschuh** [comment]
There's a function that gets called from the setup handlers called EnsureCurrencyDataFeeds and is used to verify we have conversions from quote currency to account currency. This function currently lives on the CashBook object but should probably be moved to the Portfolio object (SecurityPortfolioManager class) so it can also inspect the securities to check for non-account currency quote currencies

**Comment by jaredbroad** [comment]
Completed late 2015
