### ISSUE TITLE
Add Indicator MACD Histogram

### ISSUE THREAD

**Issue by LiXiang618** [QuantConnect/Lean#1077]
MACD Histogram (Normally N1 = 12, N2 = 26, N3 = 9)

Developed by Thomas Aspray in 1986, the MACD-Histogram measures the distance between MACD and its signal line (the 9-day EMA of MACD). Like MACD, the MACD-Histogram is also an oscillator that fluctuates above and below the zero line.

Formula:
MACD: (N1-day EMA - N2-day EMA) 
Signal Line: N3-day EMA of MACD
MACD Histogram: MACD - Signal Line

Note:
N1, N2, and N3 are 12, 26 and 9 respectively in the sample data.

Sample Data:
[spy_macd_histogram_12_26_9.txt](https://github.com/QuantConnect/Lean/files/1235008/spy_macd_histogram_12_26_9.txt)

Reference:
http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:macd-histogram

**Comment by mchandschuh** [comment]
This could be done easily by using the existing Mac indicator which already
defines a signal line, all it needs is to perform the subtraction.

**Comment by 4real** [comment]
I agree it should be a property of the existing indicator.

**Comment by Shamitha-R** [comment]
I've started looking into getting this indicator added. Can I be made the assignee?

**Comment by AlexCatarino** [comment]
@Shamitha-R , I think you need to fork Lean so that we can assign it to you.
Anyway, consider yourself assigned for this issue!
**Thank very much!**

**Comment by jaredbroad** [comment]
Merged in #1514
