### ISSUE TITLE
Profiler for cloud environment

### ISSUE THREAD

**Issue by 4real** [QuantConnect/Lean#1086]
Not sure if this is the right place to put this ticket, since the use for this primarily would be for running Lean in the cloud, but:

If you look at e.g. the Unity game engine, it has its own profiler where you can track the amount of time spent in various callback methods. The same would be very useful for QuantConnect when dealing with slow ML algorithms. E.g. I can see my universe selection algo is currently slow but I don't know if it's a scheduled event running every 5 minutes or my OnData for minute bars (both doing a lot of work potentially), so I will have to guess.

Unity profiler: https://www.youtube.com/watch?v=sBpXiJ9G3OY
No fancy charts necessary, only the percentage of execution time spent in each function as numbers.

Potentially, there's already existing libraries for this and not much coding is required beyond the user interface and adding hooks around callbacks to be profiled; haven't checked. However, given that several of my prior colleagues have implemented their own profiling systems as small part time projects I don't think it's an intractable problem.

Edit: Should add that I will work around this by using my own timing code, but aside from workarounds taking time from algo dev, I think it would be a useful feature for everybody, especially people with less coding experience.

**Comment by jaredbroad** [comment]
Would love to! Debugger has to come first though -- but perhaps more realistic / short term achievable for this would be a random data generator? Then we can do profiling work locally with the powerful existing profiling tools. Closing for now as building a profiler is a massive technical endeavor =) ... whole companies are committed to them.
