### ISSUE TITLE
VSIX VS Plugin Doesn't Build in VS 2017

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#1104]
Maybe this? https://developercommunity.visualstudio.com/content/problem/3647/build-of-vsix-project-fails-with-systemiofilenotfo.html

```
Severity    Code    Description    Project    File    Line    Suppression State
Error        The "GetDeploymentPathFromVsixManifest" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Settings.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.Settings.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.VsSDK.Build.Tasks.GetDeploymentPathFromVsixManifest.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].    QuantConnect.VisualStudioPlugin 
```

**Comment by jaredbroad** [comment]
Updating via nuget to 15.X version says:
```
Error		Could not install package 'Microsoft.VisualStudio.Utilities 15.0.26607'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	
```

**Comment by Martin-Molinero** [comment]
From: https://developercommunity.visualstudio.com/content/problem/28405/getdeploymentpathfromvsixmanifest-fails.html

"**Update** your project references using the **nugget manager** to reference the new "**Microsoft.VSSDK.BuildTools**" which is version 15. That fixes your error but you will face a new one. To avoid the build error "Manifest Pre-requisites cannot be empty", **open the manifest and add a dependency to "Visual Studio SDK"**, version 15 is automatically detected. Build your solution, should work."

I can confirm this worked for me. I'm attaching a patch with the changes.

[Issue#1104_Patch.zip](https://github.com/QuantConnect/Lean/files/1272468/Issue.1104_Patch.zip)

**Comment by jaredbroad** [comment]
Thanks @Martin-Molinero! Please fork the repo and submit a PR with the path --  you can see the contributors guide here:  https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md

**Comment by jaredbroad** [comment]
Fixed in #1116

**Comment by Worthy7** [comment]
FYI, I can install it but see no new menu items after restarting

**Comment by osnjunior91** [comment]
I was having this error, after updating the dependencies of the project via Nuget, the error disappeared.
