### ISSUE TITLE
Calculate Running Statistics & Make Accessible In Algorithm

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#1105]
Calculate the running statistics for the algorithm such as sharpe / sortino etc and make their values accessible in the algorithm. 

==

#### Expected Behavior
Be able to access runtime statistics (e.g. win rate, sharpe ratio, etc) with the algorithm. 

#### Actual Behavior
Algorithm statistics are calculated at the result handlers and users don't have access to this information during an algorithm execution which may be important for live algorithms.
Link: https://www.quantconnect.com/forum/discussion/3619/better-live-tracking-statistics/p1

#### Potential Solution
N/A

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by JackMMMC** [comment]
Yes! I can do that from the algorithmic trading platform AlgoTerminal, www.algoterminal.com
Please add that to QuantConnect.

**Comment by voidale** [comment]
Is that possible to do right now?

**Comment by jaredbroad** [comment]
- Create IStatisticsService Interface, make IResultHandler implement statistics service.
 - Add IStatisticsService.StatisticsResults method no args; returns StatisticsResults instance.
 - In SetAlgorithm() set the IStatisticsService to the algorithm as a private algorithm.SetStatisticsService(_statisticService);
 - In IAlgorithm create property Statistics return StatisticResult object
 - in QCAlgorithm implement Property as read-only `get { return _statisticService.StatisticsResults(); }`

**Comment by jaredbroad** [comment]
Bonus points if:
 - If we can avoid recalculating it at the end of the backtest and reuse the same object
 - Add custom entries to the dictionary of result statistics. Statistics.SetSummaryStatistic(key, value)
 - Which together might open the possibility to add [custom properties to the result summary](https://discord.com/channels/846109296973840424/1077363234279002244/1077363824430174278)

**Comment by ari62** [comment]
im not sure if these stats are written out into the backtest results json, I didn't see them. They are available in the backtest though. It would be great if they were added to the written out json files on a per period basis for example:
```
        for symbol, trade_bar in slice.Bars.items():  # there is 1 tradebar for each symbol
            tradeBar: TradeBar = trade_bar
            holding: SecurityHolding = self.Portfolio[symbol]

            ticker: str = holding.Symbol.Value
           
            self.statsHistory.securityStats[ticker].profits.append([timestamp, holding.Profit])
            self.statsHistory.securityStats[ticker].holdingsValues.append([timestamp, holding.HoldingsValue])
            self.statsHistory.securityStats[ticker].unrealizedProfits.append([timestamp, holding.UnrealizedProfit])
            self.statsHistory.securityStats[ticker].unrealizedProfitPercent.append([timestamp, holding.UnrealizedProfitPercent])
            self.statsHistory.securityStats[ticker].averagePrices.append([timestamp, holding.AveragePrice])
            self.statsHistory.securityStats[ticker].quantitys.append([timestamp, holding.Quantity])
            self.statsHistory.securityStats[ticker].isLongs.append([timestamp, holding.IsLong])
            self.statsHistory.securityStats[ticker].isShorts.append([timestamp, holding.IsShort])
```

also it would be great if we could download the files from cloud in the same format maybe via a zip as they get generated locally. cloud has orders in a csv vs json for local for example. a few other differences.
