### ISSUE TITLE
Optimization API

### ISSUE THREAD

**Issue by sirinath** [QuantConnect/Lean#1113]
Is it possible to get an optimization API like: https://www.quantopian.com/posts/optimize-api-generally-available. There are some drawback in the Q API which you can improve. E.g. you cannot have function / lambda which takes the weights to maximize / minimize, hence it is difficult to do mean variance optimization.

**Comment by jaredbroad** [comment]
We have a different approach to this; we'll be merging it this week. We call it the algorithm framework. https://github.com/QuantConnect/Lean/pull/1372
