### ISSUE TITLE
AddData for Quandl in research Notebooks

### ISSUE THREAD

**Issue by Worthy7** [QuantConnect/Lean#1117]
Please can we get a qb.AddData function so we can access Quandl in notebooks.

**Comment by jaredbroad** [comment]
Thanks for the issue. We *think* this works in LEAN; are you referring to generic types in the QuantConnect.com/research application?

In the cloud we only support known data sources for now (aka Quandl). We'll consider whitelisting other data sources but it is not a LEAN issue (it is done for QC.com security).

**Comment by Worthy7** [comment]
Sorry, I didn't realize there was a separate repo for the research notebooks. This was a while ago, I'll have to double check, but basically I was asking if we could pull in Quandl data into notebooks somehow.

**Comment by Worthy7** [comment]
I took a look at an old thread: https://www.quantconnect.com/forum/discussion/397/new-feature-quandl-data-importing
What's the problem with:
`AddData("YAHOO/INDEX_SPY", Resolution.Minute);`
this kind of import exactly?
Should I reopen this over in research?

**Comment by jaredbroad** [comment]
Notebooks do support AddData. I guess the issue you're reporting here is something you've found using quantconnect.com/research which is our application/tool we host -- not the open source project. This is the open source repo for issues (feature request/bugs) about LEAN specifically. 

For requesting features/issues/anything on quantconnect.com/ *** then please use the quantconnect support system or the community forums. 

Closing as already supported.
