### ISSUE TITLE
Java API?

### ISSUE THREAD

**Issue by realcake** [QuantConnect/Lean#1123]
I noticed their is support for Java, but I have no idea how to get it to work. Is there a way to get a jar file of the library so I can backtest locally in Java?

**Comment by jaredbroad** [comment]
Java isnt officially supported but you can use IKVM to build DLLs which
match the IAlgorithm interface and import them. By setting the language to
java in config.

It is hard to write an algorithm with it and so few people wanted java it
was never a priority sorry.
