### ISSUE TITLE
Using trade engine

### ISSUE THREAD

**Issue by Rexota** [QuantConnect/Lean#1141]
Hello, thanks for great library.

I am creating a crypto-currency exchange site and for it's trade engine I'd like to utilize Lean. I want to be able to dispatch **buy** & **sell** orders to Lean and listen for order events to update my database. Is it possible to integrate my current work-flow, if so, how? I couldn't find detailed example.

**Comment by jaredbroad** [comment]
That's not really LEAN's intent and it wouldn't do well there (would be large LEAN overhead / code base you wouldn't be using). It is not a trade matching engine but we would integrate with the API for your exchange as a **consumer** of your trade feeds; and then individuals would send in trades to be filled.
