### ISSUE TITLE
Review History Data Normalization

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#1142]
Review history data normalization and validate if it is using adjusted prices to end date of history request or end date of today. Confirm if it's avoiding look ahead bias in the adjusted prices.

**Comment by disruptek** [comment]
This seems like it could be a catastrophic defect, but performing a simple validation shouldn't be much of a challenge.  Am I missing something?

**Comment by Martin-Molinero** [comment]
The `SubscriptionDataReaderHistoryProvider` https://github.com/QuantConnect/Lean/blob/master/Engine/HistoricalData/SubscriptionDataReaderHistoryProvider.cs creates a new stack, including a new `SubscriptionDataConfig` for each new `HistoryRequest`. The `DataNormalization` is handled by the `PriceScaleFactorEnumerator` in this stack. He updates and applies, the `SubscriptionDataConfig.PriceScaleFactor` to the data points, based on the dates of the underlying raw data. So the history data is independent of other subscriptions states/dates.
Tested the following algorithm and verified the logged prices match.
```
        private Symbol _symbol;
        public override void Initialize()
        {
            SetStartDate(1998, 01, 1);  //Set Start Date
            SetEndDate(2018, 1, 1);    //Set End Date
            _symbol = AddEquity("SPY", Resolution.Daily).Symbol;
        }

        public override void OnData(Slice data)
        {
            Log($"{Securities["SPY"].Price}");
        }

        public override void OnEndOfAlgorithm()
        {
            var h = History(_symbol, new DateTime(1992, 01, 01), new DateTime(2018, 1, 1), Resolution.Daily);
            foreach (var tradeBar in h)
            {
                Log($"{tradeBar.Price}");
            }
        }
```
I believe this can be close
