### ISSUE TITLE
WeekStart

### ISSUE THREAD

**Issue by Lambdac0re** [QuantConnect/Lean#1167]
Please add DateRules.WeekStart as an equivalent to DateRules.MonthStart to apart from the obvious benefit help Quantopian migration.

**Comment by DMTSource** [comment]
It might also be handy to have End versions for week and Month along with ability to offset by n_days or something similar like Q had. Someone in slack today was asking for a MonthEnd equivalent for the DateRules.

**Comment by StefanoRaggi** [comment]
This issue is addressed in PR #1389
