### ISSUE TITLE
DailyFx live mode issue

### ISSUE THREAD

**Issue by Jay-Jay-D** [QuantConnect/Lean#1169]
The problem is the [DailyFx](https://github.com/QuantConnect/Lean/blob/7b66b1ddb752d7a4c6c188c37c5d831b40d38271/Common/Data/Custom/DailyFx.cs) custom data in live mode.

At every request the provider returns a JSON with all the events for the actual date (in UTC) and as the day goes by, the fields of the JSON changes.

Every event has a `DisplayTime` field that as its name indicates, points the exact time the event is fired.
The problem is that in real time it takes some minutes for the event to update all its properties, particularly the field `better` in the JSON (property `Meaning` in the `DailyFx` class).

E.g. an event has a `DisplayTime` equal to 10:30, and it fires the `OnData(DailyFx calendar)` but at that precise moment the property `Meaning` is `None`. Two minutes later at 10:32 the `Meaning` of that event is `Better` or `Worse`, but of course, the algorithm running in live mode never realizes of that change.

To overcome this problem I made the following:

- I made a static property in the `DailyFx` class that keeps track of the previous values, is a `Dictionaty<string, DailyFx>`
- If the latest JSON has a change in the `Meaning` property, I update the `DisplayTime` to UtcNow

**But the updated event doesn't fire the `OnData(DailyFx calendar)`.**

[Here]( https://gist.github.com/Jay-Jay-D/c0d4d405e3320db1f3b2982dcf3d388a) is the modified `DailyFx` I used for debugging in live mode with an Oanda paper account.

You’ll see in the `GetSource` method I used a pair of JSON files with a modified event, the first file is called two times and the second one time and should make the time update. Also there are two `Debug.Assert` to check the event is correctly updated.

The files are available [here](https://drive.google.com/uc?export=download&id=0B9-kA56h5JCMbjJ5bURZVkt5WTA) and [here](https://drive.google.com/uc?export=download&id=0B9-kA56h5JCMbjJ5bURZVkt5WTA). Please note I use to testing the 2017-09-28, so in order to test it correctly in future days, you’ll should update the `DisplayDate` field.

**Comment by jaredbroad** [comment]
Second issue is that the factory object is being re-created every resolution step. Ideally the factory is created once when the enumerator stack is formed.

**Comment by jaredbroad** [comment]
Fixed in commit 4c2a2087bab8dc23bd7975a7f4516d692deea74b
