### ISSUE TITLE
Docker Error : Step 3/5 : COPY ./Launcher/bin/Release /root/Lean/Launcher/bin/Release lstat Launcher/bin/Release: no such file or directory

### ISSUE THREAD

**Issue by shafaypro** [QuantConnect/Lean#1173]
Hi there, 
I have been adding in the configuration for the specific in the EC2 docker service and the File is missing or somehow changed I guess.
Does anyone resolved this Issue ?

**Comment by jaredbroad** [comment]
Its not a bug; simply means you haven't got the files in that folder. Read through and understand about using docker and then copy your LEAN binaries anywhere you want in that container.

The container we provide is the environment with all the libraries etc setup so you can use LEAN. You still need to place the binaries inside.

**Comment by cromulus** [comment]
Typically, a docker workflow builds any necessary artifacts in order to run...

What's the rational for having a build step outside of the traditional docker build model? This breaks compatibility with a number of docker deployment strategies, such as dokku, heroku, etc.

**Comment by jaredbroad** [comment]
@cromulus; we don't have your algorithm. So at some point your algorithm needs to get copied into the container right? (or mounted from a volume etc) We provide the foundation but you still need to tell the container _what_ algorithm to run and _how_ you want it run (brokerage?/backtesting/live? data source?).

Currently this is:
 - Foundation (almost never needs rebuilding - 4gb).
 - Backtesting/Algorithm Binaries + Config. (constant building - 60mb).

How would you recommend this is layed out?

**Comment by cromulus** [comment]
IMHO, a volume, as you mentioned. 

All that said, this seems like more of a documentation issue than anything else.

For instance, the relationship between foundation and foundation-live, Jupyter, the standard docker container, etc.

How to run python algorithms, etc.
 
Would you all be interested in a docker documentation PR once I figure this out?
