### ISSUE TITLE
Docker Issue: Step 3/5 : COPY ./Launcher/bin/Release /root/Lean/Launcher/bin/Release

### ISSUE THREAD

**Issue by shafaypro** [QuantConnect/Lean#1174]
While using the docker to create directly through file I get Folder which is missing
Step 3/5 : COPY ./Launcher/bin/Release /root/Lean/Launcher/bin/Release
vi Dockerfile
Added the data of the Docker from the Quantconnect in the file
and then ran
docker build -t friendlyhello .

it states :  Launcher/bin/Release: no such file or directory
, so I tried to configure the docker file and uncomment the option1, I get
"caution: filename not matched: /root/Lean

The command '/bin/sh -c wget https://github.com/QuantConnect/Lean/archive/master.zip && unzip 
master.zip /root/Lean && cd /root/Lean' returned a non-zero code: 11"

and then i Tried the git solution
git clone https://github.com/QuantConnect/Lean
Then opened the folder and then again ran the docker , still got the same.

**Comment by jaredbroad** [comment]
Closing as duplicate.
