### ISSUE TITLE
Handle more cases in ResolveConsolidator

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#12]
Make an indicator consolidator for when the data is custom, but extends a TradeBar (so still has OHLC).

Update the ResolveConsolidator in QCAlgorithm to accept/search for this Custom : TradeBar data

**Comment by mchandschuh** [comment]
We need to support consolidation of BaseData (time-value pairs), dynamic trade bar data (such as Quandl) with and without volume, and also tick consolidation.

**Comment by mchandschuh** [comment]
721ecf3 updates ResolveConsolidator to use TickConsolidator and BaseDataConsolidator. DynamicDataConsolidator coming soon to a QC near you!

**Comment by mchandschuh** [comment]
ef04c41 adds the DynamicDataConsolidator

These changes should allow the indicators to work with any custom data.
