### ISSUE TITLE
Desktop charting problem

### ISSUE THREAD

**Issue by taylerallen6** [QuantConnect/Lean#1204]
Hey, I am having trouble charting the desktop version of LEAN in visual studio 2017. I followed all the steps in the "Using a Desktop User Interface" video at https://www.quantconnect.com/tutorials/desktop-charting-with-lean/ but I am still getting an error.

This is the error I am getting:

Exception thrown: 'System.ComponentModel.Win32Exception' in System.dll

An unhandled exception of type 'System.ComponentModel.Win32Exception' occurred in System.dll

The system cannot find the file specified

'QuantConnect.Lean.Launcher.exe' (CLR v4.0.30319: QuantConnect.Lean.Launcher.exe): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Remote Debugger\x64\Runtime\Microsoft.VisualStudio.Debugger.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.

It also highlights line 103 in file Quantconnect.Lean.Launcher which says "Process.Start(info);"

These are my config settings:
1. "environment": "backtesting-desktop",
2. "algorithm-type-name": "BasicTemplateAlgorithm",
3.  "job-user-id": "#####",
4.  "api-access-token": "######....####",

Has anyone else had this problem?

**Comment by taylerallen6** [comment]
I figured out the problem. I changed "desktop-exe": "../../../UserInterface/bin/Debug/QuantConnect.Views.exe" to "desktop-exe": "../../../UserInterface/bin/Release/QuantConnect.Views.exe" in the config.json file.

 

There is a better explain here:

https://groups.google.com/forum/m/#!topic/lean-engine/vnE-tXRMKo0

And here:

https://www.quantconnect.com/forum/discussion/2429/error-running-lean-python-module

**Comment by jaredbroad** [comment]
Thanks for posting solution back @taylerallen6.
It depends on whether you build it in release or debug mode

**Comment by kievking** [comment]
I have QuantConnect.Views.exe in ../../../UserInterface/bin/Debug/
but the problem persists

**Comment by jaredbroad** [comment]
@kievking change the path to the location of your desktop build. If there is no desktop executable then it's not building for some other reason. All of this will be deprecated and removed soon we're just looking for the right person to build the electron application =)

Any user / application specific issues should be posted to the [LEAN Discussion Forum,](https://quantconnect.com/forum/discussions/1/lean) not the Github issues list which is generally for systematic issues.

**Comment by kievking** [comment]
@jaredbroad I think this software isn't built for mac. it's so many problems.
