### ISSUE TITLE
Consider adding packages Microsoft.Tpl.DataFlow Rx-Core Rx-Linq Rx-Interfaces

### ISSUE THREAD

**Issue by dpavlenkov** [QuantConnect/Lean#123]
They make concurrent programming easier.

**Comment by dpavlenkov** [comment]
I wonder that while in backtesting  and warmup mode, engine may run away forward in time while algorithm does some background work. I suppose that limits the applicability of concurrent blocks in these libraries, but as a way to organize code and make it concurrent ready, they are pretty good. So if someday you add async hooks to algorithm, they'll work splendidly.

**Comment by jaredbroad** [comment]
Are the libraries above cross platform? (Mono 3.12+ support and OS friendly license needed for integration)

**Comment by dpavlenkov** [comment]
I know they have portable libraries. They have microsoft license, don't
know anything about it's friendliness. If used, it seems better to install
Rx-Main, it includes everything Rx.

**Comment by Martin-Molinero** [comment]
Hi! thanks for the suggestion! In the current implementation, the data feed stack and historical requests are already fetched in parallel using a lazy weighted scheduling, with a set of workers (where the quantity is determined by the system's capacity). Closing for now.
