### ISSUE TITLE
Visual Basic Compatibility with Mono

### ISSUE THREAD

**Issue by nii236** [QuantConnect/Lean#125]
After  a fresh clone, I get this error in Xamarin Studio. Is LEAN compatible with .NET 4.5? Does Visual Basic play nice with Mono?

![Error](http://puu.sh/iCTKj/3ce01a1ae1.png)

**Comment by jaredbroad** [comment]
Hey @nii236, mono does but not MonoDevelop at the moment: see this issue we had with adding the Visual Basic project: https://github.com/travis-ci/travis-ci/issues/4107

Known bug in Xamarin,
https://bugzilla.xamarin.com/show_bug.cgi?id=29982
