### ISSUE TITLE
AlgoSeek Error

### ISSUE THREAD

**Issue by yellowandy** [QuantConnect/Lean#1261]
In AlgoSeekOptionsReader.cs within the moveNext method there's a logical error:  

Lean/ToolBox/AlgoSeekFuturesConverter/AlgoSeekFuturesReader.cs

Should be: while (tick == null && (line = _streamReader.ReadLine()) != null)

It's currently reversed so every other tick gets skipped.  I'll try to put in a pull request later.

**Comment by andrewhart098** [comment]
(facepalm)...

Nice catch @yellowandy

**Comment by jaredbroad** [comment]
Time to start up the beowulf cluster again....

**Comment by yellowandy** [comment]
It happens, I've done way worse in the past :)

Andreas
