### ISSUE TITLE
Inaccurate holdings for oanda?

### ISSUE THREAD

**Issue by p9raffi** [QuantConnect/Lean#1291]
I'm not sure if/how my own code could be affecting this. It is occurring on an oanda practice account. Please advise.

![holdings](https://user-images.githubusercontent.com/8428678/32505814-17137b2e-c3b1-11e7-9823-cc2dfee042ce.png)

**Comment by StefanoRaggi** [comment]
@p9raffi,
it's hard to tell by seeing only this screenshot, a few questions to help diagnose the issue:
1. is this a `v1` or `v20` account ? (if the account code has dashes in it, it's `v20`)
2. did the account have any holdings before the algorithm started ?
2. how long has the algorithm been running ?
3. looking back in the `log.txt` file, did you notice when the position mismatch happened ?

Having a look at the complete log file should help pinpoint the issue, if possible please attach it here removing confidential information or send an email to support@quantconnect.com

**Comment by p9raffi** [comment]
Thanks for the reply.

1. It's a V20 account
2. No holdings before the algorithm started
3. Has been running for almost 24 hours
4. Sent an email to support. Strategy code included is of course what is running. I've been using it as a placeholder to test things until I get my things properly set up.

**Comment by p9raffi** [comment]
Just sent oanda order activity as well via support if it will help.

**Comment by p9raffi** [comment]
Also note in the log that holdings reach +/-20000. I think the actual position sizes did not exceed +/- 10000 which is how it should be.

**Comment by StefanoRaggi** [comment]
Looking at the log you submitted, this seems to be exactly the issue of double order events we fixed last week in this PR: https://github.com/QuantConnect/Lean/pull/1271

Please check if you are running the latest version of LEAN from the master branch

**Comment by p9raffi** [comment]
I was running a version from Oct. 26th. I've pulled the latest changes and will see how things go. Thanks very much for your help. I'll have to keep an eye on the latest commits going forward.
