### ISSUE TITLE
Make a Custom Data Consolidator Which Used Time-Value Only as FallBack

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#13]
If ResolveConsolidator has no matching consolidator found which better suits the data type provided, use a BaseData consolidator which used only Time-Value which will be provided by the custom data itself.

This way indicators can be universally applied to any data types which implement BaseData.

**Comment by mchandschuh** [comment]
This was handled with the addition of the BaseDataConsolidator for issue #12
