### ISSUE TITLE
Something wrong with desktop GUI in 2.1.1.41

### ISSUE THREAD

**Issue by RebelionTheGrey** [QuantConnect/Lean#131]
Hello. I tried to run project in "GUI mode" (through the "QuantConnect.Views". It worked normally in 2.1.1.39 (I saw strategy debug info in WinForm window), but didn't work well in 2.1.1.41 - see no information in the window. 
When I tried to look the reason, I saw that 

while (_resultsHandler.Messages.TryDequeue(out message)) 

returned message as null each loop time.

Console version works fine.

**Comment by jaredbroad** [comment]
From version .41 onwards you can set the "environment" configuration to choose between "backtesting" setup parameters and "desktop" settings. 

If you change the "environment" setting to "desktop" it should fix your issue.
