### ISSUE TITLE
Update GDAX fee structure for non-BTC securities.

### ISSUE THREAD

**Issue by wayneadams** [QuantConnect/Lean#1314]
https://github.com/QuantConnect/Lean/blob/517fdd85371732c2267c811bc1e3ee9c419c2f3f/Common/Orders/Fees/GDAXFeeModel.cs#L38

The fees for ETH and LTC start at 0.3% instead of the 0.25% that BTC starts at. [See here](https://www.gdax.com/fees/LTC-USD).

I may pick this up later this week.

**Comment by StefanoRaggi** [comment]
@wayneadams Good catch! Thanks for reporting the bug

**Comment by jaredbroad** [comment]
Fixed in #1316

**Comment by wayneadams** [comment]
So fast! I love you guys.
