### ISSUE TITLE
Specify file paths for config and output files

### ISSUE THREAD

**Issue by p9raffi** [QuantConnect/Lean#1330]
Currently, with the exception of transaction logs, the path to any kind of output appears to be hard-coded to the current directory of QuantConnect.Lean.Launcher.exe. Even then, the transaction logs path must be specified within config.json. Additionally, the path to config.json is also fixed.

Being able to pass in various paths from the command line would make things a lot more flexible in that project management would be easier and external code could have control over where things go and what they are named. This could be used for keeping track of outputs associated with individual backtests, as well as other things.

The current list of files that it would be useful to have command-line arguments for:

Configuration File
Backtest Results
Live Results (this would be a path only)
Transactions Log
Backtest Log File

**Comment by jeffneuen** [comment]
I would second this as being pretty important for those running Lean in a docker container. If I understand the current workflow properly, when you build the Docker container, the build copies Lean/Launcher/* into the container, and runs QuantConnect.Lean.Launcher.exe from inside the container. After the container is run and the backtest is completed, backtest result .json fuel is then dropped into Lean/Launcher in the container, and then you're stuck with results trapped inside the container filesystem.

It seems like if it was possible to specify the location of config.json, that would save a lot of container rebuilds on every edit of that one file. You could mount the volume when you launch the docker container.

Additionally, if if was possible to specify the location of the backtest output .json file, it would make it much easier to get the backtest results outside of the container via volume mounting on container launch.

Maybe there are already ways to do this that I'm missing.
