### ISSUE TITLE
Create List of All (Active) Securities in Algorithm

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#1331]
Universes serve the union of multiple universes to the algorithm. The universes have different names and contents. It can be tricky to know *what* the algorithm is getting.

Could also be Security.InUniverse? So people can do Securities.Values.SelectAll(x => x.InUniverse)

https://www.quantconnect.com/forum/discussion/2915/how-can-i-log-a-list-of-my-subscribed-universe/p1/comment-8992

**Comment by mchandschuh** [comment]
@jaredbroad  -- does the `ActiveSecurities` collection address this sufficiently?

https://github.com/QuantConnect/Lean/blob/9a676491c15df81d09eecd7deeaf3462d264404e/Common/Securities/UniverseManager.cs#L43

**Comment by jaredbroad** [comment]
Yes! Closed by #2081
