### ISSUE TITLE
Add NLTK library to whitelist of python libraries

### ISSUE THREAD

**Issue by Custos123** [QuantConnect/Lean#1349]
Hi,
it would be quite useful to be able to use NLTK for NLP purposes. Please add to whitelist of python libraries.

best regards

**Comment by AlexCatarino** [comment]
Link to the [NLTK](http://www.nltk.org/) library.
We need to add it to the list of libraries in the [foundation](https://github.com/QuantConnect/Lean/blob/master/DockerfileLeanFoundation#L22) dockerfile and add a test in the [PythonPackageTestAlgorithm](https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/PythonPackageTestAlgorithm.py).
Here is a recent PR from @DMTSource that implements a third-party library: #1304 

It would be great if a working algorithm could also be added!

**Comment by AlexCatarino** [comment]
PR #1526 does *not* close this issue, because we need to add a test in the [PythonPackageTestAlgorithm](https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/PythonPackageTestAlgorithm.py).

**Comment by AlexCatarino** [comment]
Closed by #1609
