### ISSUE TITLE
Can't build Lean on docker / Ubuntu

### ISSUE THREAD

**Issue by jasantunes** [QuantConnect/Lean#1354]
# Problem

Can't build Lean using the docker files or even modifying the commands to match the README instructions for linux.

# How to reproduce

Trying to build Lean using docker (or Ubuntu-based OS):
```
docker build -t quantconnect/lean:foundation -f DockerfileLeanFoundation .
docker build -t quantconnect/lean:algorithm -f Dockerfile .
```

Or more specifically:
```
mono nuget.exe restore QuantConnect.Lean.sln -NonInteractive
xbuild QuantConnect.Lean.sln
```

These commands fail with several errors, from nuget version (2.8) being incompatible while some of the packages (requires > 2.12) to `MSBUILD: error MSBUILD0004: Too many project files specified` and 5 build errors (which I'll show up next)

Ultimately, I was able to use the linux native `nuget restore` command, but the `xbuild QuantConnect.Lean.sln` still fails with: 
```
Errors:

/root/Lean/QuantConnect.Lean.sln (default targets) ->
(Build target) ->
/root/Lean/Algorithm/QuantConnect.Algorithm.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

	QCAlgorithm.Python.cs(475,13): error CS1502: The best overloaded method match for `QuantConnect.Algorithm.QCAlgorithm.RegisterIndicator(QuantConnect.Symbol, QuantConnect.Indicators.IndicatorBase<QuantConnect.Data.Market.IBaseDataBar>, QuantConnect.Resolution?, System.Func<QuantConnect.Data.IBaseData,QuantConnect.Data.Market.IBaseDataBar>)' has some invalid arguments
	QCAlgorithm.Python.cs(475,39): error CS1503: Argument `#2' cannot convert `QuantConnect.Indicators.FilteredIdentity' expression to type `QuantConnect.Indicators.IndicatorBase<QuantConnect.Data.Market.IBaseDataBar>'
	QCAlgorithm.Python.cs(495,13): error CS1502: The best overloaded method match for `QuantConnect.Algorithm.QCAlgorithm.RegisterIndicator(QuantConnect.Symbol, QuantConnect.Indicators.IndicatorBase<QuantConnect.Data.Market.IBaseDataBar>, QuantConnect.Resolution?, System.Func<QuantConnect.Data.IBaseData,QuantConnect.Data.Market.IBaseDataBar>)' has some invalid arguments
	QCAlgorithm.Python.cs(495,39): error CS1503: Argument `#2' cannot convert `QuantConnect.Indicators.FilteredIdentity' expression to type `QuantConnect.Indicators.IndicatorBase<QuantConnect.Data.Market.IBaseDataBar>'

/root/Lean/QuantConnect.Lean.sln (default targets) ->
(Build target) ->
/root/Lean/Brokerages/QuantConnect.Brokerages.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

	Fxcm/FxcmBrokerage.cs(170,60): error CS0117: `com.fxcm.messaging.util.IConnectionManager' does not contain a definition for `APP_INFO'

	 42 Warning(s)
	 5 Error(s)
```

Any ideas on how to build this successfully?

**Comment by andrewhart098** [comment]
@jasantunes - You have a build error which states that you are not using the `RegisterIndicator` method correctly.  Could you provide an example of how you are using the `RegisterIndicator` method? Without using docker, can you build your code without errors?

**Comment by jasantunes** [comment]
@andrewhart098 forgot to mention. I'm trying to build master.

**Comment by andrewhart098** [comment]
Ok, thanks. While we work on a PR to fix this, please take a look at this solution: https://groups.google.com/forum/#!topic/lean-engine/Ul9S2lSCgq8

**Comment by StefanoRaggi** [comment]
@jasantunes I just tested building LEAN on a fresh Ubuntu 17.10 installation and had no xbuild errors with the latest master sources following the instructions here:
https://github.com/QuantConnect/Lean/blob/master/readme.md

There was a small change required in the LEAN instructions for Linux, updated in this PR:
https://github.com/QuantConnect/Lean/pull/1386/files

**Comment by jasantunes** [comment]
@StefanoRaggi please don't close this. Let me give you a couple reasons:

1. The updated instructions you mention are for Ubuntu 17.10 and not the provided Dockerfile, which is based on `phusion/baseimage:0.9.22` (a docker-optimized version of Ubuntu 16.04). Unfortunately, there's no `phusion/baseimage` for Ubuntu 17.10 and running a full fledged Ubuntu OS inside docker is not really feasible, so I couldn't confirm that it builds on Ubuntu 17.10.

2. Even using the instructions you mentioned, I'm still getting the same errors on `phusion/baseimage:0.9.22`/Ubuntu 16.04.

At best, the Dockerfile needs to be fixed/updated, which is what I'm trying to help with.

Can anyone here successfully build `master` on Ubuntu 16.04? And if so, could you provide the updated instructions?

Thanks!

**Comment by StefanoRaggi** [comment]
@jasantunes Ok, thanks for the help, sorry I misunderstood the original issue: building LEAN _inside_ a docker container.
The provided Dockerfile was actually meant to only run LEAN (the binaries are prebuilt and copied from the host machine), so it seems it is currently configured to _run_ LEAN but not to _build_ it.

About the updated instructions you are correct, those were only tested on Linux, without using docker.

**Comment by jaredbroad** [comment]
Ah understood now @jasantunes -- this isn't a bug :) The container contains just enough to run lean not build it. Containers have to be small as possible.

You should ideally copy the LEAN executables into them and re-build; or mount a directory with the exe's built and run them from inside the container. If you're set on building in the container you can also edit the dockerfile to add a builder installs line.
