### ISSUE TITLE
The requested warmup period is too large. Warmup requests are limited to 100,000 points in total.

### ISSUE THREAD

**Issue by malylemire1** [QuantConnect/Lean#1356]
Hi,

Since warmup now seems to be limited, can you add resolution parameter to setwarmup method?
I need my live algorithm to be process at second resolution but the warmup phase can be at minute resolution.

I need 30 days of warmup.

Thanks

**Comment by Maly-Lemire** [comment]
Added a PR :
https://github.com/QuantConnect/Lean/pull/1358

**Comment by jaredbroad** [comment]
Merged in #1358
