### ISSUE TITLE
Error during Log In using VisualStudioPlugin

### ISSUE THREAD

**Issue by kujo23** [QuantConnect/Lean#1357]
Hello,

I've installed QC visual studio plugin on my Visual Studio 2017 Community Ed (Win10). However, when I'm trying to log in (enter my user id and access token, click Log In), I receive an error:
"Could not load file or assembly 'QuantConnect.Configuration, Version=2.4.0.1, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified."

Am I doing something wrong?
Thanks.
Pavel

**Comment by Jay-Jay-D** [comment]
It says it can find an assembly that must be there after building the solution. 

Have you built the complete solution first?

**Comment by StefanoRaggi** [comment]
Building the solution first and installing the build output VSIX file worked for me (VS2017 Community)

**Comment by jaredbroad** [comment]
Could not repeat
