### ISSUE TITLE
SetHoldings Submits Orders Less than Lot Size

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#1365]
SetHoldings should be smart enough to not submit a trade when the order is less than a lot size.

**Comment by AlexCatarino** [comment]
In the `BasicTemplateAlgorithm`, if we set cash to $161, `CalculateOrderQuantity` returns zero, since:
```
var orderQuantity = targetOrderValue / unitPrice;   // = 0.99
orderQuantity -= orderQuantity % security.SymbolProperties.LotSize;   // = 0.00
```
Under [this condition](https://github.com/QuantConnect/Lean/blob/master/Algorithm/QCAlgorithm.Trading.cs#L904), no order is placed.

**Comment by jaredbroad** [comment]
Thanks @AlexCatarino
