### ISSUE TITLE
Add tensorforce to supported python libraries

### ISSUE THREAD

**Issue by Custos123** [QuantConnect/Lean#1369]
Tensorforce is a reinforcement learning library of tensorflow. http://tensorforce.readthedocs.io/en/latest/index.html

Please add to whitelist of python libraries, as this would allow reinforcement learning.

**Comment by AlexCatarino** [comment]
PR #1526 does *not* close this issue, because we need to add a test in the [PythonPackageTestAlgorithm](https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/PythonPackageTestAlgorithm.py).

**Comment by AlexCatarino** [comment]
Closed by #1609
