### ISSUE TITLE
Expose RealTimeEvent Handler to Algorithm

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#137]
Added a method AddScheduledEvent which passes the events through to the RealTime handlers and can trigger events at specific times in the algorithm. 

Each day a setup function is called to determine the DateTime value for the event trigger. These setup functions could be made into a static helper (like Field.Close)

The RealTime handlers will need to be extended to handle multiple re-fire of the same events over a day:: or an intraday eventhandler will need to be copied for all the times its intended to be triggered.

Example setup helpers could be:
 - Every 30mins on week days 
 - Daily at 2pm
 - 20mins after market open

Signature for the method:
AddScheduledEvent(Func<DateTime, bool> dates, Func<DateTime, DateTime[]> times, Action callback)

Add helpers static class to QCAlgorithm:
Schedule.Date.EveryWeekDay
Schedule.Date.EveryDay
Schedule.Dates.Specific(DayOfWeek)
Schedule.Times.At(TimeSpan)
Schedule.Times.Every(TimeSpan)

Steps:
1. Make QCAlgorithm API method, save schedule events to internal collection. Lock the collection after initialize with the _locked boolean.
2. Update RealTimeEventHandlers to take collection of user events.
3. Every time RealTimeEvents Setup date -- process the user functions to determine to add the scheduled event

```
//User facing API:
AddScheduledEvent(Schedule.Dates, Schedule.Times, callback);

//Example helper function implementations:
            Func<DateTime, bool> dateFilter = dt =>
            {
                if (dt.DayOfWeek == DayOfWeek.Sunday || dt.DayOfWeek == DayOfWeek.Saturday)
                {
                    return false;
                }
                return true;
            };

            Func<DateTime, DateTime[]> realTimeEvent = dt =>
            {
                // every weekday at noon
                return new []{dt.Date.AddHours(12)};
            };
```

**Comment by naicigam** [comment]
Quartz.NET (http://www.quartz-scheduler.net/) implements a very flexible
scheduler.
If we can't integrate it in Lean (I don't know what the rules are to
integrate third-party libraries), at least we can get some ideas on how to
implement it.

**Comment by dcchsieh** [comment]
FluentScheduler is another library that could be useful (https://github.com/jgeurts/FluentScheduler) from experience it's relatively lightweight.

**Comment by jaredbroad** [comment]
Cool I'll check them out. Its currently 90% implemented -- we already have working real-time events which are also modeled/fast-forwarded in backtesting, they just aren't exposed to the user/algorithm logic. This change is more about exposing the current real-time system to the user through a powerful and easy API.

**Comment by bizcad** [comment]
I have worked with quartz in the past and I hated it.  It is very difficult to get working properly.  I cannot recommend it.

**Comment by jaredbroad** [comment]
Interesting.. I propose the main reason we need to implement our own solution (or extend our current system to handle user events) is because we need to model events in backtesting, all the libraries suggested can't handle "virtual" time in a backtest..

**Comment by jaredbroad** [comment]
Completed in #293fc12
