### ISSUE TITLE
Problems with equity Tick resolution.

### ISSUE THREAD

**Issue by Maly-Lemire** [QuantConnect/Lean#1380]
- I used to get close price when Security.Exchange.ExchangeOpen was false in Second resolution. But in Tick resolution, it's never set to false.
- EMA values are always 0. EMA(Symbol, 14, Resolution.Daily, x => ((TradeBar)x).Volume)). Tried it with ((Tick)x).Quantity) and received System.ArgumentNullException: Received type of TradeBar but expected Tick. It's normal since it use Daily resolution but it should not always return 0.
- HistoricalData does not seem to work. The new SetWarmup method SetWarmup(TimeSpan.FromDays(30), Resolution.Minute) return System.ArgumentNullException: Received type of TradeBar but expected Tick

- RSI seems to work fine and return proper values. RSI(Symbol, 14, MovingAverageType.Exponential, Resolution.Minute)

**Comment by AlexCatarino** [comment]
@Maly-Lemire, I answered the [thread](https://www.quantconnect.com/forum/discussion/3028/securityexchangeexchangeopen-never-false-in-tick-resolution) you opened in the community forum about the ExchangeOpen issue. I couldn't reproduce it.
The other questions are not verified bugs, so I will close this issue. 
Please share your code in the aforementioned community forum thread or support@quantconnect.com.

**Comment by malylemire1** [comment]
Thanks, I'll try to provide a sample project to illustrate the problems.
