### ISSUE TITLE
Add Bar Indicators to Charts in results

### ISSUE THREAD

**Issue by ebengtso** [QuantConnect/Lean#1383]
ChartPoint used by Result Handler of engines need to have Open,Low,High,Close,so that we can create candle charts

Below is a snippet of current values, but we need more data
`{"Strategy Equity":{"Name":"Strategy Equity","ChartType":0,"Series":{"Equity":{"Name":"Equity","Unit":"$","Index":0,"Values":[{"x":1483246800,"y":10000.0},{"x":1483333200,"y":10000.0},{"x":1483398060,"y":10000.0},{"x":1483401540,"y":10000.0},{"x":1483405500,"y":10000.0},`

**Comment by jaredbroad** [comment]
Thank you for the issue; unfortunately there are physical limits to the size of the data we can store and realistically transfer. Users do massive backtests so we save as much as possible while still making the charts friendly to use.

Long term we have plans to build a resampling engine to dynamically calculate the smaller versions based on high resolution data; this is technically quite challenging once you reach scale. Parsing and sampling millions of points is not something you can do that quickly... even on high end machines!

So for now this is the trade off. If you want to build around it you can manually sample more points easily by just calling "Plot()" with a reference to the strategy equity plot or whatever other plot you're trying to draw.
