### ISSUE TITLE
Problems with DockerfileJupyter

### ISSUE THREAD

**Issue by layssi** [QuantConnect/Lean#1384]
1) Problem with pythonnet on line:     pip install jupyter git+https://github.com/QuantConnect/pythonnet
I get     error: option --single-version-externally-managed not recognized
This is a problem with pythonnet: https://github.com/pythonnet/pythonnet/issues/555
My Workaround was  clone pythonnet and install with:  
**python setup.py bdist_wheel** 
https://github.com/pythonnet/pythonnet/wiki/Installation
This installed it but still complained

2) On line 26: COPY ./Jupyter/bin/Debug ${LEAN} . The folder " ./Jupyter/bin/Debug" does not exist

3) You might need to add "EXPOSE 8888"

4) After doing all this and running jupyter, I still got the error : 
_**ImportError: No module named clr**_

Any help woulb be appreciated;
Ubuntu 16.04

**Comment by AlexCatarino** [comment]
@layssi , Just made a PR that fixes the issue. We just need to add the `--egg` flag.
