### ISSUE TITLE
Add PyTorch Pyro Machine Learning Libraries

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#1385]
http://pytorch.org/

http://pyro.ai/

**Comment by AlexCatarino** [comment]
PR #1526 does *not* close this issue, because we need to add a test in the [PythonPackageTestAlgorithm](https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/PythonPackageTestAlgorithm.py).

**Comment by AlexCatarino** [comment]
Closed by #1609
