### ISSUE TITLE
Create Smart Pricing Framework Execution Module

### ISSUE THREAD

**Issue by isobretatel** [QuantConnect/Lean#1414]
This feature gives big advantage in options trading:

> Smart Pricing
> In the example above, you may have noticed no price was specified. Alta5's Smart Pricing feature automatically calculates the optimal price(s) when opening opportunities. This is particularly useful when opening an option or spread opportunity as Smart Pricing will automatically attempt to fill at prices between the bid/ask spread.
> 
> For example, suppose you wanted to open a call option opportunity and the bid price is 
> $1.20
>  and the ask price is 
> $1.45
> . Smart pricing will automatically try multiple timed limit orders between the bid/ask prices (e.g. 
> $1.25
> , 
> $1.30
> , 
> $1.35
> , etc) until the order fills.

**Comment by jaredbroad** [comment]
For interactive brokers this could be the adaptive algorithm order type. 
Generically it could be a great execution model for the framework.

Sadly closing as we cannot create issues for every execution algorithm to implement. 
We can reopen when having more bandwidth to execute the feature.
