### ISSUE TITLE
Investigate currency unit discrepancies in various models

### ISSUE THREAD

**Issue by mchandschuh** [QuantConnect/Lean#1418]
#### IOrderFeeModel
The `IOrderFeeModel` documentation clearly states that order fees are to be returned in unit of the account currency. Likewse, the `Order.GetValue(Security)` documentation states the same requirement. Upon a quick glance, it appears no `IOrderFeeModel` implementations actually guarantee that we convert to the account currency before returning the fees. This is paramount in accurate modeling of any securities with a non-account currency quote currency (mostly forex/cfd/crypto).

#### ISecurityMarginModel
The security margin model is used in such a way that it requires the results from certain methods to be in the same units under similar conditions. Specifically, the `GetInitialMarginRequiredForOrder` and `GetMarginRemaining` are expected to be in the same units as they're directly compared in `SecurityTransactionManager.GetSufficientCapitalForOrder`. This hidden coupling provides an argument for moving sufficient capital checks *into* the margin models themselves, which would make the units dependency between methods much more explicit while also potentially reducing the overall interface size.

#### The Big Picture
The issue of managing currency *units* in the code is becoming increasingly burdensome and error prone. I'm beginning to think that such implementations should return a `Cash` object (or similar) which would indicate an amount, the currency unit used, as well as a conversion to the account currency. This would remove the ambiguity while also allowing implementations to require fees be paid with certain currencies. I think this new pattern could effectively be applied anywhere we're returning opaque price data from models. Off the top of my head this includes `IOrderFeeModel` and `ISecurityMarginModel` -- possibly even `IMarginCallModel`.

##### Honorable Mention
Another issue noted was that margin calculations always seem to view all currencies as equivalent, but many brokerages aren't as kind as IB and actually require you to have the proper currencies available. Still, even other brokerages require paying fees in specific currencies (sometimes the quote currency and other times the account currency). Our model interface definitions and invocation patterns should be robust enough to support these cases, preferably by burying the technical details in the implementations of specific models themselves, thereby preventing the leaky abstraction.

**Comment by jaredbroad** [comment]
Closing as 99% complete. Missing fees on currency conversions for internal transactions.
