### ISSUE TITLE
Delayed Market Open on Holidays

### ISSUE THREAD

**Issue by andrewhart098** [QuantConnect/Lean#1436]
Currently, the market-hours-database.json includes a section for the 'holidays' of an exchange.  The format of the holiday [is expected to be "M/d/yyyy"](https://github.com/QuantConnect/Lean/blob/45abca89fe5d676820d6cdfb2f8220bc52a664b3/Common/Util/MarketHoursDatabaseJsonConverter.cs#L181) and represents a binary decision about whether an exchange trades on a particular UTC date. This is problematic because holidays can sometimes mean a delayed UTC opening for a particular security. For example, the [FXCM holidays for 2017](https://fxtrade.oanda.com/community/forex-forum/topic/54018365/) indicates that on 12/25/2017, trading begins at 18:00 EST for some securities. I do not believe that Lean can handle this situation.

I believe the fix would be for holidays to be represented as something similar to a `MarketHoursSegment` which includes information about the start and end times of trading for a day.

**Comment by mchandschuh** [comment]
One thing, the dates in that file are time zone specific to the exchange.

**Comment by AlexCatarino** [comment]
This issue is not reproducible with an algorithm because there are no files from days like Christmas. Maybe those days are cut off during processing. (cc @Jay-Jay-D) and, consequently, we need to include them first.
