### ISSUE TITLE
Py Bug: "Post-Only" GDAX Order Property Doesn't Work Live

### ISSUE THREAD

**Issue by Haumed** [QuantConnect/Lean#1447]
The following python code, when added to Initialize(), stills executes with fees sometimes during Live usage:
```python
DefaultOrderProperties = GDAXOrderProperties()
DefaultOrderProperties.PostOnly = True
```

**Comment by Haumed** [comment]
I solved the issue, `DefaultOrderProperties` should be `self.DefaultOrderProperties`. There is a reference to it in the API but no documentation.

Lines 45-59 need to be fixed in this file:

https://github.com/QuantConnect/Lean/blob/dccbf635c806b6046bafb2494c6cd8603dbe6d63/Algorithm.Python/FinancialAdvisorDemoAlgorithm.py#L45

**Comment by jaredbroad** [comment]
Nice @Haumed! Thanks for the catch -- submitted a PR. If you want a QC t-shirt send us your address and size and we'll ship one out to you =)
