### ISSUE TITLE
Bug: GDAX Orders Get Lost in Live Trading

### ISSUE THREAD

**Issue by Haumed** [QuantConnect/Lean#1448]
My live GDAX algorithm has been losing track of orders, and when it can no longer cancel a lost order using `self.Transactions.CancelOpenOrders(symbol)` (Py) the money is frozen and the algorithm stops trading it. At current trading speeds this happens within a few hours.

I believe it might have something to do with how GDAX splits up orders that are partially filled.

**Comment by jaredbroad** [comment]
Please post algorithm, logs and examples; enough information we can repeat the issue and debug it. The above description isn't quite enough. The orders are never "lost" so perhaps you can explain what you mean by "no longer cancel a lost order" ?

**Comment by Haumed** [comment]
Sure, I'll try to get better logs next time and will see if I can reproduce it consistently.
