### ISSUE TITLE
OnData bar time has changed

### ISSUE THREAD

**Issue by bizcad** [QuantConnect/Lean#145]
When the first entry in a minute back test data file is 34200000, that is 34200 seconds after midnight or 9:30 AM.  In the open source version of Lean (which I updated to today), the OnData(TradeBars data) event is now reporting that data.Time is 14:31 or 1:31PM.  In previous versions data.Time was 9:31.  

I understand that the 1 minute difference is because it reports the Close of the bar.

The data.Values[x].EndTime is 9:31;

**Comment by bizcad** [comment]
More information

In FileSystemDataFeed.Run, by the time you hit this point. (on line 211)
<pre>
var time = timeSlice.Time;
var newData = timeSlice.Data;
</pre>
timeSlice.Time is set to UTC (14:40). 
timeSlice.Data is still NewYork time (9:30)

So later on (line 314 in my current version) when you 
<pre>
 //Trigger the data events: Invoke the types we have data for:
var newBars = new TradeBars(time);
var newTicks = new Ticks(time);
var newDividends = new Dividends(time);
var newSplits = new Splits(time);
</pre>
newBars.Time is set to UTC (14:40)
So when you fire the pricing events (on line 458)
<pre>
//After we've fired all other events in this second, fire the pricing events:
try
{
     if (hasOnDataTradeBars && newBars.Count > 0) methodInvokers[typeof (TradeBars)](algorithm, newBars);
     if (hasOnDataTicks && newTicks.Count > 0) methodInvokers[typeof (Ticks)](algorithm, newTicks);
}
</pre>
and call ( on line 470)
<pre>
// EVENT HANDLER v3.0 -- all data in a single event
var slice = new Slice(time, newData.Values.SelectMany(x => x),
newBars.Count == 0 ? null : newBars,
newTicks.Count == 0 ? null : newTicks,
newSplits.Count == 0 ? null : newSplits,
newDividends.Count == 0 ? null : newDividends
);

algorithm.OnData(slice);
</pre>

the slice.Time is set to UTC.  In my humble opinion, this is not correct.  The time in the TradeBars object should be the same as the Time in each TradeBar, or to the local time at the exchange.

I did not check any of the other events fired in between the code I show here.

Cheers!
Nick

**Comment by jaredbroad** [comment]
Thank you Nick you're totally right! We recently moved everything to be sync'd on UTC in the engine, and this was a left over part of that.

If you're keen please submit a pull request for this: the changes required are in the AlgorithmManager file:

After the algorithm time has been set (https://github.com/QuantConnect/Lean/blob/master/Engine/AlgorithmManager.cs#L241)

1. Use algorithm.Time to set the slice times for Splits, Dividends, Bars and Ticks:
https://github.com/QuantConnect/Lean/blob/master/Engine/AlgorithmManager.cs#L314
                 //Trigger the data events: Invoke the types we have data for:
                var newBars = new TradeBars(algorithm.Time);
                var newTicks = new Ticks(algorithm.Time);
                var newDividends = new Dividends(algorithm.Time);
                var newSplits = new Splits(algorithm.Time);

2. Slice should also use algorithm.Time https://github.com/QuantConnect/Lean/blob/master/Engine/AlgorithmManager.cs#L470

3. Also please update the DataDictionary<> "Time" property to show a "Obsolete" message. We'll deprecate this field so people use the algorithm.Time property (duplication of data causes errors)
