### ISSUE TITLE
Unable to locate exchange hours 

### ISSUE THREAD

**Issue by maxhash** [QuantConnect/Lean#148]
By default the engine uses forex data from 'fxcm' directory. I receive the following error when I try use data from 'oanda' directory.

<code>
20150725 12:10:30 ERROR:: Error Message >> Algorithm.AddSecurity(): Unable to locate exchange hours for oanda-[null]-Forex
</code>

Where do I need to set the exchange hours?

**Comment by mchandschuh** [comment]
Hey @maxhash, have a peak at the csv files in /Data/market-hours. This is the flat file database used to initialize exchange hours for securities. There's two types of files in here. 

The important, must have, is the [market-hours-database.csv](https://github.com/QuantConnect/Lean/blob/master/Data/market-hours/market-hours-database.csv) file. This defines market hours by market/symbol/security type. The symbol is optional and can be left null to indicate it's the hours for all symbols for a given market/security type combination. Read the doc at the top of the file for information on how to add another line.

The other type of file is a holidays file. This defines the dates that a given market observes and doesn't trade. They take the format of holidays-{market}.csv. Have a peak at the [holidays-usa.csv](https://github.com/QuantConnect/Lean/blob/master/Data/market-hours/holidays-usa.csv) file.

Here's the [code](https://github.com/QuantConnect/Lean/blob/master/Common/Securities/SecurityExchangeHoursProvider.cs#L82) that loads these files for your reference.

Let me know if you get stuck on anything else! I'll close this issue for now. Thanks!

**Comment by maxhash** [comment]
Everything works now. Many thanks!

**Comment by mchandschuh** [comment]
@maxhash: I welcome a PR with the changes that got it to work, I'm sure others will run into this as well.
