### ISSUE TITLE
Json Parse Results object in backtest-desktop

### ISSUE THREAD

**Issue by Worthy7** [QuantConnect/Lean#1498]
desktop-backtest doesn't allow the results object to be parsed properly. Error that it cannot parse 1000.0 (initial cash) into an integer... it should be doing it into a decimal anyway...

**Comment by Worthy7** [comment]
A bit of googling shows this is most likely related to culture, the computers I'm using have Japanese, but the interface and language setting is in English... including the decimal point setting. I also tried settings the thread to CultureInfo.InvarientCulture, and did the same by passing it as JsonParseSettings, and neither worked. Not sure how to debug further.

**Comment by Worthy7** [comment]
Ok, This does work, it's just that:
1) The Views project always compiles into bin/Release - even with debug selected.
2) So I had to also change the path in my config.json to reference the Release folder instead.
3) The fix was to change this line in Views/DesktopClient.cs:
`var backtestResultEventModel = JsonConvert.DeserializeObject<BacktestResultPacket>(payload, new JsonSerializerSettings() { Culture = CultureInfo.InvariantCulture});`

**Comment by Worthy7** [comment]
Got that done... but I don't see any charts... at all

**Comment by jaredbroad** [comment]
Existing desktop client is deprecated and recommend dont use. We're moving to new design specified in the slack/github project list
