### ISSUE TITLE
Default MACD should be Exponential

### ISSUE THREAD

**Issue by Worthy7** [QuantConnect/Lean#1508]
According to : 
http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:macd-histogram#calculation
https://en.wikipedia.org/wiki/MACD#Mathematical_interpretation

So I propose we change the default constructors...kind of a big breaking change...
`
        public MovingAverageConvergenceDivergence(string name, int fastPeriod, int slowPeriod, int signalPeriod, MovingAverageType type = MovingAverageType.Exponential)
`

**Comment by Worthy7** [comment]
If we are going to do this (correctness etc), It might be necessary to write something to the output when the user doesn't supply the moving average type "Warning: MACD default moving average type has been changed to Exponential. Please specify the MovingAverageType.Simple parameter if you would like to revert to Simple." At least for a few weeks to allow people to switch over. 

Or, for now, provide a message alerting we will move over to Exponential type as the default from X date.

**Comment by jaredbroad** [comment]
You're right -- we'll make this change and put in some notifications.

**Comment by Worthy7** [comment]
Done and I confirm it's working correctly
