### ISSUE TITLE
Add support for hedged-options margin calculations.

### ISSUE THREAD

**Issue by isobretatel** [QuantConnect/Lean#1516]
Incorrect requirements calculation for credit spreads causes "Insufficient funds" errors.
See attached example.

[BasicTemplateOptionStrategyAlgorithm.txt](https://github.com/QuantConnect/Lean/files/1680274/BasicTemplateOptionStrategyAlgorithm.txt)

**Comment by jaredbroad** [comment]
We don't support complex option margin modelling at the moment. Will re-label as feature request to extend option margin models for hedged cases.

**Comment by bobobo1618** [comment]
I'm also running into this issue.

An easy workaround is to simply add an oversized portfolio and not use the whole thing but that makes calculating returns etc. much harder.

**Comment by Martin-Molinero** [comment]
Option strategies margin calculations are now supported.
