### ISSUE TITLE
Select Option Contracts Based on Greeks

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#1518]
Option universe selection selects on price, strikes etc now but Valery requests Option Contracts selected on Greeks / Implied Volatility. Currently these are calculated in inline -- so we don't have them available at universe selection time.

**Comment by isobretatel** [comment]
Select option contracts by Open Interest, Volume.

**Comment by nkabram** [comment]
I'd also like to see support for this. Any update?

**Comment by ikamanu** [comment]
+1 to this.
Any progress?

**Comment by kbsaravana** [comment]
+1 on this

**Comment by kfeldspar** [comment]
+1 on this too

**Comment by YukaLangbuana** [comment]
+1 on this also. How's the progress?

**Comment by mattmcwaters** [comment]
+1!

**Comment by rjmig88** [comment]
Any update on this? Running option strategies on many securities is quite slow as I want to trade a specific delta, or a specific premium, which OptionChainProvider doesn't easily allow for. 

For instance, the strikes can expand greatly in high vol/high vix eras, for instance today the $0.50 SPX put expiring in two days was the 3,500 strike with SPX trading around 4155. The market was selling these deep puts for that much premium and there would be no way I'd guess I'd have to go that deep for a $0.50 put were I to use OptionChainProvider to optimize and speed things up.

**Comment by rafael-trevisan** [comment]
Looking forward to seeing this :)

**Comment by jaredbroad** [comment]
Plan is:
 - Standardize options and futures to use universe data files like the rest of LEAN(https://github.com/QuantConnect/Lean/issues/6861)
 - Create the options universe files with the greeks precalculated and passed in as part of their filtering options.
 - Calculation of daily options universe as a LEAN Data stack job.

It's a heavy project and will require gutting thousands of lines of code but will dramatically standardize the internals of LEAN universes which is very exciting.

**Comment by jaredbroad** [comment]
Side effects of the plan:
 - Filtering will be every day instead of every minute, but it's too much churn and noise for most people so we don't think people will care really. Anyone impacted can just set a wider strike range.
 - Much faster options backtesting.

**Comment by dennis-yemelyanov** [comment]
With daily refresh will it be possible to say "at 11AM, buy the option contract that currently has delta = 0.2"?

I think it's a common scenario to find an option by delta at current moment. Delta can change dramatically intraday, especially if the option is approaching expiration, so the delta value from the beginning of the day might not be very useful in such cases

**Comment by Martin-Molinero** [comment]
Equity and index options can be selected based on greeks, creating new issue to track this functionality for FOPs https://github.com/QuantConnect/Lean/issues/8438
