### ISSUE TITLE
Make subscribing to option contracts optional

### ISSUE THREAD

**Issue by isobretatel** [QuantConnect/Lean#1519]
For my algorithm I need +20/-20 strikes.
Currently loading option contracts also means that algorithm is automatically subscribed to ALL loaded contracts. Subscription to ALL contracts is expensive and unnecessary.  
Make subscription explicit.

**Comment by jaredbroad** [comment]
The LEAN way of doing this is to use the OptionChainProvider to filter out options you want and then subscribe to the contracts using AddOptionContract.

**Comment by isobretatel** [comment]
OptionChainProvider does not provide properties like OpenInterest and LastPrice.
