### ISSUE TITLE
Old Data/Forex folder needs removing/Updating with new QuoteBar formatted data

### ISSUE THREAD

**Issue by Worthy7** [QuantConnect/Lean#1522]
BasicTemplateForexAlgorithm throws this out:

ERROR:: QuoteBar.ParseTradeAsQuoteBar(): Data formatted as Trade when Quote format was expected.  Support for this will disappear June 2017.

Here's an even simpler example:

```
    public class ForexTest : QCAlgorithm
    {
        /// <summary>
        /// Initialise the data and resolution required, as well as the cash and start-end dates for your algorithm. All algorithms must initialized.
        /// </summary>
        public override void Initialize()
        {
            SetStartDate(2014, 5, 7);  //Set Start Date
            SetEndDate(2014, 5, 15);    //Set End Date
            SetCash(100000);             //Set Strategy Cash
            // Find more symbols here: http://quantconnect.com/data
            AddForex("EURUSD", Resolution.Daily, Market.FXCM);
            
        }

        /// <summary>
        /// OnData event is the primary entry point for your algorithm. Each new data point will be pumped in here.
        /// </summary>
        /// <param name="data">Slice object keyed by symbol containing the stock data</param>
        public void OnData(QuoteBars data)
        {
            Debug("I'm here");
        }
    }
```
So this means, All forex algo's don't work right now without using Tick data or a consolidator.

**Comment by Worthy7** [comment]
Minute seems to work, Daily doesn't

**Comment by Worthy7** [comment]
It is something to do with CSVLength. It seems Minute and Hourly is length 5, and the condition to use ParseForex is > 5 (Minute is size 11).

**Comment by Worthy7** [comment]
Ok, I think this is all happening because perhaps my machine has old format daily data on it? It seems I accidentally included the data in git.

**Comment by Worthy7** [comment]
Nope, it's because this repo has old data in the fxcm/daily folder. lets delete all sample data and let the API deal with it?
Lean/Data/forex/fxcm/daily/eurusd.zip

**Comment by Worthy7** [comment]
I'm gonna extend this a little:

1) Remove all API gettable data from the repo
2) Allow users to automatically download free data, without having to add it through the checkout every time (Accept fxcm etc data agreements as flag on their account - it's not needed per every download right?)

**Comment by jaredbroad** [comment]
Closing as this is just issue with your data and not related to LEAN.

**Comment by Worthy7** [comment]
Sorry for all the spam, but the issue is the data you've left in this repository, in lean : Lean/Data/forex/fxcm/daily/eurusd.zip

This stops the Api from downloading the latest, correct version - please delete it from the repo. When the data was updated around June last year, this file should have been replaced with the new format (QuoteBar) version.

**Comment by Worthy7** [comment]
@jaredbroad  I have a pull request ready, but are we actually allowed to include FXCM's data in a repo?   It's just an update of the latest EURUSD and USDNZD, but perhaps the solution should be to delete the sample data and let the user deal with it
