### ISSUE TITLE
MACD Needs Test Data for Signal and Histogram

### ISSUE THREAD

**Issue by Worthy7** [QuantConnect/Lean#1543]
Just posting this from the forums, since it seems that it is in fact a bug:

As you can see in the code, it will only plot when it IsReady. So I expected the data to be legit, but according to TradingView, it seems it's not... The bit at the beggining is wrong, it corrects itself after a few more bars.

Imagine are small, but you get the drift:
https://cdn.quantconnect.com/forum/i/30013_1518076929.jpg
https://cdn.quantconnect.com/forum/i/30013_1518076925.jpg

Basically the beginning of the histogram looks wrong, then seems to reset or something. The other image is TradingView's histogram (I checked the settings were the same).

Here's the simple backtest:
https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_ff87ac91efc82db8cb230461c903413c.html

There are 2 main differences, at the beginning the negative part doesn't reach the 50 mark. The other is the large drop. if you clone my algo and uncomment the line to the SetWarmup and run it again, it shows that the issue is when MACD "thinks" it's ready isn't enough

- [ ]  Get a working test for MACD data

**Comment by jaredbroad** [comment]
We use test data cases for the indicators to confirm accuracy; you can see other test data here:
https://github.com/QuantConnect/Lean/tree/master/Tests/TestData

There doesn't seem to be the same test-case for MACD though -- so to make it consistent we'll need to import the test data - and create a test method like this one for [ADX](https://github.com/QuantConnect/Lean/blob/master/Tests/Indicators/AverageDirectionalIndexTests.cs#L31) -- but in the [MACD test file](https://github.com/QuantConnect/Lean/blob/master/Tests/Indicators/MovingAverageConvergenceDivergenceTests.cs#L32). 

Typically we've exported the test data from [Free Stock Charts](http://www.freestockcharts.com/platform/v1). Which I've attached here: 
[spy_macd.txt](https://github.com/QuantConnect/Lean/files/1707372/spy_macd.txt)

**Comment by Jay-Jay-D** [comment]
I made some test days ago and I used data suggested by Free Stock Charts and I found it has some issues as the indicator warms up.

Please check [this notebook](https://github.com/Jay-Jay-D/NotebookShelf/blob/master/MACDTestingDataGenerator.ipynb), there I end up generating the MACD test data using Pandas `ewm` extensions.

**Comment by mchandschuh** [comment]
@Worthy7, #1634 adds some test data from an external source and sets the default average type to exponential, but it doesn't cover the histogram property.

I think I figured out the issue. In your attached algorithm you're checking if the _histogram_ is ready instead of the MACD. Now, I think we'd both agree that the histogram shouldn't be ready until both MA's are also ready, so that's something that we could change. 

The sudden change is because in the MACD implementation we don't update the signal indicator until both the fast and slow indicators are ready, and the histogram depends on the signal, so when we finally start updating the signal we get a discontinuity. I think the right fix here is to move the `Histogram.Update` into the same if block as the fast/slow and put the histogram and signal under test.

**Comment by mchandschuh** [comment]
Updated the title to reflect the remaining portion of this issue. We need test data for the signal and histogram sub-indicators. Also, there appears to be a bug in the histogram values as described in my comment above.

**Comment by Jay-Jay-D** [comment]
`Signal` is just a EMA of MACD, in turn, MACD is just a difference between two EMA.

In the same fashion, Histogram is nothing more than MACD minus Signal.

EMA is correctly estimated by the engine, also the MACD, as you can check from [this test](https://github.com/QuantConnect/Lean/blob/master/Tests/Indicators/MovingAverageConvergenceDivergenceTests.cs).

IMO, this issue should be closed.

**Comment by mchandschuh** [comment]
The histogram is incorrect and has a discontinuity because we don't edit for the slow and fast averages to be ready before calculating the histogram, but we do wait for them to ready to start calculating the signal.
