### ISSUE TITLE
Can not run Lean on Monodevelop [Python+Ubuntu]

### ISSUE THREAD

**Issue by Sdoof** [QuantConnect/Lean#1557]
While following the instruction led to expected execution in the terminal (following change to config.json to activate Python capability) - see relevant text file, the output is corrupt and the  sample trade no longer show once executing in MonoDevelop. (2nd attachment)

ERROR:: Engine.Run():  System.Exception: Loader.TryCreatePythonAlgorithm(): Unable to import python module ../../../Algorithm.Python/BasicTemplateAlgorithm.py. PyUnicodeUCS4_FromUnicode: try re-building algorithm
[Note the rebuilding from Monodevelop did not help]

OS: Ubuntu 17.1
Python setup

Output from mono:OK
[Terminal Output: QuantConnect_Lean_Launcher_exe.txt](https://github.com/QuantConnect/Lean/files/1713587/Terminal.Output.QuantConnect_Lean_Launcher_exe.txt)

Output from Monodevelop:BUG:
[Monodelevelop - Run of Quantconnect_Lean_Launcher_sln.txt](https://github.com/QuantConnect/Lean/files/1713608/Monodelevelop.-.Run.of.Quantconnect_Lean_Launcher_sln.txt)

config.json used:
[config.json.txt](https://github.com/QuantConnect/Lean/files/1713617/config.json.txt)

Installation process:
##################
##  REMOVE & PURGE
sudo apt-get purge --auto-remove nuget
sudo apt remove --purge --auto-remove mono-runtime
##################
##  Get Mono/Nuget
sudo apt-get update
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb http://download.mono-project.com/repo/ubuntu xenial main" | sudo tee /etc/apt/sources.list.d/mono-official.list
sudo apt-get update
sudo apt-get install mono-complete
sudo apt-get update
sudo apt-get install -y nuget python-pip
sudo nuget update -self
##################
sudo apt-get install python-numpy
sudo apt-get install python-pandas
##################
git clone https://github.com/QuantConnect/Lean.git
cd Lean
sudo nuget restore QuantConnect.Lean.sln
sudo msbuild QuantConnect.Lean.sln
cd Launcher/bin/Debug
sudo mono ./QuantConnect.Lean.Launcher.exe
# change config.json to Python
cd ../../..
sudo msbuild QuantConnect.Lean.sln
cd Launcher/bin/Debug
sudo mono ./QuantConnect.Lean.Launcher.exe # Run Fine
sudo flatpak run com.xamarin.MonoDevelop ./QuantConnect.Lean.Launcher.exe # ERROR MESSAGE

**Comment by Martin-Molinero** [comment]
Hi @Sdoof, 
Sorry for the late response 😅.
We currently support and use `mono 5.12` see https://github.com/QuantConnect/Lean/blob/master/DockerfileLeanFoundation#L39, which is not the latest version.
From the output log, it can be seen `ERROR:: Engine.Run():  System.Exception: Loader.TryCreatePythonAlgorithm(): Unable to import python module ../../../Algorithm.Python/BasicTemplateAlgorithm.py. PyUnicodeUCS4_FromUnicode` for python we are using 3.6.8 in Linux see https://github.com/QuantConnect/Lean/blob/master/DockerfileLeanFoundation#L52

I think a good first step it to guarantee these versions are matching and that `Monodevelop` is using them.

More information and setup procedure can be found at https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/readme.md

Closing this issue for now, please re open if not fixed and still an issue.
