### ISSUE TITLE
got error message after new clone and new build

### ISSUE THREAD

**Issue by wanghao793** [QuantConnect/Lean#156]
![image](https://cloud.githubusercontent.com/assets/9992593/9624688/e85403ac-5103-11e5-952b-a441bda4e7cf.png)

**Comment by mchandschuh** [comment]
The Statistics computation is currently being reworked in the following issue: https://github.com/QuantConnect/Lean/issues/30. Closing this issue as it's a known problem and should be OBE with the new implementation. Thanks for submitting!

Also, this can be safely ignored. What's it's saying is that there was an extra data point in the benchmark array vs the performance array.
