### ISSUE TITLE
RollingWindow<T> enumerates in reverse time order

### ISSUE THREAD

**Issue by mchandschuh** [QuantConnect/Lean#157]
The `RollingWindow<T>` class provides a reverse time based indexing system common to trading platforms where `rollingWindow[0]` is the most recent piece of data and `rollingWindow[n]` would be the piece of data from n bars in the past.

For convenience, `RollingWindow<T> : IEnumerable<T>` but it enumerates the windows using the same indexing scheme, causing the enumeration to process backwards in time. This is not expected behavior for most, given that we typically want to enumerate chronologically, but provide indexing in reverse chronological order for the convenience of  'n bars ago'.

Are there any strong opinions in either direction here? I vote for updating the `IEnumerable<T>` implementation in `RollingWindow<T>` to perform the enumeration in chronological order.

Thoughts?

**Comment by AnObfuscator** [comment]
I really think rollingWindow[0] should give the same element as the first element given when using an enumerator. Doing otherwise will be maddeningly inconsistent, at least to me as a developer.

As a compromise, maybe offer a "ChronologicalEnumerator" method, that will always iterate according to chronological order (regardless of the order in which they are added to the window)?

Regardless, there's always the Enumerable.Reverse extension method for people who want it in the opposite direction.

**Comment by mchandschuh** [comment]
I had similar thoughts which is why I implemented it that way in the beginning. I've heard some users of the code base state it is a little unexpected to enumerate in reverse chronological order.

Would it be crazy to have the indexing use negative numbers?

window[-1] gives you the previous value, this way the indexing and enumeration would be in sync?

**Comment by StefanoRaggi** [comment]
A C# developer would expect to refer to rollingWindow[0] as the first element added to a collection, but the majority of retail trading scripting languages (NinjaScript, EasyLanguage, etc.) use the "barsAgo" pattern (rollingWindow[0] is always the current/last element of the data series).

My vote is to keep the current implementation for the indexer: it makes life easier for a strategy developer to migrate existing strategies to Lean/QC.

**Comment by bizcad** [comment]
@StefanoRaggi  +1

I vote for retaining the current barsAgo implementation for the indexer.  If the developer wants to Array notation, use an array.

While debugging, I noticed that the underlying _list<{Class}> is not in the same sequence as the indexer, particularly when the indicator !IsReady().  So trying to use the for loop in @mchandschuh comment would lead to frustration and errors.  I learned I cannot rely on looping thorough the underlying list.  I learned I have to stick to the interface.  So if I want to iterate the RollingWindow I have to use a for loop like this.
<pre>
            decimal sum = 0;
            for (int i = 0; i < Price.Count; i++)
                sum += Price[i];
            for (int i = Price.Count; i != 0; i--)
                sum -= Price[i];
</pre>

EasyLanguage and most of the other scripting languages use the [0] notation for the most recent value of the RollingWindow.  However,  the = assignment in EasyLanguage creates the new [0]th element before the assignment, like this:
<pre>
// creates rw[0], adds it to the list and 
// then assigns it the value of 42 
//  + the value of the next to last addition to the rw window.
rw = 42 + rw[1];  
</pre>

Whereas, RollingWindow.Add method creates the new element after the assignment, like this:
<pre>
rw.Add(42 + rw[1]);  // not correct
rw.Add(42 + rw[0]);  // correct
</pre>
or
<pre>
var x = 42 + rw[0];
rw.Add(x);  // correct
</pre>

**Comment by jaredbroad** [comment]
Thanks for feedback @StefanoRaggi, @bizcad, @AnObfuscator. Will leave the system in its current form as a "barsAgo" indexer.
