### ISSUE TITLE
Rework ZipCacheProvider to Stream From Disk Instead of Loading into Memory

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#1577]
Reduce memory requirements by streaming from disk.

See pull request https://github.com/QuantConnect/Lean/pull/1531

@theGOTOguy

**Comment by Martin-Molinero** [comment]
Closing for now since current `ZipCacheProvider` implementation has come a long way and `Fixes out-of-memory and Too Many Open Files errors when running Lean under Mono in Linux.` is no longer true, probably due to migrating to net core
