### ISSUE TITLE
Time.ToUniversalTime() doesn't work properly

### ISSUE THREAD

**Issue by Worthy7** [QuantConnect/Lean#1580]
![image](https://user-images.githubusercontent.com/4762399/36246101-79dd1d6e-1271-11e8-80a6-3f79c93f16f4.png)

Ignore the one in the middle, and that it says `algo.`, 

I am assuming `Time` is in EST (-5).
So UTC should be +5, 5:43am.

If you need more details let me know what.
I am JST, +9, `Algo.TimeZone` is New York.

**Comment by Worthy7** [comment]
Looks like it's unfixable because it grabs the timezone from the context. I'll have to use `UtcTime` only, can be closed unless someone know's another way.

**Comment by mchandschuh** [comment]
Please see the documentation regarding [ToUniversalTime] (https://msdn.microsoft.com/en-us/library/system.datetime.touniversaltime(v=vs.110).aspx).  It's dependent on the system configured time zone and the specified date times kind property and is completely outside of the Lean engine, so it can't take the algorithm time zone into account. 

If you want the algorithms current time in utc then the correct way is to use the UtcTime property as you mentioned above.
