### ISSUE TITLE
CashBuyingPower SetHoldings fails for GDAX

### ISSUE THREAD

**Issue by multidis** [QuantConnect/Lean#1584]
Please see a reproducible example in [this gist](https://gist.github.com/multidis/5b1f19411031fc32efd1ce5b2d9bbf25)

`SetHoldings` failure started happening following a recent `AccountType.Margin` to `AccountType.Cash` change. After [this commit](https://github.com/QuantConnect/Lean/commit/5b4a994aa0a8d65f7960fd74038ce13baa7a7f63) the issue will affect anyone using GDAX.

**Comment by jaredbroad** [comment]
ty -- @StefanoRaggi is working on it now =)

**Comment by multidis** [comment]
This fixes order validation, but does `SetHoldings` target order quantity account previous holdings? Should a similar change be applied [here](https://github.com/QuantConnect/Lean/blob/master/Algorithm/QCAlgorithm.Trading.cs#L949)?
@StefanoRaggi

**Comment by StefanoRaggi** [comment]
@multidis 
I believe this line in `GetMaximumOrderQuantityForTargetValue` should be taking existing holdings into account:
https://github.com/QuantConnect/Lean/blob/f1fd14538fdd647a973de3a5ff78466a0db1041e/Common/Securities/CashBuyingPowerModel.cs#L152

Also I just fixed a couple of bugs in #1585 and added a few new tests for `CalculateOrderQuantity`:
https://github.com/QuantConnect/Lean/pull/1585/commits/f1fd14538fdd647a973de3a5ff78466a0db1041e

Please let us know if you think there is some missing case, or if any of the new tests have incorrect expected values.
