### ISSUE TITLE
ApiConnection Class Throws on ListBacktests

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#1597]
The REST response from the API request is:
"{\"backtests\":[{\"backtestId\":\"..........\",\"name\":\"2018-02-20 14:08:02Z API Backtest\",\"note\":null,\"completed\":true,\"progress\":1,\"result\":\" \"}],\"success\":true}"

This empty result value causes an exception in the ApiConnection class TryRequest method:
{"Error converting value \" \" to type 'QuantConnect.Packets.BacktestResult'. Path 'backtests[0].result', line 1, position 160."}

Listing backtest doesn't return the results (by design) but it should just return the metadata for the backtest without throwing.

Might be an issue from an API change

**Comment by mchandschuh** [comment]
@Martin-Molinero -- is this resolved by PR #1785 ?

**Comment by Martin-Molinero** [comment]
It was actually solved by a fix done by @gaviles in the server. It was at the time I was working in PR #1785
