### ISSUE TITLE
Plot time should be StartTime, not EndTime for a point

### ISSUE THREAD

**Issue by Worthy7** [QuantConnect/Lean#1598]
To be more inline with other charting solutions, the charts should plot the time that the data point started, not ended.
For example, we receive a 1 hour bar at 3pm and plot it. In QC the chart will show the bar starting at 3pm. In other solutions it will be plotted from 2pm (to 3pm, spanning 1 hour)

I cannot work on this because it requires a change to the `Plot` function, which doesn't work in the online terminal/lab because it cannot see the other variables (_liveMode, ReservedChartSeriesNames etc) . Also desktop charting is currently under maintenance, and has a bug which is not going to be addressed soon. But in essence the fix is to: 

1. Add a DateTime parameter to `public void Plot(string chart, string series, decimal value, DateTime? dateTime = null)`
2. Set it to Utc if nothing is supplied `dateTime = dateTime ?? UtcTime;`
3. and of course use that instead at https://github.com/QuantConnect/Lean/blob/c8d207cef75fce43c4a132ef98a18102fbe1b956/Algorithm/QCAlgorithm.Plotting.cs#L204

4. Create alternative Plot functions which accept at least 

- `Indicator`
- `IndicatorDataPoint`
- `Bar`
(Any others?)

which simply pulls out the `Time` and passes it as an additional argument to the main `Plot` function.

**Comment by jaredbroad** [comment]
UtcTime is instantaneous and not related to trade bars at all.  The Time-Value pair is an instantaneous pair so plotting the current moment makes sense.

The example above "receive a 1 hour bar at 3pm and plot it." -- is not possible since charting does not support trade bar logging at this time.
