### ISSUE TITLE
[Bug] Proxy server not supported

### ISSUE THREAD

**Issue by clanghir** [QuantConnect/Lean#16]
If you use the engine behind a proxy server you could get into trouble (if you work with custom data and during statistics generation). To solve that I recommend to set the Proxy property of WebClient instances always to WebRequest.GetSystemWebProxy(). 

Example (SubscriptionDataReader.cs):

using (var client = new WebClient())
                            {
                                client.Proxy = WebRequest.GetSystemWebProxy();
                                client.DownloadFile(source, location);
                            }

**Comment by jaredbroad** [comment]
Thank you @clanghir, will look at updating it soon.
