### ISSUE TITLE
GDAX API Update: Cannot Destructure Property

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#1601]
GDAX API update today causing an exception in live running algorithms.

```
Runtime Error: System.Exception: GDAXBrokerage.OnMessage: Cannot destructure property
`product_ids_required` of 'undefined' or 'null'. Stack Trace: System.Exception:
GDAXBrokerage.OnMessage: Cannot destructure property `product_ids_required` of
'undefined' or 'null'. 
```

**Comment by jameschch** [comment]
This is a strange error. The subscribe methods have a product_id property. Might be worth double checking values for this parameter making sure of formatting, case etc. Is this maybe caused by BCH pairs which went back in recently?

**Comment by mchandschuh** [comment]
I think this was a transient failure. We've made it so we'll continue trying to reconnect via #1632
