### ISSUE TITLE
Composite indicators are limited to composition of indicators of type "IndicatorBaseData" (Cannot compose TradeBar indicators together, etc).

### ISSUE THREAD

**Issue by mblouin02** [QuantConnect/Lean#1602]
Currently, it is only possible to do a composite indicator when composing two indicators that are derived from the class **"Indicator"**.

We should be able to compose indicators of type **"TradeBarIndicator"** together.

We should also be able to compose indicators of type **"Indicator"** with type **"TradeBarIndicator"**.

For example:
- The **"SimpleMovingAverage"** indicator is derived from the class **"Indicator"**.
- The **"ExponentialMovingAverage"** indicator is of type **"Indicator"**
- The **"MoneyFlowIndex"** is of type **"TradeBarIndicator"**.

Currently, it is possible to do the following:
```
SimpleMovingAverage _sma = new SimpleMovingAverage(3);
ExponentialMovingAverage _ema = new ExponentialMovingAverage(2)
CompositeIndicator<IndicatorDataPoint> _composite = _sma.Plus(_ema);
```
However, it is not possible to do any of the following:

Composing a **TradeBar** indicator with another **TradeBar** indicator:
```
MoneyFlowIndex _mfi1 = new MoneyFlowIndex(3);
MoneyFlowIndex _mfi2 = new MoneyFlowIndex(4);
CompositeIndicator<TradeBar> _composite = _mfi1.Plus(_mfi2);
```

Composing a **TradeBar** indicator, with an **Indicator**, returning a **CompositeIndicator** of type **TradeBar**:
```
MoneyFlowIndex _mfi = new MoneyFlowIndex(3);
SimpleMovingAverage _sma = new SimpleMovingAverage(4);
CompositeIndicator<TradeBar> _composite = _mfi.Plus(_sma);
```

Composing a **TradeBar** indicator, with an **Indicator**, returning a **CompositeIndicator** of type **IndicatorDataPoint**:
```
MoneyFlowIndex _mfi = new MoneyFlowIndex(3);
SimpleMovingAverage _sma = new SimpleMovingAverage(4);
CompositeIndicator<IndicatorDataPoint> _composite = _mfi.Plus(_sma);
```

Fixing the **TradeBar+TradeBar** use case is quite easy. In the file **IndicatorExtensions.cs**, we only have to duplicate the **Plus(), Minus(), Times(), Over() and Of()** functions, to compose two indicators of type **TradeBar** together.

Ex:
```
public static CompositeIndicator<TradeBar> Plus(this IndicatorBase<TradeBar> left, decimal constant)
{
    var constantIndicator = new ConstantIndicator<TradeBar>(constant.ToString(CultureInfo.InvariantCulture), constant);
    return left.Plus(constantIndicator);
}

public static CompositeIndicator<TradeBar> Plus(this IndicatorBase<TradeBar> left, IndicatorBase<TradeBar> right)
{
    return new CompositeIndicator<TradeBar>(left, right, (l, r) => l + r);
}

public static CompositeIndicator<TradeBar> Plus(this IndicatorBase<TradeBar> left, IndicatorBase<TradeBar> right, string name)
{
     return new CompositeIndicator<TradeBar>(name, left, right, (l, r) => l + r);
}
```

However, we cannot do the same with all permutations of **TradeBar** + **IndicatorDataPoint**, as the constructor of the class **"CompositeIndicator"** only accepts a **left** and **right** argument that are of the same type. (Type **"T"**)

```
/// <summary>
/// Creates a new CompositeIndicator capable of taking the output from the left and right indicators
/// and producing a new value via the composer delegate specified
/// </summary>
/// <param name="left">The left indicator for the 'composer'</param>
/// <param name="right">The right indidcator for the 'composoer'</param>
/// <param name="composer">Function used to compose the left and right indicators</param>
public CompositeIndicator(IndicatorBase<T> left, IndicatorBase<T> right, IndicatorComposer composer)
            : base(string.Format("COMPOSE({0},{1})", left.Name, right.Name))
{
    _composer = composer;
    Left = left;
    Right = right;
    ConfigureEventHandlers();
}
```

It would therefore be necessary to also create a version of the **CompositeIndicator** that accept different permutations of indicator types for its **left** and **right** arguments.

**Comment by jaredbroad** [comment]
Thank you Matt for the detailed issue & suggestions. Will review and reply ASAP.
