### ISSUE TITLE
Port C# Demonstration Algorithms->Py

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#1610]
These algorithms should be ported to Python to match their C# equivalents:

https://github.com/QuantConnect/Lean/blob/master/Algorithm.CSharp/IndicatorSuiteAlgorithm.cs

https://github.com/QuantConnect/Lean/blob/master/Algorithm.CSharp/RenkoConsolidatorAlgorithm.cs

https://github.com/QuantConnect/Lean/blob/master/Algorithm.CSharp/CoarseUniverseTop5DollarVolumeAlgorithm.cs

https://github.com/QuantConnect/Lean/blob/master/Algorithm.CSharp/DisplacedMovingAverageRibbon.cs

**Comment by mchandschuh** [comment]
Before closing this issue, verify that the above algorithms were not only ported, but also added to the regression tests.
