### ISSUE TITLE
Python Plot doesn't plot StandardDeviation indicator

### ISSUE THREAD

**Issue by Jay-Jay-D** [QuantConnect/Lean#1620]
#### Expected Behavior

In Python, the `self.Plot` function can be used as 
```python
self.Plot('RSI', self.rsi)
```
where `self.rsi` is an indicator defined in the `Initialize` method.

#### Actual Behavior

However, if the `self.Plot` this method is called with a `StandardDeviation` indicator, it throws the following error:
`Runtime Error: QuantConnect.Scheduling.ScheduledEventException: TypeError : No method matches given arguments for Plot ---> Python.Runtime.PythonException: TypeError : No method matches given arguments for Plot at Python.Runtime.Dispatcher.Dispatch (System.Collections.ArrayList args) ` 

#### Potential Solution

As the `StandardDeviation` indicator inherits from `Variance`, the Python port cannot find the correct overload

#### Reproducing the Problem

To reproduce the error, uncomment the last line `self.Plot('indicatorSTD', self.std)` in [this algorithm](https://www.quantconnect.com/terminal/processCache/?request=embedded_backtest_ce154730f41fbcc189b376668f3bc58e.html)

#### System Information

Cloud service.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Fixed in #1622
