### ISSUE TITLE
Update FXCM Market Hours Database

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#1643]
#### Expected Behavior
FXCM handles 2018 holiday hours.

#### Actual Behavior
No holiday market hours specified beyond Jan 2018 (none available from website).

#### Potential Solution
FXCM provided email with table of the market hours until March.

#### Reproducing the Problem
n/a

#### System Information
n/a

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

![2018-03-02 12_56_52- fxcm quantconnect - holiday hours - jared quantconnect com - quantconnect mail](https://user-images.githubusercontent.com/2243225/36913937-832bdc3a-1e19-11e8-993e-71f71e45fe40.png)

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/3942
