### ISSUE TITLE
Add continuous futures price support.

### ISSUE THREAD

**Issue by Maly-Lemire** [QuantConnect/Lean#1650]
Be able to use continuous futures price at minute/second resolution.
Be able to use indicators on that price.

Something like this : https://www.investing.com/indices/us-spx-vix-futures

I can help code this if needed. I really need this in a near future.

**Comment by fera0013** [comment]
I second the request.  It is great that Quantconnect started to integrate Futures - but without internal roll over handling, the practical usage of this feature is rather limited. 

I could also offer to help coding...

**Comment by marcograss** [comment]
is there any update on this @jaredbroad ?

**Comment by z0ned** [comment]
Would be great to get an updated ETA on continuous futures please!

**Comment by z0ned** [comment]
> Be able to use continuous futures price at minute/second resolution.
> Be able to use indicators on that price.
> 
> Something like this : https://www.investing.com/indices/us-spx-vix-futures
> 
> I can help code this if needed. I really need this in a near future.

Can we add Tick resolution to the request?

**Comment by rterbush** [comment]
As someone who is solely focused on futures trading, I am keen to understand this request in more detail. I'm not sure if this is the appropriate place to outline requirements for this feature and won't get into that until I confirm that is input wanted.

I'm confused by this requests as I would expect that anyone developing strategies with Lean for the futures market would be feeding the system with back adjusted data from some source like IB, IQfeed, etc. The only case I can think of where you might not want to do this is if you are creating what I know as "Custom Futures Contracts" that might utilize a different back adjustment method like Back/Forward (Panama) adjustment, Proportional adjustment, or Perpetual adjustment. A user might also want to specify which months are used in the back adjusted data. For creating back adjusted tick data, building from monthly tick data is about the only way to do this that I am aware of, so it would be useful if Lean could build continuous data from specific contract months.

I've not started with system development yet and would like to know that there is no problem using other sources of back adjusted data.
