### ISSUE TITLE
RSI test data is incorrect

### ISSUE THREAD

**Issue by ThomasSzabo** [QuantConnect/Lean#1651]
#### Expected Behavior
The test data should have the following values for the first 16 periods:
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 88.042, 81.631

#### Actual Behavior
The test data for the RSI is not correct. The test data is currently saved here: https://github.com/QuantConnect/Lean/Tests/TestData/spy_with_indicators.txt

The column for the RSI 14 has the first value after 16 periods. I have not checked your maths or the RSI indicator algorithm but if the unit test with this data succeeds, then it is likely that your RSI indicator is calculated incorrectly.

#### Potential Solution
Please double check your RSI testing data and the maths that calculated the values.

**Comment by jaredbroad** [comment]
Thanks Thomas! Where are those proposed rsi values sourced from? We use
external/third party sources for our test data ideally

**Comment by ThomasSzabo** [comment]
As a personal project I am building my own indicators from scratch in Go and Javascript. I was looking for external data that help me to verify that my maths are correct. In case of the RSI, the maths are tested against the data of J.W.Wilder 'New Concepts In Technical Trading System'. 

Also, Stockcharts provides an Excel table of close prices that includes the calculation of the RSI. Their maths match the maths of J.W.Wilder.
http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:relative_strength_index_rsi

My RSI calculation match both Stockcharts and J.W.Wilder's calculations.

I wanted to add the unit test data from QuantConnect (mentioned above) to my own unit tests. The SMA and EMA results were correct but the RSI was not. To answer your question: the expected data above comes from my lib.

My small indicator lib can be found here:
https://github.com/ThomasSzabo/indicator

**Comment by jaredbroad** [comment]
OK; our values come from third party source. Let's check with another independent source to confirm or close this ticket.

**Comment by ThomasSzabo** [comment]
The two sources above are pretty reliable. J.W.Wilder is the creator of the RSI. He published the indicator maths along with some sample data in the above mentioned book.

I transferred the sample data to a json file. Feel free to grab it from here:
https://github.com/ThomasSzabo/indicator/blob/master/testdata/rsiTestData.json

But let me know if you have better sources.

I highly recommend to double check the maths before closing the issue.

**Comment by Worthy7** [comment]
@ThomasSzabo Can you double check that you are avoiding this bug when initializing your RSI:
https://github.com/QuantConnect/Lean/issues/1542
IE, make sure you are using the `Wilders` version of RSI in QC.
`RSI(..., movingAverageType : MovingAverageType.Wilders)`

**Comment by ThomasSzabo** [comment]
@Worthy7 I am not using QuantConnect at all. I was only looking at their unit test data that I wanted to put into my own (see above) RSI indicator function. The RSI is a clearly defined set of rules to calculate a value which is defined in Wilders book. The close price values from the QuantConnect unit test data should give a different result if properly calculated. 

Like I said, I am not using QuantConnect but wanted to give you guys a hint to double check the RSI functions. If your RSI functions are tested with this data and they succeed, then I assume that your maths are different from the original RSI maths defined by Wilder.

**Comment by Worthy7** [comment]
@ThomasSzabo Ah I understand now. Perhaps we could write a test using the data from http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:relative_strength_index_rsi then to confirm.

**Comment by ThomasSzabo** [comment]
@Worthy7  Like I wrote above, feel free to use my RSI unit test data from here:
https://github.com/ThomasSzabo/indicator/blob/master/testdata/rsiTestData.json

It contains the stockcharts data and the original sample data from J.W.Wilder
