### ISSUE TITLE
Python.Runtime.dll not updated on windows 10

### ISSUE THREAD

**Issue by lacvapps** [QuantConnect/Lean#1652]
Link to google group with issue and solution from Sept 2017
https://groups.google.com/forum/#!topic/lean-engine/hxgEL-B2lK0

#### Expected Behavior
On a fresh build of lean on windows if you compile the project before doing the proper python steps there will be a version of the Python.Runtime.dll in the Launcher/bin/Debug folder that will cause an error when you try to run the launcher.

Unable to load DLL 'python3.6': The specified module could not be found.

#### Potential Solution
When rebuilding the launcher, copy the Python.Runtime.dll located in packages\QuantConnect.pythonnet.1.0.5.5\lib

#### System Information
Windows 10 64 bit

**Comment by AlexCatarino** [comment]
@lacvapps , you are right about the potential solution. When we rebuild LEAN, the right Python.Runtime.dll is copied from packages to bin. In PR #1670, I edited the readme to include that step.
