### ISSUE TITLE
Add QC500 Constituents Generator Algorithm for C# and Python

### ISSUE THREAD

**Issue by jingwu74** [QuantConnect/Lean#1662]
#### Expected Behavior

Add the python and CSharp example of estimating constituents of QC500 index using fundamental data. This algorithm will create a default universe containing 500 US equities. Constituents are chosen at the first trading day of each month. 

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Merged in #1663
