### ISSUE TITLE
Implements GetStringBetweenChars Extension method

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#1677]
This change was requested after #1659 was merged.

#### Expected Behavior

GetStringBetweenChars is a extension method.

#### Actual Behavior

GetStringBetweenChars is a static method in PythonUtil class.

#### Potential Solution

Moves the method to Extension from PythonUtil class.

#### Reproducing the Problem

N/A

#### System Information

N/A

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
Merged in #1678
