### ISSUE TITLE
Time zone inconsistency

### ISSUE THREAD

**Issue by tzaavi** [QuantConnect/Lean#168]
When data is saved into a ChartPoint the time is converted to UTC, this makes sense case it save the time as unix timestamp.

The problem that in deferent place in the application the time zone set differently for instance in the tick data or TradeBar the time zone is unspecified and the UTC conversion is adding 4 hours (incase or ETC) to the time.

In SampleEquity method the time zone is also unspecified but in the SampleBenchmark and SamplePerformance  the time zone is UTC.

That causes the data in the final results to contain a mix of UTC converted and not converted times.

**Comment by mchandschuh** [comment]
Can you reference some lines of code? I believe we use UTC as the input time for [SampleEquity](https://github.com/QuantConnect/Lean/blob/c67ff638f4d33a8a50a401476035fc795787211f/Engine/AlgorithmManager.cs#L230), [SamplePerformance](https://github.com/QuantConnect/Lean/blob/c67ff638f4d33a8a50a401476035fc795787211f/Engine/AlgorithmManager.cs#L239), and [SampleBenchmark](https://github.com/QuantConnect/Lean/blob/c67ff638f4d33a8a50a401476035fc795787211f/Engine/AlgorithmManager.cs#L227).

The `previousTime` and `time` variable in the `AlgorithmManager` are in UTC as per [TimeSlice.Time](https://github.com/QuantConnect/Lean/blob/master/Engine/DataFeeds/TimeSlice.cs#L222)

**Comment by tzaavi** [comment]
SampleEquity is also being called from [here](https://github.com/QuantConnect/Lean/blob/c67ff638f4d33a8a50a401476035fc795787211f/Engine/Results/ConsoleResultHandler.cs#L594) and time zone in this case is unspecified.

Also all the ChartPoint that generate from Plot and Plot Indicator the time zone is unspecified
