### ISSUE TITLE
Unable to build QuantConnect.Lean.sln on macOS

### ISSUE THREAD

**Issue by elihuansen** [QuantConnect/Lean#1683]
<img width="1920" alt="screen shot 2018-03-12 at 1 06 26 am" src="https://user-images.githubusercontent.com/31790206/37256234-bb7c3ad2-2592-11e8-86d6-a32cec402540.png">

Hi guys,

Thanks for the fantastic work so far! I'm unable to get Lean to build due to the errors in the attached image. I'm currently using macOS High Sierra v10.13.3. I followed the instructions in the readme. Am I missing something here?

**Comment by AlexCatarino** [comment]
These projects depend on Visual Studio features that are not available for macOS, but they are not required to compile Lean.

**Comment by jaredbroad** [comment]
@elihuansen -- if you unload those projects from the solution; the rest of LEAN will compile without issue.

If seeking to use Python-MacOS there is an outstanding issue we're working with PythonNet causing it to not work in Mac for now.
