### ISSUE TITLE
Named arguments in python algorithms

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#1696]
#### Expected Behavior

Use named arguments to specify an argument for a particular parameter by associating the argument with the parameter's name rather than with the parameter's position in the parameter list.

#### Actual Behavior

When we use named arguments, the desired values are not passed.

#### Potential Solution

Follow pythonnet's issue [265](https://github.com/pythonnet/pythonnet/issues/265)

#### Reproducing the Problem

`Log` statement should display `1`, but it `2` is shown.
```python
class BasicTemplateAlgorithm(QCAlgorithm):
    def Initialize(self):
        spy = self.AddEquity("SPY", leverage=1)
        self.Log(str(spy.Leverage))
```
#### System Information

N/A

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/5376
