### ISSUE TITLE
Add Universe Selection to QuantBook

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#1697]
#### Expected Behavior

In QuantBook, it should be possible to use the Universe Selection feature.

#### Actual Behavior

Not supported.

#### Potential Solution

N/A

#### Reproducing the Problem

N/A

#### System Information

N/A

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Duplicate #1614 👎

**Comment by pavelfedorov1** [comment]
thank you Alex, this is super important for machine learning to build datasets without lookahead bias
