### ISSUE TITLE
Option and Futures History period mismatch

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#1698]
#### Expected Behavior
Using `GetOptionHistory(Symbol, DateTime)` or `GetFutureHistory(Symbol, DateTime)`, fetch the data with the date/time defined by `DateTime`.

#### Actual Behavior
Those methods are fetching data from a day earlier.

#### Potential Solution
Directly use `QCAlgorithm.History` instead of creating a list of `HistoryRequest`.

#### Reproducing the Problem
In the [Research Environment](https://www.quantconnect.com/research):
```python
qb = QuantBook()
goog = qb.AddOption("GOOG")
goog.SetFilter(-2, 2, timedelta(0), timedelta(180))
dt = datetime(2018,1,19)
option_history = qb.GetOptionHistory(goog.Symbol, dt)
print(option_history.GetAllData())
```
Verify that the data if from 2018-01-18 instead of 2018-01-19.

#### System Information
N/A

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Fixed in #1712
