### ISSUE TITLE
Exception thrown while trying to login using VS plugin

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#1699]
#### Expected Behavior

No exception is thrown while trying to login

#### Actual Behavior

Exception "_The type initializer for 'QuantConnect.Securities.MarketHoursDatabase' threw an exception._" is thrown.

#### Potential Solution

I believe there is a state, different than the default, in which there is something funny happening with the dataFolder value

#### Reproducing the Problem

By default the issue is not present. I think deleting C:\Users\UserName\AppData\Local\Microsoft\VisualStudio\15.0_8ab640ac\privateregistry.bin caused a different state after which the issue occurs always

#### System Information

Win 10, Visual studio 2017

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Fixed in #1708 and #1700
