### ISSUE TITLE
Clean up & refactor VS plugin

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#1709]
#### Expected Behavior

Visual Studio Plugin should be aligned with the best practices used by Lean.

#### Actual Behavior

Visual Studio Plugin is not a 100% aligned with best practices

#### Potential Solution

Clean VS plugin project

#### Reproducing the Problem

Not valid

#### System Information

Not valid

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Clean up more or less finished in various PR's ending in #1723

Next steps:
 - Better error messages in event of backtest errors (e.g. runtime errors).
 - Show progress bars during backtests; show local chart of the backtest running in cloud
