### ISSUE TITLE
SetHoldings Requests Incorrect Quantity for Crypto Assets

### ISSUE THREAD

**Issue by Jay-Jay-D** [QuantConnect/Lean#1715]
#### Actual Behavior

After every order sent, the algorithm throws the following error:
```
2018-03-19T09:12:21.8464013Z ERROR:: Order Error: id: 1, Insufficient buying power to complete order (Value:100000.0000), Reason: Your portfolio holds 100000 USD, 0 USD of which are reserved for open orders, but your Buy order is for 163.33197223 BTC. Your order requires a total value of 99999.9999978175 USD, but only a total value of 99748.37078868 USD is available.
```
This in turn, makes fail the `BasicTemplateFrameworkCryptoAlgorithm` regression test.

#### Potential Solution

Change how the portfolio share to invest is estimated in [this line](https://github.com/QuantConnect/Lean/blob/4957034bd4a1ca6d5571949f4e8aa92e0d1c44b5/Common/Algorithm/Framework/Portfolio/PortfolioTarget.cs#L75) from:
```cs
var quantity = percent * algorithm.Portfolio.TotalPortfolioValue / security.Price;);

// round down to nearest lot size
var remainder = quantity % security.SymbolProperties.LotSize;
quantity = quantity - remainder;
```
to:
```cs
var targetValue = percent * algorithm.Portfolio.TotalPortfolioValue;
var quantity = security.BuyingPowerModel.GetMaximumOrderQuantityForTargetValue(algorithm.Portfolio, security, targetValue).Quantity;
```

#### Reproducing the Problem

Run the `BasicTemplateFrameworkCryptoAlgorithm`.

#### System Information

Run on  Windows 7, latest Lean (commit 4957034)

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/2458
