### ISSUE TITLE
Setting DesktopResultHandler returns a ConsoleResultHandler

### ISSUE THREAD

**Issue by chrisdk2015** [QuantConnect/Lean#172]
On latest Mono/Ubuntu 14.04 here, the line 

Config.Set("result-handler", "QuantConnect.Lean.Engine.Results.DesktopResultHandler");

in LeanEngineWinForm.cs doesn't result in a DesktopResultHandler getting returned but a ConsoleResultHandler.

I couldn't figure out why my cast to a DesktopResultHandler failed but now I know.

If you look in PollingOnTick you can see the type.

**Comment by StefanoRaggi** [comment]
The following line should be added in the `LeanEngineWinForm.Main()` function:

```
Config.Set("environment", "desktop");
```

**Comment by chrisdk2015** [comment]
Yes, then it works. Thanks.
