### ISSUE TITLE
Add LeastSquaresMovingAverage indicator

### ISSUE THREAD

**Issue by mchandschuh** [QuantConnect/Lean#174]
Recently shared on the [forums](https://www.quantconnect.com/forum/discussion/785/moving-linearregression) was a least squares moving average implementation, basically a form of moving linear regression.

**Comment by Jay-Jay-D** [comment]
I take it.

**Comment by Jay-Jay-D** [comment]
Michael, please check [this first](https://www.quantconnect.com/terminal/results/2edc2f993f30fffff4589238554a4d5c) implementation.

**Comment by mchandschuh** [comment]
The implementation looks correct, I wonder if we could conjure up an on-line implementation. My only issue with this implementation is that the compute time is dependent on the period for each time step, so as the period increases, the compute time also increases.

In order for this to be ready for a pull request we'll need to add tests and an LSMA helper function similar to [this](https://github.com/QuantConnect/Lean/blob/master/Algorithm/QCAlgorithm.Indicators.cs#L162).

**Comment by Jay-Jay-D** [comment]
I think we can make the estimation faster but not independent of period. I'm thinking in avoiding the `window` object sorting and casting by using a `RollingWindow<double>` updated at every step and defining the t vector backwards. 

What do you think?

**Comment by Jay-Jay-D** [comment]
I made the test and everything works fine. I'll make the PR today I think.

BTW, I have some modifications to the Momersion too, but I don't know if worth to open a new Issue. How is the best way to proceed?

**Comment by mchandschuh** [comment]
This has already been completed.
