### ISSUE TITLE
Python - Ubuntu 16.04 Error

### ISSUE THREAD

**Issue by learnerAI** [QuantConnect/Lean#1746]
#### Expected Behavior

Lean engine is working fine with default config.json file i.e. with CSharp. However, when I make the suggested changes i.e. 
// algorithm class selector
  //"algorithm-type-name": "BasicTemplateFrameworkAlgorithm",
  "algorithm-type-name": "BasicTemplateAlgorithm",
  // Algorithm language selector - options CSharp, FSharp, VisualBasic, Python, Java
  "algorithm-language": "Python",

  //Physical DLL location
  //"algorithm-location": "QuantConnect.Algorithm.CSharp.dll",
    "algorithm-location": "../../../Algorithm.Python/BasicTemplateAlgorithm.py",
  //"algorithm-location": "QuantConnect.Algorithm.FSharp.dll",
  //"algorithm-location": "QuantConnect.Algorithm.VisualBasic.dll",
  //"algorithm-location": "QuantConnect.Algorithm.Java.dll",

I receive the following errors when running the .exe

#### Actual Behavior

20180322 19:51:24.602 ERROR:: Loader.TryCreatePythonAlgorithm():  System.Exception: AlgorithmPythonWrapper(): The dynamic-link library for  could not be found. Please visit https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/readme.md for instructions on how to enable python support in Unix python3.6
  at QuantConnect.AlgorithmFactory.Python.Wrappers.AlgorithmPythonWrapper..ctor (System.String moduleName) [0x00317] in <b7f56beed98341e9b3a36cb5ec82c9fc>:0 
  at QuantConnect.AlgorithmFactory.Loader.TryCreatePythonAlgorithm (System.String assemblyPath, QuantConnect.Interfaces.IAlgorithm& algorithmInstance, System.String& errorMessage) [0x00068] in <b7f56beed98341e9b3a36cb5ec82c9fc>:0 
20180322 19:51:25.469 ERROR:: Engine.Run():  System.Exception: Loader.TryCreatePythonAlgorithm(): Unable to import python module ../../../Algorithm.Python/BasicTemplateAlgorithm.py. AlgorithmPythonWrapper(): The dynamic-link library for  could not be found. Please visit https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/readme.md for instructions on how to enable python support in Unix python3.6: try re-building algorithm.
  at QuantConnect.Lean.Engine.Setup.ConsoleSetupHandler.CreateAlgorithmInstance (QuantConnect.Packets.AlgorithmNodePacket algorithmNodePacket, System.String assemblyPath) [0x0006b] in <3809d8fb051c4d86ab424c28f40f9955>:0 
  at QuantConnect.Lean.Engine.Engine.Run (QuantConnect.Packets.AlgorithmNodePacket job, QuantConnect.Lean.Engine.AlgorithmManager manager, System.String assemblyPath) [0x000e3] in <3809d8fb051c4d86ab424c28f40f9955>:0 
20180322 19:51:25.470 Trace:: JOB HANDLERS: 
20180322 19:51:25.470 Trace::          DataFeed:     QuantConnect.Lean.Engine.DataFeeds.FileSystemDataFeed
20180322 19:51:25.471 Trace::          Setup:        QuantConnect.Lean.Engine.Setup.ConsoleSetupHandler
20180322 19:51:25.471 Trace::          RealTime:     QuantConnect.Lean.Engine.RealTime.BacktestingRealTimeHandler
20180322 19:51:25.471 Trace::          Results:      QuantConnect.Lean.Engine.Results.BacktestingResultHandler
20180322 19:51:25.471 Trace::          Transactions: QuantConnect.Lean.Engine.TransactionHandlers.BacktestingTransactionHandler
20180322 19:51:25.471 Trace::          Alpha:        QuantConnect.Lean.Engine.Alphas.DefaultAlphaHandler
20180322 19:51:25.475 Trace:: Config.GetValue(): send-via-api - Using default value: False
20180322 19:51:25.476 ERROR:: Algorithm.Initialize() Error: Loader.TryCreatePythonAlgorithm(): Unable to import python module ../../../Algorithm.Python/BasicTemplateAlgorithm.py. AlgorithmPythonWrapper(): The dynamic-link library for  could not be found. Please visit https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/readme.md for instructions on how to enable python support in Unix python3.6: try re-building algorithm. Stack Trace:   at QuantConnect.Lean.Engine.Setup.ConsoleSetupHandler.CreateAlgorithmInstance (QuantConnect.Packets.AlgorithmNodePacket algorithmNodePacket, System.String assemblyPath) [0x0006b] in <3809d8fb051c4d86ab424c28f40f9955>:0 
  at QuantConnect.Lean.Engine.Engine.Run (QuantConnect.Packets.AlgorithmNodePacket job, QuantConnect.Lean.Engine.AlgorithmManager manager, System.String assemblyPath) [0x000e3] in <3809d8fb051c4d86ab424c28f40f9955>:0 
   at QuantConnect.Lean.Engine.Setup.ConsoleSetupHandler.CreateAlgorithmInstance (QuantConnect.Packets.AlgorithmNodePacket algorithmNodePacket, System.String assemblyPath) [0x0006b] in <3809d8fb051c4d86ab424c28f40f9955>:0 
  at QuantConnect.Lean.Engine.Engine.Run (QuantConnect.Packets.AlgorithmNodePacket job, QuantConnect.Lean.Engine.AlgorithmManager manager, System.String assemblyPath) [0x000e3] in <3809d8fb051c4d86ab424c28f40f9955>:0 

#### Potential Solution

Can't think of anything

#### Reproducing the Problem

Followed all the steps given on the main page and python link

#### System Information

Ubuntu 16.04

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment]
@learnerAI What is the error?

**Comment by learnerAI** [comment]
QuantConnect.AlgorithmFactory.Loader.TryCreatePythonAlgorithm (System.String assemblyPath, QuantConnect.Interfaces.IAlgorithm& algorithmInstance, System.String& errorMessage) [0x00068] in :0
20180322 19:51:25.469 ERROR:: Engine.Run(): System.Exception: Loader.TryCreatePythonAlgorithm(): Unable to import python module ../../../Algorithm.Python/BasicTemplateAlgorithm.py. AlgorithmPythonWrapper(): The dynamic-link library for could not be found.

**Comment by learnerAI** [comment]
You can see the entire output in the question (had edited and added it under Actual behaviour) when the lean engine was run after making the changes to config.json file

**Comment by ehtycuact** [comment]
@AlexCatarino I don't see how this solves the issue @learnerAI mentioned. I am getting the same error.

**Comment by leochirag** [comment]
Can someone help, I am getting the same issue and have followed all the steps as mentioned in the readme.

**Comment by ehtycuact** [comment]
@leochirag Try building the python exe it worked for me. Found it in the forum:
`mono nPython.exe -m compileall -lq .`
