### ISSUE TITLE
Improve VS Plugin login dialog UI

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#1766]
#### Expected Behavior

-Icons
-Look and feel aligned with QuantConnect
-Pressing enter in password box should login
-Exception should not disable login button
-If login failed should inform user
-Help button

#### Actual Behavior

-Missing Icons
-Look and feel not aligned with QuantConnetc
-Enter does not login
-Exception should disables login button
-If login fails user isn't informed
-No help button

#### Potential Solution

Improve UI

#### Reproducing the Problem

N/A

#### System Information

N/A

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Addressed in #1767 -- thanks @Martin-Molinero !
