### ISSUE TITLE
Set correct data queue handler for live trading with IB

### ISSUE THREAD

**Issue by chrisdk2015** [QuantConnect/Lean#178]
Could you in config.json set

"data-queue-handler": "QuantConnect.Brokerages.InteractiveBrokers.InteractiveBrokersBrokerage",

in the Quantconnect.Lean.Engine project so IB works live out of the box?

Thanks.

**Comment by jaredbroad** [comment]
Maybe not the default for all, but we should definitely make an
IB environment configuration for local use, this would be a common request
:)

Best,
Jared

On Tue, Sep 29, 2015 at 4:22 AM, chrisdk2015 <notifications@github.com>
wrote:

> Could you in config.json set
>
> "data-queue-handler":
> "QuantConnect.Brokerages.InteractiveBrokers.InteractiveBrokersBrokerage",
>
> in the Quantconnect.Lean.Engine project so IB works live out of the box?
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/QuantConnect/Lean/issues/178>.
>



-- 
Jared Broad

www.quantconnect.com
Phone-USA: +1 917 327 0556
*Democratizing Finance, Empowering Individuals*
Facebook <http://www.facebook.com/QuantConnect> | Twitter
<https://twitter.com/#!/QuantConnect> | LinkedIn
<http://www.linkedin.com/company/quantconnect> | Skype: jaredbroad

**Comment by jaredbroad** [comment]
Completed in commit #937b5cb7
