### ISSUE TITLE
Build custom portfolio construction model with mean variance optimization

### ISSUE THREAD

**Issue by jingwu74** [QuantConnect/Lean#1788]
#### Expected Behavior

There should be a template for mean-variance optimization model to calculate the optimal weights for assets in the portfolio based on modern portfolio theory. 
#### Actual Behavior

There is no such custom portfolio construction model in algorithm framework.
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by #1832.
