### ISSUE TITLE
DesktopResultHandler should route OrderEvents

### ISSUE THREAD

**Issue by chrisdk2015** [QuantConnect/Lean#179]
Could you add following line to OrderEvent in DesktopResultHandler:

Messages.Enqueue(new OrderEventPacket(_algorithm.AlgorithmId,newEvent));

so we can handle orderevents in a graphical user interface?

Right now I have to add this everytime I pull from github.

**Comment by jaredbroad** [comment]
Good catch!

I'm gutting and rewriting the result handlers & messaging handlers to
support local HTML5 charting, this should be done in the next few days.
I'll make sure I includes this in the re-write,

Please feel free to submit a pull request, we've written a contributing
guide here:
https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md

JB

On Tue, Sep 29, 2015 at 4:24 AM, chrisdk2015 <notifications@github.com>
wrote:

> Could you add following line to OrderEvent in DesktopResultHandler:
>
> Messages.Enqueue(new OrderEventPacket(_algorithm.AlgorithmId,newEvent));
>
> so we can handle orderevents in a graphical user interface?
>
> Right now I have to add this everytime I pull from github.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/QuantConnect/Lean/issues/179>.
>



-- 
Jared Broad

www.quantconnect.com
Phone-USA: +1 917 327 0556
*Democratizing Finance, Empowering Individuals*
Facebook <http://www.facebook.com/QuantConnect> | Twitter
<https://twitter.com/#!/QuantConnect> | LinkedIn
<http://www.linkedin.com/company/quantconnect> | Skype: jaredbroad

**Comment by jaredbroad** [comment]
Closed by commit #31df99945
