### ISSUE TITLE
Create a Unit Test framework for QCAlgorithmFramework modules

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#1790]
#### Expected Behavior
Be able to test `QCAlgorithmFramework` modules with unit tests.

#### Actual Behavior
Not implemented yet.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
Closing as decided better to focus on regression for these
