### ISSUE TITLE
Problem with MovingAverageCross example.

### ISSUE THREAD

**Issue by jilott** [QuantConnect/Lean#18]
I'm trying to explore the examples and have found some problem exists with the MovingAverageCross. I'm a little new to C$#, so the solution is not obvious to me. Hopefully, someone can work it out. Here is the error:

ERROR:: ConsoleSetupHandler().Setup(): Type mismatch found between consolidator and indicator for symbol: SPY.Consolidator outputs type TradeBar but indicator expects input type indicatorDataPoint

**Comment by mchandschuh** [comment]
Thanks for finding this @jilott !!
