### ISSUE TITLE
For timezone CEST market never opens in live trading + tick.Time is possibly incorrect

### ISSUE THREAD

**Issue by chrisdk2015** [QuantConnect/Lean#180]
My local PC is in timezone CEST where I use the IBController (Mono/Linux).

In LocalMarketHours.cs

public bool IsOpen(TimeSpan time, bool extendedMarket)

return time >= _marketOpen
               && time < _marketClose;

always returns false because _marketOpen and _marketClose is set to 00:00:00 (?).

time is also in my local time, which is not correct?

I added -6 hours to get to NY time in InteractiveBrokersBrokerage.cs (_brokerTimeDiff) to change the tick.Time.

**Comment by mchandschuh** [comment]
This may be an issue loading data from the market-hours-database. This code is located in the `SecurityExchangeHoursProvider` [here](https://github.com/QuantConnect/Lean/blob/master/Common/Securities/SecurityExchangeHoursProvider.cs#L129)

The only time those two values should be equal to zero is when the market is closed all day (Saturday/Sunday for equities).

**Comment by mchandschuh** [comment]
A nice test would be to change your computer's time zone and see if you experience the same behavior.

**Comment by chrisdk2015** [comment]
It reads the file alright but 

in LocalMarketHours.cs

private static readonly IReadOnlyDictionary<DayOfWeek, LocalMarketHours> Open = new ReadOnlyDictionary<DayOfWeek, LocalMarketHours>(
            Enum.GetValues(typeof(IsoDayOfWeek)).Cast<DayOfWeek>()
                .ToDictionary(x => x, x => new LocalMarketHours(x, TimeSpan.Zero, TimeSpan.FromTicks(Time.OneDay.Ticks - 1)))
            ); 

TimeSpan.Zero results in _marketOpen to be 00:00:00

it doesn't seem to put the hours from securityexchangehoursprovider into LocalMarketHours?

**Comment by mchandschuh** [comment]
That private static is a definition for exchanges that are considered always open. If you place a breakpoint in the `SecurityExchangeHoursProvider` [here](https://github.com/QuantConnect/Lean/blob/master/Common/Securities/SecurityExchangeHoursProvider.cs#L89) you should be able to intercept the request to get your exchange hours. 

Market open as 00:00:00 sounds like forex hours during a weekday. What security types are you trying to run?

**Comment by chrisdk2015** [comment]
Security types: all equities (leveraged ETFs) like UPRO, TQQQ, NUGT etc.

I tried to change the timezone on my PC, didn't have any effect.

**Comment by jasonnator** [comment]
I had the same issue on a different project. The solution ended up being using DateTimeOffset instead of DateTime.

**Comment by mchandschuh** [comment]
Internally we use Jon Skeet's NodaTime library for dealing with time zones. The issue here is the source of time in the InteractiveBrokersBrokerage implementation uses DateTime.Now instead of the local machine settings agnostic DateTime.UtcNow + a time zone conversion to NewYork (or whatever the desired output time zone may be)
