### ISSUE TITLE
TickConsolidator is processing Future Contract OpenInterest ticks 

### ISSUE THREAD

**Issue by FischMati** [QuantConnect/Lean#1818]
When requesting consolidated data for a Future contract, like in this example

**(from algorithm)**

**[contract.symbol = ESM18]**

```
AddFutureContract(contract.Symbol, Resolution.Tick);

consolidator = new TickConsolidator(TimeSpan.FromMinutes(1));
consolidator.DataConsolidated += OnDataConsolidated;

SubscriptionManager.AddConsolidator(contract.Symbol, consolidator);
```

When working with Interactive brokers paper account 

**(from config.json)**

` "environment": "live-interactive"`

When OnDataConsolidated is fired

```
public void OnDataConsolidated(object sender, TradeBar bar)
{
     referenceBar = bar;
     referenceHigh = bar.High;
}
```

#### Expected Behavior
referenceHigh should evaluate to something more logical, for example
**2018/04/02 12:55** Trace:: Log: Tick at 2580,75 ; Ref high at **2582**                                                    

#### Actual Behavior
referenceHigh evaluates to
**2018/04/02 12:55** Trace:: Log: Tick at 2580,75 ; Ref high at **2051004**                                                    
While tick shouldn't be equal to referenceHigh, it's value is way too far from it.

**It doesn't happen always - sometimes, data is correct.**

#### System Information
Working on Windows 10, from Argentina, with TWS v969, IB Controller 3.4.0 and Lean from Master branch.

**Comment by jaredbroad** [comment]
`2580,75` -- Could possibly localization issue; can you please post your country-number format settings?

**Comment by mchandschuh** [comment]
Also might help to confirm what the raw data looks like going into the consolidator straight from IB.

**Comment by StefanoRaggi** [comment]
It looks like we are feeding the `OpenInterest` data into the `TickConsolidator`:

4/2/2018 3:15:59 PM - Tick: ESM18 TickType: OpenInterest Bid: 0 Ask: 0 Last: 842869
4/2/2018 3:15:59 PM - Tick: ESM18 TickType: OpenInterest Bid: 0 Ask: 0 Last: **2051004**

Only `TickType.Trade` ticks should be processed.
