### ISSUE TITLE
ES Futures - Historical data request pacing violation on Warmup

### ISSUE THREAD

**Issue by FischMati** [QuantConnect/Lean#1837]
#### Expected Behavior
Warmup should be performed as usual.

#### Actual Behavior

from Logs:

20180404 21:10:58 Trace:: InteractiveBrokersBrokerage.HandleError(): RequestId: 6 ErrorCode: 162 - Historical Market Data Service error message:Historical data request pacing violation. Origin: GetHistory: FUT ES USD GLOBEX
20180404 21:10:58 Trace:: Brokerage.OnMessage(): Warning - Code: 162 - Historical Market Data Service error message:Historical data request pacing violation. Origin: GetHistory: FUT ES USD GLOBEX

Application waits some time, and then..

20180404 21:13:00.930 Trace:: Log: Runtime Error: A data subscription for type 'TradeBar' was not found.
20180404 21:13:00.930 ERROR:: Runtime Error: A data subscription for type 'TradeBar' was not found.
 System.Exception: A data subscription for type 'TradeBar' was not found.
   en QuantConnect.Lean.Engine.AlgorithmManager.<Stream>d__22.MoveNext()

#### Reproducing the Problem

Request Warmup data for a Future contract, like in this example

**(Initialize)**

```
            SetBrokerageModel(BrokerageName.InteractiveBrokersBrokerage, AccountType.Margin);

            (...)

            SetWarmup(TimeSpan.FromDays(1));

            var futureSP500 = AddFuture(RootSP500, Resolution.Tick);

            futureSP500.SetFilter(TimeSpan.Zero, TimeSpan.FromDays(182));

```

And set config.json to live-interactive, in this case working live with Interactive Brokers Paper Account.

#### System Information
Working on Windows 10, from Argentina, with TWS v969, IB Controller 3.4.0 and Lean from Master branch.

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/2974
