### ISSUE TITLE
Rename SetPortoflioSelection to SetUniverse

### ISSUE THREAD

**Issue by mchandschuh** [QuantConnect/Lean#1845]
#### Description
The recent rename of `IPortfolioSelectionModel` to `IUniverseSelectionModel` missed the `QCAlgorithmFramework.SetPortfolioSelection` method.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by [b63f148](https://github.com/QuantConnect/Lean/pull/1854/commits/b63f148b5458f23343bb7cf9b44560aa84f6e953).
