### ISSUE TITLE
Non-USD cash added during Initialize not counted as starting capital in backtesting

### ISSUE THREAD

**Issue by StefanoRaggi** [QuantConnect/Lean#1859]
#### Expected Behavior
Other currencies or crypto added with `SetCash` in `Initialize` should be included in the starting capital for algorithm statistics. This is working in Live trading, but **not** in backtesting.

#### Actual Behavior
The conversion rates for currencies added with `SetCash` are set equal to the value passed to the method. If we pass a value of zero (because we expect LEAN to fetch them for us), those currencies will not be included in the starting capital and algorithm statistics will be incorrect, with values like these for the test algorithm below:
```
Compounding Annual Return 79228162514264337593543950335% 
Net Profit 209.519%
```

#### Potential Solution
The starting capital is currently set equal to `Portfolio.Cash` (which requires conversion rates for all non-USD currencies to be already set) in the `Setup` method for both `BacktestingSetupHandler` and `ConsoleSetupHandler`.
A possible solution could be to update these handlers to fetch the conversion rates immediately, just as `BrokerageSetupHandler` does with real brokerages.

#### Reproducing the Problem
Sample algorithm to repeat the issue:
``` C#
public class TestStartingCapitalAlgorithm : QCAlgorithm
{
    public override void Initialize()
    {
        SetStartDate(2018, 4, 4); //Set Start Date
        SetEndDate(2018, 4, 4); //Set End Date

        SetCash(10000);
        SetCash("EUR", 10000, 0);
        SetCash("BTC", 1m, 0);
        SetCash("ETH", 5m, 0);

        SetBrokerageModel(BrokerageName.GDAX, AccountType.Cash);

        AddCrypto("BTCUSD");
        AddCrypto("ETHUSD");
    }
}
```

#### System Information
n/a

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by fix8this** [comment]
I would be pleased if you could fix this as next. 
Do i have to restart live server after bugfixing?
