### ISSUE TITLE
PSAR indicator bug

### ISSUE THREAD

**Issue by Jay-Jay-D** [QuantConnect/Lean#186]
I found a bug in the ParabolicStopAndReverse indicator. The indicator runs is always estimated with the default configuration.
In [this backtest] (https://www.quantconnect.com/terminal/results/51559780b3671dfdf45d8786f2a0d5a7) I defined three PSA, one with default factors, and the three are equal in all the estimations.

**Comment by mchandschuh** [comment]
I just tried plotting the the PSARs and they look good to me :)

This plot shows price along with the three PSARs made from your algorithm, here's the code:
```C#
AddSecurity(SecurityType.Equity, "SPY", Resolution.Daily);

var close = Identity("SPY");
var psar1 = PSAR("SPY");
var psar2 = PSAR("SPY", 0.1m, 0.1m, 0.2m);
var psar3 = PSAR("SPY", 0.01m, 0.01m, 0.01m);

var chart = new Chart("SPY");
chart.AddSeries(new Series(close.Name));
chart.AddSeries(new Series(psar1.Name, SeriesType.Scatter));
chart.AddSeries(new Series(psar2.Name, SeriesType.Scatter));
chart.AddSeries(new Series(psar3.Name, SeriesType.Scatter));

PlotIndicator("SPY", close);
PlotIndicator("SPY", true, psar1, psar2, psar3);
```

@Jay-Jay-D - maybe there's a bug in your algorithm?

![2015-10-13 17_16_52-quantconnect com - algorithmic trading platform](https://cloud.githubusercontent.com/assets/531416/10468665/4a8cfce6-71ce-11e5-9c9e-0a09c321d75b.png)

**Comment by mchandschuh** [comment]
So a little more playing around and I was able to repeat what you saw... but only when I don't set the name of the indicator... very peculiar.

**Comment by mchandschuh** [comment]
Figured it out, totally a bug! Great find @Jay-Jay-D, the issue is with the constructor, it looks like it uses the input parameters, but it's actually only using them for the `string.Format` call!

Check out this [line](https://github.com/QuantConnect/Lean/blob/master/Indicators/ParabolicStopAndReverse.cs#L60).

It's specifically using all the default values! Will submit a fix today.

**Comment by Jay-Jay-D** [comment]
I'm so glad to help.

**Comment by mchandschuh** [comment]
This was fixed in https://github.com/QuantConnect/Lean/commit/431bb54398b684a1163cfc62d2ebb77fd3bcf51c
