### ISSUE TITLE
Average Daily Range (ADR) indicator

### ISSUE THREAD

**Issue by michaelsrew** [QuantConnect/Lean#1877]
On the day that this project is 99.92% finished
please add Mr. Wilders ADR indicator.

**Comment by captholley** [comment]
I am considering working on this one, but I have a question on what would be the best way to implement the ADR. 
I could simply do the difference of the high and low for the input range, though this will not take into account the user possibly inputting a resolution other than daily. 

I could also have private variables for the high and low and update these as the data points flow in, which would require a large warm-up if the user chooses a lower resolution such as minute.

Or is there a way to restrict the indicator to only certain resolutions. This may be easiest if there is an option.

Once I know this I can submit a pull request as the code is very similar to the ATR indicator.

**Comment by LouisSzeto** [comment]
[spy_adr.csv](https://github.com/QuantConnect/Lean/files/10824422/spy_adr.csv)

**Comment by LouisSzeto** [comment]
[spy_adr.csv](https://github.com/QuantConnect/Lean/files/13114667/spy_adr.csv)
columns: "SPY high" "SPY low" "ADR"

script:
```
import talib

qb = QuantBook()

spy = qb.AddEquity("SPY", Resolution.Daily).Symbol

history = qb.History([spy, qqq], datetime(1998, 1, 1), datetime(2023, 2, 23))

high = history.loc[spy].high
low = history.loc[spy].low

# Source: https://www.tradingview.com/script/6KVjtmOY-ADR-Average-Daily-Range-by-MikeC-AKA-TheScrutiniser/
adr = talib.SMA(high - low, 20).dropna().to_frame()
adr["spy high"] = high
adr["spy low"] = low
adr = adr.iloc[:, [1, 2, 0]]
adr.to_csv("spy_adr.csv", header=False)
```
