### ISSUE TITLE
about sign up

### ISSUE THREAD

**Issue by royburns** [QuantConnect/Lean#1882]
![image](https://user-images.githubusercontent.com/652375/38905810-75eeb3a8-42e5-11e8-9b58-0013a6fb164e.png)

why the website has no response

**Comment by mchandschuh** [comment]
Please submit questions/comments/concerns/bugs pertaining to www.quantconnect.com to support@quantconnect.com.

Please provide as much information as possible so that the QuantConnect support team and quickly resolve any issue you may be experiencing.
