### ISSUE TITLE
Implementation of SetFilter() method in Jupyter notebook

### ISSUE THREAD

**Issue by jingwu74** [QuantConnect/Lean#1890]
#### Expected Behavior

SetFilter() should filter futures contracts by the expiry
#### Actual Behavior

History request does not support SetFilter() for futures
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/4398
