### ISSUE TITLE
Add Insight Scoring Regression Test

### ISSUE THREAD

**Issue by mchandschuh** [QuantConnect/Lean#1899]
#### Description
We need a regression algorithm that confirms certain aspects of how we score insights. Specifically, we should include some custom data types that are monotonic to confirm we can receive a 100% direction/magnitude score (one linear, one exponential).

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
Insight scoring too artistic and niche
