### ISSUE TITLE
Add OANDA Brokerage

### ISSUE THREAD

**Issue by mourednik** [QuantConnect/Lean#19]
OANDA has a REST API with reference implementation in C#
https://github.com/oanda/rest-csharp-refimpl/
I would like to implement this feature. I will study it over the next few days.

**Comment by mchandschuh** [comment]
Sounds great. The IBrokerage interface is fairly new and still may be in flux. If you have any questions let me know.

**Comment by jilott** [comment]
@mourednik Have you made any progress on this? I'd probably be interested in helping, I've done some work with the Oanda API using Python. I'm pretty new to C# though.

**Comment by mourednik** [comment]
@jilott I haven't. Unfortunately I don't think I will have time to work on this in the next few weeks.

**Comment by jilott** [comment]
Well, it may be a race then.

**Comment by mourednik** [comment]
Please go for it. If I do start working on it I will check with you first.

**Comment by jaredbroad** [comment]
Awesome guys. I wrote a few more tutorials on how to do this today which I'll push soon.

There is one change we will make in the next few days - a BrokerageSetupHandler. This would allow an implementation of a IBrokerage to more or less setup an algorithm. At the moment the setup process isn't very generic and we don't have the IBrokerage SetupHandler committed.

Best would be to focus efforts on implementing the current IBrokerage class methods - PlaceOrder etc. And in the next few days we'll add a few more methods to the IBrokerage interface which will ask for e.g. "GetCash", "GetPositions", "GetTrades".

**Comment by jaredbroad** [comment]
Closed in #78e12d7fe78cd87ff2e9ea67b71a7b965e64929c
