### ISSUE TITLE
Custom OHLC values are not correct

### ISSUE THREAD

**Issue by Waxavi** [QuantConnect/Lean#1903]
#### Expected Behavior

Formed H4 Bars from custom m1 data on Bitcoin should give this result (for this example let's show the first 3 bars):
![image](https://user-images.githubusercontent.com/12430398/39152375-ced8f538-470d-11e8-91e3-3b29e6d7adc1.png) 

#### Actual Behavior

Instead I'm getting these values (red marks incorrect values)
![image](https://user-images.githubusercontent.com/12430398/39152539-52f82546-470e-11e8-8408-2a48f5a3409a.png)

Close values are always correct, I only get a mismatch from O-H-L values.

#### Reproducing the Problem

* Formed custom data on Bitcoin.cs.
* On Main.cs used Consolidators and Identity to get H4 OHLC values.
* Printed OHLC values on the Log.
* Checked on a spreadsheet OHLC values on m1 vs H4 for the respective time period.
* Formed some H4 OHLC bars to highlight the difference.

[Spreadsheet link](https://docs.google.com/spreadsheets/d/1ASq7xewkJ-4MSi_2noF6vESJSC0w2_Vdqw_xDwIF694/edit?usp=sharing)
[Project used to retrieve m1 data and form H4 data](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_79af8f6d9e6df2f5dc90078d8540d502.html)

#### System Information

Lean Engine (C#):   Master (3330e0bbcd)

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by mchandschuh** [comment]
The problem here is that the bitcoin custom data type does not derive from TradeBar, so the consolidator is only consolidating based on the Value property, which equals the closing value. Try making the bitcoin custom data type derive from TradeBar and remove the duplicate OHLCV properties.

**Comment by mchandschuh** [comment]
Also, we should update the Bitcoin type in this project to subclass TradeBar, as well as update any documentation that uses the existing bitcoin custom data type.

Also, @Waxavi, we natively support bitcoin through gdax, can use `AddCrypto("BTCUSD", Resolution.Minute)`

Done via my phone, so apologies if things didn't get transcribed properly.

**Comment by Waxavi** [comment]
Hello @mchandschuh, thanks for your suggestion, I understand now why it's happening.

> Try making the bitcoin custom data type derive from TradeBar and remove the duplicate OHLCV properties.

I'll try this solution as soon as I can to check if it can solve it, I tried to use TradeBarConsolidator before but it didn't work for me.

I need specifically to use this data for the moment, but I've already made some tests with GDAX as well.

**Comment by Waxavi** [comment]
Followed your advice, however it doesn't read the data anymore.

[Link](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_d609d978c8df1df740b78be98aa5c349.html)

I'm probably missing something.

15 | 16:01:38: 
Backtest Handled Error: We could not fetch the requested data. This may not be valid data, or a failed download of custom data. Skipping source (/QuantConnect.Backtesting/data/base/usa/minute/btcusd/20140115_trade.zip).

**Comment by mchandschuh** [comment]
There are a couple things wrong. First, all custom data types **must** implement the `GetSource` *and* `Reader` methods. It looks like in this second rendition you removed the `Reader` method implementation so there was no way to read the data. Another, much less obvious error (I forgot about it), is when subclassing from `Tick`/`TradeBar`/`QuoteBar` for custom data, we must set `this.DataType = MarketDataType.Base` to ensure the engine knows the data isn't the normal pricing data.

I've updated the code to use the non-obsolete overrides. We'll eventually remove the obsolete versions, do you don't want to use them. I've also updated the code to set `this.DataType` correctly as well as to properly subclass `TradeBar`. The final edit (not as important, but good to do) was to set the `Symbol` property equal to `config.Symbol` to ensure we get the correct symbol reference. Using strings for symbols relies on some c# implicit operator magic. It works as expected 99% of the time, but just to be safe I like to avoid its usage.

@Waxavi -- where did you get the initial code for `Bitcoin.cs` ? We may need to update our documentation so it uses the non-obsoleted methods.

Here's a link to your modified code. 

https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_a949373f75fc5f7b9ee349a049f57bec.html

**Comment by Waxavi** [comment]
@mchandschuh  It works perfect now, there's no longer a mismatch between the 2 samples, thanks for guiding me.

Got the code from a forum post it's from 2014. [Link](https://www.quantconnect.com/forum/discussion/272/qcu-backtesting-bitcoin-custom-data-demonstration/p1)

Also here's on a doc: [Link](https://www.quantconnect.com/lean/documentation/topic16.html)

#### Warnings popped up on backtesting:

159 | 17:29:30: 
Build Warning: File: Bitcoin.cs Line:42 Column:31 - Member 'Bitcoin.GetSource(SubscriptionDataConfig, DateTime, DataFeedEndpoint)' overrides obsolete member 'BaseData.GetSource(SubscriptionDataConfig, DateTime, DataFeedEndpoint)'. Add the Obsolete attribute to 'Bitcoin.GetSource(SubscriptionDataConfig, DateTime, DataFeedEndpoint)'.
160 | 17:29:30: 
Build Warning: File: Bitcoin.cs Line:69 Column:33 - Member 'Bitcoin.Reader(SubscriptionDataConfig, string, DateTime, DataFeedEndpoint)' overrides obsolete member 'BaseData.Reader(SubscriptionDataConfig, string, DateTime, DataFeedEndpoint)'. Add the Obsolete attribute to 'Bitcoin.Reader(SubscriptionDataConfig, string, DateTime, DataFeedEndpoint)'.
161 | 17:29:30:

**Comment by mchandschuh** [comment]
Those warnings didn't pop up with the code I provided. I had updated the code to **not** use the obsoleted members. The documentation linked is referencing the obsoleted members which we'll fix soon. The correct methods to override for custom `BaseData` implementations are:
``` csharp
public virtual SubscriptionDataSource GetSource(SubscriptionDataConfig config, DateTime date, bool isLiveMode)
{
}
public virtual BaseData Reader(SubscriptionDataConfig config, string line, DateTime date, bool isLiveMode)
{
}
```
We no longer use the `DataFeedEndpoint` enumeration.

**Comment by mchandschuh** [comment]
Thanks @Waxavi for the links, closing this issue as resolved.
