### ISSUE TITLE
Security.IsTradable is never updated from true to false

### ISSUE THREAD

**Issue by StefanoRaggi** [QuantConnect/Lean#1917]
#### Expected Behavior
The `Security.IsTradable` property should be set to `false` when a security is delisted or, more generally, whenever we stop receiving price data, such as when removed from data feed (or end of subscription).

#### Actual Behavior
The `Security.IsTradable` property is never updated from `true` to `false`.
This property only has an initial value of `false` for canonical symbols and internal feeds.

#### Potential Solution
n/a

#### Reproducing the Problem
After a security is delisted, the `IsTradable` property still has a value of `true`.

#### System Information
n/a

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by mchandschuh** [comment]
This is resolved by https://github.com/QuantConnect/Lean/pull/1955 and https://github.com/QuantConnect/Lean/pull/1951

**Comment by mchandschuh** [comment]
Looks like this isn't getting flipped in the delisted case.
