### ISSUE TITLE
AddOptionContract() is unable to fetch the current price of the option contract

### ISSUE THREAD

**Issue by jingwu74** [QuantConnect/Lean#1937]
#### Expected Behavior

With OptionChainProvider, the specified option contract should be available to trade immediately after AddOptionContract(). 
#### Actual Behavior

As AddOptionContract() is unable to fetch the current price of the option contract, in the option algorithms using OptionChainProvider, the filtered contract should wait until next time step to be available to trade. The algorithm returns the error message like `
Backtest Handled Error: AMZN  170616C01000000: asset price is $0. If using custom data make sure you've set the 'Value' property.` 

#### Reproducing the Problem

https://github.com/QuantConnect/Lean/blob/master/Algorithm.CSharp/OptionChainProviderAlgorithm.cs
#### System Information

LEAN
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by mchandschuh** [comment]
We've decided that for now you can't add contract and purchase that contract on the same time step. This is actually (somewhat) realistic as far as running in live mode is concerned. For example, if we were to add a subscription for new data and on the very next line of code query the price, there's no guarantee that we would have received a tick for that contract yet (so price would still equal zero). The alternative is to issue a history request every time we add a subscription. We actually used to do this but determined that performance cost out weighed the marginal utility. For now you'll need to add the contract on one time step and on the next time step submit the order for the contract.
