### ISSUE TITLE
Docker Images can't be built on MAC OS X

### ISSUE THREAD

**Issue by facultywork** [QuantConnect/Lean#1959]
#### Expected Behavior
Run command at the bottom of 
https://github.com/QuantConnect/Lean/blob/master/DockerfileJupyter
Expect Docker images to be built correctly to use Lean on Mac OSX

#### Actual Behavior
The second command fails with error:
```
Step 10/15 : COPY ./Launcher/bin/Debug/ ${WORK}
COPY failed: stat /var/lib/docker/tmp/docker-builder108979428/Launcher/bin/Debug: no such file or directory
```

#### Potential Solution
Test the steps on a Mac OS computer and provide correct set of instructions to run the build the docker images and run the containers.

**Comment by jaredbroad** [comment]
I think this is a misunderstand of how to use that dockerfile. I'll see if we can add a tutorial on using LEAN and Docker. 

The dockerfile is all the background apps/libraries -- but you have to put your algorithm inside it. The file provided assumes that directory location; you just need to update it to your location.
