### ISSUE TITLE
Add Ability to Save Jupyter Notebooks

### ISSUE THREAD

**Issue by facultywork** [QuantConnect/Lean#1978]
Currently the `DockerfileJupyter` copies the notebooks from the `Launcher` diretory to working directory inside the Docker container https://github.com/QuantConnect/Lean/blob/master/DockerfileJupyter#L37

The problem is that by default changes to these files won't persist on the disk after the container will be stopped. I tried using a volume to run 

```
docker run -it -p 8866:8866 -v $(pwd)/Data:/home/Data:rw -v $(pwd)/Launcher/bin/Debug:/root/Lean/Launcher/bin/Debug:rw quantconnect/jupyter
``` 

and this solved the problem of persistance but then I wasn't able to load the Quantconnect packages inside the notebooks.

Is there a way we can get the best of both worlds, ie persistance of notebooks and loading of libraries? Currently I have to download the notebooks manually and rebuild the images everytime I want to stop the containers.

**Comment by AlexCatarino** [comment]
Please map the whole Lean tree:
```docker run -it --rm -p 8888:8888 -v ~/Lean/:/root/Lean/ quantconnect/jupyter```
and the notebooks will be saved at `/Lean/Launcher/bin/Debug` in the host.
