### ISSUE TITLE
Live GDAX tick aggregation stops in QueueHandler

### ISSUE THREAD

**Issue by multidis** [QuantConnect/Lean#1990]
#### Expected Behavior

LEAN should continue aggregating new ticks from GDAX when the exchange API operates normally.

#### Actual Behavior

After a minute or two since launch, the following error appears in the log:

20180509 03:26:28.098 ERROR:: BaseDataExchange.ConsumeEnumerators():  System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds
  at System.Array.Copy (System.Array sourceArray, System.Int32 sourceIndex, System.Array destinationArray, System.Int32 destinationIndex, System.Int32 length) [0x000da] in <2e7c1c96edae44d496118948ca617c11>:0
  at System.Collections.Generic.List`1[T].ToArray () [0x0000c] in <2e7c1c96edae44d496118948ca617c11>:0
  at QuantConnect.Brokerages.GDAX.GDAXDataQueueHandler.GetNextTicks () [0x00011] in <2de4b014f46d4e1cae01a4fd55fdb30c>:0
  at QuantConnect.Lean.Engine.DataFeeds.LiveTradingDataFeed+<GetNextTicksEnumerator>d__34.MoveNext () [0x0002f] in <65abdc8086e349878c640b36857f4e49>:0
  at QuantConnect.Lean.Engine.DataFeeds.BaseDataExchange.ConsumeEnumerators (System.Threading.CancellationToken token) [0x00089] in <65abdc8086e349878c640b36857f4e49>:0

Tick aggregation stops and the same prices propagate for every `OnData` step with forward-fill.

One **dangerous aspect** of this behaviour is that the algorithm may continue running while relying on outdated prices.

Exception described also [in google group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/lean-engine/NZpS6vWCS08/8Hte_0yJAwAJ)

#### Potential Solution

The error appears in `.ToArray` call [here](https://github.com/QuantConnect/Lean/blob/master/Brokerages/GDAX/GDAXDataQueueHandler.cs#L46)

Generally thread safety issues are mentioned in this context [SO1](https://stackoverflow.com/questions/19784704/c-sharp-system-argumentexception-destination-array-was-not-long-enough), [SO2](https://stackoverflow.com/questions/10362023/destination-array-not-long-enough)

#### Reproducing the Problem

Simple C# algorithm that logs bid/ask for BTCUSD with minute resolution. `config.json` with "live-gdax" setting, all of the defaults untouched. GDAX credentials for "view-only" account (although I can not see why that would matter).

#### System Information

Following [DockerfileLeanFoundation](https://github.com/QuantConnect/Lean/blob/master/DockerfileLeanFoundation) closely, i.e. Ubuntu baseimage with mono.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by StefanoRaggi** [comment]
@multidis Thanks for reporting the bug, nice catch!

The issue is that the `Ticks` list is not synchronized properly, in the `lock` statement it should use the same `_tickLocker` object used in `GDAXBrokerage.Messaging.cs` (`_tickLocker` will also need to be made `protected` instead of `private`).
