### ISSUE TITLE
Implements C# version of BlackLittermanPortfolioConstructionModel

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#1998]
#### Expected Behavior
C# and Python implementations of all models.

#### Actual Behavior
Missing Black Litterman implementation in C#.

#### Potential Solution
Port to C#: 
 https://github.com/QuantConnect/Lean/blob/master/Algorithm.Framework/Portfolio/BlackLittermanPortfolioConstructionModel.py

#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
We have tried to port the python version of [BlackLittermanPortfolioConstructionModel](https://github.com/QuantConnect/Lean/blob/master/Algorithm.Framework/Portfolio/BlackLittermanPortfolioConstructionModel.py) into C# using [MathNet](https://numerics.mathdotnet.com/) and [Accord](http://accord-framework.net/): [BlackLittermanPortfolioConstructionModel.cs](https://gist.github.com/AlexCatarino/4e62c5a2029b911ca482abfe716ab58e).

However, to our knowledge, neither of these libraries can find the minimum of a function given:
- Initial guess;
- Boundary conditions
- Internal constraint.

The function we want to minimize is the Sharpe Ratio, the initial guess if the equally weighted portfolio, the boundary conditions is that weights of each security must be between -1 and 1 and the internal constraint is that the sum of weights must be 1.

**Comment by TheLastTech** [comment]
Is this bounty still open?

**Comment by AlexCatarino** [comment]
@TheLastTech, yes: [Implements C# version of BlackLittermanPortfolioConstructionModel](https://www.bountysource.com/issues/58218760-implements-c-version-of-blacklittermanportfolioconstructionmodel).
Good luck!

**Comment by TheLastTech** [comment]
Cool, giving it a shot.

**Comment by wildart** [comment]
Unfortunately, without a proper nonlinear optimizer, it will be hard to get it work correctly.

**Comment by jaredbroad** [comment]
We have http://www.alglib.net/optimization package available in QC Cloud. Can assume safe to use here.
