### ISSUE TITLE
[Crypto] Implement Kraken bitcoin exchange

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#2003]
#### Expected Behavior
Lean supports [Kraken](https://www.kraken.com/) bitcoin exchange.

#### Actual Behavior
Not supported.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by goughlee** [comment]
As an fyi websockets for market data is [launching soon](https://blog.kraken.com/post/2019/websockets-public-api-launching-soon/) on the 30th Jan. Websockets for orders/trades on roadmap but no eta as yet.

**Comment by jaredbroad** [comment]
Cool! We'll need sockets for order events before we can add them properly. In the past, we've tried polling the API to reconcile trade differences but for many different reasons, it is not feasible.

**Comment by quantactic** [comment]
On 3th Jan already launched Websocket should make it possible now to reliably integrate with QC:
https://www.kraken.com/en-us/features/websocket-api

**Comment by StefanoRaggi** [comment]
@quantactic 
They released public WebSocket API for market data only, for QC integration we also need private WebSocket API for order events. 

> **Will there later be a WebSockets Private API to track my orders and trades?**
> Yes – we plan to offer this in the future but no ETA is available at this time.

Source: https://blog.kraken.com/post/2019/websockets-public-api-launching-soon/

**Comment by volemont** [comment]
@StefanoRaggi
Kraken released a private WebSocket API, see https://docs.kraken.com/websockets/

**Comment by rwentzel9** [comment]
I am now working on implementing the Kraken exchange in Lean, their upgraded Websockets are now live and should cover all the necessary bases.

**Comment by rwentzel9** [comment]
This is my first QuantConnect contribution so I am unsure on the usual timeframe for this making it into a release, but my personal goal is finishing the initial brokerage code by the end of May.

**Comment by automatedmachine** [comment]
@rwentzel9 I took at look at your Lean fork and didn't see any branches or commits for Kraken. I wouldn't mind taking a look at what you've done so far if you are willing to share. Having Kraken integration would be excellent!

**Comment by rwentzel9** [comment]
@automatedmachine I believe you should be able to see the changes on my fork now, let me know if not; I'm a bit new to Git. Thanks for being willing to take a look!

**Comment by automatedmachine** [comment]
Thanks for sharing that! I took a quick look, personally I haven't worked on a QC brokerage API so I don't have a lot of input to give at the moment, I see that you are still pretty early in the dev based on all the commented out code. I'll be happy to take a look and help with testing or anything as you progress further into it.

**Comment by behzad63** [comment]
Any new updates?

**Comment by tachera** [comment]
Kraken integration is exciting.  Is there an update when a release will be available? Many thanks!
