### ISSUE TITLE
GDAXDownloader crashes with System.NullReferenceException

### ISSUE THREAD

**Issue by sp4rc** [QuantConnect/Lean#2007]
#### Expected Behavior
Calling `QuantConnect.ToolBox.exe BTCUSD Daily "20180101 00:00:00" "20180512 00:00:00"`
should download historical data in CSV format to the data directory defined in config.json. 

I have created and verified my GDAX account, created an API key and entered it accordingly within Launcher\config.json 

#### Actual Behavior
After running the build it crashes with NullReferenceException. Please find output below (sorry I only have got the german output available): 

> C:\Dev\Projects\Lean\ToolBox\bin\Release (master -> origin)
λ QuantConnect.ToolBox.exe BTCUSD Daily "20180101 00:00:00" "20180512 00:00:00"
20180513 21:03:44.199 Trace:: Config.Get(): Configuration key not found. Key: data-directory - Using default value: ../../../Data
20180513 21:03:44.205 Trace:: Config.Get(): Configuration key not found. Key: map-file-provider - Using default value: LocalDiskMapFileProvider
20180513 21:03:44.213 Trace:: Getting data for timeperiod from 1/1/2018 12:00:00 AM to 5/12/2018 12:00:00 AM..
20180513 21:03:45.290 Trace:: WARNING: Web request failed with message Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.Retrying... 1 times
20180513 21:03:45.793 Trace:: WARNING: Web request failed with message Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.Retrying... 2 times
20180513 21:03:46.295 Trace:: WARNING: Web request failed with message Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.Retrying... 3 times
20180513 21:03:46.797 ERROR:: REQUEST FAILED: https://api.gdax.com/products/BTCUSD/candles?start=1/1/2018 12:00:00 AM&end=5/12/2018 12:00:00 AM&granularity=86400

> Unbehandelte Ausnahme: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei QuantConnect.Logging.WhoCalledMe.GetMethodName(Int32 frame) in C:\Dev\Projects\Lean\Logging\WhoCalledMe.cs:Zeile 36.
   bei QuantConnect.ToolBox.GDAXDownloader.Program.Main(String[] args) in C:\Dev\Projects\Lean\ToolBox\GDAXDownloader\Program.cs:Zeile 77.

#### System Information
Running Windows 10 Pro using .Net Framework 4.5.2

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Thanks for reporting solution @sp4rc
