### ISSUE TITLE
Download() ambiguous with a single argument

### ISSUE THREAD

**Issue by multidis** [QuantConnect/Lean#2030]
#### Expected Behavior

`Download("urlstring")` should work in C# as in the [docs example](https://www.quantconnect.com/docs/algorithm-reference/importing-custom-data#Importing-Custom-Data-Loading-Reference-Data)

#### Actual Behavior

ERROR: the call is ambiguous, 2nd argument is required to discern between IEnumerable and PyObject.

#### Potential Solution

Make Python method have a more specific signature?

We could of course pass some unimportant header as a part of the second argument, but it seems uncouth to instantiate a dummy enumerable.

#### Reproducing the Problem

`Download("urlstring")` in any basic C# algorithm, then try compiling/building an executable.

#### System Information

Mono on Ubuntu Linux, but that should not matter.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment]
Since we want to keep the same signature for C# and python, we could just have one overload:
```csharp
public string Download(string address, string json = null);
```
then we could parse the `json` into `Dictionary<string, string>`.
