### ISSUE TITLE
How do I add all the Crypto trading data I have

### ISSUE THREAD

**Issue by thegamecat** [QuantConnect/Lean#2043]
#### Expected Behavior
Put a csv into the Data folder that has timestamp(ms), ohcv, backtests select the data based upon a daterange or scan.

#### Actual Behavior
It seems there are daily files or something that doesn't make much sense.

#### Potential Solution
As above - singe csv, or better still a db like postgres.

#### Checklist

- [x ] I have completely filled out this template
- [ x] I have confirmed that this issue exists on the current `master` branch
- [ x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
See [readme](https://github.com/QuantConnect/Lean/blob/master/Data/readme.md) for data format required.
