### ISSUE TITLE
Support indirect/multi-leg currency conversions ( A->{Bridge Currencies}->B )

### ISSUE THREAD

**Issue by mchandschuh** [QuantConnect/Lean#2060]
#### Expected Behavior

The system is able to handle currency pairs that are not directly convertible into the account currency

#### Actual Behavior

The system is unable to perform currency conversions if it can't find a direct pair leading back to the account currency. On crypto exchanges, it's normal fare for currencies/tokens to not be directly convertible to fiat of any kind, for example, on binance *no* coins are directly convertible to fiat (USDT doesn't count :) ). In such cases we need to move through a 'bridge' currency, such as BTC and then can use a BTCUSD rate (maybe even a BTCUSDT if it's the best available), in order to price securities in terms of dollars (or whatever your account currency may be).

This can get unwieldy if you consider the above example but for an account currency of EUR. We now would require three 'legs', an additional one to move from USD (or USDT) to EUR, unless of course the exchange provides a BTCEUR pair of it's own to skip the USD middleman.

#### Potential Solution

> The below may have spiraled into stream of consciousness but I think the comments shed some light on some potential issues/solutions/paths forward so it's left unaltered.

I think to start we should list the various concerns and cases. The main issue I see here is that it's potentially unbounded (the number of potential paths from A->...>B) and may also be temporal, IOW, if there's multiple paths how do you choose which path is the right one (and be consistent!), so things like using market cap (or volume) to give preference to particular currencies to act as 'bridge' currencies can lead to different paths depending on market movement (which might actually be the right thing to do?).

Another thought is first limiting the unbounded aspect (say max of 3 hops? A -> Bridge1 -> Bridge2 -> B, maybe 4?) and could compute a range of potential conversion rates and pull the mean (would require some work to how we pull conversion rates)... I think in all cases the fact that we currently use the security's current price for the conversion rate should be decoupled so that there's a component that provides conversion rates (perhaps `IConversionRateProvider`) and he just so happens to be initialized with some securities, so a refactoring step could be creating this abstraction and implementing for the existing direct case A->B and then expand on that for cases where we require multiple hops.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by viliwonka** [comment]
I was thinking about this before.

We are dealing with graph with bidirectional connections.

Assets `ETH`, `USD`, `REN` are nodes. Pairs `ETHUSD`, `ETHREN` are connections between nodes.

Connections are not just string/name of pair, but also hold some sort of `List<T>`, where T is object that contains `IBrokerage`, `Price`, `Volume`.

For calculating most precise conversion between assets, for example `RENUSD`, we can use Max flow algorithm. 

Souirce node is REN, Sink node is USD.

Define `Volume` as a max flow through connection.

So ok, you run Max Flow algo, and you have now defined `Flow` on each connection.

`Flow` can be positive or negative, depends what is meant in each step, like RENETH (positive) or ETHREN (negative)?

Now, what is next step I am not sure, but it probably involves calculating `PriceStep = Price * Volume * Flow`.

And then somehow you need to propagate PriceStep again (maybe second iteration with MaxFlow) to get final result.

Will give more thought to this later, ok :)

**Comment by viliwonka** [comment]
Reserved for concerns.

Possible concerns:
- Market manipulations, wash trading (fake volume), pump & dumps
- Brokerages can get offline for time being, that shouldn't mess with multi-leg conversion

Suggestions:
- ConversionRateProvider object should be customizable, at-least by picking from what brokerages ticks should be pulled.

**Comment by viliwonka** [comment]
> I think to start we should list the various concerns and cases. The main issue I see here is that it's potentially unbounded (the number of potential paths from A->...>B) and may also be temporal, IOW, if there's multiple paths how do you choose which path is the right one (and be consistent!), so things like using market cap (or volume) to give preference to particular currencies to act as 'bridge' currencies can lead to different paths depending on market movement (which might actually be the right thing to do?).

So ok, this one may not be so hard. I came up with something:

You have graph `G` with bidirectional connections. `G` holds all known assets and pairs. 
Remember, node is asset, connection is pair.

You have `X` node and `Y` node. Example `X` = `REN`, `Y` = `USD`.
X and Y represent target pair you want to calculate.

And then you have list `P`. This list holds `Path`s, for example `REN-ETH-USD`.

Ok, now all you do is repeat this process:

1. Find shortest path `p` from `X` to `Y` in graph `G`. If none found, terminate.
2. Remove path `p` from `G` (remove connections), and add it to list `P` (nodes and connections)
3. Go to step 1.

That is, you should be left with all possible paths. The graph `G` will be left with un-related pairs and could be removed.

And `p` shouldn't hold any non-sense paths like 'REN-ZRX-ETH-BTC-USD'.

I am not sure what is metric/heuristic `d(x,y)` for shortest path yet, it can just be "hops between X and Y", or if it should include volume.

**Comment by viliwonka** [comment]
Link to the branch connected to this issue, just to show current progress. 
https://github.com/viliwonka/Lean/tree/feature-2060-multi-leg-currency-conversion

It's still in rough shape, still deciding how to execute this elegantly as possible - least modifications in lean source code, and some things are not seen in the code - "still on paper".
