### ISSUE TITLE
Data normalization mode is adjusted in option algorithms with OptionChainProvider 

### ISSUE THREAD

**Issue by jingwu74** [QuantConnect/Lean#2064]
#### Expected Behavior

The data normalization mode should be set to raw price in options algorithms with OptionChainPorvider
#### Actual Behavior

The warning message informs that `the equity security was set the raw price normalization mode to work with options.` but the security price is still adjusted.
#### Potential Solution

If commenting out `equity.SetDataNormalizationMode(DataNormalizationMode.Raw);`, the filling price of IBM at 2017-01-03 09:31:00 is `$157.665765117USD`, the raw price should be `$167.23USD`.
#### Reproducing the Problem

```using System.Linq;
using QuantConnect.Data;
using QuantConnect.Securities.Option;

namespace QuantConnect.Algorithm.CSharp
{

    public class OptionChainProviderAlgorithm : QCAlgorithm
    {
        private Symbol _equitySymbol;
        private Symbol _optionContract = string.Empty;

        public override void Initialize()
        {
            SetStartDate(2017, 1, 1);
            SetEndDate(2017, 1, 6);
            SetCash(100000);
            var equity = AddEquity("IBM", Resolution.Minute);
            // equity.SetDataNormalizationMode(DataNormalizationMode.Raw);
            _equitySymbol = equity.Symbol;
        }

        public override void OnData(Slice data)
        {
            if (!Portfolio[_equitySymbol].Invested)
            {
                MarketOrder(_equitySymbol, 100);
                Log(Securities[_equitySymbol].Price.ToString());
            }

            if (!(Securities.ContainsKey(_optionContract) && Portfolio[_optionContract].Invested))
            {
                var contracts = OptionChainProvider.GetOptionContractList(_equitySymbol, data.Time);
                var Calls = (from symbol in contracts
                                where symbol.ID.OptionRight == OptionRight.Call
                                select symbol);

                    _optionContract = Calls.OrderBy(x => x.ID.Date).FirstOrDefault();
                    AddOptionContract(_optionContract, Resolution.Minute);
           
            }
            if (Securities.ContainsKey(_optionContract) && !Portfolio[_optionContract].Invested)
            {
                MarketOrder(_optionContract, -1);
            }
        }
    }
}
```
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Tricky one; as the `AddOptionContract` can be added at any time. Really it should probably throw an exception if the underlying isn't already in raw mode; since in this example it will have run ahead at least a day and the price in the data feed buffer/cache will all be adjusted.

`throw new ArgumentException("The underlying asset is set to " + security.DataNormalizationMode + ", please change this to DataNormalizationMode.Raw with the SetDataNormalization() method");`
