### ISSUE TITLE
Fix Minimum Order Size for BCH

### ISSUE THREAD

**Issue by Waxavi** [QuantConnect/Lean#2067]
#### Expected Behavior

GDAX website specifies the minimum trading size for BCH is 0.01

> All Orders placed on GDAX are subject to the following minimum order sizes: 
> 
> BTC: 0.001 
> **BCH: 0.01** 
> ETH: 0.01 
> LTC: 0.1 
> USD: 10
> EUR: 10
> GBP: 10

#### Actual Behavior

Instead, I got this warning and error:

> Warning: Due to brokerage limitations, orders will be rounded to the nearest lot size of 1
> 
> 101 | 18:15:00: Unable to submit order with id -10 which quantity (0.01) is less than lot size (1).

#### Potential Solution

Update Minimum Lot Size for BCH

#### Reproducing the Problem

````
using QuantConnect.Brokerages;
using QuantConnect.Data;
using QuantConnect.Orders;
using System;
using QuantConnect.Securities.Crypto;

namespace QuantConnect.Algorithm.CSharp
{
    public class TestBCHIssue : QCAlgorithm
    {
        private string MySymbol = "BCHUSD";
        private Crypto Security;

        public override void Initialize()
        {
            SetBrokerageModel(BrokerageName.GDAX, AccountType.Cash);
            Security = AddCrypto(MySymbol, Resolution.Minute);
        }

        public override void OnData(Slice data)
        {
            if (!Portfolio.Invested)
            {
                MarketOrder(MySymbol, 0.01m);
            }
        }

        public override void OnOrderEvent(OrderEvent orderEvent)
        {
            Log(String.Format("Order Min Lot Size {0}", Security.SymbolProperties.LotSize));
        }
    }
}
````

#### System Information

LEAN: 68416d4c9a

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by StefanoRaggi** [comment]
Hi @Waxavi,
thanks for the report, it seems that the symbol properties database csv file in the QC cloud server is out of date and does not include the BCH pairs, we'll fix it as soon as possible.

The **lot size** (used for rounding order sizes) is defined in the symbol properties database and is set to 0.00000001 for all crypto pairs:
https://github.com/QuantConnect/Lean/blob/master/Data/symbol-properties/symbol-properties-database.csv#L240

The **minimum order size** for crypto pairs is defined in the GDAXBrokerageModel here:
https://github.com/QuantConnect/Lean/blob/master/Common/Brokerages/GDAXBrokerageModel.cs#L34

**Comment by Waxavi** [comment]
Thanks @StefanoRaggi 

Yes, I was confused by the GDAXBrokerageModel, but the property Security.SymbolProperties.LotSize was giving me a value of 1, so I knew there was a problem but couldn't find where.

**Comment by jaredbroad** [comment]
Thanks @Waxavi we've updated the cloud and it'll be patched in production in the next few days ago.

**Comment by voidale** [comment]
@jaredbroad It looks like this is back again? I'm hitting `Backtest Handled Error: Unable to submit order with id -10 which quantity (0.522753039693893670780046202) is less than lot size (1).` for `SetBrokerageModel(BrokerageName.Bitfinex, AccountType.Margin);` I've shared a reproducible algo with you via Share :)
