### ISSUE TITLE
TimeRules in schedule Event counts non-trading hours 

### ISSUE THREAD

**Issue by jingwu74** [QuantConnect/Lean#2075]
#### Expected Behavior

The scheduled event should only take the trading hours into account.
#### Actual Behavior

Schedule Event counts non-trading hours. The function is fired multiple times after the market opens.
#### Reproducing the Problem

```using System;
using QuantConnect.Data;

namespace QuantConnect.Algorithm.CSharp
{
    public class ScheduledEventsAlgorithm : QCAlgorithm
    {
        public override void Initialize()
        {
            SetStartDate(2013, 10, 07); 
            SetEndDate(2013, 10, 09);   
            SetCash(100000);             
            AddSecurity(SecurityType.Equity, "SPY", Resolution.Minute);
             
            Schedule.On(DateRules.EveryDay(), TimeRules.Every(TimeSpan.FromMinutes(120)), () =>
            {
	         Log("rebalance");
            });
        }
    }
}
```
The schedule function is fired multiple times at `09:31:00` each day.
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by mchandschuh** [comment]
@jingwu74  -- as defined, it will fire every single day. If you want it to perform every trading day, you need to use `DateRules.EveryDay("SPY")`. This will at least cause the event to fire only on trading days. It looks like we may need a small refactor to make `TimeRules.Every` respect the market hours if defined in the selected `DateRules`

**Comment by mchandschuh** [comment]
@jaredbroad -- any thoughts here?

**Comment by jaredbroad** [comment]
I'd prefer to leave API as it is as majority of people are understanding just fine. I think the confusion was the "firing multiple times at 931" which is because it's not emitting data from 4pm -> 9.31am so all those events were triggered at once with the Algorithm Time unchanged.

Perhaps we rename issue -> feature/bug -> "Make Scheduled Events Trigger at Algorithm Time in Backtesting"

**Comment by jaredbroad** [comment]
Not a bug
