### ISSUE TITLE
Inconsistent behavior using AddUniverse, OnData not fired first day

### ISSUE THREAD

**Issue by Jay-Jay-D** [QuantConnect/Lean#2095]
#### Expected Behavior

`OnData`must be fired on new data the algorithm's first day.

#### Actual Behavior

When `AddUniverse` is used instead of adding the securities _manually_, `OnData`is not fired on the algorithm's first day.
Also the Logs timestamp are not consistent (check log output below).

#### Reproducing the Problem

```cs
namespace QuantConnect.Algorithm.CSharp
{
    public class OnDataNotFiredFirstDay : QCAlgorithm
    {
        private Symbol _spy = QuantConnect.Symbol.Create("SPY", SecurityType.Equity, Market.USA);
        private int _timesOnDataIsCalled = 0;

        public override void Initialize()
        {
            SetStartDate(2013, 10, 07);  //Set Start Date
            SetEndDate(2013, 10, 08);    //Set End Date
            SetCash(100000);             //Set Strategy Cash

            UniverseSettings.Resolution = Resolution.Hour;
            Schedule.On(DateRules.EveryDay(), TimeRules.At(15, 0), Testing);
            
            // Green case
            // AddEquity("SPY", Resolution.Hour);
            // Red case
            AddUniverse(CoarseSelectionFunction, FineSelectionFunction);
        }
        
        public IEnumerable<Symbol> CoarseSelectionFunction(IEnumerable<CoarseFundamental> coarse)
        {
            return new[] { _spy };
        }

        public IEnumerable<Symbol> FineSelectionFunction(IEnumerable<FineFundamental> fine)
        {
            return new[] { _spy };
        }

        public override void OnData(Slice data)
        {
            _timesOnDataIsCalled++;
        }
        
        public void Testing()
        {
        	Log($"Scheduled event fired at {Time:F}");
            if (_timesOnDataIsCalled == 0)
            {
                Log("ERROR: OnData wasn't fired even once!");
            }
            else
            {
            	Log($"OnData was fired {_timesOnDataIsCalled} times.");
            }
        }
    }
}
```
Green case log:
```
2013-10-07 15:00:00 Scheduled event fired at Monday, October 7, 2013 3:00:00 PM
2013-10-07 15:00:00 OnData was fired 5 times.
2013-10-08 15:00:00 Scheduled event fired at Tuesday, October 8, 2013 3:00:00 PM
2013-10-08 15:00:00 OnData was fired 12 times.
```
Red case log:
```
2013-10-08 00:00:00 Scheduled event fired at Monday, October 7, 2013 3:00:00 PM
2013-10-08 00:00:00 ERROR: OnData wasn't fired even once!
2013-10-08 15:00:00 Scheduled event fired at Tuesday, October 8, 2013 3:00:00 PM
2013-10-08 15:00:00 OnData was fired 5 times.
```

#### System Information

Algorithm lab.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by mchandschuh** [comment]
This isn't a bug, but a misunderstanding. The coarse data for 2013.10.07 is fed into the coarse selection function at 2013.10.08 00:00. As such, we're not selecting securities until the Tuesday the 8th, and from your logs it appears that we were able to receive data starting on the 8th as expected.

Universe selection is data driven, meaning, we don't perform universe selection unless there's data available to feed into the selection functions. For fundamental universes, we're using daily fundamental data, which is available the following day at midnight (data from Monday available Tuesday at midnight, the first moment of Tuesday). At this time we perform universe selection and SPY gets selected as expected.

**Comment by garyha** [comment]
Can you suggest an easiest way to avoid trading on the first day specified as the start of a backtest a workaround? I need to open positions using limit so I need the price data. It would be handier if data were there on the first day. (Sounds like it wouldn't be possible in the underlying code to pull data from the day before the backtest SetStartDate()). Thanks!

**Comment by jaredbroad** [comment]
>"Sounds like it wouldn't be possible in the underlying code to pull data from the day before the backtest SetStartDate()"

We had it this way but people's market orders were filling on stale data. So we made a decision that the lesser of two evils was to make people wait for fresh data. Ultimately we'd like a hybrid and are building an elegant way to do it.
