### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by LuigiBaute** [QuantConnect/Lean#2106]
Greetings @quantconnect-server   @quantconnect ,

I was passing by (this repository) and tought I'd like to collaborate by proposing a logo
if that's something that may interest you! let me know!

I'm a Graphic Designer and an Open Source enthusiastic
looking to improve my portfolio and collaborate to really cool projects like this one!

Best Regards,
-Luigi.

**Comment by jaredbroad** [comment]
Thank you for the offer Luigi! =) Literally 2 weeks ago we crowdsourced a logo and updated it recently to this: https://camo.githubusercontent.com/c0e716c01b2fd66164fdc6fe8d2ca81f8ac18bcb/68747470733a2f2f63646e2e7175616e74636f6e6e6563742e636f6d2f7765622f692f32303138303630312d313631352d6c65616e2d6c6f676f2d736d616c6c2e706e67
