### ISSUE TITLE
Doesn't deal with algorithms with subnames

### ISSUE THREAD

**Issue by Worthy7** [QuantConnect/Lean#2110]
https://github.com/QuantConnect/Lean/blob/1900e1d2678feae68859df458df7ba8160f4ea03/Common/Extensions.cs#L924

This line threw errors (only in live mode for some reason) with I have the algo names:
PnFReversal
PnFReversalLarge

and my config was `PnFReversal`

I propose we change `Contains` to `EndsWith`

**Comment by mchandschuh** [comment]
Closed by #2111
