### ISSUE TITLE
Cancelled Order Status should only be set following OrderStatusChanged event from brokerage

### ISSUE THREAD

**Issue by mchandschuh** [QuantConnect/Lean#2143]
#### Expected Behavior

Order statuses (except order invalidation) should be set in response to receiving an event from the brokerage. @Martin-Molinero identified two cases which don't follow this pattern, both pertaining to order cancellations.

#### Actual Behavior

`BrokerageTransactionHandler` is setting `order.Status = OrderStatus.Canceled` in response to `brokerage.CancelOrder` returning true, but this return value only means we were successful in submitting a request to cancel the order and not that the order was actually canceled (may need to update `IBrokerage.CancelOrder` documentation here). Also, the `BrokerageTransactionHandler` is marking `order.Status = OrderStatus.CancelPending` -- but this is probably better handled via the individual brokerage implementations emitting an `OrderStatusChanged` event stating that cancellation is pending.

#### Potential Solution

Review `BrokerageTransactionHandler` and remove cases where we set `order.Status` directly. We can leave cases where an order is determined to be invalid, but in these cases we should still firing the event handler so it gets patched through the algorithm properly. The `CancellationPending` status is a little different in that it exists to notify the algorithm that the transaction handle has received the request to cancel an order but hasn't submitted it to the brokerage. We'll need to review usage of this status.

#### Reproducing the Problem

Problem identified through code review. This behavior has also been reported in the slack channel and can be observed by cancelling an order and immediately checking `order.Status` and noting it says canceled (assuming the `brokerage.CancelOrder` returns true), even though the order cancellation may still be pending.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by mchandschuh** [comment]
Also, it seems that in some cases we invalidate the entire _order_ even though only the order _request_ was invalid. This should also be investigated.

**Comment by mchandschuh** [comment]
Invalidating an order based on an invalid update request:
https://github.com/QuantConnect/Lean/blob/master/Engine/TransactionHandlers/BrokerageTransactionHandler.cs#L846

**Comment by Martin-Molinero** [comment]
We've agreed to leave `CancelPending` where it is, since its original purpose was to be synchronous with the call and the broker is invoked async by another thread.
