### ISSUE TITLE
ITransactionHandler shouldn't allow direct access to Orders and OrderTickets

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#2149]
#### Expected Behavior

ITransactionHandler should expose a wrapper for the desired operations on the raw structures

#### Actual Behavior

ITransactionHandler is currently exposing both `ConcurrentDictionary<int, Order> Orders` and `ConcurrentDictionary<int, OrderTicket> OrderTickets`

#### Potential Solution

Refactor ITransactionHandler: Define the required interface and its implementation where it is used.

#### Reproducing the Problem

N/A

#### System Information

N/A

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by mchandschuh** [comment]
> Working this before PRing for https://github.com/QuantConnect/Lean/issues/2128 as the exposed data is causing additional complications in splitting order collections into open/closed sets.

**Comment by jaredbroad** [comment]
Is this issue pending?

**Comment by mchandschuh** [comment]
Closing as OBE
