### ISSUE TITLE
Update GDAX to use new coinbase pro endpoints

### ISSUE THREAD

**Issue by mchandschuh** [QuantConnect/Lean#2154]
#### Description
We'll need to update the REST endpoints used in the `GDAXBrokerage` implementation.

Email from coinbase:
```
On Friday June 29, we say goodbye to GDAX and hello to Coinbase Pro. To take full advantage of this upgrade, we recommend you start using pro.coinbase.com now.

Coinbase Pro is a new interface built on top of the existing GDAX trading engine. As a result, your entire account history and all balances will be shown on Pro. No action is necessary from you.

Any balances in your GDAX wallets will automatically be shown on Coinbase Pro
Any trading history on GDAX will automatically be shown on Coinbase Pro
Accessing GDAX.com after June 29 will result in being redirected to Coinbase Pro
GDAX API Integrations:

There will be no disruption to the gdax.com API during this time. GDAX APIs will continue to function until December 31, 2018.
We encourage Coinbase Pro users to begin migrating their API usage away from api.gdax.com to api.pro.coinbase.com.
Coinbase Pro is currently live and we encourage all users to update their bookmarks and try our upgraded trading experience today.
```

#### Potential Solution
Confirm and update existing GDAX endpoints to use the new endpoints.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by StefanoRaggi** [comment]
In the email GDAX only mentions the REST base URL, we also need to make sure if the WebSocket base URL is going to change or not: currently the base URL is `wss://ws-feed.gdax.com`
