### ISSUE TITLE
Liquidate cancels open orders, SetHoldings(0) does not

### ISSUE THREAD

**Issue by StefanoRaggi** [QuantConnect/Lean#2162]
#### Expected Behavior
It would be desirable to have the same behavior for these two method invocations (both cancel open orders or both do not).

#### Actual Behavior
Currently `Liquidate(symbol)` cancels open orders, while `SetHoldings(symbol, 0)` does not.

#### Potential Solution
We could make these two method calls behave identically in two ways:
- both methods cancel open orders
- both methods do not cancel open orders

If `SetHoldings(0)` is changed to cancel open orders, should it be done for *any* `SetHoldings` call?
This issue is open for discussion.

#### Reproducing the Problem
Any algorithm (backtest or live) can be used to see the difference.

#### System Information
n/a

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
- SetHoldings(0) would set an order for the delta with the existing open orders; then the open orders would fill to a 0 holding.
 - Canceling all would be pretty noisy and unsure if it would work in live trading. 
 - Marking complete as #2180 applied memory of open orders.
