### ISSUE TITLE
No Exports Corresponding to QuantConnect.ToolBox.IEX.IEXDataQueueHandler 

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#2174]
#### Expected Behavior
IEX IDQH would work in LEAN configuration.

#### Actual Behavior
No exports exception

#### Potential Solution
Add Export line to the class.

#### Reproducing the Problem
Set IDQH as a live feed in config.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by StefanoRaggi** [comment]
The `IEXDataQueueHandler` is currently working with this configuration:
```
    "paper-iex": {

      "live-mode": true,

      // real brokerage implementations require the BrokerageTransactionHandler
      "live-mode-brokerage": "PaperBrokerage",

      "data-queue-handler": "QuantConnect.ToolBox.IEX.IEXDataQueueHandler",
      "setup-handler": "QuantConnect.Lean.Engine.Setup.BrokerageSetupHandler",
      "result-handler": "QuantConnect.Lean.Engine.Results.LiveTradingResultHandler",
      "data-feed-handler": "QuantConnect.Lean.Engine.DataFeeds.LiveTradingDataFeed",
      "real-time-handler": "QuantConnect.Lean.Engine.RealTime.LiveTradingRealTimeHandler",
      "transaction-handler": "QuantConnect.Lean.Engine.TransactionHandlers.BacktestingTransactionHandler",
      "history-provider": "BrokerageHistoryProvider"
    }
```
Only thing missing to fully support local IEX usage is the history provider, as mentioned here:
https://github.com/QuantConnect/Lean/issues/2178
