### ISSUE TITLE
Create ToolBox/IEX Data Downloader

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#2178]
#### Expected Behavior
Processor for the new IEX data dumps

#### Actual Behavior
No data processor found.

#### Potential Solution
Create an `IEXDataDownloader` for downloading the IEX zips & converting them to LEAN format.
https://iextrading.com/trading/market-data/#hist-download
https://iextrading.com/developer/docs/#hist

 - Save data to a local cache folder and search the compressed files for the symbols requested.
 - Use the `LeanDataWriter` class to convert the ticks into bars as requested by the DataDownloader interface and save the files to the local disk in LEAN format.  

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by StefanoRaggi** [comment]
To maximize code reuse, we could also implement `IHistoryProvider` in `IEXDataQueueHandler` and make the `IEXDataDownloader` simply call the history provider. This pattern has already been used for other brokerages.

**Comment by wildart** [comment]
It is not trivial task, those IEX archived blobs are packet streams in IEX-TP v1 protocol. One would need to figure out how to read pcap format from C#, and then parse it for ticks, probably aggregate for different resolution. BWT, they are huge - uncompressed several GB for just for one day.
