### ISSUE TITLE
[Question] Backtesting performance

### ISSUE THREAD

**Issue by DummyCo** [QuantConnect/Lean#2194]
Hi there! I'm performing experiments with LEAN backtesting and high-performance computing.
Master software is starting hundreds of LEAN launcher instances in my setup on hi-end HPC configurations. Algorithm result json storing and file logging are turned off to evade unnecessary load and file write conflicts.
The problem is all about very poor backtesting performance. Typical algorithm configuration with dozen of rolling windows and indicators on minute resolution and 15-minute consolidation (where all the windows are updated) on 10-years duration takes up to 1 minute to backtest.
Is it possible to dramatically increase backtesting performance?
There are some release run profiling results:
![sshot](https://user-images.githubusercontent.com/3989453/42207602-fbffa318-7eb2-11e8-94bc-8983f67cdc71.png)

**Comment by jaredbroad** [comment]
Debugging user custom applications is done in the LEAN user forum. Can you post as much information as possible there? https://www.quantconnect.com/forum/discussions/1/lean

I.e. algorithm, environment, data used, kps recorded, CPU. Ram. Disk type, processes per node.
