### ISSUE TITLE
OandA Fires duplicate events occasionally

### ISSUE THREAD

**Issue by Worthy7** [QuantConnect/Lean#2204]
#### Expected Behavior
Only one event

#### Actual Behavior
Sometimes two of the exact same event

#### Potential Solution
No idea.

#### Reproducing the Problem
Cannot easily reproduce.

#### System Information
Here is a screenshot of the orders, complete with BrokerId ticket
![image](https://user-images.githubusercontent.com/4762399/42256569-1f8deb16-7f8d-11e8-9368-dd5541f0116b.png)

Here is my output log:

> 20180704 13:16:02.177 Trace:: BrokerageTransactionHandler.OrderStatusChanged(): Time: 2018/07/04 4:16:02 OrderID: 2 Symbol: EURUSD Status: Submitted BrokerId: 1162
> 20180704 13:16:02.178 Trace:: LiveTradingResultHandler.OrderEvent(): Time: 2018/07/04 4:16:02 OrderID: 2 Symbol: EURUSD Status: Submitted
> 20180704 13:16:02.181 Trace:: BrokerageTransactionHandler.OrderStatusChanged(): Time: 2018/07/04 4:16:02 OrderID: 2 Symbol: EURUSD Status: Filled Quantity: 2136000 FillPrice: 1.16646 USD Message: Oanda Fill Event BrokerId: 1162
> 20180704 13:16:02.181 Trace:: BrokerageTransactionHandler.OrderStatusChanged(): Time: 2018/07/04 4:16:02 OrderID: 2 Symbol: EURUSD Status: Filled Quantity: 2136000 FillPrice: 1.16646 USD Message: Oanda Fill Event BrokerId: 1162
> 20180704 13:16:02.189 Trace:: Debug: New Order Event: Time: 2018/07/04 4:16:02 OrderID: 2 Symbol: EURUSD Status: Submitted
> 20180704 13:16:02.261 Trace:: LiveTradingResultHandler.OrderEvent(): Time: 2018/07/04 4:16:02 OrderID: 2 Symbol: EURUSD Status: Filled Quantity: 2136000 FillPrice: 1.16646 USD Message: Oanda Fill Event
> 20180704 13:16:02.272 Trace:: Debug: New Order Event: Time: 2018/07/04 4:16:02 OrderID: 2 Symbol: EURUSD Status: Filled Quantity: 2136000 FillPrice: 1.16646 USD Message: Oanda Fill Event
> 20180704 13:16:02.289 Trace:: LiveTradingResultHandler.OrderEvent(): Time: 2018/07/04 4:16:02 OrderID: 2 Symbol: EURUSD Status: Filled Quantity: 2136000 FillPrice: 1.16646 USD Message: Oanda Fill Event
> 20180704 13:16:02.295 Trace:: Debug: New Order Event: Time: 2018/07/04 4:16:02 OrderID: 2 Symbol: EURUSD Status: Filled Quantity: 2136000 FillPrice: 1.16646 USD Message: Oanda Fill Event

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues) (There are dup closed issues)

- [ ] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Are you using latest version of master? We had a similar issue about 2/3 mo
ago but thought we fixed it.

**Comment by Worthy7** [comment]
As I said yes I am

**Comment by Worthy7** [comment]
You're talking about this
https://github.com/QuantConnect/Lean/pull/1271

I don't know what exactly the problem was back then as I don't think I was using live at that point. But the problem exists on the current master branch, and it is definitely intermittent - it happens randomly at OandA's descretion. It's really a bug on their end.

I don't know the great inner workings of Lean, but it seems that simply ignoring updates where the update has already been applied might be the way to go.
Since it is very specific to OandA, it might be worth adding a `Warning:Oanda sent fill where fill was already registered for OrderID: 3` message just to alert users that it happened.

**Comment by Worthy7** [comment]
Hold on I'll believe this when I see it lol

**Comment by mchandschuh** [comment]
@Worthy7 - yes! Please let me know if you find anything and if possible, some detailed logging to accompany any errors or unexpected behavior.

**Comment by Worthy7** [comment]
I ran a simple algo all day, seems to be fine! Thanks a lot @Martin-Molinero !
