### ISSUE TITLE
Error message when algorithm is not found is unclear

### ISSUE THREAD

**Issue by mblouin02** [QuantConnect/Lean#2205]
#### Expected Behavior
In config.json, when selecting an algorithm type name that does not exist, the error message in the log should clearly identify that the algorithm specified was not found.

#### Actual Behavior
In config.json, when selecting an algorithm type name that does not exist, the error message is confusing. It mentione "Unable to resolve multiple algorithm types to a single type...".

#### Potential Solution
Clarify the log. Maybe change the log message so that it says "cannot find the algo, or cannot resolve multiple algorithm types".

#### Reproducing the Problem
- In config.json, write an algorithm type name that does not exist.
- Launch the algorithm.

#### System Information
- Windows 10

#### Checklist
- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by mchandschuh** [comment]
Merged #2206
