### ISSUE TITLE
Update Open Source Data

### ISSUE THREAD

**Issue by mchandschuh** [QuantConnect/Lean#2208]
#### Description
Over time we've improved the way we process our data sets, and as such, the open source data sets don't match what we run in production. This difference is causing issues with our automated regression system. Let's update the data to the current baseline and in the future be more diligent about updating the data when we make changes/improvements to the formats and/or aggregation process.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Jay-Jay-D** [comment]
In order to get the same results locally and in the cloud for #2241, the GC data must be updated.
