### ISSUE TITLE
IEXDataFeedHandler data feed not working

### ISSUE THREAD

**Issue by mblouin02** [QuantConnect/Lean#2220]
#### Expected Behavior
- When selecting IEXDataQueueHandler as a live source in config.json, the algorithm should launch, and should connect correctly to IEX data stream.
- In the logs, the following two log messages should appear:
    - "IEXDataQueueHandler.Reconnect(): Connected to IEX live data"
    - "IEXDataQueueHandler.Reconnect(): IEX Real-Time Price"

#### Actual Behavior
- No connection is made with IEX.

#### Potential Solution
- Update Socket IO NuGet packages
- Increase the reconnection delay in IEXDataQueueHandler.cs (potential connection thread timing issue)

#### Reproducing the Problem
- Select a live environment in config.json
- In config.json, set the "data-queue-handler" to "QuantConnect.ToolBox.IEX.IEXDataQueueHandler"
- Launch LEAN
- Look in the logs, the log connection log message does not appear

#### System Information
- Windows 10

#### Checklist
- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [X] I have provided detailed steps to reproduce the issue

**Comment by mblouin02** [comment]
Note: I have fixed this issue locally. Pull request to come soon,

**Comment by jaredbroad** [comment]
Merged in #2222
