### ISSUE TITLE
GetMappedSymbol is returning empty causing an invalid file source

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#2223]
#### Expected Behavior

GetMappedSymbol should return the same symbol if we don't have a map file for it
#### Actual Behavior

GetMappedSymbol called at https://github.com/QuantConnect/Lean/blob/master/Engine/DataFeeds/Enumerators/Factories/BaseDataSubscriptionEnumeratorFactory.cs#L79 is returning an empty string due to `public string GetMappedSymbol(DateTime searchDate)` at MapFile.cs returning empty string due to `_data.Keys` being empty.  
#### Potential Solution

If `public string GetMappedSymbol(DateTime searchDate)` at MapFile.cs, returns an empty string, use the same symbol.
#### Reproducing the Problem

Options algorithm using symbol 'SVXY'
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by mchandschuh** [comment]
`SubscriptionDataSourceReader.cs` L565
```
                // check to see if the symbol was remapped
                var newSymbol = _mapFile.GetMappedSymbol(date);
                if (newSymbol != _mappedSymbol)
                {
                    if (_mappedSymbol != "")
                    {
                        var changed = new SymbolChangedEvent(_config.Symbol, date, _mappedSymbol, newSymbol);
                        _auxiliaryData.Enqueue(changed);
                    }
                    _config.MappedSymbol = _mappedSymbol = newSymbol;
                }
```
Here's how it was handled at the other call site -- recommend pushing this down into the `GetMappsSymbol` implementation so callers don't need to worry about it -- so the method should return the mapped symbol or the input symbol if no mappings found.
