### ISSUE TITLE
BTC futures expiration dates incorrect

### ISSUE THREAD

**Issue by gurusawhney** [QuantConnect/Lean#2225]
#### Expected Behavior

BTC future contract expiry dates should be on the last Friday of the contract month.

#### Actual Behavior

The contract expiry dates are currently on the 1st of the contract month.

#### Potential Solution

Add a crypto class in Future.cs
```cs
public static class Crypto 
{
    public const string Bitcoin = "BTC"; 
}
```
Add function to find last Friday of each month in FuturesExpiryUtilityFunctions.cs
```cs
public static DateTime LastFriday(DateTime time)
{
    var daysInMonth = DateTime.DaysInMonth(time.Year, time.Month);
    return (from day in Enumerable.Range(1, daysInMonth)
    where new DateTime(time.Year, time.Month, day).DayOfWeek == DayOfWeek.Friday
    select new DateTime(time.Year, time.Month, day)).Last();
}
```
Add BTC with the function in FuturesExpiryFunctions.cs
```cs
//BTC: https://www.cmegroup.com/trading/equity-index/us-index/bitcoin_contract_specifications.html
{Futures.Crypto.Bitcoin, (time =>
    {
        // 4:00 p.m. London Time on the last Friday of the contract month.
        var lastFriday = FuturesExpiryUtilityFunctions.LastFriday(time);
        return lastFriday.Add(new TimeSpan(16,0,0));
    })
},
```

#### Reproducing the Problem

Printing out expiry dates for BTC contracts like below:
```cs
public class FuturesAlgorithm : QCAlgorithm
{	
	private Future future;
	
	public override void Initialize()
	{
		SetStartDate(2018, 04, 12);
		SetEndDate(2018, 05, 17);
		SetCash(100000);
		
		future = AddFuture("BTC", Resolution.Minute);
		future.SetFilter(TimeSpan.Zero, TimeSpan.FromDays(92));
	}
	
	public override void OnData(Slice data)
	{
	
		foreach(var chain in data.FutureChains)
		{
			foreach(var cc in chain.Value)
			{
				Log($"symbol: {cc.Symbol.Value} exp: {cc.Expiry}");
			}
		}
	}
}
```
#### Checklist

- [x] I have completely filled out this template
- [ ] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by gsalaz98** [comment]
Fixed by https://github.com/QuantConnect/Lean/commit/44a4451ea3a9e28420b8826f3618f04bf1ff6635
