### ISSUE TITLE
When launching LEAN locally, command-line argument "--config" does not work

### ISSUE THREAD

**Issue by mblouin02** [QuantConnect/Lean#2249]
#### Expected Behavior
When specifying the command-ling argument "--config <path to config file>" when launching Quantconnect.Lean"Launcher.exe, the data from the specified config file should be used.

#### Actual Behavior
When specifying the a local config file as an argument, we get a log that claims that this file will be used for the configuration. However, values from the default config file location are used instead.

#### Potential Solution
I actually diagnosed this issue. It comes from the fact that, in Config.cs, the "Settings" singleton is instantiated before the main program gets the chance to read the command-line arguments. In other words, the config file is read when the static variables get created, which happens before program execution.

The solution would be to add "Config.Reset()" after the program read command-line arguments, in order to re-read the settings from the correct config file.

#### Reproducing the Problem
1- Copy ".\Launcher\config.json" to another location (ex: C:\Launcher\config.json).
2- Rename the new file config_UseThisOne.json
3- In config_UseThisOne.json, change "environment" to "live-paper" instead of "backtesting"
4- In Visual Studio, add a break point in Program.cs, line 58 (var liveMode = Config.GetBool("live-mode");)
5- Launch in debug mode, by passing the argument "--config <path to config_UseThisOne.json> file"
6- Step-over the line, so that "live-mode" gets populated
7- Notice that the variable liveMode is false, it should be true.

8- Now, stop the program.
9- In ".\Launcher\config.json", change "environment" to "live-paper" instead of "backtesting"
10- Repeat steps 5-7, notice that the value is now properly "true"

#### System Information
- Windows 10

#### Checklist
- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues]
- [X] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Thanks @mblouin02 sounds broken -- we'll look into it further.

**Comment by mblouin02** [comment]
Hi Jared, 

See this pull request, it should fix the issue: https://github.com/QuantConnect/Lean/pull/2251

**Comment by StefanoRaggi** [comment]
Closed by #2251
