### ISSUE TITLE
Integration with Tiingo custom data

### ISSUE THREAD

**Issue by StefanoRaggi** [QuantConnect/Lean#2252]
We should support `Tiingo` services as custom data:
- EOD Price data: https://api.tiingo.com/services/tiingo/daily
- News data: https://api.tiingo.com/services/tiingo/news

API:
- https://api.tiingo.com/docs/tiingo/daily
- https://api.tiingo.com/docs/tiingo/news

**Comment by mchandschuh** [comment]
Merged in #2255
