### ISSUE TITLE
Renko Tradebars

### ISSUE THREAD

**Issue by xenu256** [QuantConnect/Lean#23]
Used to make price action (time eliminated) bars to make more better trends.

**Comment by jaredbroad** [comment]
In what sense @xenu256? Guess doesn't apply to equity so it would be firing TradeBar events to OnData based on price movement?

**Comment by xenu256** [comment]
Can be applied to everything as it is same TradeBar, just with same range, made from ticks, so basically, just consolidator is needed (each bar would have different start time), then those bars can be feed into OnData as usual.

**Comment by mchandschuh** [comment]
I've started working on this and have an implementation that uses a new RenkoConsolidator to consolidate TradeBar data into RenkoBar data. I'll need to implement in a similar pattern as the TradeBarConsolidator, which now supports BaseData,DynamicData, Tick and TradeBar

**Comment by mchandschuh** [comment]
The RenkoConsolidator class has been added. It allows you to define your renko bar size, as well as provides for value and volume selectors. A sample algorithm, RenkoConsolidatorAlgorithm, has also been added showing the usage.
