### ISSUE TITLE
Data before start date included after warm up period ended

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#2325]
#### Expected Behavior
After warming up period is ended, `OnData` only receives data with `EndTime` that is greater then `IAlgorithm.StartDate`. In other words, the first `Slice` object after `StartDate` should be the same whether we warm up the algorithm or not.

#### Actual Behavior
In an particular case, where `StartDate` is a Sunday and the algorithm is warmed up, the first `Slice` object after the warm up period contains a `TradeBar` from previous Friday.

#### Potential Solution
N/A

#### Reproducing the Problem
```csharp
public override void Initialize()
{
    SetStartDate(2010, 07, 18); 
    SetWarmup(10); 
    AddEquity("SPY", Resolution.Daily); 
}

public override void OnData(Slice data)
{
    if (IsWarmingUp) return;
    if (!Portfolio.Invested)
    {
        SetHoldings("SPY", 1);
        Debug("Purchased Stock");
    }
}
```
#### System Information
N/A.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/2748
