### ISSUE TITLE
Python support installation  setup.py

### ISSUE THREAD

**Issue by nicemonkey** [QuantConnect/Lean#2340]
Hello,

I followed all the steps to install support for Python algorithms on an Ubuntu 18.04 distribution. The installation script ends on the error described below. 
Having searched long and unsuccessfully for a way around this problem, I publish it here.

Thanking you for your help

#### Actual Behavior
The setup.py script ends with the error: Failed building wheel for pythonnet. More precisely:

> Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
  Running setup.py install for pythonnet: started
    Running setup.py install for pythonnet: finished with status 'error'
    Complete output from command /home/myuser/miniconda3/bin/python -u -c "import setuptools, tokenize;__file__=\'/tmp/pip-req-build-kexrw4u4/setup.py\';f=getattr(tokenize, \'open\', open)(__file__);code=f.read().replace(\'\\r\\n\', \'\\n\');f.close();exec(compile(code, __file__, \'exec\'))" install --record /tmp/pip-record-2zpzal0v/install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
 error: option --single-version-externally-managed not recognized

#### Reproducing the Problem
Just follow these [steps](https://github.com/QuantConnect/Lean/tree/master/Algorithm.Python#quantconnect-python-algorithm-project ) on a new, blank Ubuntu 18.04 instance. 

#### System Information
Ubuntu 18.04
Python 3.6.4

#### Checklist

-  I have completely filled out this template
-  I have confirmed that this issue exists on the current `master` branch
-  I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

-  I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Thank you @nicemonkey we'll look into this today and see if it'll work in 18.04.

You might want to use the Docker container if you're using Ubuntu; that way its all configured and running instantly.

**Comment by AlexCatarino** [comment]
I will look into it ASAP.
Meanwhile, could you please try to upgrade setuptools and wheel?
> pip install -U setuptools
> pip install -U wheel
If it fixes the issue, we just need to modify `setup.py` so that it updates these packages before it tries to install pythonnet.

**Comment by nicemonkey** [comment]
@AlexCatarino
Thank you very much for the quick answer !
> Meanwhile, could you please try to upgrade setuptools and wheel?

I have tried. I get the same issue.

@jaredbroad 
Thanks for the suggestion. I will explore this path too.

**Comment by nicemonkey** [comment]
@AlexCatarino 
Same issue on a Debian 8 instance. 

I may be missing something.

**Comment by kievking** [comment]
This issue still persists on windows even after updating wheel and setuptools

**Comment by kievking** [comment]
@nicemonkey Did you solve it?

**Comment by AlexCatarino** [comment]
@nicemonkey and @kievking , I could reproduce the issue and fix it by installing `clang` and `libglib2.0-dev`:
> sudo apt-get install -y clang libglib2.0-dev

Could you please try this?

**Comment by nicemonkey** [comment]
@AlexCatarino 
This fixes the issue ! Thank you very much !!

**Comment by AlexCatarino** [comment]
Thank you for checking @nicemonkey.  I've just made a PR updating setup.py to check these requirements and the readme.
