### ISSUE TITLE
LazyStreamWriter throws Sharing violation on path Error

### ISSUE THREAD

**Issue by Jay-Jay-D** [QuantConnect/Lean#2382]
#### Expected Behavior

`LazyStreamWriter` implementation should be thread safe. 

#### Actual Behavior

In very specific cases it throws `Err: Sharing violation on path ...`

#### Potential Solution

Using `TextWriter.Synchronized`.

#### Reproducing the Problem

Processing Soybean futures for the date 2013-01-23.

#### System Information

This issue was reproduced in Windows 7 and Ubuntu 16.04.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
@Jay-Jay-D Is this still an issue? Mind adding steps to reproduce it?
