### ISSUE TITLE
Implement Bitfinex brokerage

### ISSUE THREAD

**Issue by Adalyat** [QuantConnect/Lean#2392]
#### Expected Behavior

Support Bitfinex cryptocurrency trading platform using on API v1.1 (stable)

#### Actual Behavior
Currently Lean doesn't support Bitfinex brokerage

#### Checklist

- [v] I have completely filled out this template
- [v] I have confirmed that this issue exists on the current `master` branch
- [v] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by StefanoRaggi** [comment]
Closed by PR #2393
