### ISSUE TITLE
[Bug] Some references are missing

### ISSUE THREAD

**Issue by cub-** [QuantConnect/Lean#24]
Hi Jared,
In QC.Lean.Engine, some references such as "Fasterflect" and "RestSharp" are missing. Couldn't find them in the directory. Please help.
Cub
![default](https://cloud.githubusercontent.com/assets/8294465/6174548/725479dc-b2bd-11e4-9ffe-9abd1860de8d.png)

**Comment by jaredbroad** [comment]
Hi @cub-, these should be automatically downloaded by Nuget --
If you don't have Nuget you can download it here: https://nuget.codeplex.com/releases/view/133091

**Comment by cub-** [comment]
It worked after I upgraded nuget from VS. Thank you.
