### ISSUE TITLE
Error No module named 'clr' when trying Lean's Jupiter support

### ISSUE THREAD

**Issue by leochirag** [QuantConnect/Lean#2402]
I've followed every step mentioned on the readme instructions for Jupiter support and when I try to compile the first chunk of imports, it gives the following error : No module named 'clr'

Please help me with this error.

Thanks again.
Chirag

**Comment by AlexCatarino** [comment]
Hi @leochirag, before running `jupyter notebook`, what happens when you do the following:
```
$ python
>>> import clr
```
If it says:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'clr'```
it means that pythonnet is not installed in your system... which is odd, since you have successfully followed every mentioned step.
Maybe pythonnet is installed in a different environment?

**Comment by jaredbroad** [comment]
No response;

**Comment by shadowxgws** [comment]
I have the same issue on Windows 10.

After building the solution, the engine starts, but as soon as I rebuild it to work with Python, every single Python file that contains QuantConnect libraries returns the same error. It can't recognize a bunch of things: clr, System, QuantConnect, QuantConnect.Algorithm ... and others.

Tried with different global and environment, the result is the same. If I install clr (tried with pythonnet as well) with pip, it seems its not the same clr that I need.

**Comment by blonc** [comment]
on new set up I am having the same issue.

**Comment by pgeorgan** [comment]
Having this issue as well. Perfectly valid code/Quantconnect project that runs in the cloud just fine, and can cloud build "locally" via Visual Studio. Can't debug cloud projects locally, however as it's "not supported", and trying to start a native Visual Studio debugging session (Python Debugger) throws all sorts of "missing module" or "class XYZ not defined" errors. 

This is a bone stock installation following [these instructions](https://www.quantconnect.com/docs/v2/local-platform/installation/install-on-macos). Pythonnet installed with pip.  My latest error message is that the compiler can't seem to find 'clr' module. Or else there is some kind of naming collision going on that I am unaware of. 

Maybe I'm missing something altogether, who knows.

**Comment by pgeorgan** [comment]
You can close this again. The not-so-obvious issue is that you can't actually debug a cloud project locally. Wish the QuantConnect documentation were more clear.

**Comment by DerekMelchin** [comment]
> Wish the QuantConnect documentation were more clear.

Hi pgeorgan,

> Local debugging only works with local projects. Locally debugging cloud projects is not currently supported.

https://www.quantconnect.com/docs/v2/local-platform/backtesting/debugging#01-Introduction

**Comment by pgeorgan** [comment]
> > Wish the QuantConnect documentation were more clear.
> 
> Hi pgeorgan,
> 
> > Local debugging only works with local projects. Locally debugging cloud projects is not currently supported.
> 
> https://www.quantconnect.com/docs/v2/local-platform/backtesting/debugging#01-Introduction

All good. I got it backtesting and debugging locally now in VS with docker+lean. Cheers.
