### ISSUE TITLE
Data from warm up period updates indicator after warm up

### ISSUE THREAD

**Issue by jingwu74** [QuantConnect/Lean#2404]
#### Expected Behavior

The indicator should only be updated once in the warm-up period with the consolidator. 
#### Actual Behavior

The consolidator generates consolidated bars in the warm-up period twice so the indicator was updated with the previous price data which throw the error `This is a forward only indicator: SMA10 Input: 2013-10-01 00:00:00Z Previous: 2013-10-22 00:00:00Z`.

The issue might relate to [#2325](https://github.com/QuantConnect/Lean/issues/2325).

#### Reproducing the Problem

```from datetime import timedelta

class RenkoConsolidatorAlgorithm(QCAlgorithm):
    def Initialize(self):

        self.SetStartDate(2013, 11, 1)
        self.SetEndDate(2013, 11, 10)
        self.AddEquity("SPY", Resolution.Daily)
        renkoConsolidator = RenkoConsolidator(3)
        self.sma = SimpleMovingAverage(10)
        self.RegisterIndicator("SPY", self.sma, renkoConsolidator)
        renkoConsolidator.DataConsolidated += self.HandleRenko
        self.SubscriptionManager.AddConsolidator("SPY", renkoConsolidator)
        self.SetWarmUp(timedelta(days=30))

    def HandleRenko(self, sender, data):
        self.Debug("BarStart "+str(data.Time) + " BarEnd "+str(data.EndTime)+" renko price "+ str(data.Close))

 ```
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [ ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/2748
