### ISSUE TITLE
Streamline Data Feed Architecture

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#2423]
### Expected Behavior
The data feed classes should be 99% identical with small differences at the bottom of the stack depending on the data subscription source.

#### Actual Behavior
Maintenance and support for data feeds are increasingly difficult due to the current data feed abstractions. 
![image](https://user-images.githubusercontent.com/2243225/44361605-5e57f700-a48c-11e8-9411-c22db77f9447.png)

#### Potential Solution
Refactor the data feed to share the subscription management and data synchronization logic. 
![image](https://user-images.githubusercontent.com/2243225/44366416-9f570800-a49a-11e8-8ff0-a50ce5ff556d.png)

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
This has already been implemented through multiple PRs. Detailed information at https://github.com/QuantConnect/Lean/projects/5
