### ISSUE TITLE
Standardize to dotnet archive compression libraries

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#2435]
#### Expected Behavior
A single clean interface for working with archives

#### Actual Behavior
Many different libraries are used in LEAN for various Compression methods; all of them copying to memory instead of streaming due to mono issues.

#### Potential Solution
Careful/thoughtful testing and exploration of an archive abstraction, similar to presented here (https://github.com/QuantConnect/Lean/pull/2416). Ideally with focus on the application and hiding the library implementation.  

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Believe we need this issue to be solved https://github.com/dotnet/runtime/issues/1544
