### ISSUE TITLE
Unable to find package 'MathNet.Filtering'.

### ISSUE THREAD

**Issue by ethode** [QuantConnect/Lean#244]
I am using Xamarin on OSX.  I thought initially there was an issue with the reference, so I added the package manually using NuGet so I knew the package was installed, and I am still seeing this error trying to to update packages per the documentation for setting up on OSx 

Thanks in advanced

**Comment by jaredbroad** [comment]
Can you please give more details on the error? Which project is throwing this exception? Ideally a copy-paste/full build report from the console.

**Comment by ethode** [comment]
This is not during build, it's while running "Update NuGet packages", per the readme instructions using Xamarin on OSx.  Thanks

**Comment by jaredbroad** [comment]
Perhaps seems like a Nuget issue @ethode? Please try with a fresh build of LEAN and re-trying without manually adding the reference. You might need to set Nuget to allow alpha packages somehow.

Closing for now for inactivity.

**Comment by pushnyakov** [comment]
Hello everyone!
It is a problem with xamarin studio!
You just need to use release mode or install MathNet.Filtering manually by downloading it from nuget website.

**Comment by flatM** [comment]
Or run the following command to get MathNet.Filtering installed:

> nuget install MathNet.Filtering -pre

**Comment by jaredbroad** [comment]
Thank you @flatM, we'll add it to the readme install steps.

On Wed, May 25, 2016 at 11:32 PM, flatM <notifications@github.com> wrote:

> Or run the following command to get MathNet.Filtering installed:
>
> nuget install MathNet.Filtering -pre
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/QuantConnect/Lean/issues/244#issuecomment-221768996>
>



-- 
Jared Broad
