### ISSUE TITLE
Python does not support custom consolidator

### ISSUE THREAD

**Issue by jingwu74** [QuantConnect/Lean#2456]
#### Expected Behavior

Python should allow the custom data consolidator.
#### Actual Behavior

Missing Python wrapper of consolidator

#### Reproducing the Problem

```
from datetime import timedelta
class CustomConsolidatorAlgorithm(QCAlgorithm):
    def Initialize(self):
        self.SetStartDate(2018,8,1)  
        self.SetEndDate(2018,8,5)    
        self.SetCash(100000)  

        self.AddForex("EURUSD", Resolution.Minute, Market.Oanda)
        consolidator = CustomConsolidator(timedelta(days=1))
        consolidator.DataConsolidated += self.OnDataConsolidated
        self.SubscriptionManager.AddConsolidator("EURUSD", consolidator)

    def OnDataConsolidated(self, sender, bar):
        self.Debug("Bar date/time: " + bar.Time.ctime())

class CustomConsolidator(QuoteBarConsolidator):
    def __init__(self, timespan):
        self.consolidatedBar = QuoteBar()
    
    def Update(self, data):
        if (data.Time.hour == 15 and data.Time.minute == 10):
            OnDataConsolidated(self.consolidatedBar)
            self.consolidatedBar = QuoteBar(data.Time)
        else:
            self.consolidatedBar.Update(data.Close, data.Bid, data.Ask)
```
#### System Information

LEAN cloud
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by JakeTheSnake3p0** [comment]
Are there any plans to complete this? My project requires sub-1D intervals to be captured starting at market open (9:30am) and not (for example) 8am (on a 4H timeframe).

**Comment by mg64ve** [comment]
Any update on this issue ?
