### ISSUE TITLE
Charts not viewable after approx. #17 - QuantConnect Algorithm Lab

### ISSUE THREAD

**Issue by jeames00** [QuantConnect/Lean#2471]
#### Expected Behavior
In the QuantConnect algorithm lab, when adding multiple charts (e.g. one for all 28 major Forex currency pairs) all charts should be selectable/viewable.

#### Actual Behavior
After about the 15th or 17th chart in the backtest view (including the backtest and equity charts), charts stop being selectable and their visual state doesn't change on mouseover. However if more charts are added, they start to become selectable/viewable again from around the 25th. The variation in chart index when this occurs appears to be dependent on browser and/or platform (tested in Safari and Firefox on Mac, Opera on Windows).  

#### Potential Solution
unknown

#### Reproducing the Problem
`
from datetime import datetime, timedelta

class BasicTemplateAlgorithm(QCAlgorithm):
    
    def Initialize(self):
        self.SetStartDate(datetime.now() - timedelta(weeks=24)) 
        self.SetEndDate(datetime.now())    
        self.SetCash(100000)           
        self.SetWarmUp(timedelta(7))
        
        self.currency_pair_dict = {
            "EURGBP": [], "EURAUD": [], "EURNZD": [], "EURUSD": [], 
            "EURCAD": [], "EURCHF": [], "EURJPY": [],
            
            "GBPAUD": [], "GBPNZD": [], "GBPUSD": [], "GBPCAD": [], 
            "GBPCHF": [], "GBPJPY": [],
            
            "AUDNZD": [], "AUDUSD": [], "AUDCAD": [], "AUDCHF": [], 
            "AUDJPY": [],
                    
            "NZDUSD": [], "NZDCAD": [], "NZDCHF": [], "NZDJPY": [],
            
            "USDCAD": [], "USDCHF": [], "USDJPY": [],
                                              
            "CADCHF": [], "CADJPY": [],
            
            "CHFJPY": []
        }
        
        for pair in self.currency_pair_dict:
            self.AddForex(pair, Resolution.Daily, Market.Oanda, 100)
            chart = Chart(pair)
            chart.AddSeries(Series('close', SeriesType.Line, 0))
            self.AddChart(chart)

    def OnData(self, data):

        if self.IsWarmingUp: 
            return
        
        for pair in self.currency_pair_dict:
            self.Plot(pair, 'close', data[pair].Close)
`

#### System Information
Safari 11.1.1, Firefox 61.0.2 on macOS Sierra 10.2.6
Opera 55.0.2994.44 on Windows 10 Pro

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Hi @jeames00! Welcome to LEAN. This is the open source backtesting engine behind QuantConnect and not really connected with the JS frontend. Sometimes the issues overlap but we ask people with QC.com support issues start with support@quantconnect.com so an engineer can determine where the issue lives first before making an issue here.
