### ISSUE TITLE
setup.py script fails to update Python.Runtime.dll after built

### ISSUE THREAD

**Issue by gvickh** [QuantConnect/Lean#2473]
#### Expected Behavior
setup.py script fails to copy Python.Runtime.dll built into QuantConnect.pythonnet packages folder.
https://github.com/QuantConnect/Lean/blob/aa110d93d506ce9a6f311aae803e658e88cd14a4/setup.py#L184
When there's an existing copy of Python.Runtime.dll inside the QuantConnect.pythonnet folder, copyfile() method will raise a SameFileError exception and refuse to make the copy

https://docs.python.org/3/library/shutil.html#shutil.SameFileError

#### Actual Behavior
Newly built Python.Runtime.dll will not be copied into QuantConnect.pythonnet folder

#### Potential Solution
replace copyfile() method with copy() method.
https://docs.python.org/3/library/shutil.html#shutil.copy

#### Reproducing the Problem
Whenever there's an existing copy of Python.Runtime.dll inside QuantConnect.pythonnet folder before executing the setup script "python setup.py" 

#### System Information
Win10 64bit

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Since the original dll is renamed: Python.Runtime.dll -> Python.Runtime.ori, we use `copyfile` instead of `copy` (by the way, I would tend to use `copy2`). If you have already a `Python.Runtime.ori` from a previous `python setup.py` execution, please delete it.
