### ISSUE TITLE
Toolbox DukascopyDownloader throws NullReferenceException

### ISSUE THREAD

**Issue by Capnode** [QuantConnect/Lean#2486]
#### Expected Behavior

Running QuantConnect.Toolbox to download Dukascopy data is expected to complete without error.

#### Actual Behavior

Error message from QuantConnect.Toolbox:
20180908 15:13:06.727 ERROR:: DukascopyDownloaderProgram.DukascopyDownloader():  System.NullReferenceException: big bar
   vid QuantConnect.Util.LeanData.GenerateLine(IBaseData data, SecurityType securityType, Resolution resolution) i D:\Source\Lean\Common\Util\LeanData.cs:rad 152

#### Potential Solution

QuantConnect.Util.LeanData.GenerateLine() must support data of type TradeBar for Forex and CFD.

#### Reproducing the Problem

Run QuantConnect Toolbox from command line:
QuantConnect.ToolBox.exe --app=DukascopyDownloader --tickers=EURUSD --resolution=Hour --from-date=20180903-00:00:00 --to-date=20180907-00:00:00

#### System Information

Windows 10
VIsualStudio Community 2017

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by miguelvm** [comment]
Can confirm that it only works with Tick resolution.
