### ISSUE TITLE
Python library request for rauth

### ISSUE THREAD

**Issue by jcoffi** [QuantConnect/Lean#2488]
#### Expected Behavior
rauth is whitelisted in QuantConnect.

#### Actual Behavior
rauth is not available.

#### Potential Solution
git clone https://github.com/litl/rauth.git
cd rauth
sudo python setup.py install

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
@jcoffi, what is the purpose? I am asking because this library is not a quant/mathematical one:
> Rauth is a simple Python OAuth 1.0/a, OAuth 2.0, and Ofly consumer library built on top of Requests.

**Comment by jcoffi** [comment]
I was talking to Jared and he told me to submit this. I explained that this is needed to pull data from Ally. But obviously it can be used to pull data from other APIs as well. I chose this one over requests_oauth because rauth only require requests, which is already installed.
