### ISSUE TITLE
Convert.ToDecimal culture issue

### ISSUE THREAD

**Issue by gustavarcticmill** [QuantConnect/Lean#25]
I didn't manage to run the project after a git clone. It complained that the format was invalid. The problem seems to be that the data files are formatted with a dot as number separator, but my culture settings (Swedish) and hence Convert.ToDecimal expects a comma.

If I change the Convert.ToDecimal's that handle csv-split arrays, into:
Convert.ToDecimal(csv[0], new CultureInfo("en-US"))
everything works perfectly. Thought you should know.

Cheers and thanks for all your great work!

**Comment by jaredbroad** [comment]
Thanks for reporting @gustavarcticmill! If possible please submit a pull request by forking the repo, making the change in your account, and then submitting a request here :) This way we'll automatically merge in your change and it'll be easy for anything you find in the future too!
