### ISSUE TITLE
Bitfinex brokerage emits negative amount for quote ticks

### ISSUE THREAD

**Issue by Adalyat** [QuantConnect/Lean#2511]
#### Expected Behavior

Quantity in trade ticks should always be positive

#### Actual Behavior

Bitfinex brokerage emits quote Ticks  with  negative AskSize

#### Potential Solution

Use absolute value inside internal order book copy

#### Reproducing the Problem

Run Bitfinex brokerage with valid api key and secret and print ticks

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by StefanoRaggi** [comment]
Closed by PR #2512
