### ISSUE TITLE
Need Updated Readme how using Docker

### ISSUE THREAD

**Issue by ec2ainun** [QuantConnect/Lean#2529]
#### Expected Behavior

Training on server using Lean build on top of Docker

#### Actual Behavior

Got same issue #1173 , but no current solution
COPY failed: stat /var/lib/docker/tmp/docker-builder532641228/Launcher/bin/Release: no such file or directory

#### Potential Solution

Provide Step by step development config Lean using Docker

#### Reproducing the Problem

Following Usage in Dockerfile
1. docker build -t quantconnect/lean:foundation -f DockerfileLeanFoundation .
2. docker build -t quantconnect/lean:algorithm -f Dockerfile .
Got error COPY failed: stat /var/lib/docker/tmp/docker-builder532641228/Launcher/bin/Release: no such file or directory

#### System Information

AWS server Ubuntu 16.04.3 LTS

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] No current solution, I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment]
This is a duplicate, as you stated of #1173. As Jared stated in that issue, it is not a bug.
Please bring technical questions to [Lean Group](https://groups.google.com/forum/#!forum/lean-engine) or [Slack chat](https://www.quantconnect.com/slack).

**Comment by ec2ainun** [comment]
@AlexCatarino and @jaredbroad yeah i know, but it is necessary right to provide step by step and updated to **Readme**? so anyone who got started developing using Lean not confused anymore because of lack of documentation here

**Comment by AlexCatarino** [comment]
Lean execution/deployment in a docker container is not exactly Lean development, right?
This is a technical issue and those are addressed in [Lean Group](https://groups.google.com/forum/#!forum/lean-engine) or [Slack chat](https://www.quantconnect.com/slack). Please use those channels.

**Comment by arbutt1010** [comment]
> #### Expected Behavior
> Training on server using Lean build on top of Docker
> 
> #### Actual Behavior
> Got same issue #1173 , but no current solution
> COPY failed: stat /var/lib/docker/tmp/docker-builder532641228/Launcher/bin/Release: no such file or directory
> 
> #### Potential Solution
> Provide Step by step development config Lean using Docker
> 
> #### Reproducing the Problem
> Following Usage in Dockerfile
> 
> 1. docker build -t quantconnect/lean:foundation -f DockerfileLeanFoundation .
> 2. docker build -t quantconnect/lean:algorithm -f Dockerfile .
>    Got error COPY failed: stat /var/lib/docker/tmp/docker-builder532641228/Launcher/bin/Release: no such file or directory
> 
> #### System Information
> AWS server Ubuntu 16.04.3 LTS
> 
> #### Checklist
> * [x]  I have completely filled out this template
> * [x]  I have confirmed that this issue exists on the current `master` branch
> * [x]  No current solution, I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
> 
> * [x]  I have provided detailed steps to reproduce the issue

Did you got solution to this issue I am trying to build docker image using docker build -t lean . command but its giving same error which you got in 2018, I used your commands as well but still same error any guide me helpful
