### ISSUE TITLE
Install/compile/run Lean Algorithm.Python without installing miniconda or anaconda

### ISSUE THREAD

**Issue by SamoPP** [QuantConnect/Lean#2535]
#### Expected Behavior
I want to install and run Lean Algorithm.Python without installing miniconda or anaconda. How can I do this?

#### Actual Behavior
On my Ubuntu 18.04 installing miniconda breaks a lot things on my system (it installs non-compatible libraries with other software linked to R, RCpp, RQuantLib etc.). So I am looking for tutorial/instructions on how to install and use Lean Algorithm.Python using just proper Python installation using apt-get and pip (without conda).

**Comment by AlexCatarino** [comment]
@SamoPP, did you try to just follow the installation instructions without installing anaconda/miniconda? If python 3.6 is already installed, you just need to make a symbolic link to `/usr/lib`:
```
sudo ln -s path/to/python/lib/libpython3.6m.so /usr/lib/libpython3.6m.so
``` 

P.S.: For technical questions, please email us at [Lean Group](https://groups.google.com/forum/#!forum/lean-engine) or chat with us at [Slack](https://www.quantconnect.com/slack).
