### ISSUE TITLE
Cannot build the Lean Solution on Visual Studio Community 2017 - The type or namespace name 'Python' and "PyObject" could not be found

### ISSUE THREAD

**Issue by Adrienlq** [QuantConnect/Lean#2536]
#### Expected Behavior
I cannot build the Lean Solution on Visual Studio Community 2017

#### Actual Behavior
When building I have the following errors (123 of them) composed of : 
- CS0246	The type or namespace name 'PyObject' could not be found (are you missing a using directive or an assembly reference?
- CS0246	The type or namespace name 'Python' could not be found (are you missing a using directive or an assembly reference?Algorithm
- CS0006	Metadata file 'C:\Users\adrie\Lean\FILEPATH\NAME_OF_FILE(.dll or .exe)' could not be found	

#### Potential Solution
Cannot find one

#### System Information
Windows 10;
Visual Studio Community 2017;
ASP.NET 4.7 activated in windows feature;
I followed the LEAN installation procedure and ran all the steps at https://github.com/QuantConnect/Lean/tree/master/Algorithm.Python#quantconnect-python-algorithm-project

**Comment by jaredbroad** [comment]
Please post individual application concerns to the user group. https://www.quantconnect.com/forum/discussions/1/lean
