### ISSUE TITLE
Interactive brokers GetOpenOrder() Error

### ISSUE THREAD

**Issue by cub-** [QuantConnect/Lean#254]
Hi everyone,
When I connect Lean to IB, I had this error: InteractiveBrokersBrokerage.GetOpenOrdes(): operation took longer than 15 seconds. My ClientID was set to 0.

The error is regardless of whether I really have any open/unfilled order in TWS or not. If it can't retrieve order info, the brokerageSetUpHandler won't set up either. Supposedly, if I call "reqOpenOrder()" in TWS API demo, it should retrieve "open order end" when no order was pending or specify any open order. 

Any thoughts?
Cub

**Comment by mchandschuh** [comment]
Hey @cub-, what O/S are you running? We've seen an issue in Linux with similar symptoms, the GetOpenOrders call fails periodically. This seemed to be a hit or miss occasion, and not failing reliably. Does yours fail reliably?

Could you share your logs? Please strip out an sensitive information first though! If you can share, please send them to michael@quantconnect.com.

**Comment by cub-** [comment]
Yep, just sent you the log. @mchandschuh  I'm on win 8. In may case GetOpenOrders() fails reliably. The issue happens with Krs so far.

**Comment by jaredbroad** [comment]
Closing - could not repeat // probably old TWS bug.
