### ISSUE TITLE
DateTime.Now used to return backtest current time, now returns real-life time

### ISSUE THREAD

**Issue by mblouin02** [QuantConnect/Lean#2550]
#### Expected Behavior
In backtest mode, DateTime.Now should return the current algorithm time, as it used to.

#### Actual Behavior
Since a few weeks (or months?), DateTime.Now returns the current real-life time when running in backtest mode, so algorithms using this are now broken in backtest mode.

#### Potential Solution
Either revert the behaviour to what it was before, or inform the community to refactor their code to use another mean to get algorithm time.

#### Reproducing the Problem
- Create a dummy algorithm running for one year, daily. Subscribe to "SPY".
- In the "OnData()" method, type Log(DateTime.Now);
- Run a backtest
- Notice that the time logged is the current time, rather than the algorithm's current time.

#### System Information
- Running in the online version of QtantConnect.

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by StefanoRaggi** [comment]
@mblouin02 
`DateTime.Now` is not implemented by LEAN, it is part of the .NET Framework:
https://docs.microsoft.com/en-us/dotnet/api/system.datetime.now?view=netframework-4.7.2

If you need to log the algorithm current time, you can use one of these:
```
Log(Time); // logs the current time in algorithm time zone
Log(UtcTime); // logs the current time in UTC
```
