### ISSUE TITLE
No Custom data imported with IB live data feed 

### ISSUE THREAD

**Issue by jingwu74** [QuantConnect/Lean#2560]
#### Expected Behavior

The custom data should be available to use with the IB live data feed.
#### Actual Behavior

For live trading on IB using IB data feed, the custom data isn't streaming.
#### Reproducing the Problem

```from QuantConnect.Python import PythonQuandl
class BasicAlgorithm(QCAlgorithm):

    def Initialize(self):

        self.SetStartDate(2018,1,1) 
        self.SetEndDate(2018,2,1)  
        self.SetCash(25000)
        self.vix = 'CBOE/VIX'
        self.AddData(QuandlVix, self.vix, Resolution.Daily)
        hist = self.History([self.vix], 10, Resolution.Daily)
        self.Debug(str(hist))
  
class QuandlVix(PythonQuandl):
    
    def __init__(self):
        self.ValueColumnName = "VIX Close"
```
#### System Information

LEAN 
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Update: this is not supported yet

**Comment by hohoCode** [comment]
Any updates ? Thanks.

**Comment by Martin-Molinero** [comment]
Selecting multiple data feeds is now supported by Lean see https://github.com/QuantConnect/Lean/pull/6047 . QC + IB data feed is now available in the cloud
