### ISSUE TITLE
python install in manjaro linux

### ISSUE THREAD

**Issue by andrewcz** [QuantConnect/Lean#2563]
I having issues installing the python module in manjaro -

![screenshot_2018-09-29_18-58-22](https://user-images.githubusercontent.com/2296335/46243636-e8936380-c419-11e8-8d3e-c3948f3ef0f6.png)

**Comment by andrewcz** [comment]
I am using manjaro and installed all the dependencies using our package manager.

**Comment by andrewcz** [comment]
I think it just cant find the installs due to the path?
BEst,
Andrew

**Comment by Martin-Molinero** [comment]
Hi!
As of https://github.com/QuantConnect/Lean/pull/2854 Lean does not require an installation step for setting up PythonNet. Readme file at https://github.com/QuantConnect/Lean/tree/master/Algorithm.Python has been updated to reflect these changes.
