### ISSUE TITLE
Date parsing assumes 8 character dates and fails with 8 character formatted dates (yyyymmdd)

### ISSUE THREAD

**Issue by ballance** [QuantConnect/Lean#2564]
#### Expected Behavior
When parsing data from csv containing 8 character dates, we should check the date length and parse accordingly.  The code currently defaults to 12 character dates and fails to parse DateTime for data sets such as free data set provided by QuantConnect.

#### Actual Behavior
For csv data with 8 character dates (yyyymmdd), the csv fails to parse.

#### Potential Solution
Check length of input (csv[0]) and use the appropriate date parsing format

#### Reproducing the Problem
Use csv input that contains 8 character input dates (yyyymmdd)

**Example Row**
19980105 | 0 | 13.4916 | 13.7033 | 13.4691 | 13.5853 | 5332919.26400001

#### System Information
Windows 10 

#### Checklist
- [x ] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by mchandschuh** [comment]
Closing. Please provide an example of QC data requiring the 8 character format in daily mode. Another issue with this PR is that it would allow the 8 character format for hourly data which would be incorrect as the 8 character format only has daily precision.
