### ISSUE TITLE
Add support for Trailing Stop Orders

### ISSUE THREAD

**Issue by dd-w** [QuantConnect/Lean#2580]
It would be great to support for Trailing Stop Orders.

Past discussion here: https://www.quantconnect.com/forum/discussion/601/trailing-orders

Using the Algorithm Framework would this best be implemented as:
- New Order Type
- Risk Management Model
- Execution Model

**Comment by itsbalamurali** [comment]
@mchandschuh @jaredbroad any update on this one?

**Comment by kevinchundu** [comment]
@jaredbroad this is super super important for live trading! I did implement a trailing stop algo in my live trade, but it could fail for all sorts of issues. The most important reason for QC to support trailing stop on live is it reduces the unreliability by a huge degree for it eliminates all the possible issues such as server goes offline, network unavailable, market data not available, etc. I'm hoping you can take this into consideration to get more Ib order type implemented(most important are stop loss and trailing stop loss). Again, I do think it is essential for live trading. Please do consider offer this!
