### ISSUE TITLE
Requesting that a condition which currently causes a fatal error instead be raised as a catchable exception

### ISSUE THREAD

**Issue by notarealdeveloper** [QuantConnect/Lean#2606]
#### Expected Behavior
In QuantConnect papertrading, submitting an order for an unsupported ticker should throw a catchable exception rather than a fatal error.

#### Actual Behavior
In a QuantConnect papertrade, when using the Interactive Brokers brokerage, submitting a MarketOrder for a ticker that Interactive Brokers does not support currently raises a fatal error of the following form:

```
Runtime Error: No security definition has been found for the request. Origin: GetContractDetails: STK [Something] USD Smart Stack Trace: System.Exception: No security definition has been found for the request. Origin: GetContractDetails: STK [Something] USD Smart
```

The fatal error occurs even if the code block in question is wrapped in a `try / except` clause.

#### Potential Solution
Catch the error at the IB API level, and raise a python RuntimeError exception with the same error message, allowing the papertrade to proceed.

#### Reproducing the Problem
Submit a MarketOrder for the ticker "FMSA" inside a `try / except` block, in LiveMode using InteractiveBrokers as the brokerage. The `AddEquity` step succeeds in the universe selection stage, only to cause a fatal error when an order is submitted. A large number of other tickers appear to behave similarly.

#### System Information
QuantConnect live mode, using an IB papertrading account. The error occurs when using the IB brokerage but not the QC brokerage.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by mchandschuh** [comment]
I believe this can be controlled by subclassing the brokerage message handler and handling this as you wish. When I'm back to my computer I'll provide a code sample.
