### ISSUE TITLE
Setting Multiple Scheduled Events to Same Time Does Not Trigger in Deterministic Order

### ISSUE THREAD

**Issue by arshamawan** [QuantConnect/Lean#2625]
#### Expected Behavior
We want the Scheduled Events, which fire at the same time, to activate in the same order in both online BTs and local.

#### Actual Behavior
They can happen the other way round.

**Comment by mchandschuh** [comment]
The underlying cause of this is that the scheduled events are stored in a concurrent dictionary which has non-deterministic enumeration behavior. We could add an index to each entry and sort them before invoking the handlers.
