### ISSUE TITLE
IQFeed IDataQueueHandler

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#264]
Create an IQFeed implementation of IDataQueueHandler for local live trading.

Can use https://sentineliqf.codeplex.com as a starting point, but this code is fairly old and messy so probably worth a re-write.

**Comment by bizcad** [comment]
Great idea.  @AlexCatarino If I can help let me know.  I almost signed up for Kinetick this week, but IQ looks better.  I am also looking forward to the nanex.  Great feeds breed great trading.

**Comment by AlexCatarino** [comment]
@bizcad, thanks. As soon as I get to this issue (it's 3rd in my priority list right now), I will evaluate and seek for your help.

**Comment by jaredbroad** [comment]
Closed by #89bb637
