### ISSUE TITLE
Provide the user a means to know is a security data is discontinued.

### ISSUE THREAD

**Issue by Jay-Jay-D** [QuantConnect/Lean#2651]
#### Expected Behavior

If data for a discontinued security is asked, e.g. JP225JPY for dates after October 2014, send a message to the user warning about lack of data.

#### Actual Behavior

The algorithm doesn't inform the user the data is not available nor indicates it cannot find the files.

#### Potential Solution

Make the [`SubscriptionDataReader`](https://github.com/QuantConnect/Lean/blob/master/Engine/DataFeeds/SubscriptionDataReader.cs#L128) aware of the available dates for each security.

#### Reproducing the Problem

The following algorithm shows the actual behavior with `JP225JPY` CFD.
```cs
    public class BasicTemplateAlgorithm : QCAlgorithm
    {
    	string _ticker = "JP225JPY"; 
        private Symbol _symbol;
        private Identity _price; 

        public override void Initialize()
        {
            SetStartDate(2018, 05, 01);  //Set Start Date
            SetEndDate(2018, 06, 01);    //Set End Date
            SetCash(100000);             //Set Strategy Cash

            _symbol = AddCfd(_ticker, Resolution.Daily, Market.Oanda).Symbol;
            
            _price = Identity(_symbol.Value);
            PlotIndicator($"{_symbol.Value} Price", _price);
        }

        public override void OnData(Slice data)
        {
            if (!Portfolio.Invested)
            {
                SetHoldings(_symbol, 1);
                Log($"Purchased Security {_symbol}");
            }
        }
    }

```

#### System Information

Cloud.

#### Checklist

- [x] I have completely filled out this template
- [ ] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
- Implementing this at the moment as a collection of statistics on every single file miss on the backtest.
 - Implementing as part of the Local Platform support; will be charted on the GUI with red-green grid area diagram
 - Closing for now.
