### ISSUE TITLE
Build.bat path issues causing Algorithm.Python build errors in Visual Studio on Windows

### ISSUE THREAD

**Issue by 1jeremy** [QuantConnect/Lean#2674]
#### Expected Behavior

Build of Algorithm.Python in Visual Studio on Windows should not generate errors.

#### Actual Behavior

Build error: 'build' is not recognized as an internal or external command, operable program or batch file. MSBuild exits with code 9009.

#### Potential Solution

Build.bat could be copied to the output directory, then it would be found when called post-build.  This alone does not resolve all build errors.  Build.bat cannot locate *.pyc files and deletes Python.Runtime.dll also leading to build errors.  Build succeeds if Build.bat is copied to the output directory and altered as follows:
````
REM QuantConnect Lean Engine -- Python Build Script.
REM del Python.Runtime.dll

REM Python Compile the Algorithm with all the files in current directory
nPython -m compileall -l ..\..

REM Copy to the Lean Algorithm Project
copy ..\..\__pycache__\*.pyc ..\..\..\Launcher\bin\Debug >NUL
copy ..\..\__pycache__\*.pyc ..\..\..\Launcher\bin\Release >NUL
copy ..\..\__pycache__\*.pyc ..\..\..\Tests\bin\Debug >NUL
````
#### Reproducing the Problem

Follow installation instructions for Windows at https://github.com/QuantConnect/Lean and https://github.com/QuantConnect/Lean/tree/master/Algorithm.Python#quantconnect-python-algorithm-project.  After all steps are followed including nuget restore at solution level, solution rebuild, enabling python support etc., and after the final Rebuild LEAN (Step 3), attempt to rebuild just the Algorithm.Python (QuantConnect.Algorithm.Python.csproj) by itself in Visual Studio 2017.

#### System Information

conda info
platform : win-64
user-agent : conda/4.5.11 requests/2.19.1 CPython/3.6.6 Windows/10 Windows/10.0.17134

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by michaelsrew** [comment]
Hi, did you manage to run a python algo on windows?
i am getting 150 build errors (step 3) after installing pythonnet.
thanks

**Comment by Martin-Molinero** [comment]
Hi @1jeremy !
There is no need to build the `Algorithm.Python` project. In the solution properties, you can see that its set not to build when building the entire solution.

**Comment by michaelsrew** [comment]
I think i have the same error but the general solution is to search on the website.
There was maybe a very smiliar problem in september:

https://github.com/QuantConnect/Lean/issues/2536

The info is missing in the readme.md that there is also some help that can be found in the forum @jaredbroad 
The solution for this is asked by the same guy on the forum:

https://www.quantconnect.com/forum/discussion/4576/cannot-build-the-lean-solution-on-visual-studio-community-2017-the-type-or-namespace-name-039-python-039-and-quot-pyobject-quot-could-not-be-found

https://www.quantconnect.com/forum/discussion/4252/running-local-python-algorithm-error/p1

https://www.quantconnect.com/forum/discussion/4802/got-an-error-msg-when-running-python-on-desktop

https://www.quantconnect.com/forum/discussion/4548/having-problems-trying-to-gt-lean-working-on-my-desktop

if you want you can close this.

#2536 has the same problem with a class in algorithm.python?
which was ansered in the forum (first link above)
more answeres within links 2,3 &4 :)

**Comment by michaelsrew** [comment]
ok another try,
i have seen some problems using anaconda and Lean,
The major problem what Visual Studio shows the user is that there are build problems in AlgorithmPython. (very similar to #2536 )
the ansers for this can be found on the forum:
https://www.quantconnect.com/forum/discussion/4576/cannot-build-the-lean-solution-on-visual-studio-community-2017-the-type-or-namespace-name-039-python-039-and-quot-pyobject-quot-could-not-be-found
https://www.quantconnect.com/forum/discussion/4252/running-local-python-algorithm-error/p1
https://www.quantconnect.com/forum/discussion/4802/got-an-error-msg-when-running-python-on-desktop
https://www.quantconnect.com/forum/discussion/4548/having-problems-trying-to-gt-lean-working-on-my-desktop

if you want you can close this issue

please add an info to the readme that there is a forum with answers on the webite for the future @jaredbroad

**Comment by 1jeremy** [comment]
Hi @michaelsrew , BasicTemplateFrameworkAlgorithm.py runs if I keep Algorithm.Python excluded from the build config as @Martin-Molinero kindly pointed out.  Because I changed the build setting to include Algorithm.Python in the solution build then I had to modify build.bat and set it to copy to the output directory in order to resolve build errors and run Python algorithms.  --Jeremy

**Comment by michaelsrew** [comment]
oh ok. thank you for the info. 
(I had also some problems with Algorithm.Python and played around with build.bat)
thanks for reporting back

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/4460
