### ISSUE TITLE
Implement Connor's RSI

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#2678]
#### Expected Behavior
Connor's RSI is supported.

#### Actual Behavior
Connor's RSI is not supported:
https://www.quantconnect.com/forum/discussion/4824/anyone-have-connors-rsi

#### Potential Solution
Implement Connor's RSI:
https://stockcharts.com/school/doku.php?id=chart_school:trading_strategies:rsi2
https://www.tradingview.com/wiki/Connors_RSI_(CRSI)

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by LouisSzeto** [comment]
[spy_crsi.csv](https://github.com/QuantConnect/Lean/files/10824241/spy_crsi.csv)

**Comment by LouisSzeto** [comment]
[spy_crsi.csv](https://github.com/QuantConnect/Lean/files/13114634/spy_crsi.csv)
columns: "SPY close" "Conner RSI"

script:
```
import talib

qb = QuantBook()

spy = qb.AddEquity("SPY", Resolution.Daily).Symbol

history = qb.History([spy, qqq], datetime(1998, 1, 1), datetime(2023, 2, 23))

close = history.loc[spy].close

# Source: https://www.tradingview.com/support/solutions/43000502017-connors-rsi-crsi/
rsi = talib.RSI(close, 3)
streak = close * 0
for i in range(1, len(close)):
    if streak.iloc[i-1] / close.pct_change().iloc[i] <= 0:
        streak.iloc[i] = 0
    else:
        streak.iloc[i] = streak.iloc[i-1]
    if close.iloc[i] > close.iloc[i-1]:
        streak.iloc[i] = streak.iloc[i] + 1
    elif close.iloc[i] < close.iloc[i-1]:
        streak.iloc[i] = streak.iloc[i] - 1
rsi_streak = talib.RSI(streak, 2)
crsi = ((rsi + rsi_streak + close.pct_change(100)) / 3).to_frame()
crsi["SPY close"] = close
crsi = crsi.iloc[:, [1, 0]].dropna()
crsi.to_csv("spy_crsi.csv", header=False)
```

**Comment by JosueNina** [comment]
[spy_crsi.csv](https://github.com/user-attachments/files/17834484/spy_crsi.csv)
Columns: date, close, crsi
The script has been updated, and the way the last part is calculated has changed. Instead of using close.pct_change(100), which is a ROC with a period of 100, a ROC with a period of 1 is used. Then, the current value is compared with the previous 100 ROC values, and finally, the percentage of values that are lower than the current one is calculated. [Source](https://chartschool.stockcharts.com/table-of-contents/technical-indicators-and-overlays/technical-indicators/connorsrsi)

```
import talib
import pandas as pd

history = pd.read_csv("https://github.com/QuantConnect/Lean/raw/master/Data/equity/usa/daily/spy.zip",
                       index_col=0, names=["open", "high", "low", "close", "volume"])

close = history.close
pd.set_option('display.max_rows', 115)

# Source: https://chartschool.stockcharts.com/table-of-contents/technical-indicators-and-overlays/technical-indicators/connorsrsi
rsi = talib.RSI(close, 3)
streak = close * 0
for i in range(1, len(close)):
    if close.pct_change().iloc[i] != 0 and streak.iloc[i-1] / close.pct_change().iloc[i] <= 0:
        streak.iloc[i] = 0
    else:
        streak.iloc[i] = streak.iloc[i-1]
    if close.iloc[i] > close.iloc[i-1]:
        streak.iloc[i] = streak.iloc[i] + 1
    elif close.iloc[i] < close.iloc[i-1]:
        streak.iloc[i] = streak.iloc[i] - 1
rsi_streak = talib.RSI(streak, 2)

period = 100
daily_return = close.pct_change()
counts = [None] * (period + 1)
for i in range(period + 1, len(daily_return)):
    previous_values = daily_return.iloc[i-period:i]
    current_value = daily_return.iloc[i]
    count = (previous_values < current_value).sum()
    counts.append(count)

counts = pd.Series(counts, index=daily_return.index)
percent_rank = counts / period * 100

crsi = ((rsi + rsi_streak + percent_rank) / 3).to_frame(name="crsi")

crsi["close"] = close
crsi = crsi.iloc[:, [1, 0]]
crsi.to_csv("spy_crsi.csv", index_label="date", header=True)
```
