### ISSUE TITLE
DailyFx EventDateTime is wrong

### ISSUE THREAD

**Issue by Worthy7** [QuantConnect/Lean#2706]
#### Expected Behavior
EventDateTime to be correct

#### Actual Behavior
EventDateTime is wrong

#### Potential Solution
Not sure, but it may be because UTC is not being specified in the datetimeoffset creation?

#### Reproducing the Problem
Difficult without being in a different timezone.

#### System Information
In Japan +9

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

![image](https://user-images.githubusercontent.com/4762399/48656418-cbb5fc80-ea68-11e8-89fb-52b27f38604a.png)

**Comment by Worthy7** [comment]
After some investigation, I believe the bug is due to using `DateTimeOffset` as the return type - It should simply be `DateTime` and that fixes things.

**Comment by jaredbroad** [comment]
Thanks @Worthy7 - patched in commit #5aade49092
