### ISSUE TITLE
Add tensorflowsharp library

### ISSUE THREAD

**Issue by fwaris** [QuantConnect/Lean#2708]
Requesting the addition of TensorFlowSharp library

https://github.com/migueldeicaza/TensorFlowSharp

This will allow C#/F# users to use TensorFlow models in QC

**Comment by Worthy7** [comment]
.Net 4.7.2 required before this can be done
https://github.com/QuantConnect/Lean/pull/2870

**Comment by Worthy7** [comment]
Cool, hadn't heard of ML.net, thanks!

**Comment by fwaris** [comment]
https://dotnet.microsoft.com/apps/machinelearning-ai/ml-dotnet

Its relatively new from Microsoft. I think it underpins the Azure Machine learning service. The main attraction is that it is easy to embed into a .Net core application.

Comes with MIT licensing - although the API is still in flux.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Martin-Molinero** [comment]
`TensorFlow.NET` has been added to QC cloud
