### ISSUE TITLE
Combo buying power model

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#2709]
#### Expected Behavior
Be able to place combo (multi-leg) order which margin requirements are evaluated my a combo buying power model.

#### Actual Behavior
Each order from a combo order is evaluated separately.

#### Reproducing the Problem
Place a combo option order and get insufficient buying power:
https://www.quantconnect.com/forum/discussion/4372/option-combo-margin-calculation/p1
https://www.quantconnect.com/forum/discussion/4468/options-and-forward-fill-data-combo-spreads-trade-data/p1

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by JoshKoberstein** [comment]
I would very much appreciate this issue being addressed.

**Comment by educandela1** [comment]
I'm very interested in the development of this feature.

**Comment by crmcwi** [comment]
Hello Alex.   I too want this feature.  Thank you.

**Comment by automaton82** [comment]
I also require this feature.

**Comment by AlexCatarino** [comment]
Closed. Continue as #5693
