### ISSUE TITLE
Extends Trailing Stop Risk Management Model for short positions

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#2716]
#### Expected Behavior
Trailing Stop Risk Management Model should work for long and short positions.

#### Actual Behavior
Trailing Stop Risk Management Model only supports long positions.

#### Potential Solution
Implement the short side logic.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by ofirshm** [comment]
class TrailingStopPerSecurity(RiskManagementModel):
    '''Provides an implementation of IRiskManagementModel that limits the drawdown per holding to the specified percentage'''

    def __init__(self, maximumDrawdownPercent = 0.05):
        '''Initializes a new instance of the MaximumDrawdownPercentPerSecurity class
        Args:
            maximumDrawdownPercent: The maximum percentage drawdown allowed for any single security holding'''
        self.maximumDrawdownPercent = -abs(maximumDrawdownPercent)
        self.asset_best_pnl = {}
        
    def ManageRisk(self, algorithm, targets):
        '''Manages the algorithm's risk at each time step
        Args:
            algorithm: The algorithm instance
            targets: The current portfolio targets to be assessed for risk'''
        syms = [kvp.Value.Symbol for  kvp in algorithm.Securities]
        new_assets = {key:val for key,val in self.asset_best_pnl.items() if key in syms}
        self.asset_best_pnl = new_assets

        targets = []
         
        for kvp in algorithm.Securities:
            security = kvp.Value
            symbol = security.Symbol
            if symbol not in self.asset_best_pnl.keys():
               self.asset_best_pnl[symbol] = security.Holdings.UnrealizedProfitPercent
            self.asset_best_pnl[symbol] = np.maximum(self.asset_best_pnl[symbol], security.Holdings.UnrealizedProfitPercent)
            if not security.Invested:
                continue

            pnl = security.Holdings.UnrealizedProfitPercent -  self.asset_best_pnl[symbol]
            if pnl < self.maximumDrawdownPercent:
                # liquidate
                targets.append(PortfolioTarget(symbol, 0))

        return targets
