### ISSUE TITLE
Job Batching

### ISSUE THREAD

**Issue by Hendrik410** [QuantConnect/Lean#2723]
#### Expected Behavior
The Lean Documentation talks about the batching for algorithm jobs (https://www.quantconnect.com/lean/docs) which would be a feature, I would find really helpful.

#### Actual Behavior
Except for this one documentation page, I can't find any place, where the topic is adressed.
Also in the code I only find functions to run a single algorithm.

Am I missing something?

#### Reproducing the Problem
N/A

#### System Information
N/A

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Welcome @Hendrik410, broadly we're categorizing this as optimization. Please follow along with these issues to get notified of updates. https://github.com/QuantConnect/Lean/projects/1
