### ISSUE TITLE
Error While Trying to Load the Project - "Unknown solution item type"

### ISSUE THREAD

**Issue by tlkahn** [QuantConnect/Lean#2724]
I download from the most recent release. When I tried to open QuantConnect.Lean.sln, I ran into the error: "Error while trying to load the project '/users/.../mypath/Lean-2.4.0.1/VisualStudioPlugin/QuantConnect.VisualStudioPlugin.csproj': Unknown solution item type: {82b43b9b-a64c-4715-b499-d71e9ca2bd60}".

I am running Visual Studio community edition on MacOS Mojave 10.14.1

Not sure if there is something I am missing?

**Comment by jaredbroad** [comment]
Not sure @tlkahn - we will test with VS Community and get back to you.

**Comment by supermodo** [comment]
Hi Karen, I get a similar error but i can't find the XML with the line to change.
I've searched in the three files but no luck.

Can you please give me a hint?
Thanks in advance

![Screen Shot 2019-04-02 at 11 32 38](https://user-images.githubusercontent.com/3813726/55422591-97d40300-5541-11e9-8e40-471a16a7a435.jpg)

**Comment by yegodz** [comment]
I am getting the exact same error messages when trying to load VS and Lean 
Any solution?
I am using MacOS High Sierra

**Comment by jaredbroad** [comment]
Have you installed Python Tools? It is optional with Visual Studio I think

**Comment by yegodz** [comment]
Do you mean `ptvsd`? 
Yes, I did install that with `pip`
However, I did see on the Visual Studio support page that python is not supported for Visual Studio on Mac. But the tutorial suggests that it should work.
[https://docs.microsoft.com/en-us/visualstudio/python/overview-of-python-tools-for-visual-studio?view=vs-2019#questions-and-answers](url)

**Comment by hjzhang79** [comment]
@jaredbroad @yegodz  same errors here. is there a way to solve it?

**Comment by corywheeler** [comment]
@jaredbroad @yegodz I happened upon this early this morning as well and have been trying to track down where explicit sdk imports are happening in the solution but unfortunately haven't found any yet. 

I peeked inside of the 

`.../VisualStudioPlugin/QuantConnect.VisualStudio17Plugin.csproj`

file, and didn't see any so I greped for any using

`Lean git:(master) ✗ grep -rnw ./ -e  'Sdk='`

If anyone stumbles on how we're falling into this scenario I would love to understand how.

**Comment by kaimdx** [comment]
I have the exact same error as @supermodo and it seems that there is no fix yet?

The visual studio page linked in @yegodz's comment mentioned that Visual Studio Code is compatible with Python on Mac. Will it be possible to run Lean with Visual Studio Code, which I prefer over Visual Studio Community?

Finally, what is the impact of these errors? I tried `Run --> Starting debugging` and 
`cd Lean/Launcher/bin/Debug`, `mono QuantConnect.Lean.Launcher.exe`
as shown in the [Lean readme](https://github.com/QuantConnect/Lean#macos). It compiled with no error and outputs some statistics when run `Launcher.exe`. Does this mean I can still run my Python algorithm and back testing (haven't created any yet)?

**Comment by corywheeler** [comment]
@jaredbroad Since this seems to still be occurring for folks, is there any chance we could get this Issue re-opened just so people cruising by looking for help don't get confused?
