### ISSUE TITLE
Support 4 char currencies

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#2744]
#### Expected Behavior

- Lean supports 4 char currencies. e.g. Coinbase `USDC`
#### Actual Behavior

Lean currently supports 3 char currencies, e.g. https://github.com/QuantConnect/Lean/blob/master/Common/Securities/Cash.cs#L90 https://github.com/QuantConnect/Lean/blob/master/Common/Securities/SecurityService.cs#L66 https://github.com/QuantConnect/Lean/blob/master/Common/Currencies.cs
As pointed by @StefanoRaggi at https://github.com/QuantConnect/Lean/pull/2742#discussion_r240216838 Coinbase is incrementally adding new symbols with 4-char base currencies and 4-char quote currencies
#### Potential Solution

- Refactor
#### Reproducing the Problem

N/A
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Note that today no 4-char base or/and quote currency is supported see https://github.com/QuantConnect/Lean/blob/master/Common/Currencies.cs#L32

**Comment by Martin-Molinero** [comment]
I'll close this issue as a duplicate of https://github.com/QuantConnect/Lean/issues/996

**Comment by mchandschuh** [comment]
Have we considered implementing a separator character to split the base and quote currencies. We could make it such that if the separator is not present it reverts to existing behavior. It's my understanding that the parsing of the symbol is the only difficulty in supporting n character currencies.
