### ISSUE TITLE
Latest Nuget (2.4.4923) doesn't include AlpacaBrokerage

### ISSUE THREAD

**Issue by codebeaulieu** [QuantConnect/Lean#2749]
I've installed Nuget QuantConnect.Lean version 2.4.4923 and the Alpaca Markets brokerage code is not included. Is there a reason for this? Or is there another package out there that I missed? 

Last package release date is 11/28/2018

**Comment by jaredbroad** [comment]
Not sure about that version but the latest version has it here:
![image](https://user-images.githubusercontent.com/2243225/50038083-b338f380-ffce-11e8-805a-c860d84f1446.png)
