### ISSUE TITLE
Market orders can be filled at stale prices in backtesting

### ISSUE THREAD

**Issue by StefanoRaggi** [QuantConnect/Lean#2762]
#### Expected Behavior
Market orders should never fill at stale prices (e.g. fill-forward bars).

#### Actual Behavior
Market orders can be filled at stale prices in the following cases:
- using multiple assets at different resolutions and submitting a market order for the lower resolution symbol
- submitting market orders from scheduled events at times not aligned with the asset resolution

#### Potential Solution
Update the `FillModel.MarketFill` method to never return fills if the order was submitted **after** the latest data point was received. When a new data point is received, the market order will be filled at the bar `Open` price.

#### Reproducing the Problem
This simple algorithm shows the issue:
``` C#
    public class MarketFillOnNextBarRegressionAlgorithm : QCAlgorithm
    {
        private Symbol _symbol;

        public override void Initialize()
        {
            SetStartDate(2013, 10, 7);
            SetEndDate(2013, 10, 11);
            SetCash(10000);

            _symbol = AddEquity("AAPL", Resolution.Hour, Market.USA, true, 1).Symbol;
            AddEquity("SPY", Resolution.Minute, Market.USA, true, 1);
        }

        public override void OnData(Slice data)
        {
            if (Time.Day != 8) return;

            if (Time.Hour == 9 && Time.Minute == 45)
            {
                var lastData = Securities[_symbol].GetLastData();

                // log price from market close of 10/7/2013 at 4 PM
                Log($"{Time} - latest price: {lastData.EndTime} - {lastData.Price}");

                // this market order will be filled at the open of the next hourly bar (10:00 AM)
                SetHoldings(_symbol, 0.85);

                if (Portfolio.Invested)
                {
                    // order filled at price of last market close
                    throw new Exception("Unexpected fill on fill-forward bar with stale price.");
                }
            }
            if (Time.Hour == 9 && Time.Minute == 50)
            {
                var openOrders = Transactions.GetOpenOrders(_symbol);
                if (openOrders.Count == 0)
                {
                    throw new Exception("Pending market order was expected on current bar.");
                }
            }
            else if (Time.Hour == 10 && Time.Minute == 0)
            {
                if (!Portfolio.Invested)
                {
                    throw new Exception("Order fill was expected on current bar.");
                }
            }
        }
    }
```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by ikamanu** [comment]
Any ETA for this issue?

**Comment by jaredbroad** [comment]
For maximum backwards compatability and minimizing the core issue;
 - Add a new FillModelParameter FillOnStalePrices and default to `false`;
 - In fill models if prices stale - fill on prices stale is false -- do not fill and return
 - Refactor GetPriceBestEffort*Price to be TryGetBestEffort*Price; if fail; return.

**Comment by NickMessore** [comment]
1
