### ISSUE TITLE
Update NLog to support Mono ver. 5.10 and newer

### ISSUE THREAD

**Issue by snakefoot** [QuantConnect/Lean#2775]
https://github.com/QuantConnect/Lean/blob/84272fa9da9785ef8eb67eba04456ce677579a58/Logging/packages.config#L5-L7

Either update to NLog [ver. 4.4.13](https://www.nuget.org/packages/NLog/4.4.13) or the latest.

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/4772
