### ISSUE TITLE
How to model Forex market hours when they span 2 physical days?

### ISSUE THREAD

**Issue by kabua** [QuantConnect/Lean#2779]
#### Expected Behavior
In Forex, a trading day spans across two physical days. For example:

Logically Mon starts on Sun @ 5 pm ET and ends on Mon @ 5 pm ET. 
Logically Tue starts on Mon @ 5 pm ET and ends on Tue @ 5 pm ET.
Logically Wed starts on Tue @ 5 pm  ET and ends on Wed @ 5 pm ET.
Logically Thu starts on Wed @ 5 pm  ET and ends on Thu @ 5 pm ET.
Logically Fri starts on Thu @ 5 pm  ET and ends on Fri @ 5 pm ET.

How can we model this better?

#### Actual Behavior
Currently, the Forex market hours are model from midnight to midnight, this behavior is not correct. Most exchanges model the Forex market hours as stated above. Or they are closed from 5 pm ET to 5:15 pm or from 5 pm ET to 6 pm ET.

As one consequence, the current system calls the `OnEndOfDay()` methods at the wrong time of day as well as severl other related functions return the wrong values.

#### Potential Solution
There are several ways we could model these requirements. The correct way would require lots of changes, I believe, to the internals to the `SecurityExchangeHours` class. However, one quick and dirty way would be to a add two new optional fields to the `MarketHoursSegment` class. Which are:
```
        /// <summary>
        /// Gets the logical day this segment represents
        /// </summary>
        /// <remarks>
        /// If not specified in the json file, then it will be set to it's <see cref="LocalMarketHours.DayOfWeek"/> value.
        /// </remarks>
        [JsonProperty("logicalDay")]
        public DayOfWeek? LogicalDayOfWeek { get; internal set; }
```
and
```
        /// <summary>
        /// True if this segment marks the end of the normal market hours for this (logical) day.
        /// </summary>
        /// <remarks>
        /// If not specified in the json file, then it will be set to last segment who <see cref="State"/> is equal to <see cref="MarketHoursState.Market"/>.
        /// </remarks>
        [JsonProperty("endOfDay")]
        public bool? EndOfDay { get; internal set; }
```
They are marked as optional so that the existing json file doesn't have to be modified too much. Here is a snipit of the new format:
```
      "sunday": [
        {
          "logicalDay": "monday",
          "start": "17:00:00",
          "end": "1.00:00:00",
          "state": "market",
          "endOfDay": "false"
        }
      ],
      "monday": [
        {
          "logicalDay": "monday",
          "start": "00:00:00",
          "end": "17:00:00",
          "state": "market",
          "endOfDay": "true"
        },
        {
          "logicalDay": "tuesday",
          "start": "17:00:00",
          "end": "1.00:00:00",
          "state": "market"
        }
      ],
```
Which solves my immediate issue.

**Comment by jaredbroad** [comment]
Welcome to LEAN @kabua! Thank you for the detail & suggestions.

We model the data timezone and the exchange timezone differently in LEAN. The data-timezone represents what the physical file is stored in. The exchange timezone is the open-close times of the market/exchange. To keep things simple we immediately convert from the data-timezone into the exchange-timezone as soon as the files are read from disk.

What you're describing is actually a GMT day - "Logically Mon starts on Sun @ 5 pm ET and ends on Mon @ 5 pm ET.". The fx-brokerages who serve the US market say they are open from "5pm Sunday" but really they're just expressing the _real_ exchange hours in ET (Monday 12am UTC)

**Comment by kabua** [comment]
Hmm. I wasn't ware of the fact that FX market hours changed due to day-light saving etc. I was under the impression that the FX market always opened at 5 pm ET regardless of day-light savings.

So, what is the best way to compare Jan 1 @ 10:05 with Jun 1 @ 10:05 (local time)?
