### ISSUE TITLE
Build error with latest git master on GeneratedInsightsCollection

### ISSUE THREAD

**Issue by crystalneth** [QuantConnect/Lean#2795]
Build error with latest git master. Cloned repo and attempted to build.

.../Lean/Common/Algorithm/Framework/Alphas/Analysis/InsightManager.cs(111,111): Error CS0246: The type or namespace name 'GeneratedInsightsCollection' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (QuantConnect)

**Comment by jaredbroad** [comment]
Closing as no response and TravisCI building.
