### ISSUE TITLE
(Market hours) Holidays prior to 2017 not provided for Oanda CFDs

### ISSUE THREAD

**Issue by Doggie52** [QuantConnect/Lean#2796]
#### Expected Behavior
Holidays prior to 2017 present in https://github.com/QuantConnect/Lean/blob/master/Data/market-hours/market-hours-database.json for all Oanda CFDs.

#### Actual Behavior
No holidays before 2017 present in `market-hours-database.json` for Oanda CFDs, causing the algorithm to look for these and generate errors around missing files.

#### Potential Solution
Two potential solutions:

1. Ask (?) Oanda for their holidays before 2017.
1. Assume that all missing data files in these folders correspond to holidays. Scan for any non-weekend missing days.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
Closed by #3003

**Comment by Doggie52** [comment]
I disagree - holidays for plenty of CFDs are still missing, including `Cfd-oanda-WHEATUSD` and `Cfd-oanda-WTICOUSD`.

**Comment by mblum** [comment]
I realize this is an old issue but can we re-open, since I agree with @Doggie52 that this is not solved. 

I volunteer to fix this, if given directions on best practice. @Doggie52 proposed 2 possible solutions. How do you normally handle this, @jaredbroad ?
