### ISSUE TITLE
IB Brokerage occasionally fails to complete cash sync

### ISSUE THREAD

**Issue by StefanoRaggi** [QuantConnect/Lean#2799]
#### Expected Behavior
The IB Brokerage should never fail to complete the daily cash synchronization.

#### Actual Behavior
In some cases (especially during weekends), a live algorithm deployed to IB is terminated with the following error message:
```
System.Exception: The maximum number of attempts for brokerage cash sync has been reached.
```

#### Potential Solution
The `InteractiveBrokersBrokerage.DownloadAccount()` method is currently assuming that the `updatePortfolio` IB callback is always being called after the account download, which will in turn call `Reset` on the `ManualResetEvent` instance.
According to the IB documentation [here](https://interactivebrokers.github.io/tws-api/interfaceIBApi_1_1EWrapper.html#a790ccbe25033df73996f36a79ce2ce5a) the `updatePortfolio` callback will only be called when positions change.

The solution is to add this line at the top of the `InteractiveBrokersBrokerage.DownloadAccount()` method:
```
            _accountHoldingsResetEvent.Reset();
```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by bradhallett** [comment]
I have received this error this morning: "Runtime Error: The maximum number of attempts for brokerage cash sync has been reached.: StackTrace: System.Exception: The maximum number of attempts for brokerage cash sync has been reached." It appears that this issue is recurring. Can this be looked into further?
