### ISSUE TITLE
Remove "Error List"

### ISSUE THREAD

**Issue by pps83** [QuantConnect/Lean#2802]
When I build `Lean` completely new git clone at first it's ok, second time I press F7 (build solution) I get "Error List" window with no error displayed in it. I absolutely hate that "Error List" and I always have it disabled, but somehow I started getting it with `Lean` even though it's disabled in my VS settings:

![image](https://user-images.githubusercontent.com/1614246/50733108-d07b6080-113b-11e9-809b-4dd8445e4ed7.png)

This "Error List" just drives me crazy, I tried to figure out how come I started getting it and it seems that after first build is complete some of these packages have some settings that enable "Error List" somehow.

In my case inside `Lean\packages\Microsoft.VisualStudio.Shell.14.0.14.3.25407\lib\Microsoft.VisualStudio.Shell.14.0.xml` there is 
```
    <member name="M:Microsoft.VisualStudio.Shell.ErrorListProvider.BringToFront">
      <summary>Activates the Error List window and makes it visible.</summary>
    </member>
```

and when I remove it, it seems that this "Error List" annoyance disappears. Can this be somehow fixed in `Lean` itself, as this file isn't part of git repo and is a result from the build itself (I'm not C# developer, so now idea where all these packages come from). Also, there are other files in these packages that reference `Error List` the same way.

**Comment by jaredbroad** [comment]
Sorry @pps83 I don't think we can address this with LEAN. I'm glad you've found a hack around it.
