### ISSUE TITLE
Please actualize CONTRIBUTING.md

### ISSUE THREAD

**Issue by Ales999** [QuantConnect/Lean#2803]
#### Expected Behavior
git checkout -b issue-123/short-issue-description
...
git commit

> You can push your changes to your fork's master branch using:
$ git push origin master

#### Actual Behavior
$ git push origin master
**Everything up-to-date**

#### Potential Solution
git checkout master
git.exe merge --no-commit --ff issue-123/short-issue-description
git push origin master

**And here I am finally confused how to correctly, read:**

>After performing some work you'll want to merge in changes from the upstream/master. You can use the following two commands in order to assist upstream merging:
>$ git fetch upstream
>$ git rebase upstream/master **issue-123/short-issue-description**

#### System Information
Windows7x64, git version 2.20.1.windows.1

**Comment by mchandschuh** [comment]
The blurb you reference at the end is intended to remind contributors to keep their current copies up to date before submitting a pull request. Rebasing is the cleanest way of doing this so as to avoid unnecessary merge commits in the PR branch. If you're stuck on something in particular, DM me in slack and I can help you.
