### ISSUE TITLE
Create and Default To "Trade Insight Alpha Model"

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#2817]
#### Expected Behavior
All LEAN backtests would have the same powerful alpha ability as framework algorithms. Ideally, even classic algorithms would generate insights - and get the free powerful alpha charting. 

#### Actual Behavior
Currently, only the Framework backtests generate insights or the advanced plotting which comes along for free with them.

#### Potential Solution
Set a default alpha model in classic algorithms to generate insights intelligently based on the trades/order events of the user. E.g.
 - Long -> Insight Up
 - Short -> Insight Down
 - Liquidate -> Insight Flat
 - 100% capital allocation to 1 asset - 100% confidence.
 - 1% capital allocation to 100 assets - 1% confidence each.
 - Strategy average hold period => Insight Period? (weak indicator, better one needed)
 - Period-deviation of asset * average period holding => Asset predicted magnitude.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by simonsonjack** [comment]
@Martin-Molinero we can close this, right? I'm assuming all of this has been sufficiently accomplished by your changes a couple of months ago

**Comment by Martin-Molinero** [comment]
Good catch 👍 , correct, already implemented by https://github.com/QuantConnect/Lean/pull/3055
