### ISSUE TITLE
Daily and Hour Resolution History Requests Slow

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#2820]
#### Expected Behavior
- Hour resolution history request data throughput should be similar to other resolutions.

#### Actual Behavior
- Hour resolution history request is an order of magnitude slower than for example a minute resolution history request. This is because the entire hour data for each symbol is stored **in a single file** causing a big overhead for just fetching one data point (vs separated daily zips for Minute Resolution)

#### Potential Solution
- Maybe we could jump around in the file without actually iterating through every line by using a binary search algorithm + [File.Seek](https://docs.microsoft.com/en-us/dotnet/api/system.io.filestream.seek?view=netframework-4.5.2).

#### Reproducing the Problem
- Execute an algorithm performing a `History(_symbol, 1, Resolution.Hour);` on each OnData.

#### System Information
N/A
#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
#### Step 2: Caching, and only _reading_ the history once from disk. 
Definitely the fastest idea from @gsalaz98; but will need some smarts to prevent memory explosion. Cache the results of the history call and only parse it from disk once. Imagine `History` asking for 1 minute bar - every minute of the day; it will parse the minute zip file 390x per day. Caching the instances parsed will reduce work done 390x (less overhead for returning relevant rows and caching).

**Comment by jaredbroad** [comment]
Caching sounds worth a shot. We might need to be smart about who gets cached though. The daily data is about 6GB in memory so can't cache it all.  

IMHO the key issue isn't parallel or parsing the data -- its the design of the data feed which disposes of the entire enumerator stack each day - even for files which have more than 1-day of data. This causes the feed to need to start from scratch each day, re-enumerating the whole daily file each day.

**Comment by stan4git** [comment]
PR is out.
https://github.com/QuantConnect/Lean/pull/2899

6GBs is specifically for shared data web service(remote data source). Not for standalone LEAN instance.

On interesting finding during the performance profile is - Each LEAN backtest instance spins up about 16 user threads, two of which are taking about 90% of the time/computation while others doing very little work.

We should be able to make quite a performance boost by adopting C# managed async task pool in the IO/worker components, specifically means, each (I/O) task shouldn't be thread-blocking and could be parallel. Once blocked, the thread should be released to process other tasks.

**Comment by stan4git** [comment]
Here is a quick summary of performance with the benchmark algo.

(Per request time unit: Ticks)
ZipFileCache Daily Avg: | 111071.7248
ZipFileCache Minute Avg: | 16564.97222
DataPointCache Daily Avg: | 2383.724771
DataPointCache Minute Avg: | 11974.46296

Daily request improvement: | 97.85%
Minute request improvement: | 27.71%
