### ISSUE TITLE
Could not load file or assembly 'QuantConnect.Common, Version=2.4.0.1, Culture=neutral, PublicKeyToken=null' 

### ISSUE THREAD

**Issue by Cloudmersive** [QuantConnect/Lean#2823]
Could not load file or assembly 'QuantConnect.Common, Version=2.4.0.1, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.'

#### Expected Behavior
Lean runs as expected for version Install-Package QuantConnect.Lean -Version 2.4.5035

#### Actual Behavior
Installed from nuget and tried to use/run but getting the above dynamic load error

#### Reproducing the Problem
Installed from Nuget: https://www.nuget.org/packages/QuantConnect.Lean/

Install-Package QuantConnect.Lean -Version 2.4.5035

#### System Information
Windows 10 latest

**Comment by Cloudmersive** [comment]
I was able to "Fix" this by downgrading to 2.4.0.3, so it's a breaking change made in a later version

**Comment by jaredbroad** [comment]
Don't recommend 2.4.0.3 its very old. If you can pull all the dependencies (Common etc) separately and it should fix the issue - likely your nuget didn't pull the dependencies for some reason. I've just re-run the command and its working OK now.
