### ISSUE TITLE
LeanDataWriter Unable to Write Futures and Options to Disk

### ISSUE THREAD

**Issue by gsalaz98** [QuantConnect/Lean#2826]
#### Expected Behavior

I am able to write options and futures to disk via `LeanDataWriter`

#### Actual Behavior

I'm unable to write options or futures data onto disk using `LeanDataReader` because the constructor has an if statement checking if we've passed it a futures or options symbol. In addition, there is a call to an outdated method called `GenerateZipEntryName` (not covered by unit tests). There exists another implementation of the same method with the same name, with support for futures and options.
#### Potential Solution

Changing the parameters in the method call to `GenerateZipEntryName` in `ToolBox/LeanDataWriter.cs` from

```C#
Compression.Zip(data, tempFilePath, LeanData.GenerateZipEntryName(_symbol.Value, _securityType, date, _resolution, _dataType));
```

to

```C#
Compression.Zip(data, tempFilePath, LeanData.GenerateZipEntryName(_symbol, date, _resolution, _dataType));
```
Deleting the old code is possible as well. There are no other uses of that method across the codebase except for the one invocation referenced above.

-------------------

Adding futures and options to the constructor `LeanDataWriter` in `LeanDataWriter.cs`, from:
```C#
if (_securityType != SecurityType.Equity && _securityType != SecurityType.Forex && _securityType != SecurityType.Cfd && _securityType != SecurityType.Crypto) {...}
```
to

```C#
if (_securityType != SecurityType.Equity && _securityType != SecurityType.Forex && _securityType != SecurityType.Cfd && _securityType != SecurityType.Crypto && _securityType != SecurityType.Future && _securityType != SecurityType.Option) {...}
```

#### Reproducing the Problem

Create a new `Symbol` object with the method `CreateFuture` or `CreateOption`, then try to write to disk using 
```C#
new LeanDataWriter(...).Write(...)
```
#### System Information

Windows 10 x64
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Fixed in #2827
