### ISSUE TITLE
Python CoarseFundamental data selection process is slow

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#2838]
#### Expected Behavior

- Python and C# `CoarseFundamental` selection process should be executed at the same speed (or as close as possible).
#### Actual Behavior

- The Python `CoarseFundamental` selection process has to convert the data members its using from C# to python dinamically, causing an execution overhead
#### Potential Solution

- Remove the need for the selection process to convert any data to Python. This could be achieved by preconverting all data members to Python in the data threads. 
- Improve the conversion speed. Reducing the size of the data to convert to python (for example converting C# decimal to C# double before conversion to Python)
#### Reproducing the Problem

Execute the python benchmark algorithm.
The selection function `def CoarseSelectionFunction(self, coarse)` is accessing only 1 member of the coarse data, but its already causing an overhead. If it were to access even more members, the overhead increses linearly.
[python_benchmark_algo.txt](https://github.com/QuantConnect/Lean/files/2773881/python_benchmark_algo.txt)

#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
- Close as focus on Python 3.11
 - Focus on stateless universe design which would pass the func filter to backend and run ahead without assuming any algorithm state in the filter selection.
