### ISSUE TITLE
Isolate indicators library

### ISSUE THREAD

**Issue by amittleider** [QuantConnect/Lean#2863]
It would be great to have the indicators library with minimal dependencies, compiled into dotnet standard, and have its own independent nuget package.

This library is better than TA-Lib as far as real-time performance is concerned because it can update values one by one. The downside is that the library is not independent -- it has dependencies from other dlls of the QuantConnect libs, so if you try to depend on just the one indicators nuget, you get errors like:
```
Message: System.TypeLoadException : Could not load type 'QuantConnect.Indicators.IIndicator' from assembly 'QuantConnect.Common, Version=2.4.0.1, Culture=neutral, PublicKeyToken=null'.
``` 
because you need to pull Common.
It's also not compiled in dotnet standard, so we can't use it in our linux projects. 

It would be really great for us if the library had:
1. Minimal dependencies on other QuantConnect objects (IndicatorDataPoint, SubscriptionDataConfig, BaseData, etc.). Imagine the RSI object having a simple Update(decimal newData) method.
2. Compiled in dotnet standard so our linux projects could depend on it
3. All the indicators still usable in Pythonnet
4. A standalone nuget package, like Cryptowatch's TA-Lib nuget package.

I'd like to know if it's useful for others as well as myself, and any other thoughts. I have set up a sample repo of the proposed changes here https://github.com/amittleider/Streaming-TALib.

**Comment by guanm326** [comment]
given the same data and indicator (rsi), are both talib calculate indicators the same as QuantConnect streaming?

**Comment by amittleider** [comment]
The RSI is equal to within 6 decimal places (maybe more?). But, I don't think it's a relevant question to the topic. The topic is more about ease of use of QuantConnect indicators. Because TA-Lib has less dependencies (just arrays of floats), it can be easier to use.

**Comment by jaredbroad** [comment]
Thanks @amittleider, it is a great idea. I'll leave this issue open but it's not a simple task as we designed it for use in LEAN so might take a while to pull apart. If you reuse the LEAN indicators in your repo could you please call it LEAN-Indicators; 'Streaming-TALib' drops all the work of the community.

**Comment by amittleider** [comment]
@jaredbroad I have renamed the repository. Thanks to you (and the rest) for the indicators!

**Comment by Martin-Molinero** [comment]
> Minimal dependencies on other QuantConnect objects (IndicatorDataPoint, SubscriptionDataConfig, BaseData, etc.). Imagine the RSI object having a simple Update(decimal newData) method.
    Compiled in dotnet standard so our linux projects could depend on it
    All the indicators still usable in Pythonnet
    A standalone nuget package, like Cryptowatch's TA-Lib nuget package.

All QC repos & projects can be found as nugets at https://www.nuget.org/profiles/jaredbroad. Lean is currently using .Net6 which is cross platform, there are no issue running under linux.
