### ISSUE TITLE
Logs Pandas and Numpy version

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#2871]
#### Expected Behavior
Lean displays pandas and numpy version. It is important to display this information since updates on those packages can break the PandasConverter implementation used in History Requests for python algorithms. 

#### Actual Behavior
Lean does not display pandas and numpy version.

#### Potential Solution
Logs the information when an instance of PandasConverter is created. 

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
Core issue is knowing what version of the DockerLeanFoundation file is running not the individual python libaries. Design needed to address that.
