### ISSUE TITLE
Custom Account Currenty has a limitation on its length

### ISSUE THREAD

**Issue by Adalyat** [QuantConnect/Lean#2874]
#### Expected Behavior

Custom Account currency should accept any custom currency with different length. For example, Binance uses USDT (pegged currency) as account curreny.

#### Actual Behavior

I setup an Account curreny using
`SetAccountCurrency("USDT");`
And get an ArgumentException "Cash symbols must be exactly 3 characters."

#### Reproducing the Problem

Use any Binance account to replicate the problem.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Adalyat** [comment]
![2019-01-31_22-33-45](https://user-images.githubusercontent.com/3648114/52080874-e436ad00-25a9-11e9-81ce-3ca6619b63bf.png)

**Comment by Adalyat** [comment]
After I removed this limitation locally I've got another one "Currency pairs must be exactly 6 characters"

![2019-01-31_22-33-03](https://user-images.githubusercontent.com/3648114/52081008-32e44700-25aa-11e9-9532-038c41bff307.png)

**Comment by jaredbroad** [comment]
@Adalyat the root challenge if you care to take a crack at it --> resolving the account currency from the pair string e.g. "EURUSD". It uses the 3/6 length to determine the individual currencies in the pair. Something like: ETHUSDT is difficult to resolve: is it `ETHU-SDT`? or `ET-HUSDT` etc.

It might be simplest to simply start accepting "/" as a divider.

**Comment by StefanoRaggi** [comment]
Totally agree on the separator, maybe better use "-" if we need them in filenames?

Btw, this was suggested by @mchandschuh a while ago: https://github.com/QuantConnect/Lean/issues/2744
