### ISSUE TITLE
Fix bitfinex order event status filled

### ISSUE THREAD

**Issue by Adalyat** [QuantConnect/Lean#2878]
#### Expected Behavior

Bitfinex brokerage should send Filled status if order filled.

#### Actual Behavior

Bitfinex send trade size, but not filled. That's why If order filled in multiple trades (partially) we always emit OrderEvent with PartiallyFilled status.

#### Potential Solution

Substitute PartiallyFilled with Filled status on the last part of the order execution.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by StefanoRaggi** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/2879
