### ISSUE TITLE
Use Bitfinex trade update information to calc fees

### ISSUE THREAD

**Issue by Adalyat** [QuantConnect/Lean#2881]
#### Actual Behavior

On brokerage order fill we calculate fees via BitfinexFeeModel based on trading symbol, quantity and other information. Seems we can use trade update information to use real fee values for each order fill.

#### Potential Solution

Use `tu` entries to determine fee and fee currency for trace

#### Reproducing the Problem

This information is available in BitfinexBrokerage on order execution event.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by StefanoRaggi** [comment]
Closed by #2882
