### ISSUE TITLE
Create an IQFeedDataDownloader

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#2886]
#### Expected Behavior
Ability to download and save data in LEAN format from IQFeed

#### Actual Behavior
No `IQFeedDataDownloader`

#### Potential Solution
Create an IQFeedDataDownloader class and put it into the `QuantConnect.ToolBox` project. It should implement an IDataDownloader interface. Pull request should submit a bounty claim to  https://www.bountysource.com/issues/69682744-create-an-iqfeeddatadownloader

Class should be stored in the IQFeed Folder https://github.com/QuantConnect/Lean/tree/master/ToolBox/IQFeed

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by mathpaquette** [comment]
@jaredbroad why this one still open?

**Comment by aytacasan** [comment]
@mathpaquette Actually i already developed this functionality almost a year ago for the community. @jaredbroad Because of that this issue could close.

**Comment by mathpaquette** [comment]
@aytacasan yes I know. On the other hand, Ill change your implementation because the performance could be improved by a lot. Are you still an IQFeed subscriber?

**Comment by aytacasan** [comment]
@mathpaquette you are right performance could be improve. If you do that i would be grateful to you. And yes i'm still IQFeed subscriber.

**Comment by mathpaquette** [comment]
@aytacasan thats very good because ill use your brain to review the PR. thanks!

**Comment by aytacasan** [comment]
@mathpaquette I am willing to do it happily if there is anything I can do. Thanks to you too.

**Comment by mathpaquette** [comment]
@aytacasan awesome, created #iqfeed on QuantConnect's slack if you can join. talk you soon. thanks.,

**Comment by mathpaquette** [comment]
@aytacasan check this out. Ill list down all improvements I made. Stated mostly with ticks data which was incredibly slow: https://github.com/mathpaquette/Lean/commit/fc31d2f9db66fc80bcb32ba0785f579bc3fc985e

**Comment by aytacasan** [comment]
@mathpaquette #iqfeed is a channel name? So, how can i join? I searched it on slack and can not find ant result about it. I'm not a good user of slack only follows public channel.

**Comment by mathpaquette** [comment]
https://quantconnect.slack.com/archives/C0119GBHHPB

**Comment by aytacasan** [comment]
@mathpaquette when i click the link i'm receiving that messag;

There’s been a glitch… We’re not quite sure what went wrong. You can go back, or try looking on our Help Center if you need a hand.

Anyway it's not so important. I'll look into your PR as soon as possible.

**Comment by mathpaquette** [comment]
@aytacasan ill right. not in the final shape not I see a lot of improvements just in this shape. Are you dealing with ticks data ?

**Comment by aytacasan** [comment]
@mathpaquette i'm using all tick, second, minute, hourly, daily etc. But especially using tick data.

**Comment by mathpaquette** [comment]
@aytacasan can you join https://gitter.im/IQFeed-CSharpApiClient/public

**Comment by mathpaquette** [comment]
@aytacasan I need you to review this one. https://github.com/QuantConnect/Lean/pull/4302 huge performance increase!

**Comment by aytacasan** [comment]
@mathpaquette Wow increased performance 27X! It's amazing. ı'll review it as soon as possible. Also i'll talk with my colleague for test it. Often he is downloading historical tick data from IQFeed for historical backtests. This performance improvement affected both download historical data to local hard drive (for backtest the strategies) and warming up strategies (consolidatoes, indicators etc.) with data. Am i right?

**Comment by mathpaquette** [comment]
@aytacasan just historical download for now. Ill integrate the realtime part as well.

**Comment by mathpaquette** [comment]
@jaredbroad you can close this one.
