### ISSUE TITLE
Option strategy limit order

### ISSUE THREAD

**Issue by hippich** [QuantConnect/Lean#2900]
This is a rather open-ended ticket, as I am not sure there is a quick solution to it.

#### Expected Behavior
I would expect to be able to place limit orders for Option Strategy based on the total price of the combo, not an individual legs.

#### Actual Behavior
Right now all strategies employ Market Order for each individual leg of the combo order. 

To better understand what I mean, take a look at OptionLegData class - each of them has their own OrderPrice and OrderType - https://github.com/QuantConnect/Lean/blob/master/Common/Securities/Option/OptionStrategy.cs (same applies to UnderlyingLegData)

Yet when trading with IB, TastyWorks, etc, trader most of the time deal with one price for the whole combo. Brokerages deal with these differently, but for the most "standard" types of option strategies broker can give guarantees either fill at the price entered, or not filling any legs at all. Some brokerages publish these orders as combo on exchanges (if exchange supports such orders natively) or automatically places individual legs with different exchanges (the case of SMART routed combos in IB most of the time)

From looking at how strategies are defined in LEAN (https://github.com/QuantConnect/Lean/blob/master/Common/Securities/Option/OptionStrategies.cs) and how trading is implemented (https://github.com/QuantConnect/Lean/blob/master/Algorithm/QCAlgorithm.Trading.cs#L549) I am not sure with the existing approach it is possible to implement something like that. It feels like it would almost require creating own Security based on the existing option chain, and not deal with individual options when trading combos, i.e. something similar to `this.addOptionStrategy(XXX)` and be able to trade it as one instrument.

Any thoughts and ideas are appreciated. I am new to the LEAN framework, so there is a chance I am missing something - in this case I would appreciate pointers towards how I can handle option combo orders as a single unit instead of dealing with them on per-leg basis.

**Comment by hippich** [comment]
From my brief look into Alpha models, it also deals with single securities, so creating Alpha models providing insight for multi-leg positions becomes problematic as well...

One idea came up - ThinkOrSwim platform uses symbols like `.SPY190315C271-.SPY190315C272+.SPY190315P270-.SPY190315P269` to describe multi-leg contract. Perhaps we could do something similar to work with multilegged contract as a one security.

**Comment by jaredbroad** [comment]
Alphas are multi symbol.
This is addressed by `Insight.Group()`

Please check out the documentation on quantconnect.com it covers this
feature.

**Comment by hippich** [comment]
Thanks!

**Comment by hippich** [comment]
So from reading source code it appears that `Insight.Group()` just sets `GroupId` to unique value, but portfolio needs to handle it on its own (i.e. ensure that all insight from the group get an appropriate target). Is this correct?

**Comment by Martin-Molinero** [comment]
OptionStrategy combo order support has already been added, current API are for market orders
- LimitOrders need a new API, `LimitOrder(OptionStrategy strategy, int quantity, decimal limitPrice, string tag = "", IOrderProperties orderProperties = null)`
- Example algorithms C#/Py

**Comment by Martin-Molinero** [comment]
This can be achieved manually creating the desired strategy legs and submitting them through the new `ComboLimitOrder` API see example `CoveredCallComboLimitOrderAlgorithm` https://github.com/QuantConnect/Lean/blob/master/Algorithm.CSharp/CoveredCallComboLimitOrderAlgorithm.cs

**Comment by nishantpant** [comment]
How would you close a ComboLimitOrder for a vertical spread? By simply reversing the +1 and -1 (i.e by reversing the leg you buy and sell) ?
