### ISSUE TITLE
Adding Iron Condor option strategy

### ISSUE THREAD

**Issue by hippich** [QuantConnect/Lean#2901]
I wanted to implement Iron Condor option strategy but a bit puzzled on how to test it. I did not find any examples of unit tests for option strategies (besides one sample strategy utilizing straddle option strategy).

I also assume I can't really test this on live options data, since options data is available only when running on quantconnect.com, is that correct? 

Here is example of code I want to test - https://github.com/hippich/Lean/commit/29064c092a7ed6dd6af6312670a17c24ed8d2590

**Comment by Martin-Molinero** [comment]
Hey @hippich!
Sorry for the delay, Iron Condor strategy is already implemented, can see example usage at https://github.com/QuantConnect/Lean/blob/58793acae8ba72a35a53cc146f5011d50ea3277c/Algorithm.CSharp/OptionEquityIronCondorRegressionAlgorithm.cs
