### ISSUE TITLE
BrokerageSetupHandler should not clear CashBook with BacktestingBrokerage

### ISSUE THREAD

**Issue by StefanoRaggi** [QuantConnect/Lean#2912]
#### Expected Behavior
`BrokerageSetupHandler` should only clear the `CashBook` when used with real brokerages.
It should not do this with `PaperBrokerage` and `BacktestingBrokerage`.

#### Actual Behavior
`BrokerageSetupHandler` is also clearing the `CashBook` when used with `BacktestingBrokerage`.

#### Potential Solution
In `BrokerageSetupHandler.Setup` update this check to also exclude `BacktestingBrokerage`:
``` C#
// if (liveJob.Brokerage != "PaperBrokerage")
if (liveJob.Brokerage != "PaperBrokerage" && liveJob.Brokerage != "BacktestingBrokerage")
{
    //Zero the CashBook - we'll populate directly from brokerage
    foreach (var kvp in algorithm.Portfolio.CashBook)
    {
        kvp.Value.SetAmount(0);
    }
}
```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Given the resolution of https://github.com/QuantConnect/Lean/pull/2913 I believe this issue can be closed.
