### ISSUE TITLE
Manual trade on managed (OANDA-)account crashes LEAN

### ISSUE THREAD

**Issue by radi-ka** [QuantConnect/Lean#2916]
#### Expected Behavior
Taking a non-LEAN(manual) trade on an (OANDA-)account that is used by LEAN updates the portfolio an triggers a call to `QCAlgorithm.OnOrderEvent`.

#### Actual Behavior
LEAN crashes with logging: `Log.Error($"OandaBrokerage.OnTransactionDataReceived(): order id not found: {transaction.OrderID}");`

#### Potential Solution
Incoming Transactions are scanned for their `OrderId`, which is used to lookup the original `Order`. If no order is found an `Error` is logged. 
I would propose to handle the "no `Order` found" case differently:
The transaction should be parsed for needed information and the portfolio should be updated accordingly.

#### Reproducing the Problem
1. Use an OANDA account with a live deployment
2. issue a trade via web/mobile client of OANDA.
3. watch LEAN crash

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
This is by design. We cannot maintain state and portfolio value with
external unknown orders. To lower risk we stop LEAN.

**Comment by jaredbroad** [comment]
Imagine your algorithm says 
```
if no holdings: 
     Buy(EURUSD)
```
and a human sells all positions from the web console, triggering the algorithm to immediately rebuy the position. With infinite algorithms and infinite human behavior, its too risky to support human-machine engagements.

We have manual "commands" which allow triggering orders in a stateful way from the QC-web console. These are handled by the LEANManager which is state-aware. If you want some way to have human-machine engagement please use the QC web console order panel or your own implementation of the LeanManager class.
