### ISSUE TITLE
Submitted orders are not always added to open orders immediately

### ISSUE THREAD

**Issue by StefanoRaggi** [QuantConnect/Lean#2920]
#### Expected Behavior
Calling `GetOpenOrders` immediately after submitting an order of any type (except for market orders filled synchronously) should **always** include the new order in the returned list.

#### Actual Behavior
`GetOpenOrders` will **sometimes** return the new order.

#### Potential Solution
Update `BrokerageTransactionHandler.AddOrder` to wait for the transaction handler thread to process the new order ticket before returning it to the caller.

#### Reproducing the Problem
The frequency of this issue is system dependent but it can be repeated consistently by adding a delay in the transaction handler thread loop and running this unit test:
``` C#
        [Test]
        public void AddOrderWaitsForOrderToBeProcessed()
        {
            var algorithm = new QCAlgorithm();
            algorithm.SubscriptionManager.SetDataManager(new DataManagerStub(algorithm));

            var security = algorithm.AddSecurity(SecurityType.Equity, "SPY");
            security.SetMarketPrice(new Tick { Value = 150 });
            algorithm.SetFinishedWarmingUp();

            var transactionHandler = new BrokerageTransactionHandler();
            transactionHandler.Initialize(algorithm, new BacktestingBrokerage(algorithm), new BacktestingResultHandler());

            algorithm.Transactions.SetOrderProcessor(transactionHandler);

            Task.Run(() => transactionHandler.Run());

            var ticket = algorithm.LimitOrder(security.Symbol, 1, 100);

            var openOrders = algorithm.Transactions.GetOpenOrders();

            transactionHandler.Exit();

            Assert.AreEqual(1, openOrders.Count);
        }
```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Instead of waiting can force synchronized processing of the order to keep
system snappy.
