### ISSUE TITLE
Allow custom data with market hours defined in the database

### ISSUE THREAD

**Issue by ebengtso** [QuantConnect/Lean#2923]
#### Expected Behavior
Allow us to add custom data from any market.

#### Actual Behavior
Currently it's hardcoded Market.USA and SecurityType.Base

#### Potential Solution
The signature of the function QCAlgorittm.AddData<T> should include two additional parameters: Market and SecurityType, defaulting to Market.USA and SecurityType.Base.

#### Checklist
- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by erikbengtson** [comment]
Hi, here is the code to allow adding custom data with market hours defined in the database
`
        /// <summary>
        /// AddData<typeparam name="T"/> a new user defined data source, requiring only the minimum config options.
        /// </summary>
        /// <param name="symbol">Key/Symbol for data</param>
        /// <param name="resolution">Resolution of the Data Required</param>
        /// <param name="market">Specifies the market name</param>
        /// <param name="fillDataForward">When no data available on a tradebar, return the last data that was generated</param>
        /// <param name="leverage">Custom leverage per security</param>
        /// <returns>The new <see cref="Security"/></returns>
        /// <remarks>Generic type T must implement base data</remarks>
        public Security AddData<T>(string symbol, Resolution resolution, string market, bool fillDataForward = false, decimal leverage = 1.0m)
            where T : IBaseData, new()
        {
            //Add this to the data-feed subscriptions
            var symbolObject = new Symbol(SecurityIdentifier.GenerateBase(symbol, market), symbol);

            //Add this new generic data as a tradeable security:
            var config = SubscriptionManager.SubscriptionDataConfigService.Add(typeof(T),
                symbolObject,
                resolution,
                fillDataForward,
                extendedMarketHours: false,
                isCustomData: true);
            var security = Securities.CreateSecurity(symbolObject, config, leverage);
            
            AddToUserDefinedUniverse(security, new List<SubscriptionDataConfig> { config });
            return security;
        }`
