### ISSUE TITLE
Error subscribing Futures symbol in Interactive Brokers with ambiguous specification

### ISSUE THREAD

**Issue by miguelvm** [QuantConnect/Lean#2924]
There are Futures symbols in Interactive Brokers that have the same `contract.Symbol` but are different contracts. For example the silver futures contract SI  (Futures.Metals.Silver in QC) with 5000 multiplier has the same Interactive Brokers symbol for both the 5000 and the 1000 multiplier.

#### Expected Behavior
The subscription is processed without error and Futures Chains are received for the subscribed contract.

#### Actual Behavior

20190220 10:59:44.540 Trace:: InteractiveBrokersBrokerage.Subscribe(): Subscribe Request: SI29K19
20190220 10:59:44.582 Trace:: InteractiveBrokersBrokerage.HandleError(): RequestId: 33 ErrorCode: 200 - The contract description specified for SI is ambiguous;. you must specify the multiplier or trading class.. Origin: Subscribe: FUT SI USD NYMEX
20190220 10:59:44.582 ERROR:: Brokerage.OnMessage(): Error - Code: 200 - The contract description specified for SI is ambiguous;. you must specify the multiplier or trading class.. Origin: Subscribe: FUT SI USD NYMEXErr

#### Potential Solution
Hack: In the class InteractiveBrokersBrokerage.cs line 1727 insert the following code in the method CreateContract:

`if (contract.Symbol.Equals("SI")) {
contract.Multiplier = "5000";
}`

Suggested solution: There are other futures contracts with the same problems: DAX in Interactive Brokers has the same symbol for both the DAX (25 multiplier) and mini DAX (5 multiplier). Since EUREX futures are still unsupported this has not been tested but the same could happen. I would suggest to refactor the IB symbol mapper in order to include the multiplier parameter for the contracts that require it. There should be a SI and SIL QC futures contracts that translate into SI 5000 multiplier and SI 1000 multiplier inside the CreateContract method. Likewise there should be a DAX and MDAX QC futures contracts that translate into DAX 25 multiplier and DAX 5 multiplier when sent to IB.

#### Reproducing the Problem
Subscribe the futures contract Futures.Metals.Silver from any algorithm.

#### System Information
Tested under Lean master in Ubuntu 18.04.1

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by adriantorrie** [comment]
@miguelvm is this still an issue?
