### ISSUE TITLE
ParallelRunnerController consuming a lot of CPU

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#2928]
#### Expected Behavior

- `ParallelRunnerController` should not waste CPU time
#### Actual Behavior

- `ParallelRunnerController.ProcessHoldQueue()` 
```
                foreach (var workItem in _holdQueue.GetConsumingEnumerable(token))
                {
                    if (workItem.IsReady)
                    {
                        _processQueue.Add(workItem, token);
                    }
                    else
                    {
                        _holdQueue.Add(workItem, token);
                    }
                }
```
If the `workItem` is not ready it will add it and get it in a tight loop until its ready. Profiling bellow shows the CPU consumption of the thread and where its being used 
![imagen](https://user-images.githubusercontent.com/18473240/53123727-7b9f7800-3538-11e9-8c0c-9d8b3d58bae9.png)

#### Potential Solution

- A simple solution would be: if the `_holdQueue` has no `workItem` which is ready, the thread should sleep.
```
                foreach (var workItem in _holdQueue.GetConsumingEnumerable(token))
                {
                    if (workItem.IsReady)
                    {
                        _processQueue.Add(workItem, token);
                    }
                    else
                    {
                        if (!_holdQueue.Any(x => x.IsReady))
                        {
                            Thread.Sleep(5);
                        }
                        _holdQueue.Add(workItem, token);
                    }
                }
```
Performance profile of this solution is bellow. **CPU usage went down from 25% to 15%**, having no real impact on execution times (see after image bellow).
![imagen](https://user-images.githubusercontent.com/18473240/53123988-1435f800-3539-11e9-9116-a13a4406e8c1.png)

[Proposed Solution C# HistoryRequestBenchmark]
57.08 seconds at 16k data points per second. Processing total of 904,955 data points.
54.53 seconds at 17k data points per second. Processing total of 904,955 data points.
53.51 seconds at 17k data points per second. Processing total of 904,955 data points.
51.26 seconds at 18k data points per second. Processing total of 904,955 data points.
51.51 seconds at 18k data points per second. Processing total of 904,955 data points.
51.24 seconds at 18k data points per second. Processing total of 904,955 data points.
[MASTER C# HistoryRequestBenchmark]
56.97 seconds at 16k data points per second. Processing total of 904,955 data points.
53.48 seconds at 17k data points per second. Processing total of 904,955 data points.
52.25 seconds at 17k data points per second. Processing total of 904,955 data points.
51.07 seconds at 18k data points per second. Processing total of 904,955 data points.
51.48 seconds at 18k data points per second. Processing total of 904,955 data points.
51.07 seconds at 18k data points per second. Processing total of 904,955 data points.

--------
[Proposed fix EmptyMinute400Daily10YearBenchmark] 
19.10 seconds at 44k data points per second. Processing total of 840,365 data points.
18.31 seconds at 46k data points per second. Processing total of 840,365 data points.
18.43 seconds at 46k data points per second. Processing total of 840,365 data points.
17.67 seconds at 48k data points per second. Processing total of 840,365 data points.
18.06 seconds at 47k data points per second. Processing total of 840,365 data points.
17.88 seconds at 47k data points per second. Processing total of 840,365 data points.
[MASTER EmptyMinute400Daily10YearBenchmark]
20.69 seconds at 41k data points per second. Processing total of 840,365 data points.
20.93 seconds at 40k data points per second. Processing total of 840,365 data points.
19.48 seconds at 43k data points per second. Processing total of 840,365 data points.
18.68 seconds at 45k data points per second. Processing total of 840,365 data points.
18.86 seconds at 45k data points per second. Processing total of 840,365 data points.
18.88 seconds at 45k data points per second. Processing total of 840,365 data points.

Profile showed same ~10% CPU usage reduction, no significant impact on execution times.

#### Reproducing the Problem

- The performance profile was captured using the C# `HistoryRequestBenchmark` https://github.com/QuantConnect/Lean/blob/master/Algorithm.CSharp/Benchmarks/HistoryRequestBenchmark.cs
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Make sure to profile the dense universe benchmarks as well like 400 minute
securities

**Comment by Doggie52** [comment]
Ah! I have been seeing this but it never hit me that it would be a bug worthy of an issue. Thank you for looking into this, this is definitely an area deserving of work :)!
