### ISSUE TITLE
Add Support For Option Tick Data

### ISSUE THREAD

**Issue by jandykwan** [QuantConnect/Lean#2959]
I am using the Lean engine to backtest, I add subscribe to the tick data with the following code:

AddOption(UnderlyingTicker, resolution: Resolution.Tick);

but i found the engine try to load the second data. 

I found the following line in OptionChainUniverseSubscriptionEnumeratorFactory line 114:

// Making sure data is non-tick
var resolution = config.Resolution == Resolution.Tick ? Resolution.Second : config.Resolution;

why do this?

**Comment by Doggie52** [comment]
Tick resolution option data is not available: https://www.quantconnect.com/data/tree/option/usa

**Comment by jandykwan** [comment]
I have downloaded the Tick data to my disk, would i do the Tick resolution backtest locally with the engine?

**Comment by jaredbroad** [comment]
Sorry it is not supported at this time. As its a rare request I can't give
an ETA at this time. To confirm you want to do options tick resolution
backtesting?

**Comment by jandykwan** [comment]
Yes. I want to do some HFT backtest base on the tick history.   I think Lean can do this.

**Comment by jaredbroad** [comment]
This should be possible with a touch of work:

It's forcing the underlying to be a trade bar so it can be filled forward (ticks can't be copied forward as they are point values) -- this is so we always have a bar when we calculate the options universe. I think this only applies to the underlying, not the options trades themselves. If you tweak it a little to only apply that resolution to the underlying subscription it might work.
