### ISSUE TITLE
Issuing Flat insights with large magnitudes can inflate Alpha score

### ISSUE THREAD

**Issue by Doggie52** [QuantConnect/Lean#2960]
#### Expected Behavior
Issuing `Flat` insights should be treated intelligently by the scoring system.

#### Actual Behavior
Issuing repeated `Flat` insights with an artificially large `Magnitude` inflates the Alpha score as it guarantees perfect 100% direction and magnitude scores for that insight.

#### Potential Solution
A couple of solutions, ranked in order of my personal preference:

1. Have `Flat` insights "cancel" other insights (have them expire and cause score to be calculated as if their expiry was now). Markets change over time and we should be allowed to update/refine our estimate of the period of an insight over time.
1. Have `Flat` insights not contribute to any score whatsoever. After all, what worth do they really have?

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Thanks for reporting this issue @Doggie52 👍
