### ISSUE TITLE
Makes QLNet available for Algorithms

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#2976]
#### Expected Behavior
C# algorithms can use QLNet library.

#### Actual Behavior
QLNet library is used for Options pricing, but it is restricted to Common project.

#### Potential Solution
Adds QLNet reference to Algorithm Project

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
`QLNet` is already available in the cloud
