### ISSUE TITLE
No documentation exists for non-equity data

### ISSUE THREAD

**Issue by gsalaz98** [QuantConnect/Lean#2977]
#### Expected Behavior

Explain data formats to anybody interested in downloading or importing data
#### Actual Behavior

No documentation exists for non-equity data
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Fixed by #2978
