### ISSUE TITLE
Running lean from google colab

### ISSUE THREAD

**Issue by ahmedengu** [QuantConnect/Lean#2981]
Greetings,

It would be nice if we can run lean from google colab

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closing this issue for now
