### ISSUE TITLE
Add Mesa Adaptive Moving Average indicator

### ISSUE THREAD

**Issue by madnesspie** [QuantConnect/Lean#2986]
Hi! :) I have a code and a tests of 2 technical indicators by John Ehlers. I want to push it into Lean.
The indicators are described in original Ehlers [paper](http://www.mesasoftware.com/papers/MAMA.pdf)

#### Expected Behavior
Mesa Adaptive Moving Average and Following Adaptive Moving Average indicators are implemented in Lean 

#### Actual Behavior
Indicators aren't implemented

#### Potential Solution
Create a MesaAdaptiveMovingAverage and FollowingAdaptiveMovingAverage classes and put it into the QuantConnect.Indicators project. Also need add it to QCAlgorithm.Indicators.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Duplicated of https://github.com/QuantConnect/Lean/issues/83

**Comment by LouisSzeto** [comment]
There are 2 columns: (Time/Mesa Adaptive Moving Average/Following Adaptive Moving Average)
[spy_mama.csv](https://github.com/QuantConnect/Lean/files/10823165/spy_mama.csv)

**Comment by LouisSzeto** [comment]
[spy_hurst_exponent.csv](https://github.com/QuantConnect/Lean/files/13114565/spy_hurst_exponent.csv)
columns: "SPY close" "Mesa Adaptive Moving Average" "Following Adaptive Moving Average"

script:
```
import talib

qb = QuantBook()

spy = qb.AddEquity("SPY", Resolution.Daily).Symbol

history = qb.History([spy, qqq], datetime(1998, 1, 1), datetime(2023, 2, 23))

close = history.loc[spy].close

mama, fama = talib.MAMA(close)
mama = pd.concat([mama, fama], axis=1).dropna()
mama["spy close"] = close
mama = mama.iloc[:, [1, 2, 0]].dropna()
mama.to_csv("spy_mama.csv", header=False)
```
