### ISSUE TITLE
Update Futures Expiry functions and symbol properties

### ISSUE THREAD

**Issue by Jay-Jay-D** [QuantConnect/Lean#2991]
#### Expected Behavior

All futures must be modeled correctly.

#### Actual Behavior

For available futures, only 33 have an expiry function defined and 29 have properties defined in the [symbol-properties-database](https://github.com/QuantConnect/Lean/blob/master/Data/symbol-properties/symbol-properties-database.csv#L87).

#### Potential Solution

Define all future's expiry functions and properties. 

#### Reproducing the Problem

N/A.

#### System Information

N/A.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

**Comment by Jay-Jay-D** [comment]
The values for `ZT` in the [`symbol-properties-database.csv`](https://github.com/QuantConnect/Lean/blob/5db98c8f532d8c6aab2998aeaecf3e1644bb44fa/Data/symbol-properties/symbol-properties-database.csv#L93) should be updated to correctly model bond futures behavior.

**Comment by Martin-Molinero** [comment]
Believe we can close this one now. The [symbol-properties-database](https://github.com/QuantConnect/Lean/blob/master/Data/symbol-properties/symbol-properties-database.csv#L87) has 189 futures at the moment 🚀
