### ISSUE TITLE
Allow User Supplied History on QB Indicator Overload (make public)

### ISSUE THREAD

**Issue by JeffreyMargolis** [QuantConnect/Lean#2992]
QuantBook includes functionality to evaluate an Indicator against the History of a Symbol.
The specific scenario I am trying to enable is to evaluate an Indicator structure that operates on/combines data from multiple symbols. 

#### Expected Behavior

QuantBook should support evaluating / plotting of Indicator results with user supplied history queries.

#### Actual Behavior

Currently it is not possible to evaluate Indicator structures that depend on multiple symbols within the QuantBook framework.

#### Potential Solution

Only a subset of the Indicator methods that takes an indicator and target symbol are public, those methods that take  a history as a parameter are marked as private.
The two functions requested to be made public: 

    private PyObject Indicator(IndicatorBase<IndicatorDataPoint> indicator, IEnumerable<Slice> history, Func<IBaseData, decimal> selector = null) 
    private PyObject Indicator<T>(IndicatorBase<T> indicator, IEnumerable<Slice> history, Func<IBaseData, T> selector = null)

Alternate Solution would be to expose additional Indicator Methods that take a collection of Symbols 

for Example, For the family of exposed Indicator methods such as:

    public PyObject Indicator(IndicatorBase<IndicatorDataPoint> indicator, Symbol symbol, int period, Resolution? resolution = null, Func<IBaseData, decimal> selector = null)
        
add 

    public PyObject Indicator(IndicatorBase<IndicatorDataPoint> indicator, IEnumerable<Symbol> symbols, int period, Resolution? resolution = null, Func<IBaseData, decimal> selector = null)
        
#### Checklist

- [x] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by JeffreyMargolis** [comment]
Upon further investigation, believe that this is actually a larger feature request.
To make this work, a collection of indicators would need to be evaluated against a History, with results being collected from a (optionally different) designated Indicator. 

This could be accomplished either through a registration/broadcast model not too different to what is done in the the QCAlgorithm with RegisterIndicator, or more explicitly by evaluating a history against a collection of Identity Indicators paired to Symbols...

**Comment by jaredbroad** [comment]
- Make PyObject private indicator method public
 - Add example of updating the B() Beta indicator with 2 tickers say SPY and another SPY ETF (NOT SPY) where beta expected to be 1.
 -  Update Documentation with example.
