### ISSUE TITLE
Once-a-week or once-a-month rebalancing frequency in Framework Algorithm

### ISSUE THREAD

**Issue by fera0013** [QuantConnect/Lean#2999]
#### Expected Behavior
It should be possible to schedule rebalancing in the Algorithm Framework, such that the Update method of an AlphaModel class is triggered only once per week / month at a specified time. 

In the classical framework, this can be achieved by using 

```
self.Schedule.On(self.DateRules.MonthStart("SPY"), \
                 self.TimeRules.AfterMarketOpen("SPY"), \
                 self.RebalancingCode)
```

but this is not available in the Framework Algorithm.

#### Actual Behavior

The Update method in an AlphaModel is triggered each day, at a minimum.

**Comment by Martin-Molinero** [comment]
Hey @fera0013!
You could achieve something similar with the portfolio construction model 'rebalancing' argument, for example, https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/PortfolioRebalanceOnDateRulesRegressionAlgorithm.py#L49 with a date rule or even a custom function https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/PortfolioRebalanceOnCustomFuncRegressionAlgorithm.py#L50. Also this could be achieved at the selection model level, returning `Universe.Unchanged` when no change desired, for example, https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/UniverseUnchangedRegressionAlgorithm.py. There are other examples of both cases both, in GH and in QCs community forum. Hope this solves the issue, closing for now
