### ISSUE TITLE
[Feature] Create Bollinger Bands Indicator

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#3]
Create an "BollingerBand" indicator class and the associated "BB" helper method in the QCAlgorithm base class. See introduction to indicators - https://lean.quantconnect.com/docs#topic9.html

Add the associated tests to Tests project under /Indicators to confirm the Bollinger Bands match up with the data provided in Tests/TestData/spy_bollinger_bands.txt file.

**Comment by mourednik** [comment]
I'm working on this now. I will also create a StandardDeviation indicator to be used by the BollingerBand indicator.

**Comment by mchandschuh** [comment]
Wonderful! You'll be the first indicator contributor.

I couldn't agree more that making a StandardDeviation indicator is the way to go, and then using that in the BollingerBand indicator. Let me know if you have any questions about the design of the indicator system or anything else in Lean! Thanks!!

**Comment by mourednik** [comment]
Thanks. So far, everything looks very sensible. I'll let you know if there's anything questionable.

**Comment by mourednik** [comment]
@jaredbroad @mchandschuh 
There is a problem with the test data.

spy_bollinger_bands.txt is missing the initial 50 rows, assuming that the moving average is a 50 period SMA. We need those 50 rows to initialize the SMA so that it matches the CSV. Are you able to easily generate a new CSV from somewhere?

Also, I added the en-US date format so that it can parse the CSV dates. That fixed two other failing tests.

**Comment by mchandschuh** [comment]
b78398c updates the bollinger band data to be correct. The Bollinger Band (20, 2) uses a 20 period moving average and +- 2 standard deviations (also computed from 20 periods) from the mean for the upper and lower bands respectively.  This data is generated using the FreeStockCharts.com desktop silverlight application's 'Export Chart' feature.

Thanks for fixing those tests! They were passing in Travis but, I suppose we need to be more aware of globalization concerns.

**Comment by mourednik** [comment]
Thanks. Pull request submitted.

**Comment by jaredbroad** [comment]
Closed by commit #1d912765, +5 kudos to @mourednik
