### ISSUE TITLE
Security Current Day OHLC

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#3009]
#### Expected Behavior
Be able to access the security OHLC values of the current trading day.

#### Actual Behavior
We need to implement this manually in each algorithm.

#### Potential Solution
Implement a system that keeps track of the current trading day OHLC.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Duplicate of https://github.com/QuantConnect/Lean/issues/1608
