### ISSUE TITLE
Benchmarking Inside a running job.

### ISSUE THREAD

**Issue by Nucs** [QuantConnect/Lean#3012]
Greetings,

I'm asking if there is an way to solve the following scenario:
I train a `machinelearning` model via historical data I request during `QCAlgorithm.Initialize`.
After fitting the ML model, I need to perform optimization to two or more parameters which require me to iterate the historical data, perform trades based on ML's predictions with the given parameters and return the `Portfolio.Profit` as a score (or a benchmark).
Normally I would just run a small simulator just for that case.
But a need for more complex trading commands like stop-loss and take-profit that cancel each other or basically anything that is beyond plain market order is just way too complex.

I was wondering, is there a way to run a backtest over _n_ times during an algorithm initialization?

The only possible solution I came by is to run a separate engine that awaits new jobs and runs them one by one. 
This leads to creating extra threads just for that engine.
Imagine trying to run 8 engines simultaneously to fully take advantage of all cores.

Note: I'm running the Lean engine as a desktop application and not on `quantconnect.com`.

Thanks, Eli.

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Doggie52** [comment]
Hey Eli, I made a [batch launcher for Lean](https://github.com/Doggie52/Lean-Batch-Launcher/) a while ago, perhaps it could be of use to you?

**Comment by Nucs** [comment]
Ended up creating a custom set of classes/components (see [image](https://user-images.githubusercontent.com/649919/56925598-7e8a8c00-6ad8-11e9-83fd-32d8a86a273b.png)) that run a single-threaded run with the ability to fake data, e.g. a sinus.
If anybody needs it, let me know.
