### ISSUE TITLE
Enable calling Alpha Framework on schedule basis, and not only on tick data

### ISSUE THREAD

**Issue by erikbengtson** [QuantConnect/Lean#3024]
#### Expected Behavior
1.End of day event should be called and risk management model triggered. Rational: avoid low liquidity periods, and high spread costs, avoid overnight interest costs
2.RiskManagementModel should be called on endofday
#### Actual Behavior
1.standard OnEndOfDay Event is scheduled on a fixed time market close - 10 minutes
2.RiskManagementModel is called on data resolution, but not triggered on scheduled events

#### Potential Solution
1.Allow configuration of scheduled periods.
2.add a new OnScheduledEvent On risk management model class. We should be able to schedule events and this method should be called

#### Checklist
- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

This is a feature request, since alpha framework methods cannot be run on schedule

**Comment by erikbengtson** [comment]
workaround for point 2. Add to the Risk Model implementation this condition, and set target there

`                    
var marketClose = security.Exchange.Hours.GetNextMarketClose(algorithm.Time, security.IsExtendedMarketHours);

// define the time of day we want the event to fire before marketclose
var eventTime = marketClose.Subtract(ScheduledEvent.SecurityEndOfDayDelta);

// convert the event time into UTC
var eventUtcTime = eventTime.ConvertToUtc(security.Exchange.TimeZone);

if (algorithm.Time > eventUtcTime)
{
//set target here
}
`

**Comment by michaelsrew** [comment]
https://www.quantconnect.com/docs/algorithm-reference/scheduled-events


BeforeMarketClose(symbol, min) | self.TimeRules.BeforeMarketClose("SPY", 10) 					Trigger an event a few minutes before close for a specific symbol.

does not help?

**Comment by erikbengtson** [comment]
Yes it certainly helps for item 1.

However, the alpha framework, risk management model, is not aware of scheduled events.

The issue is that risk management model, is called on every tick and not on scheduled event.

As workaround, I keep a dictionary of events by symbol on the Algorithm class that is updated on schedule, and on risk management model, on tick basis, I check if the flag exists for that symbol.

**Comment by jaredbroad** [comment]
@erikbengtson inside your risk management model can't you use: `algorithm.Schedule(....)` to setup any scheduled events you need? This could be done inside the constructor or update by using the reference to the algorithm.

**Comment by erikbengtson** [comment]
Yes I can, but I want to update Portfolio Targets. I don't know how to do that on schedule basis... For the moment, I've been tracking at QCAlgorithm flags per symbol to qualify whether the risk model based on schedule should run or not. It works, but looks like a workaround.

**Comment by jaredbroad** [comment]
Lack of demand
