### ISSUE TITLE
Consolidator with custom start time

### ISSUE THREAD

**Issue by Doggie52** [QuantConnect/Lean#3027]
#### Background
Let's say you run a strategy on EURUSD, Oanda, daily bars. Each bar closes at midnight UTC, but you don't want to execute immediately since that time is when the spreads are highest. Let's say you'd like to execute at 1AM UTC instead (but still have the bar close at midnight). What are your options?

Firstly, you would have to build an execution model that only executes around 1AM UTC. That's not too difficult, but in order for this execution model to run, you need to increase the data resolution to hourly. You would also need to create a QuoteBarConsolidator to consolidate your hourly bars into daily ones.

What happens if you do that? Your daily bars will now start closing at 4AM or 5AM UTC instead! Why? Because all consolidators reference their times against the exchange timezone which (for some reason) is New York time for all Oanda forex pairs.

The only option I see to properly be able to execute at a different time than the bar close is to add a dummy security (not one of the ones you intend to trade) with a higher resolution. But because you're still using daily resolution for the securities you intend to trade, this means in a backtest they will execute on stale prices.

#### Expected Behavior
Quotebar and Tradebar consolidators allow for custom start times (down to the same resolution as the data resolution).

#### Potential Solution
A user built a [working prototype](https://www.quantconnect.com/forum/discussion/5244/daily-quotebar-consolidator-with-different-close-time/p1/comment-15294) but this operates on a timespan referenced on the exchange timezone. It should be possible to have the timespan reference UTC or another timezone.

#### Reproducing the Problem
~~I can try to produce a working example if necessary.~~
This is a feature request so this section is not needed.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by moconnell** [comment]
Co-sign on this functionality being useful. 

This issue looks similar to [#2456](https://github.com/QuantConnect/Lean/issues/2456)?

**Comment by Doggie52** [comment]
Hey, that issue is for python support for consolidators of custom data. This is for allowing any consolidator to start at any time in any language.

**Comment by Doggie52** [comment]
I've built this: https://github.com/Doggie52/Lean-Zoned-Time-Of-Day-Consolidator

Never PRed it because I didn't feel the code quality and elegance was up to scratch. Thoughts on what kind of work it requires?

**Comment by victorcomposes** [comment]
H,
Is there a way to have a start time with a four hour consolidator?

**Comment by Martin-Molinero** [comment]
Existing `FutureMarketOpenConsolidatorRegressionAlgorithm` is an example of a consolidator using a custom start time
