### ISSUE TITLE
Internationalisation: Use culture invariant anywhere there is a conversion

### ISSUE THREAD

**Issue by erikbengtson** [QuantConnect/Lean#3045]
#### Expected Behavior
Lean should be able to run on non English based computers

#### Actual Behavior
Parsing prices is failing because it takes machine culture
#### Potential Solution
Use CultureInfo.InvariantCulture everywhere there is a conversion such as Convert.ToDecimal
e.g. in class OandaRestApiV20.OnPricingDataReceived change code to:
Convert.ToDecimal(data.Bids.Last().Price, CultureInfo.InvariantCulture)
Convert.ToDecimal(data.Asks.Last().Price, CultureInfo.InvariantCulture)

#### Reproducing the Problem
Change machine to other language/location

#### System Information
macOS french

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Merged in QuantConnect#3045
