### ISSUE TITLE
Python Version of StandardDeviationExecutionModel Issue with Forex

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#3075]
#### Expected Behavior
`StandardDeviationExecutionModel` can be used with any security type.

#### Actual Behavior
```Runtime Error: AttributeError : 'Pandas' object has no attribute 'volume' AttributeError : 'Pandas' object has no attribute 'volume'```
#### Reproducing the Problem
Set up a Python algorithm with Forex universe and `StandardDeviationExecutionModel`.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
** Or some way to signify the "requirements" of a module; to solve this more generically.
