### ISSUE TITLE
Performance degradation after classic and framework algorithm merge

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#3076]
#### Expected Behavior

- Lean runs as fast as possible
#### Actual Behavior

- After https://github.com/QuantConnect/Lean/pull/3055 was merged there was a performance impact on previous non framework algorithms, the impact was expected as framework algorithms were slower than classic versions.
The objective of this issue is to find the root causes of this difference and improve their performance.
![imagen](https://user-images.githubusercontent.com/18473240/55995262-6e764e00-5c8a-11e9-9b64-1636b49c0fc0.png)

#### Potential Solution

- Measure, review, refactor, improve.
#### Reproducing the Problem

- Executing Lean benchmark algorithms Py and C#
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Addressed in #3077, #3085, #3111, #3112
 
![image](https://user-images.githubusercontent.com/2243225/56756260-3c62f280-6746-11e9-92ba-1430b6213175.png)
