### ISSUE TITLE
Extend Alpaca to Support Margin Trading

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#3081]
#### Expected Behavior
Alpaca now supports margin, LEAN should allow it.

#### Actual Behavior
Locked in cash accounts only.
 
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by pmannle** [comment]
This would be awesome.... any ETA?

**Comment by vguruv** [comment]
@jaredbroad  could you outline the changes needed at a high level? maybe I/someone can implement.
