### ISSUE TITLE
Enable Greeks and Implied Vol. from Options History Request

### ISSUE THREAD

**Issue by simonsonjack** [QuantConnect/Lean#3083]
#### Expected Behavior
Enable accessing Greeks and Implied Volatility in a historical data request for options data. This is a handy feature and will help with calculation of things such as IV Rank without needing to implement custom functions using Rolling Windows.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by mcguirebc** [comment]
Would love to see this feature!

**Comment by JakeTheSnake3p0** [comment]
I'll second that. It would answer [my question](https://www.quantconnect.com/forum/discussion/7450/implied-volatility-from-getoptionhistory/p1).

**Comment by jgerardsimcock** [comment]
Is there a way to contribute to this?

**Comment by ikamanu** [comment]
Any update on this?

**Comment by petegordon** [comment]
I was looking into this a bit. Looks like Resesarch OptionHistory.cs has slice referenced as a private variable; curious if it was public would it be able to be used for OptionPriceModel Evaluate.  

https://github.com/QuantConnect/Lean/blob/43e9cad2d6407d4d2d3c1a5fb9788e44a97a8a7d/Research/OptionHistory.cs#L29

https://github.com/QuantConnect/Lean/blob/43e9cad2d6407d4d2d3c1a5fb9788e44a97a8a7d/Common/Securities/Option/IOptionPriceModel.cs#L35

That's as far as I have gotten.

I have talked to others that are using Backtesting Options IDE to gather pricing data; saving it to ObjectStore and then referencing it from Research notebook to get around the fact that Option Pricing object model is not available from Research.  Seems to be a descrepency between the Options object model being worked from backtest versus research.

Let me know if anyone makes any more progress. Thanks!

**Comment by ikamanu** [comment]
This is very promising.  Thank for sharing this.

**Comment by Kevin-Chen0** [comment]
Is there an update on this?

**Comment by petegordon** [comment]
I have no update; I haven’t touched QuantConnect  code since running into this issue.

**Comment by jaredbroad** [comment]
Hi all, no update yet sorry. We're currently working on daily options and then will explore this again on a much smaller dataset which should make it an easier issue to start working on and to verify against third-party greek sources which are all generally daily.

We appreciate it's an important feature to make options easier and should start work on it this year. The best way to support us is volunteering time in our slack/discord/community or sponsoring [LEAN](https://github.com/sponsors/QuantConnect).

**Comment by RyanTau** [comment]
Been around 11 months, has there been any progress made with this?

**Comment by dryqin** [comment]
IV and IVR basically indicate if a contract is cheap or expensive. A platform is basically useless for trading options without this indication obviously.

**Comment by ikamanu** [comment]
I don't think you understand, @drywin .  You can calculate IV and IVR on the platform today. Quantconnect supports this.  This ticket is just about making it _easier_ to do so.

**Comment by jaredbroad** [comment]
Dynamic history request option greeks should be possible relatively easily now - 

 - Recent work making option greeks and IV work in a classic AddOption request should be portable and work on history requests with some review.
 - Reuse the fictional security object created for the history request (and the IVolatilityModel on the OptionSecurity object)
 - Update SubscriptionDataReaderHistoryProvider L 108 to create an Option instead of a Security. 
 - Potentially do this via the SecurityService

**Comment by ikamanu** [comment]
Excited to see activity around this! 🤞

**Comment by jaredbroad** [comment]
Small update for everyone; we worked January and February creating the option greeks as technical indicators and then doing studies to compare the outputs with popular third party sources. We were able to perfect our open-source variants and will use those technical indicators to pre-process the historical data greeks. 

The pre-processing step is next on the cards; then loading it into LEAN for things like history calls or easily using it in universe filters.

We're in a maintenance sprint at the moment catching up on bugs, libraries, and small polish features but will get back to this superhero community project later in April.

**Comment by ikamanu** [comment]
This is great news. Thanks for the update!

**Comment by Martin-Molinero** [comment]
Equity and index options can retrieve daily greeks and implied vol history, creating new issue to track this functionality for FOPs https://github.com/QuantConnect/Lean/issues/8438 and separate issue for intra day support https://github.com/QuantConnect/Lean/issues/8440

**Comment by jaredbroad** [comment]
Reopening to fix the expiry date / 0DTE greeks issue.

**Comment by Martin-Molinero** [comment]
> Reopening to fix the expiry date / 0DTE greeks issue.

Fix has been shipped
