### ISSUE TITLE
Extend C# API SDK to Return Insights for Deployment

### ISSUE THREAD

**Issue by Doggie52** [QuantConnect/Lean#3099]
#### Expected Behavior
API SDK provides generated insights of the algorithm, either as part of the `ReadLiveAlgorithm` function or in a separate function.

#### Actual Behavior
API SDK doesn't offer this functionality currently.

Insights are served by the web API. 
https://www.quantconnect.com/docs/v2/cloud-platform/api-reference/live-management/read-live-algorithm/live-algorithm-statistics

#### Background
Outputting the current generated insights is useful when restarting the algorithm and resetting it to its previous state.

#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Doggie52** [comment]
One can imagine a situation where the algorithm calls the API on a restart and populates/"warms up" its insights with the ones it had before.

**Comment by jaredbroad** [comment]
Waiting on YAML https://github.com/QuantConnect/Documentation/issues/1141

**Comment by Martin-Molinero** [comment]
This has been implemented and documented see https://www.quantconnect.com/docs/v2/cloud-platform/api-reference

**Comment by Martin-Molinero** [comment]
Re opening because we are missing `backtests/insights/read` endpoint in the C# API client & in the documentation
