### ISSUE TITLE
huge limitation in LEAN must be fixed

### ISSUE THREAD

**Issue by RogerBolin** [QuantConnect/Lean#3127]
LEAN doesnt allow you to buy a contract of 1000 EURUSD, and then later buy another contract of 1000 EURUSD, and then later only liquidate the second contract. LEAN forces you to liquidate everything first, even though you want to keep the first contract. But on your brokers platform you can have multiple long and short contracts in any given asset. 

This fundamental problem also prevents "covering" operations. LEAN doesnt allow you to simultaneously have a long and short contract in any asset, even though covering is a very regular operation in the hedge fund industry and must be allowed by any serious trading platform. 

Quant Connect must get away from this "holding" ideology, because it is very limiting, and instead view trading as individual contracts. One should be able to have multiple different long and short contracts in any asset. There is a huge room for improvement here.

**Comment by jaredbroad** [comment]
Hi @RogerBolin; appreciate the feedback and made an issue for you here. https://github.com/QuantConnect/Lean/issues/3130

**Comment by RogerBolin** [comment]
Thank you very much Jared. You are truly the best.

Skickat från Outlook<http://aka.ms/weboutlook>
________________________________
Från: Jared <notifications@github.com>
Skickat: den 25 april 2019 18:58
Till: QuantConnect/Lean
Kopia: RogerBolin; Mention
Ämne: Re: [QuantConnect/Lean] huge limitation in LEAN must be fixed (#3127)


Hi @RogerBolin<https://github.com/RogerBolin>; appreciate the feedback and made an issue for you here. #3130<https://github.com/QuantConnect/Lean/issues/3130>
