### ISSUE TITLE
Hedging of Assets (long short simultaneous holdings)

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#3130]
#### Expected Behavior
Able to go long and short on the same asset and manage positions with order tickets. 

#### Actual Behavior
An averaged portfolio with no individual ticket management.

#### Potential Solution
Forex Only Portfolio / Holdings classes which support the separation of the trade ticket holdings

Ref: #3127 

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by DarkoAlexander** [comment]
One should be able to have multiple long and short contracts/positions in any asset, just like you can have multiple positions on your brokers platform. This is a great proposal by Jared.

**Comment by bestvcboy** [comment]
good

**Comment by guzuomuse** [comment]
hedging support should be on the top priority!

**Comment by jaredbroad** [comment]
Too niche (Fx, some brokerages) for widespread adoption and don't have bandwidth to execute

**Comment by DarkoAlexander** [comment]
Terrible decision to close this issue, Jared. It means that you deprive your customers of the most powerful trading technique, which is covering.
