### ISSUE TITLE
Add MT4 connection to brokers

### ISSUE THREAD

**Issue by Puhtooie** [QuantConnect/Lean#3142]
Not actually an issue, BUT I found this library that creates a connection to MT4 and it looks very cool. 
[https://github.com/darwinex/dwx-zeromq-connector](Darwinex)

Right now, it's main language for the api is in Python, but any language that supports ZeroMQ can utilize it. Personally, I'm thinking layer a graphQL api, or something similar over it, which would effectively open it up to other code. 
Currently there is no support for historical data to do back trades with. There's a couple things nested in their files that look like they could be used to create CSV files to import, so if you know mql4 that might be useful.
They support Live trading, and live data feeds; but, although it technically works out of the box there definitely is still work to be done on it.

This community seems very passionate and active, so I thought I'd put this here. I'm not affiliated with Darinex or ZeroMQ in any way, just seems like a good idea.

There is also the following libraries:
https://github.com/AustenConrad/mql4zmq
https://github.com/dingmaotu/mql-zmq
 https://github.com/krisn/lws2mql

The first two also use ZeroMQ, the last one does not. I have not explored these in much depth. There are not many commits, and some of them are rather old, but they may be good reference points at the very least.

**Comment by jaredbroad** [comment]
Thanks @Puhtooie! We'll review the connection.

**Comment by el-buku** [comment]
has this been integrated? couldnt find anything
