### ISSUE TITLE
Build Alpha Stream Fee / Slippage / Margin Interest Models

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#3145]
#### Expected Behavior
Models to accurately represent institutional ability to execute. 

#### Actual Behavior
No appropriate models

#### Potential Solution
Build a series of models which people can apply to their strategies to reflect realistic transaction costs.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by simonsonjack** [comment]
Updating and expanding on this in issue #3346
