### ISSUE TITLE
The problem with open function !!!

### ISSUE THREAD

**Issue by jolyjoly** [QuantConnect/Lean#3153]
in my algorithm there is this code :
with open('portfolio_val/{}-{}.p'.format(timestamp, args.mode), 'wb') as fp:
    pickle.dump(portfolio_value, fp)
but quantconnect say some thing like : "sorry but open is not whitelisted within quantconnect, please remove it from the code" !!!!!
what is the equivalent of that in quantconnect plz ?

**Comment by jaredbroad** [comment]
Hey JolyJoly, please use support@quantconnect.com for website questions. This is a different project.
