### ISSUE TITLE
Infinitely Polling Custom Data URL When Return Null

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#3156]
#### Expected Behavior
Should ping custom data URL's on the resolution step with max 30min, and when no data wait for the next step to poll again.

#### Actual Behavior
Returning null triggered immediate re-polling, causing LEAN to hit rate limit warnings for custom data APIs. 

#### Potential Solution
Review custom data enumerator stack; perhaps there should be another return option:
 `null` - immediately retry?  `BaseData.None` - wait for next resolution step?  

#### Reproducing the Problem
Return null from USEnergyInformation.cs instead of new BaseDataCollection. 

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by erikbengtson** [comment]
Hi, In TextSubscriptionDataSourceReader.Read I added the following the check, it fixes my issue. That means, if the current BaseData implementation does not return a value, it skips and goes to the next enumerator. does this fix makes sense? at least I've been using this fix for a while. 


`                        if(instance == null)
                        {
                            yield break;
                        }

                        if (instance != null && instance.EndTime != default(DateTime))
                        {`
