### ISSUE TITLE
Implement NullMarginModel for Live Trading

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#3157]
#### Expected Behavior
Live trading should lean on the brokerage margin limitations and not impose them in LEAN.

#### Actual Behavior
LEAN models restrict brokerage margin.

#### Potential Solution
1) Improve option margin models
2) and Implement null margin model to disable restrictions for live trading.

#### Reproducing the Problem
Live trading straddles.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by bradhallett** [comment]
Are there any updates on this request? Implementing a NullMarginModel will open up a much wider array of options strategies that can be deployed via QuantConnect. Thank you!

**Comment by briancmcguire** [comment]
This would be very valuable to me as well.

**Comment by kbsaravana** [comment]
+1

**Comment by itsjacobhere** [comment]
Has this issue been resolved? Is there a way to turn off margin limitations for options?

**Comment by mattmcwaters** [comment]
Very interested in this!

**Comment by jaredbroad** [comment]
- Confirm if same or different to ConstantBuyingPowerModel
 - If same; then add a shim NullMarginModel with default 0.001 (tiny incase account currency BTC)
 - Add an example algorithm using it.
 - https://github.com/QuantConnect/Lean/blob/master/Common/Securities/ConstantBuyingPowerModel.cs
