### ISSUE TITLE
Remove QCAlgorithm Framework Cash Account Throw L86

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#3165]
#### Expected Behavior
Able to use Alpaca+Algorithm Framework.

#### Actual Behavior
```
Non null IExecutionModel and IPortfolioConstructionModel are currently unsuitable for Cash Modeled brokerages (e.g. GDAX) and may result in unexpected trades. To prevent possible user error we've restricted them to Margin trading.
```
The root reason for this was that crypto trading required manual coin management and the automated methods were not sufficient. However, this doesn't apply to equity cash accounts. They should be able to place trades easily as they are all tied to the USD cash entry.

#### Potential Solution
Review the trigger for this exception and place exception for equity brokerages.

#### Reproducing the Problem
Alpaca brokerage model + framework.
```csharp

namespace QuantConnect.Algorithm.CSharp {

    public class BasicTemplateFrameworkAlgorithm : QCAlgorithm
    {
        public override void Initialize()
        {
            UniverseSettings.Resolution = Resolution.Minute;

            SetStartDate(2013, 10, 07);
            SetEndDate(2013, 10, 11);

            SetBrokerageModel(BrokerageName.Alpaca, AccountType.Cash);

            SetUniverseSelection(new ManualUniverseSelectionModel(QuantConnect.Symbol.Create("SPY", SecurityType.Equity, Market.USA)));
            SetAlpha(new ConstantAlphaModel(InsightType.Price, InsightDirection.Up, TimeSpan.FromMinutes(20), 0.025, null));
            SetPortfolioConstruction(new EqualWeightingPortfolioConstructionModel());
        }
    }
}
```
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by multidis** [comment]
Now that Alpaca includes short selling and margin, perhaps Alpaca Brokerage can be modified accordingly to work with the Algorithm Framework?

**Comment by jzderadicka** [comment]
Hi All,

I also would like to see changes to support Alpaca+Algorithm Framework.  I spent a fair amount of time building out and back testing a framework to deploy with Alpaca, unfortunately, I was immediately met with runtime errors.  If there is anything that can be done assist with this implementation, please advise.  I would like to deploy asap.

With thanks,

Joey

**Comment by multidis** [comment]
For those tracking the issue: Alpaca brokerage implementation now works in margin mode. See [AlpacaBrokerageModel.cs history](https://github.com/QuantConnect/Lean/commits/master/Common/Brokerages/AlpacaBrokerageModel.cs) starting from this [Dec 2019 commit](https://github.com/QuantConnect/Lean/commit/3d568f2da07c766c1ac203096785570dbe26b4e2#diff-92d53dc0d2865e5f5307bce8ee5b3cc4). Our initial paper trading tests proceeded error-free.

Thanks to @StefanoRaggi for the modifications and debugging!
