### ISSUE TITLE
SubscriptionCollection Memory Leak

### ISSUE THREAD

**Issue by Nucs** [QuantConnect/Lean#3166]
#### Expected Behavior
Upon removing `Subscription` from `SubscriptionCollection`, it should be released from memory by `GC`.

#### Actual Behavior
`SubscriptionCollection` retains removed Subscription (via `TryRemove`) in `_subscriptionsByTickType` and prevents from clearing from memory.

Note: I'm running a local version with many modifications - This problem might be the case in my local version only. Nevertheless I've checked the related files in this post and they are identical to master branch.

#### Reproducing the Problem
I ran multiple `Engine`s in parallel for many iterations. Some are stopped via QCAlgorithm.Quit() and some run to completion. Noticed ticks that was left in the memory, leading me to this (dotmemory):
![image](https://user-images.githubusercontent.com/649919/57146242-8a729880-6dcd-11e9-8f26-7ab1201da5c8.png).

#### Potential Solution
Ensure they are removed from _subscriptionsByTickType when they are from SubscriptionCollection.
``` C#
 public bool TryRemove(SubscriptionDataConfig configuration, out Subscription subscription)
        {
            if (_subscriptions.TryRemove(configuration, out subscription)) {
                **_subscriptionsByTickType.Remove(subscription);**
                UpdateFillForwardResolution(FillForwardResolutionOperation.AfterRemove, configuration);
                _sortingSubscriptionRequired = true;
                return true;
            }
            return false;
        }
```
Edit:
It is not enough, `SubscribtionSyncornizer` that uses `SubscriptionCollection` iterator throws a collection modified exception.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hi!
At `TryRemove`, once the `Subscription` is removed it sets `_sortingSubscriptionRequired` to true so the next time the `SubscriptionCollection` is enumerated (on each time loop) it will update `_subscriptionsByTickType`, so this shouldn't be causing the issue. 
What could be happening in this case is that once the algorithm stops, the engine removes all subscriptions (https://github.com/QuantConnect/Lean/blob/master/Engine/Engine.cs#L449) but the `SubscriptionCollection` won't be enumerated again, so they could still be in `_subscriptionsByTickType`, could test adding `SubscriptionCollection.RemoveAll()` and call it from `DataManager.RemoveAllSubscriptions()`

**Comment by Martin-Molinero** [comment]
Closing due to no user response and since its not an issue related with current `master` usage.
