### ISSUE TITLE
Coarse universe selection fails

### ISSUE THREAD

**Issue by multidis** [QuantConnect/Lean#3167]
#### Expected Behavior
Algorithm Framework coarse universe selection should work as described in the docs and example algorithms.

#### Actual Behavior
Empty universe is returned at the coarse filtering stage in most algorithms.

#### Potential Solution
`HasFundamentalData` bool-filter appears to cause the problem.

#### Reproducing the Problem
Run [StatelessCoarseUniverseSelectionBenchmark.py](https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/Benchmarks/StatelessCoarseUniverseSelectionBenchmark.py)

#### System Information
QC Lab Terminal, LEAN Engine v2.4.0.0.5642

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Thanks @multidis - its a cloud issue not related to LEAN.
