### ISSUE TITLE
Backtesting with Backtesting brokerage and IQFeed data feed

### ISSUE THREAD

**Issue by aytacasan** [QuantConnect/Lean#3169]
#### Expected Behavior
Want to use Backtesting brokerage and IQFeed data feed on my local machine. Here is what i expected generally;

1. Start IQFeed client if not started.
2. Download security universe if not in cache.
3. Request required security history from IQFeed.
4. Process response and save data to data folder.
5. Run strategy with FileSystemDataFeed on Backtesting brokerage.

#### Actual Behavior
Here is results of above steps;

1. IQFeed client starting if not started.
2. Downloading security universe if not in cache and loading symbols.
3. Requesting required security history from IQFeed with GetData method.
4. Process response and don't save data to data folder. My problem starting from here.
5. Because of previous step fails, engine throwing exceptions can not find data.

#### Potential Solution
Maybe i don't understand or misunderstand Lean's backtesting logic. Because of that can't configure launcher correctly.

#### Reproducing the Problem
I changed four parts in Lean's config file;

1. "environment": "backtesting-iqfeed"
2. "algorithm-type-name": "BasicTemplateAlgorithm"
3. "iqfeed-username": "private content",
    "iqfeed-password": "private content",
    "iqfeed-productName": "private content",
    "iqfeed-version": "1.0",
4. "backtesting-iqfeed": {
      "live-mode": false,
      "setup-handler": "QuantConnect.Lean.Engine.Setup.ConsoleSetupHandler",
      "result-handler": "QuantConnect.Lean.Engine.Results.BacktestingResultHandler",
      "data-feed-handler": "QuantConnect.Lean.Engine.DataFeeds.FileSystemDataFeed",
      "data-queue-handler": "QuantConnect.ToolBox.IQFeed.IQFeedDataQueueHandler",
      "real-time-handler": "QuantConnect.Lean.Engine.RealTime.BacktestingRealTimeHandler",
      "history-provider": "QuantConnect.ToolBox.IQFeed.IQFeedDataQueueHandler",
      "transaction-handler": "QuantConnect.Lean.Engine.TransactionHandlers.BacktestingTransactionHandler"
    }

And in strategy i only changed start and end dates;

1. SetStartDate(2019, 05, 01);
2. SetEndDate(2019, 05, 03);

I don't do any other changes, using exactly same codes from github.

#### System Information
Using Visual Studio 2019 Version 16.1.0 Preview 2.0
OS is Windows 10 with regional/language settings compatible to Turkey/Turkish.

#### Checklist
- [*] I have completely filled out this template
- [*] I have confirmed that this issue exists on the current `master` branch
- [*] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [*] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/3264
