### ISSUE TITLE
Add Algorithm execution thread

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#3177]
#### Expected Behavior

- `Algorithm` code is executed always by the same thread. This is required to allow functional debugging in python, specifically adding breapoints during a debugging session, why? Because existing debugging python tools set new breakpoints in a per thread fashion, this being a limitation of the underlying python debugger.
#### Actual Behavior

- Currently `Lean` uses `Tasks` to execute algorithm code, in consequence the thread executing the code changes during the life of the process.
#### Potential Solution

- Add a worker thread that will execute `Algorithm` code
#### Reproducing the Problem

N/A
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Doggie52** [comment]
Is there any potential performance impact from keeping all the `Algorithm` code in one thread? Do we lose some multi-threading performance boost?

**Comment by Martin-Molinero** [comment]
No, there shouldn't be any performance impact. Before we sequentially used 1 `Task` (any thread from the pool), now we will use the same thread instance.
