### ISSUE TITLE
Unrealized Profit incorrect after restart of algorithm

### ISSUE THREAD

**Issue by ebengtso** [QuantConnect/Lean#3186]
#### Expected Behavior
Unrealized Profit has correct value or raise of an error

#### Actual Behavior
Unrealized profit value is way above the correct value
WTICOUSD UnrealizedProfit 503.8380 USD <== wrong, correct 76,98 EUR

#### Reproducing the Problem

- Create positions
- Shutdown algo
- Restart algorithm before market opens
- Print the UnrealizedProfit value

#### System Information

Logs:
20190512 23:05:15.442 Trace:: BrokerageSetupHandler.Setup(): Has existing holding: WTICOUSD: 207 @ $61.260 - Market: $61.713 - Conversion: 
20190512 23:05:15.446 Trace:: BrokerageSetupHandler.Setup(): Has existing holding: BCOUSD: 198 @ $69.815 - Market: $71.126 - Conversion:

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by ebengtso** [comment]
Another example of error

20190519 23:32:30.542 Trace:: BrokerageSetupHandler.Setup(): Has existing holding: HK33HKD: 5 @ $27778.4 - Market: $27825.6 - Conversion: 

20190519 23:32:44.174 Trace:: Log: MFERiskManagementModel HK33HKD UnrealizedProfit 1342.4889071309207113202713018 MFE 500.0 conversion rate 0.1274676136660577963653884639, current price 29887.8, avg price 27778.4

How come 27823.1 (correct current price) becomes 29887.8 (current price in algo)?

**Comment by ebengtso** [comment]
More details, I think I understood the cause of this issue. UnrealizedProfit is updated with past prices when I request to warm up, rather than relying on current price.

See more detail below, some some explanation: at the beginning the price is correct, then warm up happens, this time security price is incorrect (reflects warm up data), then the price is correct again, after warm up.

Since my RiskManagementModel is called for all these QuoteBar, the code is executed with warmup data.
 
20190520 01:31:56.434 Trace:: Log: MFERiskManagementModel HK33HKD UnrealizedProfit 30.064728340974785119997757893 MFE 500.0 conversion rate 0.1273929166990456996610074487, current price 27825.6, avg price 27778.4, last data time 5/20/2019 1:31:52 AM
...
20190520 01:33:00.065 Trace:: Log: MFERiskManagementModel HK33HKD UnrealizedProfit 28.473096745467713610331338938 MFE 500.0 conversion rate 0.1273964060199897700685965948, current price 27804.3, avg price 27778.4, last data time 5/17/2019 11:44:00 PM
...
20190520 01:35:00.022 Trace:: Log: MFERiskManagementModel HK33HKD UnrealizedProfit 28.473096745467713610331338938 MFE 500.0 conversion rate 0.1273964060199897700685965948, current price 27804.3, avg price 27778.4, last data time 5/17/2019 11:44:00 PM

**Comment by jaredbroad** [comment]
Not sure this is a bug. WarmUp should reply history so is doing as expected,
If your code logic relies on it you should use the algo.IsWarmingUp flag to wait for steady state

**Comment by ebengtso** [comment]
Thanks, I already implemented the suggestion. Why alpha risk management model is called during warm up? That’s the root cause of my issue.
