### ISSUE TITLE
Add `TensorFlow 2.0` Python Library to Foundation

### ISSUE THREAD

**Issue by simonsonjack** [QuantConnect/Lean#3189]
Add [TensorFlow 2](https://www.tensorflow.org):
`pip install tensorflow==2.1.0`

Add Tensorflow [Model Optimizatoin](https://github.com/tensorflow/model-optimization)

Add [Cvxpylayers](https://github.com/cvxgrp/cvxpylayers) (previously in #3982)

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jcandan** [comment]
Any update on this?

**Comment by jaredbroad** [comment]
@jcandan we'd prefer to not make breaking changes to users algorithms; if you could find a way we could install both and optionally use 2.0 we'll install it into the lean-foundation.

**Comment by LBrummer** [comment]
Is there any update on this, @jaredbroad ?

Users with tensorflow 1 could use

```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

```
if they want to continue using tensorflow 1 (see https://www.tensorflow.org/guide/migrate for some caveats).

**Comment by babagi** [comment]
Appreciate if you can prioritise this issue. TF1 is too slow and training timeout after 30min.

**Comment by LEChaney** [comment]
Update on this? TF1 is now quite outdated and TF2 has massive usability improvements. Not to mention the TF docs don't reflect TF1 at all anymore, so this could be quite confusing for new users.

**Comment by Natsu-Dragneel-Aka** [comment]
Hi Team am getting below error while running LSTM in Quantconnect, Seems like its related to tf2, can anyone help with that.

EXCEPTION:WARNING:tensorflow:OMP_NUM_THREADS is no longer used by the default Keras config. To configure the number of threads, use tf.config.threading APIs.,2020-12-02 13:18:39.993700: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations: SSE4.1 SSE4.2 AVX AVX2 FMA, To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.,2020-12-02 13:18:40.024441: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3999980000 Hz, 2020-12-02 13:18:40.024529: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f51ab7ca6f0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:,2020-12-02 13:18:40.024573: I tensorflow/compiler/xla/service/service.cc:176] StreamExecutor device (0): Host, Default Version, 2020-12-02 13:18:40.025017: I tensorflow/c

**Comment by LuCeHe** [comment]
Hi, I'd like to be able to use tf2 as well. Tf2 opens many more possibilities than tf1.

**Comment by 94Sip** [comment]
What is the status of TensorFlow 2.4

**Comment by lilith** [comment]
None of the new research is based on TF 1.x. This is a huge missed opportunity.

**Comment by ajaye2** [comment]
Any update on this?

**Comment by 94Sip** [comment]
I'm assuming at this point that QC does not want to support traders who want/need to build deep learning models for trading.

**Comment by jmerle** [comment]
The CLI supports TensorFlow 2+ for local projects using its [custom libraries](https://www.lean.io/docs/lean-cli/tutorials/custom-libraries) feature. After running `lean library add <project name> tensorflow` you can use the latest version of TensorFlow in local backtests, local research, local optimization and local live trading on the given project.

Using the CLI to transfer locally trained models to the cloud is not possible at the moment.
