### ISSUE TITLE
Failed when debugging

### ISSUE THREAD

**Issue by franklili3** [QuantConnect/Lean#3204]
#### Expected Behavior
complete debugging

#### Actual Behavior
Newtonsoft.Json.JsonReaderException:“Invalid character after parsing property name. Expected ':' but got: ". Path '', line 5, position 0.” when parsing the config.cs 
" return JObject.Parse(File.ReadAllText(ConfigurationFileName));"

#### Reproducing the Problem
After building, click debug, start debugging.

#### System Information
windows 7 64bits

#### Checklist

- [ ] I have completely filled out this template
- [ ] I have confirmed that this issue exists on the current `master` branch
- [ ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
This is a bug in your configuration file. For individual 1-1 debugging please post to the LEAN user group:
https://www.quantconnect.com/forum/discussions/1/lean
