### ISSUE TITLE
Helpers For Options Trading

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#3207]
#### Expected Behavior
Lean provides a series of helpers for options trading.

#### Actual Behavior
Lean users need to handle various options calculations and logic.
For instance, if the algorithm wants to track an option contract greeks and implied volatility, it needs to look for the latest contract in `QCAlgorithm.CurrentSlice.OptionChains`. If the algorithm needs to close a combo order (buy one call and one put) at 30%, it needs to keep track of all the legs and compute weighted means.

#### Potential Solution
Implement helpers.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Closing as https://github.com/QuantConnect/Lean/issues/5067 is the right solution. General "helpers" will just mess up the API.
