### ISSUE TITLE
Backtest with weekly and/or monthly data?

### ISSUE THREAD

**Issue by aytacasan** [QuantConnect/Lean#3208]
#### Expected Behavior
Want to call AddEquity method with weekly and/or monthly resolution parameter.

#### Actual Behavior
There is no weekly and/or monthly resolution support with AddEquity method.

#### Potential Solution
Want to backtest my strategy with weekly and/or monthly data. I'm sure others needed same thing. But when i search issues i can not see anything about this. If there is a way Quant Connect can support this resolutions too. Or provide data consolidators for weekly and monthly time frames. Maybe i can write myself but i can't figured out how can i handle holidays, weekends etc. Could you please help me about that?

#### Checklist
- [*] I have completely filled out this template
- [*] I have confirmed that this issue exists on the current `master` branch
- [*] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Doggie52** [comment]
Hey, this is possible already thanks to #3022 but might not be documented yet, not sure.

**Comment by jaredbroad** [comment]
Thank you for the issue @aytacasan - at this time we do not have plans to support things which can be implemented with a consolidator (e.g. issue #3022). The consolidation+resolution system already covers every possible combination and it would be significant reengineering to support edge cases.
