### ISSUE TITLE
Improve EmaCrossUniverseSelectionAlgorithm example.

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#3212]
#### Expected Behavior
`EmaCrossUniverseSelectionAlgorithm` includes History Request calls to warm up the indicators.

#### Actual Behavior
`EmaCrossUniverseSelectionAlgorithm` does not warm up the indicators.

#### Potential Solution
Implement historical data requests in `EmaCrossUniverseSelectionAlgorithm`. This implementation needs to be smart because one history request call per security cause time out in live mode.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
I have done some work on this issue. Here is what I got:
https://github.com/QuantConnect/Lean/compare/master...AlexCatarino:feature-3212-ema-cross-universe-selection
Maybe this should be solved at cloud level (cc @StefanoRaggi)

**Comment by jaredbroad** [comment]
Derek made a decent stab at it; https://github.com/QuantConnect/Lean/pull/4831 closing as more a documentation issue.
