### ISSUE TITLE
Dynamic Option Universes

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#3224]
#### Expected Behavior
Ability to select stocks by an unknown universe; and then further add option universes ontop of that.

#### Actual Behavior
Option stocks need to be selected at initialization time.

#### Potential Solution
Review use of Add/Remove universes to ensure cleans up Option universes+subscriptions properly.

#### Reproducing the Problem
Memory leaks deploy dynamic-stocks, option universes,

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues) 
- [x] I have provided detailed steps to reproduce the issue

**Comment by DerekMelchin** [comment]
Partially solved by https://github.com/QuantConnect/Lean/pull/4804

**Comment by jaredbroad** [comment]
Not worth adding support IMHO with the OptionChainProvider and the AddChainedOptionUniverse -- we have 99% coverage of how people would want to use option universes.
