### ISSUE TITLE
Implements Download Helper for Cvs to Pandas DataFrame

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#3227]
#### Expected Behavior
Be able to fetch a remote csv file and convert it to pandas DataFrame with a single method.

#### Actual Behavior
Not implemented. Python algorithms need to fetch the data with QCAlgorithm.Download method and manipulate the string. It has been done with `pandas.read_csv` method. 

#### Potential Solution
Write a wrapper around `pandas.read_csv` or manipulate the string and create a pandas DataFrame.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by sahilseth** [comment]
Is there a work around for this?

**Comment by jaredbroad** [comment]
Closing as a single line to do with CSV and can't assume the format of Downloads. The edge cases of download formats then become extreme to support. 

```
import pandas as pd
df = pd.read_csv(io.StringIO(self.Download( ... )))
```
