### ISSUE TITLE
Add pyramid-arima Library

### ISSUE THREAD

**Issue by simonsonjack** [QuantConnect/Lean#3234]
#### Expected Behavior

Adds pyramid-arime library to supported Python libraries. Library's main functionality is to bring R's _auto.arima_ function into Python.
Available via PyPi
```
pip install pyramid-arima
```
#### Checklist

- [x] I have completely filled out this template
- [ ] I have confirmed that this issue exists on the current `master` branch
- [ ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

**Comment by JakeTheSnake3p0** [comment]
Thank you for including these libraries. I've tried using auto_arima in my notebook unsuccessfully however: `from pyramid.arima import auto_arima`. Are there more steps I need to do?
