### ISSUE TITLE
Some question on python.runtime

### ISSUE THREAD

**Issue by shmliao** [QuantConnect/Lean#3247]
when using python.runtime,some questions puzzle me, many mistakes happens, like "System.IO.FileNotFoundException","System.IO.FileLoadException",System.IO.FileNotFoundException,maybe this is the reason leadd my python code running slow,very slowly,I cant tolerate.my code is just a simple demo.so l wanna know how you resolve this problem,thanks,my python version is 3.6

**Comment by Doggie52** [comment]
Please follow the standard issue template so that we may get the information needed to help you resolve your issues.
