### ISSUE TITLE
some question in python.runtime

### ISSUE THREAD

**Issue by shmliao** [QuantConnect/Lean#3248]
#### Expected Behavior
run fast 

#### Actual Behavior
using python.runtime lead slowly than python

#### Reproducing the Problem
when using python.runtime,some questions puzzle me, many mistakes happens, like "System.IO.FileNotFoundException","System.IO.FileLoadException",System.IO.FileNotFoundException",maybe this is the reason leads my python code running slow,very slowly,I cant tolerate.my code is just a simple demo.so l wanna know how you resolve this problem,thanks,my python version is 3.6

#### System Information
win10,python3.6,x64

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [ ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment]
Hi @shmliao, we are constantly working on Lean performance, especially its integration with Python. 
Could you please post your questions in the [community forum](https://www.quantconnect.com/forum/discussions/1/interesting) with more detail before you open a GitHub issue?
