### ISSUE TITLE
Use quote data when available for Buying Power Model

### ISSUE THREAD

**Issue by firestrand** [QuantConnect/Lean#3255]
#### Expected Behavior

When Filling a Buy order we expect the Ask.Close price to be used.
When Filling a Sell order we expect the Bid.Close price to be used.
#### Actual Behavior

Currently OandaBrokerage uses the ImmediateFillModel which uses the Midpoint Close price, and a $0 transaction fee. This will lead to incorrect backtesting since Oanda uses the Bid and Ask spread as a transaction fee.

#### Potential Solution

Create a new FillModel named SpreadFillModel which uses the Bid or Ask prices based on the Direction.

#### Reproducing the Problem

Using the OandaBrokerageModel take note that the buy and sell prices used are the Midpoints instead of the Bid and Ask prices is would be expected.

#### System Information

N/A

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by Doggie52** [comment]
It's my understanding that `ImmediateFillModel` **does** use ask and bid prices correctly:

 1. https://github.com/QuantConnect/Lean/blob/master/Common/Orders/Fills/ImmediateFillModel.cs calls https://github.com/QuantConnect/Lean/blob/master/Common/Orders/Fills/FillModel.cs
 2. In e.g. a market order, `GetPricesCheckingPythonWrapper()` is called with the direction of the trade
 3. The above calls `GetPrices()` which returns either the Bid or Ask bar (https://github.com/QuantConnect/Lean/blob/master/Common/Orders/Fills/FillModel.cs#L519) depending on direction

Where are you seeing midpoint prices being used as fills? Can you please attach evidence of this?

**Comment by firestrand** [comment]
I was looking at the values present in the Portfolio object while debugging.
There the quantity and $value reported for the position matched the midpoint, I assumed that was due to the FillModel.

Upon further investigation it appears that [https://github.com/QuantConnect/Lean/blob/master/Common/Securities/BuyingPowerModel.cs#L358](https://github.com/QuantConnect/Lean/blob/master/Common/Securities/BuyingPowerModel.cs#L358) is responsible for calculating the orderQuantity using the midpoint.

For a simple buy and hold example this is through `SetHoldings("EURUSD", 1);` which results in the call path SetHoldings->CalculateOrderQuantity->PortFolioTarget.Percent->BuyingPowerModel.GetMaximumOrderQuantityForTargetValue

As pointed out the logic in `FillModel.cs` indeed looks correct even if the Porfolio values aren't. So most likely the required change would be to make the BuyingPowerModel and Portfolio values match the eventual FillModel values by respecting the Direction when calculating and setting the values.

As I am still new to the code I look forward learning more.

**Comment by Doggie52** [comment]
> I was looking at the values present in the Portfolio object while debugging.
> There the quantity and $value reported for the position matched the midpoint, I assumed that was due to the FillModel.
> 
> Upon further investigation it appears that https://github.com/QuantConnect/Lean/blob/master/Common/Securities/BuyingPowerModel.cs#L358 is responsible for calculating the orderQuantity using the midpoint.
> 
> For a simple buy and hold example this is through `SetHoldings("EURUSD", 1);` which results in the call path SetHoldings->CalculateOrderQuantity->PortFolioTarget.Percent->BuyingPowerModel.GetMaximumOrderQuantityForTargetValue
> 
> As pointed out the logic in `FillModel.cs` indeed looks correct even if the Porfolio values aren't. So most likely the required change would be to make the BuyingPowerModel and Portfolio values match the eventual FillModel values by respecting the Direction when calculating and setting the values.
> 
> As I am still new to the code I look forward learning more.

This is interesting actually, never spotted that myself as I'm trading instruments where the bid/ask spread is quite tight.

I don't see why https://github.com/QuantConnect/Lean/blob/2e6ea241c8bf3c7793aa58b967e61b2f210dbe1c/Common/Securities/BuyingPowerModel.cs#L338 shouldn't take into account the direction, i.e. replacing `1` with `direction == OrderDirection.Sell ? -1 : 1`, but someone might correct me.

**Comment by firestrand** [comment]
Replacing the unitPrice line in the BuyingPowerModel with:
`var unitPrice = direction == OrderDirection.Buy ? parameters.Security.AskPrice : parameters.Security.BidPrice;
`
Makes things work as I expect but I have no idea if that's the best way to deal with it or would have unintended side effects for other Securitys.

**Comment by Doggie52** [comment]
I don't think your approach is the best, I think the one I suggested is more robust. You want to submit a market order rather than simply taking the values of the last received bids and asks, as you're not sure when these were received. Submitting a market order (especially in live trading) will guarantee you're working with as up-to-date prices as possible.

**Comment by firestrand** [comment]
I disagree, the MarketOrder implementation of GetValue actually uses the passed in Security
[https://github.com/QuantConnect/Lean/blob/master/Common/Orders/MarketOrder.cs#L61](https://github.com/QuantConnect/Lean/blob/master/Common/Orders/MarketOrder.cs#L61
) as such my solution just doesn't bother using the MarketOrder to get the price for order quantity calculation, and respects the Direction.

**Comment by Doggie52** [comment]
I don't necessarily agree with your approach but do not have any good reasons why it wouldn't work. I suppose you could have securities that don't have a concept of bids or asks.

Upon further reflection, my approach probably would not work anyway, as it would return a negative number.

**Comment by firestrand** [comment]
Agree, I don't know enough about the code surrounding a Security to know if bid and ask always have values.

**Comment by jaredbroad** [comment]
Cool discussion. Glad the fill model correctly uses spread; 

Sound like the final point is that the portfolio & buying power model values are off by about 0.1%?

**Comment by Doggie52** [comment]
Closed because `wontfix`? Seems like low-hanging fruit to fix - we are simply unsure of the best approach from a performance and consistency perspective.
