### ISSUE TITLE
Volatility and variance should be calculated using log of returns and zero mean

### ISSUE THREAD

**Issue by Doggie52** [QuantConnect/Lean#3257]
#### Background
This issue is meant more as a basis for discussion, similar to https://github.com/quantopian/zipline/issues/29.

##### Log of returns
In quantitative finance we typically use the logarithm of returns (rather than the raw returns themselves) to calculate variance and volatility. This assumption enables use of other statistical measures and is generally the academically preferred way. It also forces the assumption that prices follow geometric (rather than arithmetic) brownian motion, which is probably more accurate for systematic algorithms where the order size varies with the portfolio size.

Sources include:
 - Wilmott, P. (2007). Paul Wilmott introduces quantitative finance. Chichester, West Sussex, England: J. Wiley & Sons, pp.209-210.
 - _ample more, please feel free to add_

##### Zero mean in the calculation of standard deviation
Assuming the mean is zero is also widely used, typically because over shorter time periods, the most correct prediction is that the mean return (drift) is indeed zero.

#### Expected Behavior
Volatility and variance are calculated using the log of price returns and assume mean is zero.

#### Actual Behavior
Volatility and variance are calculated using the raw price returns.

#### Potential Solution
Passing in the logs of `1 + return_i` at https://github.com/QuantConnect/Lean/blob/d43344318a69ae7cc495c6d4f32aeaadfc023bba/Common/Statistics/PortfolioStatistics.cs#L285 using LINQ.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Hi @Doggie52 , 
I believe that using log returns is the correct approach for volatility modeling in options modeling which is Paul Wilmott's subject. Whereas you are suggesting a change in the portfolio statistics. 

We have found the following article from Meucci:
> Meucci, Attilio, Quant Nugget 2: Linear vs. Compounded Returns – Common Pitfalls in Portfolio Management (May 1, 2010). 
GARP Risk Professional, pp. 49-51, April 2010 , Available at SSRN: https://ssrn.com/abstract=1586656

where he discussed linear and log returns for Portfolio Management. He concludes that we should use linear returns.
