### ISSUE TITLE
Feature Request: Increase contrast of highlight/text in dark mode code editor search function

### ISSUE THREAD

**Issue by mlepisto** [QuantConnect/Lean#3260]
#### Expected Behavior
Using search in code editor should easily highlight the result.

#### Actual Behavior
In dark mode, highlight is light gray over a black background, resulting in hard to see text and hard to find matches.  See "self.ivRank" in the attached screenshot. 

#### Potential Solution
Change the highlight block to a much higher contrast color such as red. 

#### Reproducing the Problem
Perform a search for text in the Algo Labcode editor. 

#### System Information

MacOS 10.14.4
![Screen Shot 2019-06-03 at 12 04 32 PM](https://user-images.githubusercontent.com/221701/58816607-d0eb2b00-85f7-11e9-8173-f094fa13b0a7.png)

#### Checklist

- [ ] I have completely filled out this template
- [ ] I have confirmed that this issue exists on the current `master` branch
- [ ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hi @mlepisto ! Thanks for the feature request. Note that this is the Lean repository, for cloud/UI please post at the QC forums or send an email to support@quantconnect.com
