### ISSUE TITLE
Add Implied Volatility Rank API

### ISSUE THREAD

**Issue by simonsonjack** [QuantConnect/Lean#3265]
#### Expected Behavior

Implied Volatility Rank is the percentile of the current option's Implied Volatility against the one-year IV minimum and maximum for rolling ATM options.

```
IVR = 100 * (current IV - 52-week IV low) / (52-week IV High - 52-week IV low)
```

Essentially, you are taking weighted averages of each OTM contract's implied volatility (symmetrical around the risk-neutral 30-day at-the-money-forward price) of the two options expiration cycles that are closest to the 30-day mark (more than 23 days and less than 37 days to expiration), then interpolating between the two in order to calculate a singular constant-maturity 30-day implied volatility. This calculation is then repeated at a minimum of once per day. Typically, this value will then be compared in a percentile rank calculation to the prior 52-weeks/252 days of values to compute IVR.

Note this process will naturally be reliant on using the relative dispersion of strikes around the ATM (i.e. using a constant OTM moneyness or delta, not a constant strike level) rather than specific contract symbols.

#### Actual Behavior

Not yet implemented.

#### Checklist

- [x] I have completely filled out this template
- [ ] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Closing as no demand for now. Can reopen with demand.

**Comment by nj20** [comment]
As an options trader, implied volatility rank is a must to have since it defines the demand for the option in the market

**Comment by kevinostoll-dfg** [comment]
> As an options trader, implied volatility rank is a must to have since it defines the demand for the option in the market

2nd that request. Could we reopen this?

**Comment by jaybennett89** [comment]
Would love to see this feature please!

**Comment by DaakuPMT** [comment]
+1 need this feature as an options trader. I currently have to implement things from scratch if I want to run any options backtests.
