### ISSUE TITLE
Live coarse universe may include securities from previous day

### ISSUE THREAD

**Issue by StefanoRaggi** [QuantConnect/Lean#3287]
#### Expected Behavior
After Live coarse universe selection runs, we expect algorithm.ActiveSecurities to include only the securities selected (plus any security with open positions and orders).

#### Actual Behavior
Depending on the time Live coarse universe selection runs, securities which were selected previously may be kept in the universe (even if there are no open positions/orders).

#### Potential Solution
Update the default value of `QCAlgorithm.UniverseSettings.MinimumTimeInUniverse` from `TimeSpan.FromDays(1)` to `TimeSpan.Zero`.

#### Reproducing the Problem
Run a Coarse universe selection algorithm in Live mode for a week, logging the symbols selected by the coarse selection function and the symbols in `algorithm.ActiveSecurities` each day. 
On some days, securities from the previous day will be carried over to the next day.

#### System Information
n/a

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by simonsonjack** [comment]
User reports another instance of this
