### ISSUE TITLE
Add Alternative Data from Estimize

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#3289]
#### Expected Behavior
[Estimize](https://www.estimize.com/) is part of Lean/QuantConnect alternative data portfolio.

#### Actual Behavior
Not implemented.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
Closed by #3290
