### ISSUE TITLE
[Feature] Stop-Limit Order Types

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#33]
Add Stop Limit order type to LEAN

1) Extend the order type enum to add the new type.
2) Add new default fill methods to SecurityTransactionModel, EquityTransactionModel and ForexTransactionModel. High chance only need to implement the base type (SecurityTransactionModel) and the others can just use that.
3) Create helper methods in QCAlgorithm.Transactions.cs which return the order id of the newly created and submitted order.
```
int LimitOrder(symbol, quantity, limitPrice); 
int StopLimitOrder(symbol, quantity, stopPrice, limitPrice);
void CancelOrder(int orderId);
```
Because limit orders are filled at a later moment in time they can bypass the equity checks(?) and be submitted directly to the Orders queue (they'll need to be be checked at fill time dynamically by the fill methods**). If an invalid order is requested (e.g. stop price is zero or negative) return a negative value for order id (See Order method in QCAlgorithm Transactions file).

** Should research/get references this is possible from a brokerage or other source - maybe in reality the brokerage limits the size of limit orders when they are placed to the account buying power.

**Comment by jaredbroad** [comment]
Tradier brokerage confirms the orders are rejected if you don't have enough cash to fill them at *placement* time - this is because they are submitted to the exchange and on record as a real-offer (which must be backed by cash).  

So the Order method in QC.Transactions.cs can be used to perform pre-submission checks. This will keep all the negative order id's in one place.

Tradier disallows cash withdrawals while there are in-market limit orders, and in the event of trade fees or interest charges pushing cash below the order value they call/email the client to cancel the order. This is tricky to model. We might need to model it by checking the cash available at fulfillment time instead.

**Comment by jilott** [comment]
@jaredbroad, are you thinking this should be implemented as stop order that gets converted to a limit order when triggered? The alternative is to add a new field to the Order class to hold the stop(or limit) price and to simply create a fill method which combines the logic of the existing stop and limit order methods.

Personally, I think I like the idea of the stop order triggering and becoming a limit order, the same could be applied to the stop market order that exists. I think that this would simplify the transaction fill code and reduce duplication. The market and limit aspect of a stop order should behave exactly as a regular market or limit order does.

**Comment by jilott** [comment]
I'm digging into the transaction models and I'm not sure I understand why the order price is modified by the fill methods. It seems like the order price should never change because you get a fill at some price which may or may not be different from the order that was placed(slippage). In the code as it stands now, the fill price and order price seem to end up being equal. Can anyone comment on this?

**Comment by jaredbroad** [comment]
Hey @jilott - this was because I was trying to cram limit and market orders into the same object; which was [bad but] OK for backtesting; but not with live trading. Now we'll do it properly:

I've brain stormed it with @mchandschuh and we think the best way would be to define new order types which extend from the Order object. From now on the base "Price" will be the *fill price*.

The new types will be:
LimitOrder : Order
StopLimitOrder : Order
MarketOrder : Order 
StopMarketOrder : Order ... 
etc as defined by the current OrderType enum.

This way the StopLimitOrder can hold the StopPrice and LimitPrice specific to its order type. Later we can add OneCancelsAllOrder type which has a list of the orders to cancel.

Inside the security transaction model I'll move the Fill() method out into the BacktestingBrokerage to keep the switch statement in one place and transaction models will be 100% focused on methods for filling the virtual order.

Its a bit of a big change but 99.5% of users use the default Order(symbol, quantity) helper method inside the QCAlgorithm class so it shouldn't break any algorithms. Now is a good time to change it before too many people are doing advanced order types. And with this more robust system in place we can do some elegant helper methods in QCAlgorithm to create the specific order types.

I'll port the code over tonight, it should be up in a couple of hours with a pattern we can follow for the "StopLimitOrder" type.

**Comment by jilott** [comment]
That sounds good. I was thinking that some refactoring was probably going to be needed to come up with a good solution. Once the more significant changes have been committed, I should be able to do up a StopLimit order.

**Comment by jaredbroad** [comment]
Committed new order type pattern & dedicated classes with latest commits #73c73a5f4e7a18f5f16df876afd0a03b24d36f81,

**Comment by jilott** [comment]
Well @jaredbroad it looks like you beat me to it. I really wanted to work on this but my day job kept me busy most nights this week.

**Comment by jaredbroad** [comment]
No worries @jilott - there are plenty more to do! I wanted to do one to make sure it was possible. In the process I found there were a few helper methods and system wide changes needed to make it possible. 

We can start with this list: https://www.interactivebrokers.com/en/index.php?f=4985 Popular ones would probably be Market on Open,Close, Limit on Open, Close, One Cancels All, Trailing Stop

Now to implement new types we just need to implement them in the interface and the base security transaction model.
