### ISSUE TITLE
Make Order Quantity Fractional

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#330]
Order quantity is currently an int. Change it to be a decimal. 

The change will be fairly extensive covering API methods and brokerage implementations.

**Comment by jameschch** [comment]
I've looked into this and just changing the order quantity is not necessarily very problematic. There are a few explicit variable declarations but apart from this, everything ties together with just a few field types. There should not be a great deal of breaking changes to algorithms, although I think some will be unavoidable.

If this is followed through, there will also need to be change to Tick and Tradebar classes to support decimalised volumes.

**Comment by StefanoRaggi** [comment]
Fixed in https://github.com/QuantConnect/Lean/pull/982
