### ISSUE TITLE
Visual Studio 2019 crashes when submitting backtest via plugin 

### ISSUE THREAD

**Issue by marvin-hansen** [QuantConnect/Lean#3300]
#### Expected Behavior
Plugin submits python algo for backtest to QuantConnect 

#### Actual Behavior
* Visual Studio 2019 crashes
* No backtest submitted 

#### Reproducing the Problem
1) Install VS 2019 (June) 
2) Install Plugin & Python 3.6  
3) Clone Lean & build 
4) Login to plugin & Click right for upload file to QC
5) Chose any sample algo, click right and send to backtest 

Essentially, the exact same steps from the tutorial except its VS 2019
https://www.quantconnect.com/tutorials/open-source/backtesting-from-visual-studio

#### System Information
* Win 10 
* Visual Studio 2019 
* Python 3.6 (added to path)

#### Checklist

- [ x] I have completely filled out this template
- [x ] I have confirmed that this issue exists on the current `master` branch
- [ x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ x] I have provided detailed steps to reproduce the issue

**Comment by marvin-hansen** [comment]
Switched to Visual Studio 2017 and now everything works as expected. Whatever the actual cause might be, it is very likely related to VS 2019.

**Comment by mcsj120** [comment]
Is there anyway we can update it to work with Visual Studio 2019? I am encountering the same issue.

**Comment by Martin-Molinero** [comment]
Hi @mcsj120 ! We've released a new version with the changes of the PR https://github.com/QuantConnect/Lean/pull/3391, please test it, can be found at https://www.quantconnect.com/tutorials/open-source/backtesting-from-visual-studio
Also please update your VS to the latest version, we have had reports before that older VS2019 didn't work properly, ref https://www.quantconnect.com/forum/discussion/5866/backtesting-from-visual-studio/p1

**Comment by gcifani** [comment]
I successfully installed the latest version of the plug-in (QuantConnect.VisualStudioPlugin_**20190711**.vsix) in VS2019 Professional 16.2.3 but when I right click a .cs algo file in Solution Explorer the menus "Send for Backtesting" and "Save to QuantConnect" doesn't appear. QuantConnect login and QuantConnect window are both working perfectly.

Any idea about how to solve this before switching back to VS2017?

**Comment by gcifani** [comment]
Hi @Martin-Molinero, thank you.

I suspected a Regional Setting issue here (my OS is in ENG but all my locale settings are set in ITA) but even after switching locale to en-us nothing changed. I also tried to uninstall, reboot, reinstall the plug-in without any success.

I run VS with /Log flag activeted and shared privately with you the log file.

Thanks
