### ISSUE TITLE
API: Completely parse Live deployment result JObject

### ISSUE THREAD

**Issue by Doggie52** [QuantConnect/Lean#3301]
Creating a placeholder issue so this can be referenced later.

#### Expected Behavior
`CreateLiveResultsFromJObject()` is able to fully parse and return the live deployment results to `ReadLiveAlgorithm()`.

#### Actual Behavior
`CreateLiveResultsFromJObject()` only returns charts (and only the last ~25 minutes worth of data, see #3150).

#### Potential Solution
Deserialize more of the data in `CreateLiveResultsFromJObject()`.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
See https://github.com/QuantConnect/Lean/issues/3150
