### ISSUE TITLE
RollingWindow ArgumentOutOfRangeException is confusing when Count == 0

### ISSUE THREAD

**Issue by Doggie52** [QuantConnect/Lean#3306]
People forgetting to check `RollingWindow.IsReady` or accessing an entry that doesn't exist is one of the most commonly observed issues on the forums these days. I think it could be alleviated if the error message was a bit more verbose.

#### Expected Behavior
The way I see it, there are three different cases:

Attempting to:
1. access any entry in the `RollingWindow` when `Count == 0` should result in an error telling the user the window is empty and that they should check if their window is ready;
2. access an `i` that is outside the range of allowable `i`'s should result in an error telling the user their `i` should be within the allowable range (similar to how https://github.com/QuantConnect/Lean/blob/master/Common/Indicators/RollingWindow.cs#L142 does it today);
3. access an `i` inside the range of allowable `i`'s but that hasn't been populated yet (i.e. `i > Count - 1`) should result in an error telling the user that this entry is not populated yet and that they should check if their window is ready;

Potentially 1 and 3 could be merged into one.

#### Actual Behavior
Today, all of the above cases leads to the same error message. This is particularly problematic when `i == 0 && Count == 0`, as it tells the user `i` should be between `0 and -1` which is nonsensical.

#### Potential Solution
Re-writing the relevant section in `public T this [int i]`.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
Closed by #3373
