### ISSUE TITLE
Custom Timeouts for Training Models

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#3319]
With the rise of AI it is becoming more common to do expensive computations in a strategy which might take a while. LEAN currently has a limit of 10 minutes per loop of the algorithm designed to prevent an algorithm locking up and crashing without user awareness.

We need a way to train these models for longer periods.

#### Expected Behavior
Some mechanism for training models -- with a maximum timeout controlled by the Controls class. 

#### Actual Behavior
No safe way to do computations longer than 10min. 

#### Potential Solution
Helper method:
QCA.Train( action, defaultTimeout = 30min, callback=null, synchronous=true)

or "semaphore" flag for 1x increases in the timeout:
QCA.LoopTimeout = TimeSpan.FromMinutes(30);

#### Reproducing the Problem
Run any backtest with long processing intra-loop. 

#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jordizle** [comment]
I've run into this problem..

It would be good to have a global setting, with a default of 5 minutes but can be overwritten in the `Initialize` function.
