### ISSUE TITLE
Adding Multiple Custom Data Sources Results in Symbol Collision

### ISSUE THREAD

**Issue by gsalaz98** [QuantConnect/Lean#3332]
#### Expected Behavior

Custom data sources should have unique symbols separated by type of custom data
#### Actual Behavior

The two symbols generated would collide with each other
#### Potential Solution

Add an identifier to the `Symbol.ID.Symbol` value containing the name of the custom data type
#### Reproducing the Problem

```C#
AddData<T>("TWX", Resolution.Daily).Symbol == AddData<K>("TWX", Resolution.Daily).Symbol

// returns true
```

#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by mchandschuh** [comment]
VS regex for finding usages of `Symbol.Create(xxx, SecurityType.Base`
> Symbol.Create\(.*Base

**Comment by mchandschuh** [comment]
Questions:
1. Is it important to embed type information for universes w/ `SecurityType.Base` ?

**Comment by jaredbroad** [comment]
Trying to fit "square pegs into round holes" solutions always make me regret the implementation later. Perhaps this needs a new type of non-price data which isn't keyed by symbol? Are we missing a core abstraction concept here? Or should the symbol object itself get more properties (vs putting it into the ticker string). e.g. should we change from `SecurityType` - to just `Type`?

**Comment by mchandschuh** [comment]
> Trying to fit "square pegs into round holes" solutions always make me regret the implementation later. Perhaps this needs a new type of non-price data which isn't keyed by symbol? Are we missing a core abstraction concept here? Or should the symbol object itself get more properties (vs putting it into the ticker string).

I had considered something like this as well, but the other security types don't really match up in the same way, for example, the difference between ticks/trade bars/quote bars (the 'data type')  vs custom data, where the data type is inextricably linked to the data source. I do, however, agree with your assessment RE: embedding type information into the ticker string, just not so sure yet if adding an additional `string` member to `SecurityIdentifer` is the right way to go for solely supporting custom data, and I suppose further to that point, I haven't located a case where I've needed (or wanted) to extract the type information from the SID.

**Comment by jaredbroad** [comment]
Bit of an exhaustive discussion but summary is:

 - Appending TypeName as an extension least ugly solution; gives it a unique string for manual lookups and is relatively portable as type evolve over time. 

AddData<Estimize>("IBM");
 -- Inside AddData add it to system as `"IBM.Estimize"`; including adding to symbol cache so it won't conflict with the AddEquity("IBM") look up.
 -- Direct manual look ups possible with `slice["IBM.Estimize"]`
 -- Users recommended to use symbol objects anyway which will be `slice[ x ]`;
 -- Likely need to strip the extension at the reader level to get the data-file location.
