### ISSUE TITLE
Docker container build failed, oracle-java8-installer is not available

### ISSUE THREAD

**Issue by adp786** [QuantConnect/Lean#3334]
#### System Information

![docker error](https://user-images.githubusercontent.com/40971247/59890528-4cdac680-939f-11e9-978a-973a89a1d010.PNG)
#### Checklist

- [x ] I have completely filled out this template
- [x ] I have confirmed that this issue exists on the current `master` branch
- [ x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ x] I have provided detailed steps to reproduce the issue

**Comment by darkknight7** [comment]
According to this forum, this ppa has been discontinued. https://askubuntu.com/questions/790671/oracle-java8-installer-no-installation-candidate

So we need to use alternate solution to install Java. I am also working on solving the same problem. will let you know, if it works.

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/3379
