### ISSUE TITLE
Migrate from IEX Trading to IEX Cloud API for Data Downloader

### ISSUE THREAD

**Issue by simonsonjack** [QuantConnect/Lean#3342]
#### Expected Behavior

The command 
`QuantConnect.ToolBox.exe --app=IEXDownloader --tickers=NFLX --resolution=Daily --from-date=20180101-00:00:00 --to-date=20181231-00:00:00`
should download 1 year of daily NFLX data from the IEX API. It has worked previously and was published as an example in one of our blog posts.
#### Actual Behavior

The command returns a 403 error. Upon inspection, it turns out IEX has stopped supporting their free API endpoint (https://iextrading.com/developer/#sunset-schedule).

#### Potential Solution

Delete the IEX Downloader class

#### Reproducing the Problem

Run the code specified above
#### System Information

Windows 10
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
https://intercom.help/iexcloud/collections/1751918-migrating-to-iex-cloud-from-legacy-iex-group-api

**Comment by simonsonjack** [comment]
Closed by PR #3350
