### ISSUE TITLE
2 issues with dockerfile

### ISSUE THREAD

**Issue by mg64ve** [QuantConnect/Lean#3352]
#### Expected Behavior

Running the following command should complete smoothly:

docker build -t lean.v1 .

after:

git clone https://github.com/QuantConnect/Lean.git

#### Actual Behavior

Getting this error:

Step 3/5 : COPY ./Launcher/bin/Release /root/Lean/Launcher/bin/Release
COPY failed: stat /d2/docker/tmp/docker-builder116511166/Launcher/bin/Release: no such file or directory

#### Potential Solution

While compiling the mono project I was getting an error that xbuild should not be used and instead I should use msbuild.
The problem is that msbuild does not produce the following directory:

./Launcher/bin/Release

it makes:

./Launcher/bin/Debug

changing the line in the docker file to:

COPY ./Launcher/bin/Debug /root/Lean/Launcher/bin/Release

solves the problem of building the container.
However, I am not sure if this process is correct.

#### System Information

Linux wks.net 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core)

rpm -qa | grep -i mono
mono-data-oracle-6.0.0.307-0.xamarin.1.epel7.x86_64
mono-data-6.0.0.307-0.xamarin.1.epel7.x86_64
mono-extras-6.0.0.307-0.xamarin.1.epel7.x86_64
mono-devel-6.0.0.307-0.xamarin.1.epel7.x86_64
gnu-free-mono-fonts-20120503-8.el7.noarch
mono-winfxcore-6.0.0.307-0.xamarin.1.epel7.x86_64
mono-llvm-tools-6.0+mono20181128173919-0.xamarin.4.epel7.x86_64
mono-data-sqlite-6.0.0.307-0.xamarin.1.epel7.x86_64
culmus-miriam-mono-clm-fonts-0.130-3.el7.noarch
mono-core-6.0.0.307-0.xamarin.1.epel7.x86_64
dejavu-sans-mono-fonts-2.33-6.el7.noarch
mono-mvc-6.0.0.307-0.xamarin.1.epel7.x86_64
liberation-mono-fonts-1.07.2-16.el7.noarch
mono-web-6.0.0.307-0.xamarin.1.epel7.x86_64
mono-winforms-6.0.0.307-0.xamarin.1.epel7.x86_64
mono-wcf-6.0.0.307-0.xamarin.1.epel7.x86_64
libmono-llvm0-6.0.0.307-0.xamarin.1.epel7.x86_64

#### Checklist

- [X ] I have completely filled out this template
- [ X] I have confirmed that this issue exists on the current `master` branch
- [ X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ X] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
This is more of a question about how you use the provided dockerfile, you will need to customize it to your build path and to what executables you want to run.
