### ISSUE TITLE
LiveOptionChainProvider.GetOptionContractList Failure

### ISSUE THREAD

**Issue by StefanoRaggi** [QuantConnect/Lean#3364]
#### Expected Behavior
`LiveOptionChainProvider.GetOptionContractList` should try to download the option chain a few times, before reporting the exception and terminating the algorithm.

#### Actual Behavior
In `LiveOptionChainProvider.GetOptionContractList` any web failure or timeout causes the algorithm to be terminated immediately with a runtime error. 
The most common error seen is this one:
```
System.Net.WebException: Error getting response stream (ReadDoneAsync2): ReceiveFailure
```

#### Potential Solution
Add retry logic in `LiveOptionChainProvider.GetOptionContractList`

#### Reproducing the Problem
n/a

#### System Information
n/a

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Fixed by https://github.com/QuantConnect/Lean/pull/3365
