### ISSUE TITLE
Add RollingWindow History on All Indicators

### ISSUE THREAD

**Issue by oldrichsmejkal** [QuantConnect/Lean#3372]
#### Expected Behavior
Rolling window (history), should be available just by specifying history length in constructor or calling some method with this parameter after initialisation.
This is quite heavily used feature, given number of question for this topic. It is available in implicit form similar to described one in most other trading/backtesting platforms...
.
#### Actual Behavior
To add rolling window functionality, there is need to explicitly add values to explicitly created rolling window

#### Potential Solution
Example usage: 
self.RSI_Ind = self.RSI("AAPL", RSI_Period, history= 50)
...
if self.RSI_Ind.history.IsReady:
  self.Debug ("Previous RSI value is: {}".format(self.RSI_Ind.history[1]))

**Comment by jaredbroad** [comment]
- Agreed. Popular request. Full API spec here: https://github.com/QuantConnect/Lean/pull/4842#issuecomment-706798613
 - Add optional int parameter to all helper methods, to the current indicators. Default to 0.
