### ISSUE TITLE
Create an IQueueDataHandler / IDataDownloader implementation for Polygon API.

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#3380]
#### Expected Behavior
[Polygon.io](https://polygon.io/docs/#getting-started) provides affordable market data via API. It would be nice to have this supported in LEAN. Their API can support historical download and live data.

#### Actual Behavior
No Polygon implementation.

#### Potential Solution
Implement Polygon.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by mul1sh** [comment]
@jaredbroad which polygon endpoints would you like implemented?

**Comment by mul1sh** [comment]
@jaredbroad which polygon endpoints would you like implemented i.e. stocks, forex, crypto or all of them? Would like to try to sort this issue.

**Comment by mul1sh** [comment]
@jaredbroad thanks will be working from the above PR, should be done by tomorrow because everything is straightforward thus far 😃 

Also should I include tests?

**Comment by mul1sh** [comment]
hi @jaredbroad  just to clarify, what does the --resolution argument stand for , for the [downloaders ](https://github.com/QuantConnect/Lean/tree/master/ToolBox#available-downloaders)

**Comment by IlshatGaripov** [comment]
Sorry I am stopping working on this issue - as data vendonrs are low class !

**Comment by sprgn** [comment]
Looks like Alpaca uses plygon.io , so part of that implementation is already there.  But would love to be able to do backtesting with data from polygon.io

**Comment by TightLinesOfCode** [comment]
I tried using the LEAN toolbox for a local installation with Polygon.IO as my data stream, and it fails.   Has anyone done a proper development of the APIs that can easily be used ?    Is there still a bounty available ?

I need to have a local installation that I can very easily download the data and store properly in the LEAN format.
