### ISSUE TITLE
Add missing Coinbase currency pairs

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#3393]
#### Expected Behavior
Lean support all Coinbase currency pair.

#### Actual Behavior
`Symbol can't be found in the Symbol Properties Database: BTCUSDC.`

Update: `SUSHIUSD` is not in SPDB but QuantConnect has its data. 

#### Potential Solution
Add missing pair (see #3341)

#### Reproducing the Problem
Algorithm with `AddCrypto("BTCUSDC")`.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
`BTCUSDC` already present for GDAX, Binance & kraken 👍
