### ISSUE TITLE
Set Security to Raw Normalization To a Pending Equity Addition

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#3396]
#### Expected Behavior
Adding options contracts vai `AddOptionContract` in a universe selection algorithm should not issue an error message on price normalization mode. 

#### Actual Behavior
At the end of time-step, while options contracts were added underlying equity may be pending to be added to the universe and this error message is sent
```
Runtime Error: Warning: The NVDA equity security was set the raw price normalization mode to work with options.
```
#### Potential Solution
N/A

#### Reproducing the Problem
Universe selection algorithm that adds options contracts in `OnSecuritiesChanged` method.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
I believe this issue could be avoided using `UniverseSettings.DataNormalizationMode = DataNormalizationMode.Raw;` during algorithm initialization, could this be a valid option? Used the following algorithm to reproduce and test the suggested workaround.

```
public class CoarseFundamentalTop3Algorithm : QCAlgorithm
{
    private const int NumberOfSymbols = 3;
    public override void Initialize()
    {
        UniverseSettings.Resolution = Resolution.Minute;
        UniverseSettings.DataNormalizationMode = DataNormalizationMode.Raw;
        SetStartDate(2014, 03, 24);
        SetEndDate(2014, 03, 28);
        AddUniverse(CoarseSelectionFunction);
    }

    public static IEnumerable<Symbol> CoarseSelectionFunction(IEnumerable<CoarseFundamental> coarse)
    {
        return coarse.OrderByDescending(x => x.DollarVolume)
            .Take(NumberOfSymbols)
            .Select(x => x.Symbol);
    }

    public override void OnSecuritiesChanged(SecurityChanges changes)
    {
        Log($"OnSecuritiesChanged({UtcTime:o}):: {changes}");
        foreach (var addedSecurity in changes.AddedSecurities.Where(security => security.Type == SecurityType.Equity))
        {
            var contracts = OptionChainProvider.GetOptionContractList(addedSecurity.Symbol, Time).Take(5);
            foreach (var contract in contracts)
            {
                AddOptionContract(contract);
            }
        }
    }
}
```
