### ISSUE TITLE
CoarseUniverseGenerator does not save files

### ISSUE THREAD

**Issue by scolemann** [QuantConnect/Lean#3411]
#### Expected Behavior
CoarseUniverseGenerator should generate coarse files

#### Actual Behavior
CoarseUniverseGenerator did not generate files.  After stepping through it appeared that ProcessEquityDirectories method was simply being skipped.

#### Potential Solution
It appears that the reason ProcessEquityDirectories was skipped is because it returns via yield and when it is called on Line 78 of CoarseUniverseGeneratorProgram.cs it does nothing with the return value.  Since it does nothing, the compiler appears to skip the method.

A solution would be to add .ToList() at the end of the method call, this will force the method to be called.

#### Reproducing the Problem
Run the CoarseUniverseGenerator app via commandline

#### System Information
Windows 10.

#### Checklist

- [x ] I have completely filled out this template
- [ x] I have confirmed that this issue exists on the current `master` branch
- [ x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/3826
