### ISSUE TITLE
Add Custom Indicator to RollingWindow

### ISSUE THREAD

**Issue by AlinXlin** [QuantConnect/Lean#3423]
#### Expected Behavior
 
Custom Indicators should have `Updated` attribute which is an event handler that fires after the custom indicator is updated. This would allow users to add custom indicators to a rolling window.

#### Actual Behavior

The following exception has occurred: `AttributeError : 'CustomSimpleMovingAverage' object has no attribute 'Updated'`.

#### Potential Solution

N/A

#### Reproducing the Problem

Add
```
self.custom.Updated += self.customUpdated
self.customWindow = RollingWindow[IndicatorDataPoint](5)
```
in the `Initialize` method and add
```
def customUpdated(self, sender, updated):
        self.customWindow.Add(updated)
```
in `CustomIndicatorAlgorithm(QCAlgorithm)` class of [CustomIndicatorAlgorithm.py](https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/CustomIndicatorAlgorithm.py#L44) and run the algorithm.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Doggie52** [comment]
To be clear this is only an issue for Python algos, correct?
