### ISSUE TITLE
Future-usa-ES Missing Holidays in MHDB

### ISSUE THREAD

**Issue by xinweimetrics** [QuantConnect/Lean#3461]
#### Expected Behavior

On 2017/12/31, FrontMonth() should return ES contract with expiry on 2018/03/16.

#### Actual Behavior

On 2017/12/31, FrontMonth() returns ES contract with expiry on 2018/06/15.

#### Potential Solution

`holidays` is empty for this security. If `holidays` are specified, the issue will not happen as backtesting would ignore date 2017/12/31 due to market early close on New Year Eve.

Note: A related issue is that the ES data file is incomplete on 2017/12/31. If information about the ES contract with expiry on 2018/03/16 is included, the issue also would not have happened. I've reported this [missing file issue](https://www.quantconnect.com/forum/discussion/6232/es-minute-the-issue-starts-from-dec-31st-2017-and-continues-until-dec-31st-2017/p1) on the Data Explorer.

#### Reproducing the Problem

The problem is reported in this ticket: https://www.quantconnect.com/forum/discussion/6036/es-frontmonth-changes-often-early-2018/p1 and can be reproduced using the backtest the user attached.

#### System Information

Cloud.

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Note: there are a few futures missing to be completed in the MHDB, not only ES.
