### ISSUE TITLE
Automatically filter HasFundamentalData When Using Fine Filter

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#3462]
#### Expected Behavior
LEAN doesn't attempt to find fine data on disk when the coarse property "hasFundamentalData" is false.

#### Actual Behavior
LEAN attempts to read data slowing down backtest.

#### Potential Solution
Automatically add the hasFundamental data when the fine universe selection is included  

#### Reproducing the Problem
Fine filter backtest without specifying hasFundamental in coarse. 
 

#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
In a discussion with @simonsonjack he pointed out that some algorithms may want to be able to access ETFs in Coarse Fundamental Selector function (CFSf). So maybe it is not a good solution to automatically add the `HasFundamentalData` check automatically before CFSf is called. Instead, we could log (once) that CFSf is passing symbols of securities without that data and advise to read the docs.
`"Please do not include securities without fundamental data when performing fine fundamental selection. Check out the documentation for details."`
