### ISSUE TITLE
Estimize Custom Data Implementation Does Not Set Symbol Property

### ISSUE THREAD

**Issue by gsalaz98** [QuantConnect/Lean#3466]
#### Expected Behavior

We can access the symbol for a given piece of Estimize data
#### Actual Behavior

The symbol is blank (default)
#### Potential Solution

Set `Symbol = config.Symbol` in `Reader` calls 
#### Reproducing the Problem

```C#
public class EstimizeDataAlgorithm : QCAlgorithm
{
    public override void Initialize()
    {
        SetStartDate(2017, 1, 1);
        SetEndDate(2017, 12, 31);

        AddData<EstimizeRelease>("AAPL.R");
    }

    public void OnData(EstimizeRelease data)
    {
        Log($"{Time} - {data.Symbol.Value}");
    }
}
```

prints:

```
20190801 10:26:20.596 Trace:: Log: 1/31/2017 9:00:00 PM -
20190801 10:26:20.596 Trace:: Log: 5/2/2017 8:00:00 PM -
20190801 10:26:20.596 Trace:: Log: 8/1/2017 8:00:00 PM -
20190801 10:26:20.596 Trace:: Log: 11/2/2017 8:00:00 PM -
```
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Close by https://github.com/QuantConnect/Lean/pull/3467
