### ISSUE TITLE
Implement Brain Data Custom Data 

### ISSUE THREAD

**Issue by gsalaz98** [QuantConnect/Lean#3492]
#### Expected Behavior

We are able to use Brain Data custom data in LEAN
#### Actual Behavior

We are unable to use Brain Data custom data in LEAN
#### Potential Solution

Implement a data converter + required BaseData implementations
#### Reproducing the Problem

N/A
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Solved at https://github.com/QuantConnect/Lean.DataSource.BrainSentiment
