### ISSUE TITLE
Recently merged changes to TimeSliceFactory(?) introduce race condition

### ISSUE THREAD

**Issue by theGOTOguy** [QuantConnect/Lean#3494]
#### Expected Behavior
In the past, when I added custom data using, e.g.:

`AddData<Level2>(symbolStr, Resolution.Tick);`

the data was fed into my consolidators in order to produce aggregated ladder bars for my methods. 

#### Actual Behavior

I can confirm that in all cases, the data files are indeed being read.  However, it appears that there is a race whereby randomly my consolidators will never be fired.  While I can confirm that they exist in the SubscriptionManager in all cases, they randomly do not appear in the data packets inside TimeSliceFactory, and in these cases the entire backtest must be restarted.

I've also noticed that after merging this most recent pull request into my own repository that I need to add the following line to my algorithms:

`
SubscriptionManager.Add(
    typeof(Level2),
    TickType.Quote,
    ladder_product,
    Resolution.Tick,
    TimeZones.NewYork,
    TimeZones.NewYork,
    false,  // True or false, doesn't seem to affect anything.
    UniverseSettings.FillForward,
    UniverseSettings.ExtendedMarketHours,
    false,  // Actually has to be false, otherwise the ladder consolidators won't work.
    false);
`

otherwise, I get the error:

RuntimeError: Slice: System.ArgumentException: Type mismatch found between consolidator and symbol. Symbol: CL does not support input type: Level2. Supported types: ZipEntryName.

#### Potential Solution
Somehow, subscriptions are being added to the SubscriptionManager correctly but randomly never make it as far as the packet in the TimeSliceFactory, so that an ostensibly registered consolidator will not fire.  I'm hoping that the authors will have a better idea as to why I am encountering a race condition here, and be able to fix it.

#### Reproducing the Problem
Add a consolidator for a custom data type such as FxcmVolume, Quandl, or USEnergyInformation.

#### System Information
Ubuntu 18.04

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch -- Kind of.  My own build of Lean is mostly identical to the master branch, only adding additional data types, methods and consolidators.  I don't expect there to be anything functionally different.
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by theGOTOguy** [comment]
After further research, I now believe that this behavior is in fact tied to a change in Synchronizer.  In particular, the addition of TimeSlice TimePulse.

https://github.com/QuantConnect/Lean/blob/master/Engine/DataFeeds/Synchronizer.cs#L92

Since some of my indicators and their required consolidators are not added until we actually need the data (e.g., near the front-month or back-month roll,) then the indicator itself is created outside of Initialize().  I'm not entirely sure why doing so only works about half the time now, but it appears that this is the source of my race: sometimes, indicators added outside of Initialize() are never propagated into SubscriptionSynchronizer at all.

**Comment by Martin-Molinero** [comment]
Hi @theGOTOguy , thanks for the report.
Is there a basic algorithm that reproduces the issue you could share? 
I've sent you an invite to join QC slack, might be better for communicating, can find me as Martin-Molinero.

**Comment by theGOTOguy** [comment]
It's hard to create a basic algorithm that reproduces the issue, since as far as I know the QC repository doesn't actually contain consolidators for data other than "usual" market data.  So, without my own custom data and consolidators, this algorithm won't actually work for you, but this should give you an idea of how I'm causing the issue.  

`
// etc...
        const string symbolStr = Futures.Energies.CrudeOilWTI;
        Symbol ladder_product = QuantConnect.Symbol.Create(symbolStr, SecurityType.Base, Market.USA);
        Dictionary<DateTime, LadderIndicator> ladder_by_expiry;
        Dictionary<Symbol, DateTime> datetime_lookup;
        Dictionary<DateTime, Symbol> symbol_lookup;
        List<DateTime> expiries;

// etc...

        public override void Initialize() {

// etc...
            expiries = new List<DateTime>();
            datetime_lookup = new Dictionary<Symbol, DateTime>();
            symbol_lookup = new Dictionary<DateTime, Symbol>();
            ladder_by_expiry = new Dictionary<DateTime, LadderIndicator>();

            // This is necessary if Level2 data is needed.
            SubscriptionManager.Add(
                typeof(Level2),
                TickType.Quote,
                ladder_product,
                Resolution.Tick,
                TimeZones.NewYork,
                TimeZones.NewYork,
                false,  // For us, this actually IS normal QC data.
                false,  // Don't cache the data feed?  UniverseSettings.FillForward,
                UniverseSettings.ExtendedMarketHours,
                false,  // Actually has to be false, otherwise the ladder consolidators won't work.
                false);
            AddData<Level2>(symbolStr, Resolution.Tick);
        }

// etc.

        private DateTime lastDateTime = new DateTime(1900, 1, 1);
        public void OnData(Slice slice) {
            // Quickly exit if there are no future chains in this data set.
            // This will be the case if the Slice contains level 2 data only.
            if (slice.FutureChains.Count == 0) {
                return;
            }

            // Keep track of the day.
            if (slice.Time.Day != lastDateTime.Day) {
                Debug("Running on day " + slice.Time.ToString());
                lastDateTime = slice.Time;
            }

            foreach (var chain in slice.FutureChains) {
                foreach (var futuresContract in chain.Value) {
                    // Keep track of indicators.
                    if (!(expiries.Contains(futuresContract.Expiry))) {
                        expiries.Add(futuresContract.Expiry);
                        datetime_lookup[futuresContract.Symbol] = futuresContract.Expiry;
                        symbol_lookup[futuresContract.Expiry] = futuresContract.Symbol;
                    }
                    if (!(ladder_by_expiry.ContainsKey(futuresContract.Expiry))) {
                        // SimpleLadder lives in QCAlgorithm.Indicaotrs.cs, and creates a consolidator
                        // which collects the order book data into aggregates which are far
                        // more convenient to work with.
                        Debug("Adding SimpleLadder for contract expiring at " + futuresContract.Expiry.ToString());
                        ladder_by_expiry[futuresContract.Expiry] = (
                            SimpleLadder(ladder_product, TimeSpan.FromMinutes(1), futuresContract.Expiry, Resolution.Minute));
                    }
                }
            }

            // etc.
        }


`

**Comment by theGOTOguy** [comment]
Just wanted to give you an update on why this race is happening, what caused it, and how I fixed it.  Someone with better understanding of why this change was made should determine whether my use case should be supported or just documented.

The change that ultimately broke me was [this line from SubscriptionManager.cs](https://github.com/QuantConnect/Lean/blob/411c6456f54f08f362ed6103f49fc4c302156e1f/Common/Data/SubscriptionManager.cs#L43)

The initial interaction between that change was that I had to add my custom data to the SubscriptionManager before adding my consolidators.  That clears the error, but adds a race.
`SubscriptionManager.Add(
            typeof(Level2),
            TickType.Quote,
            ladder_product,
            Resolution.Tick,
            TimeZones.NewYork,
            TimeZones.NewYork,
            false,  // For us, this actually IS normal QC data.
            false,  // Don't cache the data feed?  UniverseSettings.FillForward,
            UniverseSettings.ExtendedMarketHours,
            false,  // Actually has to be false, otherwise the ladder consolidators won't work.
            false);
`

The race [actually lives in SubscriptionManager](https://github.com/QuantConnect/Lean/blob/411c6456f54f08f362ed6103f49fc4c302156e1f/Common/Data/SubscriptionManager.cs#L174).  

In particular:  when I then turned around and added my consolidators, then, there was a chance that they would be added to the "wrong" Level2 subscription (I'm not entirely clear on why there were now two of them, but AddData must add one that wasn't being recognized at first).  The solution could have been one of two things:  instead of returning after attaching to one of the subscriptions, attach to all possible ones, returning the error if none are found, or alternatively revert the change that filtered internal data from subscriptions above.

At any rate, I'll leave it to you to decide what the right solution is, if anything.  It's possible that my custom build of Lean is not your intended use case.  Thanks again for all your hard work.  There is no other publicly available backtesting system that is able to deal with the volume of data that I'm able to throw at Lean!

**Comment by Martin-Molinero** [comment]
Hi,
Thanks for the awesome analysis -
It seems to me that the underlying issue is that the custom data subscription is being added as internal? then when calling the consolidator it doesn't find the subscription. Directly calling `SubscriptionManager.Add` should not be required.

**Comment by theGOTOguy** [comment]
Yeah, that's certainly the root issue.

One idea, to protect those who may make the same mistake as me:  In SubscriptionManager,AddConsolidator, we throw an error if no valid subscriptions are found to attach to.  Would it be worth also throwing an error if multiple valid subscriptions are found to attach to, indicating to the user that some misconfiguration has occurred that will lead to a race in their code?

**Comment by Martin-Molinero** [comment]
>  the underlying issue is that the custom data subscription is being added as internal

Can't seem to reproduce this - is there an example algorithm you could provide where this is happening?

**Comment by Martin-Molinero** [comment]
No reply, so closing for now.
