### ISSUE TITLE
Create TradeBars Consolidator (Multiple Symbol Indicators)

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#35]
Create a consolidator which can pipe multiple data symbols into an indicator. It would send a IDictionary<string, BaseData> into the indicator which would support custom and tradebar data.

(TradeBars object is a IDictionary<string, TradeBar> which could extend from the generic base data version)

**Comment by mchandschuh** [comment]
The hard part here is that this consolidator will need to receive 'time' updates to know when to emit data since you can never be 100% sure you've received updates for all symbols.

**Comment by jaredbroad** [comment]
Closing as 3 ticket concentrated here: 
https://github.com/QuantConnect/Lean/issues/83
