### ISSUE TITLE
Inconsistent Historical Data Request Result

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#3519]
#### Expected Behavior
Historical data request reflects the date range. 

#### Actual Behavior
For some date ranges, the history request turns out to be empty.

#### Reproducing the Problem
```csharp
namespace QuantConnect.Algorithm.CSharp
{
    public class CalibratedResistanceEngine : QCAlgorithm
    {
        public override void Initialize()
        {
            SetStartDate(2019, 2, 18);

            AddEquity("AA", Resolution.Minute);

            var startDate = new DateTime(2016, 10, 1);

            var prices = History(Securities.Keys, startDate, new DateTime(2016, 11, 1), Resolution.Daily);
            Log($"First: {prices.Count()}");

            var pricex = History(Securities.Keys, startDate, new DateTime(2016, 10, 31), Resolution.Daily);
	    Log($"Second: {pricex.Count()}");
        }

        public override void OnData(Slice data) => Quit();
    }
}
```
Prints out:
```
2019-02-18 00:00:00 First: 7
2019-02-18 00:00:00 Second: 0
```
where it should be
```
2019-02-18 00:00:00 First: 21
2019-02-18 00:00:00 Second: 20
```
#### System Information
QuantConnect cloud. The expected result is found in local backtest mode in a linux virtual machine. 

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Alcoa split into two companies in November 2016.
The original Alcoa Inc (AA) became Arconic Inc. (ARNC) and then Arconic Inc. (ARNC) spun off the new Alcoa Corporation (AA). So the first date for `AA` is 2016-11-1.
Why are we getting 7 data points for the first history request? We are not checking the data against the map file first date, that allows these data points to pass through, this seems like the issue here.
