### ISSUE TITLE
Add Library Scikit-Optimize

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#3531]
Library request for https://scikit-optimize.github.io/ 

#### Potential Solution
Review and build the scikit into the docker foundation

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/3703
