### ISSUE TITLE
Visual Studio Plugin for macOS

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#3538]
#### Expected Behavior
Be able to use QuantConnect VS Plugin in macOS

#### Actual Behavior
Not supported

#### Reproducing the Problem
Follow the [Backtesting from Visual Studio Tutorial](https://www.quantconnect.com/tutorials/open-source/backtesting-from-visual-studio).

#### System Information
macOS

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closing since `Visual Studio Plugin` is no longer supported and has been replaced by https://www.quantconnect.com/skylight

**Comment by yul** [comment]
Err, how does it work? Does it work at all on Mac? All I can do is to create a new project without any files in it. There are no docs apparently either, is there a source for some more information about Skylight?

**Comment by Martin-Molinero** [comment]
Hey @yul, it does support Mac, you can check out a demo video here https://youtu.be/OOFZqZdPHCM, we are working hard on adding new features, you can see the road map at https://www.quantconnect.com/skylight
