### ISSUE TITLE
Implement AUM Capacity Estimate Calculation

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#3539]
#### Expected Behavior
Calculate an estimate of the capacity of the strategy backtest/live trade. This will provide funds with an understanding of the maximum dollar allocation they can make to the strategy to maximize its return potential without moving the market.

#### Actual Behavior
No estimate available

#### Potential Solution
Capacity will be calculated using the volume capacity per symbol per trade each day. At the end of the day, the symbol capacity will be calculated as the minimum of all individual trade capacities for the specific symbol. Then, the portfolio capacity for the day will be the sum of all individual symbol capacities. The final AUM Capacity will be displayed as the average of all of the daily capacities calculated).

Please see the excel sheet for a detailed calculation of this in various circumstances.
[Alpha Capacity Calculations.xlsx](https://github.com/QuantConnect/Lean/files/3552416/Alpha.Capacity.Calculations.xlsx)

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed https://github.com/QuantConnect/Lean/pull/5351
