### ISSUE TITLE
Unable to Import Python Module in Algorithms Frameworks Example

### ISSUE THREAD

**Issue by MuellerDave** [QuantConnect/Lean#3551]
Expected Behaviour: Successfully running a backtest that ranks every pair combination by its Pearson correlation and trades the pair with the highest correlation. 

Actual Behaviour: Returns a algorithm.initialze error and says "unable to import python module"

Reproducing the problem: Run the exact example code at this link https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/PearsonCorrelationPairsTradingAlphaModelFrameworkAlgorithm.py

Note: This problem persists with all framework example algorithms

#### Checklist

- [Y ] I have completely filled out this template
- [ Y] I have confirmed that this issue exists on the current `master` branch
- [Y ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ Y] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hi @MuellerDave !
Just tested `PearsonCorrelationPairsTradingAlphaModelFrameworkAlgorithm.py` locally and it worked correctly - Have you followed the python setup steps? https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/readme.md - If the issue persists we would need some more information: setup information (OS, mono version, python version, etc) and the error in detail (log file, snapshot)

**Comment by MuellerDave** [comment]
Hi Martin!

I am not running the algorithm locally; it is being run online in the QuantConnect IDE. How does that affect it?

Dave

**Comment by Martin-Molinero** [comment]
Tested creating an empty python project and pasting the `PearsonCorrelationPairsTradingAlphaModelFrameworkAlgorithm.py` code into `main.py` and it successfully finished. 
For _Cloud_ support please open a support ticket or post in the forums sharing the algorithm with the issue. These GH issues reserved for Lean open source issues.
