### ISSUE TITLE
Add hmmlearn as supported library

### ISSUE THREAD

**Issue by Zheng-Zuo** [QuantConnect/Lean#3560]
#### Expected Behavior

from hmmlearn import GaussianHMM

#### Actual Behavior

ModuleNotFoundError: No module named 'hmmlearn'

#### Potential Solution

Add hmmlearn as a supported library,
It was originally a package in an older version of sklearn, and then went independent, GaussianHMM is very useful for regime detection,
https://hmmlearn.readthedocs.io/en/latest/tutorial.html

#### Checklist

- [ √] I have completely filled out this template
- [√] I have confirmed that this issue exists on the current `master` branch
- [ √] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Hi @Zheng-Zuo ! `hmmlearn` has been added, current version at `0.2.2`.
