### ISSUE TITLE
Quandl data fails with different column names

### ISSUE THREAD

**Issue by multidis** [QuantConnect/Lean#3562]
#### Expected Behavior
Quandl data is read properly for different dataset codes.

#### Actual Behavior
Data reading fails when OHLC column names have different names. Error example:

> Error invoking BITFINEX/XRPBTC data reader. Line: 2018-06-22,8.087e-05,7.852e-05,7.9725e-05,7.971e-05,7.97e-05,7.975e-05,7871763.9450174 Error: Property with name 'close' does not exist. Properties: Time, Symbol, Value high, low, mid, last, bid, ask, volume

#### Potential Solution
Include column name inference from common names used by Quandl, or provide a way + document how to specify the columns to be used instead of standard OHLC names.

#### Reproducing the Problem
`AddData<Quandl>("BITFINEX/XRPBTC", Resolution.Daily, DateTimeZone.Utc, true, 3.0m);`

#### System Information
QC Cloud.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment]
Hi @multidis,

Lean already supports this feature. We need to define a class that derives from `Quandl` class and define the `ValueColumnName` through the constructor:
```csharp
/// <summary>
/// Custom quandl data type for setting customized value column name. Value column is used for the primary trading calculations and charting.
/// </summary>
public class QuandlFuture : Quandl
{
    /// <summary>
    /// Initializes a new instance of the <see cref="QuandlFuture"/> class.
    /// </summary>
    public QuandlFuture()
        : base(valueColumnName: "Settle")
    {
    }
}
```
This is not explictly explained in the docs, but it has a link to the example: [QuandlImporterAlgorithm.cs](https://github.com/QuantConnect/Lean/blob/master/Algorithm.CSharp/QuandlImporterAlgorithm.cs)

**Comment by multidis** [comment]
Yes this works, thank you Alex for pointing out.
