### ISSUE TITLE
Warm Up Security Added By Universe Selection

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#3590]
#### Expected Behavior
Be able to place orders in `OnSecuritiesChanged`.

#### Actual Behavior
If the algorithm tries to place orders in `OnSecuritiesChanged` for securities that entered in the universe for the first time, they will fail because the price is zero.

#### Potential Solution
1. Enact `SecurityInitializer` with a History request.
2. Use CoarseFundamental data in [UniverseSelection.cs#L291](https://github.com/QuantConnect/Lean/blob/master/Engine/DataFeeds/UniverseSelection.cs#L291):
```csharp
CoarseFundamental data;
if (coarseData.TryGetValue(symbol, out data))
{
    security.Cache.AddData(
        new Tick()
        {
            Symbol = symbol,
            EndTime = data.EndTime,
            Quantity = data.Volume,
            TickType = TickType.Trade,
            Value = universe.UniverseSettings.DataNormalizationMode == DataNormalizationMode.Raw
                ? data.Price
                : data.AdjustedPrice
        }
    );
}
``` 
#### Reproducing the Problem
```csharp
namespace QuantConnect.Algorithm.CSharp {
    public class UniverseSelectionDefinitionsAlgorithm : QCAlgorithm {
        public override void Initialize() {
            SetStartDate(2013, 10, 07);
            SetEndDate(2013, 10, 11);

            AddUniverse(Universe.DollarVolume.Top(5));
        }

        public override void OnSecuritiesChanged(SecurityChanges changes) {
            foreach (var security in changes.RemovedSecurities) {
                if (security.Invested)
                    Liquidate(security.Symbol);
            }

            foreach (var security in changes.AddedSecurities)
                MarketOrder(security.Symbol, 10);
        }
    }
}
```
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
This is now possible specifying the security initializer `SetSecurityInitializer(new BrokerageModelSecurityInitializer(BrokerageModel, new FuncSecuritySeeder(GetLastKnownPrices)));` see https://github.com/QuantConnect/Lean/pull/5923
