### ISSUE TITLE
Enable non-US account currency in Live mode

### ISSUE THREAD

**Issue by Adalyat** [QuantConnect/Lean#3593]
#### Expected Behavior

We want to use non-USD account currency. Blocks #2004

#### Actual Behavior

Using non-USD account currency is not allowed and throws NotImplementedException. 

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Adalyat** [comment]
moved from: https://github.com/QuantConnect/Lean/pull/3511#discussion_r315920619

**Comment by jaredbroad** [comment]
Duplicate of #110
