### ISSUE TITLE
Lean fails to build on OSX

### ISSUE THREAD

**Issue by tactevo** [QuantConnect/Lean#3606]
#### Expected Behavior
The QuantConnect.Lean solution builds on OSX.

#### Actual Behavior
The QuantConnect.Jupyter project fails to build on OSX because as part of the build, the file `Python.Runtime.dll` is attempted to be copied from the solution local NuGet packages directory to the output directory.   The file can't be copied because the wrong version is specified in `QuantConnect.Jupyter.csproj`.  This behavior only happens when building on OSX because `QuantConnect.Jupyter.csproj` specifies the following condition:

`<When Condition="$(IsOSX) AND '$(ForceLinuxBuild)' != 'true'">`

#### Potential Solution
Fix the `Python.Runtime.dll` version in `QuantConnect.Jupyter.csproj`.

It is currently specified as:

`<Content Include="..\packages\QuantConnect.pythonnet.1.0.5.23\lib\osx\jupyter\Python.Runtime.dll">
          <Link>jupyter\Python.Runtime.dll</Link>
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>`

but should be:

`<Content Include="..\packages\QuantConnect.pythonnet.1.0.5.24\lib\osx\jupyter\Python.Runtime.dll">
          <Link>jupyter\Python.Runtime.dll</Link>
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>`

#### Reproducing the Problem

Attempt to build the QuantConnect.Lean solution on OSX using Visual Studio for Mac or Jetbrains Rider.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment]
Hi, @tactevo .
It looks like you were not working with the latest `master` since the current `pythonnet` version is `1.0.5.25` (see #3598).
