### ISSUE TITLE
LiveTradingResultHandler holdings dictionary duplicate keys

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#3609]
#### Expected Behavior

- LiveTradingResultHandler holdings dictionary should never add twice the same key
#### Actual Behavior

- The `LiveTradingResultHandler` is trying to add twice the same key at https://github.com/QuantConnect/Lean/blob/master/Engine/Results/LiveTradingResultHandler.cs#L244 because custom data types which required mapping and hold an underlying symbol will have the same `Security.Symbol.Value` as the underlying Symbol instance - note this is a feature, not a bug, since the custom data type current `Symbol.Value` is used to determine the source path and updated by mapping
#### Potential Solution

- The holdings dictionary key should probably not use `Symbol.Value` as key since its not unique and use `Symbol.ID.ToString()` instead (as currently being used for pandas data frame key, for Py history requests) or maybe `Symbol.ID.Symbol`-> note this will probably require some frontend changes
    - option 1 unique `Symbol.ID.ToString()`: `"SPY R735QTJ8XC9X"` `"SPY.MyCrazyCustomData R735QTJ8XC9W"`
    - option 2: `Symbol.ID.Symbol`: `"SPY"` `"SPY.MyCrazyCustomData"`
    - master: `"SPY"` `"SPY"`
#### Reproducing the Problem

- Live trading `CustomDataAddDataRegressionAlgorithm`
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
- Use symbol hash
 - Use 2022 web service hash-ticker conversion in frontend
