### ISSUE TITLE
Missing files errors spamming log

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#3611]
#### Expected Behavior

- Missing files errors are informative and not cause log flood
#### Actual Behavior

- In some cases, custom data types, do not have a specific ticker (at all) causing Lean to flood the log with missing file errors and not being catched by the logging flood protection due to having the file name with a date
- Some data sources, like custom data types, are sparse and can have multiple days without a data file, which also causes a log flood
#### Potential Solution

N/A
#### Reproducing the Problem

N/A
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by spmuppar** [comment]
Having same issue here, not sure why the "AddEquity" can't write files into the Data directory or something...

20190926 17:32:18.660 ERROR:: DefaultDataProvider.Fetch(): The specified file was not found: ../../../Data/equit
y/usa/second/spy/20141008_trade.zip
20190926 17:32:18.660 ERROR:: DefaultDataProvider.Fetch(): The specified file was not found: ../../../Data/equit
y/usa/second/spy/20141009_trade.zip
20190926 17:32:18.661 ERROR:: DefaultDataProvider.Fetch(): The specified file was not found: ../../../Data/equit
y/usa/second/spy/20141010_trade.zip

**Comment by Martin-Molinero** [comment]
Closing in favor of https://github.com/QuantConnect/Lean/issues/3618
