### ISSUE TITLE
Index Options Support

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#3616]
#### Expected Behavior

Index options available e.g. SPX

#### Actual Behavior
Only equity options available. e.g. SPY

#### Potential Solution
Implement index options.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by memoryfraction** [comment]
Any update about this feature?
I would like to do some backtests on the RUT option.

**Comment by Sharma-Rajat** [comment]
any updates here?

**Comment by Sharma-Rajat** [comment]
@jaredbroad as I understand this is still not supported. Would it be possible to use custom data provided by https://docs.orats.io/data-api-guide/definitions.html#strikes to use in Quantconnect to run options backtesting on?

**Comment by Sharma-Rajat** [comment]
I spoke to @jaredbroad earlier today. It seems they will most likely crowd source the data and will be looking for contributors. **I highly recommend everyone watching this thread to contribute. We would be doing a great service to the community.**

**Comment by ikamanu** [comment]
I'm following up here as I need this functionality well. 

I joined under the mistaken impression that I could backtest my intraday SPX strategies.  

This is an unfortunate disappointment. 

@jaredbroad and team: please let us know how we can help.

**Comment by nkabram** [comment]
Any update on this feature? I'd also like to test index equities and options related to them.
