### ISSUE TITLE
Auto-remove custom derivative data when underlying data removed

### ISSUE THREAD

**Issue by mchandschuh** [QuantConnect/Lean#3619]
#### Expected Behavior

Alternative derivative data is removed from the algorithm when it's underlying data is removed. For example, if we have `SPY` and `SPY.PsychSignal` then removing `SPY` should also remove `SPY.PsychSignal`

#### Actual Behavior

Alternative derivative data remains in algorithm and is causing OOM issues.

#### Potential Solution

Remove alternative derivative data (potentially adding a flag to `BaseData.Options` indicating this behavior) when it's underlying data is removed.

**NOTE:** For now we're just applying this to custom data but we should also investigate doing this for _all_ securities w/ underlying (options/etc) as they depend on their underlying as well. Options w/out the underlying equity data is useless for us since our filters require the underlying price data, etc...

#### Reproducing the Problem

Run alternative derivative data such as PsychSignal and remove it's parent (underlying) subscription and observe that PsychSignal is not removed.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
- Closing as now we do not require the underlying to add the alternative data. Alternative data can be freely added independent of underlying.
