### ISSUE TITLE
Only add data if available, starting enumerators via map file start dates

### ISSUE THREAD

**Issue by mchandschuh** [QuantConnect/Lean#3621]
#### Expected Behavior

Enumerator stacks shouldn't start looking for data until the data's start date.

#### Actual Behavior

We start looking for data immediately, regardless of the enumerator start date.

#### Potential Solution

When creating the enumerator stack, check the map file and adjust the start date accordingly. We may want to consider emitting a message notifying the user that we've adjusted the start date to coincide with the map file start date. If no map file available, don't modify start date.

#### Reproducing the Problem

Run an algo starting far in the past and select data for a symbol that doesn't start for a few years. You'll get tons of messages about data not found even though we _know_ data shouldn't be found as per map file start date.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by captholley** [comment]
Any progress on this issue? I am experiencing the same.

**Comment by Martin-Molinero** [comment]
Addressed by https://github.com/QuantConnect/Lean/pull/3770
