### ISSUE TITLE
Consolidate logging to reduce thread contention on single log file

### ISSUE THREAD

**Issue by mchandschuh** [QuantConnect/Lean#3622]
#### Expected Behavior

Log spamming shouldn't block threads.

#### Actual Behavior

Log spamming causes lots of thread contention as threads wait for their turn to write _and flush_ to a single log file.

#### Potential Solution

Queue up log messages and have a separate thread be responsible for writing them. We should also consolidate the messages to provide for less write operations in total.

#### Reproducing the Problem

Run and algorithm lots of sparse data sets and observe the slower than expected run time due to log file contention from missing data log spam.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
We will close this for now as `WillNoFix` since the benefit for Lean logging usage does not overcome the problems associated with runtime explosions and the potential loss of those precious last logs.
