### ISSUE TITLE
Tick time precision

### ISSUE THREAD

**Issue by IlshatGaripov** [QuantConnect/Lean#3625]
few questions realted to tick object timestamp precion ; would appreciate if anyone could help me to sort the things out. 

1) First thing I noticed is that Lean reads forex data as DateTime.Ticks count:
https://github.com/QuantConnect/Lean/blob/master/Common/Data/Market/Tick.cs#L251
But stores them millisecond truncated:
https://github.com/QuantConnect/Lean/blob/master/Common/Util/LeanData.cs#L173

2) Wondering is it helpful if lean stored all tick data as DateTime.Ticks count for the best precision that .net can provide? There are data vendors that do return equity trade (tick) data nonoseconds timestamped - which is 100 times more accurate than DateTime.Tick.. not to mention milliseconds

#### Potential Solution
Update Tick object and lead data readers.. and all the csv files that store tick data to represent datetime in 10^-7 second precision (DateTime.Tick)

#### Checklist

- [X ] I have completely filled out this template
- [ ] I have confirmed that this issue exists on the current `master` branch
- [ ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

**Comment by mchandschuh** [comment]
I'm pretty sure the existing format is milliseconds as the time of day and I'm pretty sure it supports fractional milliseconds, meaning it already supports nanosecond precision. Just write the value in decimalized milliseconds.

Have you tried this?

**Comment by IlshatGaripov** [comment]
I checked again now. It's all fine as concerned to the writings to the file. But when ticks are read back there is an issue. Because it uses everywhere ```Date.AddMilliseconds``` which truncates a precision. Here is a method decompiled:

```
/// <summary>Returns a new <see cref="T:System.DateTime" /> that adds the specified number of milliseconds to the value of this instance.</summary>
/// <param name="value">A number of whole and fractional milliseconds. The <paramref name="value" /> parameter can be negative or positive. Note that this value is rounded to the nearest integer.</param>
/// <returns>An object whose value is the sum of the date and time represented by this instance and the number of milliseconds represented by <paramref name="value" />.</returns>
/// <exception cref="T:System.ArgumentOutOfRangeException">The resulting <see cref="T:System.DateTime" /> is less than <see cref="F:System.DateTime.MinValue" /> or greater than <see cref="F:System.DateTime.MaxValue" />. </exception>
    [__DynamicallyInvokable]
    public DateTime AddMilliseconds(double value)
    {
      return this.Add(value, 1);
    }
```

Its documentation says ```Note that this value is rounded to the nearest integer.``` 

Same discussion is here:
https://stackoverflow.com/questions/2690043/why-does-addmilliseconds-round-the-double-parameter
And suggested solution around this is to use ```AddTicks(values * 10000)``` instead..
