### ISSUE TITLE
History by number of bars and end time

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [QuantConnect/Lean#3662]
Please allow for requesting history by number of bars leading up to an end time - and conversely, by number of bars past a start time.

Currently I can either specify number of bars (which changes the dataset when testing over time), or by timestamp (which is hard to determine accurately within my algo). My algo knows how many bars it needs, but determining the timestamps is quirky at best considering I need to account for holidays, weekends, tradable hours per day, etc. I'd like to be efficient in making history requests - at the moment the best option is to make a very large history request every time, and truncate based on number of bars I need.

**Comment by jaredbroad** [comment]
Hi @JakeTheSnake3p0 you can do this with: 
https://github.com/QuantConnect/Lean/blob/master/Algorithm/QCAlgorithm.History.cs#L571
https://github.com/QuantConnect/Lean/blob/master/Algorithm/QCAlgorithm.History.cs#L596

then pass the history request objects into:
https://github.com/QuantConnect/Lean/blob/master/Algorithm/QCAlgorithm.History.cs#L471

Please make a PR to make these methods public if you can.
