### ISSUE TITLE
Create CalculateOrderQuantity Equivalent for Limit, StopLimit and StopMarket

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#3675]
#### Expected Behavior
Have a helper method that computes the quantity of a `LimitOrder`, `StopLimitOrder` and `StopMarketOrder` given a percentage target.  

#### Actual Behavior
Only `CalculateOrderQuantity` for `MarketOrder` is available.

#### Potential Solution
Implement it.

#### Reproducing the Problem
N/A 

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
From private chat -- full use case was to swap the fee model used in the calculate order quantity. Closing as not sufficiently generally applicable. Specific cases should be implemented as a method in the algorithm
