### ISSUE TITLE
nuget and msbuild errors when creating building the Dockerfile.

### ISSUE THREAD

**Issue by randomthought** [QuantConnect/Lean#3711]
#### Expected Behavior

Build without any nuget or msbuild issue.

#### Actual Behavior

I get the following error
```
The 'Newtonsoft.Json 10.0.3' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.60717.93'.
'QLNet' already has a dependency defined for 'System.Reflection.Emit.Lightweight'.
The 'System.Net.Http 4.3.3' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.60717.93'.
The 'Microsoft.CSharp 4.6.0' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.60717.93'.
The 'System.Reflection.Emit 4.3.0' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.60717.93'.
The 'System.Reflection.Emit.Lightweight 4.3.0' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.60717.93'.
The 'System.ValueTuple 4.4.0' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.60717.93'.
```

After upgrading the nuget version, I get the following msbuild error
```
MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.
```

#### Potential Solution

Downloading latest nuget and specif
#### Reproducing the Problem

Upgrade the Nuget version then specify the solutions file when calling msbuild.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by laur89** [comment]
Which dockerfile -backed container did this error reproduce?
Running `msbuild` in latest foundation image reports

```MSBuild auto-detection: using msbuild version '14.0' from '/usr/lib/mono/xbuild/14.0/bin'.    ```

**Comment by randomthought** [comment]
Apologies, I should have been more clear in my description. This error happens when yo un-comment Option 1 in the `Dockerfile`. I have provided a fix below but I am not sure why it's failing the travis-cl tests. I am not doing any modifications to the source code :(

https://github.com/QuantConnect/Lean/pull/3712/files
