### ISSUE TITLE
Smart Insider Transactions History Requests Failing

### ISSUE THREAD

**Issue by gsalaz98** [QuantConnect/Lean#3719]
#### Expected Behavior

We are able to use the History API to request historical SmartInsiderTransaction data
#### Actual Behavior

PandasData throws the exception:

```
PandasData.ctor(): More than one 'price' member was found in 'SmartInsiderTransaction' class.
```
#### Potential Solution

Rename the property
#### Reproducing the Problem

```
from QuantConnect.Data.Custom.SmartInsider import *

class HorizontalTransdimensionalProcessor(QCAlgorithm):

    def Initialize(self):
        self.SetStartDate(2019, 4, 13)
        self.SetEndDate(2019, 4, 15)
        self.SetCash(100000)
        
        ibm = self.AddEquity("IBM", Resolution.Minute).Symbol
        si = self.AddData(SmartInsiderTransaction, ibm).Symbol
        history = self.History(SmartInsiderTransaction, si, 60, Resolution.Daily)

    def OnData(self, data):
        pass
```
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/3729
