### ISSUE TITLE
Add Extensions to Short Cut Composite Indicators

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#372]
Composite indicators provide a nice way of chaining indicators but they can be confusing to use sometimes. A couple of well written extension methods would help cover 90% of use cases: specifically:

```
//This is current operation:
_adx = ADX(_symbol, 30);
_smaADX = new SimpleMovingAverage(_symbol + " SMA of ADX",10).Of(_adx);

//Could be re-written with extensions to be:
_adx = ADX(_symbol, 30).SMA(10);
```

**Comment by mellertson** [comment]
Hi Jared, quick question.  It seems to me like the last line:

    `_adx = ADX(_symbol, 30).SMA(10);`

should be returning an SMA object instead of an ADX object, because the end result of the first three lines seems to be an SMA of the ADX data.  Is my understanding correct?

**Comment by jaredbroad** [comment]
Yes exactly! The resulting obect should be the SMA of the ADX. It was
intended to wrap the .Of operator into something more intuative.

**Comment by mellertson** [comment]
Great, thanks!

**Comment by jaredbroad** [comment]
Completed by c47eb47
