### ISSUE TITLE
Invalid AddUniverse Method Call

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#3727]
#### Expected Behavior
Do not allow `AddUniverse` be called before `SetStartDate`.

#### Actual Behavior
We can call `AddUniverse` before `SetStartDate`. It leads the algorithm to run out-of-memory.

#### Potential Solution
Throw exception when `AddUniverse` before `SetStartDate`.

#### Reproducing the Problem
```csharp
namespace QuantConnect.Algorithm.CSharp {
    public class CoarseFineFundamentalRegressionAlgorithm : QCAlgorithm {
        private Symbol _msft = QuantConnect.Symbol.Create("MSFT", SecurityType.Equity, Market.USA);

        public override void Initialize() {
            UniverseSettings.Resolution = Resolution.Daily;
            AddUniverse(coarse => new[] { _msft }, fine => new[] { _msft });

            SetStartDate(2019, 03, 01);
            SetEndDate(2019, 04, 01);
            SetCash(50000);
        }
    }
}
```
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by prasadsom** [comment]
Hi,

Had a quick look. By default start date is set at start of 1998. And that seems to be reason, it's running out of memory. So possibly, talking about here not having a default value. Then check for start date can be made. Because start of 1998 is still valid date.

**Comment by prasadsom** [comment]
@AlexCatarino , do you have any further comment. As mentioned earlier, even if `SetStartDate` is not called, it does use default value.

**Comment by Martin-Molinero** [comment]
Hi ! This issue has been fixed by https://github.com/QuantConnect/Lean/pull/3991.
