### ISSUE TITLE
[Idea] Separate slippage models depending on order type

### ISSUE THREAD

**Issue by worthy7** [QuantConnect/Lean#3730]
I'm reading through a very interesting book on building trading algorithms, and it makes a very good point about how different types of orders (limit, stop, market) will have different types of slippage.

Perhaps this is something that should be built into lean as an option when choosing slippage model?

**Comment by jaredbroad** [comment]
Thanks for the suggestion @worthy7; is there any reason it can't be done with the current slippage models? They provide the order type information. 
`public decimal GetSlippageApproximation(Security asset, Order order)`

**Comment by worthy7** [comment]
I guess not, I haven't used the models in a while, never noticed it's there already!
