### ISSUE TITLE
Value Consolidator

### ISSUE THREAD

**Issue by globophobe** [QuantConnect/Lean#3754]
#### Expected Behavior

Value Consolidator, for Volume and Dollar Bars as described in the book Advances in Financial Machine Learning, and as implemented by mlfinlab:

https://www.quantconnect.com/forum/discussion/5853/mlfinlab-python-package-released-advances-in-financial-machine-learning/ 

#### Actual Behavior

Discussion forum replies suggest RenkoConsolidator. However, RenkoBars do not accumulate value of previous bars.

Wanted:

```
bars = []
data = [1, 2, 3, 4, 5]
total = 0
bar = { 'open': 0, 'close': 0, 'high': 0, 'low': 0}
for d in data:
    total += d
    if total < threshold:
        if bar['open'] == 0:
            bar['open'] = d
        ...
    else:
        bar['close'] == d
        bars.append(bar)
        total = 0
        bar =  { 'open': 0, 'close': 0, 'high': 0, 'low': 0}
```

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by adriantorrie** [comment]
Also mentioned in forums here:
https://www.quantconnect.com/forum/discussion/7313/tick-volume-and-dollar-bars
