### ISSUE TITLE
Custom data Resolution and FillForwarding

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#3772]
#### Expected Behavior

- Custom data does not trigger unnecessary fill forwarding
#### Actual Behavior

- When running the algorithm provided bellow, equity data is filled forward since the custom data resolution is Minute, the default value, but in this case, CBOE is a daily data source, so this causes a significant performance overhead which could be avoided
#### Potential Solution

- Data types could be aware of their supported data resolutions, and Lean could throw an exception if the requested `Resolution` isn't available. This could be useful for `Options` Daily resolution too. Similar pattern as `IsSparseData/RequiresMapping`
- Work around is to set the right resolution for custom data
#### Reproducing the Problem

```
    public class BasicTemplateBenchmark : QCAlgorithm
    {
        public override void Initialize()
        {
            SetStartDate(2000, 01, 01);
            SetEndDate(2019, 01, 01);
            AddEquity("SPY", Resolution.Daily);
            AddData<CBOE>("VIX");
        }

        public override void OnData(Slice data)
        {
            if (!Portfolio.Invested)
            {
                SetHoldings("SPY", 1);
                Debug("Purchased Stock");
            }
        }
    }
```
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Per discussion -- to better support multiple custom resolutions
`List<Resolution> SupportedResolutions`
along with testing making `Resolution` nullable which defaults to `DefaultResolution`

Then a beautiful message like:
"Sorry `Minute` is not a supported resolution for `USEnergy`. Please change your `AddData` to use one of the supported resolutions (`Daily`)." which throws if one of the requested resolutions is not provided.
