### ISSUE TITLE
AOT Compilation Results in Approx. 10-20% Speed-up For C#

### ISSUE THREAD

**Issue by gsalaz98** [QuantConnect/Lean#3783]
#### Expected Behavior

LEAN runs as fast as possible
#### Actual Behavior

LEAN isn't using AOT compilation. Naive tests show about a 10-20% performance improvement using full AOT compilation for standard library, mscorlib, and dependencies of LEAN (tested under Ubuntu 18.04 VM)

This might also have the added side-benefit of improved startup time and lower memory usage, but I haven't tested that yet.

Python has not been tested either. Investigate to see if performance improvements apply there too.

Sample benchmark ran was `BasicTemplateBenchmark` with resolution set to `Resolution.Tick`
#### Potential Solution

Add to DockerFile (or something similar):

```bash
sudo mono --aot=full -O=all /usr/lib/mono/4.5/mscorlib.dll

for i in /usr/lib/mono/gac/*/*/*.dll; do sudo mono --aot=full -O=all $i; done

# after MSBuild step
cd Launcher/bin/Release
mono --aot=full -O=all *.dll
mono --aot=full -O=all *.exe

# Run LEAN
mono QuantConnect.Lean.Launcher.exe
```

The `after MSBuild step` commands are prone to failing, but should nonetheless still be able to complete.
#### Reproducing the Problem

N/A
#### System Information

Linux using Mono

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment]
I made a quick test by adding these lines in the `DockerFileLeanFoundation` after `mono` installation:
```
# Apply full AOT compilation
RUN mono --aot=full -O=all /usr/lib/mono/4.5/mscorlib.dll
RUN for i in /usr/lib/mono/gac/*/*/*.dll; do mono --aot=full -O=all $i; done
```
then, without the "after MSBuild step", I was able to run the `RegressionTests`.
I tried without that step because I got an error with:
```
mono --aot=full -O=all *.dll
```
