### ISSUE TITLE
[Crypto] Implement CCXT API and connect to 130+ exchanges 🚀

### ISSUE THREAD

**Issue by omidkrad** [QuantConnect/Lean#3793]
[CCXT (CryptoCurrency eXchange Trading Library)](https://github.com/ccxt/ccxt) provides a unified trading API to 130+ cryptocurrency exchanges. If we can add it as a broker to QuantConnect then we can use all those exchanges.

CCXT is implemented in JavaScript and transpiled to Phyton and PHP. It does not have a C# interface. I can think of two ways to integrate CCXT with Lean:

- Use [Edge.js](https://github.com/tjanczuk/edge) to run CCXT in-process with the C# code.
- Use [ccxt-rest](https://ccxt-rest.io/) to run CCXT as a REST API and connect to that.

It may also be possible to connect through the Python API, but I don't have much opinion there.

**Comment by volemont** [comment]
CCXT Pro will support WebSockets, see https://github.com/ccxt/ccxt/issues/6332 and https://github.com/ccxt/ccxt/issues/56#issuecomment-507290536

>We will release CCXT Pro on the 1st of March 2020.

Source: https://github.com/ccxt/ccxt/issues/6332#issuecomment-586626802

**Comment by dwittevronghel** [comment]
Dear,

Is there a manual of how to implement all this stuff?

Greetings,
David

**Comment by omidkrad** [comment]
@dwittevronghel there is a [Manual](https://github.com/ccxt/ccxt/wiki/ccxt.pro) for CCXT API, and there is [QuantConnect Development Guide](https://www.quantconnect.com/tutorials/open-source/brokerage-development-guide).

**Comment by Martin-Molinero** [comment]
Hey! We started down the integration path with CCXT, can see branch at https://github.com/QuantConnect/Lean/tree/ccxt-pro-integration , but hit some limitations in the integration scope/support and decided it wouldn't be worth the work around. Instead for now we've decided to focus on the major crypto exchanges and integrate them natively as Lean brokerages plugins directly
