### ISSUE TITLE
Refactoring AlgoSeekFuturesConverter.cs 

### ISSUE THREAD

**Issue by prasadsom** [QuantConnect/Lean#3795]
#### Expected Behavior
While reading issue #3788 realized function GetFilesInRawFolder erroneous and unnecessary. It basically try to run commands by launching separate process.  I was going to comment on original issue, but PR is merged before I got a chance

#### Actual Behavior
Class has  `DirectoryInfo` member variable `_remote` which is used in `GetFilesInRawFolder` to create full path. This function lanches separate process calling dir on windows and ls on linux systems.

#### Potential Solution
`_remote` can be used to iterate through directory it pointing to . No need of `GetFilesInRawFolder` 
#### Reproducing the Problem
NA
#### System Information
NA
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [ ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the

**Comment by Martin-Molinero** [comment]
Closing this issue for now, current implementation is required to support network share, see https://github.com/QuantConnect/Lean/pull/3796#issuecomment-549340905
