### ISSUE TITLE
[BUG] Indicators & Candlesticks Patterns Gets Updated 1 Candle Late

### ISSUE THREAD

**Issue by HeroKato-Dev** [QuantConnect/Lean#3840]
#### Expected Behavior
Expected behaviour should be that whenever a QuoteBar gets consolidated all the indicators you have registered with minor or same TimeSpan/Consolidator would automatically update, so you would be able to use them.

#### Actual Behavior
There are some cases where actually indicators and CandlesticksPatterns do not update correctly.
infact, after many tests, i could see that sometimes, with unkown reasons those indicators update later by 1 candle of how they should properly work.
Example, Engulfing candle changes its value not when the correct candle closes (the engulfing one) but next one, delaying the pattern by 1 candle.
**-Edit- I've also noticed that whenever this happens, the indicator stays offsetted by the candle for the whole algo run. maybe it's caused by the order of updates or some concurrent events.**

#### Potential Solution
Cause not yet known

#### Reproducing the Problem
I am not yet able to reproduce constantly the problem , as it appears "randomly" without reason.
even testing with super basic algo such as, consolidate 1hr quotebar, register engulfingcandle 1hr, and save every quotebar on data , reproduces the bug sometimes.
As soon as i have more informations, hoping to find them, i'll update the post.

#### System Information
using Lean / C# / Forex

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
@HeroKato-Dev indicators are updated on their consolidated data events. Please provide a reproducible example if this isn't what you're seeing.
