### ISSUE TITLE
Windows reserved file names

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#3849]
#### Expected Behavior

- We correctly handle, and in a normalized manner, this windows reserved file and directories names
#### Actual Behavior

- Different classes handle this issue in their own manner, see `PsychSignalDataConverter`, `BenzingaDataConverter` and many directly don't handle it.

see https://github.com/QuantConnect/Lean/pull/3779/files/886e0232ec3113172d514182c27bc1b96d203c7f#r345286756
#### Potential Solution

- Create a new class that handles this case for windows., files and directories.
#### Reproducing the Problem

N/A
#### System Information

Windows
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
- File Normalizer
 - Add in Extensions class, on the OS File class?
 - ToValidPath (for writing to disk safely)
 - FromValidPath (for getting the ticker from its normalized format)
