### ISSUE TITLE
Security Start Dates

### ISSUE THREAD

**Issue by ckramvisus** [QuantConnect/Lean#3867]
It would be useful for security objects (or else where) to store their data start dates so groups of securities can be easily lined up to form square matrix history calls ie all symbols have history starting as of a particular date.

**Comment by Martin-Molinero** [comment]
Hi @ckramvisus !
For equities, `SecurityIdentifier.Date` is the first date the security traded and it can be accessed through `Security.Symbol.ID.Date`. Can find more details at https://www.quantconnect.com/docs/key-concepts/security-identifiers (code ref https://github.com/QuantConnect/Lean/blob/master/Common/SecurityIdentifier.cs#L151). Let us know if this is what you are looking for.

**Comment by ckramvisus** [comment]
I was more hoping for when the symbol first has data which you can query for. This is so you know what the first date that all symbols would have data for when trading a universe of symbols. The ID.Date would be when it was listed. Would it suffice to say if ID.Date < general database start date then use database start date else ID.Date if so then that would be good enough.

**Comment by jaredbroad** [comment]
Correct @ckramvisus for square date history calls you could do:

```
earliestSquareDate = max(s.ID.Date for s in algorithm.ActiveSecurities.Keys) 
algorithm.Debug(str(earliestSquareDate))```
