### ISSUE TITLE
Adds of OrderTicker UpdateXXX Methods

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#3868]
#### Expected Behavior
Be able to update an order ticker with just one method call.

#### Actual Behavior
We need to create a `UpdateOrderFields` object to use in `OrderTicket.Update`. 

#### Potential Solution
Add the following methods:
`OrderTicket.Update(string tag, decimal? quantity = null, decimal? limitPrice = null, decimal? stopPrice = null)`
or 
`OrderTicket.UpdateTag(string tag)`
and
`OrderTicket.UpdateQuantity(decimal quantity, string tag = null)`
`OrderTicket.UpdateLimitPrice(decimal limitPrice, string tag = null)`
`OrderTicket.UpdateStopPrice(decimal stopPrice, string tag = null)`

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
Implemented in #3876
