### ISSUE TITLE
PopulateDataDictionaries in TimeSlice is duplicating ticks

### ISSUE THREAD

**Issue by lithast** [QuantConnect/Lean#387]
I put some trip wires into my application to to catch issues I was having with out of order data merging live and historical ticks (unrelated). I noticed something else quite strange when I fixed the original issue. The trip wire was firing while loading historical data from the History Provider. I'm getting each tick in my data file repeated twice. Tracked it down to `PopulateDataDictionaries` in `TimeSlice`

![image](https://cloud.githubusercontent.com/assets/17696925/14741426/b4d1f124-08c8-11e6-82d0-0730d158c115.png)

`ticksList = new List<Tick> {(Tick) baseData};` 
Should this just create the list?

**Comment by jaredbroad** [comment]
Great catch @lithast! Please submit a PR and we'll merge it into master.

**Comment by jaredbroad** [comment]
+ An extra 10 bonus points if you submit a test with the PR :) /Tests/Engine/DataFeeds/TimeSliceTests.cs

**Comment by lithast** [comment]
Well now, can't be leaving points on the table. I'll take a look at it tomorrow :)

**Comment by jaredbroad** [comment]
Fixed by 36f3ef8
