### ISSUE TITLE
Random Data Generator - missing initial row in generated symbols map file.

### ISSUE THREAD

**Issue by chigginson** [QuantConnect/Lean#3882]
## Expected Behavior
If you generate random data using the toolbox utility it should be compatible with the default template algo BasicTemplateAlgorithm.cs.

#### Actual Behavior
Because of a missing start date line in the map file generated for the new symbol, the OnData method will never be called even though the symbol has data for the date range.

#### Potential Solution
Make sure we write at least the start date we used in the generator utility to the map file before the 2050 date.  For example add the following conditional to GenerateRandomData method:
// existing code
if (dividendsSplitsMaps.MapRows.Count > 1)
{
     // Remove the last element if we're going to have a 20501231 entry
     dividendsSplitsMaps.MapRows.RemoveAt(dividendsSplitsMaps.MapRows.Count - 1);
}
// start new code
 if (dividendsSplitsMaps.MapRows.Count == 0)
{
      dividendsSplitsMaps.MapRows.Add(new MapFileRow(settings.Start,dividendsSplitsMaps.CurrentSymbol.Value));
 }
// end new code
...

#### Reproducing the Problem
1) generate data with a random symbol using the following command line:
QuantConnect.ToolBox.exe --app=randomdatagenerator --resolution=Minute --start=2018-01-01 --end=2019-01-01 --market=usa --data-density=Dense --include-coarse=true --symbol-count=1

2) modify BasicTemplateAlgorithm.cs to use the newly generated symbol with a start and end date of 1/1/2018 to 1/10/2018.

3) run algo from launcher and note that no trades are made and OnData never called within algo.

#### Future Design Change
Locally I've written a few more classes to generate custom data. Random data is nice for local testing but data specifically designed to test all paths in an algo is even better.  If anyone on the team wants to discuss v2 of a data generation tool, please let me know.

#### System Information
win7 test

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jmerle** [comment]
This bug was fixed in #5443, I didn't know it was already reported here.
