### ISSUE TITLE
Adds Algorithm Example that Features ExerciseOption method

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#3897]
#### Expected Behavior
`ExerciseOptionAlgorithm` is an example of how to place `ExerciseOption` method.

#### Actual Behavior
No such example. It would be helpful to have one and add a link to it in the docs.

#### Potential Solution
Implement C# and Python version `ExerciseOptionAlgorithm`.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by prasadsom** [comment]
Isn't method `ExerciseOption ` already there ?https://github.com/QuantConnect/Lean/blob/dc59d9c5edc322b113c8e7668b0f90bd9a0abc6a/Algorithm/QCAlgorithm.Trading.cs#L489

**Comment by AlexCatarino** [comment]
@prasadsom Thank you! I missed that since I was looking for something with `Order` in its name.

**Comment by Martin-Molinero** [comment]
We already have a few examples and tests using `ExerciseOption`, see `InteractiveBrokersBrokerageDisablesIndexOptionsExerciseRegressionAlgorithm`, `EuropeanOptionsCannotBeExercisedBeforeExpiryRegressionAlgorithm`, `OptionExerciseRegressionAlgorithm` + a few unit tests
