### ISSUE TITLE
Market On Open, Market On Close Order Types

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#39]
Add market on open and market on close order type.

1) Specific Order Classes in the /Common/Orders folder, and added OrderTypes to the enum

2) Add the default fill models for each order type (one method each). Update the Interface and implement the default fill models in SecurityTransactionModels.cs. Ensure to check the validity of the order in the fill model.

3) Map the OrderType to its fill method in BacktestingBrokerage 

4) Add helper methods in QCAlgorithm.Trading.cs which return the order id for the new order. Add an 

Market On Open - According to (http://www.investopedia.com/terms/m/marketonopen-order-moo.asp) the orders can only be submitted/or cancelled between 7am - 9.28am.

Market On Close - According to (http://www.investopedia.com/terms/m/marketonclose.asp) the orders must be submitted before 3.45pm and after which can't be modified.

The order must always be rejected if its a forex type in the helper method.

We don't have a good way of *updating* orders yet.. currently order objects must be updated directly and resubmitted for processing. This puts [too much] responsibility in the algorithm to not break things. We're weighing up whether to make the orders immutable. This will break some existing community algorithms but would ensure they can't modify order state, and avoid threading issues.

Feedback welcome -

**Comment by mchandschuh** [comment]
This was implemented in https://github.com/QuantConnect/Lean/commit/099cee9b3fd89ef30382712eb79130a09cb73206
