### ISSUE TITLE
Realistic Fills for Low Volume Assets

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#391]
Currently its possible in backtests to place large orders on very low volume assets, as the default models simple fill at the last traded price. We should update LEAN to either:
- Have realistic fills which factor in volume (difficult without order book data)
- Block fills which account for more than x% of the daily volume. 

Are there good models for trade-only data which can approximate the book depth?

**Comment by 4real** [comment]
I've created a model that fills up from trades as they happen (if passing order limit), which means volume is respected. Of course that's pessimistic and does not take into account the quotes available. However, I'm thinking it's more realistic than the default model when trading thin liquidity, and it's easy to implement.

Modelling the order book from trades would be far more involved.

**Comment by jaredbroad** [comment]
We have this PR now (https://github.com/QuantConnect/Lean/pull/812) which partially addresses it using only trade and last volume data.

We don't have a way to pass through book data yet but that won't be long. We've added quote data support for all assets.

**Comment by 4real** [comment]
Ah great! Yeah, that seems pretty much like the same thing.
