### ISSUE TITLE
Include day of mourning for former president H.W. Bush in US holiday data

### ISSUE THREAD

**Issue by RohanTalip** [QuantConnect/Lean#3920]
See also issue #2730.

#### Expected Behavior

2018-12-05 should exist as a non-tradeable date in the US holiday data.

#### Actual Behavior

2018-12-05 is missing from the US holiday data.

#### Potential Solution

Add in the date (2018-12-05) for former president H.W. Bush in the static class USHoliday in Common/Global.cs (I have a pending change).

#### Checklist

- [ ] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

**Comment by RohanTalip** [comment]
FYI, I'm not sure that this issue is still valid given the discussion on pull request #3921 .

@Jay-Jay-D wrote:
> 2018-12-05 **should not** be present in the USHoliday.Dates HashSet

... after which I withdrew my pull request and wrote:
> Should the other ad hoc / specific dates (e.g. for 9/11 (i.e. the World Trade Center attacks), Hurricane Sandy, and the other 2 days of mourning for former presidents) also be removed from the USHoliday.Dates HashSet?

**Comment by jaredbroad** [comment]
Thanks @RohanTalip
