### ISSUE TITLE
Adds Hurst Exponent Indicator

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#3924]
#### Expected Behavior
Hurst Exponent Indicator is part of Lean indicator collection.

#### Actual Behavior
Hurst Exponent Indicator is not part of Lean indicator collection.

#### Potential Solution
Implement Hurst Exponent Indicator.
Community suggestion: 
https://www.quantconnect.com/forum/discussion/1695/hurst-exponent-indicator/p1
Note: Indicator implementation **must** include unit tests with third party data.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by ikamanu** [comment]
🙏

**Comment by LouisSzeto** [comment]
[spy_hurst_exponent.csv](https://github.com/QuantConnect/Lean/files/10823021/spy_hurst_exponent.csv)

**Comment by LouisSzeto** [comment]
[spy_hurst_exponent.csv](https://github.com/QuantConnect/Lean/files/13114565/spy_hurst_exponent.csv)
columns: "SPY close" "hurst exponent"

script:
```
import talib

qb = QuantBook()

spy = qb.AddEquity("SPY", Resolution.Daily).Symbol

history = qb.History([spy, qqq], datetime(1998, 1, 1), datetime(2023, 2, 23))

close = history.loc[spy].close

# Source: https://towardsdatascience.com/introduction-to-the-hurst-exponent-with-code-in-python-4da0414ca52e

def get_hurst_exponent(time_series):
    lags = range(2, 20)
    tau = [np.std(np.subtract(time_series.shift(-lag), time_series)) for lag in lags]
    reg = np.polyfit(np.log(lags), np.log(tau), 1)
    return reg[0]

# we use a rolling window of past 252 data points
hurst_exponent = close * 0
for i in range(252, len(close)):
    hurst_exponent[i] = get_hurst_exponent(close.iloc[i-252:i])
hurst_exponent = hurst_exponent[hurst_exponent != 0].to_frame()
hurst_exponent["spy close"] = close
hurst_exponent = hurst_exponent.iloc[:, [1, 0]].dropna()
hurst_exponent.to_csv("spy_hurst_exponent.csv", header=False)
```
