### ISSUE TITLE
FillForward Data is cloned twice

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#3926]
#### Expected Behavior

- Lean is as fast as possible
#### Actual Behavior

- When fill forwarding the `FillForwardEnumerator` clones the data point emitted https://github.com/QuantConnect/Lean/blob/master/Engine/DataFeeds/Enumerators/FillForwardEnumerator.cs#L282 but higher in the stack we clone the same data point again https://github.com/QuantConnect/Lean/blob/master/Engine/DataFeeds/SubscriptionData.cs#L63
![image](https://user-images.githubusercontent.com/18473240/71009961-e58d9d00-20c9-11ea-82a2-9f54eb0bd5b0.png)

#### Potential Solution

- Refactor to avoid cloninig twice
#### Reproducing the Problem

```
public class EmptyMinute400EquityBenchmark : QCAlgorithm
{
    public override void Initialize()
    {
        SetStartDate(2015, 10, 1);
        SetEndDate(2015, 11, 15);
        foreach (var symbolToAdd in Symbols.Equity.All.Take(400))
        {
            var symbol = AddSecurity(SecurityType.Equity, symbolToAdd, Resolution.Daily).Symbol;
            AddData<TiingoNews>(symbol);
        }
    }
}
```
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Seems that the original reason to clone data points was to avoid `interfere with the enumerator's internal logic` since `SubscriptionData` performs time round down, see https://github.com/QuantConnect/Lean/blame/ae0919b8e304c6225cb9539cf61e63c087569da8/Engine/DataFeeds/SubscriptionSynchronizer.cs#L102 -> so maybe we could avoid cloning the data points if there isn't a time change.

**Comment by jaredbroad** [comment]
- Keeping because in worker threads so low impact; and reduces chances of error in the consumers of the Data point later in the call stack.
