### ISSUE TITLE
Resume stats when redeploying live algorithm

### ISSUE THREAD

**Issue by wardjm** [QuantConnect/Lean#3931]
#### Expected Behavior

Implement a checkbox or something to enable reloading the previous running statistics for a live deployed algorithm. Currently, even if it is only a redeployment of a connection issue, the running stats are gone.

#### Actual Behavior

Previous algorithm stats are unrecoverable when an algorithm is redeployed.

#### Potential Solution

It seems like the old trade data is there, so it could be calculated using this.

#### Reproducing the Problem

I'm not really familiar with this part of the code to know if there is an independent test that can be done to see this occur. It could just be a front end thing for the web client.

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Closing as an issue about the cloud environment and not LEAN itself.

**Comment by wardjm** [comment]
Sorry, didn't realize it was implemented elsewhere!
