### ISSUE TITLE
Enable true "Alternative Data"-driven algorithms on QC

### ISSUE THREAD

**Issue by jordizle** [QuantConnect/Lean#3933]
The current implementation of alternative data has a number of issues:

1. A symbol-first approach has been taken, meaning you can only use the alternative data if you have selected a symbol first. For example, you can't take the news data and then decide what symbols you want to add to your universe or in the case of a basic algorithm that does not use a universe, you can't get news data without subscribing to a symbol first.

2. Too slow - throws 10 minute timeout bug when universe selects (in some cases) a very low amount of securities.

#### Expected Behavior

I can access alternative data, without adding a security/symbol to an algorithm first.

#### Actual Behavior

I can't access alternative data, without adding a security/symbol to an algorithm or selecting it via a universe selection first.

#### Potential Solution

```python
class MyAlgorithm(QCAlgorithm):
    def Initialize(self):
        self.SetStartDate(2018, 1, 1)
        self.SetCash(1000000)
        self.UniverseSettings.Resolution = Resolution.Minute
        self.SetUniverseSelection(MyCustomUniverseSelectionModel())

        # Alternative Tiingo news data every hour (different to the universe selection model - that stays at minute based data)
        self.SubscribeToCustomDataType(Tiingo, Resolution.Hour, self.OnTiingoCustomData)

    def OnTiingoCustomData(self, tiingo_news):
        for item in tiingoNews.Values:
            # {
            #  Title: 'x',
            #  Description: 'x',
            #  Symbols: ['AAA', 'BBB', 'CCC'],
            #  Description: 'x',
            # }

            title = item.Title.lower()
            symbols = item.Symbols

            if 'x' in title:
              for symbol in symbols:
                self.AddEquity(symbol)
```

#### Reproducing the Problem

I have already provided QC with a backtest to recreate multiple issues.

#### System Information

None

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
> Too slow - throws 10 minute timeout bug when universe selects (in some cases) a very low amount of securities.

The described behavior seems the same as issue https://github.com/QuantConnect/Lean/issues/3976, solved by PR https://github.com/QuantConnect/Lean/pull/3977 since it introduced a new weighted work system.

**Comment by jordizle** [comment]
> > Too slow - throws 10 minute timeout bug when universe selects (in some cases) a very low amount of securities.
> 
> The described behavior seems the same as issue #3976, solved by PR #3977 since it introduced a new weighted work system.

Thanks for the update.

**Comment by jordizle** [comment]
@Martin-Molinero What are your thoughts on having a custom data driven symbol selection as opposed to symbol-first? Maybe just for a basic algo in first instance.

**Comment by Martin-Molinero** [comment]
Hey @jordizle!
> For example, you can't take the news data and then decide what symbols you want to add to your universe or in the case of a basic algorithm that does not use a universe, you can't get news data without subscribing to a symbol first.

At https://github.com/QuantConnect/Lean/pull/4513 we've merged a couple of example algorithms showcasing custom universes that directly add custom data into the algorithm. In this case, they add TiingoNews data based on Coarse selection skipping adding the underlying equity.
It still requires having a source of Symbols, whether it's from a universe selection or a hardcoded list in the algorithm or another external source. Believe this approach was taken, following other data sources, due to performance/hardware limitations, it's a **lot** of data. Ignoring those, maybe with some refactoring a **'*'** type of Symbol could be implemented that makes the data feed load all symbols for a given type/resolution.

**Comment by jordizle** [comment]
> Hey @jordizle!
> 
> > For example, you can't take the news data and then decide what symbols you want to add to your universe or in the case of a basic algorithm that does not use a universe, you can't get news data without subscribing to a symbol first.
> 
> At #4513 we've merged a couple of example algorithms showcasing custom universes that directly add custom data into the algorithm. In this case, they add TiingoNews data based on Coarse selection skipping adding the underlying equity.
> It still requires having a source of Symbols, whether it's from a universe selection or a hardcoded list in the algorithm or another external source. Believe this approach was taken, following other data sources, due to performance/hardware limitations, it's a **lot** of data. Ignoring those, maybe with some refactoring a **'*'** type of Symbol could be implemented that makes the data feed load all symbols for a given type/resolution.

@Martin-Molinero Thank you very much for the example! I will test it out.

**Comment by jordizle** [comment]
@Martin-Molinero Is it possible to get an example with Coarse selection and Fine Selection?

**Comment by jaredbroad** [comment]
https://www.quantconnect.com/docs/v2/writing-algorithms/universes/chained-universes

Please see the various examples with coarse, fine, alternative data, and options/future universes! All of them =)
