### ISSUE TITLE
Python solutions fail to load in Visual Studio under macOS

### ISSUE THREAD

**Issue by adamny** [QuantConnect/Lean#3935]
#### Expected Behavior

QuantConnect.Lean.Launcher loads solutions like: 
QuantConnect.Algorithm. FSharp, Python, PytonTools, PythonToolbox, and VisualStudio17Plugin.

#### Actual Behavior

FSharp and  Python come with a warning: "Project not built in active configuration" 
PytonTools, PythonToolbox, and VisualStudio17Plugin have an error "Load failed: Unknown solution" 
(If I understand this correctly, the plugin is a missing feature in macOS: https://github.com/QuantConnect/Lean/issues/3538 )  

#### Potential Solution

Some internet discussion thread suggested installing .Net-SDK for mac, which I did.
But it only seems to make things worse as now I get 4 errors when I build Lean. They are all similar, the first one: "~/Lean/Lean-master/Algorithm.Framework/CSC: Error CS1705: Assembly 'QuantConnect.Common' with identity 'QuantConnect.Common, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null' uses 'NodaTime, Version=2.4.7.0, Culture=neutral, PublicKeyToken=4226afe0d9b296d1' which has a higher version than referenced assembly 'NodaTime' with identity 'NodaTime, Version=1.3.0.0, Culture=neutral, PublicKeyToken=4226afe0d9b296d1' (CS1705) (QuantConnect.Algorithm.Framework)"
  
#### Reproducing the Problem

Build QuantConnect.Lean.sln in Visual Studio for macOS.

#### System Information

macOS 10.15.2, Visual Studio for mac 8.3.11, latest master of Lean.

#### Checklist

- [ x] I have completely filled out this template
- [x ] I have confirmed that this issue exists on the current `master` branch
- [x ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x ] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment]
We recommend using [Lean-CLI](https://www.lean.io/docs/lean-cli):
> The Lean CLI is a cross-platform CLI which makes it easier to develop with the LEAN engine locally and in the cloud.
