### ISSUE TITLE
GDAXDownloader Hitting API Rate Limit

### ISSUE THREAD

**Issue by adamw96** [QuantConnect/Lean#3943]
#### Expected Behavior

Download historical pricing data from Coinbase Pro (GDAX) via Toolbox
#### Actual Behavior

Hits API Rate Limit (Error 429) after ~20-30 fetches
#### Potential Solution

`Thread.Sleep()` not working as intended perhaps in GDAXDownloader
#### Reproducing the Problem

Fresh install of latest version of LEAN, working (tested with sample algorithm) installation, build Toolbox project in Visual Studio 19, and run
`$ ./Toolbox.exe --app=GDAXDownloader --tickers=BTC-USD --resolution=# --from-date=#`
#### System Information

Win 10, Python 3.6.7 in new conda environment with dependencies.
#### Checklist

- [ X] I have completely filled out this template
- [X ] I have confirmed that this issue exists on the current `master` branch
- [X ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ X] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
@adamw96 are you running more than 1 instance in parallel?

**Comment by jaredbroad** [comment]
Closing as no response
