### ISSUE TITLE
Extension Methods for ObjectStore Not Supported in Python

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#3952]
#### Expected Behavior
Be able to use `Read`, `ReadString`, `ReadJson`, `ReadXml` and `Save` extension methods in both C# and Python algorithms.

#### Actual Behavior
Not supported. pythonnet doesn't support extension methods.

#### Potential Solution
Move those methods to the `IObjectStore` interface or create a base class that implement them.

#### Reproducing the Problem
```x = self.ObjectStore.Read("my_saved_data")```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Close by https://github.com/QuantConnect/Lean/pull/3956
