### ISSUE TITLE
LastFillTime Truncated from Market On Open Orders

### ISSUE THREAD

**Issue by gsalaz98** [QuantConnect/Lean#3953]
#### Expected Behavior

LastFillTime is available for all filled orders in the live results
#### Actual Behavior

Because of Truncation, MarketOnOpen is sometimes not be reported as `filled` because we currently only filter by the creation time of the order.
#### Potential Solution

Expand filter
#### Reproducing the Problem

Place market on open order
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/3954
