### ISSUE TITLE
Backtest Strategy with Multi TimeFrame Data for One Security.

### ISSUE THREAD

**Issue by aytacasan** [QuantConnect/Lean#3972]
#### Expected Behavior

When add multi timeframe data in a strategy for one security. OnData method must be call for all timeframes or slice must be provide all related data.

I put sample algorithm in to Reproducing the Problem section. Acording to test algoritm i want to see two log output line at 5:00am;

2019-12-02 05:00:00 MINUTE
2019-12-02 05:00:00 HOURLY

and want to see three log output line at 0:00am;

2019-12-03 00:00:00 MINUTE
2019-12-03 00:00:00 HOURLY
2019-12-03 00:00:00 DAILY

#### Actual Behavior

I don't understand exactly actual behavior. I think behavior can be change according to backtest data. For my data OnData method calling each minute for minute data between 4:00am to 5:00am. After that OnData method calling each minute for hour data(!) which is 4:00am to 5:00am hourly bar data.

#### Potential Solution

I don't have any idea about solution. Only i know that we have to access all data like explain in a [documentation](https://www.quantconnect.com/docs/key-concepts/understanding-time) Also i'm not sure is this behavior because of lean design.

Looks like Lean doesn't support this type behaviour. We can only add one and smallest timeframe for any security which we want to process and if we need bigger timeframe data too then we can only use consolidators despite datafeed provider provide that bigger timeframe data.

#### Reproducing the Problem

`using System;
using QuantConnect.Data;

namespace QuantConnect.Algorithm.CSharp
{
    public class TestAlgorithm : QCAlgorithm
    {
        private readonly Symbol spy = QuantConnect.Symbol.Create("SPY", SecurityType.Equity, Market.USA);
        public override void Initialize()
        {
            SetCash(100000);
            SetStartDate(2019, 12, 02);
            SetEndDate(2019, 12, 04);

            AddEquity(spy.Value, Resolution.Minute, Market.USA, true, 0M, true);
            AddEquity(spy.Value, Resolution.Hour, Market.USA, true, 0M, true);
            AddEquity(spy.Value, Resolution.Daily, Market.USA, true, 0M, true);
        }

        public override void OnData(Slice slice)
        {
            if (slice.Bars.ContainsKey(spy))
            {
                if (slice.Bars[spy].Period == new TimeSpan(00, 00, 01, 00))
                {
                    Log($"MINUTE {slice.Bars[spy].Time.ToString("HH:mm:ss")}");
                }
                if (slice.Bars[spy].Period == new TimeSpan(00, 01, 00, 00))
                {
                    Log($"HOURLY {slice.Bars[spy].Time.ToString("HH:mm:ss")}");
                }
                if (slice.Bars[spy].Period == new TimeSpan(01, 00, 00, 00))
                {
                    Log($"DAILY {slice.Bars[spy].Time.ToString("HH:mm:ss")}");
                }
            }
        }
    }
}`

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
This is addressed in LEAN with Consolidators. Please review the documentation for them to add consolidators of any resolution to your algorithm.

**Comment by aytacasan** [comment]
@jaredbroad thanks for your explanation. I discovered Lean almoust two years ago. I didn't have a chance to write hundreds and hundreds algorithms but i used dozens of times consolidators in my algoritims. I know what they are, how we use etc. Because of use many trading platforms and develop strategies for them i'm questioning lean's multi timeframe behaviour. Also there's a chance I might have misunderstood some concepts about algorithmic trading.

Lets say my datafeed provider provide tick, minute, hour and daily data. In my strategy i need tick, 1 & 5 minute data, 1 & 4 hour data, daily and monthly data all together. I think you are saying that you have to add securities to your algorithm with AddEquity("XYZ", Resolution.Tick, Market.USA) because tick is lowest time frame you needed and then add consolidators for each time frame which are 1 min, 5 min, 1 hour, 4 hour, daily and monthly and feed that consolidators with ticks.

I'm not sure if it makes sense but why i can not receive 1 hour and 1 day data directly from my datafeed provider? So i can use daily data for my indicators and for consolidate to monthly data. I understand that we can not do that for 5 minute data and we need consolidator(because datafeed provider not provide that). Is it right approach to form daily, monthly bars from tick by tick data?
