### ISSUE TITLE
How to update config file?

### ISSUE THREAD

**Issue by adamny** [QuantConnect/Lean#3978]
#### Expected Behavior

Clear instructions in https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/readme.md

#### Actual Behavior

The instructions say:
"Update the config to run the python algorithm:
"algorithm-type-name": "BasicTemplateAlgorithm",
"algorithm-language": "Python",
"algorithm-location": "../../../Algorithm.Python/BasicTemplateAlgorithm.py",
"

1. Where I am supposed to put the linked config.json file? Somewhere in my Anaconda python directory tree? Somewhere in Visual Studio installation or in the Lean Master?
2. Where and how I am to run the above script? 

#### Reproducing the Problem

See "Update the config to run the python algorithm:"
in https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/readme.md 

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by adamny** [comment]
Oh, now I am guessing that perhaps it means that I need to execute config.json in Lean solution in VS before running python scripts. Correct? I did just that and then BasicTemplateAlgorithm.py and it went fine, except that the output says that there were 3 successful trades even though the script makes zero trades. I don't know if that's because I didn't understand the above installation instruction after all or because of some other issue.

**Comment by Martin-Molinero** [comment]
Hi @adamny !
You need to update the config.json, build the solution and launch Lean (Control + F5 for VS). You could also directly modify the config.json in the output directory (should be 'Launcher\bin\Debug\') and launch Lean. `BasicTemplateAlgorithm.py` performs 1 trade. `BasicTemplateFrameworkAlgorithm` performs 3 trades which is the default configuration value.
Hope this helps!

**Comment by adamny** [comment]
Thanks, @jaredbroad.
That was helpful!
