### ISSUE TITLE
config.json build fails 

### ISSUE THREAD

**Issue by adamny** [QuantConnect/Lean#3985]
#### Expected Behavior

Successful build of Lean solution

#### Actual Behavior

Error: CS1705	Assembly 'QuantConnect.Lean.Engine' with identity 'QuantConnect.Lean.Engine, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null' uses 'DotNetZip, Version=1.13.5.0, Culture=neutral, PublicKeyToken=6583c7c814667745' which has a higher version than referenced assembly 'DotNetZip' with identity 'DotNetZip, Version=1.13.3.0, Culture=neutral, PublicKeyToken=6583c7c814667745'	
In project: QuantConnect.ToolBox	
C:\Users\Adam\Downloads\Lean-master\Lean-master\ToolBox\IQFeed\IQFeedDataQueueUniverseProvider.cs

Then I get 2 more errors saying that QuantConnect.ToolBox.exe and QuantConnect.Lean.Laucher.exe cannot be found.

#### Reproducing the Problem

Install VS, download Lean, open QuantConnect.Lean.sln. Build.

#### System Information

Fresh install of VS and Lean on Win 10. See pic 
I have Anaconda Python 3.7.4 -- could that be an issue?
(However, on another windows machine I have anaconda python 3.7.0, and I don't have this issue)

#### Checklist

- [v ] I have completely filled out this template
- [ v] I have confirmed that this issue exists on the current `master` branch
- [ v] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [v ] I have provided detailed steps to reproduce the issue
![VS-version png](https://user-images.githubusercontent.com/50718721/72005419-90056580-321b-11ea-99c5-3ab57c8b9808.jpg)

**Comment by Martin-Molinero** [comment]
Hi @adamny !
Just tested this on my end and wasn't able to reproduce using VS 16.4.2. Lean currently uses python 3.6.8, I'd suggest testing with it instead.

**Comment by jaredbroad** [comment]
Guessing nuget packages not installed; closing while await further information

**Comment by adamny** [comment]
Thanks! I am currently dealing with conda errors trying to downgrade to
python 3.6.8. Once I managed that I will let you know if my Lean build
problems continue.
