### ISSUE TITLE
Add Plotly Library for Research

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#3987]
#### Expected Behavior
Suppor plotly jupyter plugin

#### Actual Behavior
No plotly support.

#### Potential Solution
Add Plotly

#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
I believe this has been implemented already https://github.com/QuantConnect/Research/issues/17
