### ISSUE TITLE
GPU Acceleration Support for Python Machine Learning

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#3990]
#### Expected Behavior
Enable GPU acceleration for machine learning when a python packages support it. 

#### Actual Behavior
GPU acceleration is disabled.

#### Potential Solution
N/A

#### System Information
QuantConnect Cloud

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
A cloud issue - not something LEAN can address
