### ISSUE TITLE
Create Parabolic SAR Indicator

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#4]
Create an "ParabolicSAR" indicator class and the associated "SAR" helper method in the QCAlgorithm base class. See introduction to indicators - https://lean.quantconnect.com/docs#topic9.html

Add the associated tests to Tests project under /Indicators to confirm the Parabolic SAR values match up with the data provided in Tests/TestData/spy_parabolic_SAR.txt file.

**Comment by mchandschuh** [comment]
Hey @AlexCatarino! Just wondering if there was any progress on this? If not, are you OK with me un-assigning you in case someone else wants to take a stab at it? Thanks!

**Comment by AlexCatarino** [comment]
Please, do assign someone else, @mchandschuh!
I'm quite busy with delayed work right now and I don't want to hold the indicators coding back.

**Comment by chutes** [comment]
I just added an example psar on the forums.

during testing, my test fails after 83 updates on this line...
5/15/2013 12:00:00 AM,164.98,166.45,164.91,166.12,161.7411

**Comment by jaredbroad** [comment]
Closed in commit 788b598
