### ISSUE TITLE
Custom Benchmark

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#40]
Add the ability to use a custom benchmark, or at least any symbol from yahoo.  Steps:

1) Add helper method SetBenchmark(string symbol) which takes the Yahoo symbol,
2) Save the symbol to a public "string Benchmark" property, 
3) Update IAlgorithm to include new Benchmark property.
3) Use this symbol when downloading the benchmark data from Yahoo in the Statistics class.

**Comment by mchandschuh** [comment]
This was merged in https://github.com/QuantConnect/Lean/commit/1b9c1b792165848566edcc1fa543ca526b15286d
