### ISSUE TITLE
lean installation on linux

### ISSUE THREAD

**Issue by josefstr** [QuantConnect/Lean#400]
I tried to install Lean on a linux system with the steps described on github, but it failed at step:
"xbuild build"

Lean (git)-[master] % xbuild build
XBuild Engine Version 12.0
Mono, Version 4.2.1.0
Copyright (C) 2005-2013 Various Mono authors
MSBUILD: error MSBUILD0000: Project file 'build' not found.

Is the build config missing?

**Comment by jaredbroad** [comment]
Hi @josefstr I've updated the readme here, and updated the Sln file to not build Fsharp because it just had too many issues in mono compile. https://github.com/QuantConnect/Lean/blob/master/readme.md

Make sure you run the new Nuget process too -- (downloading nuget.exe and running it with mono).
