### ISSUE TITLE
Issue with FSharp.Core in VS Windows Installation

### ISSUE THREAD

**Issue by adamny** [QuantConnect/Lean#4005]
#### Expected Behavior

Lean builds with no issues with NuGet libraries. 

#### Actual Behavior

![mono packages problem png](https://user-images.githubusercontent.com/50718721/72405922-8eaad000-3728-11ea-9e46-30efa4d7842e.jpg)

Building Lean leads to errors (as in pic) and restoring NuGet packages is looping itself.
It maybe a problem with VS/NuGet. Which version of FSharp.Core library: 4.2.1 or 4.5.2 does Lean need? Perhaps both?

#### Reproducing the Problem

Lean installation success relies on a large number of factors, some of which are subtle. I have this problem on one Windows machine but not another.

#### System Information

![VS-version png](https://user-images.githubusercontent.com/50718721/72405897-776be280-3728-11ea-9bc3-f6c6e75031a8.jpg)

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey! Only the engine project is requiring `FSharp.Core` 4.5.2 today, the other references have been removed, believe this issue isn't valid anymore, closing
