### ISSUE TITLE
CoarseFineFundamentalRegressionAlgorithm is failing regression test

### ISSUE THREAD

**Issue by gsalaz98** [QuantConnect/Lean#4008]
#### Expected Behavior

We have deterministic results whenever we run the algorithm.

#### Actual Behavior

Statistics generated are non-deterministic. Test fails on every single run, even if statistics are updated every run. This includes the "Total Trades" statistic.

#### Potential Solution

Bisect and examine where non-determinism first began, then ---> ?
#### Reproducing the Problem

You can test this by setting `regression-update-statistics` to true in config.json, and see that the test will fail every time, even though we're updating the algorithm's expected statistics on each run.

@Martin-Molinero is reproducing same results on his end.

#### System Information

Tested on Win 10/VS2019. 
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
I believe this started after PR https://github.com/QuantConnect/Lean/pull/4000
