### ISSUE TITLE
Add Weight argument to Insight.Price constructor

### ISSUE THREAD

**Issue by simonsonjack** [QuantConnect/Lean#4037]
#### Expected Behavior

All Insight constructors, and Insight constructor helper-methods, should have ```weight``` as an optional argument.

#### Actual Behavior

The ```Insight.Price``` constructor using the expiry function does not include ```weight```
https://github.com/QuantConnect/Lean/blob/master/Common/Algorithm/Framework/Alphas/Insight.cs#L380

#### Potential Solution

Add the argument to the constructor as in others.
```
public static Insight Price(Symbol symbol, Func<DateTime, DateTime> expiryFunc, InsightDirection direction, double? magnitude = null, double? confidence = null, string sourceModel = null, double? weight = null)
{
     return new Insight(symbol, expiryFunc, InsightType.Price, direction, magnitude, confidence, sourceModel, weight);
}
```
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/4038
