### ISSUE TITLE
Duplicate bars appear at end of warmup

### ISSUE THREAD

**Issue by haxdds** [QuantConnect/Lean#4048]
#### Expected Behavior
Last bar of warm up period and first bar of algorithm period should be unique.

#### Actual Behavior
During warmup for certain starting dates for at least Forex Symbols "EURUSD" and "GBPUSD", the last bar of warm up period and first bar of algorithm period are duplicates, with identical time stamps, identical price/quote data, and are not fillforward bars.

#### Reproducing the Problem
See [Forum Post](https://www.quantconnect.com/forum/discussion/7293/backtest-charting-duplicate-datapoint-with-warmup-set/p1) with attached backtest which reproduces issue: 

Simple case
```csharp
namespace QuantConnect.Algorithm.CSharp {
    public class DuplicateDataPoint : QCAlgorithm {
    	private int _day;
    	
        public override void Initialize() {
            SetStartDate(2020, 1, 1);
            AddEquity("SPY", Resolution.Daily);
            SetWarmup(100);
            _day = Time.Day;
        }

        public override void OnData(Slice data) {
            if (_day == Time.Day) {
            	_day = Time.Day;
            	Quit($"{Time} :: {IsWarmingUp}");
            }
            _day = Time.Day;
        }
    }
}
```
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by shilewenuw** [comment]
Backtest demonstrating bug: https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_870ddaae6eb2881f9c1739dd27b0027d.html
