### ISSUE TITLE
Create Algorithm Micro-Strategies and Templates

### ISSUE THREAD

**Issue by jameschch** [QuantConnect/Lean#408]
I'm considering the usefulness of some algorithm micro-strategies that perform operations not directly related to indicators and trade signals, such as:

-Position Sizing/Risk Management (martingale, proportional to volatility, fixed amount/%, time interval limit)
-Entry Stategies (active/passive, maker/taker)
-Stop Loss/Take Profit: % of total portfolio, time elapsed, psar, arbitrary % profit

I'm sure there are lots of QC and LEAN users like myself that don’t have a firm grasp on the some of the more mundane, but still very important concepts of efficient algorithms that would really get a boost from something like this. I think initially it might be worthwhile to implement some simple template algorithms that others can imitate, but if there’s sufficient demand I'd like to think about formalizing these as reusable algorithm micro-strategy components exposing API’s something like:
```
SetHoldings(“APL”, PositionSizingStrategy.Martingale, OrderDirection.Buy)

StopLimitOrder(“APL”, EntryStrategy.MakerFee, StopLossStrategy.Psar, psarInstance)

TryStopLoss(“APL”, StopLossStrategy.TotalPortfolioValue, 50m)
```

Is there any interest in these kinds of micro-strategies? I’ll be the first to admit that I’m not an authority on trading techniques so will greatly appreciate the advice and direction of the trading experts out there.

**Comment by jaredbroad** [comment]
Thanks @jameschch, we have something similar to this on the roadmap, but framed in a slightly different way. We called it the "execution engine" where users could provide plugin's for various execution choices.

I shared an algorithm in the QC University called "Algorithm Framework" which separated an algorithm into components for this purpose. We were thinking of making an Executor property in the QCAlgorithm class which accepts "IExecutionEngine" types. 

The default IExecutionEngine would be a simple "order 100% of instruction immediately". It would be refreshed by LEAN (algo loop or transaction manager not sure) and if you wrote a custom one it would allow you to break an order into any pieces required. The QCU Algorithm Framework template has a "standard deviation" execution template. 

Ideally we don't overload the API like that as there are n-potential execution methods so its best solved with an interface/plugin point.

**Comment by jameschch** [comment]
Excellent. I expected someone would have already considered this as I'm basically describing a higher level of abstraction over trade execution. I was planning to just add some high level utilities for my own reuse, so was thinking more at the level of plugins than additions to the core trading classes. I'll look closely at IExecutionEngine.
