### ISSUE TITLE
Respect FreePortfolioValuePercentage As Portfolio Grows in Value

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#4104]
#### Expected Behavior
When using Settings.FreePortfolioValuePercentage it is respected as the portfolio grows in value.

#### Actual Behavior
Because the percentage is calculated as a value only once at start it is fixed in time and will not adjust to the portfolio value.

#### Potential Solutions
 - Update the value each day.
 - Change the logic to calculate it on-demand vs using a static value.
 - Make them nullable and switch to percent or value mode depending on which is set.
https://github.com/QuantConnect/Lean/blob/master/Engine/Setup/BacktestingSetupHandler.cs#L230

#### Reproducing the Problem
Set Settings.FreePortfolioValuePercentage in OnData.
 
#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
One thing to keep in mind is automatic portfolio rebalancing to respect the `FreePortfolioValuePercentage`, which may cause undesired transaction fees.
For example in the case of `Settings.FreePortfolioValuePercentage = 0.1m;` and holding 0.9m AAPL, if  the price of AAPL goes down, `FreePortfolioValuePercentage` will be > 0.1m

**Comment by marvin-hansen** [comment]
Is there a known workaround to this issue?

Would it be possible to just add an optional boolean flag **is_trailing** to switch between trailing and non-trailing behavior to ensure full compatibility with all existing code?

**Comment by jaredbroad** [comment]
- Easily done with the PCM recalculating the targets on a rebalance period. 
 - For classic algorithm equivalent in SetHoldings we could refresh the Free portfolio value right before the SetHoldings is calculated. This would keep it up to date at the point its about to be used and not introduce unscheduled churn?
