### ISSUE TITLE
Adds Missing History Overload that Returns Pandas.DataFrame

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4110]
#### Expected Behavior
To have overloads for History method for both C# and Python with matching parameters.

#### Actual Behavior
No python equivalent of
```csharp
public IEnumerable<Slice> History(
    IEnumerable<Symbol> symbols,
    DateTime start,
    DateTime end,
    Resolution? resolution = null,
    bool? fillForward = null,
    bool? extendedMarket = null)
```
#### Potential Solution
Implements:
```csharp
public IEnumerable<Slice> History(
    PyObject symbols,
    DateTime start,
    DateTime end,
    Resolution? resolution = null,
    bool? fillForward = null,
    bool? extendedMarket = null)
```

#### Reproducing the Problem
```python
bars = self.History([symbol], self.Time - timedelta(hours=96, minutes=0), self.Time, Resolution.Hour, False, False)
```
throw the exception:
_To prevent the exception, ensure each parameter type matches those required by the History method. Please check out the API documentation._

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closing issue as it's now fixed, running the following algorithm works as expected

```python
# region imports
from AlgorithmImports import *
# endregion

class LogicalMagentaGiraffe(QCAlgorithm):
    def Initialize(self):
        self.SetStartDate(2013,10, 7)
        self.SetEndDate(2013,10,11)

        symbol = self.AddEquity("SPY", Resolution.Minute).Symbol
        bars = self.History([symbol], self.Time - timedelta(hours=96, minutes=0), self.Time, Resolution.Hour, False, False)
        self.Debug("bars: " + str(bars))
```
