### ISSUE TITLE
Replace Deprecated Alpaca NAT Connection with Websocket

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#4111]
#### Expected Behavior
Local streaming of Polygon data works.

#### Actual Behavior
Fails to connect. 

#### Potential Solution
 - Update the [NatClient](https://github.com/QuantConnect/Lean/blob/master/Brokerages/Alpaca/Markets/NatsClient.cs) with [WebSocket](https://github.com/polygon-io/client-examples/blob/master/websockets/cs/example.cs) client. 
 - Update the SDK Package.

#### Reproducing the Problem
Run a local alpaca with live feed.
 
#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues) 
- [x] I have provided detailed steps to reproduce the issue

**Comment by auwsom** [comment]
Hi @gsalaz98, I'm interested in helping to get the Alpaca client reconnected. I have the WebSocket authenticated and working within the AlpacaBrokerage.cs. The next step looks like to integrate the client calls with the IDataQueueHandler. Where are you at and can I help you or ask a couple of questions? Thanks, and let me know either way if you could

**Comment by auwsom** [comment]
@gsalaz98, I should have seen your merge.. Would have got to run it before the bell, but it runs on historic data. On to the actual algo coding and refining my backtests - much better for a Python programmer. The code looks very thorough and much better than my mono msc debugging. 
Thanks very much and have a great weekend! And Jared too..
