### ISSUE TITLE
Remove deprecated/obsolete RunMode enum

### ISSUE THREAD

**Issue by RohanTalip** [QuantConnect/Lean#4114]
#### Expected Behavior

The RunMode enum is removed within a reasonable time after being deprecated / made obsolete.

#### Actual Behavior

The RunMode enum is still present.

#### Potential Solution

I have a change that I will send shortly as a pull request.

#### Reproducing the Problem

N/A

#### System Information

N/A

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/4115
