### ISSUE TITLE
Report Generator Portfolio Looper Fails On Cash Account Type

### ISSUE THREAD

**Issue by nazbrok** [QuantConnect/Lean#4124]
Run locally

I created an algorithm using GDAX on cash setup like this

```
          SetBrokerageModel(BrokerageName.GDAX, AccountType.Cash);
          var btc = AddCrypto("BTCUSD", Resolution.Hour);
```

I ran the algo and generated the json file for the report.

(copy below)
[CryptoAlgorithm.json.log](https://github.com/QuantConnect/Lean/files/4231989/CryptoAlgorithm.json.log)

When running the report it throw an exception about leverage not allowed on cash account despite the fact I didn't use leverage on my algorithm.

#### Expected Behavior
Generate the report

#### Actual Behavior
Throw an exception "CashBuyingPowerModel does not allow setting leverage. Cash accounts have no leverage"

System.InvalidOperationException
  HResult=0x80131509
  Message=CashBuyingPowerModel does not allow setting leverage. Cash accounts have no leverage.
  Source=QuantConnect.Common
  StackTrace:
   at QuantConnect.Securities.CashBuyingPowerModel.SetLeverage(Security security, Decimal leverage) in C:\Users\me\Documents\Perso\Dev\Test6\Lean-master\Common\Securities\CashBuyingPowerModel.cs:line 54
   at QuantConnect.Securities.Security.SetLeverage(Decimal leverage) in C:\Users\me\Documents\Perso\Dev\Test6\Lean-master\Common\Securities\Security.cs:line 649
   at QuantConnect.Securities.SecurityService.CreateSecurity(Symbol symbol, List`1 subscriptionDataConfigList, Decimal leverage, Boolean addToSymbolCache) in C:\Users\me\Documents\Perso\Dev\Test6\Lean-master\Common\Securities\SecurityService.cs:line 173
   at QuantConnect.Securities.SecurityManager.CreateSecurity(Symbol symbol, List`1 subscriptionDataConfigList, Decimal leverage, Boolean addToSymbolCache) in C:\Users\me\Documents\Perso\Dev\Test6\Lean-master\Common\Securities\SecurityManager.cs:line 315
   at QuantConnect.Report.PortfolioLooperAlgorithm.FromOrders(IEnumerable`1 orders) in C:\Users\me\Documents\Perso\Dev\Test6\Lean-master\Report\PortfolioLooper\PortfolioLooperAlgorithm.cs:line 43
   at QuantConnect.Report.PortfolioLooper..ctor(Double startingCash, List`1 orders, Resolution resolution) in C:\Users\me\Documents\Perso\Dev\Test6\Lean-master\Report\PortfolioLooper\PortfolioLooper.cs:line 116
   at QuantConnect.Report.PortfolioLooper.<FromOrders>d__12.MoveNext() in C:\Users\me\Documents\Perso\Dev\Test6\Lean-master\Report\PortfolioLooper\PortfolioLooper.cs:line 274
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at QuantConnect.Report.Report..ctor(String name, String description, String version, BacktestResult backtest, LiveResult live) in C:\Users\me\Documents\Perso\Dev\Test6\Lean-master\Report\Report.cs:line 50
   at QuantConnect.Report.Program.Main(String[] args) in C:\Users\me\Documents\Perso\Dev\Test6\Lean-master\Report\Program.cs:line 69

#### Potential Solution
Update the line 43 of PortfolioLooperAlgorithm.cs currently setting a default leverage of 10000m (why is it initialize to 10000 ?)

#### Reproducing the Problem
Algorithm used to generate the file

```
using QuantConnect;
using QuantConnect.Algorithm;
using QuantConnect.Algorithm.Framework.Execution;
using QuantConnect.Algorithm.Framework.Risk;
using QuantConnect.Brokerages;
using QuantConnect.Data;
using QuantConnect.Data.Consolidators;
using QuantConnect.Indicators;
using QuantConnect.Orders;
using System;

namespace Nazbot.Algorithm
{
    public class CryptoAlgorithm : QCAlgorithm
    {
        private enum Trend
        {
            None = 0,
            Up = 1,
            Down = 2,
        }
        private ArnaudLegouxMovingAverage _alma;
        private Trend _previousTrend = Trend.None;
        private Trend _warmupTrend = Trend.None;

        private decimal _high;

        private int _count;

        private Series _sellSeries;
        private Series _buySeries;
        private Series _almaSeries;

        public override void Initialize()
        {
            SetStartDate(2018, 1, 1);  //Set Start Date
            SetEndDate(2018, 12, 31);
            SetCash(1000);             //Set Strategy Cash

            SetBrokerageModel(BrokerageName.GDAX, AccountType.Cash);
            var btc = AddCrypto("BTCUSD", Resolution.Hour);
            btc.SetDataNormalizationMode(DataNormalizationMode.Raw);

            _alma = ALMA(btc.Symbol, 50);

            var consolidator = new TradeBarConsolidator(TimeSpan.FromHours(4));
            consolidator.DataConsolidated += (sender, tradeBar) =>
            {
                if (!_alma.IsReady)// || _count > 5)
                {
                    return;
                }

                var trend = (Securities["BTCUSD"].Close > _alma) ? Trend.Up : Trend.Down;

                if (_warmupTrend == Trend.None)
                {
                    Debug($"Warmup trend : {trend.ToString()}");
                    _warmupTrend = trend;
                    // Mode warmup, we wait the next reversal
                    return;
                }

                if (_previousTrend == Trend.None && _warmupTrend == trend)
                {
                    // Mode warmup, we wait the next reversal
                    return;
                }

                Debug($"Trend reversal : previous {_previousTrend.ToString()}, Current {trend.ToString()}");
                if (!Portfolio.Invested)
                {
                    var price = Securities["BTCUSD"].Close;
                    if (trend != _previousTrend && trend == Trend.Up && price > _alma)
                    {
                        Debug($"Buying at {price}");
                        SetHoldings("BTCUSD", 1);
                        _count++;
                        StopMarketOrder("BTCUSD", -Portfolio["BTCUSD"].Quantity, Securities["BTCUSD"].Close * 0.99m);
                    }
                }
                else
                {
                    _high = Math.Max(Securities["BTCUSD"].High, _high);

                    // Trend changed
                    if (_previousTrend != trend)
                    {
                        Debug($"Liquidating : Trend is now {trend.ToString()}");
                        Liquidating("BTCUSD", $"Trend is now {trend.ToString()} ; High was {_high}");
                        //SetHoldings("BTCUSD", -1);
                    }
                }

                _previousTrend = trend;
            };
            RegisterIndicator(btc.Symbol, _alma, consolidator);

            SetRiskManagement(new TrailingStopRiskManagementModel(0.01m));
            SetExecution(new NullExecutionModel());

            var almaPlot = new Chart("Bouh");
            //On the Trade Plotter Chart we want 3 series: trades and price:
            _buySeries = new Series("Buy", SeriesType.Scatter, "$", System.Drawing.Color.Green, ScatterMarkerSymbol.Triangle);
            _sellSeries = new Series("Sell", SeriesType.Scatter, "$", System.Drawing.Color.Red, ScatterMarkerSymbol.TriangleDown);
            _almaSeries = new Series("AlmaIndicator", SeriesType.Line, "$", System.Drawing.Color.Yellow);
            almaPlot.AddSeries(_buySeries);
            almaPlot.AddSeries(_sellSeries);
            almaPlot.AddSeries(_almaSeries);
            AddChart(almaPlot);
        }

        /// OnData event is the primary entry point for your algorithm. Each new data point will be pumped in here.
        /// Slice object keyed by symbol containing the stock data
        public override void OnData(Slice data)
        {

            Plot("AlmaIndicator", _alma);
            if (!Securities["BTCUSD"].Exchange.ExchangeOpen)
            {
                Debug("Exchange open");
            }

        }

        public override void OnOrderEvent(OrderEvent orderEvent)
        {
            if (orderEvent.Status == OrderStatus.Filled)
            {
                var series = orderEvent.FillQuantity < 0 ? "Sell" : "Buy";

                Plot(series, orderEvent.FillPrice);
            }


            Debug($"{Time} {orderEvent} cash available ({Portfolio.CashBook["USD"].Amount})");
        }

        private void Liquidating(Symbol symbol, string reason)
        {
            Debug($"Liquidating : {reason}");
            Liquidate(symbol);
        }


    }
}
```

#### System Information
Windows 10
Visual Studio 19

#### Checklist

- [X] I have completely filled out this template
- [X ] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hi @nazbrok 
Did a quick test locally and wasn't able to reproduce in current `master`, could you confirm your using latest master? We fix a related issue a few days back https://github.com/QuantConnect/Lean/pull/4068

**Comment by Martin-Molinero** [comment]
Never mind, I was running the algorithm backtest but the bug is in the report generator: https://github.com/QuantConnect/Lean/blob/master/Report/PortfolioLooper/PortfolioLooperAlgorithm.cs#L43
Thanks for the report @nazbrok

**Comment by nazbrok** [comment]
Yes I just double checked and on different environment (mac os). With the master branch the report throw the error.
