### ISSUE TITLE
Updating an Indicator with the same time/value multiple times should not apply the data multiple times

### ISSUE THREAD

**Issue by adam-may** [QuantConnect/Lean#4137]
#### Expected Behavior
If the same time and value is pushed through the IndicatorBase's Update(DateTime, decimal) method multiple (consecutive times), the data should only be applied the first time, similar to Update(IBaseData).

#### Actual Behavior
Due to a new IndicatorDataPoint being created each time, the reference check in Update(IBaseData) fails, thereby applying the data each time.

#### Potential Solution
Check the date and value fields in Update(DateTime, decimal) prior to calling Update(IBaseData).

#### Reproducing the Problem
Call Update(DateTime, decimal) multiple times with the same values. Each time it gets called, the data is applied to the Indicator.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hi @adam-may 
Wondering what's the use case that causes this behavior: `Reproducing the Problem: Call Update(DateTime, decimal) multiple times with the same values.`, seems there could potentially be another Lean bug triggering this behavior?

**Comment by Jumaga2015** [comment]
Hola @Martin-Molinero 

This problem appears when you enable `EnableAutomaticIndicatorWarmUp = true;` In the following sample, the result of the backtest when you enable the Automatic Indicator WarmUp is different than when it is not enabled.

 `namespace QuantConnect.Algorithm.CSharp
{
    public class SistemaCruceEmas : QCAlgorithm
    {
    	
        private SimpleMovingAverage _fast;
        private SimpleMovingAverage _slow;

        private Symbol _symbol;


        public override void Initialize()
        {
        	EnableAutomaticIndicatorWarmUp = true;
        	
            SetTimeZone("Europe/Madrid");

            SetStartDate(2016, 01, 01);
            SetEndDate(DateTime.Now);

            SetAccountCurrency("USD");
            SetCash(100000);             //Set Strategy Cash

            SetBrokerageModel(BrokerageName.GDAX, AccountType.Cash);

            // Find more symbols here: http://quantconnect.com/data
            _symbol = AddCrypto("BTCUSD", Resolution.Daily).Symbol;

            // create one moving average
            _fast = SMA(_symbol, 2, Resolution.Daily);
            _slow = SMA(_symbol, 22, Resolution.Daily);
        }

        /// OnData event is the primary entry point for your algorithm. Each new data point will be pumped in here.
        /// Slice object keyed by symbol containing the stock data
        public override void OnData(Slice data)
        {
		   if (data.Time.Year < 2017) return;	
			
           if (_fast > _slow)
            {
                if (Portfolio.CashBook["BTC"].Amount == 0)
                {
                    Buy(_symbol, 10);
                }
            }
            else
            {
                if (Portfolio.CashBook["BTC"].Amount > 0)
                {
                    Liquidate(_symbol);
                }
            }
        }

    }
}`

**Comment by Martin-Molinero** [comment]
Hola @Jumaga2015 ,
Your right, in this case, the underlying issue is https://github.com/QuantConnect/Lean/issues/3861. I've updated that issue adding the algorithm you shared to reproduce and included a comment about this undesired behavior. Thanks for the report 👍.

**Comment by Martin-Molinero** [comment]
The underlying issue has been fixed by PR https://github.com/QuantConnect/Lean/pull/4227
