### ISSUE TITLE
Adds Python Version of ObjectStoreExampleAlgorithm

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4146]
#### Expected Behavior
Lean provides examples of features in both C# and Python.

#### Actual Behavior
ObjectStoreExampleAlgorithm only available in C#.

#### Potential Solution
Implement Python version

#### Reproducing the Problem
Broken link in docs: [Storing Trained Models](https://www.quantconnect.com/docs/algorithm-reference/machine-learning#Machine-Learning-Storing-Trained-Models).

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/4326
