### ISSUE TITLE
CustomChartingAlgorithm/Custom Charting State?

### ISSUE THREAD

**Issue by cmoski** [QuantConnect/Lean#4148]
Hey all,

I'm curious about the state of Custom Charting Algorithm. Is it technically supposed to be supported?

Not sure where this might be even in partial form -- I can't find references to TriangleDown and other indicators anywhere except for Series.cs which leads to the JSON export.. 

Thought I'd make an issue anyway though :)

#### Expected Behavior
1) Grab a fresh copy of the LEAN repo
2) Modify the config.json to include CustomChartingAlgorithm
3) Modify Custom Charting Algorithm to have data compatible with the provided dataset
`        private readonly DateTime _startDate = new DateTime(2013, 10, 07);
        private readonly DateTime _endDate = new DateTime(2013, 10, 11);
            AddSecurity(SecurityType.Equity, "SPY",Resolution.Minute);
`
3b) Modify conditions to actually plot something on the minute scale.
4) Generate CustomChartingAlgorithm.json
5) Create config.json in the report project and point it to CustomChartingAlgorithm.json
6) Custom charts for Trade Plot, Strategy Equity should appear in the output

#### Actual Behavior
All of the above works great, except for the output does not contain any of the custom charts definied in CustomChartPlot.

#### System Information
Windows 10 1607, Python 3.6, Visual Studio 2019

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Thank you for the issue @cmoski; this is not a supported feature at this time,
