### ISSUE TITLE
Update .NET Framework Version to 4.6.1+ For Net Standard 2.0 Compatibility

### ISSUE THREAD

**Issue by cmoski** [QuantConnect/Lean#4149]
Please excuse the ignorance on this, but is there a reason we are at .NET framework 4.5.2? My use case is wanting to utilize libs built up on netstandard2.0, and think LEAN would benefit from better dotnetcore/dotnet cross compatibility. 

Compatibility list here:
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

Have a working branch upgraded to .NET 4.7.2 and it seems to be working well. 

https://github.com/cmoski/Lean/tree/feature-472dotnetupgrade

The docker container compiles without any issue/runs for the sample algorithm at least on Mono 6.8.0.105 / Debian Buster. (https://www.mono-project.com/docs/about-mono/compatibility/)

Any thoughts? (You guys rock, by the way..)

Thanks!

**Comment by jaredbroad** [comment]
Thanks @cmoski! We've tried to upgrade a few times but quickly encounter memory leaks. It is rock-solid on 4.5.2 (_16+ months uptime_) but we'll continue testing the new versions as they come out.

**Comment by cmoski** [comment]
Jared,

Thanks for getting back with me, and totally understood on the fact that you have to consider the version requirements for the cloud environment.  (After posting the issue this consideration quickly arose)

Thought I'd ask -- any guidance on where the memory leaks may occur? I have some experience on the CLR side (contributed a bit in porting core to ARM64) and have been somewhat successful in the past at tracking these down. Would be happy to take a look at specific areas on my fork in general. (past success and future results, and all of that)

**Comment by Leonardo-Ferreira** [comment]
> We've tried to upgrade a few times but quickly encounter memory leaks.

Would you mind expanding on that a bit? I would like to contribute and this (performance and scalability) is my speciality!

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/4423
