### ISSUE TITLE
Premier Stochastic Oscillator Indicator

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#4164]
#### Expected Behavior
Support "Premier Stochastic Oscillator"
- https://www.investopedia.com/articles/trading/10/premier_stochastic_oscillator_explained.asp
- https://www.tradingview.com/script/xewuyTA1-Indicator-Premier-Stochastic-Oscillator/

#### Actual Behavior
No implementation of "Premier Stochastic Oscillator"

#### Potential Solution
Implement "Premier Stochastic Oscillator"

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by bulbbeing** [comment]
[PSO.zip](https://github.com/QuantConnect/Lean/files/4358212/PSO.zip)

**Comment by LouisSzeto** [comment]
[spy_pso.csv](https://github.com/QuantConnect/Lean/files/10822819/spy_pso.csv)

**Comment by LouisSzeto** [comment]
[spy_pso.csv](https://github.com/QuantConnect/Lean/files/13114371/spy_pso.csv)
Columns: "SPY high" "SPY low" "SPY close" "PSO"

script:
```
import talib

qb = QuantBook()

spy = qb.AddEquity("SPY", Resolution.Daily).Symbol

history = qb.History([spy, qqq], datetime(1998, 1, 1), datetime(2023, 2, 23))

close = history.loc[spy].close
high = history.loc[spy].high
low = history.loc[spy].low

k, d = talib.STOCH(high, low, close,
                   fastk_period=8,
                   slowk_period=8,
                   slowd_period=8)
nsk = 0.1 * (k - 50)
ss = talib.EMA(talib.EMA(nsk.dropna(), 5), 5).dropna()
expss = np.exp(ss)
pso = ((expss - 1) / (expss + 1)).to_frame()

pso["high"] = high
pso["low"] = low
pso["close"] = close
pso = pso.iloc[:, [1, 2, 3, 0]]
pso.to_csv("spy_pso.csv", header=False)
```

**Comment by guitrading** [comment]
I will take this one.

**Comment by JosueNina** [comment]
Updated script to manually calculate FastK instead of using SlowK (talib.STOCH)
[spy_pso.csv](https://github.com/user-attachments/files/17638380/spy_pso.csv)

```
import pandas as pd
import numpy as np
import talib

history = pd.read_csv(
    "https://github.com/QuantConnect/Lean/raw/master/Data/equity/usa/daily/spy.zip",
    index_col=0,
    names=["open", "high", "low", "close", "volume"]
)

date = history.index
open_ = history["open"]
high = history["high"]
low = history["low"]
close = history["close"]


period = 8

low_min = low.rolling(window=period).min()  
high_max = high.rolling(window=period).max()  
k = 100 * ((close - low_min) / (high_max - low_min))  

nsk = 0.1 * (k - 50)

ss = talib.EMA(talib.EMA(nsk, timeperiod=5), timeperiod=5)

expss = np.exp(ss)

pso = (expss - 1) / (expss + 1)

pso_df = pd.DataFrame({
    'date': date,
    'open': open_,
    'high': high,
    'low': low,
    'close': close,
    'pso': pso
})

pso_df = pso_df[['date', 'open', 'high', 'low', 'close', 'pso']]

pso_df.to_csv("spy_pso.csv", index=False)
