### ISSUE TITLE
Relative Volume (RVOL) Indicator

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#4165]
#### Expected Behavior
Support "Relative Volume (RVOL)" Indicator
https://www.smbtraining.com/blog/relative-volume-rvol-defined-and-how-we-use-it

#### Actual Behavior
No implementation of "Relative Volume (RVOL)" indicator

#### Potential Solution
Implement "Relative Volume (RVOL)" Indicator

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by bulbbeing** [comment]
[RVOL - Beasley Savage.zip](https://github.com/QuantConnect/Lean/files/4358221/RVOL.-.Beasley.Savage.zip)

**Comment by jaredbroad** [comment]
Thank you for the dataset @bulbbeing

**Comment by LouisSzeto** [comment]
[spy_rvol.csv](https://github.com/QuantConnect/Lean/files/10814231/spy_rvol.csv)

**Comment by ikamanu** [comment]
I believe Jovad implemented this indicator already, no?

**Comment by Martin-Molinero** [comment]
Believe your right @ikamanu, thank you for catching this 👍. Duplicate https://github.com/QuantConnect/Lean/issues/5746 and PR implementation https://github.com/QuantConnect/Lean/pull/5747
