### ISSUE TITLE
Squeeze Momentum Indicator

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#4166]
#### Expected Behavior
Supports "John Carter's TTM Squeeze Momentum Indicator"

#### Actual Behavior
No implementation of "Squeeze Momentum Indicator"

#### Potential Solution
Implement "Squeeze Momentum Indicator".  Add unit tests

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jdharmon** [comment]
Is this John Carter's TTM Squeeze?

**Comment by steve-goswell** [comment]
Is there an ETA on this new indicator?

**Comment by jdharmon** [comment]
@steve-goswell I implemented this a while ago, but haven't had time to get the tests against external data working. 

The exact formula for calculating momentum is not public. I based my implementation on what I could find. I think it is close enough to use as an indicator. If you compare my implementation with the indicator in your trade platform, the momentum histogram values will not match. However, increasing, decreasing, and whether you're above or below 0 should be consistent.

Feel free to take a look at [Squeeze.cs](https://github.com/jdharmon/Lean/blob/feature-4166-squeeze-momentum/Indicators/Squeeze.cs) and [SqueezeMomentum.cs](https://github.com/jdharmon/Lean/blob/feature-4166-squeeze-momentum/Indicators/SqueezeMomentum.cs) in [feature-4166-squeeze-momentum](https://github.com/jdharmon/Lean/pull/new/feature-4166-squeeze-momentum).

**Comment by steve-goswell** [comment]
many thanks! I'll take a look at the code.  are there any plans to add this to the list of indicators? 

https://www.quantconnect.com/docs/algorithm-reference/indicators

**Comment by AlexCatarino** [comment]
Hi @jdharmon, what is the source of the formulae you used and the data for comparison?

**Comment by jdharmon** [comment]
@AlexCatarino Links to the formulas are in the comments.

    /// <remarks>
    /// Adapted formulas from
    /// https://school.stockcharts.com/doku.php?id=technical_indicators:ttm_squeeze and
    /// https://freethinkscript.blogspot.com/2009/05/ttm-like-squeeze-indicator-with.html
    /// </remarks>

When I developed the indicators, I used data downloaded from AlphaVantage and cross-checked against thinkorswim. In my testing, my indicators matched the indicator in thinkorswim. I only picked a few places in recent history where the squeeze fired or the histogram crossed 0.
    
For unit testing, I used test data from one of the existing TestData files; `spy_bollinger_bands.txt`, I believe. I could never seem to find the time to go line-by-line in the `spy_squeeze.csv` file and validate that the data is correct. The bug may be in the test data or in my code. I'm not sure.

**Comment by LouisSzeto** [comment]
[spy_smi.csv](https://github.com/QuantConnect/Lean/files/10814191/spy_smi.csv)

**Comment by LouisSzeto** [comment]
[spy_smi.csv](https://github.com/QuantConnect/Lean/files/13114110/spy_smi.csv)
Columns: "SPY high" "SPY low" "SPY close" "SMA" "BB high" "BB low" "KC high" "KC low" "Squeeze on?"

Script:
```
import talib

qb = QuantBook()

spy = qb.AddEquity("SPY", Resolution.Daily).Symbol

history = qb.History([spy, qqq], datetime(1998, 1, 1), datetime(2023, 2, 23))

close = history.loc[spy].close
high = history.loc[spy].high
low = history.loc[spy].low

high_bb, sma, low_bb = talib.BBANDS(close, 20, 2)
bb = pd.concat([sma, high_bb, low_bb], axis=1).dropna()
bb.columns = ['sma', 'bb high', 'bb low']

tr = talib.TRANGE(high, low, close)
sma_tr = talib.SMA(tr, 20)
upper_kc = sma + sma_tr * 1.5
lower_kc = sma - sma_tr * 1.5
kc = pd.concat([upper_kc, lower_kc], axis=1).dropna()
kc.columns = ['kc high', 'kc low']

smi = pd.concat([bb, kc], axis=1).dropna()
smi['squeeze on'] = (smi['kc high'] > smi['bb high']) & (smi['kc low'] < smi['bb low'])
smi["high"] = high
smi["low"] = low
smi["close"] = close
smi = smi.iloc[:, [6, 7, 8, 0, 1, 2, 3, 4, 5]]
smi.to_csv("spy_smi.csv", header=False)
```
