### ISSUE TITLE
Arms Index (TRIN) Indicator

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#4168]
#### Expected Behavior
Support Arms Index (TRIN) Indicator
https://www.investopedia.com/terms/a/arms.asp

#### Actual Behavior
No support for Arms Index (TRIN) Indicator

#### Potential Solution
Implement Arms Index (TRIN) Indicator. Add unit tests

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by bulbbeing** [comment]
[TRIN - HPotter.zip](https://github.com/QuantConnect/Lean/files/4358228/TRIN.-.HPotter.zip)

**Comment by Adalyat** [comment]
@bulbbeing , could you clarify how did you generate your data and which formula did you use to calculate TRIM values based on OHLC and Volume for single Stock?
