### ISSUE TITLE
Typo on DockerFile option 1 and..

### ISSUE THREAD

**Issue by auwsom** [QuantConnect/Lean#4169]
Hi All, trying to set up from DockerHub repo (docker pull quantconnect/lean) and then trying to reenter the install process from the DockerFile at https://github.com/QuantConnect/Lean/blob/master/Dockerfile, and just noticed a trivial typo. It should be:
mv /root/Lean-master/ /root/Lean
not:
mv /root/Lean-master /root/Lean

**Comment by auwsom** [comment]
Moving this auxiliary info to another comment. Its about using a Small instance instead of Micro, at least for building Lean, on Google Cloud Platform, for any future web searchers on this error.


Thought I would point it out. I don't see a guide to installing from the DH image although it looks like it is actively being updated. I'm installing to a GCP instance to see what the cost comes out to. 

It's currently stuck on the line: msbuild QuantConnect.Lean.sln /property:Configuration=Release
..with error:
```
Project "/root/Lean/Indicators/QuantConnect.Indicators.csproj" (11:5) is building "/root/Lean/Common/QuantConnect.csproj" (12:6) on node 1 (default targets).
PrepareForBuild:
...
Data/Custom/TradingEconomics/TradingEconomics.Event.cs(9308,22): warning CS1570: XML comment has badly formed XML -- 'Reference to undefined entity 'P'.' [/root/Le
an/Common/QuantConnect.csproj]
Data/Custom/Fred/ICEBofAML.cs(2140,467): warning CS1570: XML comment has badly formed XML -- 'Reference to undefined entity 'P'.' [/root/Lean/Common/QuantConnect.c
sproj]
```
..and its causing the the instance to freeze and need to be reset.

Happy to open a separate issue. It looks like this is just when installing specific Indicators, which I may try removing to finish installation. Any suggestions appreciated! thanks

EDIT: looks like Google wanted me to increase the instance level, and running on Small seems to be working.. Yes, it has fully built now.

**Comment by jaredbroad** [comment]
Thank you @auwsom I've made a note to delete/clean up the whole docker file here: https://github.com/QuantConnect/Lean/issues/4176

I'll close this for now but it'll be tagged in the other issue so we'll be sure to clean it up.
