### ISSUE TITLE
Can not build Lean:Algorithm from Docker container

### ISSUE THREAD

**Issue by Sutyke** [QuantConnect/Lean#4172]
#### Expected Behavior
d@dpc:~/Lean$ docker build -t quantconnect/lean:algorithm -f Dockerfile .

Docker container should be created

#### Actual Behavior
Error received:

Sending build context to Docker daemon    564MB
Step 1/5 : FROM quantconnect/lean:foundation
 ---> 7f631430dc6a
Step 2/5 : MAINTAINER QuantConnect <contact@quantconnect.com>
 ---> Using cache
 ---> a511adb4a824
Step 3/5 : COPY ./Launcher/bin/Release /root/Lean/Launcher/bin/Release
COPY failed: stat /var/lib/docker/tmp/docker-builder415840919/Launcher/bin/Release: no such file or directory

#### System Information
Ubuntu 18.04

**Comment by jaredbroad** [comment]
DockerfileLeanFoundation builds correctly, the supplied application file is mostly for running your own build of LEAN. We'll remove it from the repository to make it cleaner.  https://github.com/QuantConnect/Lean/issues/4176
