### ISSUE TITLE
Not possible to build Quantconnect/Jupyter from docker

### ISSUE THREAD

**Issue by Sutyke** [QuantConnect/Lean#4173]
# Expected Behavior
docker build -t quantconnect/jupyter -f DockerfileJupyter .
Docker container should be created

# Actual Behavior
Error received:
Step 10/18 : COPY ./Launcher/bin/Debug/* ${WORK}
COPY failed: no source files were specified

# System Information
Ubuntu 18.04

**Comment by Martin-Molinero** [comment]
Hey @Sutyke,
Lean has to be built and available in the location `./Launcher/bin/Debug/*` for it to work and note that `.` folder is where the Dockerfile is.
We've made a related issue to improve usability https://github.com/QuantConnect/Lean/issues/4176
