### ISSUE TITLE
Update to QCUWeatherBasedRebalancing.py

### ISSUE THREAD

**Issue by haxdds** [QuantConnect/Lean#4181]
#### Expected Behavior

[QCUWeatherBasedRebalancing](https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/QCUWeatherBasedRebalancing.py) imports custom historical weather data and then rebalances its portfolio based on that data.
#### Actual Behavior

The sources for weather data on QCUWeatherBasedRebalancing is outdated.
#### Potential Solution

Replace the sources for weather data
#### Reproducing the Problem

On [QCUWeatherBasedRebalancing.py](https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/QCUWeatherBasedRebalancing.py), the links for weather data return 404 errors.
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment]
Closed by #4252 and #4255
