### ISSUE TITLE
nUnit Migration

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [QuantConnect/Lean#4201]
I was just wondering if there's a reason not to migrate to a more recent nUnit, like 3. If not I think I will start contributing with this

**Comment by Leonardo-Ferreira** [comment]
well yeah... I was able to update it but the CI was not ready for it... who can help me here?

**Comment by OsirisTerje** [comment]
Hi!  Can you explain what was the issue with the CI?   

Just guessing:  Checked one project, and the adapter was not included there.  It should be included with all unit tests projects.
