### ISSUE TITLE
Enable bi-directional sync of projects

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [QuantConnect/Lean#4206]
#### Expected Behavior
Work on algorithm through the algorithm lab, go home, open up visual studio and sync the changes to my local environment. Make changes, upload back to QC's servers, go elsewhere and work through the algorithm lab again. Rinse and repeat.

#### Actual Behavior
Open up visual studio and realize that I can't download any of my project data. I can only upload. If I made changes in my algorithm lab, I have to remember which files were updated and copy/paste into my local env. Hopefully I didn't miss anything, otherwise when I upload to QC I might overwrite any progress I've made.

#### Potential Solution
To be honest I haven't looked at the source code for the VS extension and I doubt I'd be able to contribute - but since you can already upload to QC's storage it shouldn't be too difficult to download from it. Ideally, projects should be synced with a user-specified git repository/account. That way I can reference my personal repos (projects) from both QC and my local setup.

#### Reproducing the Problem
Everything as-is.

#### System Information
Windows 10, Google Chrome, Visual Studio 2019 with QC extension, Python 3.7+

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
Thanks @JakeTheSnake3p0 this will soon be deprecated and replaced with our skylight synchronization project which is a cross-platform alternative, and does bidirectional sync. Once released we will remove this from LEAN but you're free to keep a copy of its source and maintain-extend as required.
