### ISSUE TITLE
Anaconda on version 3.7

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [QuantConnect/Lean#4208]
#### Expected Behavior
Tests to run successfully after installing latest version of python and anaconda.

#### Actual Behavior
Test don't run due to "libpython3.6m.dylib" not being found because anaconda now uses "libpython3.7m.dylib". Renaming the 3.7 to 3.6 doesn't work. Mapping 3.6 to 3.7 also doesn't work

#### Potential Solution
Updating the decencies to newer versions of python and anaconda

#### Reproducing the Problem
Fresh installation of environment on mac osx

#### System Information
MAC OSX => MOJAVE latest update
Python --version => 2.7.16
Python3 --version => 3.6.8
python3.7 --version => 3.7.4
Anaconda => 4.8.2

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment]
Hi @Leonardo-Ferreira ,
We have already successfully tested support for Python 3.7, but we haven't pulled the trigger yet, because [Pythonnet Team](https://github.com/pythonnet/) is working on [modernisation](https://github.com/pythonnet/pythonnet/projects/6) that will make it agnostic to the Python version in use.

**Comment by Leonardo-Ferreira** [comment]
Thats sounds very promising! I noticed that our fork is very behind, so if you need help, let me know

**Comment by jaredbroad** [comment]
Pending modernization project: https://github.com/pythonnet/pythonnet/projects/6
