### ISSUE TITLE
What is IKVM used for?

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [QuantConnect/Lean#4214]
I noticed that the launcher project has a ref to the IKVM Nuget package, which was abandoned. I removed it for testing purpose and everything seems to be fine... any reason for it to still be around?

#### Checklist
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by StefanoRaggi** [comment]
@Leonardo-Ferreira 
IKVM is used by the FXCM Brokerage.
Unfortunately, the only FXCM API usable with Mono is the Java SDK, which we made callable from NET via IKVM:
https://github.com/QuantConnect/FXCM

**Comment by Leonardo-Ferreira** [comment]
No it's not, at least not anymore: they have a [Rest API](https://www.fxcm.com/markets/algorithmic-trading/compare-api/)

**Comment by StefanoRaggi** [comment]
Nice! I saw they just added it this year (including live streaming events), so replacing the JavaAPI/IKVM with the Rest API is definitely doable, not sure when though 😃

**Comment by Leonardo-Ferreira** [comment]
and I just noticed, there's the "FOREXCONNECT" which accepts C#... perhaps its even easier than we hoped for
