### ISSUE TITLE
Folder structure is not preserved when "Saving to QuantConnect" through Visual Studio extension

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [QuantConnect/Lean#4220]
Within the algorithm lab, I have multiple libraries, one of which is called "Utilities". Its directory structure is as such:

- Utilities
    - Utilities
        - Statistics.py

This way when I include the Utilities library within another project, all of its files aren't in the root directory. It would look like this:

- Some Rando Project
    - main.py
    - Utilities
        - Statistics.py

For the sake of backups, as well as having started to work on a local environment (Visual Studio), I have made a private git repository which will house all of my scripts related to development on Lean:

- git-repo
    - Utilities
        - Statistics.py
    - Indicators
        - ExampleIndicator.py
    - ...

#### Expected Behavior
In VS solution explorer, right-click a the "Utilities" directory and select "Save to QuantConnect". After selecting the appropriate QC project ("Utilities"), "Statistics.py" should by synchronized to the algorithm lab's "Utilities" library under "Utilities/Statistics.py".

#### Actual Behavior
"Statistics.py" ends up being written to the root directory of the "Utilities" library and the resulting structure becomes:

- Utilities
    - Statistics.py
    - Utilities
        - Statistics.py

#### Potential Solution
Unknown; though it seems like a trivial problem to solve.

#### Reproducing the Problem
See 'Expected Behaviour'.

#### System Information
Windows 10, Visual Studio with QC extension installed, Anaconda using Python 3.6.8

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Thanks @JakeTheSnake3p0 this will soon be deprecated and replaced with our skylight synchronization project which is a cross-platform alternative, and does bidirectional sync. Once released we will remove this from LEAN but you're free to keep a copy of its source and maintain-extend as required.
