### ISSUE TITLE
Access Insights Via the API

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#4250]
#### Expected Behavior
SDK Supports accessing insights.

#### Actual Behavior
No insight download for live or backtest

#### Potential Solution
Update API and SDK.  

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Duplicate of https://github.com/QuantConnect/Lean/issues/3099
