### ISSUE TITLE
Q: is Tradier still supported brokerage?  or which brokerage is best supported by Lean to run locally from e.g. home computer?  (for US stocks)

### ISSUE THREAD

**Issue by mingwugmail** [QuantConnect/Lean#4254]
Hi,

I searched on the Google groups, but I cannot find the current status of brokerage support, I'm interested in US stocks.

E.g.: on the  Supported Brokerages section of this QC page:
https://www.quantconnect.com/docs/home/home#Home-Supported-Brokerages

Tradier is not listed, and I search on the Google groups and on the web, but didn't find much information about it.

The only other choice is IB, however on Google groups 
https://groups.google.com/forum/#!searchin/lean-engine/which$20brokerage%7Csort:date
seems people complain about lots of connection or data issues with IB.

So I'm wondering which brokerage is best supported by Lean to run locally from e.g. home computer, for US stocks?  and any reference doc how to set it up?

Thanks for any help.

**Comment by AlexCatarino** [comment]
Hi @mingwugmail ,
We have dropped support for Tradier in QuantConnect Cloud, but the latest implementation can still be found in Lean for anyone who wants to use it.

All of the [supported brokerages](https://www.quantconnect.com/docs/home/home#Home-Supported-Brokerages) can be used locally. For US stocks, we can use IB and Alpaca. There are no docs on how to set them up at the moment. For help, please open a thread in the [Community Forum](https://www.quantconnect.com/forum).
