### ISSUE TITLE
Q: can I set TrailingStopRiskManagementModel for each symbol in MultipleSymbolConsolidationAlgorithm.cs?

### ISSUE THREAD

**Issue by mingwugmail** [QuantConnect/Lean#4257]
Suppose my algorithm is trading both QQQ and TQQQ, using:

https://github.com/QuantConnect/Lean/blob/master/Algorithm.CSharp/MultipleSymbolConsolidationAlgorithm.cs#L81

```
public override void Initialize() {
    ...
    SetRiskManagement(new TrailingStopRiskManagementModel(maximumDrawdownPercent));

}
```

Looks like this is a global property that I can set only once, i.e. QQQ & TQQQ will use the same percentage as trailing stop.

I would like to set different trailing stop percentage for different symbols.

Is this possible?

**Comment by AlexCatarino** [comment]
Hi @mingwugmail ,
Could you please use the [Community Forum](https://www.quantconnect.com/forum) to ask how Lean Framework Models work?

Answering your question: yes, this model assumes the same maximum drawdown percent to define the trailing stop. If you want to set different values for different securities, you will need to create a custom risk management model. Please check out the [docs](https://www.quantconnect.com/docs/algorithm-framework/risk-management) for more details.
