### ISSUE TITLE
Add Optional Parameter to NotificationManager.Web To Allow Headers

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4270]
#### Expected Behavior
Be able to send Web notification with headers.

#### Actual Behavior
Not supported.

#### Potential Solution
Add `IEnumerable<KeyValuePair<string, string>> headers` to `NotificationManager.Web`:
```csharp
public bool Web(string address, object data, 
    IEnumerable<KeyValuePair<string, string>> headers) {
}
public bool Web(string address, object data, 
    PyObject headers) {
}
```
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by fbanke** [comment]
I would like to contribute, but I don't see a way to implement it in the source code here on Github. The actual handlers that make the webrequest seem to be part of the live trading platform, or am I missing something?
