### ISSUE TITLE
Options Algorithm Causing Mono Native Unhandled Exception 

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4279]
#### Expected Behavior
Options algorithm runs successfully in QuantConnect Cloud.

#### Actual Behavior
We get the following exception in some options algorithms:
```
[ERROR] FATAL UNHANDLED EXCEPTION:ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0 [vsyscall],Native stacktrace:, /usr/bin/mono() [0x4b9890], /usr/bin/mono() [0x4305ae], /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390) [0x7f3f73c5c390], /usr/bin/mono() [0x6730cf], /usr/bin/mono() [0x696425], /usr/bin/mono() [0x6ab3c0], /usr/bin/mono() [0x6aca9e], /usr/bin/mono() [0x69ed5a], /usr/bin/mono() [0x6cdc95], /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f3f73c526ba], /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f3f7377241d],Debug info from gdb:,mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb,=================================================================,Got a SIGSEGV while executing native code. This usually indicates, a fatal error in the mono runtime or one of the native libraries ,used by your application.,==============================================================
```
or the algorithm stops with any error indication.

#### Reproducing the Problem
Options algorithm running in QuantConnect Cloud.

#### System Information
QuantConnect Cloud (Linux)

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Backend infrastructure has been updated and this issue is not reproducible anymore
