### ISSUE TITLE
Pushing cash balance updates from IBrokerage

### ISSUE THREAD

**Issue by jameschch** [QuantConnect/Lean#428]
It may be this is already possible, in which case, would appreciate someone pointing this out. It would be really useful to be able to push cash balance updates from the brokerage to the algorithm. Currently cash balances are only updated on initialization and on a daily schedule as far as I can tell.

My use case on Bitfinex: 

1. I have USD from a BTCUSD leveraged trade in trading wallet.
2. I transfer the USD from the trading wallet to the exchange wallet.
3. I make discretionary trades to convert USD to BTC.
4. I transfer btc to the trading wallet.
5. The algorithm makes leveraged trades with the correct cash balance.

The wss subscription will push wallet updates for each of these wallet transfers, and I am consuming them, I just need to push the updates. I'm considering exposing the method BrokerageTransactionHandler.PerformCashSync() to the brokerage. Is there already a way to do this? Any better ideas?

edit: Another option would be calling SecurityPortfolioManager.SetCash() directly. Is this advisable?

**Comment by jaredbroad** [comment]
Correct we currently re-sync each day - which was intended to catch small differences like fees / interest (not large ones like withdrawals). To handle your use case we need "journal entry" events exposed by the brokerage via an event handler -- and having the BTH bind to the brokerage journal event - and trigger a cash sync when there's a cash movement.

The issue we found was syncing too often caused weird jumps / loss in state if we synced before or after a trade was withdrawn from the available cash. IB for example delays withdrawing the cash for a few minutes meaning we can't rely on them for "TotalPortfolioValue" state. 

A complete PR here would need through testing for all the brokerages to make sure they don't loose state   (e.g. portfolio value jumps 100% for 1-2 minutes after placing a trade)

**Comment by jameschch** [comment]
Thanks. This makes sense. I noticed the defensiveness around the calls to PerformCashSync with relation to fills. Could this be implemented generally and then enabled on a brokerage by brokerage basis, perhaps as part for the BrokerageModel? I get the feeling you don't think this would be of great utility to any other brokerages.

**Comment by jaredbroad** [comment]
It would be of great utility! We just need to make sure it doesn't break existing behavior :)

**Comment by jameschch** [comment]
Right. I will look into this. For an event drive approach I would follow the pattern of Brokerage.OnOrderEvent.

**Comment by jameschch** [comment]
The code to do this is just commented out in BrokerageTransactionHandler.HandleAccountChanged. Will just add a clause with IBrokerkageModel.AllowAccountUpdates
