### ISSUE TITLE
Major bug! Skylight recursively copies libraries (projects) and botches hierarchy

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [QuantConnect/Lean#4283]
### Environment
Assume [User Account] is the root directory when logging into QC algorithm lab. A user can create projects that are also semantically referred to as "libraries".  "Library" is a folder I made through the algorithm lab to store my "libraries" (re: reusable projects). Typically you would see "libraries" (projects) such as "Utilities", "Alphas", "Algorithms", "Insights", and "Indicators". I feel my intent is self-explanatory at this point, but for further clarification:

I have multiple Algorithms, each of which rely on overlapping and non-overlapping use of indicators, alphas, insights, etc. So if I were to have a project called "ExpectedRangeAlgorithm", I would need to import the "Indicators" project and use specific indicators found therein. Same as in my other project called "MeanReversionAlgorithm". And by 'import', I mean akin to using `import pandas as pd`. I don't actually want to duplicate files/folders into my other projects, I only want to be able to reference them as any other python library that QC has whitelisted.

Due to the way QC handles user libraries, when importing to another project it actually imports the directory structure as-is. So for example:

- Project called "Test" has a single file called "main.py"
- Project called "Utilities" has a file called "main.py" and a file called "Statistics.py"
- Project "Test" imports "Utilities" using the algorithm lab UI and the resulting structure becomes:
> [User Account]/Test
> [User Account]/Test/main.py
> [User Account]/Test/main.py
> [User Account]/Test/Statistics.py

Yes, that's two "main.py" files in the same project, and a Statistics module no longer namespaced to the library it belongs to! In order to combat this issue I decided that for all of my "library" projects I would create a directory in them that matches the name of the project. So in the "Utilities" project, the structure would look like this:
> [User Account]/Library/Utilities
> [User Account]/Library/Utilities/Utilities
> [User Account]/Library/Utilities/Utilities/main.py
> [User Account]/Library/Utilities/Utilities/Statistics.py

So the resulting structure in "Test" after importing "Utilities" would be:
> [User Account]/Test
> [User Account]/Test/main.py
> [User Account]/Test/Utilities
> [User Account]/Test/Utilities/main.py
> [User Account]/Test/Utilities/Statistics.py

This way in Test/main.py I could use the line `from Utilities import Statistics` and everything would work as expected. Even though I've been having caching issues with the python notebook and an unexpectedly high number of 'code changes' when QC emails me my monthly stats, things were working as expected.

This leads us to my experimental use of Skylight to synchronize my algorithm lab to my local computer. The initial sync proved successful, however after a few short seconds things went haywire.

#### Expected Behavior
Syncing should replicate the directory structure between the algorithm lab and my local computer exactly as shown in the algorithm lab. I would therefore expect imported libraries to be symbolically linked directories to the actual location of the linked project.

For example, if the algorithm lab had the following true directory structure:
> [User Account]/Test
> [User Account]/Library/Utilities

Where in each of those projects you have the structure as defined previously (main.py, Statistics.py, etc.).

I would expect the local file system structure to be:
> [User Account]/Test
> [User Account]/Library/Utilities
> [User Account]/Test/Utilities (symlinked to [User Account]/Library/Utilities/Utilities)

#### Actual Behavior
Of course this highlights the problem with how QC handles user library imports to begin with. What would happen if I had main.py in the root of Test and another main.py in the root of Utilities? In the algorithm lab it doesn't care much for whatever reason, but in my local filesystem it would be impossible to synchronize these files as you would have a filename conflict.

In any case - all of this is only to set the stage for the actual bug report. When I synchronized using Skylight, it began to recursively copy all of my projects into one another and sync back to the algorithm lab which in turn synced back to my local environment. Queue the circus music and my directory structure is too mangled to make sense of in many places and I can no longer work in the algorithm lab due to slow loading because of all of the files that were created.  But there's a common theme observed in the replication in that Skylight simply writes the file contents of linked libraries as if they were actual files belonging to the local project, and also it creates files in the root of the project that belong only in a subdirectory of that project while renaming the file.

So working off of our Utilities example, the resulting structure after syncing would become:

In the algorithm lab (I use quotes around the filenames to explicitly show that it is not a directory but a file):
> [User Account]/Utilities/Utilities
> [User Account]/Utilities/Utilities/main.py
> [User Account]/Utilities/Utilities/Statistics.py
> [User Account]/Utilities/"Utilities\\main.py"
> [User Account]/Utilities/"Utilities\Statistics.py"

And in my local file system structure:
> [User Account]/Utilities/Utilities
> [User Account]/Utilities/Utilities/main.py
> [User Account]/Utilities/Utilities/Statistics.py
> [User Account]/Utilities/"Utilities main.py"
> [User Account]/Utilities/"Utilities Statistics.py"

You read that right, the backslash in the algorithm lab file converts to a space in the local file system (likely due to invalid characters in the filename). Couple this issue with the fact that the synchronization duplicates library files that are imported into other projects and you end up with something like the following in the algorithm lab:
> [User Account]/Test
> [User Account]/Test/main.py
> [User Account]/Test/Utilities/Utilities
> [User Account]/Test/Utilities/Utilities/main.py
> [User Account]/Test/Utilities/Utilities/Statistics.py
> [User Account]/Test/Utilities/"Utilities main.py"
> [User Account]/Test/Utilities/"Utilities Statistics.py"

Keep in mind that the Utilities directory should ONLY be a linked library - but now it's a bunch of real files/folders in the Test project. So not only do I have real files/folders in the Test project under the "Utilities" folder, I ALSO have a linked library called "Utilities" which now has its own mangled structure due to the botched sync.

I suspect the way QC handles user libraries and the way Skylight handles syncing points to the reason why I've been having caching issues in my python notebooks as well as why I've been getting emails from QC saying:

> ...535,240 LINES CHANGED
> ...You were more productive than 100% of the community, with 22,465,968 code updates. In total, you compiled your code 937 times.

 

#### Potential Solution
Fix the way QC references libraries (do not import to the root of the project; import as a directory that matches the name of the library). And in Skylight, those library references should be symlinked to the actual project directory. If duplicate file URLs are detected, a build error should occur. When browsing through linked libraries in the algo lab, adding new files should actually add it to the linked library project and NOT to the project we're currently in.

So as far as Skylight syncing goes, assuming the real directory structure in the algo lab is:
> [User Account]/Library/Utilities
> [User Account]/Library/Utilities/main.py
> [User Account]/Test
> [User Account]/Test/main.py

And the "Test" project imports "Utilities" in the algo lab, the local filesystem after syncing should be:
> [User Account]/Library/Utilities
> [User Account]/Library/Utilities/main.py
> [User Account]/Test
> [User Account]/Test/main.py
> [User Account]/Test/Utilities (symlinked to [User Account]/Library/Utilities)
> [User Account]/Test/Utilities/main.py (behaves exactly like it should to the parent symlinked directory)

#### Reproducing the Problem

1. Create a brand new user account in QC
2. Create a new project called "Test" with "main.py" in root
3. Create a new project called "Utilities" with "main.py" in root, "Utilities" directory in root and "Statistics.py" in that folder.
4. Move the "Utilities" project into a folder called "Library" just for the sake of clarity of its use
5. In the "Test" project, import the "Utilities" project
6. In Test's main.py, write `from Utilities import Statistics` and write/user whatever method you want to in order to validate that it's working. Build your project to confirm no issues.
7. Sync with Skylight and witness the chaos

#### System Information
Windows 10 x64

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by JakeTheSnake3p0** [comment]
As an addendum:

Skylight also doesn't upload directories which don't already exist in the algo lab. To see this, create a new directory called "NewFolder" in:
> [Local User Account]/[User Name]/NewFolder

Where [User Name] is the directory that Skylight creates in your userprofile folder in Windows for syncing your projects.

Put any python file in there and nothing gets synced back to the algo lab.

However if you create NewFolder in the algo lab, sync to your local computer, then make changes, those changes are reflected back to the algo lab.

---

Also when I tried fixing one of my libraries through syncing Skylight again I believe I know why the hierarchies are fubar. Apparently Skylight/QC doesn't handle paths in an OS-agnostic way. The file path for a file in a subfolder of a project will have a backslash in it. So when it uploads to QC, the following local folder structure:
> [User Account]/Utilities
> [User Account]/Utilities/Utilities
> [User Account]/Utilities/Utilities/Statistics.py

becomes in the algo lab:
> [User Account]/Utilities
> [User Account]/Utilities/Utilities\Statistics.py

on the 1st sync. Then when it syncs back to the local environment with what it thinks is a new file called "Utilities\Statistics.py", Windows doesn't like the backslash in the filename so it renames it to "Utilities Statistics.py". Also, since no folder was uploaded to QC, it gets removed in the local file system after sync and the local folder structure becomes:
> [User Account]/Utilities/Utilities Statistics.py

which then uploads back to QC and the resulting QC folder structure becomes:
> [User Account]/Utilities
> [User Account]/Utilities/Utilities\Statistics.py
> [User Account]/Utilities/Utilities Statistics.py

**Comment by jaredbroad** [comment]
Thanks Jake closed as moved to the private Skylight repository, but copied the note there.
