### ISSUE TITLE
StopLimit order StopTriggered flag not being set

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#4285]
#### Expected Behavior

- `StopLimit` orders `StopTriggered` flag is being set correctly
#### Actual Behavior

- `StopLimit` orders `StopTriggered` flag is just being set by the `FillModel` in its own copy of the order.
#### Potential Solution

- The `StopTriggered` flag is set by brokerage driven code. For example believe IB does send events for this
- The flag could potentially be set by data-driven code path (not exact)
- The `StopTriggered` is only an internal feature of the `FillModel` in backtesting
#### Reproducing the Problem

Submit StopLimit order
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
- Fill models should send information back to the Backtesting Brokerage -- and trigger and event there to notify subscribers.
 - BrokerageTransaction Handler would update the root/master order properties.
