### ISSUE TITLE
Add Optional Headers to Notify.Web()

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#4290]
#### Expected Behavior
Ability to customize the headers on a Notify.Web ping.

#### Actual Behavior
Not configurable

#### Potential Solution
Extend the Notify with an optional IDictionary header collection; pass through to the execution system.  

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Duplicate of https://github.com/QuantConnect/Lean/issues/4270
