### ISSUE TITLE
Broken Dependencies for Win10 Installation

### ISSUE THREAD

**Issue by Snowman418** [QuantConnect/Lean#4304]
#### Expected Behavior
Python BasiCTemplateFrameworkAlgorithm.py runs and compiles with Win10 Visual Studio 2019.

#### Actual Behavior
Run fails "Unable to load DLL python36".

#### Potential Solution
Divorce yourselves from the Anaconda framework. Provide comparability with any Python version > 3 and not hardcode to 3.6.

#### Reproducing the Problem
Follow the installation instructions for using Windows and Python. Anaconda is broken and does not install properly (activate.bat script is not created, which is necessary for Anaconda to even run). Too many LEAN project dependencies rely upon Anaconda for functionality. Recommend divorcing yourselves from that configuration.

#### System Information
Win10 fresh install, Anaconda3 (python 3.6), Visual Studio 2019.

**Comment by adam-may** [comment]
@Snowman418 - note that the chose of python version is due to the dependency on pythonnet (https://github.com/pythonnet/pythonnet), which provides the interop between python and the underlying .Net framework.

Therefore supporting any version of python is going to be extremely difficult.

**Comment by jaredbroad** [comment]
Waiting on underlying dependency upgrade. WIP.
