### ISSUE TITLE
Add Feature to Identify Weekly Option

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4307]
#### Expected Behavior
Be able to easily identify whether a given option, option contract, option symbol is standard or weekly.

#### Actual Behavior
It's possible to identify the option as standard with 
```csharp
var isStandard = OptionSymbol.IsStandardContract(symbol);
``` 
#### Potential Solution
Adds `IsStandard` and/or `IsWeekly` member to `Option` class. 

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/4341
