### ISSUE TITLE
IQFeed symbol characters for continuous future contracts causes problems with LoadSymbolOnDemand

### ISSUE THREAD

**Issue by scalptrader** [QuantConnect/Lean#4309]
LoadSymbolOnDemand is failing as the code isn't filtering out the new characters DTN introduced for the continuous future contracts.

#### Potential Solution

Filter out unsupported characters IQFeed::LoadSymbolOnDemand

#### Reproducing the Problem

Run a real-time algorithm that uses IQFeed and requests some minute data

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/4310
