### ISSUE TITLE
Respect Set Start and End DateTime 

### ISSUE THREAD

**Issue by mingwugmail** [QuantConnect/Lean#4312]
#### Expected Behavior
Able to run a backtest on the algorithm dates specified. Algorithm EndDate is not modified. 

Ideally able to support DateTime as well. 

#### Actual Behavior
End-date is rounded down to the previous date.

#### Potential Solution
Unknown.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Thank you for the issue @mingwugmail we'll try and look into it.

**Comment by jaredbroad** [comment]
The relative cost-benefit of skewing all the statistics vs adding another half day of backtest that very few will utilize is not worth the expense. If you want another day of backtesting for this edge case please add a day to your end time. You can read it as "end when date equal to the end date".

**Comment by MagicCodeCannot** [comment]
Hello guys @jaredbroad I have found this code in QCAlgorithm.cs 

https://github.com/QuantConnect/Lean/blob/master/Algorithm/QCAlgorithm.cs#L1271
https://github.com/QuantConnect/Lean/blob/master/Algorithm/QCAlgorithm.cs#L1318

Which rounds up the end date (to the end of the day) and round down the start date but is this correct ? if I specify start and end date to be exactly something but it just rounds up/down stuff is this ok? I think this should be fixed

Example: specify start = 1/1/2021 15:00 end = 1/2/2021 16:00
this will round to 1/1/2021 00:00 and end = 1/2/2021 23:59

**Comment by MagicCodeCannot** [comment]
I have opened a new issue because this is closed already https://github.com/QuantConnect/Lean/issues/5241
