### ISSUE TITLE
Review Option Trading Fee Modelling for Interactive Brokers

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4320]
#### Expected Behavior
`InteractiveBrokersFeeModel` reflects IB [fee structure for options]( https://www.interactivebrokers.com/en/index.php?f=1590&p=options1 ).

#### Actual Behavior
`InteractiveBrokersFeeModel` always returns 0.25 rate.

#### Potential Solution
In this statement, [InteractiveBrokersFeeModel.cs#L99](https://app.slack.com/client/T02SZ88UC/G51920EN4/thread/InteractiveBrokersFeeModel.cs#L99), we can use `Security.Price` or `Order.Price` should be set by the `FillModel`.

#### Reproducing the Problem
[USAOptionFee](https://github.com/QuantConnect/Lean/blob/master/Tests/Common/Orders/Fees/InteractiveBrokersFeeModelTests.cs#L96) expected value is wrong. For 1000 contracts of an option at $100, we should not expect $250, but $700.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by aricooperman** [comment]
This happens everywhere the fee model is used, for instance, checking margin or buying power will get a wrong fee calculation as well

**Comment by aricooperman** [comment]
I can't think of how to solve this without changing significantly how the fee model works. In my mind, it should be based on a set of fills, not an order. For instance, say you put in an order and it partially fills at two different premium tiers (for example a buy order that clears the size at 0.05 and then partially fills some at 0.06), in this case, I think the premium would be pro-rata. This may not be true and I am going to ask IB, however, even if it isn't, then you need to know all the fills to properly calculate the fee.

Maybe it needs two API's, one that takes OrderFeeParameters and one that takes a list of fills or similar enclosing param object. The first could be used for any of the pre-send checks using conservative values, and the second in the transaction handler to calculate actual fees.

**Comment by jaredbroad** [comment]
Addressed by setting an approximation for the monthly volume at the start of the algorithm or via the security initializer

https://github.com/QuantConnect/Lean/blame/master/Common/Orders/Fees/InteractiveBrokersFeeModel.cs#L51
[9:25](https://quantconnect.slack.com/archives/D6YG8072A/p1676643934641349)

```        
/// <summary>
        /// Initializes a new instance of the <see cref="ImmediateFillModel"/>
        /// </summary>
        /// <param name="monthlyForexTradeAmountInUSDollars">Monthly FX dollar volume traded</param>
        /// <param name="monthlyOptionsTradeAmountInContracts">Monthly options contracts traded</param>
        public InteractiveBrokersFeeModel(decimal monthlyForexTradeAmountInUSDollars = 0, decimal monthlyOptionsTradeAmountInContracts = 0)
        {
            ProcessForexRateSchedule(monthlyForexTradeAmountInUSDollars, out _forexCommissionRate, out _forexMinimumOrderFee);
            Func<decimal, decimal, CashAmount> optionsCommissionFunc;
            ProcessOptionsRateSchedule(monthlyOptionsTradeAmountInContracts, out optionsCommissionFunc);
            // only USA for now
            _optionFee.Add(Market.USA, optionsCommissionFunc);
        }
```
