### ISSUE TITLE
QuantConnect.Securities.SecurityHolding and QuantConnect.Holding should be merged / inherited

### ISSUE THREAD

**Issue by mingwugmail** [QuantConnect/Lean#4333]
These 2 types 'QuantConnect.Holding' and 'QuantConnect.Securities.SecurityHolding' right now are independent,  they should be merged into one, or one inherit from the other.

**Comment by jaredbroad** [comment]
We will not merge them as one is a simple transport DTO the other is am API and portfolio concern which requires more information.
