### ISSUE TITLE
Debug message should be the same in _liveMode or not

### ISSUE THREAD

**Issue by mingwugmail** [QuantConnect/Lean#4335]
Hi,

I'm running my algorithm in live mode & back testing mode, and when I compare the logs, I found they are not consistent, I print some variable value, and then do some calculation, and print that variable again, I want to check (in logs) that variable haven't changed.  But I found in backtesting mode that print-line only show up once.

Eventually I found this line:

https://github.com/QuantConnect/Lean/blob/master/Algorithm/QCAlgorithm.cs#L1850

```
            if (!_liveMode && (message == "" || _previousDebugMessage == message)) return;
```

This filtering is unnecessary, and only cause confusion.

As a normal Lean library user (who didn't dig into the code), I would want to see what I printed *AS IT IS, NO STRING ATTACHED*.

The underlining library shouldn't do any filtering. Because it doesn't know the user's intention!

**Comment by mingwugmail** [comment]
If you really want to filter: 

1) Why should one just detect duplication with the previous 1 message? why not in previous 10 message? why not the whole message queue?  then create a _previousDebugMessageHashMap to detect them all.

2) rename this function as:
```
  DebugNoDupPrevMessage(...)
```

to make the function's intention clear.

Such simple function shouldn't give any confusion & surprise to the user.

**Comment by jaredbroad** [comment]
Hi @mingwugmail this is well-documented behavior. Try and keep API concerns and user-application discussion to the [LEAN forums](https://www.quantconnect.com/forum/discussions/1/lean). 

The solution to your issue is to add the time to your debug messages.
