### ISSUE TITLE
Option Speed Decrease Over Execution Time

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4347]
#### Expected Behavior
Every iteration has sensibly the same duration.

#### Actual Behavior
We have observed a slowdown in iteration speed with options. 

#### Reproducing the Problem
```python
from datetime import timedelta, datetime
from QuantConnect.Securities.Option import *

class LongBrokenWingButterflyAlgorithm(QCAlgorithm):

    def Initialize(self):
        self.SetStartDate(2015, 1, 1)
        x = self.AddOption('SPY')
        x.SetFilter(-1, 1, 0, 31)
        x.PriceModel = OptionPriceModels.CrankNicolsonFD()
        self.SetWarmup(30, Resolution.Daily)
        self.SetSecurityInitializer(lambda x: x.SetMarketPrice(self.GetLastKnownPrice(x)))

    def OnEndOfDay(self):
        self.Debug(f'{self.Time} :: {self.Securities.Count} :: {datetime.now()}')
        #self.Plot("Count", "All", len(self.Securities))
        #self.Plot("Count", "Tradable", len([symbol for symbol, security in self.Securities.items() if security.IsTradable]))
```
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
It seems there are two reasons behind this behavior:
- The most influential in performance is the data itself, to perform selection Lean takes the option symbols from the option quote.zip files, for SPY, on 2015 there are ~3k symbols, on the end of 2019 we have  ~7k symbols. Which causes the selection process to take longer
- The second reason is securities are currently not removed from the SecurityManager collection, increasing time spent of a couple of operations performed during the algorithm loop

**Some backtesting performance sampling**
Short backtest
![image](https://user-images.githubusercontent.com/18473240/81098240-7b8e5c80-8edf-11ea-9e44-5a4a3f41ec43.png)
Long backtest
![image](https://user-images.githubusercontent.com/18473240/81098301-8fd25980-8edf-11ea-9f01-581aa60342b8.png)

**Comment by Martin-Molinero** [comment]
Closing this for now, PR https://github.com/QuantConnect/Lean/pull/4376 improved overall performance significantly and reduced the Lean overhead of a long-running backtest which isn't that significant in comparison with other factors as exposed
