### ISSUE TITLE
Error: The request does not meet the security criteria. Reference: 6db9fd44a

### ISSUE THREAD

**Issue by MislavSag** [QuantConnect/Lean#4361]
I have just signed up to quantconnect platform. Nothing works there!

I clicked on "Algorithm lab" but it returns an error all the time:

The request does not meet the security criteria. Reference: 6db9fd44a

Then, it's asking me over and over again which language I prefer and what color of the theme, even if I have chosen x times.

Then I logged out and can't log in again!

I tried to send a message through a messenger that pops up, but it has frozen!

Then I clicked on community > Lean and its' loading the content forever!

How can anybody use this platform for such sensitive work as trading when nothing works from the beginning?

I wanted to compare it with backtrader, because I find it hard to implement my ml model with backtrader. But haven't find any example of sklearn or keras model plus quantconnect too.

**Comment by Pi-Rr** [comment]
Hi MislavSag, I am a very happy user of QuantConnect, it is an amazing project and is working very well for me and thousands of other users, and maintained by an amazing team!
I think I had the issue you describe in the past, it was just a matter of signing out, clearing the cache of my browser (Google Chrome) and then signing in again.
Definitely worth persevering!

**Comment by MislavSag** [comment]
Sorry, not for me obviously. Lean installation returns several errors too. Files could not be found etc. I spent half a day just trying to install lean and sign up to the platform. Can be closed.
