### ISSUE TITLE
Old issues still open

### ISSUE THREAD

**Issue by adriantorrie** [QuantConnect/Lean#4362]
I've seen numerous issues that have been open for years, some appear to have been completed, others have merges to master, yet are still open.

Willing to pitch in and be part of everything, just wondering what the process is for closing issues (so when I open one, I know it will get resolved).

**Comment by Martin-Molinero** [comment]
Hi Adrian!
> I've seen numerous issues that have been open for years, some appear to have been completed, others have merges to master, yet are still open.

We prioritize and try to tackle as many issues as we can. Each issue is tracked in their own ticket, with their progress/discussion.

> Willing to pitch in and be part of everything, just wondering what the process is for closing issues (so when I open one, I know it will get resolved).

We love and encourage community contributions! We have a "good first issue" label for issues you might want to check out. Also, you can find us in slack to discuss/brainstorm https://www.quantconnect.com/slack
