### ISSUE TITLE
`Error	CA1305	The behavior of 'StringBuilder.AppendFormat

### ISSUE THREAD

**Issue by MislavSag** [QuantConnect/Lean#4367]
I am trying to install lean and use it with python.

I stacked at step:

> Build the solution by clicking Build Menu -> Build Solution (this should trigger the Nuget package restore)
Qhen I click Build Solution multiplie warnings and erros pop up. First error is:
Severity	Code	Description	Project	File	Line	Suppression State
`Error	CA1305	The behavior of 'StringBuilder.AppendFormat(string, object, object, object)' could vary based on the current user's locale settings. Replace this call in 'Log.VarDump(object, [int])' with a call to 'StringBuilder.AppendFormat(IFormatProvider, string, object, object, object)'.	QuantConnect.Logging	C:\Users\Mislav\Lean\Logging\Log.cs	204	Active`

How can I solve this error?

**Comment by jaredbroad** [comment]
Welcome to LEAN @MislavSag! Glad to have you with us but please post user installation issues to the LEAN user-group in the forums here: https://www.quantconnect.com/forum/discussions/1/lean

The LEAN repository is specifically for code issues.
