### ISSUE TITLE
Add Property for Deployment Environment and Algorithm Mode

### ISSUE THREAD

**Issue by omidkrad** [QuantConnect/Lean#4391]
Maybe we can add a `IsLocal` property like in `HttpRequest` class or an Environment property with values "local", "quantconnect-cloud", etc.

Workarounds: check operating system, cloud is linux, or use timezone. I think cloud is EST.

#### Checklist

- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Hi! Maybe another option could be checking the `AlgorithmId`, locally it will use the name of the algorithm or a config/cmdline argument which _could_ always start with `localdeploy` (at https://github.com/QuantConnect/Lean/blob/master/Queues/JobQueue.cs#L104), in the cloud it will be a uid

**Comment by jaredbroad** [comment]
In the Algorithm Manager set a public enum on creation of the algorithm before calling initialize
 - DeploymentTarget.CloudPlatform / LocalPlatform
 - AlgorithmMode.Live / Optimize / Backtest
 - Source data from the job packet
