### ISSUE TITLE
Library Request: Keras.NET

### ISSUE THREAD

**Issue by sherzyang** [QuantConnect/Lean#4419]
#### Expected Behavior
Supports Keras.NET.

#### Actual Behavior
No support.

#### Potential Solution
Install https://www.nuget.org/packages/Keras.NET/ to the foundation.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
`TensorFlow.Keras` has been added to QC cloud
