### ISSUE TITLE
QuantConnect.Report regression with BasicTemplateAlgorithm

### ISSUE THREAD

**Issue by mathpaquette** [QuantConnect/Lean#4424]
#### Expected Behavior

HTML reports should be generated without 

#### Actual Behavior

- Serialization issue: 
![image](https://user-images.githubusercontent.com/4358455/82160621-b3dd5580-9864-11ea-8209-8b2177a7bee3.png)
- Unknown ticks property
![image](https://user-images.githubusercontent.com/4358455/82160682-09b1fd80-9865-11ea-8599-34b84e075214.png)

#### Reproducing the Problem

- from master
- generate BasicTemplateAlgorithm.json
- `QuantConnect.Report.exe --backtest-data-source-file ../../../Launcher/bin/Debug/BasicTemplateAlgorithm.json --report-destination report-test.html`

#### System Information

Windows 10

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by gsalaz98** [comment]
Hey Mathieu,

I've managed to reproduce and fix the deserialization issue, but I'm unable to reproduce the second issue (`unknown property ticks`).

Could you please let me know what version of matplotlib you're running?
I'm currently running version `3.1.2`.

**Comment by mathpaquette** [comment]
@gsalaz98 added some additional info. Ill try to update my libs to match docker's setup.
[debug info.txt](https://github.com/QuantConnect/Lean/files/4659960/debug.info.txt)

**Comment by mathpaquette** [comment]
@gsalaz98 one additional comment, I followed exactly the steps listed here: 
https://github.com/QuantConnect/Lean/tree/master/Algorithm.Python#quantconnect-python-algorithm-project for Windows. Also checked the Docker image and there's no explicit dependency regarding matplotlib.

**Comment by mathpaquette** [comment]
@gsalaz98 upgrading to matplotlib 3.1.2 fixed the issue!
we might need to explicit this in the How to listed above! Thank you!
Cheers.

**Comment by gsalaz98** [comment]
Awesome! I'll make a note of that 👍
