### ISSUE TITLE
Create CI.Powered LEAN Docker Image

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#4425]
#### Expected Behavior
quantconnect/lean:latest would be the latest build of LEAN setup and ready to go.

#### Actual Behavior
There is no latest or tagged versions of docker image.

#### Potential Solution
 - Integrate docker hub update into CI process and push updates programmatically. This should be possible via TravisCI+TravisCISecrets. 

 - Include the build tag and number on tags. Generate a lean:v2-4-8099 tag. This is a magic number of the build number. There's no public source for it at the moment but we can set up a public API once yml ready. Assume a `wget` call to a rest endpoint.

 - Create a `Dockerfile` which is `from quantconnect:lean:foundation` but checks out LEAN master and builds it, then ends with running the LEAN engine. This way `docker run` will not need anything special to work. 

 - Update the run_docker.bat/sh to point to the latest image instead of the foundation to avoid even needing to build LEAN! ❤️ 

#### Reproducing the Problem
https://hub.docker.com/repository/docker/quantconnect/lean/tags?page=1

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by nabeelio** [comment]
Hi @jaredbroad, thanks for opening this and taking this into consideration. 

Just for reference of anyone else looking, my original comment was [here](https://github.com/QuantConnect/Lean/issues/4176#issuecomment-629861382) with some details.

In regards to this GH issue, the main problem with having a container prebuilt with Lean is that the source files are built into the final binary, so having that container for the C# case won't work, it'll just need to be rebuilt with the user's algorithm's files. Though it's OK to have a build for demo, etc, my suggestion is having a container with the source already checked out into it (with it and the master branch having an identical semver tag), and a simple Dockerfile that is something like what's in my example. The problem with that though is the csproj file...

If it's made clear that the workflow is that you use Visual Studio or whatever to create the source files, _and_ that VS has already modified the csproj file to include those source files, then a `Dockerfile` similar to [this](https://github.com/nabeelio/QuantConnectDockerExample/blob/master/QuantConnect.Algorithm.CSharp/Dockerfile) would work, with a) `COPY` of the `CSharp` folder into the container and b) a `COPY` of the `config.json` file. Then run the `nuget`/`msbuild` will run. Then there's no local build, and you can develop/deploy on whatever platform you want. I have a feeling that would clean up some things in your own cloud environment.

I also really recommend using docker-compose over shell scripts, or at least having a `docker-compose` file included as an example. It's easier to do things the Docker way. I have storage/data directories mounted to a NAS drive and it's all started on boot by Docker. You can't do that with a script easily. Also in the container, if you do the `COPY`, most of the parameters of the shell script go away. And the user can modify the docker-compose to mount paths wherever they want; the defaults can just be the local directories. The shell script(s) can just call `docker-compose run`.

My main request was that the csproj format needs to be of the NET Core style, where the source files to build aren't individually listed in the csproj file. I understand this might not be as easy, depending on the earliest Visual Studio version that needs to be supported. This would need to be researched.

However, then it won't matter where the algorithm files are kept, or there's no "magic" in the csproj needing being updated (even though chances are one won't have to touch it), as long as they're placed into the correct folder in the container, the final build will have them (that's what my example repo does). That gives the most flexibility in terms of build/deploy. For me, that means I have a separate repo with only my algo files, and a Dockerfile and docker-compose, and I can run backtests, etc, without having to have Lean checked out locally at all.

**Comment by adam-may** [comment]
In the current feature branch, the Lean codebase is being built. Couldn't this also be a nuget install, provided the version numbers match the docker tag you're intending to build?

**Comment by Martin-Molinero** [comment]
> 
> 
> In the current feature branch, the Lean codebase is being built. Couldn't this also be a nuget install, provided the version numbers match the docker tag you're intending to build?

Hey! We've aligned all versioning under the same system: nuget packets, docker tags, QC cloud versions and github tags too
