### ISSUE TITLE
Avoid linking libpython3.6m.so to /usr/lib/

### ISSUE THREAD

**Issue by nbstrong** [QuantConnect/Lean#4426]
#### Expected Behavior
The program should pull the python library from the conda env /lib/ folder.

#### Actual Behavior
Currently you require linking the lib folder for linux installs:
sudo ln -s $HOME/miniconda3/lib/libpython3.6m.so /usr/lib/libpython3.6m.so

This requires a python 3.6.8 base Anaconda install. What people should do is use a conda environment to install Python 3.6.8. Linking to this file in /usr/lib breaks the environment encapsulation, though.

Manually linking the library like the above is bad practice. Requiring python 3.6.8 is fine, but if you are going to do so you should support conda environments.

#### Potential Solution
Retrieve the library from the python env path.

#### Reproducing the Problem
This can be reproduced on Ubuntu by installing the latest version of Anaconda, making an environment with 3.6.8 and not linking the library using the command above.

#### System Information
Ubuntu 20.04 LTS

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by nbstrong** [comment]
As for now, the better workaround I have found is to set the LD_LIBRARY_PATH in the conda environment.

Resources for this:
https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#macos-and-linux
https://docs.conda.io/projects/conda-build/en/latest/resources/use-shared-libraries.html
https://stackoverflow.com/questions/39298681/anaconda-python-virtualdev-cant-find-libpython3-5m-so-1-0-on-windows-subsystem
https://stackoverflow.com/questions/46826497/conda-set-ld-library-path-for-env-only

**Comment by Martin-Molinero** [comment]
Hey @nbstrong! sorry for the delay here, linking is not required. Removed from the foundation file by https://github.com/QuantConnect/Lean/pull/6558
