### ISSUE TITLE
Library Request: Scikit-TDA

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4430]
#### Expected Behavior
Supports Scikit-TDA.

#### Actual Behavior
No Support.

#### Potential Solution
Install https://scikit-tda.org/ to the foundation.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by nborggren** [comment]
@AlexCatarino 
Has there been any progress on this pull request?  The included packages aren't available for import at this stage.
