### ISSUE TITLE
Update FXCM Error Message

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#4434]
#### Expected Behavior
FXCM Brokerage error message up to date

#### Actual Behavior
https://github.com/QuantConnect/Lean/blob/ae927677f332502c96730a48c58cde0e6688508c/Brokerages/Fxcm/FxcmBrokerage.Messaging.cs#L101

Message old

#### Potential Solution
Update to the new FXCM email.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Marrri4ka** [comment]
Email: pcs@fxcm.com

Template:
Hello FXCM staff,

Please enable Java API for all accounts which are associated with this email address.

Also, please respond to this email address once Java API has been enabled, letting me know that the change was done successfully.

**Comment by trumpslist** [comment]
Sorry this is one of my first additions to this project, does this look good or am I mistaking the given issue.

```

throw new NotSupportedException("FxcmBrokerage.LoadAccounts(): Please enable Java API for all accounts which are associated with this email address." +
                    "Please respond to this email address once Java API has been enabled, letting us know that the change was done successfully, pcs@fxcm.com.");
```

**Comment by trumpslist** [comment]
Updated, my branch naming is messed up (My origin is named "local") however I have added the change in [FxcmBrokerage.Messaging.cs](https://github.com/trumpslist/Lean/blob/local/Brokerages/Fxcm/FxcmBrokerage.Messaging.cs)

**Comment by C-SELLERS** [comment]
I see this error message we are editing has to do with hedging being enabled. Is this still something that needs to be disabled?

The reason I ask is I am a little confused about the email template commented above, as it talks about enabling the Java API? Does that fit this problem? 

If not I'll only update the email and leave the error message the same. I could also create a new template email to add to it.

**Comment by C-SELLERS** [comment]
![image](https://user-images.githubusercontent.com/41277998/85887880-69bd8d00-b79d-11ea-9e69-d11dd649fde5.png)

**Comment by C-SELLERS** [comment]
I see now that we use their Java API. Still poking around with some tests to make sure we have the right error response for this issue.

**Comment by StefanoRaggi** [comment]
@C-SELLERS Hedging and API access are two separate issues:

- An account with Hedging enabled means it can have opposing positions open (both long and short), 
LEAN does not support this, so we have this check:
https://github.com/QuantConnect/Lean/blob/ae927677f332502c96730a48c58cde0e6688508c/Brokerages/Fxcm/FxcmBrokerage.Messaging.cs#L98-L104
Perhaps the text message can be changed for the contact info, but the hedging flag check should be kept as-is.

- If a live account does not have API access, it should get this error message:
https://github.com/QuantConnect/Lean/blob/ae927677f332502c96730a48c58cde0e6688508c/Brokerages/Fxcm/FxcmBrokerage.cs#L194
The current error message is probably obsolete and can be updated.

**Comment by C-SELLERS** [comment]
@StefanoRaggi Thank you!! This is exactly what I was looking for. Seeing the two issues addressed as one was confusing in this context. I just wanted to be sure I wasn't replacing the wrong thing. I will ensure both messages are up to date!
