### ISSUE TITLE
Please update Linux documentation

### ISSUE THREAD

**Issue by joeldg** [QuantConnect/Lean#4450]
Linux documentation is out of date.
Please refer to mono installation instead as different distributions require different instructions.

https://www.mono-project.com/download/stable/#download-lin

#### Checklist
- [x ] I have completely filled out this template
- [x ] I have confirmed that this issue exists on the current `master` branch
- [ x] I have confirmed that this is not a duplicate issue by searching [issues]

**Comment by Martin-Molinero** [comment]
Hey! Linux mono install documentation at https://github.com/QuantConnect/Lean#linux-debian-ubuntu matches the current docker foundation version at https://github.com/QuantConnect/Lean/blob/master/DockerfileLeanFoundation#L40. We are using a pinned version of mono to prioritize stability above all.
