### ISSUE TITLE
Saving Keras Model in Object Store

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4461]
#### Expected Behavior
Be able to save and load Keras models.

#### Actual Behavior
The method used in [KerasNeuralNetworkAlgorithm](https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/KerasNeuralNetworkAlgorithm.py#L45:L49) does not get the model weights.

#### Potential Solution
N/A

#### Reproducing the Problem
Run `KerasNeuralNetworkAlgorithm` twice. In the second run, verify that the model weights are not set in the model.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Can't seem to reproduce in the cloud nor locally

**Comment by adamw96** [comment]
The Keras API `serialize_keras_object(#model instance)` only saves the configuration/architecture of the model, not the weights, optimizer states, etc. So when reloading the model, the weights are re-initialized randomly for each layer (or based on whatever function `layer.kernel_initializer` is set to.

Method used in example:
```
model = # Trained model instance

# Sample of weights
[np.mean(w) for w in model.get_weights()][:5]
--
[OUT] [0.00024323749, -0.0003448199, 0.2500111, -4.5052566e-05, 1.3041326e-05]

# Test save/load
from keras.utils import serialize_keras_object, deserialize_keras_object

encoded_json_model = serialize_keras_object(model)
loaded_model = deserialize_keras_object(encoded_json_model)

# New weights
[np.mean(w) for w in test_model.get_weights()][:5]
--
[OUT] [2.8747385e-05, 0.00051491224, 0.25, -6.0398008e-05, 2.7704182e-06]
```

To save the weights, we have to encode the weights as JSON and save that as well:
```
# Saving
import json
from json import JSONEncoder
import numpy as np
class EncodeNumpyArray(JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        return JSONEncoder.default(self, obj)
    
model_params = {'weights':model.get_weights(), } # we can also save optimizer states, hidden states, etc
encoded_json_params = json.dumps(model_params, cls=EncodeNumpyArray)
self.ObjectStore.Save('savedparamspath', encoded_json_params)

# Loading
encoded_json_model = self.ObjectStore.Read('savedmodelpath') 
loaded_model = deserialize_keras_object(encoded_json_model) # Load the model
encoded_json_params = self.ObjectStore.Read('savedparamspath')
weights = np.asarray(encoded_json_params['weights'])
loaded_model.set_weights(weights)

[np.mean(w) for w in loaded_model.get_weights()][:5]
--
[OUT] [0.00024323749, -0.0003448199, 0.2500111, -4.5052566e-05, 1.3041326e-05]
```
For saving/loading the full model (especially when there are custom objects such as custom losses, layers, etc), this requires a bit of book-keeping. Alternatively, there's the `keras.models.save_model` and `keras.models.load_model` functionalities but they save directly to disk in .hdf5 and may not play that well with the ObjectStore.
