### ISSUE TITLE
Library Request: TA

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4468]
#### Expected Behavior
Supports [TA](https://github.com/bukosabino/ta).

#### Actual Behavior
No Support.

#### Potential Solution
Install ta to the foundation:
> pip install ta

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by JustinGuese** [comment]
And apparently someone implemented sth in that direction already?
https://github.com/amittleider/LEAN-Indicators
