### ISSUE TITLE
RAM Usage in Linux

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#447]
RAM usage in windows is very very low; backtesting 400 symbols uses roughly 30MB as it streams off the disk and only holds a small fraction of data in memory. But for some reason linux usage shows much higher usage on the magnitude of the data used. 

Potentially linux file-memory caching is holding the old data files in ram and this is counting against the ram usage of the application? Perhaps there's a better way to measure the RAM usage of the LEAN process which excludes the file caching?

**Comment by jameschch** [comment]
I can't report on backtest performance but I've found memory usage in live mode on Linux is more than I'd expect: a single process can exceed ~256MB which is a bit of a problem on micro instances. I've tried increasing vm.swappiness as the swap file is hardly touched but yet to see a positive outcome.

**Comment by theGOTOguy** [comment]
I believe that the high RAM usage may be a function of files never being closed.  During a long-term backtest spanning 2 years, after about 8 months we had exceptionally high RAM and virtual memory usage.  See the screenshot here:

[High RAM and Virtual Memory Usage in Linux](https://imgur.com/a/n9OQl)

Some back of the envelope math indicates that I have a total of 244GB of memory available to Lean, and that I opened roughly 271GB (uncompressed size) of files before seg faulting.    These two numbers are close enough that I think it's possible that I believe that files may simply never have been closed or garbage collected at all.

I have a stack trace from GDB, though I don't believe it's going to be of much utility.  An out of memory will fail wherever the last of the memory was allocated.

[Stack Trace](https://pastebin.com/duze7f7c)
[stderr](https://pastebin.com/X7Utk4mL)

**Comment by jaredbroad** [comment]
Are you on master Ben? We fixed lots of open files recently

**Comment by theGOTOguy** [comment]
I believe I found the cause of this issue for me.

https://github.com/QuantConnect/Lean/blob/master/Engine/DataFeeds/ZipDataCacheProvider.cs#L248

The cause of the leak is that the stream opened by entry.OpenReader() here needs to be Disposed, and never is.  After I finish testing my solution, I will submit a PR to that effect unless someone beats me to the punch.  

It's surprising to me that this is an issue considering that only one stream opened by entry.OpenReader()  may be open at a time without causing corruption.  I would have expected that the previously-opened one would be closed when the new one is opened.
