### ISSUE TITLE
Process killed by out of memory on Linux

### ISSUE THREAD

**Issue by PaoloOranges** [QuantConnect/Lean#4470]
#### Expected Behavior
Not eat all memory and keep running indefinitely

#### Actual Behavior
After 4 days of running in paper mode on Linux + Mono, Lean process has been killed because it consumed all memory available

#### Reproducing the Problem
Compile Lean in Release. Configure and algorithm running in paper mode. Run it on Linux + Mono, leave it for days.

#### System Information
Raspberry Pi 3B
Linux Raspian Buster  10. Kernel 4.19.97-v7
Mono 6.8.0.123
Lean commit: 61a8ace34cd7809eaa877ab0b7a8bfb68446328e

Linux dmesg:
[Thu May 28 04:49:38 2020] Out of memory: Kill process 3426 (Algorithm Analy) score 793 or sacrifice child
[Thu May 28 04:49:38 2020] Killed process 3426 (Algorithm Analy) total-vm:1026704kB, anon-rss:779868kB, file-rss:0kB, shmem-rss:4kB

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
=D Running on a Raspberry Pi 👍 🥇 

Mono > 5.12 has issues in our experiments, we're yet to discover if its a leak in mono or LEAN. We'll soon be forced to upgrade as Ubuntu 20.04 does not have Mono 5.12 in their package list and we'll get to the bottom of it. 

For now, closing this as Pi is not an officially supported platform. 

Were you running python or C#? I tried getting Pi running with python but couldn't crack it.

**Comment by PaoloOranges** [comment]
Hi Jared. C# it took a while to have something stable, there was a WebSocket exception happening randomly. A change in websocket implementation recently (in Lean) fixed that. 
I will try the same in Ubuntu with the same mono or previous versions and see what happen.

Thanks for the quick answer
