### ISSUE TITLE
History Request For Hour-Resolution Crypto Returning Empty

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4478]
#### Expected Behavior
History request to return data when available.

#### Actual Behavior
1-data-point history request returns an empty data frame.

#### Potential Solution
N/A

#### Reproducing the Problem
```python
class BasicTemplateAlgorithm(QCAlgorithm):
    def Initialize(self):
        self.SetStartDate(2020, 5, 17)
        self.eth = self.AddCrypto("ETHUSD", Resolution.Hour, Market.Bitfinex).Symbol

    def OnData(self, data):
        if self.History(self.eth, 1).empty:
            self.Log(f'{self.Time}')
```
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by AdalyatNazirov** [comment]
This is caused by missing data points problem. Created corresponding [issue](https://www.quantconnect.com/forum/discussion/9130/ethusd-btcusd-hour-the-issue-starts-from-may-18th-2020-and-continues-until-may-23rd-2020/p1)
