### ISSUE TITLE
Feature Request: Include Bid/Ask Sizes in History() for Quote Data

### ISSUE THREAD

**Issue by adamw96** [QuantConnect/Lean#4489]
#### Expected Behavior
For Quote data (i.e. FX), the Pandas DataFrame returned by `.History()` should include the Bid/Ask sizes, similar to `QuoteBar.LastAskPrice`.

#### Actual Behavior
Currently, the columns returned for a second/minute resolution history request are:
```
[askclose, askhigh, asklow, askopen, bidclose, bidhigh, bidlow, bidopen, close, high, low, open]
```
Users can manually request historical tick-level data to reconstruct bid/ask sizes - but may be unnecessarily memory-intensive/computationally expensive if only a lower granularity (i.e. second/minute) of data is desired.

#### Potential Solution
Since Bid/Ask sizes are included in the data, add these columns into `.History()`.

**Comment by AlexCatarino** [comment]
Hi @adamw96 ,
The pandas data frame returned by `History` method excludes columns filled with `null` and/or `zero` values. The Forex data QuantConnect redistributes does not report the `Volume` (thus, it is zero).
