### ISSUE TITLE
Optional Parameter in Indicator Helpers Sets Wrong Values in Python

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4491]
#### Expected Behavior
Indicators created with QCAlgorithm helper methods are perfectly set in Python algorithms.

#### Actual Behavior
If the Resolution is explicitly defined, but the previous optional parameter is not, the Resolution value is used to set the parameter. Pythonnet cannot distinguish the types because Resolution is converted to an integer (a number).

#### Potential Solution
Add new method overloads for these cases without optional methods (see recently added KAMA).

#### Reproducing the Problem
```python
rsi = self.RSI(symbol, 14, Resolution.Daily)
```
rsi moving average will be `MovingAverageType.DoubleExponential` since `Resolution.Daily` is also the 5th member in the Enum.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Don't think this is valid use case doesn't compile in C# either but using named arguments works correctly `rsi = self.RSI(symbol, 14, resolution=Resolution.Daily)` . Same for C# of course `var rsi = RSI("SPY", 14, resolution:Resolution.Daily);`
