### ISSUE TITLE
History Request Discrepency Between Research and Backtesting

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#4493]
#### Expected Behavior
If a history request in research returns a full DataFrame, the same DataFrame should be returned during a backtest.

#### Actual Behavior
When requesting data for DRYS in research, a DataFrame contain 1 year of data is returned. The same request in backtesting returns an empty DataFrame 

#### Potential Solution

Unknown.

#### Reproducing the Problem

Compare the backtest log of [this backtest](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_314ceabf46f0ef955896fac23ca19b3d.html) with the output from its research notebook.

#### System Information

Run in the QC web terminal. Windows 10.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
The logs of the backtesting algorithm show `Data  for symbol DRYS has been limited due to numerical precision issues in the factor file. The starting date has been set to 8/11/2016`, this suggests there ir some discrepancy in the map files used by research vs backtesting

**Comment by jaredbroad** [comment]
>The logs of the backtesting algorithm show Data for symbol DRYS has been limited due to numerical precision issues in the factor file. The starting date has been set to 8/11/2016

We should update this error/log message to suggest using Raw mode data to access a longer historical period.
