### ISSUE TITLE
git development workflow for documentation 

### ISSUE THREAD

**Issue by ChrisFagan** [QuantConnect/Lean#450]
Hi,
Is there a git development workflow for documentation e.g. submitting a “Newbie backtesting-desktop setup”
Regards, chris

**Comment by jaredbroad** [comment]
Hey! We have the contributing guide here:
https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md

On Thu, Jun 30, 2016 at 6:26 AM, ChrisFagan <notifications@github.com>
wrote:

> Hi,
> Is there a git development workflow for documentation e.g. submitting a
> “Newbie backtesting-desktop setup”
> Regards, chris
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/QuantConnect/Lean/issues/450>, or mute the thread
> <https://github.com/notifications/unsubscribe/ACI6mb_qZQRNYYU7PH7caDEj75Ix7qIiks5qQ5m4gaJpZM4JCBB1>
> .
>



-- 
Jared Broad

www.quantconnect.com
Phone-USA: +1 917 327 0556
*Democratizing Finance, Empowering Individuals*
Facebook <http://www.facebook.com/QuantConnect> | Twitter
<https://twitter.com/#!/QuantConnect> | LinkedIn
<http://www.linkedin.com/company/quantconnect> | Skype: jaredbroad

**Comment by ChrisFagan** [comment]
Thx - I read the doc -- its primarily about code submissions. 
Do you want to take "user" documentation submissions through Lean/Document ?
And if so what format makes the "puller's" job easier?
Regards, chris

**Comment by jaredbroad** [comment]
Ah great idea, documentation PR's welcome. For Github its probably best to
submit in md format,

We have "https://lean.quantconnect.com" but the tutorials section is
lacking,

Best,
Jared

On Thu, Jun 30, 2016 at 10:08 PM, ChrisFagan <notifications@github.com>
wrote:

> Thx - I read the doc -- its primarily about code submissions.
> Do you want to take "user" documentation submissions through Lean/Document
> ?
> And if so what format makes the "puller's" job easier?
> Regards, chris
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/QuantConnect/Lean/issues/450#issuecomment-229837058>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACI6mYcXeVGa0Hy8_h_GSoMP7BPWgauoks5qRHaFgaJpZM4JCBB1>
> .
>



-- 
Jared Broad

**Comment by jasonnator** [comment]
Why not go all out and use sandcastle?

**Comment by jaredbroad** [comment]
We chose DocumentX instead by InnovaSys. You can see it here:
https://www.quantconnect.com/lean/docs#topic14.html

We think its better and easier to maintain than SandCastle + is supported.
