### ISSUE TITLE
Library Request: XPlot.Plotly and/or Plotly.NET

### ISSUE THREAD

**Issue by simonsonjack** [QuantConnect/Lean#4501]
Add support for the [XPlot.Plotly](https://www.nuget.org/packages/XPlot.Plotly/) and/or [Plotly,NET](https://plotly.net/) library to enable plotting in C# Jupyter notebooks.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Since XPlot.Plotly requires the XPlot.Plotly.Interactive package to plot in notebooks, which conflicts with our DotNetZip and many of our System.* dependency versions, we were not able to add this library.

We should do some research on alternatives like https://plotly.net/.

**Comment by Martin-Molinero** [comment]
`Plotly.NET` has been added to QC cloud

**Comment by atomic800** [comment]
Hi Martin, is this live in QuantConnect now? Getting compile errors when I try to add the using in a C# Research book.
