### ISSUE TITLE
Adds Ease Of Movement Indicator

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4502]
#### Expected Behavior
Richard Arms' [Ease of Movement](https://www.investopedia.com/terms/e/easeofmovement.asp) indicator is supported.

#### Actual Behavior
Not supported

#### Potential Solution
Implement EOM

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by guitrading** [comment]
I will take this one.

**Comment by guitrading** [comment]
Looks like this has already been implemented. See #4591 @jaredbroad
