### ISSUE TITLE
IDE and docker integration

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#4515]
#### Expected Behavior

- Add support to debug and run QCAlgorithms, developing locally in an IDE (VS Code, pycharm, visual studio, etc) and executing in Leans docker container. Add required documentation, scripts and configuration files for each IDE
#### Actual Behavior

- Currently, we have `run_docker.sh/bat`, which don't allow providing an external algorithm to run `.py/.dll` (nor debugging)
#### Potential Solution

Implement 1 IDE at the time, first running a custom algorithm, second debugging.
#### Reproducing the Problem

N/A
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
@Martin-Molinero mind adding the hint from the google-hangout about the switch statement to select the right IDE when setting up debugging
