### ISSUE TITLE
Previous Quote Bar Close is not equal to Current Quote bar Open when using TickQuoteBarConsolidator

### ISSUE THREAD

**Issue by AnandVishnu** [QuantConnect/Lean#4522]
#### Expected Behavior
For quote bar previous close should equal to current bar open when using TickQuoteBarConsolidator

#### Actual Behavior

TickQuoteBarConsolidator creates a new bar every period. So open will take the first value in the consolidated period

#### Potential Solution

Store the previous tick. when ever a new working bar is created, initialise it with previous tick

        protected override void AggregateBar(ref QuoteBar workingBar, Tick data)
        {
            if (workingBar == null)
            {
                workingBar = new QuoteBar
                {
                    Symbol = data.Symbol,
                    Time = GetRoundedBarTime(data.Time),
                    Bid = null,
                    Ask = null
                };

                // sync last tick  close price with this tick open price
                if (_previousTick != null)
                {
                    workingBar.Update(0, _previousTick.BidPrice, _previousTick.AskPrice, 0, _previousTick.BidSize, _previousTick.AskSize);
                }

                if (Period.HasValue) workingBar.Period = Period.Value;
            }

            // update the bid and ask
            workingBar.Update(0, data.BidPrice, data.AskPrice, 0, data.BidSize, data.AskSize);
            if (!Period.HasValue) workingBar.EndTime = GetRoundedBarTime(data.EndTime);
            _previousTick = (Tick) data.Clone();
        }

#### Reproducing the Problem

Following unit test will fail

        public void LastCloseAndCurrentOpenPriceShouldBeSameConsolidatedOnCount()
        {
            QuoteBar quoteBar = null;
            var creator = new TickQuoteBarConsolidator(1);
            creator.DataConsolidated += (sender, args) =>
            {
                quoteBar = args;
            };

            var reference = DateTime.Today;
            var tick1 = new Tick
            {
                Symbol = Symbols.SPY,
                Time = reference,
                TickType = TickType.Quote,
                AskPrice = 25,
                BidPrice = 24,

            };

            creator.Update(tick1);

            var tick2 = new Tick
            {
                Symbol = Symbols.SPY,
                Time = reference.AddSeconds(1),
                TickType = TickType.Quote,
                AskPrice = 36,
                BidPrice = 35,
            };

            creator.Update(tick2);

            Assert.AreEqual(tick1.AskPrice, quoteBar.Ask.Open, "Ask Open not equal to Previous Close");
            Assert.AreEqual(tick1.BidPrice, quoteBar.Bid.Open, "Bid Open not equal to Previous Close");
            Assert.AreEqual(tick2.AskPrice, quoteBar.Ask.Close, "Ask Close incorrect");
            Assert.AreEqual(tick2.BidPrice, quoteBar.Bid.Close, "Bid Close incorrect");
        }

#### System Information

No specific requirements

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by Jay-Jay-D** [comment]
@AnandVishnu Thank you very much for this making this issue with a test case.

But it is based on a false premise:
> For quote bar previous close should equal to current bar open when using TickQuoteBarConsolidator

The observed behavior is the expected one.

From the `PeriodCountConsolidatorBase.Update` method [xml docs](https://github.com/QuantConnect/Lean/blob/17b03a7d281785dcf4d0460f3333a4eb39c76756/Common/Data/Consolidators/PeriodCountConsolidatorBase.cs#L121):
> Updates this consolidator with the specified data. This method is
responsible for raising the DataConsolidated event
In time span mode, the bar range is closed on the left and open on the right: [T, T+TimeSpan).
For example, if time span is 1 minute, we have [10:00, 10:01): so data at 10:01 is not 
included in the bar starting at 10:00.

In your example, it's implemented with counter but is the  the same concept, once a bar is emitted (in your case after a single tick), it start a brand new bar.

**Comment by byguid** [comment]
@Martin-Molinero could you elaborate on why the opening price _must_ match the previous bar close? Gaps are natural, and opening price should be determined by the first trade of the opening day (first tick of new the period). Am I missing something?

**Comment by Martin-Molinero** [comment]
> 
> 
> @Martin-Molinero could you elaborate on why the opening price _must_ match the previous bar close? Gaps are natural, and opening price should be determined by the first trade of the opening day (first tick of the new period). Am I missing something?

Hey! For _quotes_ (bid/ask prices) this is the expected behavior because they are valid until canceled of next update. Which is different than the behavior around trade information, where we do not apply this logic, see https://github.com/QuantConnect/Lean/blob/master/Common/Data/Consolidators/TradeBarConsolidator.cs#L94

**Comment by byguid** [comment]
Hey @Martin-Molinero! Thanks for clarification! I missed the fact that we might receive only one price (bid or ask) at a time.
