### ISSUE TITLE
Update Accord Library

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#4526]
#### Expected Behavior
 - Update accord optimization library.
 - Update accord math  

#### Reproducing the Problem
 - "using AlgLib" gives an error.
 - the QC Accord.Math.Differentiation.FiniteDifferences Class does not support the Gradient(double []) method, but the Compute method, which is obsolete according to the doc.
 

#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closing since Accord is at it's latest possible version `3.6.0`, note the project is now archived https://github.com/accord-net/framework
