### ISSUE TITLE
Email headers with html? 

### ISSUE THREAD

**Issue by Jakepawl** [QuantConnect/Lean#4544]
Am I able to set email headers? Trying to make an email template through QC that is sent daily as an update. Unless an html header is set, I can't use tables to display data...

```
headers = array('Content-Type: text/html; charset=UTF-8')
algorithm.Notify.Email(email, subject, message)
```

**Comment by Jakepawl** [comment]
Is the only way to achieve my goal is to use the webhook to send data to my website and then use php to send however I want?

**Comment by Jakepawl** [comment]
> <b>LONGS INFO</b>
> <u>Current Longs:</u> ['UNFI', 'TGI', 'RRC', 'SPCE', 'DRNA', 'DRD', 'TNDM', 'AU', 'FLIR', 'PAAS', 'SCWX', 'RGEN', 'GSX', 'RGLD', 'MDB', 'KGC', 'IRWD', 'VLY']
> <u>Flattening Longs:</u> ['AU_01180388334', 'KGC_78083601151', 'GSX_78136670705', 'MDB_24207661826', 'UNFI_22211010626']
> <u>New Longs:</u> []
> <b>SHORTS INFO<b>/
> <u>Current Shorts:</u> ['RJF', 'ALXN', 'MIK', 'PE', 'MMSI', 'REFR', 'MUR', 'FELE', 'AEY', 'BZUN']
> <u>Flattening Shorts:</u> ['REFR_48552800810', 'MMSI_53702678828', 'ALXN_54405584048', 'REFR_48555264868', 'RJF_28367237766']
> <u>New Shorts:</u> []

**Comment by Martin-Molinero** [comment]
Related to https://github.com/QuantConnect/Lean/issues/4270
