### ISSUE TITLE
Support Dynamic RenkoConsolidator

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4555]
#### Expected Behavior
The "brick size" of the `RenkoConsolidator` can be changed after initialization. 

#### Actual Behavior
We cannot change the value of the brick size after initialization.

#### Potential Solution
Adds a constructor overload that accepts a function that updates the value of BarSize.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by itsbalamurali** [comment]
@aarjaneiro seems you've touched this one in code.

**Comment by jaredbroad** [comment]
Closing as not a common in industry and focusing core team on industry standards. Can implement this with a custom indicator on individual projects.
