### ISSUE TITLE
ApiDataProvider Creates File That Does Not Existe

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4556]
#### Expected Behavior
If the file doesn't exist in QuantConnect Data Library, `ApiDataProvider` logs that it doesn't exist and continues.

#### Actual Behavior
`ApiDataProvider.Fetch` creates a file when there is correspondence in QuantConnect Data Library.

#### Reproducing the Problem
Use ApiDataProvider and fetch USDCAD.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by omidkrad** [comment]
Thanks for creating this issue. Wanted to add that this makes the downloader error on "Corrupt zip file" since the file is empty.
