### ISSUE TITLE
Order.Value Property Does Not Take Into Account Currency and Multiplier

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4571]
#### Expected Behavior
`Order.Value` property should reflect the same value of `Order.GetValue` method.

#### Actual Behavior
`Order.Value` property is defined as price times quantity.

#### Potential Solution
Set a `Order.Value` when `Order.GetValue` is called.

#### Reproducing the Problem
Download orders csv from a backtest with options.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Flag `Value` as obsolete, we should use `GetValue(security)` instead on the order or even better `security.Holdings.HoldingsValue`
