### ISSUE TITLE
Ability to load .cs file

### ISSUE THREAD

**Issue by ttodua** [QuantConnect/Lean#4572]
I see that the launcher loads only .dll and .py files. 
in config we see:

  //Physical DLL location
  //"algorithm-location": "QuantConnect.Algorithm.CSharp.dll",
  "algorithm-location": "../../../Algorithm.Python/BasicTemplateAlgorithm.py",
  ...

Compiling each algorithm into .dll and running that consumes much time when we are in the middle of the strategy development.
can you please make an ability to load directly ".cs" file, like it's possible to load .py?

**Comment by ttodua** [comment]
moreover, there should be an ability to directly drag .cs file onto load and it made it's job.

**Comment by jaredbroad** [comment]
Thank you for the suggestion @ttodua for now we don't have the bandwidth to execute this idea.
