### ISSUE TITLE
Can't See Multiple Charts With Name "Chart_X"

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#4574]
#### Expected Behavior

We can name custom backtest charts "Chart_1" and "Chart_2" and view both charts at the same time on the backtest view page.

#### Actual Behavior

After naming the charts "Chart_1" and "Chart_2", the backtest view page only allows you to display one chart at a time.

#### Potential Solution

Unknown

#### Reproducing the Problem

Reproducible with [this backtest](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_dcfc4c85e9748bf8fa33c5c887624e5a.html).

#### System Information

Run with the QC web terminal. Windows 10.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @DerekMelchin, closing since this is a bug in the QC front end, unrelated to Lean.
