### ISSUE TITLE
the Test can Run? why i can not test ?

### ISSUE THREAD

**Issue by theone-pang** [QuantConnect/Lean#4578]
#### Checklist

- [ ] I have completely filled out this template
- [ ] I have confirmed that this issue exists on the current `master` branch
- [ ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @theone-pang! yes, the tests can run correctly, we've recently added a readme at https://github.com/QuantConnect/Lean/tree/master/Tests
