### ISSUE TITLE
[Research] QuantBook Retrieves Backtest Results For Analysis

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4580]
#### Expected Behavior
Be able to fetch backtest results in the research environment for further analysis.

#### Actual Behavior
Not supported.

#### Potential Solution
N/A

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by xieliaing** [comment]
any update on this feature request?
