### ISSUE TITLE
run_docker.sh, line 104,  has "$" in wrong place. it's placed before the bracket 

### ISSUE THREAD

**Issue by bootcampshare** [QuantConnect/Lean#4611]
#### Expected Behavior

if [ "{$debugging,,}" == "y" ]; then

#### Actual Behavior

syntax error:
if [ "${debugging,,}" == "y" ]; then

#### Potential Solution

if [ "{$debugging,,}" == "y" ]; then

**Comment by C-SELLERS** [comment]
Syntax is correct for param expansion, this use forces it to lowercase. To address compatibility issues with this method (before bash 4.0) we will change the comparison to use a bash behaviour modifier that will allow no case matching to occur.
