### ISSUE TITLE
StandardDeviationExecutionModel not loading history for CFD and Forex

### ISSUE THREAD

**Issue by ebengtso** [QuantConnect/Lean#4615]
#### Expected Behavior

The StandardDeviationExecutionModel should be warmed up with history data for CFD and Forex

#### Actual Behavior

The History is not loaded
"Calling this method on a Forex or CFD security will return an empty result. Please use the generic version with QuoteBar type parameter."

#### Potential Solution

Solution is simple and will be compatible with all security types

1) In the constructor SymbolData remove the code to load the history
2) In the method OnSecuritiesChanged add the below code. 
`
           // warmup our indicators by pushing history through the consolidators
            algorithm.History(changes.AddedSecurities.Select(security => security.Symbol), _period, _resolution)
                .PushThrough(bar =>
                {
                    SymbolData symbolData;
                    if (_symbolData.TryGetValue(bar.Symbol, out symbolData))
                    {
                        symbolData.SMA.Update(bar.EndTime, bar.Value);
                    	symbolData.STD.Update(bar.EndTime, bar.Value);
                    }
                });
`

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @ebengtso! Don't think this is a Lean issue since it's expected behavior, Forex and CFD do not have TradeBars as shown in the warning message when calling the history overload returning TradeBars. Although the suggested solution might help other users that got the same message, thanks 👍
