### ISSUE TITLE
Daily Data in BacktestResultPacket for Series "Equity" has 2 identical data points for each day

### ISSUE THREAD

**Issue by MoreDough** [QuantConnect/Lean#462]
To replicate this error: run local backtest with BasicTemplateAlgorithm and daily data for SPY and in method LeanWinForms.MessagingOnBacktestResultEvent() create a data dump after 
first line "if (packet.Progress != 1) return;"

The data dump can use the following code to adjust from UTC to America/New_York:
var tz = DateTimeZoneProviders.Tzdb["America/New_York"];
var localTimeKeeper = new LocalTimeKeeper(DateTime.UtcNow, tz);
var timestampAsDt = Time.UnixTimeStampToDateTime(timestamp);
localTimeKeeper.UpdateTime(timestampAsDt);
var timestampAdjustedToNewYorkTime = localTimeKeeper.LocalTime;

(Let me know if you need the dump code)

**Comment by jaredbroad** [comment]
Sampling is at the open and close of a day; in FX this is at the same time (as FX is 24hrs), and with daily data as there is only one point per day so the sample appears twice. 

For the other resolutions this isn't an issue. Is there a compelling reason its an issue for your case?

We could check the resolution of all the securities/feeds on each loop and selectively sample if they're all daily data (computationally expensive for an edge case), or strip out the duplicated data points from the final results.

**Comment by MoreDough** [comment]
No, not an issue now that I have an explanation of the data. Documentation is completely missing on this and trying to figure out exactly how it works and why it is done in a particular way by studying complex code is not easy for us users out here. So, more and better documentation, Jared!
