### ISSUE TITLE
skylight is synchronizing the obj folder, but should not

### ISSUE THREAD

**Issue by ebengtso** [QuantConnect/Lean#4625]
#### Expected Behavior

.Net Project c# generates an "obj" folder. Skylight is copying this folder to QuantConnect, but instead should ignore it

#### Actual Behavior

obj folder is getting copied

#### Potential Solution

Ignore the folder obj

#### Reproducing the Problem

Create a .net project under the skylight folder. the obj folder is synchronized to QC

#### System Information

MacOS. Visual Studio 

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Thanks for the report, this issue has now been fixed in version 0.1.11.
