### ISSUE TITLE
Daily chart data in BacktestResultPacket for series "Equity" has only 1 data value

### ISSUE THREAD

**Issue by MoreDough** [QuantConnect/Lean#463]
Daily chart data in BacktestResultPacket for series "Equity" is SeriesType.Candle, but has only one data value. To draw proper candles you need 4 values.

How LeanWinForm can generate candles (actually bars) is hidden in the browser script downloaded from QC. My guess is that "fake" bars with only High-Low are generated using data from "Daily Performance" in combination with the single data value from "Equity". 

Please give us proper OHLC data for candle series.

**Comment by jaredbroad** [comment]
You can think of the equity chart as a line if its easier which happens to be drawn as a candle (for aesthetics) when you have multiple days of data. At a minimum it samples at the start and end of a day.

Shorter timeframes sample more often to generate full candles but that isn't feasible with longer timeframes as it would generate far more points and crash the charting / browsers as I mentioned in Issue #466.
