### ISSUE TITLE
Add IQFeed support for Docker + documentation

### ISSUE THREAD

**Issue by mathpaquette** [QuantConnect/Lean#4631]
#### Checklist

- [ ] I have completely filled out this template
- [ ] I have confirmed that this issue exists on the current `master` branch
- [ ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/4632
