### ISSUE TITLE
Variable Index Dynamic Average (VIDYA) Indicator

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4633]
#### Expected Behavior
Support Variable Index Dynamic Average (VIDYA) indicator

#### Actual Behavior
Not supported

#### Potential Solution
Implements VIDYA ([formula](http://www.fxcorporate.com/help/MS/NOTFIFO/i_Vidya.html))

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by LouisSzeto** [comment]
[spy_vidya.csv](https://github.com/QuantConnect/Lean/files/13114763/spy_vidya.csv)
columns: "SPY close" "VIDYA"

script:
```
import talib

qb = QuantBook()

spy = qb.AddEquity("SPY", Resolution.Daily).Symbol

history = qb.History([spy, qqq], datetime(1998, 1, 1), datetime(2023, 2, 23))

close = history.loc[spy].close

# Source: https://www.technicalindicators.net/indicators-technical-analysis/145-vidya-variable-index-dynamic-average
std9 = close.rolling(9).std()
std30 = close.rolling(30).std()
alpha = (0.2 * std9 / std30).dropna()
vidya = close.loc[alpha.index]
for i in range(1, vidya.shape[0]):
    vidya[i] = alpha[i] * close[i] + (1 - alpha[i]) * vidya[i-1]
vidya = vidya.to_frame()
vidya["SPY close"] = close
vidya = vidya.iloc[:, [1, 0]].dropna()
vidya.to_csv("spy_vidya.csv", header=False)
```
