### ISSUE TITLE
Property to get timestamps correctly adjusted to local exchange time

### ISSUE THREAD

**Issue by MoreDough** [QuantConnect/Lean#464]
There should be a property in the chart data in BacktestResultPacket that can be used to get timestamps correctly adjusted to local exchange time where the symbol is traded.

**Comment by jaredbroad** [comment]
This is tricky as LEAN is multi-timezone so there isn't a single timezone for equity/daily performance. Each stock plot is saved in UTC but the asset itself does have a timezone which could be saved. This information is in the market-hours-database though - can you provide a solid use case where this would need to be duplicated?

**Comment by MoreDough** [comment]
A Chart has a collection of Series. Every Series contains data for one symbol that is traded on one exchange which has one fixed timezone. Why not create a method Series.UnixTimestampToExchangeTime(long timestamp) that returns a DateTime and uses timezone info stored in series to convert timestamp to the local timezone for the particular exchange? This would make it MUCH easier for anyone wanting to use charting data in  BacktestResultPacket.Results.Charts. 

I need this because I am working on my own charting solution for Lean using a charting library I have and need to convert the unix timestamps that are x-values for chart data into exchange time in order for the charts to be meaningful.

Storage required for this in Series is minimal and the method should not be difficult to write.

**Comment by jaredbroad** [comment]
> very Series contains data for one symbol that is traded on one exchange which has one fixed timezone. 
I don't believe this is the case; all charts other than stock plots are in their own timezones. 

In general we try to keep everything in the "models"/data layer in UTC; the conversion to local timezones for display is handled on the "views" layer of the application.
