### ISSUE TITLE
TD Ameritrade support

### ISSUE THREAD

**Issue by mLewisLogic** [QuantConnect/Lean#4647]
TD Ameritrade's current API is quite solid.
REST: https://developer.tdameritrade.com/apis
streaming (including L2): https://developer.tdameritrade.com/content/streaming-data

The reason for "why" another brokerage is that I've found that TDA provides the best order execution (for sitting limit orders) of any of the $0 commission brokerages. I prototyped strategies by hand on a few brokerages before coding and found that TDA would happily execute orders that would sit unfilled all day on Alpaca. Not much surprise though since Alpaca runs through Wolverine, but TDA runs straight to Citadel. This means that strategies that could work on TDA are no-gos on Alpaca.

The only other $0 brokerage that offers comparable execution is Schwab, but they don't provide easy API access.

**Comment by shahrokhf** [comment]
I thought this API is not supported anymore. My old program that wrote two years ago is not working anymore. Would somebody comment please.  Thanks

**Comment by mLewisLogic** [comment]
Works very well.

Numerous Python wrappers in active development:
* https://github.com/areed1192/td-ameritrade-python-api
* https://github.com/alexgolec/tda-api
* https://github.com/timkpaine/tdameritrade

I've used the first 2 for communicating in production (within the past month). Streaming and REST are both working great. Occasional connections drops on streaming, but nothing a client can't recover from.

**Comment by kjanoudi** [comment]
Is there a guide on implementing another brokerage for use with Lean? I'd like to help implement the TDA API, if anyone else is working on it as well.

**Comment by cmoski** [comment]
There is a great C++ API that can be used for reference here:

https://github.com/jeog/TDAmeritradeAPI

I did this a few years ago with LEAN, but it no longer functions with the new code base. I'd be happy to help contribute to an effort to get the brokerage officially supported. (The most annoying part of the impl has to be the brokerage refresh tokens)

**Comment by csdelan** [comment]
I would also be willing to help chip into a TDA brokerage implementation, I'd really like to see this happen.  Though I'm a little newer to the Lean framework (but C# is my specialty), so I'm still in learning curve mode and would be better as a helper rather than a leader.

**Comment by Martin-Molinero** [comment]
This is already available, see https://github.com/QuantConnect/Lean.Brokerages.TDAmeritrade

**Comment by hchaudhary1** [comment]
Will cloud support this?
Or private LEAN only?

**Comment by Martin-Molinero** [comment]
> Will cloud support this? Or private LEAN only?

Hey! Yes both cloud and local support is available already.
