### ISSUE TITLE
MarketOnClose and MarketOnOpen doesn't work using AlpacaBrokerageModel

### ISSUE THREAD

**Issue by oldrichsmejkal** [QuantConnect/Lean#4648]
#### Expected Behavior
MarketOnClose and MarketOnOpen shoud be supported for AlpacaBrokerageModel, because they are supported by alpaca (it's in their api documentation.

#### Actual Behavior
There is error when trying to submit MarketOnClose order:
"The AlpacaBrokerageModel does not support MarketOnClose order type."

**Comment by Martin-Molinero** [comment]
Closing since alpaca has been removed https://github.com/QuantConnect/Lean/pull/5249
