### ISSUE TITLE
Local Charting "Vector smash protection is enabled"

### ISSUE THREAD

**Issue by MoreDough** [QuantConnect/Lean#465]
There seems to be a race condition between the backtest and the charting implementation in LeanWinForm.

When the problem occurs, "Vector smash protection is enabled" is shown at the bottom of console output window.

If you put Thread.Sleep(15) in the OnData(Slice data) method in the algo, the backtest is slowed down and charting works.

**Comment by jaredbroad** [comment]
It is a protection mechanism of Internet Explorer. Ideally we can use another cross platform web browser plugin but I haven't found one yet that works well. 

Maybe just the first few browser injections can be slowed down? The result handler only does it every second so its probably just the initial injections.

**Comment by MoreDough** [comment]
I don't know what the problem is and will not look at this any more.

**Comment by jameschch** [comment]
There is a slow answer and a quick answer to this. The quick answer is that the code attempts to use the most recent IE that's installed and I suspect the issue only occurs on older versions (I can't recreate on IE11).  It may be worth establishing the browser version(s) experiencing the problem, and displaying a warning that the user should upgrade, I'm not inclined to create a compatibility fix for old versions of IE.

The slow answer is that the IE WebBrowser control has always been and is still notoriously problematic and we are better off without it. I'm looking into alternatives.

**Comment by jaredbroad** [comment]
Agree completely. It was the only thing I could get to compile/work on windows and linux (in mono the WebBrowser control gets converted to MonoBrowser under the hood). Open to alternatives though!

**Comment by MoreDough** [comment]
Just tested again with no slowdown sleep in algo. Chart window is shown but contains no chart data, only the static stuff like scroller, 2 tabs and such.

From console window:
20160713 22:27:34 Trace:: Engine.Run(): Disconnecting from brokerage...
20160713 22:27:34 Trace:: Engine.Run(): Disposing of setup handler...
20160713 22:27:34 Trace:: Engine.Main(): Analysis Completed and Results Posted
20160713 22:27:34 Trace:: BacktestingResultHandler.ProcessLogMessages(): Ready
20160713 22:27:34 Trace:: FileSystemDataFeed.Exit(): Exit triggered.
Engine.Main(): Analysis Complete. Press any key to continue.
Vector smash protection is enabled.

My IE is ver 11, about box says:
Version: 11.0.9600.18349
Update versions: 11.0.32 (KB3160005)

I have Win 7 prof. (don't know if this could make a difference)

Well, it shouldn't be to easy guys. Wouldn't be any sport then, would it?

**Comment by jaredbroad** [comment]
Fixed by  commit 583baa7
