### ISSUE TITLE
Indicator Request: Heikin Ashi

### ISSUE THREAD

**Issue by shilewenuw** [QuantConnect/Lean#4652]
#### Expected Behavior

Heikin Ashi and Supertrend indicators request. [Thread](https://www.quantconnect.com/forum/discussion/9072/hekin-ashi-amp-supertrend-indicator-in-python/p1).
#### Actual Behavior

Indicator not yet supported.
#### Checklist

- [x ] I have completely filled out this template
- [x ] I have confirmed that this issue exists on the current `master` branch
- [ x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by movy** [comment]
Any update on this?

**Comment by ksawada1** [comment]
I would like to work on this.  Could you please explain more about this?

**Comment by AlexCatarino** [comment]
Hi @ksawada1, those indicators have been implemented. We haven't closed this issue...
Closed by https://github.com/QuantConnect/Lean/pull/4844 and https://github.com/QuantConnect/Lean/pull/6013
