### ISSUE TITLE
Add organizations/read API endpoint

### ISSUE THREAD

**Issue by jmerle** [QuantConnect/Lean#4663]
#### Expected Behavior

There is an organizations/read API endpoint which can be used to retrieve display-friendly organization names of the organizations a user is in.

This endpoint can be used in [QuantConnect/quantconnect-cli](https://github.com/QuantConnect/quantconnect-cli) which already has some neat interactive project and backtest selectors, but is lacking a "neat" interactive organization selector because there is no way to get a list of display-friendly names of the organizations a user is in.

With neat interactive project selector I mean this:
![image](https://user-images.githubusercontent.com/14951909/91369041-f078ff80-e80a-11ea-87a4-6a78b4c86dc6.png)

Against this (which is the current "non-neat" organization selector):
![image](https://user-images.githubusercontent.com/14951909/91369163-5bc2d180-e80b-11ea-8552-cfa39ffaef56.png)

#### Actual Behavior

There is no way to map organization ids from the projects/read endpoint to a display-friendly organization name via the REST API.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by C-SELLERS** [comment]
@gaviles 

No endpoints currently support organization names.

Also interesting is there is no way to update preferred organization from lean api, so when I create a project it will just go to my web preferred, I cannot place it in one organization to then have it use a node in that org.
