### ISSUE TITLE
Dividend History Request

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4665]
#### Expected Behavior
Be able to get the historical dividend data similar to price data.

#### Actual Behavior
Not possible.
```csharp
var dividends = History<Dividend>("SPY", 300, Resolution.Daily);
```
If we need the past dividends of security we need to collect it during runtime which cannot be used in Universe Selection algorithms.

#### Potential Solution
N/A

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
- Refactoring LEAN to have Dividends, Splits, etc as a standard data feed not an auxiliary-data feed.
 - Adjusting data loading in Reader to support reading from the factor CSVs.
 - Access dividends via the normal history system.

**Comment by AlexCatarino** [comment]
- Include Margin Interest Rate.
