### ISSUE TITLE
AddReference cannot be imported despite pythonnet having been installed

### ISSUE THREAD

**Issue by aarjaneiro** [QuantConnect/Lean#4674]
#### Expected Behavior

pythonnet installation allows one to import clr
#### Actual Behavior

Can at times not occur (https://www.quantconnect.com/forum/discussion/9054/lean-vagrant-box/p1)
#### Potential Solution

Add test to see if pythonnet must be reinstalled/different source required for installation
#### Reproducing the Problem

As per https://stackoverflow.com/questions/56957512/pythonnet-missing-addreference-method, one method would be to make a clr.py file in site-packages. Otherwise, delete site_builder.py from site-packages\clr\,
#### Checklist

- [ x] I have completely filled out this template
- [ x] I have confirmed that this issue exists on the current `master` branch
- [ x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x ] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @aarjaneiro!
QC has its own fork of pythonNet https://github.com/QuantConnect/pythonnet with some changes to better support our use case. Installing `pythonnet/pythonnet` will probably cause compatibility issues. We are currently not installing pythonNet in our docker images but rely on the NuGet package pulled by Lean on build, is this not working for you?

**Comment by aarjaneiro** [comment]
@Martin-Molinero 
Unfortunately not as per https://www.quantconnect.com/forum/discussion/9054/lean-vagrant-box/p1/comment-25262. In my case,  removing my local ~/anaconda3/lib/python3.7/site-packages/clr/ folder and then reinstalling worked despite having originally installed the Lean version. Via docker, however, I've gotten it working.

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/4673
