### ISSUE TITLE
Feature Request: Smart Sharpe Ratio Backtest Statistic

### ISSUE THREAD

**Issue by shilewenuw** [QuantConnect/Lean#4682]
#### Expected Behavior
Include Smart Sharpe Ratio in backtest statistics. Relevant [thread](https://www.quantconnect.com/forum/discussion/6483/probabilistic-sharpe-ratio/p2/comment-25356).

#### Actual Behavior
Not yet included.

#### Checklist

- [x ] I have completely filled out this template
- [x ] I have confirmed that this issue exists on the current `master` branch
- [x ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x ] I have provided detailed steps to reproduce the issue

**Comment by haxdds** [comment]
[Relevant Paper](https://www.keyquant.com/Download/GetFile?Filename=%5CPublications%5CKeyQuant_WhitePaper_APT_Part2.pdf)

**Comment by jaredbroad** [comment]
With limited bandwidth focusing on industry standards for now.
