### ISSUE TITLE
NetStandard/NeCore compatibility

### ISSUE THREAD

**Issue by eramosr16** [QuantConnect/Lean#4687]
#### Expected Behavior
Packages be compatible with the NetStandard/NetCore versions

#### Actual Behavior
Nuget packages aren't compatible with NetStandard/NetCore

#### Potential Solution
Migrate packages to NetStandard v2.1

#### Checklist

- [x ] I have completely filled out this template
- [x ] I have confirmed that this issue exists on the current `master` branch
- [x ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Hey @eramosr16,
I'm closing this issue since we already have an older issue about .Net core support https://github.com/QuantConnect/Lean/issues/452, Nuget packages will migrate alongside with Lean itself.
