### ISSUE TITLE
OnMessage, Subscribe usage & implementation (BaseWebsocketsBrokerage base class) 

### ISSUE THREAD

**Issue by BadgerTheAdger** [QuantConnect/Lean#4697]
### How do Subscribe / On... events relate and what is the usage of On... events and of Subscribe method?

So we have OnOrderEvent OnAccountChanged OnOptionPositionAssigned OnError OnMessage WebSocket callbacks.

The first 4 make a lot of sense but the 5th one is not obvious - seems like it's supposed to be generic i.e the one I can use if there's an event that is not supported in QuantConnect (for instance, new ticker arrived). 

But I can only find usages with BrokerageMessageType.Warning or Error, I couldn't find any with Information (a new ticker/candle arriving is not an error or warning). That confuses me.

If an exchange supports getting tickers / candles / etc updates via websocket I usually callback it as follows: `OnMessage(new BrokerageMessageEvent(BrokerageMessageType.Information, "Ticker", jsonData));`. 

Is my usage of it correct? Please assist with what these are supposed to do and if I have tickers or candles I can't see an event handling them.

**Comment by Martin-Molinero** [comment]
Hey @BadgerTheAdger!
> Is my usage of it correct?

I believe so, there are 2 implementations of the `BaseWebsocketsBrokerage` already available GDAX (at https://github.com/QuantConnect/Lean/tree/master/Brokerages/GDAX) & Bitfinex (at https://github.com/QuantConnect/Lean/tree/master/Brokerages/Bitfinex). Basically, when you get data your supposed to create a Trade or a Quote tick and pump it into the aggregator manager, all `IDataQueueHandler` implementations do so, there are plenty of examples of this. Hope I helped, I'll close this issue for now.
