### ISSUE TITLE
QuantConnect.Orders.Order.OrderId is not generic (limited to int only)

### ISSUE THREAD

**Issue by BadgerTheAdger** [QuantConnect/Lean#4698]
#### Expected Behavior
OrderId is of type string so that it can be guid / other type of id, not just int

#### Actual Behavior
OrderId is limited to int. I'm adding a brokerage which retrieves ID as guid after placing order.

#### Potential Solution
Change type to string or maybe make the type generic but changing it to string is probably better

#### Checklist

- [x ] I have completely filled out this template
- [ x] I have confirmed that this issue exists on the current `master` branch
- [x ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ x] I have provided detailed steps to reproduce the issue

**Comment by BadgerTheAdger** [comment]
Any idea on a proper way to fix ? Is it an issue at all? Because maybe you there is some specific reason to why it's int not string...

**Comment by BadgerTheAdger** [comment]
Is it client side ID? i.e our interal ID not the brokerage's order id

**Comment by Martin-Molinero** [comment]
Hey @BadgerTheAdger!
`Order.Id` is internal to lean, believe you should be using `List<string> BrokerId`. At `/Brokerages` you can see examples of differente brokerages implementation which use this broker id. Closing this issue for now, let us know if it doesn't solve it
