### ISSUE TITLE
What are FactorFile and MapFile ?

### ISSUE THREAD

**Issue by BadgerTheAdger** [QuantConnect/Lean#4707]
Hi guys, I'm implementing my own layer to read data not from file but from a database, could you please help me understand what FactorFile and MapFile are about? I see they're used everywhere in SubscriptionDataReader regardless of data source / data type i.e even if it's crypto exchange these are used. Tho they're stored in equity folder. So I struggle to understand will these values be even used if I use crypto type of data?

**Comment by BadgerTheAdger** [comment]
Right now I have FactorFileRow implemented as a candle for binance API ... I'm not sure if that's correct... Could you please just explain what this model is about?

**Comment by BadgerTheAdger** [comment]
I also struggle to understand MapFiles.. What is permtick? What are these mapped symbols about?

**Comment by BadgerTheAdger** [comment]
Right now I have MapFiles implemented as market symbols (e.g BTCUSDT, ETH_BTC etc) and the current date

**Comment by jaredbroad** [comment]
Hey there, great to see you digging into LEAN! Please post user-group style questions to the LEAN forum on QuantConnect
https://www.quantconnect.com/forum/discussions/1/lean
