### ISSUE TITLE
Lean Symbol conversion issue

### ISSUE THREAD

**Issue by BadgerTheAdger** [QuantConnect/Lean#4715]
Hello,

I struggle understanding how to convert Lean Symbol into a symbol in format (BASE-QUOTE). I saw some implementations of ISymbolMapper. The naive approach would be to match BASE and then simply construct  the symbol with the new format. However, I don't understand what the format of Lean Symbol is. For instance, for BTC-USDT lean symbol is BTCUST which is not the same as BTCUSDT and this part is very confusing. Probably there are other pairs like that too.

Do you guys know where I can read what the format of Lean Symbol is for instance some ISO stuff etc? And any suggestions? Because what I saw in various brokerage implementations is that they simply have a list of known / unknown symbols and all bitfinex binance gdax etc brokerages they assume that their symbol is the same as the lean's symbol. They dont parse base and quote from that.

So could you let me know if there's a mechanism to split lean symbol into base quote?
Also, I need to know what the format of the lean symbols is. For instance, I see BTCUST instead of BTCUSDT for the first time

Thanks,
Mark

**Comment by BadgerTheAdger** [comment]
Binance probably has an error in the "Known symbol strings". Binance looks to be a copy-paste of Bitfinex. See Bitfinex has BTCUST pair. Lean has it. Lean doesn't have BTCUSDT pair AFAIU. But Binance simply maps its BTCUSDT to BTCUSDT. Not to BTCUST.

**Comment by BadgerTheAdger** [comment]
I'm talking about QuantConnect.Brokerages.Binance.BinanceSymbolMapper.KnownSymbolStrings

**Comment by BadgerTheAdger** [comment]
Ah looks like UST is the only currency exceptional to Bitfinex

**Comment by Martin-Molinero** [comment]
Hey Mark!
We've recently refactored these crypto symbol mappers to be `symbol-properties-database.csv` driven see https://github.com/QuantConnect/Lean/pull/4888, we also added a new column for the exchange ticker, I hope it's clearer now. CLosing this issue, let us know otherwise
