### ISSUE TITLE
Python Documentation

### ISSUE THREAD

**Issue by aarjaneiro** [QuantConnect/Lean#4721]
#### Expected Behavior

Python documentation in the style of https://www.quantconnect.com/lean/docs.
#### Actual Behavior

Documentation only exists for general usage (https://www.quantconnect.com/docs/home/home) as opposed to outlining individual module elements/classes and their members like in the C# documentation.
#### Potential Solution

With Lean/Algorithm.Python/stubs/QuantConnect now added, docstrings already used there can be used as a starting point for Sphinx styled documentation (of course, "styled" given that the stubs are not the source - nonetheless, having a searchable documentation for the module element names and their docstrings would help). Should your namespace work properly (e.g., with no import errors due to a non-sane pythonnet install), following https://matplotlib.org/sampledoc/ should quickly produce a sample.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment]
@aarjaneiro, QuantConnect has a repo for [Documentation](https://github.com/QuantConnect/Documentation) (and, by the way, [Tutorials](https://github.com/QuantConnect/Tutorials)). Please contact [support ](support@quantconnect.com) or [QuantConnect at Slack](https://www.quantconnect.com/slack) before openning issues in this repo if you are not sure it belongs here.

That said, we have been working on new documentation: https://github.com/QuantConnect/Documentation/pull/335.
