### ISSUE TITLE
Prevent Repetitive Factor File Warning

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4722]
#### Expected Behavior
The following message is only logged once per security:
> "Data for symbol DRYS has been limited due to numerical precision issues in the factor file. The starting date has been set to 8/11/2016."

#### Actual Behavior
The message above is logged multiple times.

#### Potential Solution
Use the pattern that is in place for map files.
Maybe we should also improve the message, since "The starting date has been set to 31/12/2050." troubles users. :-D

#### Reproducing the Problem
Any universe selection model that selected DRYS for example.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by mchandschuh** [comment]
Regarding the 2050 message:
> "The starting date has been set to 31/12/2050."

This implies we won't be processing any data for the security at all, correct? Presumably this would be due to all entries in the factor file being INF. Do you know of any such cases? What would a better error message be?
