### ISSUE TITLE
SetWarmup to Fetch history from disk in live mode

### ISSUE THREAD

**Issue by captholley** [QuantConnect/Lean#4729]
#### Expected Behavior

SetWarmup() request at initialization performs an API call while in live mode to the exchange being used at that time. The exchange I am using does not have enough historical data for the security I am trading and I would like to use data from files stored on disk the same way I would during backtest mode. I believe this may also speed up the warmup period as the data will be quicker to access and won't run into rate limiting issues.
#### Actual Behavior

SetWarmup() in live mode makes continuous API calls to retrieve history
#### Potential Solution

Allow the use of disk data, automatically switching to api if data is not available

#### Checklist

- [x ] I have completely filled out this template
- [x ] I have confirmed that this issue exists on the current `master` branch
- [x ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Hey @captholley!
Interesting use case, currently Lean only allows specifying a single history provider. A workaround for your use case is having a custom history provider wrapping both providers you want to use, a file-based one, and the brokerage one and switching on each acordengly.
