### ISSUE TITLE
Add Regression Channel as an Indicator

### ISSUE THREAD

**Issue by abhishekc05** [QuantConnect/Lean#474]
Is it possible to include linear regression channels as a built in Indicator ?

**Comment by jameschch** [comment]
I've considered putting together linear regression channels as I believe it's just offset periods of the existing LSMA indicator. Was there a reference implementation you have in mind?

**Comment by abhishekc05** [comment]
Hi,

Thanks for that. The regression channel needs just a few extra outputs
other than the last predicted value. I was using the following crude
version - am not really confident of being able to add an indicator
properly to the Engine as am relatively new to C#.

The input is the period.

The important outputs are: slope, standard deviation of errors and last
predicted value. The bands can be calculated using the current price and
standard deviation of errors or can be part of the output (in which case
the number of standard deviations to use would also be an input); slope is
useful to identify the trend.


--------------------------------------------------------------
public void AddSample(decimal price)
{
if (_samples<_period)
{
_slope = 1m;
_upBand = price;
_lowBand =price;
_isReady = false;
_samples++;
_yBuffer.Add((double)price);
_xBuffer.Add(_samples);
return;
}
else
{
_slopeCoefficients = Fit.Polynomial(_xBuffer.ToArray(),
_yBuffer.ToArray());
_isReady =  true;
double[] _errors = new double[_xBuffer.Count()];
            double[] _modelledValues = new double[_yBuffer.Count()];
            for (int _curCount = 0;_curCount<_xBuffer.Count();_curCount++)
        {
              //_modelledValues[_curCount] =
Evaluate.Polynomial(_xBuffer[_curCount], _slopeCoefficients);
             _modelledValues [_curCount] = _slopeCoefficients[0] +
_slopeCoefficients[1]*_xBuffer[_curCount];
             _errors[_curCount] = _modelledValues[_curCount] -
_yBuffer[_curCount];
                }

            _oneStdDev =
(decimal)ArrayStatistics.PopulationStandardDeviation(_errors);
 //Standard
Devation of errors  - Population uses N
            _lastPredictedValue = (decimal)(_slopeCoefficients[0] +
_slopeCoefficients[1]*_xBuffer.Last());        //Getting the last
calculated value
            _slope = (decimal)_slopeCoefficients[1];
            _upBand = _lastPredictedValue + _oneStdDev*(decimal)_deviation;
            _lowBand = _lastPredictedValue - _oneStdDev*(decimal)_deviation;

            _yBuffer.Add((double)price); //Preparing for next band value
            _yBuffer.RemoveAt(0);
            }
}
--------------------------------------------------------------

You could also change this easily into a polynomial regression using the
Fit.Polynomial(x,y, power) where the output would have multiple
coefficients instead of one slope and inputs would also have power- but for
now, it would be great if we could have the linear regression channel!

Thanks a lot,
Abhishek

**Comment by jaredbroad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Regression Channel Indicator](https://trello.com/c/QW9GcuX0/985-regression-channel-indicator)
