### ISSUE TITLE
Library Request: Rpy2

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4746]
#### Expected Behavior
Support [Rpy2](https://pypi.org/project/rpy2/)
Adds R library exuber. 

#### Actual Behavior
Does not support [Rpy2](https://pypi.org/project/rpy2/)

#### Potential Solution
Review and approve [Rpy2](https://pypi.org/project/rpy2/)
```python
from rpy2.robjects.packages import importr

exuber = importr('exuber')

# params
x = np.random.rand(500) # python code, test data
adf_lag = 2
bubble = exuber.radf(x, minw= 50, lag = adf_lag)
``` 
#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by MislavSag** [comment]
Any progress on the reuest?
