### ISSUE TITLE
Setting cash to BASE instead of QUOTE gives an "Insufficient buying power" error

### ISSUE THREAD

**Issue by BadgerTheAdger** [QuantConnect/Lean#4767]
Hello everyone,

I got this simple strategy working with USDT currency set as cash (see the SetCash("USDT")) - it is generating me ~26k trades. But when I change it from USDT to BTC everywhere (in the SetCash, in the ` var usdTotal = Portfolio.CashBook["USDT"].Amount;`, in the config - I changed default currency) as I want the base currency to be the cash, it will start complaining in the console saying:

> 20200927 11:28:11.924 ERROR:: Order Error: id: 23510, Insufficient buying power to complete order (Value:0,559519), Reason: Your portfolio holds 0 BTC, 0 BTC of which are reserved for open orders, but your Buy order is for 0.559519 USDT. Your order requires a total value of 5263.15463983 BTC, but only a total value of 0 BTC is available.

And this is true for every single order.
So I get 0 trades at the end 

Do you have an idea of how to make it work with base currency set as cash?

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using QuantConnect.Data;
using QuantConnect.Brokerages;
using QuantConnect.Indicators;
using QuantConnect.Orders;
using QuantConnect.Interfaces;
using Remotion.Linq.Parsing.Structure.IntermediateModel;

namespace QuantConnect.Algorithm.CSharp
{
    /// <summary>
    /// The demonstration algorithm shows some of the most common order methods when working with Crypto assets.
    /// </summary>
    /// <meta name="tag" content="using data" />
    /// <meta name="tag" content="using quantconnect" />
    /// <meta name="tag" content="trading and orders" />
    public class BasicTemplateCryptoAlgorithmBinanceQuickSMA : QCAlgorithm, IRegressionAlgorithmDefinition
    {
        private SimpleMovingAverage _fast;
        private SimpleMovingAverage _slow;
        private DateTime _previous;
        private readonly string _symbol = "BTCUSDT";

        /// <summary>
        /// Initialise the data and resolution required, as well as the cash and start-end dates for your algorithm. All algorithms mUSDT initialized.
        /// </summary>
        public override void Initialize()
        {
            SetStartDate(2020, 02, 01);  //Set Start Date
            SetEndDate(2020, 06, 01);    //Set End Date

            TraceDuration();    // Trace the duration to validate against the requested data

            // Set Strategy Cash (USDT)
            SetCash("USDT", 10000);

            SetBrokerageModel(BrokerageName.Binance, AccountType.Cash);

            // You can uncomment the following line when live trading with GDAX,
            // to ensure limit orders will only be posted to the order book and never executed as a taker (incurring fees).
            // Please note this statement has no effect in backtesting or paper trading.
            // DefaultOrderProperties = new GDAXOrderProperties { PostOnly = true };

            // Find more symbols here: http://quantconnect.com/data
            AddCrypto(_symbol);

            // create two moving averages
            _fast = SMA(_symbol, 30, Resolution.Daily);
            _slow = SMA(_symbol, 60, Resolution.Daily);
        }

        /// <summary>
        /// OnData event is the primary entry point for your algorithm. Each new data point will be pumped in here.
        /// </summary>
        /// <param name="data">Slice object keyed by symbol containing the stock data</param>
        public override void OnData(Slice data)
        {
            // only once per day
            if (_previous.Date == Time.Date)
                return;

            Log("_fast.IsReady:" + _fast.IsReady);
            Log("_slow.IsReady:" + _slow.IsReady);

            if (!(_fast.IsReady && _slow.IsReady))
                return;

            var holding = Portfolio[_symbol];

            // If the fast is over the slow sma and we don't have any holdings let's go long
            if (holding.Quantity == 0 == _fast.Current > _slow.Current)
            {
                // Submit a buy limit order for BTC at 5% below the current price
                var usdTotal = Portfolio.CashBook["USDT"].Amount;
                var limitPrice = Math.Round(Securities[_symbol].Price * 0.95m, 2);

                // use only half of our total USD
                var quantity = usdTotal * 0.5m / limitPrice;

                Buy(_symbol, quantity);

                // LimitOrder(_symbol, quantity, limitPrice);
            }
            else if (holding.Quantity > 0 && _slow.Current < _fast.Current)
            {
                Sell(_symbol, holding.Quantity);
            }
        }

        public override void OnOrderEvent(OrderEvent orderEvent)
        {
            Debug(Time + " " + orderEvent);
        }

        public override void OnEndOfAlgorithm()
        {
            Log($"{Time} - TotalPortfolioValue: {Portfolio.TotalPortfolioValue}");
            Log($"{Time} - CashBook: {Portfolio.CashBook}");
        }

        /// <summary>
        /// This is used by the regression test system to indicate if the open source Lean repository has the required data to run this algorithm.
        /// </summary>
        public bool CanRunLocally { get; } = true;

        /// <summary>
        /// This is used by the regression test system to indicate which languages this algorithm is written in.
        /// </summary>
        public Language[] Languages { get; } = { Language.CSharp, Language.Python };

        /// <summary>
        /// This is used by the regression test system to indicate what the expected statistics are from running the algorithm
        /// </summary>
        public Dictionary<string, string> ExpectedStatistics => new Dictionary<string, string>
        {
            {"OrderListHash", "1076887691"}
        };
    }
}
```

**Comment by Martin-Molinero** [comment]
Hey @BadgerTheAdger !
With `AccountType.Cash` you need cash in the quote currency to be able to trade an asset. Wondering what behavior were you expecting? Think you could sell `"BTCUSDT"` to get some `USDT`?

**Comment by BadgerTheAdger** [comment]
Hello @Martin-Molinero ,

Here's my thinking of the issue:

1. Bitfinex / Binance list quote first, base second
2. _base_ in a pair means the currency we are buying with. 
3. _quote_ means the currency we are selling with.
4. example - in a Binance pair BTCUSDT where _base_ is USDT and _quote_ is BTC, when we buy, we use USDT to buy BTC. When we sell, we use BTC to buy USDT.
5. Lean expects "Quote" currency to be at the end of the symbol. - which I find ok - probably Lean needs to have a common format for symbols of all brokerages...?
![image](https://user-images.githubusercontent.com/33373431/97795712-18714e80-1c12-11eb-959e-59dce460a21e.png)
6. To make it work, we need to specify USDT (originally base) as quote. And BTC (originally quote) as base.
7. When we do a "buy", Lean buys base for quote. Which is a reversed concept and, in turn, a somewhat way to "recover" from the previous point which is an indicator of wrong behavior. I would say it's a **_crutch_** to make it clearer.
![image](https://user-images.githubusercontent.com/33373431/97795598-f1664d00-1c10-11eb-8731-1c6972a94546.png)


Till 5 point all is good. Except that Binance has a reversed symbol and so, to make it pass the 5th point, one needs to say that "Quote" is USDT (which it isn't). Once we say that Binance's USDT in BTCUSDT is **Quote**, it makes data inconsistent / turns it into a broken state. 

On the 6th point, we made USDT quote and BTC base. Because later, in the 7th point, Lean will use Quote to buy Base. Which is a reversed concept and I would think it's there because of the issue with Binance / Bitfinex / GDAX symbols? But that's a crutchy way of dealing with such issues. Until recent time I thought Lean had some mapping mechanisms that would map symbols to a common format / or simply ignore the format and use whatever is base and whatever is quote

This is my thinking of the situation. Can you carefully go through the points and explain why it's ok, why I need to specify base as quote and quote as base etc.? Maybe my understanding is incorrect, that is a possible option, as I'm only gaining my first experience in crypto-trading.

**Comment by BadgerTheAdger** [comment]
Hello @Martin-Molinero ,

Here's my thinking of the issue:

1. Bitfinex / Binance list quote first, base second
2. _base_ in a pair means the currency we are buying with. 
3. _quote_ means the currency we are selling with.
4. example - in a Binance pair BTCUSDT where _base_ is USDT and _quote_ is BTC, when we buy, we use USDT to buy BTC. When we sell, we use BTC to buy USDT.
5. Lean expects "Quote" currency to be at the end of the symbol. - which I find ok - probably Lean needs to have a common format for symbols of all brokerages...?
![image](https://user-images.githubusercontent.com/33373431/97795712-18714e80-1c12-11eb-959e-59dce460a21e.png)
6. To make it work, we need to specify USDT (originally base) as quote. And BTC (originally quote) as base.
7. When we do a "buy", Lean buys base for quote. Which is a reversed concept and, in turn, a somewhat way to "recover" from the previous point which is an indicator of wrong behavior. I would say it's a **_crutch_** to make it clearer.
![image](https://user-images.githubusercontent.com/33373431/97795841-f8428f00-1c13-11eb-947a-745a336b7bd0.png)

Till 5 point all is good. Except that Binance has a reversed symbol and so, to make it pass the 5th point, one needs to say that "Quote" is USDT (which it isn't). Once we say that Binance's USDT in BTCUSDT is **Quote**, it makes data inconsistent / turns it into a broken state. 

On the 6th point, we made USDT quote and BTC base. Because later, in the 7th point, Lean will use Quote to buy Base. Which is a reversed concept and I would think it's there because of the issue with Binance / Bitfinex / GDAX symbols? But that's a crutchy way of dealing with such issues. Until recent time I thought Lean had some mapping mechanisms that would map symbols to a common format / or simply ignore the format and use whatever is base and whatever is quote

This is my thinking of the situation. Can you carefully go through the points and explain why it's ok, why I need to specify base as quote and quote as base etc.? Maybe my understanding is incorrect, that is a possible option, as I'm only gaining my first experience in crypto-trading.

**Comment by Martin-Molinero** [comment]
Hey!

> base in a pair means the currency we are buying with.

> For example - in a Binance pair BTCUSDT where base is USDT and quote is BTC,

I believe the above isn't right, in the pair `BTCUSDT` `USDT` is the quote currency and `BTC` is the base currency. As you can see bellow `USDT` is used to determine the price of `BTC` and used to buy it (from `binance`)
![image](https://user-images.githubusercontent.com/18473240/98053177-bf263c80-1e16-11eb-8a16-b3169ff1ada6.png)

**Comment by BadgerTheAdger** [comment]
Hey @Martin-Molinero
Thank you for the response
I will need more time to make a research on this topic
Then I'll come back to you with an answer / update. Ok? So let's not close it now, I'll come back later with an update.

Also I'm not sure if you're getting notifications on closed issues, I posted a [comment](https://github.com/QuantConnect/Lean/issues/4878#issuecomment-722943843) in a closed issue
