### ISSUE TITLE
SecurityHolding uses time varying account currency conversion rates for internal calculations

### ISSUE THREAD

**Issue by mchandschuh** [QuantConnect/Lean#4774]
#### Expected Behavior

`SecurityHolding` uses conversion rates appropriate for each calculation. For example:
* `HoldingsCost` should use a conversion rate from the time the position was opened
* `TotalCloseProfit` should _probably_ use two different conversion rates, one to convert `_averagePrice` and another to convert `price`, in order to capture _carry_  gains/losses.

#### Actual Behavior
 
`SecurityHolding` always uses the current conversion rate from the security's quote currency to the account's quote currency. This impacts forex, such as `EURGBP`, and crypto, such as `ETHBTC`. Forex/Crypto with `USD` as the quote are unaffected since the conversion rate is always identity by definition. Luckily, this property doesn't appear to be used internally for any compound calculations, such as for profit/loss calculations (`UnrealizedProfit` depends on the `_averagePrice` member variables instead of the `HoldingsCost` property).

#### Potential Solution

Track conversion rates correlated with events that impact the security holdings. An organized way of doing this could be by adding a new type that encapsulates a quantity and two prices, one of which would be the price in the security's quote currency and another would be the price of the security's quote currency in the account's quote currency (conversion rate). This new type could additionally simplify much of the maths in `SecurityPortfolioModel` by abstracting/encapsulating the complexity of conversion rates.

#### Reproducing the Problem

Create an algorithm and purchase `EURGBP`. On each time step log `Portfolio["EURGBP"].HoldingsCost` and observe the value changing over time. For extra credit, before closing the `EURGBP` position, log `Portfolio["EURGBP"].TotalCloseProfit` and compare with the actual change in cash. This value will differ proportionally with the change in `GBPUSD` because it doesn't current account for the _carry_ 

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
- Close due to low impact and high cost to fix.
 - Potentially address this when we have Trade Management / Portfolio Holding Ticket Tracking (not averaging)
