### ISSUE TITLE
SetBrokerageModel(BrokerageName.Bitfinex, AccountType.Cash) throws when called after adding securities

### ISSUE THREAD

**Issue by StefanoRaggi** [QuantConnect/Lean#4784]
#### Expected Behavior
- `SetBrokerageModel` should not throw

#### Actual Behavior
- `SetBrokerageModel(BrokerageName.Bitfinex, AccountType.Cash)` throws the following exception:
```
CashBuyingPowerModel does not allow setting leverage. Cash accounts have no leverage.
```

#### Potential Solution
- Securities are added using the default brokerage model (in this case `BitfinexBrokerageModel` which defaults to `AccountType.Margin` and `Leverage = 3.3`), unless `SetBrokerageModel(BrokerageName.Bitfinex, AccountType.Cash)` is called first.

#### Reproducing the Problem
``` Python
class ModulatedVerticalThrustAssembly(QCAlgorithm):

    def Initialize(self):
        self.SetStartDate(2020, 3, 28)  # Set Start Date
        self.SetCash(100000)  # Set Strategy Cash
        
        self.AddCrypto('ETHUSD', Resolution.Minute)
        self.SetBrokerageModel(BrokerageName.Bitfinex, AccountType.Cash)
```

#### System Information
n/a

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
This issue has been solved, closing
