### ISSUE TITLE
Create Williams % R Indicator

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#48]
Create the Williams % R Indicator (http://en.wikipedia.org/wiki/Williams_%25R), and the associated "WILR" helper method in the QCAlgorithm base class. See introduction to indicators - https://lean.quantconnect.com/docs#topic9.html

Add the associated tests to Tests project under /Indicators to confirm the WILR values match up with the data provided in Tests/TestData/spy_with_williamsR14.txt file.

**Comment by mchandschuh** [comment]
Merged in 16f291 via PR#67

Thanks @AlexCatarino!
