### ISSUE TITLE
LocalObjectStore.GetFilePath Rewrites Existing File With New Name

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4811]
#### Expected Behavior
No file with duplicated information is created.

#### Actual Behavior
`LocalObjectStore.GetFilePath` creates a new file with information found in files loaded in `LocalObjectStore.Initialize`

#### Potential Solution
N/A

#### Reproducing the Problem
```python
import os
qb = QuantBook()

for i in range(2):
    qb.ObjectStore.Save(f'{chr(i+97)}.txt', f'{i}'*100)

keys = [str(j).split(',')[0][1:] for _, j in enumerate(qb.ObjectStore.GetEnumerator())]
sizes = [os.path.getsize(qb.ObjectStore.GetFilePath(key)) for key in keys]
for i in keys:
    path = qb.ObjectStore.GetFilePath(i)
    print(f"{i} - {path} - {os.path.getsize(path)/1e6:.1f} MB")
    print(f'Deleted? {qb.ObjectStore.Delete(i)}')
print(f"Total size: {sum(sizes)/1e6:.1f} MB in {len(sizes)} files")
```
Run this notebook once, the comment out lines 4 and 5, and run it again. We can see that there are more files in every new cell execution.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
`ObjectStore.Delete(key)` should probably be checking if the file exists on disk and delete it there too, using the same path as done by `ObjectStore.GetFilePath(key)`

**Comment by AlexCatarino** [comment]
#4816 did not solve all problems in this issue. If we comment out this statement:
```python
print(f'Deleted? {qb.ObjectStore.Delete(i)}')
```
and rerun the code, we will notice that new items will emerge. We can notice that it looks like a new item is a duplicate since it's key has the same value of the created file:
```
ce506ace22f28ac2bc4f933d4cf989fd.dat - /home/jovyan/work/storage/QuantBook/878a3d4e212091ada83424c6ff32da88.dat - 0.0 MB
b.txt - /home/jovyan/work/storage/QuantBook/ce506ace22f28ac2bc4f933d4cf989fd.dat - 0.0 MB
```
`ce506ace22f28ac2bc4f933d4cf989fd.dat` in this case.
