### ISSUE TITLE
RenkoBar printing incorrect bar on price reversal

### ISSUE THREAD

**Issue by aseedb** [QuantConnect/Lean#4841]
#### Expected Behavior
We are considering Renko charts. Let a bar size B.

Let a rising bar with an opening price of Y and a closing price of Y+B. 
Let the next bar be a falling bar. 
The latter bar will have an **opening price of Y and closing price of Y-B**.

Let a falling bar with an opening price of Y and a closing price of Y-B
Let the next bar be a rising bar. 
The latter bar will have an _opening price of Y and closing price of Y+B_.

see [an example chart on wikipedia](https://en.wikipedia.org/wiki/Renko_chart#/media/File:Renko_chart_example.png)

#### Actual Behavior
Let a rising bar with an opening price of Y and a closing price of Y+B. 
Let the next bar be a falling bar. 
The latter bar will have an **opening price of Y+B and a closing price of Y**.

Let a falling bar with an opening price of Y and a closing price of Y-B
Let the next bar be a rising bar. 
The latter bar will have an _opening price of Y-B and closing price of Y_.

#### Potential Solution
Direction of the previous Renko bar must be considered to set the limits of the next bar.

If the last consolidated Renko bar was rising, then the bar being consolidated must have an upper limit UL of
`UL =  open + bar size`,
 and a lower limit LL of
`LL = open - 2*bar size`

If the last consolidated Renko bar was falling, then the bar being consolidated must have an upper limit UL of
`UL =  open + 2*bar size`, 
and a lower limit LL of
`LL = open - bar size`

#### Reproducing the Problem
```
class RenkoConsolidatorAlgorithm(QCAlgorithm):
    def Initialize(self):
        self.SetStartDate(2012, 1, 1)
        self.SetEndDate(2012, 2, 1)
        self.AddForex("EURUSD", Resolution.Minute, Market.FXCM)
        renkoClose = RenkoConsolidator(0.003)
        renkoClose.DataConsolidated += self.HandleRenkoClose
        self.SubscriptionManager.AddConsolidator("EURUSD", renkoClose)

    def OnData(self, data):
        pass

    def HandleRenkoClose(self, sender, data):
        self.Log(f"open: {data.Open} close: {data.Close} direction: {data.Direction}")

```
#### System Information
online platform [https://www.quantconnect.com/terminal/](https://www.quantconnect.com/terminal/)
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Potential duplicat of https://github.com/QuantConnect/Lean/issues/2853

**Comment by aarjaneiro** [comment]
Hello @aseedb,
I was going through your code for reproducing the problem but was unable to see anything out of the ordinary. Moreover, running the following on the cloud service does not seem to point to any irregularities with respect to the bar direction:
```
class RenkoConsolidatorAlgorithm(QCAlgorithm):
    def Initialize(self):
        self.SetStartDate(2012, 1, 1)
        self.SetEndDate(2012, 2, 1)
        self.AddForex("EURUSD", Resolution.Minute, Market.FXCM)
        # public RenkoConsolidator(decimal barSize, bool evenBars = true)
        renkoClose = RenkoConsolidator(0.003)
        # public WickedRenkoConsolidator(decimal barSize)
        wickedRenkoClose = WickedRenkoConsolidator(0.003)
        renkoClose.DataConsolidated += self.HandleRenkoClose
        wickedRenkoClose.DataConsolidated += self.HandleRenkoClose
        self.SubscriptionManager.AddConsolidator("EURUSD", renkoClose)
        self.SubscriptionManager.AddConsolidator("EURUSD", wickedRenkoClose)
    def OnData(self, data):
        pass
    def HandleRenkoClose(self, sender, data):
        # self.Log(f"open: {data.Open} close: {data.Close} direction: {data.Direction}")
        boolDir = data.Open > data.Close
        if boolDir:
            self.Log(f"{data.Direction == 2}") # falls
        else:
            self.Log(f"{data.Direction == 0}") # rises
```
If the bug still indeed exists, could you clarify where *exactly* we would expect to see a discrepancy in your code for reproducing the problem?
