### ISSUE TITLE
Paper trading launched via QuantConnect.Lean.Launcher won't stop

### ISSUE THREAD

**Issue by BadgerTheAdger** [QuantConnect/Lean#4845]
Hi everyone, 

I have launched some paper trading stuff via the **QuantConnect.Lean.Launcher** project and I have configured config.json to use "paper-binance" environment, I have binance keys populated I debugged the flow it works. But I can't stop the paper trading how can I do that? And get the results via result-handler? What does the duration depend on? It's been working for 2 hours already.

Thanks,
Mark

**Comment by BadgerTheAdger** [comment]
![image](https://user-images.githubusercontent.com/33373431/95726710-f07d7380-0c81-11eb-97bb-cf054939b59f.png)
I keep getting this output

**Comment by BadgerTheAdger** [comment]
![image](https://user-images.githubusercontent.com/33373431/95733174-68e83280-0c8a-11eb-8643-6b4782cdbfc5.png)
I have debugged through the code and the _fast and _slow are never ready... it's was ready with backtesting on 1000th call but with live trading the 1000th call will be in years

**Comment by BadgerTheAdger** [comment]
Algorithm code: 

`
using System;
using System.Collections.Generic;
using System.Linq;
using QuantConnect.Data;
using QuantConnect.Brokerages;
using QuantConnect.Indicators;
using QuantConnect.Orders;
using QuantConnect.Interfaces;
using QuantConnect.Configuration;

namespace QuantConnect.Algorithm.CSharp
{
    /// <summary>
    /// The demonstration algorithm shows some of the most common order methods when working with Crypto assets.
    /// </summary>
    public class BasicTemplateCryptoAlgorithmQuickSMA : QCAlgorithm, IRegressionAlgorithmDefinition
    {
        private SimpleMovingAverage _fast;
        private SimpleMovingAverage _slow;
        private DateTime _previous;

        private readonly string _symbol = Config.Get("benchmark-symbol");
        private readonly string BC = Config.Get("default-currency");
        private readonly string QC = Config.Get("quote-currency");

        private Resolution _resolution = Resolution.Daily;

        /// <summary>
        /// Initialise the data and resolution required, as well as the cash and start-end dates for your algorithm. All algorithms mUSDT initialized.
        /// </summary>
        public override void Initialize()
        {
            SetStartDate(2020, 02, 01);
            SetEndDate(2020, 06, 01);

            //TraceDuration();    // Trace the duration to validate against the requested data

            SetCash(BC, 1);

            var brokerageName = Enum.Parse<BrokerageName>(Config.Get("benchmark-market"));

            SetBrokerageModel(brokerageName, AccountType.Cash);

            // You can uncomment the following line when live trading with GDAX,
            // to ensure limit orders will only be posted to the order book and never executed as a taker (incurring fees).
            // Please note this statement has no effect in backtesting or paper trading.
            // DefaultOrderProperties = new GDAXOrderProperties { PostOnly = true };

            // Find more symbols here: http://quantconnect.com/data
            AddCrypto(_symbol);

            // create two moving averages
            _fast = SMA(_symbol, 1, _resolution);
            _slow = SMA(_symbol, 1, _resolution);
        }

        /// <summary>
        /// OnData event is the primary entry point for your algorithm. Each new data point will be pumped in here.
        /// </summary>
        /// <param name="data">Slice object keyed by symbol containing the stock data</param>
        public override void OnData(Slice data)
        {
            TraceSlice(data);

            if (!(_fast.IsReady && _slow.IsReady))
                return;

            var hBC = Portfolio.CashBook[BC];
            var hQC = Portfolio.CashBook[QC];
            var holding = Portfolio[_symbol];

            // If the Fast is over the Slow SMA and we don't have any holdings let's go long
            if (hQC.Amount == 0 && hBC.Amount > 0 && _fast.Current.Value > _slow.Current.Value)
            {
                TraceData("Buy ", holding);

                // Submit a buy limit order for BTC at 5% below the current price
                var usdTotal = hBC.Amount;
                var limitPrice = Math.Round(Securities[_symbol].Price * 0.95m, 2);

                // use only half of our total USD
                if (limitPrice != 0)
                {
                    var quantity = usdTotal * 0.5m / limitPrice;
                    Buy(_symbol, quantity);

                    // LimitOrder(_symbol, quantity, limitPrice);
                }
            }
            else if (hQC.Amount > 0 && _slow.Current.Value < _fast.Current.Value)
            {
                TraceData("Sell", holding);

                Sell(_symbol, hQC.Amount);
            }
            else
            {
                TraceData("Hold", Portfolio[_symbol]);
            }

            _previous = Time;
        }

        public override void OnOrderEvent(OrderEvent orderEvent)
        {
            //Log($"OnOrderEvent | {orderEvent.Symbol} Direction:{orderEvent.Direction}, Status:{orderEvent.Status}, Filled @ {orderEvent.FillPrice} {orderEvent.FillPriceCurrency} {orderEvent.OrderFee}");
        }

        public override void OnEndOfAlgorithm()
        {
            Log($"OnEndOfAlgorithm | {Time} - TotalPortfolioValue: {Portfolio.TotalPortfolioValue}");
            Log($"OnEndOfAlgorithm | {Time} - CashBook: {Portfolio.CashBook}");
        }

        /// <summary>
        /// This is used by the regression test system to indicate if the open source Lean repository has the required data to run this algorithm.
        /// </summary>
        public bool CanRunLocally { get; } = true;

        /// <summary>
        /// This is used by the regression test system to indicate which languages this algorithm is written in.
        /// </summary>
        public Language[] Languages { get; } = { Language.CSharp, Language.Python };

        /// <summary>
        /// This is used by the regression test system to indicate what the expected statistics are from running the algorithm
        /// </summary>
        public Dictionary<string, string> ExpectedStatistics => new Dictionary<string, string>
        {
            {"OrderListHash", "1076887691"}
        };
    }
}
`

**Comment by BadgerTheAdger** [comment]
QCAlgorithm defaults end date to 2050 and in the algorithmmanager the loop finishes only when a slice's enddate is past the algorithm's enddate. Can you help me understand how live / paper trading works?

**Comment by Martin-Molinero** [comment]
Hey @BadgerTheAdger! Live trading does not end unless explicitly ending it (or some unexpected error happens) see `QCAlgorithm.Quit()`. Regarding the indicators, you could use `QCAlgorithm.SetWarmUp()` or even just directly warm up the indicators. Curious what's the live trading use case you were thinking about? Closing this since it isn't a Lean issue.

**Comment by BadgerTheAdger** [comment]
Well I simply want to do a bit of a paper + live day-trading. Thanks for the help. Can you also clarify - Can I stop the engine from launcher? i.e in the launcher I will modify it to call Engine.Algorithm.Quit or something like that? How is that achievable from the external code (i.e the launcher) not the algorithm instead?

**Comment by BadgerTheAdger** [comment]
@Martin-Molinero can you also clarify this _slow and _fast readiness - when is it gonna be ready? I expect to launch the engine and start trading right away or maybe like in an hour, but it's been 5 hours it's still not ready, can you please comment this

**Comment by Martin-Molinero** [comment]
Hey Mark! Sorry for the late response,

>  Thanks for the help. Can you also clarify - Can I stop the engine from launcher? i.e in the launcher I will modify it to call Engine.Algorithm.Quit or something like that? How is that achievable from the external code (i.e the launcher) not the algorithm instead?

Addressed at https://github.com/QuantConnect/Lean/pull/4972

> when is it gonna be ready? I expect to launch the engine and start trading right away or maybe like in an hour, but it's been 5 hours it's still not ready, can you please comment this

Please take a look at `QCAlgorithm.SetWarmUp()` or there's also `EnableAutomaticIndicatorWarmUp`, there are examples of both usages at [Algorithm.CSharp](https://github.com/QuantConnect/Lean/tree/master/Algorithm.CSharp) and [Algorithm.Python](https://github.com/QuantConnect/Lean/tree/master/Algorithm.Python)
