### ISSUE TITLE
SetAccountCurrency cannot be called more than once

### ISSUE THREAD

**Issue by StefanoRaggi** [QuantConnect/Lean#4855]
#### Expected Behavior
- Users should be able to override the account currency set automatically from a live brokerage (new feature merged in #4806)

#### Actual Behavior
- In live mode, after the account currency has been set from the brokerage, `algorithm.SetAccountCurrency()` does not change the account currency and only logs this warning:
```
SecurityPortfolioManager.SetAccountCurrency(): account currency has already been set to EUR. Will ignore new value USD.
```

#### Potential Solution
Remove the `_setAccountCurrencyWasCalled` check

#### Reproducing the Problem
- Deploy an algorithm to Oanda `EUR` account with `SetAccountCurrency("USD")` in `algorithm.Initialize()`

#### System Information
n/a

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by StefanoRaggi** [comment]
Reopening as the issue is not resolved yet

**Comment by jaredbroad** [comment]
Closing as we normally make the live deploys use brokerage-defined values. i.e. IB returns the account currency.
