### ISSUE TITLE
Option chain not loaded when only quote data exists in a single day

### ISSUE THREAD

**Issue by gsalaz98** [QuantConnect/Lean#4858]
#### Expected Behavior

We are able to load an option chain, provided that either quotes or trade data exists for a given day for the underlying Symbol.
#### Actual Behavior

We are unable to load an option chain if we have only quote data, but not trade data for a given day for the underlying Symbol.
#### Potential Solution

Add QuoteBar to the configs list here: https://github.com/QuantConnect/Lean/blob/9cdb4a91c58b9f9d81c500e9ba0a339dc5b1ba75/Engine/DataFeeds/Enumerators/Factories/OptionChainUniverseSubscriptionEnumeratorFactory.cs#L104, so that an underlying BaseData instance is resolved, allowing the option chain to be included in the algorithm:

```c#
var configurations = new List<SubscriptionDataConfig>
{
    // add underlying trade data
    new SubscriptionDataConfig(config, resolution: resolution, fillForward: true, symbol: underlying, objectType: typeof (TradeBar), tickType: TickType.Trade),
    new SubscriptionDataConfig(config, resolution: resolution, fillForward: true, symbol: underlying, objectType: typeof (QuoteBar), tickType: TickType.Quote),
};
```
#### Reproducing the Problem

Load an option chain for a Symbol with quotes, but no trades
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Midterm solution following the 'universe' pattern, where we create a daily universe file which will contain all the option/future/etc chain contracts & the underlying prices, this issue will be responsibility of the universe chain generator.
In the case the underlying had no trades for a date we could fill forward previous day trades and provide quote information too
