### ISSUE TITLE
ApiPriceProvider is no longer supported

### ISSUE THREAD

**Issue by C-SELLERS** [QuantConnect/Lean#4859]
#### Expected Behavior

N/A

#### Actual Behavior

ApiPriceProvider is implemented but GetLastPrice function does not work because the endpoint is no longer supported.

#### Potential Solution

Remove `ApiPriceProvider` and refactor its dependents as needed

#### Reproducing the Problem

Try using `ApiPriceProvider`'s `GetLastPrice()`

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by C-SELLERS** [comment]
Note on #4838 , The PR wrote over the function and NOP'd it out, but the class still exists and we should still refactor.

**Comment by jaredbroad** [comment]
- Remove from LEAN and all the brokerage plugins.
