### ISSUE TITLE
Bitfinex ProcessTradeUpdate out of range exception

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#4862]
#### Expected Behavior

- No out of range exception
#### Actual Behavior

```
Brokerage.OnMessage(): Error - Code: -1 - Parsing wss message failed. Data: [23568,[2.6316,0,1]] Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at QuantConnect.Brokerages.Bitfinex.BitfinexSubscriptionManager.ProcessTradeUpdate (QuantConnect.Data.Channel channel, System.String[] entries) [0x00058] in <f9964629229b45f38eadcfc9ba8c2068>:0
  at QuantConnect.Brokerages.Bitfinex.BitfinexSubscriptionManager.OnUpdate (System.Int32 channelId, System.String[] entries) [0x0009b] in <f9964629229b45f38eadcfc9ba8c2068>:0
  at QuantConnect.Brokerages.Bitfinex.BitfinexSubscriptionManager.OnMessage (System.Object sender, QuantConnect.Brokerages.WebSocketMessage e) [0x00139] in <f9964629229b45f38eadcfc9ba8c2068>:0
```
#### Potential Solution

- Review implementation avoid out of range exception 
#### Reproducing the Problem

- Believe the exception has the data in the message that produced the issue `Data: [23568,[2.6316,0,1]]`
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by StefanoRaggi** [comment]
Very strange...
The message format is correct: `[23568,[2.6316,0,1]]` is an order book update but was processed as a trade 😕 

Trades should only be processed here:
https://github.com/QuantConnect/Lean/blob/master/Brokerages/Bitfinex/BitfinexSubscriptionManager.cs#L383
Order book updates should only be processed here:
https://github.com/QuantConnect/Lean/blob/master/Brokerages/Bitfinex/BitfinexSubscriptionManager.cs#L410
then here:
https://github.com/QuantConnect/Lean/blob/master/Brokerages/Bitfinex/BitfinexSubscriptionManager.cs#L613

For some reason, an order book update came through the "trades" channel and was passed in here:
https://github.com/QuantConnect/Lean/blob/master/Brokerages/Bitfinex/BitfinexSubscriptionManager.cs#L617

Seems the channel id mapping was incorrect, maybe it happened after a disconnect/reconnect?

The only potential missing lock I'm seeing in the code is here:
https://github.com/QuantConnect/Lean/blob/master/Brokerages/Bitfinex/BitfinexSubscriptionManager.cs#L148
