### ISSUE TITLE
Live realtime prices update after hours even if extended market hours are false

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#487]
In live trading -- the charting/data sampling continues to get updated with updated TotalPortfolioValue values even after the market has closed - indicating the SetRealTimePrice() is being set after market close, and then the result handler is sampling that updated price.

If the subscription sets extended: false we probably shouldn't set the real-time prices after-hours either.

**Comment by mchandschuh** [comment]
I wonder how IB evaluates portfolio value for margin calculations in these
events and whether or not we should follow IB here.

**Comment by jaredbroad** [comment]
Not sure, but it would seem unethical/impossible to trigger margin calls on pre/post market prices (they can vary wildly with no liquidity). Its probably market hours only?

Its not the data loop getting called, just the charting sampling. 95% of people don't care about pre-post market data so no reason to show it in results and potentially scare people (with large drops in portfolio value because of a single post market trade etc).

**Comment by mchandschuh** [comment]
Don't disagree with the margin calls. I was thinking about trading multiple
markets, say forex and us equities. If the after market price plummets,
will it affect how much currency you can trade in forex market.

**Comment by jaredbroad** [comment]
Fixed by pr #809
