### ISSUE TITLE
Data Download via QuantConnect.ToolBox.exe not working

### ISSUE THREAD

**Issue by TheRealBecks** [QuantConnect/Lean#4874]
#### Expected Behavior
Data download via QuantConnect.ToolBox.exe gets started.

#### Actual Behavior
I get an error that '--tickers=' or '--resolution=' parameter is missing. I tried different example commands from the forum - they worked in the forum, but not for my installation.

As you can see I'm using mono under Linux (OpenSue Tumbleweed). The configuration and compilation of Lean worked flawlessly. I also tested a default Python algorithm - it also worked. But the data downloader via QuantConnect.ToolBox.exe isn't working:

```
$ mono QuantConnect.ToolBox.exe --app=IEXDownloader --tickers=NFLX --resolution=Daily --from-date=20200820-00:00:00 --to-date=20200830-00:00:00 --api-key="key"    
IEXDownloader ERROR: '--tickers=' or '--resolution=' parameter is missing
--tickers=eg SPY,AAPL
--resolution=Minute/Daily
```

Another test:
```
$ mono QuantConnect.ToolBox.exe --app=YahooDownloader --tickers=AAPL --resolution=Daily --from-date=20200820-00:00:00 --to-date=20200830-00:00:00 
YahooDownloader ERROR: '--tickers=' or '--resolution=' parameter is missing
--tickers=eg SPY,AAPL
--resolution=Daily
```

#### Reproducing the Problem
Maybe you will get the error only under Linux? Don't know. Go into the directory 'Lean/Launcher/bin/Debug' and start 'mono QuantConnect.ToolBox.exe ...'.

#### System Information

- OS: openSUSE Tumbleweed
- Lean Version: Current git master, downloaded today (2020-10-18)

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by TheRealBecks** [comment]
What I found out so far:

There are three files involved:

- Lean/Configuration/ToolboxArgumentParser.cs --> parses arguments
- Lean/ToolBox/Program.cs --> passes the arguments to the function 'YahooDownloaderProgram.YahooDownloader(tickers, resolution, fromDate, toDate)'
- Lean/ToolBox/YahooDownloader/YahooDownloaderProgram.cs --> 'if (resolution.IsNullOrEmpty() || tickers.IsNullOrEmpty())'
 --> The variables seems to be empty.

I would like to print the variables, but I don't know how to do that in C#, I'm a Python programmer. I tried it with that code snippet in 'Program.cs' exactly this way in the 'case' (I added the 'Console.WriteLine' lines):
```
case "yahoodownloader":
    Console.WriteLine("targetApp: ", targetApp);
    Console.WriteLine("tickers: ", tickers);
    Console.WriteLine("resolution: ", resolution);
    Console.WriteLine("fromDate: ", fromDate);
    Console.WriteLine("toDate: ", toDate);
    YahooDownloaderProgram.YahooDownloader(tickers, resolution, fromDate, toDate);
    break;
```
I get the output on the console, but the variables like 'targetApp' are empty, but that doesn't make sense as the variable 'targetApp' needs to be set to 'yahoodownloader' to get this case running. How can I print these variables for further debugging?

**Comment by TheRealBecks** [comment]
Ok, I found out how to print correctly:
```
Console.WriteLine("tickers: " + tickers);
Console.WriteLine("resolution: " + resolution);
Console.WriteLine("fromDate: " + fromDate);
Console.WriteLine("toDate: " + toDate);
```
And:
```
foreach (KeyValuePair<string, object> arg in optionsObject)
{
  Console.WriteLine("Key: {0}, Value: {1}",
  arg.Key, arg.Value);
}
```
At the end I used this foreach loop in 'Program.cs':
```
var optionsObject = ToolboxArgumentParser.ParseArguments(args);
if (optionsObject.Count == 0)
{
    PrintMessageAndExit();
}
foreach (KeyValuePair<string, object> arg in optionsObject)
{
    Console.WriteLine("Key: {0}, Value: {1}",
    arg.Key, arg.Value);
}
```

And that's the output:
```
Key: app, Value: YahooDownloader
Key: tickers, Value: System.Collections.Generic.Dictionary`2[System.String,System.String]
Key: resolution, Value: Daily
Key: from-date, Value: 20200820-00:00:00
Key: to-date, Value: 20200830-00:00:00
YahooDownloader ERROR: '--tickers=' or '--resolution=' parameter is missing
--tickers=eg SPY,AAPL
--resolution=Daily
```

I don't know what ```System.Collections.Generic.Dictionary`2[System.String,System.String]``` is? And I did not find out how to print that value - if there is any.

I added the following lines to YahooDownloaderProgram.cs:
```
Console.WriteLine("YahooDownloader");
Console.WriteLine("tickers: " + tickers);
Console.WriteLine("resolution: " + resolution);
Console.WriteLine("startDate: " + startDate);
Console.WriteLine("endDate: " + endDate);
```
And that's the output:
```
Key: app, Value: YahooDownloader
Key: tickers, Value: System.Collections.Generic.Dictionary`2[System.String,System.String]
Key: resolution, Value: Daily
Key: from-date, Value: 20200820-00:00:00
Key: to-date, Value: 20200830-00:00:00
YahooDownloader
tickers: 
resolution: Daily
startDate: 20.08.2020 00:00:00
endDate: 30.08.2020 00:00:00
YahooDownloader ERROR: '--tickers=' or '--resolution=' parameter is missing
--tickers=eg SPY,AAPL
--resolution=Daily
```

Does anyone know where the problem is?

**Comment by Martin-Molinero** [comment]
Hey @TheRealBecks, thanks for the report, this bug was introduced a couple of days ago by https://github.com/QuantConnect/Lean/pull/4819/files, I've opened a PR to fix it.
