### ISSUE TITLE
Include Algorithm Parameters in Report & Result

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4881]
#### Expected Behavior
`Report` includes the list of parameters used.

#### Actual Behavior
Users need to manually distinguish between backtests with different parameters.

#### Potential Solution
- Add `IAlgorithm.GetParameters` (which is currently not on the interface)
- The `AlgorithmPythonWrapper` would call the `_baseAlgorithm.GetParameters`
- Add `Parameters` to `AlgorithmConfiguration` so they are stored for live & backtest results. Use  `AlgorithmConfiguration.Create()`
- ~If available in result json, and not empty, add Parameters to report~

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jcandan** [comment]
Especially considering that when deleting a parameter in Quantconnect, the parameter value it was set to seems to be cached.

**Comment by i3130002** [comment]
After almost a year, May I ask for followup on this? @AlexCatarino

**Comment by DerekMelchin** [comment]
This issue was closed, but I don't see the algorithm parameters in the [report.pdf](https://github.com/QuantConnect/Lean/files/10735114/report.pdf)

https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_eb8632af39d091b0dd431fd81658530a.html
