### ISSUE TITLE
Bar consolidation appears to include extra data for the first aggregation, subsequent aggregations are inaccurate

### ISSUE THREAD

**Issue by imphasing** [QuantConnect/Lean#4885]
#### Expected Behavior

15m bar consolidates 15 1m bars starting from the correct genesis point, resulting in accurate 15m bars based on the aggregation timeframe

#### Actual Behavior

first 15m bar contains 16 1m bars, but claims to be a correct 15m bar - subsequent bars claim to be correct 15m bars (eg 9:45-10:00) but actually contain offset 1m data bars (9:46-10:01) in the data aggregated on

#### Potential Solution

Consolidate bars from start time to end time for the first bar

In https://github.com/QuantConnect/Lean/blob/98d3a986564c86530daa3d81b778cda0f738ce9b/Common/Data/Consolidators/PeriodCountConsolidatorBase.cs#L132 you can see that it aggregates based on the "Time" property, which is bar start time. This results in start - start time aggregation, which means 9:30 start to 9:45 start, which is actually 9:30 start to 9:46 close. The aggregated bar shows as a correct 15m bar due to it being based on a computed property, not the actual data aggregated (https://github.com/QuantConnect/Lean/blob/master/Common/Data/Market/TradeBar.cs#L107)

I believe this results *the first* aggregated bar containing 1 extra data piece from the aggregation time frame, but display and claim to be accurate aggregated bars - subsequent bars are based on 1 data piece offset, but claim to be accurate aggregated bars.

I've placed logging into LEAN to validate this (IQFeed historical data, 1m timeframe, NOW american equity):

	476.47,478,476.16,476.16 -  opens: 9/16/2020 9:30:00 AM closes: 9/16/2020 9:31:00 AM
	476.65,477.62,476.65,477.165 -  opens: 9/16/2020 9:31:00 AM closes: 9/16/2020 9:32:00 AM
	476.995,477.932,476.02,477.66 -  opens: 9/16/2020 9:32:00 AM closes: 9/16/2020 9:33:00 AM
	476.85,477.98,475.875,477.98 -  opens: 9/16/2020 9:33:00 AM closes: 9/16/2020 9:34:00 AM
	477.26,477.76,476.265,476.265 -  opens: 9/16/2020 9:34:00 AM closes: 9/16/2020 9:35:00 AM
	476.73,477.2009,475.965,476.5 -  opens: 9/16/2020 9:35:00 AM closes: 9/16/2020 9:36:00 AM
	476.405,477.345,476.405,476.91 -  opens: 9/16/2020 9:36:00 AM closes: 9/16/2020 9:37:00 AM
	477.05,477.98,477,477.98 -  opens: 9/16/2020 9:37:00 AM closes: 9/16/2020 9:38:00 AM
	477.82,478.65,477.82,478.65 -  opens: 9/16/2020 9:38:00 AM closes: 9/16/2020 9:39:00 AM
	479.04,479.44,478.1,478.1 -  opens: 9/16/2020 9:39:00 AM closes: 9/16/2020 9:40:00 AM
	478.2299,478.2299,477.86,477.86 -  opens: 9/16/2020 9:40:00 AM closes: 9/16/2020 9:41:00 AM
	477.2701,478.01,475.25,475.3 -  opens: 9/16/2020 9:41:00 AM closes: 9/16/2020 9:42:00 AM
	475.31,475.5923,474.15,474.345 -  opens: 9/16/2020 9:42:00 AM closes: 9/16/2020 9:43:00 AM
	474.39,474.39,472.19,472.19 -  opens: 9/16/2020 9:43:00 AM closes: 9/16/2020 9:44:00 AM
	472.28,472.28,470.35,470.7 -  opens: 9/16/2020 9:44:00 AM closes: 9/16/2020 9:45:00 AM
	470.95,471.405,470.14,471.07 -  opens: 9/16/2020 9:45:00 AM closes: 9/16/2020 9:46:00 AM
	--- 15m ---476.47,479.44,470.35,470.7 - opens: 9/16/2020 9:30:00 AM closes: 9/16/2020 9:45:00 AM
	470.69,470.85,469.33,469.7899 -  opens: 9/16/2020 9:46:00 AM closes: 9/16/2020 9:47:00 AM
	469.49,469.98,469.2,469.62 -  opens: 9/16/2020 9:47:00 AM closes: 9/16/2020 9:48:00 AM
	469.64,470.04,469.05,469.05 -  opens: 9/16/2020 9:48:00 AM closes: 9/16/2020 9:49:00 AM
	468.36,468.36,467.02,467.52 -  opens: 9/16/2020 9:49:00 AM closes: 9/16/2020 9:50:00 AM
	467.07,467.57,466.46,466.46 -  opens: 9/16/2020 9:50:00 AM closes: 9/16/2020 9:51:00 AM
	466.75,468.58,466.75,468.58 -  opens: 9/16/2020 9:51:00 AM closes: 9/16/2020 9:52:00 AM
	468.495,469.15,468,468.93 -  opens: 9/16/2020 9:52:00 AM closes: 9/16/2020 9:53:00 AM
	469.27,469.81,469.1766,469.33 -  opens: 9/16/2020 9:53:00 AM closes: 9/16/2020 9:54:00 AM
	469.02,469.255,468.0101,468.8 -  opens: 9/16/2020 9:54:00 AM closes: 9/16/2020 9:55:00 AM
	468.91,469.69,468.91,469.69 -  opens: 9/16/2020 9:55:00 AM closes: 9/16/2020 9:56:00 AM
	469.58,470.28,468.715,468.715 -  opens: 9/16/2020 9:56:00 AM closes: 9/16/2020 9:57:00 AM
	468.44,468.87,468.19,468.19 -  opens: 9/16/2020 9:57:00 AM closes: 9/16/2020 9:58:00 AM
	467.88,468.12,467.5,468.025 -  opens: 9/16/2020 9:58:00 AM closes: 9/16/2020 9:59:00 AM
	467.64,468.41,467.64,468.41 -  opens: 9/16/2020 9:59:00 AM closes: 9/16/2020 10:00:00 AM
	469.1,469.305,468.675,468.82 -  opens: 9/16/2020 10:00:00 AM closes: 9/16/2020 10:01:00 AM
	--- 15m ---470.95,471.405,466.46,468.41 - opens: 9/16/2020 9:45:00 AM closes: 9/16/2020 10:00:00 AM

Where it says "--- 15m ---" that is when the consolidator fires its DataConsolidated event. When I look at the Update method in PeriodCountConsolidatorBase.cs I see that it is using .Time to aggregate on, which is always open time..

#### Reproducing the Problem

Aggregate data, I am using:

    var warmupConsolidator = new TradeBarConsolidator(TimeSpan.FromMinutes(15));
    warmupConsolidator.DataConsolidated += (e, bar) =>
    {
        vc.Update(bar);
    };

and using it with historical data from:

    var history = History(60 * 6 * 30, Resolution.Minute);

#### System Information
Windows 10 client OS 1607, LEAN from github latest

#### Checklist

- [x] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by imphasing** [comment]
it's likely the only impact is the first bar is messed up, and the next bars are correctly aggregated but on data that is offset, eg 9:46 - 10:01 so it is 15 minutes but offset 1m

**Comment by imphasing** [comment]
This appears to only apply to historical data - live trading seems to be accurate on the correct timestamp, this is probably just about where the aggregation starts for historical data..

I've verified with IQFeed that my *live* aggregated data event fires at the correct time (11:45 AM PST in this case)

**Comment by Martin-Molinero** [comment]
Hey @imphasing!
Thanks for the report! I'm not sure it's an issue though, the `PeriodCountConsolidatorBase` will emit when a new bar comes in that's after the expected close time of the current work bar **but will not use it in the aggregation**, check https://github.com/QuantConnect/Lean/blob/master/Common/Data/Consolidators/PeriodCountConsolidatorBase.cs#L178 `if (_workingBar != null && data.Time - _workingBar.Time >= _period.Value && GetRoundedBarTime(data.Time) > _lastEmit)`, this will cause it to emit and it won't use that bar.
See the following unit test passing in `master`
```
        [Test]
        public void CorrectlyAggregatesFromMinuteBars()
        {
            QuoteBar quoteBar = null;
            var creator = new QuoteBarConsolidator(TimeSpan.FromMinutes(3));
            creator.DataConsolidated += (sender, args) =>
            {
                quoteBar = args;
            };

            var time = new DateTime(2020, 10, 30, 9, 0, 0);
            for (var i = 0; i < 4; i++)
            {
                var bar1 = new QuoteBar
                {
                    Time = time.AddMinutes(i), // end Time is 1 more minute
                    Symbol = Symbols.SPY,
                    Bid = new Bar(i, i, i, i),
                    LastBidSize = i,
                    Ask = null,
                    Value = i
                };
                creator.Update(bar1);
            }

            // emitted bar used data from minute 0 to 2 start time. Last endTime is minute 3.
            Assert.IsNotNull(quoteBar);
            Assert.IsNull(quoteBar.Ask);
            Assert.AreEqual(2, quoteBar.Bid.High);
            Assert.AreEqual(2, quoteBar.Bid.Close);
            Assert.AreEqual(0, quoteBar.Bid.Low);
            Assert.AreEqual(0, quoteBar.Bid.Open);

            // working bar, not emitted, is using the bar going from minute 3 to 4
            var workingQuoteBar = creator.WorkingData as QuoteBar;
            Assert.IsNotNull(workingQuoteBar);
            Assert.IsNull(workingQuoteBar.Ask);
            Assert.AreEqual(3, workingQuoteBar.Bid.High);
            Assert.AreEqual(3, workingQuoteBar.Bid.Close);
            // opens at the prev close
            Assert.AreEqual(2, workingQuoteBar.Bid.Low);
            Assert.AreEqual(2, workingQuoteBar.Bid.Open);
        }
```

**Comment by Martin-Molinero** [comment]
Closing for now since no response.
