### ISSUE TITLE
Handle Ambiguous Contract Definition in Interactive Brokers

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4889]
#### Expected Behavior
No error message.

#### Actual Behavior
When the algorithm tried to place an order for SPCE in live mode, it receives the following message:
```
The contract description specified for SPCE is ambiguous
```
#### Potential Solution
N/A

#### Reproducing the Problem
Place limit order for SPCE to IBKR.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jhonabreul** [comment]
Cannot reproduce this issue as of 2023/02/22. According to IB, a workaround for this is setting the `PrimaryExchange` to the `Contract`, which is [already being done by the IB brokerage](https://github.com/QuantConnect/Lean.Brokerages.InteractiveBrokers/blob/c4a1c8c6c81693124abe79e717edaae8818c990a/QuantConnect.InteractiveBrokersBrokerage/InteractiveBrokersBrokerage.cs#L2544-L2547)
