### ISSUE TITLE
Refactor Fundamental Universe Data / Gain History and 10x Speed Gain

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#4890]
#### Expected Behavior

History requests for fundamental data is implemented in both the research and backtesting environment.

#### Actual Behavior

History requests for fundamental data is not implemented in the backtesting environment.

#### Potential Solution

Add fundamental history method to backtesting environment.

#### Reproducing the Problem

Try requesting historical fundamental data in the backtesting environment.

#### System Information

Windows 10.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by fishstoryyy** [comment]
Any update on this?

**Comment by kfeldspar** [comment]
I'd also like this feature. Any update?

**Comment by violet-day** [comment]
Any update on this?

**Comment by gjkendall** [comment]
Coming up on one year of this being open.  Can we get this done pretty please?
?????

**Comment by grocco** [comment]
Any progress on this? Happy to help!

**Comment by tmcdonough** [comment]
This would be very helpful! importing quantbook is quite slow

**Comment by taglia** [comment]
This would be a very useful addition, especially since the using the `GetFundamental` qb method does not seem to work from the fine selection method (I want to warm up some rolling windows using historical fundamental data). I wonder if this is taking so long because it is not within the agreement with Morningstar?

**Comment by jaredbroad** [comment]
- Rip out Fine Fundamental data source.
 - Convert MorningStar to be a normal 1D alternative data source, linked to underlying assets.
 - Add Shardar as a second 1D alternative data source, 
 - Adding fine universe data then is "just another alternative dataset" and 100x faster.
 - History for alternative datasets would work as others do already.

**Comment by gjkendall** [comment]
Would love to see this implemented as I will use it immediately and am waiting on it.

**Comment by jaredbroad** [comment]
Congrats team; thank you for the patience community 🙏 

It's in production on QC's website with an 8-10x speed increase. We'll publish its documentation today—a formal announcement next week.
