### ISSUE TITLE
Create Rate of Change Indicator, Rate of Change Percent

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#49]
Create a Rate of Change indicator and associated ROC and associated helper method QCAlgorithm base class. See introduction to indicators https://lean.quantconnect.com/docs#topic9.html

More information on the ROC indicator. 
 - http://www.investopedia.com/terms/p/pricerateofchange.asp
 - http://research.scottrade.com/knowledgecenter/Public/education/Article?docid=8813a3b19ac04f2fbcad244836a5e43c

The Momentum.cs indicator could be a good template to start from. ROCP is almost identical; just like MOM%. It makes sense to create both these indicators at the same time. 

Add the associated tests to Tests project under /Indicators to confirm the ROC and ROCP values match up with the data provided in Tests/TestData/spy_with_roc50.txt file, spy_with_rocp50.txt file.

**Comment by mchandschuh** [comment]
Merged in 6bfc70.

Thanks @AlexCatarino for the awesome contribution!
