### ISSUE TITLE
Periods other than 1m, 1h & 1day

### ISSUE THREAD

**Issue by pomeara** [QuantConnect/Lean#4907]
Hi I am new to lean and am trying to determine the best way to run a strategy using other periods than the ones defined in the Resolution enum.

I would like to have 5m, 15m, 30m candles and indicators and am curious what the best way to achieve this would be and would like to know if there are any good examples of this type of requirement as I am sure it's something which is a common requirement

**Comment by Martin-Molinero** [comment]
Hey @pomeara! Welcome to Lean,
I think what you are looking for are consolidators, there is a boot camp [available](https://www.quantconnect.com/terminal/#lesson-267/Opening-Range-Breakout). Suggest going through the boot camps first as they cover a range of common requests and tools. At https://github.com/QuantConnect/Lean/tree/master/Algorithm.CSharp (python equivalents are at `/Algorithm.Python`)) we have many example/test algorithms you might wanna take a look at too.
Hope this helps! I'll close this issue for now
