### ISSUE TITLE
Add Property cf.IsETF for CoarseFundamental objects

### ISSUE THREAD

**Issue by ArthurAsenheimer** [QuantConnect/Lean#4920]
#### Expected Behavior
Ability to check if a given CoarseFundamental object is an ETF. 

#### Actual Behavior
We are currently using 
`etfs = [x.Symbol for x in coarse if not x.HasFundamentalData]`
as a workaround. See this [related thread](https://www.quantconnect.com/forum/discussion/9641/how-precisely-can-universe-selector-be).

#### Potential Solution
Implementation of Property **cf.IsETF** to determine if a given CoarseFundamental object is an ETF. 

#### Reproducing the Problem
**N/A**

#### System Information
N/A

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Review security master(?) to determine if an asset is an ETF; and store the information on a row in the coarse fundamental file. As part of the Coarse Fundamental Generator.

**Comment by Martin-Molinero** [comment]
This issue is no longer valid since coarse and fine are now joint in the fundamental type, all properties area available on selection time
