### ISSUE TITLE
Research :  ValueError: cannot reindex from a duplicate axis

### ISSUE THREAD

**Issue by kgoderis** [QuantConnect/Lean#4927]
When running the provided BasicQuantBookTemplate.ipynb example in the research docker, the example stops at

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-2be348dae713> in <module>
      4 
      5 # Gets historical data of indicator
----> 6 bbdf = qb.Indicator(bb, "SPY", 360, Resolution.Daily)
      7 
      8 # drop undesired fields

ValueError: cannot reindex from a duplicate axis
```

#### Expected Behavior

The example notebook functions

#### Actual Behavior

The example notebook has a non-recoverable error

#### Reproducing the Problem

1. Follow instructions for Research docker installation
2. Start above example

#### System Information

MacOS X 10.15.7
Research docker image : ba23f2aa50f9

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [X] I have provided detailed steps to reproduce the issue

**Comment by hsm207** [comment]
Is there a difference between the environment used in the research container and the one used on the web?

Just came across this issue and noticed that the line `bbdf = qb.Indicator(bb, "SPY", 360, Resolution.Daily)` works as expected if run on the web.

**Comment by C-SELLERS** [comment]
No, but because the web IDE has access to QC data storage the issue does not reproduce.

**Comment by hsm207** [comment]
> No, but because the web IDE has access to QC data storage the issue does not reproduce.

@C-SELLERS I'm not sure I understand the reason for the issue not being reproducible in the web.

Are saying that there is an error in the SPY data in the `Data` folder that does not exist in the QC data storage?

**Comment by C-SELLERS** [comment]
Take a look at #4944 which attempted to address this issue.

The bug comes from a sub indicator of the BB being filled forwarded when it runs out of data. But when its filled forwarded the date is the same for those points, and when pandas attempts to place this in a matrix it throws the error about duplicate entries for one index (date)

Locally only the data included in the repo or separately downloaded is available to use. In the cloud it has access to QC's data which is updated daily so there is no need to fill forward.

**Comment by hsm207** [comment]
Thanks @C-SELLERS  for clarifying things!
