### ISSUE TITLE
PolygonDataQueueHandler.cs  not fully implemented

### ISSUE THREAD

**Issue by TightLinesOfCode** [QuantConnect/Lean#4954]
#### Expected Behavior
A standard data model for equity ticks and a supporting architecture that is not vendor specific

#### Actual Behavior
The tick class is not supporting the full SIP standard.

#### Potential Solution
Map a proper data model for equity ticks and bars that maps to SIP.    Determine logic for suspicious ticks so that if this used in the LEAN algorithm it will work for any tickers.

#### Reproducing the Problem
Basic tick creation doesn't have room for the exchange timestamp

#### System Information
C#

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by TightLinesOfCode** [comment]
Also, the conditions mappings and exchange were not fully implemented in the PolygonDataQueueHandler.cs

yield return new Tick(time, request.Symbol, string.Empty, string.Empty, row.BidSize, row.BidPrice, row.AskSize, row.AskPrice);

**Comment by TightLinesOfCode** [comment]
I forked and branch and will be working on this

**Comment by TightLinesOfCode** [comment]
@Martin-Molinero    Martin, can you help me with this one question regarding the sale conditions ?       I need to know if your existing vendor is using multiple sale conditions, or just one.    The other equity data feeds have multiple sale conditions from the SIP Processing.     I need to determine the scope of the code I am going to fix.   I already have all of the Polygon APIs built in a multithreaded, api throttled architecture and am working on adding this to the LEAN code. 

I also have a RocksDB implementation I can add, but I really need to figure out scope

**Comment by jaredbroad** [comment]
Hi @TightLinesOfCode, tick data is not filtered in LEAN. We provided in a raw form and advise only use for experts who know how to interpret those fields themselves. Please implement the Polygon IQDH to not filter any ticks.  

Please remember a nice separation of PRs; if wanting to contribute a RocksDB please make it a separate issue and PR. 

Please also respect the contributing guidelines and templates and create complete fully filled out issues in the future.

**Comment by TightLinesOfCode** [comment]
Well, this is a problem for me, because it seems like your equity vendor is not providing a complete view of the Tick data and there for current architecture is not sufficient.     I am trying to understand what is most helpful as I want to contribute a lot of the backend code to LEAN in a way that makes sense.

Your tick architecture does not support multiple Sale Conditions.  I am concerned as that the equity data you are currently using in the backtesting and want to make sure that I contribute properly to your system.

Can anyone answer the question as to why your data doesn't currently support multiple sale conditions ?

Also, the suspicious flag is not coded in LEAN and its seems like it is data vendor specific.

Please help me figure this out, so that my code can be useful.

**Comment by TightLinesOfCode** [comment]
Jared, thanks for helping.   One other question is do you have a standard data model for equity ticks that needs to be implemented ?    This is probably what causes the challenge.    The Polygon data maps directly to SIP and has SIP timestamps along with exchange timestamps.    This is not currently supported in your data model, so I would want to have an exact data model that data for any equity vendors can follow the same implementation.

All of this raw data, like exchange timestamps and multiple sale conditions needs to flow through the entire architecture, for example, consolidation of bars.

I'm am willing to write all of the code once I have good guidance from you guys.

**Comment by jaredbroad** [comment]
- Datafeed is from SIP
 - Exchange flags are bit flags and support multiple flags.
 - Ticks contain complete information passed through SIP.
