### ISSUE TITLE
API allows F# projects to be created but doesn't allow F# files to be uploaded

### ISSUE THREAD

**Issue by jmerle** [QuantConnect/Lean#4970]
#### Expected Behavior

If F# projects are still supported on quantconnect.com I expect to be able to upload F# files using the REST API. If F# projects are no longer supported I expect the `projects/create` endpoint to respond with an error when trying to create an F# project.

#### Actual Behavior

It's possible to create an F# project using the `projects/create` endpoint, but it's not possible to upload .fs files using the `files/create` endpoint.

#### Potential Solution

N/A

#### Reproducing the Problem

Using the CLI:
```
$ qcli api:post projects/create --body '{ "name": "F# Project", "language": "F#" }'
{
  "projects": [
    {
      "projectId": 6177583,
      "name": "F# Project",
      "created": "2020-11-26 02:34:21",
      "modified": "2020-11-26 02:34:21"
    }
  ],
  "success": true
}

$ qcli api:post files/create --body '{ "projectId": 6177583, "name": "Main.fs", "content": "// F#" }'
{
  "errors": [
    "File extension is not valid."
  ],
  "success": false
}
```

#### System Information

OS: Ubuntu 20.04.1 LTS

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @jmerle!
Thanks for the report, F# projects are currently not supported at quantconnect.com, agree that `projects/create` should fail appropriately 👍

**Comment by aarjaneiro** [comment]
Potentially related, but what of installing FSharp.Core in QuantConnect.Algorithm.CSharp/Python to use F# via DynamicInterOp? .fs files could be called from in such a manner from C#/Python algos.

**Comment by jmerle** [comment]
Closing this issue, the `projects/create` endpoint now responds with a "Language not valid (f#)" error when trying to create an F# project.

**Comment by jmerle** [comment]
Nevermind, just noticed that the behavior is a bit weird. Even though the `projects/create` endpoint returns an error, the project still gets created without any files in it. The same goes for the `files/create` endpoint, it returns an error for the .fs extension, but it does create a file with the given name containing a single hashtag as content. Changing the content is impossible though, the `files/update` endpoint returns a "File extension is not valid." error when you attempt to edit it.
