### ISSUE TITLE
IRegressionAlgorithmDefinition Does Not Contain Expected Status

### ISSUE THREAD

**Issue by C-SELLERS** [QuantConnect/Lean#4977]
#### Expected Behavior

That the `IRegressionAlgorithmDefinition` interface contains a member for its expected status, this way when we create regressions we expect to end with a different status than `complete` we can define it directly in the test algorithm

#### Actual Behavior

Expected algorithm status is only defined in `Tests/RegressionsTests.cs` for any non `complete` regressions.

#### Potential Solution

Expand the interface with a `ExpectedStatus` member.

#### Reproducing the Problem

Reference `Test/RegressionsTests.cs`

#### System Information

N/A

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
- Add `AlgorithmStatus AlgorithmStatus { get; }` to `IRegressionAlgorithmDefinition`
- Update the `RegressionTestMessageHandler` to update the new property expected value like it's doing for the other `IRegressionAlgorithmDefinition` values
- Remove hardcoded status list from https://github.com/QuantConnect/Lean/blob/master/Tests/RegressionTests.cs#L88 use the new value instead
