### ISSUE TITLE
ApiDataProvider downloading non existent data

### ISSUE THREAD

**Issue by C-SELLERS** [QuantConnect/Lean#4994]
#### Expected Behavior

When using ApiDataProvider it will only download data for valid days and for files that actually exist

#### Actual Behavior

ApiDataDownloader will download non-existent data and create a zip for it causing issues with Lean reading the data later.

**Example 1 SPY Second Data:**
![image](https://user-images.githubusercontent.com/41277998/101108787-26581d80-358a-11eb-87f9-eea7fcda44f1.png)

For 2008 1/23 & 2/14 there is no data that exists in the web data repository, yet Lean creates files for them and they are both corrupted. Later when Lean goes to read this in a backtest it throws an error.

**Example 2 ARQL Minute Data:**
![image](https://user-images.githubusercontent.com/41277998/101108866-54d5f880-358a-11eb-956e-2fa25a68a4b4.png)

After 2020 1/15 ARQL is delisted, yet the ApiDataProvider attempts to download past this point and creates a bunch of corrupted files.

#### Potential Solution

Source of the problem is not yet definitive so I do not yet have a potential solution. 

#### Reproducing the Problem

Try either of the examples above by:
1. Get the data on your QuantConnect account
2. Use `ApiDataProvider` in config; also include your Api UserID and Key.
3. Run an Algorithm that would download data for either equity in the example range.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Think this one is a duplicate of https://github.com/QuantConnect/Lean/issues/4556 ?

**Comment by C-SELLERS** [comment]
Whoops, yup! I'll close this guy out.
