### ISSUE TITLE
Support Portfolio Recovery Between Live Algorithm Deployments Using QuantConnect Paper Brokerage

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4996]
#### Expected Behavior
QuantConnect/Lean `PaperBrokerage` gets the current portfolio state (cashbook, positions, orders) like the other paper brokerage implementations that fetch the information from the brokerage.

#### Actual Behavior
When a live deployment is restarted, the portfolio information is lost.

#### Potential Solution
N/A

P.S.: 
- It would also be helpful to fetch Alpha Stream insights that have not been expired if we consider Alpha Stream restarts too.
- When securities are fetched, they are added to the user-defined universe. They should be added to the universe that added them in the first place.

#### Reproducing the Problem
Stop and redeploy a live algorithm with open positions.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
See https://github.com/QuantConnect/Lean/pull/5647 & https://github.com/QuantConnect/Lean/pull/5651

**Comment by Martin-Molinero** [comment]
This is already solved in production 👍
