### ISSUE TITLE
Feature Request: RVI Indicator 

### ISSUE THREAD

**Issue by shilewenuw** [QuantConnect/Lean#4999]
#### Expected Behavior
RVI Indicator implemented
[Relevant Thread](https://www.quantconnect.com/forum/discussion/9953/does-quantconnect-have-a-relative-vigor-index-indicator/p1)

#### Actual Behavior
Not implemented

#### Potential Solution
https://www.investopedia.com/terms/r/relative_vigor_index.asp

#### Checklist

- [x ] I have completely filled out this template
- [x ] I have confirmed that this issue exists on the current `master` branch
- [x ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x ] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/5041
