### ISSUE TITLE
Library Request: IntelLabs' Coach

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5006]
#### Expected Behavior
Supports [IntelLabs' Coach](https://github.com/IntelLabs/coach):
Coach is a python reinforcement learning framework containing the implementation of many state-of-the-art algorithms.

#### Actual Behavior
Does not support this library.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
IntelLabs' Coach is archived & no longer maintained, last release being from 2019, skipping request for now
