### ISSUE TITLE
Quantbook.GetFundamental Accepts Multiple Selectors

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5009]
#### Expected Behavior
Be able to request more than one fundamental property by `GetFundamental` call.

#### Actual Behavior
We can only request one property. If we want multiple properties we need to call this method multiple times and it's inefficient.

#### Potential Solution
N/A

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
Completed by https://github.com/QuantConnect/Lean/pull/5743
