### ISSUE TITLE
FXCM Downloader Connection Problems

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#5010]
#### Expected Behavior

Running
`QuantConnect.ToolBox.exe --app=FxcmDownloader --from-date=20201001-12:00:00 --tickers=EURUSD --resolution=Minute --to-date=20201129-12:00:00`
should execute without error.

#### Actual Behavior

Running
`QuantConnect.ToolBox.exe --app=FxcmDownloader --from-date=20201001-12:00:00 --tickers=EURUSD --resolution=Minute --to-date=20201129-12:00:00`
and using the demo credentials throws
`20201207 16:03:22.552 ERROR:: FxcmDownloaderProgram.FxcmDownloader():  com.fxcm.GenericException: problem on communication request: pdemo41.fxcorporate.com`

#### Potential Solution

N/A

#### Reproducing the Problem

Run 
`QuantConnect.ToolBox.exe --app=FxcmDownloader --from-date=20201001-12:00:00 --tickers=EURUSD --resolution=Minute --to-date=20201129-12:00:00`

#### System Information

Windows 10

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by hn2** [comment]
I have the same problem on linux(ubuntu):

mono QuantConnect.ToolBox.exe --app=FxcmDownloader --from-date=20201001-12:00:00 --tickers=EURUSD --resolution=Minute --to-date=20201129-12:00:00

ERROR:: FxcmDownloaderProgram.FxcmDownloader():  com.fxcm.GenericException: problem on communication request: pdemo41.fxcorporate.com

Doesn't work with Oanda either:
mono QuantConnect.ToolBox.exe --app=OandaDownloader --from-date=20201001-12:00:00 --tickers=EURUSD --resolution=Minute --to-date=20201129-12:00:00

Oanda.RestV20.Client.ApiException: Error calling GetInstrumentCandles: {"errorMessage":"Invalid value specified for 'OANDA-Agent'"}
