### ISSUE TITLE
Custom Securities are not longer configurable due to recent commit

### ISSUE THREAD

**Issue by shilewenuw** [QuantConnect/Lean#5026]
#### Expected Behavior
Custom Securities (Securities created from AddData) should support custom SymbolProperties settings. 

#### Actual Behavior
Custom Securities are no longer configurable

#### Potential Solution
SymbolProperties setter methods were removed in [this commit](https://github.com/QuantConnect/Lean/commit/e98b31fc4c1a1b7c3951f9e94a3448ec701c09b6#diff-870ef5ce8d2c30225b1bc0acbbac25ddf2e4f488a323cecc93b142f28c170792), however, Custom Securities were also affected.

#### Reproducing the Problem
https://www.quantconnect.com/forum/discussion/9955/symbolproperties-error-property-is-read-only/p1

#### System Information
Web QC

#### Checklist

- [ x] I have completely filled out this template
- [ x] I have confirmed that this issue exists on the current `master` branch
- [ x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Update: we will look into adding `SymbolPropertiesDatabase.SenEntry()`, following the pattern of `MarketHoursDatabase.SetEntry()`, which algorithms can call before adding their securities
