### ISSUE TITLE
zero conversion rate for a different than BTCUSDT pair, although both pairs I'm using emit trade ticks the same way

### ISSUE THREAD

**Issue by borseno** [QuantConnect/Lean#5029]
Hey guys I have an issue. I'm doing paper-trading for BitMart (brokerage I implemented) and it's working fine in live and paper for BTCUSDT however it doesn't do so for LTCBTC. The data brokerage sends is the same in terms of correctness (it does call EmitTradeTick in both cases just the same way). 

However I get this exception: 

> Buy | Invalid | ForexConversionRateZero | LTCBTC: requires LTC and BTC to have non-zero conversion rates. This can be caused by lack of data.

I tried to debug through the code and I see that 1) EmitTradeTick are called the same way for both currencies 2) The difference I found was in   ```var updateData = cash.ConversionRateSecurity?.GetLastData();``` call at https://github.com/QuantConnect/Lean/blob/master/Engine/AlgorithmManager.cs#L300, it returned null for LTCBTC. 

Do you guys have any clue what I need to check? See this GetLastData() returned null. Any ideas about why that is possible? EmitTradeTick is called for both currencies.

**Comment by Martin-Molinero** [comment]
Hey! Sorry for the late reply here. We recently added support for multi leg currency resolution and increased the look back period for warming up conversion rates, should do the trick for this issue. On initialize, Lean resolves conversion rate security and sets an initial price using history requests.
Closing this issue for now, let me know if it doesn't solve it, if so we would need some logs and algorithm reproducing the issue
