### ISSUE TITLE
Better error message for FXCM mini-accounts

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#503]
FXCM Mini accounts don't have API access. We can search for this error code and pre-pend a better error message to it.

Failed to initialize algorithm: Error connecting to brokerage: 19915;DAS 19915: ZDas Exception
 ORA-20003: Access denied
ORA-06512: at "U10R3.API", line 440
ORA-06512: at line 1
. This may be caused by incorrect login credentials or an unsupported account type.

**Comment by mchandschuh** [comment]
Looks like an Oracle exception, lol.

**Comment by mchandschuh** [comment]
Looks like it has been reported before:
http://www.dailyfxforum.com/threads/691972-Help-me-Please!

**Comment by jaredbroad** [comment]
Here's a slightly better thread for it: http://fxcodebase.com/code/viewtopic.php?f=37&t=63629

Its because of the account type (mini) which doesn't have API access. There is 1 solution - changing the account to a standard account (which has fees / lower spread / and api access). But it is impossible to know from this error message -- so we should show a better error message when the error contains "Access denied".
