### ISSUE TITLE
History not returning requested number of bars/periods, when trade data is partially unavailable.

### ISSUE THREAD

**Issue by cnaccio** [QuantConnect/Lean#5032]
#### Expected Behavior
My understanding is that when calling History with a constant number of periods/bars, Lean will intelligently handle getting you that exact number of bars by taking into account market hours, so that you can ultimately warm up your indicators, rolling windows, etc...

#### Actual Behavior
However, if for some reason data is unavailable for a period of time, you will not receive the expected number of bars, not even while using the fill forward setting.

#### Reproducing the Problem
See example below that can be ran in the CSharp Research environment. I'm requesting 2520 bars starting from 11/20/2020, and going backwards. However only 1035 bars are returned. When analyzing data for IMMP, you can see that there's no data available for 11/17/2020 which is what's causing this issue. I confirmed via the data explorer (https://www.quantconnect.com/data/tree/equity/usa/minute/i*/immp) and also via other charting packages. For whatever reason, data isn't available for the 17th. 

That said, what I would expect to happen is that data would be filled forward from the last bar available on 11/16/2020 and Lean would return 2520 bars. This is how most charting platforms handle this, and how any indicator would be calculated. 

Code Example (can run in research environment)

```
#load "../QuantConnect.csx"
var qb = new QuantBook();
qb.SetStartDate(2020, 11, 20);
var security = qb.AddEquity("IMMP", Resolution.Minute, Market.USA, fillDataForward: true, leverage: 1, extendedMarketHours: true);
var begin = qb.Time - TimeSpan.FromDays(27);
var end = qb.Time - TimeSpan.FromDays(22);
var history = qb.History(security.Symbol, 2520, Resolution.Minute);
Console.WriteLine($"History: {history.Count()}");
foreach(var bar in history) {
    Console.WriteLine($"[{bar.Time}] {bar}");
}
```

![image](https://user-images.githubusercontent.com/8041783/102137705-dcd8bf80-3e20-11eb-95ee-0fd1821da687.png)

#### Potential Solution
Now in order to do this, I assume Lean would have to reference the actual data within the Time.GetStartTimeForTradeBars method, which could cause a performance hit, but if the FillForward setting is enabled, I think this is how things should work. 

Let me know if you guys think this change/enhancements makes sense/is warranted, and if so we can take a crack at it when we get a chance, assuming it's not something you guys want to handle.

#### System Information
C# algo running on QuantConnect cloud environment running Lean Id: '10011'

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Tricky one. Would prefer not to rely on fill forward and focus on fixing the data issue that made it happen. I think filling forward the gap would also be weird for many people and worse hide the issue
