### ISSUE TITLE
Library Request: stable-baselines3

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5042]
#### Expected Behavior
Supports [stable-baselines3](https://github.com/DLR-RM/stable-baselines3):
Stable Baselines3 is a set of improved implementations of reinforcement learning algorithms in PyTorch. It is the next major version of Stable Baselines.
It works along with stable-baselines with an independent package:
```python
from stable_baselines3 import PPO
```

#### Actual Behavior
Does not support this library.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by vio-codes** [comment]
Any update on this?

**Comment by Magno-M-S-Silva** [comment]
I would also like to use this library please.

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/6558

**Comment by Martin-Molinero** [comment]
Note: it requires using the `Foundation-Tensorforce` environment. Ref https://github.com/QuantConnect/Lean/blob/master/DockerfileLeanFoundation#L221
