### ISSUE TITLE
Reduce Factor File Numerical Precision Warnings

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5044]
#### Expected Behavior
Lean logs the following message:
> "Due to numerical precision issues in the factor file, data from the following symbols has been limited: DRYS, LIVKU"

#### Actual Behavior
The following message is only logged once per security:
> "Data for symbol DRYS has been limited due to numerical precision issues in the factor file. The starting date has been set to 8/11/2016."

This is an improvement (#4742) from previous behavior but still generated too much unnecessary logging.

#### Reproducing the Problem
```csharp
namespace QuantConnect.Algorithm.CSharp {
    public class VentralModulatedEngine : QCAlgorithm {
        public override void Initialize() {
            SetStartDate(2000, 1, 1);
            AddUniverse(coarse => new[]{ "DRYS", "LIVKU" }
            	.Select(x => QuantConnect.Symbol.Create(x, SecurityType.Equity, Market.USA)));
        }
    }
}
```
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by DerekMelchin** [comment]
The error message should also only be logged if the date in the error message (8/11/2016) is **after** the current time in the backtest. Refer [this related thread](https://www.quantconnect.com/forum/discussion/10814/data-for-symbol-has-been-limited-due-to-numerical-precision-issues-in-the-factor-file/p1/comment-30919).
