### ISSUE TITLE
Library Request: ML.Net

### ISSUE THREAD

**Issue by aarjaneiro** [QuantConnect/Lean#5053]
https://www.nuget.org/packages/Microsoft.ML/  
https://github.com/dotnet/machinelearning

Generally seems to have the largest library for time series for C# other than the non-free https://www.extremeoptimization.com/Documentation/Statistics/Time-Series-Analysis/

#### Expected Behavior

Available as an import.
#### Actual Behavior

Not implemented.
#### Potential Solution

Add as nuget package

#### Checklist

- [x ] I have completely filled out this template
- [ x] I have confirmed that this issue exists on the current `master` branch
- [x ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Reopening this issue to ask for additional packages of the ML.Net ecosystem: 
[Microsoft.ML.TimeSeries 1.7.0](https://www.nuget.org/packages/Microsoft.ML.TimeSeries/)
[Microsoft.ML.OnnxRuntime 1.10.0](https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime/)
[Microsoft.ML.FastTree 1.7.0](https://www.nuget.org/packages/Microsoft.ML.FastTree/)
[Microsoft.ML.LightGbm 1.7.0](https://www.nuget.org/packages/Microsoft.ML.LightGbm/)
[Microsoft.ML.Mkl.Components 1.7.0](https://www.nuget.org/packages/Microsoft.ML.Mkl.Components/)
[Microsoft.ML.Ensemble 0.19.0](https://www.nuget.org/packages/Microsoft.ML.Ensemble/)

**Comment by Martin-Molinero** [comment]
The following packages have been added to QC cloud
```"Microsoft.ML.CpuMath" Version="1.7.1"
"Microsoft.ML.DataView" Version="1.7.1"
"Microsoft.ML.Ensemble" Version="0.19.1"
"Microsoft.ML.FastTree" Version="1.7.1"
"Microsoft.ML.LightGbm" Version="1.7.1"
"Microsoft.ML.Mkl.Components" Version="1.7.1"
"Microsoft.ML.OnnxRuntime" Version="1.12.1"
"Microsoft.ML.TensorFlow" Version="1.7.1"
"Microsoft.ML.TimeSeries" Version="1.7.1"
