### ISSUE TITLE
Library Request: modin

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5055]
#### Expected Behavior
Supports [modin](https://github.com/modin-project/modin):
Scale your pandas workflows by changing one line of code

#### Actual Behavior
Does not support this library.

#### Notes
This library would be used for pandas transformation in user code, not replace pandas in Lean `PandasConverter`.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Sharma-Rajat** [comment]
@AlexCatarino I made a PR that was declined as we only update packages in bulk. Where can users see what the FIFO order of packages are? I am more than happy to submit a PR for multiple packages to get modin in.
