### ISSUE TITLE
Add order type & status ID mappings in Python toolbox modules

### ISSUE THREAD

**Issue by aricooperman** [QuantConnect/Lean#5074]
#### Expected Behavior
Be able to have an accurate mapping for missing order related status and type mappings in pure python

#### Potential Solution
Add a new order.py module file that contains these mappings and future order related code

#### Checklist
- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jmerle** [comment]
I don't know exactly what functionality you need, but it may already be available (using `OrderStatus` as example):
- We can use [`Extensions.GetEnumString(OrderStatus.UpdateSubmitted, OrderStatus)`](https://github.com/QuantConnect/Lean/blob/01a13a095af9500b5af7ed38e43de6effd58f015/Common/Extensions.cs#L2163-L2183) and [`Enum.Format(OrderStatus, OrderStatus.UpdateSubmitted, "g")`](https://docs.microsoft.com/en-us/dotnet/api/system.enum.format?view=net-5.0) to convert enum ints to strings.
- We can use [`Enum.GetValues(OrderStatus)`](https://docs.microsoft.com/en-us/dotnet/api/system.enum.getvalues?view=net-5.0) to get the int values of all the constants in an enum.
- We can use [`Enum.GetNames(OrderStatus)`](https://docs.microsoft.com/en-us/dotnet/api/system.enum.getnames?view=net-5.0) to get the string names of all the constants in an enum.

If you need something else, chances are the [`Enum`](https://docs.microsoft.com/en-us/dotnet/api/system.enum?view=net-5.0) class in C# has a method for it.

**Comment by aricooperman** [comment]
I am looking for similar mappings for a pure python (not .net python interpreter) environment to process results data. The PythonToolbox right now is written in such a way that the QA modules can be used outside of a .Net or QC environment.
