### ISSUE TITLE
Brokerage Holdings Respecting Initialize Resolution 

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#5082]
#### Expected Behavior
Brokerage holdings added at the resolution of the data set in the Initialize() method when it exists.

#### Actual Behavior
Assets added at minute resolution default, despite algorithms having other resolutions. 

#### Potential Solution
Override subscriptions or initialize a hypothetical algorithm for added data before using the minute default.  

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Related to https://github.com/QuantConnect/Lean/issues/4473

**Comment by jaredbroad** [comment]
I feel like there's a ResolveResolution() method for redeployments due. Using the universe + initialize method, and showing a warning to the user about the default choice.
