### ISSUE TITLE
InteractiveBrokers MapSymbol Option And Future Failure

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#5083]
#### Expected Behavior

- IB can map option symbols correctly
#### Actual Behavior

```
During the algorithm initialization, the following exception has occurred: Error connecting to brokerage: InteractiveBrokersBrokerage.MapSymbol(): Failed to convert contract for SPY JUN2021 345 P [SPY 210618P00345000 100]; Contract description: OPT SPY JUN2021 345 P [SPY 210618P00345000 100] USD 0 0 0. This may be caused by incorrect login credentials or an unsupported account type.InteractiveBrokersBrokerage.MapSymbol(): Failed to convert contract for SPY JUN2021 345 P [SPY 210618P00345000 100]; Contract description: OPT SPY JUN2021 345 P [SPY 210618P00345000 100] USD 0 0 0 InteractiveBrokersBrokerage.MapSymbol(): Failed to convert contract for SPY JUN2021 345 P [SPY 210618P00345000 100]; Contract description: OPT SPY JUN2021 345 P [SPY 210618P00345000 100] USD 0 0 0 String was not recognized as a valid DateTime.
```
#### Potential Solution

- Reproduce & fix issue
#### Reproducing the Problem

Believe there are 3 paths for a call to `MapSymbol()`: calling `LookupSymbols()`, have an open order or position in the security
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment]
Reopening this issue since we have a new unhandled case with `FUT VIX      MAR2021 (VX) USD   0 0 0`
```
2021-01-19T23:46:25.6738770Z ERROR:: InteractiveBrokersBrokerage.Connect():  System.Exception: InteractiveBrokersBrokerage.MapSymbol(): Failed to convert contract for VIX      MAR2021 (VX); Contract description: FUT VIX      MAR2021 (VX) USD   0 0 0 ---> System.Exception: InteractiveBrokersBrokerage.MapSymbol(): Failed to convert contract for VIX      MAR2021 (VX); Contract description: FUT VIX      MAR2021 (VX) USD   0 0 0 ---> System.FormatException: String was not recognized as a valid DateTime.
```

**Comment by gsalaz98** [comment]
> 
> 
> Reopening this issue since we have a new unhandled case with `FUT VIX MAR2021 (VX) USD 0 0 0`
> 
> ```
> 2021-01-19T23:46:25.6738770Z ERROR:: InteractiveBrokersBrokerage.Connect():  System.Exception: InteractiveBrokersBrokerage.MapSymbol(): Failed to convert contract for VIX      MAR2021 (VX); Contract description: FUT VIX      MAR2021 (VX) USD   0 0 0 ---> System.Exception: InteractiveBrokersBrokerage.MapSymbol(): Failed to convert contract for VIX      MAR2021 (VX); Contract description: FUT VIX      MAR2021 (VX) USD   0 0 0 ---> System.FormatException: String was not recognized as a valid DateTime.
> ```

Unhandled case is passing in latest Lean master. User launched their algorithm (2021-01-04) before the Futures fix made it into master (2021-01-06).
