### ISSUE TITLE
Research notebook keeps on asking for a token

### ISSUE THREAD

**Issue by iukea1** [QuantConnect/Lean#5089]
Hello when I run 

`sudo ./run_docker_notebook.sh 

in the /Lean/Research/run_docker_notebook.sh

I sometimes get prompted for a Juniper access token (80% of the time I do, but 20% of the time I do not which is causing me to scratch my head) 

`![image](https://user-images.githubusercontent.com/35882815/103236130-964b9080-4909-11eb-91c0-d4a6736cd0be.png)

When I view the logs for this container I see 
- 
![image](https://user-images.githubusercontent.com/35882815/103236215-e88cb180-4909-11eb-9640-8a0e89e5eba4.png)

**Comment by C-SELLERS** [comment]
Hey @iukea1 , I am having trouble trying to reproduce this issue. I tried it with both Windows 10 and Ubuntu 20.04

What environment are you running it in? Also for the URL are you using localhost:8888 or the container_id:8888? Any other instances of jupyter running locally?

If you hit "Log in" with the blank box does it work? I mean it shouldn't even request a token but I am curious. Its hardcoded into the dockerfile to have a blank token. 

Any details are appreciated!! That's very strange that it works 1/5th of the time 🤔

**Comment by Martin-Molinero** [comment]
Closing this issue for now until more information is provided
