### ISSUE TITLE
Algorithm Manager Iterates Slice with Same Timestamp After AddOptionContract

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5093]
#### Expected Behavior
The algorithm does not iterate Slice with the same timestamp.

#### Actual Behavior
After adding an `Option` security with `AddOptionContract`, `OnData` is triggered with the same `IAlgorithm.Time`. 

#### Potential Solution
N/A

#### Reproducing the Problem
```csharp
namespace QuantConnect.Algorithm.CSharp {
    public class AddOptionContractAlgorothm : QCAlgorithm {
	private Symbol _symbol;
	private DateTime _lastDatetime = DateTime.MinValue;
		
        public override void Initialize() {
            SetStartDate(2020, 6, 1);
            
            var spy = AddEquity("SPY");
            spy.SetDataNormalizationMode(DataNormalizationMode.Raw);
            _symbol = spy.Symbol;
        }

        public override void OnData(Slice data) {
            if (Time.Ticks - _lastDatetime.Ticks < 1000)
                throw new Exception($"Repeated time: {Time}");
            
            var underlyingPrice = Securities[_symbol].Price;

            var contractSymbol = OptionChainProvider.GetOptionContractList(_symbol, Time)
            	.Where(x => x.ID.StrikePrice - underlyingPrice > 0)
            	.OrderBy(x => x.ID.Date)
		.FirstOrDefault();
            
            if (contractSymbol != null) {
            	var contract = AddOptionContract(contractSymbol);
            	_lastDatetime = Time;
            }
        }
    }
}
```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by C-SELLERS** [comment]
Related PR #4879 and issue #4757

Will have to take a deeper look and try and solve this for all subscriptions.

**Comment by C-SELLERS** [comment]
Findings looking into this issue:
A TimeSlice being sent to OnData() with one extra tick triggers the Expection case in this issue, although this extra tick is caused by #4879, without that tick, it would still trigger two timeslices for the same time. This is because of the contents of the TimeSlice and when their subscriptions are added.

 Two special data cases that trigger the exception:
- OpenInterest data
- Delisted data



Open interest has special behavior in the Subscription
