### ISSUE TITLE
No iNAV Data Source for ETFs

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#5106]
#### Expected Behavior

We have the iNAV property of ETFs.

#### Actual Behavior

We don't have the iNAV property of ETFs.
[Related thread](https://www.quantconnect.com/forum/discussion/9842/shipped-l1-equity-quote-data-instant-universe-selection/p1/comment-28644).

#### Potential Solution

Add the iNAV data source and property.

#### Reproducing the Problem

Try selecting the iNAV of an ETF.

#### System Information

Windows 10. 

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Implemented
