### ISSUE TITLE
Move to DebugPy

### ISSUE THREAD

**Issue by C-SELLERS** [QuantConnect/Lean#5108]
#### Expected Behavior

Using a supported Python debugger for VSCode and VS

#### Actual Behavior

Currently use PTVSD for Python debugging in VSCode and VS which has been deprecated

#### Potential Solution

Migrate to DebugPy

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/6153
