### ISSUE TITLE
Configured Debug Type Mono Not Supported

### ISSUE THREAD

**Issue by gelinger777** [QuantConnect/Lean#5120]
I have had success running lean in docker container with ./run-docker.sh , but in MS Code , when I try to Run in Container I get Configured Type 'mono' not supported. Any ideas how to fix this?

**Comment by aarjaneiro** [comment]
What operating system are you running? I'd first look at https://marketplace.visualstudio.com/items?itemName=ms-vscode.mono-debug and make sure you have mono-complete installed.

**Comment by gelinger777** [comment]
Sorry not to mention it. I am on Ubuntu 20.04 LTS

**Comment by gelinger777** [comment]
Oh, that works now. How to stop running the engine in container? Seems Stop stucks ...

**Comment by gelinger777** [comment]
@aarjaneiro  where I can see the console logs which comes from onData? Because in Docker logs  it is not visible... Sorry if it's a noob question, I am very new to mono...
