### ISSUE TITLE
Library Request: scipy (Explicit Addition)

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5121]
#### Expected Behavior
Upgrades [scipy](https://www.scipy.org/) to version >1.6.0
- SciPy (pronounced “Sigh Pie”) is a Python-based ecosystem of open-source software for mathematics, science, and engineering.

#### Actual Behavior
We do support scipy but we should explicitly add it via pip install, and upgrade to >1.6 to include the following [bug fix](https://github.com/scipy/scipy/pull/13009).

#### Notes
This library would be used for pandas transformation in user code, not replace pandas in Lean `PandasConverter`.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by EmilioFreire** [comment]
Any update on this? The new version is supposed to fix this issue! https://github.com/scipy/scipy/issues/11403

**Comment by ikamanu** [comment]
Following up here as well. Is this an easy add?
