### ISSUE TITLE
Library Request: RLlib

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5140]
#### Expected Behavior
Supports [RLlib](https://docs.ray.io/en/master/rllib.html)
RLlib is an open-source library for reinforcement learning that offers both high scalability and a unified API for a variety of applications. RLlib natively supports TensorFlow, TensorFlow Eager, and PyTorch, but most of its internals are framework agnostic.

#### Actual Behavior
Not supported.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
`"ray[rllib]"==2.0.0             \` is in the current foundation image
