### ISSUE TITLE
Missing early closes for equities USA in MHDB

### ISSUE THREAD

**Issue by Jay-Jay-D** [QuantConnect/Lean#5149]
#### Expected Behavior

All early closes should be in MHDB.

#### Actual Behavior

There are some missing early closes, e.g. 2020-07-03

#### Potential Solution

Update MHDB with missing early closes.

#### Reproducing the Problem

N/A

#### System Information

-

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [ ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

**Comment by klk-** [comment]
Looks like the following early closes are missing:

2008 (https://web.archive.org/web/20080129195253/http://www.nasdaqtrader.com/trader.aspx?id=calendar)
- 2008-12-24
- 2008-07-03

2007
- 2007-07-03 (https://www.wsj.com/articles/SB118346253999056531)
- 2007-12-24 (https://www.wsj.com/articles/SB119850499385048797)

2006
- 2006-07-03 (https://www.wsj.com/articles/SB115192887740696973)

2005
- 2005-11-25 (https://www.wsj.com/articles/SB113293004627706578)

2004
- 2004-11-26 (https://www.wsj.com/articles/SB110147041265884201)

2003
- 2003-07-03 (https://www.wsj.com/articles/SB105726439650704600)
- 2003-11-28 (https://www.wsj.com/articles/SB107002893713412400)
- 2003-12-24 (https://www.wsj.com/articles/SB107227430049424800)
- 2003-12-26 (https://www.wsj.com/articles/SB107244777695004400)

2002
- 2002-07-05 (https://www.wsj.com/articles/SB10258677283004680)
- 2002-11-29 (https://www.wsj.com/articles/SB1038573248238261508)
- 2002-12-24 (https://www.wsj.com/articles/SB1040740116622268993)

2001
- 2001-07-03 (https://www.wsj.com/articles/SB993843765385730626)
- 2001-11-23 (https://www.wsj.com/articles/SB1006524984343604320)

2000
- 2000-07-03 (https://www.wsj.com/articles/SB962641447121293017)
- 2000-11-24 (https://www.wsj.com/articles/SB975075013116392530)

1999
- 1999-11-26 (https://www.wsj.com/articles/SB943626105870252239)

**Comment by klk-** [comment]
@Jay-Jay-D does this change only require editing the JSON file? Or are there unit tests etc. that have to be written too? I'm happy to attempt this if you can provide some guidance

**Comment by Jay-Jay-D** [comment]
@klk- Thank you very very much for your time and effort!

I confirmed all those dates are missing early closes in the Market Hours DB.

Please go ahead and update the [MHDB](https://github.com/QuantConnect/Lean/blob/master/Data/market-hours/market-hours-database.json#L336), and open a PR, I'll review it ASAP.
