### ISSUE TITLE
MortgageRateVolatilityAlpha Algorithm is broken

### ISSUE THREAD

**Issue by C-SELLERS** [QuantConnect/Lean#5151]
#### Expected Behavior

MortgageRateVolatilityAlpha works and is included in the C#/Py Algorithm project.

#### Actual Behavior

MortgageRateVolatilityAlpha is broken and also not included in the C#/Py algorithm project. 

#### Potential Solution

Fix the algorithm and include it in the project.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
`MortgageRateVolatilityAlpha` is currently working as expected, see https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_579a65b863eebf4a934a3629d50e6b94.html
