### ISSUE TITLE
Build Warnings Overload

### ISSUE THREAD

**Issue by C-SELLERS** [QuantConnect/Lean#5155]
#### Expected Behavior

We ignore the warnings that are acceptable in our codebase to reduce build logs and improve visibility into new warnings and errors.

#### Actual Behavior

2000+ warnings in VS build

#### Potential Solution

Decide and then suppress acceptable warnings

Also maybe handle the warnings that are unacceptable.

#### Reproducing the Problem

Build Lean

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by C-SELLERS** [comment]
Closing this issue because of the merges that wiped a lot of the warnings. There will still be some ongoing but they are more difficult and involve some breaking changes.

**Comment by C-SELLERS** [comment]
With the recent upgrade to dotnet 5 framework a lot of new warnings have been generated. It would be great to clear these up so I am going to re-open this issue.

**Comment by Martin-Molinero** [comment]
In master we are currently at 
<img width="368" alt="image" src="https://github.com/QuantConnect/Lean/assets/18473240/55696c6f-2c95-4d6a-8c40-deba97a1d654">

**Comment by Martin-Molinero** [comment]
Still in progress
