### ISSUE TITLE
Delisted event cancels option exercise order

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#5160]
#### Expected Behavior

- Options are exercised correctly
#### Actual Behavior

- Delisted event cancels option exercise order
#### Potential Solution

- OptionExercise order should fill before delisted event get's processed
#### Reproducing the Problem

```
class MyFuturesOptionsAlgorithm(QCAlgorithm):    
    def Initialize(self):
        self.SetStartDate(2012, 1, 1)
        
        self.dc = self.AddFuture("DC", Resolution.Minute, "cme")
        self.dc.SetFilter(timedelta(days=1), timedelta(days=120))
                self.AddFutureOption(self.dc.Symbol, lambda filter: filter.Strikes(-2, 2))
    
    def OnData(self, data: Slice):    
        if len(data.OptionChains) == 0 or self.Portfolio.Invested:
            return
    
        futuresOptionsContracts = [contract for chain in data.OptionChains.Values for contract in chain.Contracts.Values]
        
        for futureOptionContract in futuresOptionsContracts:
            self.MarketOrder(futureOptionContract.Symbol, 1)
```
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment]
#5169 set the expiry time to the first bar of the expiry date preventing trades during the expiry day that are allowed in reality. The expiry time should be at the market closing or a few minutes before.
