### ISSUE TITLE
Remove VB and F# Projects

### ISSUE THREAD

**Issue by C-SELLERS** [QuantConnect/Lean#5161]
#### Expected Behavior

Since we no longer support VB and F#, we should remove the projects from the code base.

#### Actual Behavior

N/A

#### Potential Solution

Remove the projects

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by alexander-myltsev** [comment]
@C-SELLERS please clarify, would you accept a PR in F# that integrates yet another broker?
