### ISSUE TITLE
[Feature Request] Autocomplete/Intellisense in Web QC Research Notebooks

### ISSUE THREAD

**Issue by shilewenuw** [QuantConnect/Lean#5170]
#### Expected Behavior
Autocomplete/Intellisense in Research notebooks for Web QC. [Relevant thread](https://www.quantconnect.com/forum/discussion/10364/autocomplete-intellisense-for-python-research-notebooks/p1)

#### Actual Behavior
No autocomplete/intellisense

#### Checklist

- [x ] I have completely filled out this template
- [x ] I have confirmed that this issue exists on the current `master` branch
- [x ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x ] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
This is now available in the new code environment 👍
