### ISSUE TITLE
Alpaca Live Data w/ Polygon

### ISSUE THREAD

**Issue by C-SELLERS** [QuantConnect/Lean#5175]
#### Expected Behavior

When using "live-alpaca" mode, the polygon data queue handler will connect to polygon through the alpaca socket and stream data.

#### Actual Behavior

Using "live-alpaca" mode the polygon data queue handler connects to polygons base wss socket, which fails to authenticate with alpaca key.

#### Potential Solution

If configuration mode is set to "live-alpaca" use the alpaca-polygon wss url ("wss://alpaca.socket.polygon.io") instead of polygon wss url "wss://socket.polygon.io"

Also if mode is "live-alpaca" use "alpaca-api-key" for authentication. 

#### Reproducing the Problem

Try and run an algorithm in "live-alpaca" mode.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closing since alpaca has been removed https://github.com/QuantConnect/Lean/pull/5249
