### ISSUE TITLE
Feature - Add Docker configurations for usage outside of Launcher

### ISSUE THREAD

**Issue by aarjaneiro** [QuantConnect/Lean#5197]
#### Expected Behavior

Ability to either mount subdirectories or copy files/directories to the container for development. Such would allow one easily bypass common issues due to PythonNet and other machine-specific issues which do not exist in the standard environment. Moreover file-copying allows manipulation of files in the container without changing them locally. 
#### Actual Behavior

Current configuration copies files -> runs algo -> disposes. 
#### Potential Solution

Extend run_docker.sh

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closing for now, see https://github.com/QuantConnect/Lean/pull/5198#issuecomment-771270684
