### ISSUE TITLE
Universe Removals Not Working Properly

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#5215]
#### Expected Behavior

Universe additions and removes work as expected.

#### Actual Behavior

The backtest in [this thread](https://www.quantconnect.com/forum/discussion/10423/scheduleduniverseselectionmodel-inconsistently-adding-and-removing-securities/p1) shows the universe removal process isn't working as expected.

#### Potential Solution

Unknown. It seems related to [this merged PR](https://github.com/QuantConnect/Lean/pull/5134).

#### Reproducing the Problem

Run the backtest in [this thread](https://www.quantconnect.com/forum/discussion/10423/scheduleduniverseselectionmodel-inconsistently-adding-and-removing-securities/p1).

#### System Information

QC Cloud. Windows 10.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Believe this is the `UniverseSettings.MinimumTimeInUniverse` effect, setting it to `TimeSpan.Zero` solves the misbehavior. Will close when the user confirms the fix.
