### ISSUE TITLE
[Feature Request] IBKR Custom Order types

### ISSUE THREAD

**Issue by shilewenuw** [QuantConnect/Lean#5219]
#### Expected Behavior
Support for IBKR custom order types, e.g. Bracket and Trailing Stop order types. [Relevant Thread](https://www.quantconnect.com/forum/discussion/10444/ibkr-custom-api-calls/p1)

#### Actual Behavior
Not supported

#### Checklist

- [x ] I have completely filled out this template
- [x ] I have confirmed that this issue exists on the current `master` branch
- [x ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x ] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Closing this one as not specific enough. @AlexCatarino please break into specific dedicated issues for the popular currently unsupported order types.

**Comment by AlexCatarino** [comment]
New Issues for **popular** and unsupported: #2580 #7133 #7134 #7135 #7136 
Interactive Brokers supports the orders listed on the following page:
https://interactivebrokers.github.io/tws-api/basic_orders.html
