### ISSUE TITLE
Volume is not adjusted for splits

### ISSUE THREAD

**Issue by SimDoes** [QuantConnect/Lean#5221]
#### Expected Behavior

Volume should be adjusted for splits when using `DataNormalizationMode.SplitAdjusted`

#### Actual Behavior

Volume is not adjusted for splits.

#### Potential Solution

Dividing volume by PriceScaleFactor of that day seems to fix the volume.
For e.g. PriceScaleFactor of TSLA before the split was 0.2 and 19M / 0.2 yields 95M which is the correct volume. This should work for reverse splits as well.

#### Reproducing the Problem

Run the backtest [here](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_fd2bac140c77e4d7704beccb2bf58f3c.html)

Reverse split example [here](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_b51631c3e9c003fda8ec983f6f1a5fb8.html)

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
![image](https://user-images.githubusercontent.com/2243225/106066843-561b3180-60b2-11eb-975c-b3fb66ddfa48.png)
Thanks @SimDoes I think you're right. We'll post a fix ASAP.

**Comment by bendressner** [comment]
Still hitting this issue today (Mar 24, 2021)
