### ISSUE TITLE
Off by one in BuyingPowerModel.GetMaximumOrderQuantityForTargetBuyingPower

### ISSUE THREAD

**Issue by mchandschuh** [QuantConnect/Lean#5228]
#### Expected Behavior

Calling `security.BuyingPowerModel.GetInitialMarginRequiredForOrder` using the results of `security.GetMaximumOrderQuantityForTargetBuyingPower` should not exceed the provided target buying power.

#### Actual Behavior

The initial margin required for order can exceed the target buying power in cases of constant fees, leading to an off by one error. The error in computed quantity increases according to the ratio of the stock's share price and the constant fee, so if the fee is 100x the stock's share price, then we'll end up off by 100 shares.

#### Potential Solution

Update the `GetMaximumOrderQuantityForTargetBuyingPower` implementation to properly account for fees. This will be done by effectively rewriting the implementation according to the new `SecurityPositionGroupBuyingPowerModel`'s implementation which was reformulated from the ground up based on the initial implementation going back many years, with two specific modification, to remove the fees from the total margin per share as well as defining minimum and maximum targets. The current implementation aims to produce a high estimate and walk it down until it's within range. This approach requires at least two full loops, whereas the new implementation can solve the problem with no looping when fees are strictly proportional with order value, such as in crypto trading where fees are a percentage of total order value.

#### Reproducing the Problem

I'll add some new unit tests to address this issue directly, but if you run any of the following tests and use the results of `GetMaximumOrderQuantityForTargetBuyingPower` to compute `GetInitialMarginRequiredForOrder`, you'll observe that the initial margin required exceeds the requested target buying power.

These tests, aimed at generating margin call orders, are the easiest ones to view the errant behavior:
``` text
PatternDayTradingMarginBuyingPowerModelTests:
  VerifyMarginCallOrderLongClosedMarket
  VerifyMarginCallOrderLongOpenMarket
  VerifyMarginCallOrderShortClosedMarket
  VerifyMarginCallOrderShortOpenMarket

```

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by IlshatGaripov** [comment]
Hi @mchandschuh I also have noticed this bug couple years ago, I think GetMaximumOrderQuantityForTargetBuyingPower in CashBuyingPowerModel  keeps count correctly though.  I had a closer look on these two methods when implemented custom portfolio construction model for a basket of stocks. And helper methods as:
1) GetMinQuantityToReleaseTargetMarginValue - determines minimum number of shares to buy/sell to release required margin
2) GetMaxQuantityForTargetMarginValue - determines max number of shares can buy for available margin , including fees..

**Comment by Martin-Molinero** [comment]
Closing for now since we doubled checked this isn't a bug. Some notes by @mchandschuh:

> The get max quantity algorithm searches for an order quantity that when executed, yields the requested percentage of holdings in the particular security (or group). This means that the reference point for the percentage is **after** the order executes. The implication of this is needing to deduct order fees from TPV before applying any scale factors (such as RequiredFreeBuyingPower and parameters.TargetBuyingPower). If fees were scaled along with order margin, then the resulting holdings would be the requested target percent of what TPV used to be, i.e, currently is at the time get max quantity runs.

> CashBuyingPowerModel doesn't handle fees the same way as BuyingPowerModel
