### ISSUE TITLE
SubscriptionDataReader finishes too early in certain cases involving symbol mapping and sub-daily resolution

### ISSUE THREAD

**Issue by klk-** [QuantConnect/Lean#5232]
#### Expected Behavior
SubscriptionDataReader (and by extension History requests and backtests) provides all data for a symbol for the requested time range, even with symbol mapping events.

#### Actual Behavior
SubscriptionDataReader MoveNext() returns false too early in certain case (see reproduce steps)

#### Potential Solution
In SubscriptionDataReader.MoveNext(), move the following check to after the call to `UpdateDataEnumerator`.  This way, if the next instance in current source is beyond data range, we will first try to use a new source that respects the updated mapping before exiting (see reproduce steps).
```
if (instance.Time > _periodFinish)
{
    // stop reading when we get a value after the end
    _endOfStream = true;
    return false;
}
```

#### Reproducing the Problem
General case:
On date d, there is a change for symbol s from ticker t1 -> t2

t1.csv data looks like this (omitted hourly entries for brevity).
```
d-1 trade bar
d trade bar
d + 1000 trade bar
```
Basically there is a symbol change back to t1 at some point in the future

Then, a history request or backtest that ends between [d+1, d+1000] will only see data up until date d.

Example reproduction (it is easy to find more examples following pattern above e.g. AAIC, AAXN, PLUG)

```
from datetime import datetime

qb = QuantBook()
qb.AddEquity("SPWR", Resolution.Hour, "usa", False)
df = qb.History(qb.Securities.Keys, datetime(2008,9,1), datetime(2008,12,31), Resolution.Hour)
print(df)
```

This doesn't happen at daily resolution because every data point is a new day and therefore results in a call to UpdateDataEnumerator(), so on the final data point for the new symbol, the enumerator gets switched to the file for new mapping.

#### System Information
N/A

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Thanks, nice catch @klk-! We will look into ASAP
