### ISSUE TITLE
[Live] - Holdings avg. price vs. current price can be mismatched depending on data feed

### ISSUE THREAD

**Issue by gsalaz98** [QuantConnect/Lean#5238]
#### Expected Behavior

The holdings acquired price remains at the same scale as the current price
#### Actual Behavior

Sometimes, when switching between Interactive Brokers and QC data feed (using IB as the brokerage), the scales changes for holdings vs. current price:

![image](https://user-images.githubusercontent.com/25196864/106200181-74913380-616b-11eb-9b74-62cd61e0066a.png)

^^^ Might only apply to ZC futures

![image](https://user-images.githubusercontent.com/25196864/106200278-95598900-616b-11eb-83b1-1d74c31f0714.png)

Another related finding. This Futures Options' contract's holdings value is off the charts, but might be real because of contract multiplier -- might be a different issue altogether.
#### Potential Solution

N/A
#### Reproducing the Problem

Unsure if this will 100% replicate, but place an order in the QC data feed (using IB as brokerage) for ZC contracts. Then, switch to IB data feed and compare the prices the contracts were bought at vs. current holdings
#### System Information

N/A, cloud
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by spdjudd** [comment]
I think this might relate to the ContractDetails.PriceMagnifier field in IB - for ZC and several other futures this is set to 100 as the prices are quoted in **cents** rather than dollars on the exchange.  

From what I can see InteractiveBrokersBrokerage passes through prices for ticks and order fills in cents, and expects to receive limit orders etc with the cent price.  (Current holdings are given a dollar price at startup though.)

So, a potential fix would be to fetch the ContractDetails for each symbol subscribed to (at least for futures, don't know if this field is used for other contracts), and adjust prices coming in and out, consistent with the fix for #5297.

Not sure what your plans are for this, but happy to help if I can?

**Comment by Martin-Molinero** [comment]
Hey @spdjudd! 

> happy to help if I can

Sounds great, ty! I think the first step here is to have some repeatable steps for the reproduction of the issue to determine and assert what are the parts affected too, which will determine the scope of the fix (adjust holdings/orders/etc) 👍 do you mind going through this?

> So, a potential fix would be to fetch the ContractDetails for each symbol subscribed to (at least for futures, don't know if this field is used for other contracts), and adjust prices coming in and out, consistent with the fix for #5297.

yes, believe the brokerage already has a cache of `_contractDetails` and a method to request it if not present

**Comment by spdjudd** [comment]
Sure, I'll go through it next week and provide steps

**Comment by Martin-Molinero** [comment]
Awesome @spdjudd 💯 

> So when InteractiveBrokersBrokerage downloads the current holdings at startup the price is given correctly in USD, giving a correct holdings cost of $26.2k. All other interactions - Trade/QuoteBars, OrderEvents etc pass through the cent price as USD, meaning HoldingsCost for a position that was opened in the current session is 100x too big (shown as $2.62M above). Limit orders are clearly assuming the provided limit price is in cents.

Sounds good 👍.  Posting a potential solution bellow to be called on each use case normalizing into Lean (dollars) or IB (cents) expected prices

```csharp
/// <summary>
/// Helper method to normalize a provided price to the Lean expected unit
/// </summary>
private decimal NormalizePriceToLean(decimal price, Contract contract, Symbol symbol)
{
    // which other security type should be normalized: FOPs?
    if (symbol.SecurityType == SecurityType.Future)
    {
        return price / GetContractPriceMagnifier(contract, symbol);
    }
    return price;
}

/// <summary>
/// Helper method to normalize a provided price to the brokerage expected unit, for example cents
/// </summary>
private decimal NormalizePriceToBrokerage(decimal price, Contract contract, Symbol symbol)
{
    // which other security type should be normalized: FOPs?
    if (symbol.SecurityType == SecurityType.Future)
    {
        return price * GetContractPriceMagnifier(contract, symbol);
    }
    return price;
}

/// <summary>
/// Will return the price magnifier for the requested symbol
/// </summary>
private decimal GetContractPriceMagnifier(Contract contract, Symbol symbol)
{
    var uniqueKey = GetUniqueKey(contract);
    if (!_contractDetails.TryGetValue(uniqueKey, out var contractDetails))
    {
        contractDetails = GetContractDetails(contract, symbol);
        if (contractDetails == null)
        {
            Log.Error("");
            return 1;
        }
    }
    return contractDetails.PriceMagnifier;
}
```

**Comment by spdjudd** [comment]
Looks good!

There are a couple of other changes required to have the contract and symbol available at the point each conversion needs to happen, specifically in `HandleCommissionReport()`/`HandleExecutionDetails()` for generating order fills, `ConvertTradeBar()` in the history query and `HandleTickPrice()`.  

I've tested the version attached here and it successfully addresses all the issues from my previous test: 
[InteractiveBrokersBrokerage.cs.txt](https://github.com/QuantConnect/Lean/files/7171299/InteractiveBrokersBrokerage.cs.txt)

Haven't been able to test the history query as I don't have a working market data subscription for IB right now (only delayed data)

**Comment by Martin-Molinero** [comment]
Hey @spdjudd!

> I've tested the version attached here and it successfully addresses all the issues from my previous test:

Nice! do you mind going ahead opening the PR with the current changes 👌 + any `// TODO comments` so we can tackle/review it from there?

**Comment by spdjudd** [comment]
Sure - I've opened #5930 but will need a bit more time to sort out testing.  I've run tests using algos as described above, and existing unit tests pass, except for the History request ones that I can't run because I don't have IB market data.  There are also a couple of tests that restart the IB connection that are failing, but that seems to be because of a difference with the newest IB Gateway rather than my changes.
