### ISSUE TITLE
Cannot import auto_arima from pyramid.arima

### ISSUE THREAD

**Issue by iotaweb** [QuantConnect/Lean#5240]
#### Expected Behavior
The following import statement should work without error:

`from pyramid.arima import auto_arima`

#### Actual Behavior

Error on import:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-4e35d3e40b01> in <module>
----> 1 from pyramid.arima import auto_arima

/opt/miniconda3/lib/python3.6/site-packages/pyramid/__init__.py in <module>
     27 
     28     # Stuff we want at top-level
---> 29     from .arima import auto_arima, ARIMA
     30     from .utils import acf, autocorr_plot, c, pacf, plot_acf, plot_pacf
     31 

/opt/miniconda3/lib/python3.6/site-packages/pyramid/arima/__init__.py in <module>
      3 # Author: Taylor Smith <taylor.smith@alkaline-ml.com>
      4 
----> 5 from .approx import *
      6 from .arima import *
      7 from .auto import *

/opt/miniconda3/lib/python3.6/site-packages/pyramid/arima/approx.py in <module>
      9 import numpy as np
     10 
---> 11 from ..utils.array import c
     12 from ..utils import get_callable
     13 from ..compat.numpy import DTYPE

/opt/miniconda3/lib/python3.6/site-packages/pyramid/utils/__init__.py in <module>
      3 # Author: Taylor Smith <taylor.smith@alkaline-ml.com>
      4 
----> 5 from .array import *
      6 from .metaestimators import *
      7 from .testing import *

/opt/miniconda3/lib/python3.6/site-packages/pyramid/utils/array.py in <module>
      8 
      9 from sklearn.utils.validation import check_array, column_or_1d
---> 10 from sklearn.externals import six
     11 
     12 import numpy as np

ImportError: cannot import name 'six'
```

#### Potential Solution

The `pyramid-arima` library has been superseded by `pmdarima`. Active maintenance of `pyramid-arima` ceased on 3 Nov 2018 but has been continued by the same author in `pmdarima` and continues to receive regular updates. `pyramid-arima` is considered legacy and is not recommended.

Propose that `pyramid-arima` be replaced by `pmdarima`.

https://pypi.org/project/pmdarima/

#### Reproducing the Problem

Problem was encountered in Research notebook using the statement:

`from pyramid.arima import auto_arima`

#### System Information
Error encountered on QuantConnect hosted notebook (presumably using `master` branch of Lean). Chrome browser.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Working correctly, solved by https://github.com/QuantConnect/Lean/pull/6558. Note it has been renamed to `pmdarima`
![image](https://user-images.githubusercontent.com/18473240/186528507-944ba5af-f088-46b6-98c9-32bd0035daab.png)
