### ISSUE TITLE
Library request: PyJulia

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5260]
#### Expected Behavior
Supports [PyJulia](https://pyjulia.readthedocs.io/en/latest/)
We will need to install [Julia](https://pyjulia.readthedocs.io/en/latest/installation.html#step-1-install-julia) too.

#### Actual Behavior
Not supported.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Will not add to the foundation due to the overhead it brings, creating an issue to add a tutorial for the lean cli https://github.com/QuantConnect/Documentation/issues/1160
