### ISSUE TITLE
Feature - Rolling Sharpe Ratio Indicator

### ISSUE THREAD

**Issue by aarjaneiro** [QuantConnect/Lean#5269]
The Sharpe Ratio (SR) measures the relative expected return of a portfolio relative to its risk.
That is, SR = (E(R) − r)/ σ where R is the portfolio's return, E denotes expectation, r is the risk-free rate, and σ is the standard deviation (risk) of the returns. This indicator in particular calculates the SR over
a rolling window of data and is thus referred to as a "Rolling Sharpe Ratio" (RSR).

#### Expected Behavior

An indicator for Sharpe Ratio should be included.
#### Actual Behavior

One is not.
#### Potential Solution

Add a Rolling Sharpe Ratio (RSR) indicator
#### Checklist

- [ x] I have completely filled out this template
- [ x] I have confirmed that this issue exists on the current `master` branch
- [ x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/5348
