### ISSUE TITLE
Backtest data from Fxcm

### ISSUE THREAD

**Issue by benjaminthedonkey** [QuantConnect/Lean#529]
In backtest mode the system  looks for historical data into  ..Data/Forex/Fxcm/  folder. How I  change it to use another broker?.   Thanks.

**Comment by jaredbroad** [comment]
We break data into markets; e.g. you can have AAPL stock in the Mexican and the US exchanges as two separate tradable contracts. This is even more apparent with FX brokerages who often are market makers themselves and have their own contract pricing.

This is controlled in the Market.X enum; you specify which market you'd like when you AddForex("EURUSD", Resolution.Minute, Market.Oanda / Market.Fxcm); You could add your own brokerage and add an entry to the market enum here.

If you add a new brokerage implementation please submit it as a PR!

PS: We provide all the FXCM and Oanda data for download via our data library on quantconnect.com/data.
