### ISSUE TITLE
Unable to link LEAN with fxcm

### ISSUE THREAD

**Issue by hn2** [QuantConnect/Lean#5292]
For a few days now, I am unable to link LEAN with fxcm. It was working until about a week ago.

**Comment by Martin-Molinero** [comment]
Hey @hn2, just sanity tested it and it's working correctly for me in QC cloud. Mind providing more details?

**Comment by hn2** [comment]
20210211 23:30:02.366 Trace:: Config.GetValue(): debug-mode - Using default value: False
20210211 23:30:02.371 Trace:: Config.Get(): Configuration key not found. Key: results-destination-folder - Using default value:
20210211 23:30:02.372 Trace:: Config.Get(): Configuration key not found. Key: plugin-directory - Using default value:
20210211 23:30:02.373 Trace:: Config.Get(): Configuration key not found. Key: composer-dll-directory - Using default value: C:\QuantConnect\trade-fxcm-d1\
20210211 23:30:02.477 Trace:: Config.Get(): Configuration key not found. Key: data-directory - Using default value: ../../../Data/
20210211 23:30:02.478 Trace:: Config.Get(): Configuration key not found. Key: version-id - Using default value:
20210211 23:30:02.478 Trace:: Config.Get(): Configuration key not found. Key: cache-location - Using default value: ../Data/
20210211 23:30:02.478 Trace:: Python for .NET Assembly: Python.Runtime, Version=1.0.5.30, Culture=neutral, PublicKeyToken=null
20210211 23:30:02.478 Trace:: Engine.Main(): LEAN ALGORITHMIC TRADING ENGINE v2.4.0.0 Mode: DEBUG (64bit)
20210211 23:30:02.479 Trace:: Engine.Main(): Started 11:30 PM
20210211 23:30:02.480 Trace:: Config.GetValue(): job-project-id - Using default value: 0
20210211 23:30:02.481 Trace:: Config.GetValue(): regression-update-statistics - Using default value: False
20210211 23:30:02.481 Trace:: Config.Get(): Configuration key not found. Key: lean-manager-type - Using default value: LocalLeanManager
20210211 23:30:02.483 Trace:: Config.Get(): Configuration key not found. Key: cloud-api-url - Using default value: https://www.quantconnect.com/api/v2/
20210211 23:30:02.496 Trace:: JobQueue.NextJob(): Selected ../my-algos/drl-forex/trade-fxcm-d1.py
20210211 23:30:02.511 Trace:: Python for .NET Assembly: nPython, Version=1.0.5.30, Culture=neutral, PublicKeyToken=null
20210211 23:30:02.582 Trace:: Config.GetValue(): scheduled-event-leaky-bucket-capacity - Using default value: 120
20210211 23:30:02.583 Trace:: Config.GetValue(): scheduled-event-leaky-bucket-refill-amount - Using default value: 18
20210211 23:30:02.583 Trace:: Config.GetValue(): scheduled-event-leaky-bucket-time-interval-minutes - Using default value: 1440
20210211 23:30:02.585 Trace:: Config.Get(): Configuration key not found. Key: algorithm-id - Using default value: trade-fxcm-d1
20210211 23:30:02.585 Trace:: Config.GetValue(): scheduled-event-leaky-bucket-capacity - Using default value: 120
20210211 23:30:02.586 Trace:: Config.GetValue(): scheduled-event-leaky-bucket-refill-amount - Using default value: 18
20210211 23:30:02.586 Trace:: Config.GetValue(): scheduled-event-leaky-bucket-time-interval-minutes - Using default value: 1440
20210211 23:30:05.324 Trace:: Config.Get(): Configuration key not found. Key: data-permission-manager - Using default value: DataPermissionManager
20210211 23:30:05.325 Trace:: Config.Get(): Configuration key not found. Key: results-destination-folder - Using default value: C:\QuantConnect\trade-fxcm-d1
20210211 23:30:05.326 Trace:: Config.GetValue(): streamed-chart-limit - Using default value: 12
20210211 23:30:05.326 Trace:: Config.GetValue(): streamed-chart-group-size - Using default value: 3
20210211 23:30:05.330 Trace:: Config.Get(): Configuration key not found. Key: object-store-root - Using default value: ./storage
20210211 23:30:05.331 Trace:: Config.GetValue(): ignore-version-checks - Using default value: False
20210211 23:30:05.332 Trace:: AlgorithmManager.CreateTokenBucket(): Initializing LeakyBucket: Capacity: 120 RefillAmount: 18 TimeInterval: 1440
20210211 23:30:05.334 Trace:: Config.GetValue(): algorithm-manager-time-loop-maximum - Using default value: 20
20210211 23:30:05.341 Trace:: Config.GetValue(): consumer-batching-timeout-ms - Using default value: 0
20210211 23:30:05.596 Trace:: PythonInitializer.Initialize(): start...
PythonEngine.Initialize(): Runtime.Initialize()...
Runtime.Initialize(): Py_Initialize...
Runtime.Initialize(): PyEval_InitThreads...
Runtime.Initialize(): Initialize types...
Runtime.Initialize(): Initialize types end.
Runtime.Initialize(): AssemblyManager.Initialize()...
Runtime.Initialize(): AssemblyManager.UpdatePath()...
PythonEngine.Initialize(): register atexit callback...
PythonEngine.Initialize(): GetCLRModule()...
PythonEngine.Initialize(): clr GetManifestResourceStream...
20210211 23:30:05.856 Trace:: PythonInitializer.Initialize(): ended
20210211 23:30:05.859 Trace:: AlgorithmPythonWrapper(): Python version 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]: Importing python module trade-fxcm-d1
20210211 23:30:07.673 Trace:: AlgorithmPythonWrapper(): Creating IAlgorithm instance.
20210211 23:30:07.727 Trace:: Config.GetValue(): mute-python-library-logging - Using default value: True
20210211 23:30:07.774 Trace:: Config.Get(): Configuration key not found. Key: results-destination-folder - Using default value: C:\QuantConnect\trade-fxcm-d1
20210211 23:30:07.775 Trace:: LocalObjectStore.Initialize(): Storage Root: C:\QuantConnect\trade-fxcm-d1\storage\QCAlgorithm
20210211 23:30:07.776 Trace:: LiveTradingDataFeed.GetDataChannelProvider(): will use DataChannelProvider
20210211 23:30:07.781 Trace:: Config.Get(): Configuration key not found. Key: data-aggregator - Using default value: QuantConnect.Lean.Engine.DataFeeds.AggregationManager
20210211 23:30:07.802 Trace:: LiveTradingDataFeed.GetDataQueueHandler(): will use FxcmBrokerage
20210211 23:30:07.803 Trace:: BaseDataExchange(CustomDataExchange) Starting...
20210211 23:30:07.806 Trace:: FxcmBrokerage.Connect()
log4j:WARN No appenders could be found for logger (com.fxcm.messaging.ConnectionManagerEx).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
20210211 23:30:08.507 ERROR:: LiveTradingResultHandler.Update(): Algorithm not yet initialized.
20210211 23:30:18.583 Trace:: LiveTradingResultHandler.SendStatusUpdate(): status: 'LoggingIn'.  Logging into brokerage...
20210211 23:30:18.584 Trace:: BrokerageSetupHandler.Setup(): Connecting to brokerage...
20210211 23:30:18.584 Trace:: BrokerageSetupHandler.Setup(): FXCM Brokerage account base currency: USD
20210211 23:30:18.584 Trace:: BrokerageSetupHandler.Setup(): Initializing algorithm...
20210211 23:30:18.584 Trace:: LiveTradingResultHandler.SendStatusUpdate(): status: 'Initializing'.  Initializing algorithm...
20210211 23:30:18.587 Trace:: Config.Get(): Configuration key not found. Key: security-data-feeds - Using default value:
20210211 23:31:18.642 Trace:: Isolator.ExecuteWithTimeLimit(): Used: 66, Sample: 72, App: 3634, CurrentTimeStepElapsed: 00:00.000
20210211 23:32:18.682 Trace:: Isolator.ExecuteWithTimeLimit(): Used: 88, Sample: 71, App: 3634, CurrentTimeStepElapsed: 00:00.000
20210211 23:33:18.695 Trace:: Isolator.ExecuteWithTimeLimit(): Used: 95, Sample: 113, App: 3658, CurrentTimeStepElapsed: 00:00.000
20210211 23:34:18.758 Trace:: Isolator.ExecuteWithTimeLimit(): Used: 103, Sample: 118, App: 3673, CurrentTimeStepElapsed: 00:00.000
20210211 23:35:18.619 Trace:: Isolator.ExecuteWithTimeLimit(): Execution Security Error: Operation timed out - 5 minutes max. Check for recursive loops.
20210211 23:35:18.623 ERROR:: Security.ExecuteWithTimeLimit(): Execution Security Error: Operation timed out - 5 minutes max. Check for recursive loops.
20210211 23:35:18.665 ERROR:: Engine.Run(): During the algorithm initialization, the following exception has occurred: System.TimeoutException: Execution Security Error: Operation timed out - 5 minutes max. Check for recursive loops.
   at QuantConnect.Isolator.MonitorTask(Task task, TimeSpan timeSpan, Func`1 withinCustomLimits, Int64 memoryCap, Int32 sleepIntervalMillis) in C:\Users\hanna\Source\Repos\Lean\Common\Isolator.cs:line 186
   at QuantConnect.Isolator.ExecuteWithTimeLimit(TimeSpan timeSpan, Func`1 withinCustomLimits, Action codeBlock, Int64 memoryCap, Int32 sleepIntervalMillis, WorkerThread workerThread) in C:\Users\hanna\Source\Repos\Lean\Common\Isolator.cs:line 95
   at QuantConnect.Isolator.ExecuteWithTimeLimit(TimeSpan timeSpan, Action codeBlock, Int64 memoryCap, Int32 sleepIntervalMillis, WorkerThread workerThread) in C:\Users\hanna\Source\Repos\Lean\Common\Isolator.cs:line 201
   at QuantConnect.Lean.Engine.Setup.BrokerageSetupHandler.Setup(SetupHandlerParameters parameters) in C:\Users\hanna\Source\Repos\Lean\Engine\Setup\BrokerageSetupHandler.cs:line 216Execution Security Error: Operation timed out - 5 minutes max. Check for recursive loops.
20210211 23:35:18.666 Trace:: JOB HANDLERS:
20210211 23:35:18.666 Trace::          DataFeed:     QuantConnect.Lean.Engine.DataFeeds.LiveTradingDataFeed
20210211 23:35:18.666 Trace::          Setup:        QuantConnect.Lean.Engine.Setup.BrokerageSetupHandler
20210211 23:35:18.666 Trace::          RealTime:     QuantConnect.Lean.Engine.RealTime.LiveTradingRealTimeHandler
20210211 23:35:18.667 Trace::          Results:      QuantConnect.Lean.Engine.Results.LiveTradingResultHandler
20210211 23:35:18.667 Trace::          Transactions: QuantConnect.Lean.Engine.TransactionHandlers.BrokerageTransactionHandler
20210211 23:35:18.667 Trace::          Alpha:        QuantConnect.Lean.Engine.Alphas.DefaultAlphaHandler
20210211 23:35:18.667 Trace::          ObjectStore:  QuantConnect.Lean.Engine.Storage.LocalObjectStore
20210211 23:35:18.667 Trace::          History Provider:     QuantConnect.Lean.Engine.HistoricalData.BrokerageHistoryProvider
20210211 23:35:18.668 Trace::          Brokerage:      QuantConnect.Brokerages.Fxcm.FxcmBrokerage
20210211 23:35:18.668 Trace:: LiveTradingDataFeed.Exit(): Start. Setting cancellation token...
20210211 23:35:18.668 Trace:: BaseDataExchange(CustomDataExchange) Stopping...
20210211 23:35:18.669 Trace:: LiveTradingDataFeed.Exit(): Exit Finished.
20210211 23:35:18.669 Trace:: DefaultAlphaHandler.Exit(): Exiting...
20210211 23:35:18.673 Trace:: DefaultAlphaHandler.Exit(): Ended
20210211 23:35:18.679 Trace:: BaseDataExchange(CustomDataExchange).ConsumeQueue(): Cancellation requested.  Exiting...
20210211 23:35:18.679 ERROR:: LiveTradingResultHandler.Update(): Algorithm not yet initialized.
20210211 23:35:18.679 ERROR:: During the algorithm initialization, the following exception has occurred: System.TimeoutException: Execution Security Error: Operation timed out - 5 minutes max. Check for recursive loops.
   at QuantConnect.Isolator.MonitorTask(Task task, TimeSpan timeSpan, Func`1 withinCustomLimits, Int64 memoryCap, Int32 sleepIntervalMillis) in C:\Users\hanna\Source\Repos\Lean\Common\Isolator.cs:line 186
   at QuantConnect.Isolator.ExecuteWithTimeLimit(TimeSpan timeSpan, Func`1 withinCustomLimits, Action codeBlock, Int64 memoryCap, Int32 sleepIntervalMillis, WorkerThread workerThread) in C:\Users\hanna\Source\Repos\Lean\Common\Isolator.cs:line 95
   at QuantConnect.Isolator.ExecuteWithTimeLimit(TimeSpan timeSpan, Action codeBlock, Int64 memoryCap, Int32 sleepIntervalMillis, WorkerThread workerThread) in C:\Users\hanna\Source\Repos\Lean\Common\Isolator.cs:line 201
   at QuantConnect.Lean.Engine.Setup.BrokerageSetupHandler.Setup(SetupHandlerParameters parameters) in C:\Users\hanna\Source\Repos\Lean\Engine\Setup\BrokerageSetupHandler.cs:line 216Execution Security Error: Operation timed out - 5 minutes max. Check for recursive loops.
20210211 23:35:18.681 ERROR:: LiveTradingResultHandler.Update(): Algorithm not yet initialized.
20210211 23:35:18.681 Trace:: Debug: FXCM Brokerage account base currency: USD
['EURUSD', 'USDJPY', 'GBPUSD', 'AUDUSD', 'USDCAD', 'USDCHF', 'NZDUSD']
[0.0001, 0.01, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001]
[3, 3, 3, 3, 3, 3, 3]
oanda
4
24
td3
long_and_short
all
[log_returns]
--------------
['EURUSD', 'USDJPY', 'GBPUSD', 'AUDUSD', 'USDCAD', 'USDCHF', 'NZDUSD']
['spawn']
12
--------------
24
124
20210211 23:35:18.689 Trace:: StopSafely(): waiting for 'Result Thread' thread to stop...
20210211 23:35:18.784 Trace:: LiveTradingResultHandler.Run(): Ending Thread...
20210211 23:35:18.785 Trace:: LiveTradingResultHandler.SendFinalResult(): Starting...
20210211 23:35:53.858 Trace:: LiveTradingResultHandler.SendFinalResult(): Finished storing results. Start sending...
20210211 23:35:53.858 Trace:: LiveTradingResultHandler.SendFinalResult(): Ended
20210211 23:35:53.859 Trace:: Engine.Run(): Disconnecting from brokerage...
20210211 23:35:53.861 Trace:: FxcmBrokerage.Disconnect()
20210211 23:35:56.779 Trace:: Engine.Run(): Disposing of setup handler...
20210211 23:35:56.784 Trace:: BrokerageSetupHandler.Setup(): Found data queue handler to dispose: QuantConnect.Brokerages.Fxcm.FxcmBrokerage
20210211 23:35:56.797 Trace:: Engine.Main(): Analysis Completed and Results Posted.
Engine.Main(): Analysis Complete.
20210211 23:35:56.799 Trace:: Config.GetValue(): close-automatically - Using default value: False
Engine.Main(): Press any key to continue.
20210211 23:35:58.673 Trace:: FxcmBrokerage.GetHistory(): Maximum attempts reached for: GBPUSD

**Comment by hn2** [comment]
I am running the exact same script with oanda and it is working fine.

**Comment by Martin-Molinero** [comment]
Hey @hn2, this issue is **not** happening in the cloud I believe, I see those logs are from a local deployment. From the logs `FxcmBrokerage.GetHistory(): Maximum attempts reached for: GBPUSD`, seems FXCM is timing out/failing in the history request, curious what mono version are you using?

**Comment by hn2** [comment]
I believe the latest one.

**Comment by hn2** [comment]
It throws this error:
mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb
What mono version are you using in the cloud?

**Comment by Martin-Molinero** [comment]
> I believe the latest one.

See https://github.com/QuantConnect/Lean/blob/master/DockerfileLeanFoundation#L38, we are using 5.12. Suggest using quantconnect dockerhub images, at https://hub.docker.com/repository/docker/quantconnect/lean, to avoid these kinds of issues, closing this issue since it's not a Lean issue.

**Comment by hn2** [comment]
I was trying your code to install mono 5.12 but it keeps installing the latest version instead. 
Even if I deleted old version, deleted and recreated mono-xamarin.list or even on a fresh new server, it keeps installing the latest version. What could be the problem?
