### ISSUE TITLE
Review CBOT contract mutiplier Agricultural futures

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#5297]
#### Expected Behavior

- SymbolProperty Database contract multiplier are correctly set
#### Actual Behavior

- Seems CBOT ZC,ZS,ZW are off see https://github.com/QuantConnect/Lean/pull/4993#issuecomment-777200748
#### Potential Solution

Review and fix
#### Reproducing the Problem

N/A
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by esefem** [comment]
Hi there, would you have an update/ETA on this Ag futures multipliers fix?
