### ISSUE TITLE
Unable to install mono=5.12

### ISSUE THREAD

**Issue by hn2** [QuantConnect/Lean#5305]
Please do not close issues without giving a solution.
The issue is related to LEAN installation and the code posted on the main page IS NOT working.
I'm trying to solve this for a few days without success and therefore I can not run LEAN.
apt-cache policy mono-complete:
mono-complete:
  Installed: (none)
  Candidate: 6.12.0.107-0xamarin13+ubuntu1604b1
  Version table:
     6.12.0.107-0xamarin13+ubuntu1604b1 500
        500 http://download.mono-project.com/repo/ubuntu xenial/main amd64 Packages
     6.8.0.105+dfsg-2 500
        500 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages
     5.10.1.20-0xamarin1+debian7b1 500
        500 http://download.mono-project.com/repo/debian wheezy/main amd64 Packages
Please explain how to change the candidate to version 5.12 or otherwise correct the code on LEAN main page (it also has permissions problems which I was able to solve)

Thank you.

**Comment by jaredbroad** [comment]
We cannot provide support for installing Mono.
