### ISSUE TITLE
Feature - Add instructions on setting up local Python code completion for JetBrains IDEs

### ISSUE THREAD

**Issue by aarjaneiro** [QuantConnect/Lean#5312]
#### Expected Behavior

IDEs should be able to provide programming assistance in python development.
#### Actual Behavior

Whereas stub generators do exist (https://pypi.org/project/quantconnect-stubs/) and it used to be the case that because the stubs were kept in the source, JetBrains IDEs were able to incorporate them into automatic completion, the separation of the stubs into their own project makes incorporation of them a non-automatic affair.
#### Potential Solution

For idea users, inform them that an import statement can be added to their python interpreter Startup scripts for the project.
#### Checklist

- [ x] I have completely filled out this template
- [ x] I have confirmed that this issue exists on the current `master` branch
- [ x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey! Closing for now since this is now covered by https://www.quantconnect.com/docs/v2/lean-cli/tutorials/local-autocomplete#02-Python-and-PyCharm using the new CLI https://www.quantconnect.com/cli
