### ISSUE TITLE
Incorrect fill price with Limit Orders

### ISSUE THREAD

**Issue by matkopitic** [QuantConnect/Lean#5337]
#### Expected Behavior
Non-marketable limit orders should be executed at the best price available in the market (unless trade through 
exemption is specified), which should never be better by the posted limit order.

For reference, see:
https://www.investopedia.com/terms/r/regulation-nms.asp
https://www.investopedia.com/terms/t/tradethrough.asp
https://tradingqna.com/t/if-the-bid-and-ask-prices-cross-each-other-who-will-get-the-better-trade-buyer-or-the-seller/1303

#### Actual Behavior
In QuantConnect/Lean it is possible to get fills for limit orders which are better than the  specified limit price.
I believe this is unrealistic in real markets.

#### Potential Solution
Modify the default Order Fill Strategy to execute at the specified Limit Price in case of non-marketable limit orders.

#### Reproducing the Problem
Execute the following code on QuantConnect
```
class FatVioletCoyote(QCAlgorithm):

    def Initialize(self):
        self.SetStartDate(2020, 1, 8)
        self.SetEndDate(2020, 1, 8)
        
        self.order_posted = False

        self.SetCash(100000)
        self.AddEquity("CEI", Resolution.Tick)
        

    def OnData(self, data):
        if not self.order_posted:
            if self.TimeIs(10, 20, 0):
                price = self.Securities['CEI'].Price
                self.Log(f"Current price: {price}")
                self.LimitOrder("CEI", 1, 3.42)
                self.order_posted = True

    def OnOrderEvent(self, order_event):
        self.Log(f"{self.Time} {order_event}")
        
    def TimeIs(self, hour, minute, second):
        return self.Time.hour == hour and self.Time.minute == minute and self.Time.second == second
```

It results:
```
2020-01-08 10:20:00 : | Current price: 3.92
2020-01-08 10:20:00 : | 2020-01-08 10:20:00.011000 Time: 01/08/2020 15:20:00 OrderID: 1 EventID: 1 Symbol: CEI Status: Submitted Quantity: 1 LimitPrice: 3.42
2020-01-08 11:20:12 : | 2020-01-08 11:20:12.553000 Time: 01/08/2020 16:20:12 OrderID: 1 EventID: 2 Symbol: CEI Status: Filled Quantity: 1 FillQuantity: 1 FillPrice: 3.41 USD LimitPrice: 3.42 OrderFee: 1 USD
2020-01-08 16:00:00 : | Algorithm Id:(b57e76b754b542db8aa73552428f78b8) completed in 3.76 seconds at 39k data points per second. Processing total of 148,364 data points.

```

#### System Information
QuantConnect platform, also on Lean Latest

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by matkopitic** [comment]
@Martin-Molinero / @jaredbroad : Any thought/comment on this issue would be greatly appreciated!

**Comment by Martin-Molinero** [comment]
Are you maybe pointing to the case described here https://github.com/QuantConnect/Lean/issues/4567#issuecomment-725055856 ?

**Comment by Martin-Molinero** [comment]
Closing for now since no response, feel free to reopen when replying though 👍
