### ISSUE TITLE
QuantBook GetOptionHistory Does Not Include OpenInterest

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5378]
#### Expected Behavior
`QuantBook.GetOptionHistory` includes `OpenInterest` data.

#### Actual Behavior
`QuantBook.GetOptionHistory` doesn't include `OpenInterest` data.

#### Potential Solution
N/A

#### Reproducing the Problem
```python
qb = QuantBook()
spy = qb.AddEquity("SPY") # add SPY data
spy_option = qb.AddOption("SPY") # add SPY option data

start_time =  datetime(2017, 1, 11, 10, 10) 
end_time = datetime(2017, 1, 13, 12, 10)

option_history = qb.GetOptionHistory(spy.Symbol, start_time, end_time)
history = option_history.GetAllData()
```
`history.colums` should have 'openinterest` value as shown in [docs](https://www.quantconnect.com/docs/research/historical-data#Historical-Data-Historical-Options-Data). 

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
After bug fix https://github.com/QuantConnect/Lean/pull/5207 by default open interest was left outside history requests, this was primarily decided because open interest time could be outside market hours and wouldn't align with market data causing a big change in the returned data

**Comment by AlexCatarino** [comment]
Ok, but could it not be included for the specific case of `GetOptionHistory`?

**Comment by marcdemers** [comment]
Any update on this?

**Comment by Martin-Molinero** [comment]
Should be able to request the open interest separately, can see examples at https://github.com/QuantConnect/Lean/pull/5207/files. Including it by default would cause a big change in the returned data because it's not necessarily aligned with market hours.

**Comment by marcdemers** [comment]
How would one do this via the QuantBook api?

**Comment by Martin-Molinero** [comment]
Hey @marcdemers!

>How would one do this via the QuantBook API?

Currently, there isn't a direct helper method for this, as there is for [GetOptionHistory](https://github.com/QuantConnect/Lean/blob/master/Research/QuantBook.cs#L317), so I'm posting an example of how to get it done. QuantBook inherits from [QCAlgorithm ](https://github.com/QuantConnect/Lean/blob/master/Algorithm/QCAlgorithm.Python.cs)so it's possible to call its methods most of the cases
![image](https://user-images.githubusercontent.com/18473240/114436939-5056c780-9b9c-11eb-9e89-3070f3b366f8.png)


```
qb = QuantBook()
aapl = qb.AddEquity("AAPL")
optionsAAPL = qb.OptionChainProvider.GetOptionContractList(aapl.Symbol, DateTime(2015, 6, 1))
for symbol in optionsAAPL:
    qb.AddOptionContract(symbol, fillDataForward=False)
history = qb.History(OpenInterest, optionsAAPL, DateTime(2015, 6, 6, 0, 0, 0), DateTime(2015, 6, 10, 0, 0, 0))
history
```

**Comment by marcdemers** [comment]
Hi @Martin-Molinero 
Thanks for the response! I think what confused me was the fact that [this documentation page on QC](https://www.quantconnect.com/docs/research/historical-data) states that 

> Regular qb.History calls do not work for options. Instead, we need to use qb.GetOptionHistory, which allows us to request options data during a given period. 

Perhaps this documentation page on Options in research should be adjusted to reflect this new API for OpenInterest? Especially given that this figure below indicates that openinterest is returned in the dataframe.

![image](https://user-images.githubusercontent.com/43256268/116327537-fa397500-a794-11eb-8361-093ab7ed7726.png)

Again, thanks!

This issue can be marked as resolved.
