### ISSUE TITLE
Plotly plots not showing in research environment / Jupyter Lab

### ISSUE THREAD

**Issue by alex04103** [QuantConnect/Lean#5384]
#### Expected Behavior
When creating a plotly plot, `fig.show()` should display a plot.

#### Actual Behavior
No plot is shown, but instead an empty output cell.

#### Potential Solution
To fix this issue, installation of the `jupyterlab-plotly` lab extension is required, as stated in the plotly documentation: https://plotly.com/python/getting-started/#jupyterlab-support 

This requires npm / nodejs=>10.

```
# root shell in container
curl -sL https://deb.nodesource.com/setup_14.x | bash -
apt-get install -y nodejs

# In a lab terminal (maybe also works in bash shell)
jupyter labextension install jupyterlab-plotly

# Reload JupyterLab web page
```

I don't really understand why this extension is not installed, but plotly itself is installed - it seems that plotly is of much less utility without being able to display plots directly in the notebook.

#### Reproducing the Problem
Execute the following snippet to see an empty output cell.

```
import plotly.express as px
df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length", color="species")
fig.show()
```

#### System Information
Using the offical docker image, `quantconnect/research:latest`. Started with `./run_docker_notebook.sh`.

#### Checklist

- [ x] I have completely filled out this template
- [ x] I have confirmed that this issue exists on the current `master` branch
- [ x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
This is working for the current version of master
![image](https://user-images.githubusercontent.com/18473240/118338892-b4e3aa00-b4ed-11eb-975d-b24beb745b00.png)
