### ISSUE TITLE
Adds Custom ToString Method to API Classes

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5388]
#### Expected Behavior
Be able to visualize the results from API calls with `ToString` method. It's particularly helpful in Jupyter Notebooks.

#### Actual Behavior
The string representation looks like this:
```
<QuantConnect.Api.Compile object at 0x7f7082330978>
```
#### Potential Solution
Implement Custom `ToString`

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by MaxTube-dot** [comment]
Hi, can I take it ?

**Comment by Martin-Molinero** [comment]
Hey @MaxTube-dot! yes please go ahead, suggest just implementing one at the time with it's unit test 👍

**Comment by jfweonc** [comment]
Are you talking about this document? 
https://github.com/QuantConnect/Lean/blob/master/Api/Api.cs
How did you get the message
```<QuantConnect.Api.Compile object at 0x7f7082330978>```

**Comment by Martin-Molinero** [comment]
Hey @jfweonc!
The `ToString` methods should be added for the objects returned by the [Api methods](https://github.com/QuantConnect/Lean/blob/master/Api/Api.cs), can see them at https://github.com/QuantConnect/Lean/tree/master/Common/Api. 
Suggest taking them one at the time. 

> What steps did you go through to get the message
<QuantConnect.Api.Compile object at 0x7f7082330978>

This is just the default to string implementation that python takes from a C# class. If `ToString` was implemented it would use it instead
