### ISSUE TITLE
Retry commonly failed NUnit tests

### ISSUE THREAD

**Issue by C-SELLERS** [QuantConnect/Lean#5399]
#### Expected Behavior

Tests that commonly fail during CI builds should automatically retry

#### Actual Behavior

If they fail it marks the CI test as a failure. 

#### Potential Solution

Not a huge deal but instead of re-triggering the build we could add NUnit `[Retry(n)]` attribute to allow them to re attempt if they failed up to n times. 

#### Reproducing the Problem

Check latest commits travis tests, about half the time a few regulars will fail because of external factors to Lean. Such as tingo news based tests.

#### System Information

Applicable to all OS's

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Should diagnose cause and avoid retries if possible
