### ISSUE TITLE
Tick data does not arrive to an algorithm's OnData method

### ISSUE THREAD

**Issue by CodingGenie** [QuantConnect/Lean#5404]
#### Expected Behavior
When a tick is emitted in live or paper mode, even if the algorithm works with another resolution (e.g minute), the tick will still arrive to an algorithm's OnData method. This is the way it previously worked and I'm right now finding my algorithms to only get consolidated TradeBar objects. 

#### Actual Behavior
both TradeBar and the Ticks it consists of will arrive to the OnData method. 

#### Potential Solution
This worked previously as expected but now doesn't, I think that there was some breaking change? Could you explain please

#### Reproducing the Problem
Try running Binance in paper trading mode.
Note that Binance updates aggregator every time a tick arrives https://github.com/QuantConnect/Lean/blob/master/Brokerages/Binance/BinanceBrokerage.Messaging.cs#L171

Then, 
the AggregatorManager updates ScannableEnumerators https://github.com/QuantConnect/Lean/blob/master/Engine/DataFeeds/AggregationManager.cs#L150

Then ScannableEnumerators update the tradebars https://github.com/QuantConnect/Lean/blob/87b42f6fb564f767b9e1c647eded12dea2a504e4/Engine/DataFeeds/Enumerators/ScannableEnumerator.cs#L104

So I couldn't find any code that pushes the trade ticks to an algorithm. Have you guys removed it? It previously worked as follows (in paper trading mode): 
* The tick websocket is set-up by binance broker 
* The ticks are sent to aggregator, tradebars are bulding
* In the meantime while tradebars are building, the ticks arrive to an algorithm's OnData method.

Have you guys removed it? Or is there some new configuration I need to set-up?

**Comment by AlexCatarino** [comment]
If the algorithm doesn't add tick-resolution data, e.g.:
```csharp
AddCrypto("BTCUSD", Resolution.Tick);
```
OnData should **not** receive tick data. In order to get both ticks and trade bars, it must add two subscriptions:
```csharp
AddCrypto("BTCUSD", Resolution.Tick);
AddCrypto("BTCUSD", Resolution.Minute);
```
