### ISSUE TITLE
Support Indicator RollingWindow

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#5407]
#### Expected Behavior

Indicators have the option to have a RollingWindow of values automatically applied.

#### Actual Behavior

Indicators don't have the option to have a RollingWindow of values automatically applied.

#### Potential Solution

N/A

#### Reproducing the Problem

[This backtest ](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_7eb38068642fd32b71a89b89ad2fa25c.html) shows we currently have to create a RollingWindow and add indicator values to it manually.

#### System Information

QC web terminal.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by biiiipy** [comment]
oh yes please, it would be a massive improvement!
It would be even better if the RollingWindow would automatically recalculate if the asked entry is outside the window. So, for example, by default the window would be 0, so no RollingWindow, and when algo asks 10 bar old value, RollingWindow automatically sets length of 10 and warms up the RollingWindow on deman behind the scenes.

**Comment by Martin-Molinero** [comment]
Implemented by https://github.com/QuantConnect/Lean/pull/7314
