### ISSUE TITLE
Better and More Controllable Visual Designer

### ISSUE THREAD

**Issue by sirinath** [QuantConnect/Lean#5410]
Can we have a better visual designer incorporating features from other platforms

**Comment by IlshatGaripov** [comment]
There is an amazing platform for hedge fund operations management done by sofistar.ch Switzerland . A guy who made the platform is now a senior developer with Amazon . At my spare time I am working on integrating lean into q-trade . We need to discuss with management we may make it open source too once day.. thanks to Jared who keeps all this great code open ..

**Comment by jaredbroad** [comment]
Good to see you again @sirinath. A general visual designer is not in the plan for 2021. IMHO it is the death knell for a trading platform. L2, GUI Upgrades, International Equities, +30 Brokerages, WFO, Better AI support... there are better places to spend energy. 

The closest we are making is a "Strategy Builder" focused on clipping Algorithm Framework modules together on QuantConnect.com. The key difference is there is no attempt to implement code logic with shapes and it's about laying your philosophy and systems.

**Comment by sirinath** [comment]
-  International Equities, +30 Brokerages, - can you support connectivity to Colombo Stock Exchange. Many of the exchanges worldwide uses the software developed for the Colombo Stock Exchange licensed through [MillenniumIT](https://en.wikipedia.org/wiki/MillenniumIT) now part of London Stock Exchange Group. More about the technology used is found here: https://www.cse.lk/pages/aboutus-technology/aboutus-technology.component.html
- GUI Upgrades - can we have a way to configure our own dash board with own charts and visualisations using Plotly and ECharts.
- L2 - can you make it L3 where we can see individual splits and contra broker

What is WFO?

**Comment by jaredbroad** [comment]
Walk Forward Optimization;

Closing as original post not planned for 2021
