### ISSUE TITLE
Projects to Borrow Ideas From

### ISSUE THREAD

**Issue by sirinath** [QuantConnect/Lean#5413]
Following projects can give further ideas:
- https://github.com/goldmansachs/gs-quant
- https://github.com/microsoft/qlib
- https://github.com/google/tf-quant-finance

May be these libraries can also be made available for use in Lean.

**Comment by jaredbroad** [comment]
Thanks @sirinath might be a better post for the community user group - https://www.quantconnect.com/forum/discussions/1/lean
I still find it so strange Microsoft got into quant..
