### ISSUE TITLE
Look Back at Orders and Transactions in the Algos synched with Broker Records

### ISSUE THREAD

**Issue by sirinath** [QuantConnect/Lean#5414]
Give the ability to get Orders and Transactions for:
- portfolio as a whole or
- individual securities

The orders will be available with the status and particulars.

The details will be synched with the broker account also.

**Comment by jaredbroad** [comment]
Closing as Orders are already synchronized with LEAN. Please spend some more time becoming familiar with the platform and then would welcome continued suggestions.

**Comment by sirinath** [comment]
Going through the documentation [Algorithm Reference - Trading and Orders](https://www.quantconnect.com/docs/algorithm-reference/trading-and-orders) I cannot find how this is done.

E.g. say I want to search my account for all past IBM buy good-till-cancelled limit orders in price range x to y from date p to q which just expired (as the algo needs to put in replacement orders for the expired order).

There are many times you need to put contingent orders say:
- when stop loss or limit orders expire you need to put new ones in place
- when certain orders are places you may need to put a matching order
- when certain orders are cancelled  you need to put other orders and cancel other orders
- when certain orders are adjusted you need to adjust other orders also
- etc.

Also there is no documentation on how to access your account details.

Also an algo need to know about:
- new money deposited to your account
- money withdrawn from the account
- deposited of dividends to the account
- deposited of rights and bonus shares to the account
- transfer of securities to and from the account
- etc.

Again these needs to be sliced and diced. Whole portfolio, security, date range, etc.

Therefore you need to be able to query account history, order details and transaction details. The way to do this should also be well documented.
