### ISSUE TITLE
Support International Markets

### ISSUE THREAD

**Issue by sirinath** [QuantConnect/Lean#5416]
Can the markets listed (members and affiliates) here be at least supported: https://www.world-exchanges.org/membership-events#member-list

This is to extract the item in the following comment to own issue: https://github.com/QuantConnect/Lean/issues/5410#issuecomment-803760234

**Comment by IlshatGaripov** [comment]
I am not sure event https://www.worldquant.com/home/ has all those affiliations. in general, it seems to me that this is nothing more than a question of resource issue. programming requires a detailed thoughtful approach. Finding good programmers is a big issue nowadays. Devepolment of large product is a large expense..

**Comment by jaredbroad** [comment]
We generally do support all markets already. Its been an ongoing project for 2 years; https://github.com/QuantConnect/Lean/projects/6

We do not have all the data and do not connect to all the brokerages yet. 
Closing as not specific and generally already supported. 

If you'd like to add any of them process their data into LEAN format; create an entry into `Markets` class; and add them to the symbol properties DB / market hours DB.
