### ISSUE TITLE
I do not understand data ingestion

### ISSUE THREAD

**Issue by JustinGuese** [QuantConnect/Lean#5419]
#### Expected Behavior
Data loaded automatically when running Lean Python algorithms in docker, same performance as in Quantconnect

#### Actual Behavior
0 trades, no returns

#### Potential Solution
Could it be that lean by default does not load data? The documentation is very unclear on this, and adding an API key is deprecated according to the documentation and it should load data by default with out api key?

#### Reproducing the Problem
Clone LEAN repo, use the linux docker vs studio routine

#### System Information
Linux, Docker, VS Code, Python

#### Checklist

- [X ] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Hi there, please create a post in the LEAN user group. Github is for the building of the engine itself 
https://www.quantconnect.com/forum/discussions/1/lean
