### ISSUE TITLE
Algorithm keeps receiving quotes after the stock is delisted

### ISSUE THREAD

**Issue by quant1729** [QuantConnect/Lean#542]
Hello, 

I have faced this interesting issue. I run DelistingEventsAlgorithm locally with provided input files (I am using AAPL, SPY) to see delistings happenning (I modified map files for this). 
In DelistingEventsAlgorithm.cs I changed just initialization method: 
        public override void Initialize()
        {
            SetStartDate(2015, 07, 3);  //Set Start Date
            SetEndDate(2015, 07, 20);    //Set End Date
            SetCash(100000);             //Set Strategy Cash
            // Find more symbols here: http://quantconnect.com/data
            AddSecurity(SecurityType.Equity, "AAPL", Resolution.Daily);
            AddSecurity(SecurityType.Equity, "SPY", Resolution.Daily);
        }

What I noticed is that when the file is over and there is no more data in it, the algo keeps receiving the forward filled prices up to the EndDate. So e.g. if I say in algo "SetEndDate(2015, 07, 20)" and there is no data for SPY after 2015-07-15 my algo will still be getting last price 210.63 on 16th, 17th.. 20th of July ..even after receiving the delisting event. 

Modified map file for SPY to emulate delisting:
[spy.csv.txt](https://github.com/QuantConnect/Lean/files/435769/spy.csv.txt)

Screenshot:
![image](https://cloud.githubusercontent.com/assets/11757550/17949998/a16a2f24-6a58-11e6-8789-eae45560ab40.png)

**Comment by jaredbroad** [comment]
Fixed in 5b3227ef501bc687e28231f26e9007f080d943f0
