### ISSUE TITLE
Consolidator Scan Only Triggered W/ Data

### ISSUE THREAD

**Issue by C-SELLERS** [QuantConnect/Lean#5457]
#### Expected Behavior

Consolidator `Scan(time)` would be called even if no data is present for the consolidator so we emit bars at the appropriate time.

#### Actual Behavior

The algorithmManager update loop only calls on consolidator `Scan(time)` when there is data for the consolidator. In most cases this is fine, but in the event that there is no data and we are past the `workingBar`'s end time the bar will __not__ emit until the next piece of data comes through. This is a flaw in algo loop.

#### Potential Solution

Figure out an alternative to have the consolidators scan with or without data.

Such as:
- An event that triggers scanning all consolidators
- At the beginning of the loop have SubscriptionManager scan all consolidators
- etc.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
``` cs
        [Test]
        public void LiveTradingAlgorithmManagerUnitTest()
        {
            _startDate = new DateTime(2018, 08, 1, 11, 10, 0);
            _manualTimeProvider.SetCurrentTimeUtc(_startDate);

            var symbol = Symbols.AAPL;

            var feed = RunDataFeed(getNextTicksFunction: handler =>
                {
                    return  new List<BaseData>();
                });

            var job = new LiveNodePacket { };
            var manager = new AlgorithmManager(true, job);

            var tt = new LiveTradingResultHandler();
            tt.Initialize(job, new QuantConnect.Messaging.Messaging(), new Api.Api(), new BrokerageTransactionHandlerTests.BrokerageTransactionHandlerTests.TestBrokerageTransactionHandler());
            tt.SetAlgorithm(_algorithm, 1000);
            var rt = new LiveTradingRealTimeHandler();
            rt.Setup(_algorithm, job, tt, new Api.Api(), manager.TimeLimit);
            var bt = new BrokerageTransactionHandlerTests.BrokerageTransactionHandlerTests.TestBrokerageTransactionHandler();
            bt.Initialize(_algorithm, new BacktestingBrokerage(_algorithm), tt);

            var lm = new TestNullLeanManager();
            lm.TimeProvider = _manualTimeProvider;
            lm.Algorithm = _algorithm;

            // TEST
            _algorithm.AddEquity("SPY", Resolution.Hour, fillDataForward: false);
            _algorithm.Consolidate("SPY", Resolution.Hour, delegate(TradeBar bar)
            {
                // ASSERT
            });
            manager.Run(job, _algorithm, _synchronizer, bt, tt, rt,
                lm, new AlgorithmManagerTests.NullAlphaHandler(), 
                CancellationToken.None);
        }
```

**Comment by Martin-Molinero** [comment]
A
  1- Profile schedule events, see why/how/where/when they are slow and improve it
  2- Create a schedule event to scan consolidators, which will work for backtesting & live trading both
B
  - Today we scan settlement models and margin models every hour, we could do the same for the consolidators, at AlgorithmManager.cs line 266
