### ISSUE TITLE
Delete Algoseek Options Data Importer from ToolBox

### ISSUE THREAD

**Issue by blonc** [QuantConnect/Lean#5458]
#### Expected Behavior
able to import data provided from algoseek

#### Actual Behavior
no longer functional due to algoseek changes 

#### Potential Solution
data now provided in .csv.gz, not csv.bz2 anymore
Data must contain the "Type" column header, while there is no such header

#### Reproducing the Problem
single data file attached

[SPX.20210319.csv.gz](https://github.com/QuantConnect/Lean/files/6261399/SPX.20210319.csv.gz)

#### System Information
Ubuntu

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by blonc** [comment]
also this is one min bar data with quotes.  

what seems a bit confusing is , is the converter taking in tick data then converting to 1 min bars?  i thought lean only could use 1 min options bars.

**Comment by Martin-Molinero** [comment]
TODO: Delete Algoseek Options Data Importer from toolbox
