### ISSUE TITLE
No Portfolio Statistics for less than 2 days 

### ISSUE THREAD

**Issue by CodingGenie** [QuantConnect/Lean#5460]
Hi everyone! \
I noticed that lean doesn't build portfolio statistics when algorithm working less than 2 days. I think it might be a bug, so it need to be fixed. \
Thanks.

**Comment by Martin-Molinero** [comment]
Hey @CodingGenie! sorry for the late reply, this isn't a bug I think, most of the statistics needs at least 2 days to get a performance sample, believe that's why it's not able to generate them
