### ISSUE TITLE
EnsureCurrencyDataFeed Exception With USDC-USD

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5478]
#### Expected Behavior
Do not throw exceptions for missing USDC-USD pair. Their conversion rate is 1.

#### Actual Behavior
Following exception:
```
System.ArgumentException: In order to maintain cash in USDC you are required to add a subscription for Forex pair USDCUSD or USDUSDC
```
in live mode with Coinbase Pro.

#### Reproducing the Problem
```python
class FocusedYellowFrog(QCAlgorithm):

    def Initialize(self):
        self.SetBrokerageModel(BrokerageName.GDAX, AccountType.Cash)
        self.SetStartDate(2020, 10, 11)
        self.SetCash(10000)
        self.SetCash("USDC", 0.00000036)
```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by castrated** [comment]
Thanks for looking into this.
