### ISSUE TITLE
Python 3 vs. Python 2

### ISSUE THREAD

**Issue by agiap** [QuantConnect/Lean#548]
Perhaps worth considering Python 3 instead of Python 2 for QuantConnect? 

> The End Of Life date (EOL, sunset date) for Python 2.7 has been moved five years into the future, to 2020. This decision was made to clarify the status of Python 2.7 and relieve worries for those users who cannot yet migrate to Python 3.

**Comment by aajtodd** [comment]
IronPython3 is in development still. Unknown ETA

https://github.com/IronLanguages/ironpython3

**Comment by jaredbroad** [comment]
Until IronPython supports Python 3.0; or we re-write the system to use a messaging bus and run python as an independent app; we can only use python 2.7

**Comment by sircambridge** [comment]
this is unfortunate as tensorflow on windows is only supporting python 3.5+ and 3.6+

**Comment by sircambridge** [comment]
oh looks like I am out of date. since quant connect switched to pythonnet - should be possible by a manual build of Python.Runtime.dll : 
https://github.com/QuantConnect/pythonnet

**Comment by jengelman** [comment]
@sircambridge were you able to get this to work?  I have python27 and python36 on this computer, did a manually build of Python.Runtime.dll and still got the "unable to load DLL 'python27'" error
