### ISSUE TITLE
Missing BasicTemplateFutureOptionsAlgorithm

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5484]
#### Expected Behavior
Lean should include a basic template for every security type.

#### Actual Behavior
Missing `BasicTemplateFutureOptionsAlgorithm`

#### Potential Solution
Add C# and Py `BasicTemplateFutureOptionsAlgorithm`. Since it's an Options algorithm, it should include Greeks and Implied Volatility. I think this GH issue might lead to others, because of the setting of `VolatilityModel`.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
We already have a `BasicTemplateFutureOptionAlgorithm` & `FutureOptionCallITMGreeksExpiryRegressionAlgorithm` example
