### ISSUE TITLE
Binance listing in symbol properties database becomes outdated frequently

### ISSUE THREAD

**Issue by jmerle** [QuantConnect/Lean#5494]
#### Expected Behavior

We can live trade on Binance while having holdings in recently added Binance pairs.

#### Actual Behavior

When we start live trading using a Binance account which has holdings in a coin that was recently added to Binance, chances are the symbol properties database doesn't contain it yet and the live deployment fails:
```
20210417 03:58:44.641 ERROR:: During the algorithm initialization, the following exception has occurred: System.ArgumentException: In order to maintain cash in XEM you are required to
add a subscription for Forex pair XEMUSDT or USDTXEM
at QuantConnect.Securities.Cash.EnsureCurrencyDataFeed (QuantConnect.Securities.SecurityManager securities, QuantConnect.Data.SubscriptionManager subscriptions, 
System.Collections.Generic.IReadOnlyDictionary`2[TKey,TValue] marketMap, QuantConnect.Data.UniverseSelection.SecurityChanges changes, QuantConnect.Interfaces.ISecurityService 
securityService, System.String accountCurrency, QuantConnect.Resolution defaultResolution) [0x00467] in <2420a6bc50c043f09c03b2fa27d4255d>:0
at QuantConnect.Securities.CashBook.EnsureCurrencyDataFeeds (QuantConnect.Securities.SecurityManager securities, QuantConnect.Data.SubscriptionManager subscriptions, 
System.Collections.Generic.IReadOnlyDictionary`2[TKey,TValue] marketMap, QuantConnect.Data.UniverseSelection.SecurityChanges changes, QuantConnect.Interfaces.ISecurityService 
securityService, QuantConnect.Resolution defaultResolution) [0x00031] in <2420a6bc50c043f09c03b2fa27d4255d>:0
at QuantConnect.Lean.Engine.DataFeeds.CurrencySubscriptionDataConfigManager.EnsureCurrencySubscriptionDataConfigs (QuantConnect.Data.UniverseSelection.SecurityChanges securityChanges,
QuantConnect.Brokerages.IBrokerageModel brokerageModel) [0x00045] in <e5337bec719442099c7ba1eb7e95ec3d>:0
at QuantConnect.Lean.Engine.DataFeeds.UniverseSelection.EnsureCurrencyDataFeeds (QuantConnect.Data.UniverseSelection.SecurityChanges securityChanges) [0x00013] in 
<e5337bec719442099c7ba1eb7e95ec3d>:0
at QuantConnect.Lean.Engine.Setup.BaseSetupHandler.SetupCurrencyConversions (QuantConnect.Interfaces.IAlgorithm algorithm, QuantConnect.Lean.Engine.DataFeeds.UniverseSelection 
universeSelection) [0x00007] in <e5337bec719442099c7ba1eb7e95ec3d>:0
at QuantConnect.Lean.Engine.Setup.BrokerageSetupHandler.Setup (QuantConnect.Lean.Engine.Setup.SetupHandlerParameters parameters) [0x0030b] in <e5337bec719442099c7ba1eb7e95ec3d>:0 In 
order to maintain cash in XEM you are required to add a subscription for Forex pair XEMUSDT or USDTXEM
```

#### Potential Solution

Jared:
> it should be a CI to an API to update the file automatically. Stefano made a unit test which did this I think

#### Reproducing the Problem

Start live trading any algorithm on Binance using an account that has some [XEM](https://www.binance.com/en/trade/XEM_USDT) in it.

#### System Information

OS: Ubuntu 20.04

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by CyberNigma** [comment]
As Jared is quoted above, you can manually update it via the QuantConnectToolBox executable:
QuantConnect.ToolBox --app binancesymbolpropertiesupdater

All of the available apps/options can be found in QuantConnect.ToolBox.Program.

The logic is located in QuanctConnect.ToolBox.BinanceDownloader class BinanceExchangeInfoDownloader which you could alternatively plug in elsewhere.

Years ago before the official binance implementation was created I ended up implementing it for my own usem and I came across this issue for both GDAX and Binance (I implemented Binance based on the GDAX implementation).  Unfortunately, it became annoying to always update it manually, and I also needed other information such as min/max price/size, notionals, etc so I ended up just implementing it elsewhere.

In the latest version it looks like GDAX and Binance use the SymbolPropertiesDatabaseSymbolMapper in the appropriate brokerages.  Previously I implemented my own symbolmapper that used the APIs to download all of the data upon startup, which I'm planning to do again.  I'll share it somewhere so the official maintainer can look at it and pick out whatever may be useful for the official version.  The benefit of it is that it automatically updates every time you launch.

I hope that helps.

**Comment by Martin-Molinero** [comment]
Solved by https://github.com/QuantConnect/Lean/pull/6213
