### ISSUE TITLE
ObjectStore Has No .Keys Attribute

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#5507]
#### Expected Behavior

We can gather all of the keys in the ObjectStore with `.Keys`.

#### Actual Behavior

To gather the keys in the ObjectStore, we currently need to use 
`keys = [str(j).split(',')[0][1:] for _, j in enumerate(qb.ObjectStore.GetEnumerator())]`
See [this related thread](https://www.quantconnect.com/forum/discussion/11256/objectstore/p1).

#### Potential Solution

Upgrade `IObjectStore` from `IEnumerable<KeyValuePair<string, byte[]>>` to `IDictionary<string, byte[]>`.

#### Reproducing the Problem

Refer to the notebook in the related thread.

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
The `ObjectStore` instance can be iterated directly providing `kvp` pairs. In the algorithm can use `for kvp in self.ObjectStore:` or `for kvp in qb.ObjectStore:` for research. We might of fixed this in some recent update to pythonNet. Closing issue for now.
