### ISSUE TITLE
Library Request: stumpy

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5526]
#### Expected Behavior
Supports [stumpy](https://github.com/TDAmeritrade/stumpy)
[STUMPY](https://github.com/TDAmeritrade/stumpy) is a powerful and scalable library that efficiently computes something called the matrix profile, which can be used for a variety of time series data mining tasks.

#### Actual Behavior
Not supported.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by seanlaw** [comment]
@AlexCatarino I am excited to see this. May I ask what is needed to add STUMPY to Lean?
