### ISSUE TITLE
Allows Data Resolution Swap

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5530]
#### Expected Behavior
Be able to easily add and remove subscriptions. 

#### Actual Behavior
We can add several data subscriptions with different resolutions for a given security. However,  if we want to add and remove only one, we need to remove all subscriptions with `RemoveSecurity` method and add the desired subscription back.

#### Potential Solution
Add a method that adds/removes data subscriptions to the secutiry.

#### Reproducing the Problem
Add two resolutions:
```csharp
AddEquity("SPY", Resolution.Daily);
AddEquity("SPY", Resolution.Second);
```
how can we remove the second-resolution data feed temporarily? We need to code:
```csharp
RemoveSecurity("SPY");   // Removes both Daily and Second
AddEquity("SPY", Resolution.Daily);   // Adds Daily again
```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Not really a well supported use of the API At the moment. Many of the bar types would overwrite -- like hourly and minute bars; so we can't promise this style would work at all. 

People should use consolidators for lower freuquency bars.
