### ISSUE TITLE
GDAX Brokerage Model Has Old Trading Rules

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5544]
#### Expected Behavior
`GDAXBrokerageModel` reflects current Coinbase rules:
https://www.coinbase.com/legal/trading_rules
https://pro.coinbase.com/markets

#### Actual Behavior
Minimum order sizes from dead link: https://support.gdax.com/customer/portal/articles/2725970-trading-rules

#### Potential Solution
Updates `GDAXBrokerageModel`.

#### Reproducing the Problem
In a live algorithm we got:
```
New Order Event: Time: 05/08/2021 21:00:00 OrderID: 70 EventID: 1 Symbol: BTCUSD Status: Invalid Quantity: -0.00061915 Message: BrokerageModel declared unable to submit order
OrderID: 70 Warning - Code: NotSupported - The minimum order quantity for BTCUSD is 0.001
```
where the minimum order quantity is `0.0001` for `BTCUSD`.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment]
What is the difference between "minimum order sizes" in `GDAXBrokerageModel` and lot size?

**Comment by C-SELLERS** [comment]
Lot size describes the minimum increment possible in order size whereas minimum order size is a base value that has to be exceeded for the order to valid. 

EX. minimum order size is .01 and lot size .0001
I can order .0101
but I can't order .0001
