### ISSUE TITLE
Default Security Market to Brokerage Model

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#555]
When using SetBrokerageModel we should override the AddSecurity default markets. Its confusing needing to set both the brokerage model and the AddSecurity. 

e.g.
```
// #1
SetBrokerageModel(BrokerageName.Fxcm);
AddForex("EURUSD", Resolution.Minute);  // FXCM as expected

// #2
SetBrokerageModel(BrokerageName.Oanda); //Oanda fee models
AddForex("EURUSD", Resolution.Minute);  // Still a FXCM data feed [bug]. 
AddForex("EURUSD", Resolution.Minute, Market.Oanda);  // Oanda data feed.

// #3
// No brokerage model set, FXCM fee structure but Oanda market data.
AddForex("EURUSD", Resolution.Minute, Market.Oanda);  // Oanda data feed.
```

**Comment by andrewhart098** [comment]
@jaredbroad How about changing the default value of the "market" parameter on AddForex() to null? So from this:

    Forex AddForex(string ticker, Resolution resolution = Resolution.Minute, string market = Market.FXCM, bool fillDataForward = true, decimal leverage = 0m)

To this:

    public Forex AddForex(string ticker, Resolution resolution = Resolution.Minute, string market = null, bool fillDataForward = true, decimal leverage = 0m)

That way, if no brokerage was specified when AddForex() was called, AddSecurity() will receive a null "market" parameter and lookup the market from BrokerageModel.DefaultMarkets which was set using SetBrokerageModel().
