### ISSUE TITLE
Multiple exceptions thrown when running jupyter notebooks for python and c#(dotnet interactive)

### ISSUE THREAD

**Issue by bmello4688** [QuantConnect/Lean#5555]
#### Potential Solution
If you re-run the cell that gives you the reflection load exception then the load works. Moved Composer initialization to start.py and QuantConnect.csx for usability purposes so that all cells can just be run once without errors.

Changed start/py to dynamically add referenced for pythonnet so that we can try and stay in sync with the csx scripts. Copied and pasted csx import references.

There seems to be some trouble going from a python notebook to c# assemblies to python packages. Site packages are missing from sys.path causing the lean engine to throw exceptions on loading the python packages. We do not see this issue in the C# notebooks

#### Reproducing the Problem
using lean cli create both a python and c# project. Then run all cells in jupyter lab. All errors originate from QuantBook.cs

Errors Include:
C# and python notebook:
Composer ReflectionTypeLoadException on GetExportedValueByTypeName
Python
Unable to import pandas
start.py missing references and imports (Changed to be synchronized with csx files)

#### System Information
quantconnect/research docker image

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @bmello4688, 
Sorry to hear it's not working for you, we will need exact steps to reproduce and the error output your experiencing

**Comment by bmello4688** [comment]
Hi @Martin-Molinero ,

I just updated my comments.

**Comment by Martin-Molinero** [comment]
Closing for now, see https://github.com/QuantConnect/Lean/pull/5557#issuecomment-859792799
