### ISSUE TITLE
oanda lot sizes have now changed to 1/10, update of symbol database is required

### ISSUE THREAD

**Issue by ebengtso** [QuantConnect/Lean#5574]
#### Expected Behavior

Be able to place orders with lot sizes down to 0.1 (according to oanda documentation)

#### Actual Behavior

orders with fractional quantities are rounded to 1

#### Potential Solution

update symbol properties database for oanda symbols

#### Reproducing the Problem

place any order in oanda with a lot of 0.1 quantity with CFD instrument SPX500USD

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @ebengtso!
Can you please add an example algorithm reproducing the issue? Interested in seeing specifically which symbols are you trying to trade with quantity 0.01 and you are expecting to work

> Be able to place orders with lot sizes down to 0.01 (according to oanda documentation)

Mind adding a link for this too?

Thanks, it will help us address the issue ASAP

**Comment by ebengtso** [comment]
Actually, I'm not trading fractional quantities, but Oanda changed this from weekend, for a few symbols, and now allow orders with fractional lots.

The below is an example of what is happening when I try to place fractional order. 

To reproduce place an order with quantity of 0.1 for SPX500USD.
`20210518 18:00:02.229 ERROR:: Warning: Due to brokerage limitations, orders will be rounded to the nearest lot size of 1`

Please find attached the minimum size order for the oanda instruments
[instruments.txt](https://github.com/QuantConnect/Lean/files/6503580/instruments.txt)

**Comment by ebengtso** [comment]
By the way, you can get the information of lot sizes from Oanda by connecting to the URL:

"https://api-fxtrade.oanda.com/v3/accounts/<ACCOUNT>/instruments"

according to this documentation: http://developer.oanda.com/rest-live-v20/account-ep/
