### ISSUE TITLE
Adds Sortino Ratio to Algorithm Statistics and Report

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5594]
#### Expected Behavior
The Sortino Ratio is available in Algorithm Statistics and Report. 

#### Actual Behavior
The Sortino Ratio is not available in Algorithm Statistics and Report, but it is calculated in Lean.

#### Potential Solution
Adds the Sortino Ratio value to the results. It's a popular statistics metric that has been used in Alpha Streams portfolio optimization.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by ikamanu** [comment]
Thank you!
