### ISSUE TITLE
Delisting Event / Data Events 

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#56]
Create an "OnDelisting" event in the QCAlgorithm class which is called when a symbol is to be delisted. 

This should be triggered in the Algorithm Manager(?) from a feed.DataEvents queue which has generic status events on the data. The data event will include the subscription-id, symbol and relevant event types.

Before the OnData event, the DataEvents queue would be cleared (synchronously processed) and passed into the algorithm event handlers.

This same mechanism could later be used for circuit breakers, and unexpected market closes.

For now this would only be supported in backtesting using the *map_files*. If the map files final date is today, pass through the delisting data event. For live trading we would need to organize a data source.

**Comment by bizcad** [comment]
I was just thinking about this problem.  It should be fired when the data feed breaks as well so that the algo could issue an OnLiquidate() and perhaps a quit, if the algo goes blind.

**Comment by jaredbroad** [comment]
Completed in #e1938ba
