### ISSUE TITLE
Latest master is incompatible with released nuget version

### ISSUE THREAD

**Issue by hackkash** [QuantConnect/Lean#5614]
#### Expected Behavior
Nuget version and latest lean engine in Quant Connect are compatible.

#### Actual Behavior
Latest nuget is [2.5.11719](https://www.nuget.org/packages/QuantConnect.Algorithm.Framework/2.5.11719?_src=template). Latest version used by the Lean engine is [11796](https://github.com/QuantConnect/Lean/releases/tag/11796). There is [a breaking change](https://github.com/QuantConnect/Lean/pull/5418) in the 11796 version.

#### Potential Solution
Option 1: Release 11796 as a nuget package
Option 2: Rollback the Quant Connect Lean Engine in the cloud to 2.5.11719 (or at least prior to 11796)
Option 3: Change the qaunt connect cloud lean engine to use the latest nuget version, not the latest version from master branch
Option 4: Revisit [this decision](https://www.quantconnect.com/forum/discussion/7583/choose-engine-version/) and let everyone select their own Lean engine version so breaking changes like this are easily solvable by customers.

#### Reproducing the Problem
Try to create a project locally using the latest nuget above and then push it to the cloud. The Lean engine in the cloud can see build failures like the below when using `FundamentalUniverseSelectionModel`

```
'FundamentalUniverseSelectionModel' does not contain a constructor that takes 3 arguments
```

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @hackkash!
We've released a new nuget version `11800`. Note we seldom push breaking changes like https://github.com/QuantConnect/Lean/pull/5418, the code removed has been obsolete for two years and was not used. The `securityInitializer` pass in to the `FundamentalUniverseSelectionModel` should be removed 👍.
