### ISSUE TITLE
Library Request: Neo 4j

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5621]
#### Expected Behavior
Supports [neo4j](https://pypi.org/project/neo4j/)
[neo4j](https://pypi.org/project/neo4j/) is used to model a neural network as a graph structure in Neo 4j.

#### Actual Behavior
Not supported.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
Awesome package but sorry we cannot host this as an internal service
