### ISSUE TITLE
TradeStatistics works with C# but not Python.

### ISSUE THREAD

**Issue by varuk** [QuantConnect/Lean#5622]
[

#### Expected Behavior

The TradeStatistics object should work for both python and C#
#### Actual Behavior

Only works for C#
#### Reproducing the Problem

[ Here](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_cee62abaf85ad2f1d4d03dfba1005f3b.html) is the C# code, and here is python to reproduce the [problem](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_9ef33e1cdd7210aaf818cba6ed5af272.html)
#### Checklist

- 

- [x] I have completely filled out this template

- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Thanks for the report @varuk 👍. I've open an PR with a work around for the underlying pythonNet issue that we will be addressing soon
