### ISSUE TITLE
Python Version of Black Litterman PCM Throws ValueError

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#5627]
#### Expected Behavior

The python implementation of BlackLittermanOptimizationPortfolioConstructionModel matches the C# implementation.

#### Actual Behavior

The python implementation of BlackLittermanOptimizationPortfolioConstructionModel doesn't match the C# implementation. For instance, [this backtest](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_def6eceba5117135cb8b7a763d518567.html) shows that when a security in `symbolDataBySymbol` doesn't have an active insight, the matrix multiplication in `apply_blacklitterman_master_formula` fails.

#### Potential Solution

N/A

#### Reproducing the Problem

See the backtest above.

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by rosswendt** [comment]
[I hacked something together in my fork](https://github.com/rosswendt/Lean/tree/bug-5627-python-black-litterman-value-error). Unfortunately all we gain is sometimes backtesting works, and sometimes we just get Value Errors moved the ROC function in the SymbolData class.
