### ISSUE TITLE
Generating random data for specific tickers

### ISSUE THREAD

**Issue by jmerle** [QuantConnect/Lean#5643]
#### Expected Behavior

It is possible to specify which ticker(s) the random data generator generates data for.

#### Actual Behavior

The random data generator doesn't allow configuring the tickers it generates data for.

#### Potential Solution

Add a `--symbols` option that takes a comma separated list of tickers to generate data for. This solution should skip all given tickers which don't have a matching symbol properties database entry, otherwise the generated data cannot be used.

#### System Information

OS: Ubuntu 20.04

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Chizkiyahu** [comment]
I try to [add --symbol](https://github.com/Chizkiyahu/Lean/commit/5a091bfd1db4ff290838365d2f24ce9cce5c4062)
but I don't know how to check the  `symbolString`  is a valid ticker
when I used `Symbol.Create(symbolString, securityType,market)`

**Comment by jmerle** [comment]
To check whether a given string is a valid ticker, you can use the [`SymbolPropertiesDatabase`](https://github.com/QuantConnect/Lean/blob/master/Common/Securities/SymbolPropertiesDatabase.cs) class. This class provides access to the [symbol properties database](https://github.com/QuantConnect/Lean/blob/master/Data/symbol-properties/symbol-properties-database.csv), which all valid tickers have a matching entry in. This can either be an entry specifically for the ticker (like "oanda,EURUSD,forex,EUR/USD,USD,1,0.0000"), or for all tickers of a given security type/market combination using a wildcard (like "usa,[*],equity,,USD,1,0.01,1").

You can get a `SymbolPropertiesDatabase` instance using `SymbolPropertiesDatabase.FromDataFolder()`, and check whether an entry exists using `symbolPropertiesDatabase.ContainsKey(market, symbol, securityType)`. In this method, `symbol` must either be a ticker or `SecurityDatabaseKey.Wildcard`. If an entry exists for the given symbol or the wildcard, the symbol is a valid ticker.

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/6135, `--tickers=SPY,AAPL,etc` is now a valid optional argument for the  random data generator
