### ISSUE TITLE
NumericalPrecisionLimited Warning Overload

### ISSUE THREAD

**Issue by C-SELLERS** [QuantConnect/Lean#5665]
#### Expected Behavior

SubscriptionDataReader would post a StartDateLimitedEvent when _periodStart < _factorFile minimum date. Also would limit this kind of warning.

#### Actual Behavior

Currently posts NumericalPrecisionLimitedEvent. 

and in the case of this backtest making a history request
https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_6ba2e9f607abe1660bcd25b12b51a2ac.html

It fills the log with the date reassignment for each history request.
![image](https://user-images.githubusercontent.com/41277998/122122240-69206b00-cde1-11eb-8638-1d1bb03eeef8.png)

This error posting should be limited, even though the history request may be an odd one.

#### Potential Solution

First change the event type to StartDateLimitedEvent <- Because this is exactly what the code is doing by changing the start date.

Then put a limiter on the warning posting, <- I believe we already have one for the HistoryProvider but best to double check.

#### Reproducing the Problem

Run the algorithm attached

#### System Information

N/A

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closing since this has been solved by https://github.com/QuantConnect/Lean/pull/5767/files
