### ISSUE TITLE
Github Stubs Workflow Broken

### ISSUE THREAD

**Issue by C-SELLERS** [QuantConnect/Lean#5667]
#### Expected Behavior

Upon merge into master builds are able to produce new python stub packages.

#### Actual Behavior

Currently the CI/CD workflows are failing to publish stubs, this appears to be because of an issue with space in the containers they are running.

```
 Cloning into '/__w/Lean/Lean/Launcher/bin/Release/dotnet-runtime'...
fatal: write error: No space left on device
fatal: index-pack failed
```

#### Potential Solution

Figure out why its running out of space now vs before, and attempt to deal with the issue.

#### Reproducing the Problem

Look at the latest merges and their workflows

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closing for now, PR https://github.com/QuantConnect/Lean/pull/5673 seems to have solved the issue
