### ISSUE TITLE
Library Request: xlrd and openpyxl

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5685]
#### Expected Behavior
Supports [xlrd](https://pypi.org/project/xlrd/)
[xlrd](https://pypi.org/project/xlrd/) is a library for reading data and formatting information from Excel files in the historical .xls format.
Supports [openpyxl](https://pypi.org/project/openpyxl/)
[openpyxl](https://pypi.org/project/openpyxl/) is a Python library to read/write Excel 2010 xlsx/xlsm/xltx/xltm files.

#### Actual Behavior
Not supported.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by cauldnz** [comment]
Hi @AlexCatarino. ~12 months since the support ticket that was closed on the creation of this Github issue. Still no resoution. Any chance of an update please?
