### ISSUE TITLE
Can't Maximize Position Size of OptionStrategies

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#5693]
#### Expected Behavior

We can place an order with OptionStrategies to maximize the position size (minimize the amount of margin remaining).

#### Actual Behavior

When we try to maximize the position size of OptionStrategies, we receive the error
> Order Error: id: 1, Insufficient buying power to complete order

Related issue: #2709 
Related thread: [Examples of how to use OptionStrategyPositionGroupBuyingPowerModel?](https://www.quantconnect.com/forum/discussion/11552/examples-of-how-to-use-optionstrategypositiongroupbuyingpowermodel/p1/)

#### Potential Solution

Fix the bug in the OptionStrategyPositionGroupBuyingPowerModel.
None of [the examples in the repo using OptionStrategies](https://github.com/QuantConnect/Lean/search?q=optionstrategies) maximize the position size. They all use a small order size of <= 10. We need more unit tests to cover the case of attaining the maximum position size.

#### Reproducing the Problem

Run [this backtest](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_f47d2721f781c595b680852c34570d11.html). 

When placing a single order for the BullPutSpread, with
`self.Order(strategy, 54) # Works in interval [1, 54]`
the orders go through without error but we have $7,111 of $10K margin remaining. Increasing the order size to 55 throws the error.

Additionally, when placing the orders incrementally with 
```
for i in range(64): # Works in interval [1, 64]
    self.Order(strategy, 1)
```
we can achieve a larger position size but we have $6,480 of $10K margin remaining. Increasing the `range` to `range(65)` throws the error.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
I think this is because the orders are being placed individually internally by Lean, and later if finds strategy matches from the current portfolio, reducing margin requirements. The combo orders are not there yet which is what should probably be used instead. In the provided example backtest splitting the `Order(strategy, x)` in multiple operations should do the trick

**Comment by wheredyoufindthis** [comment]
Hey, @AlexCatarino asked me add my case to the issue

I backtest a futures spread trading strategy

It seems that QuantConnect broker simulation is not correct about margin amount for future spreads
QuantConnect just summarise margins of two contracts. In fact QuantConnect requires 4 times bigger margin than Interactive Broker does

I expected QuantConnect to reproduce futures spread margin correctly as broker does

QuantConnect requires 18k$ margin. The strategy short CL Jul 21 and long CL Sep 21 contracts. [qc code](https://gist.github.com/wheredyoufindthis/f2306b3d415d23f773f0e39530e43818)

![image](https://user-images.githubusercontent.com/8260020/123553778-e8b91d00-d785-11eb-8c88-f946eb1e0807.png)

Interactive Broker required 4k$ margin for that spread
![image](https://user-images.githubusercontent.com/8260020/123553795-f5d60c00-d785-11eb-95fa-e734f59a7f9e.png)

**Comment by ikamanu** [comment]
Any ETA or expected timeline for this issue?

**Comment by rafael-trevisan** [comment]
Is there any workaround for this issue for the time being?

**Comment by DerekMelchin** [comment]
It would be nice to have something like
```
self.SetHoldings(option_strategy, 1)
```
so we can maximize the position size.

**Comment by ArthurAsenheimer** [comment]
> It would be nice to have something like
> 
> ```
> self.SetHoldings(option_strategy, 1)
> ```
> 
> so we can maximize the position size.

And please also consider adding `Insight(option_strategy, ...)` and `PortfolioTarget(option_stratetgy, quantity)` so that we can use it in the context of the Algorithm Framework as well. See also #6661.

**Comment by Martin-Molinero** [comment]
The underlying bug here was solved, opening new feature request to add missing sugar syntax for option strategies https://github.com/QuantConnect/Lean/issues/7261.

**Comment by i3wangyi** [comment]
@Martin-Molinero It sounds like just a syntax sugar missing??? Are we able to workaround ourselves by having a ugly syntax?
