### ISSUE TITLE
Example Algorithms Using Quandl VIX Data Throw Errors

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#5705]
#### Expected Behavior

The example algorithms in the repo work without error.

#### Actual Behavior

These examples throw an error because the column name has been changed from "VIX Close" to "Close":
- https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/CustomDataIndicatorExtensionsAlgorithm.py
- https://github.com/QuantConnect/Lean/blob/master/Algorithm.CSharp/CustomDataIndicatorExtensionsAlgorithm.cs

[Related thread](https://www.quantconnect.com/forum/discussion/11720/backtests-failing-vix-data-issue/p1).

#### Potential Solution

Replace
`self.AddData(QuandlVix, 'CBOE/VIX', Resolution.Daily)`
with
`self.AddData(CBOE, "VIX", Resolution.Daily)`

#### Reproducing the Problem

Run the algorithms listed above.

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment]
We should also replace:
`self.AddData(QuandlVix, 'CBOE/VXV', Resolution.Daily)`
with
`self.AddData(CBOE, "VIX3M", Resolution.Daily)`
Ref.: https://www.macroption.com/vxv/
