### ISSUE TITLE
Improve Error Message from ObjectStore

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5724]
#### Expected Behavior
`ObjectStore` logs user-friendly error messages. 

#### Actual Behavior
We got the following message when we create more files than the limit impose:
```
ObjectStore Persistence Error: LocalObjectStore.InternalSaveBytes(): at file capacity: 101. Unable to save: ‘live_SCHW'
```

#### Potential Solution
Improve error message. E.g.:
```
ObjectStore Persistence Error: LocalObjectStore.InternalSaveBytes(): You have reached the ObjectStore limit for files it can save: 101. Unable to save the new file: ‘live_SCHW'
```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by RhnSharma** [comment]
I would like to take this one.
