### ISSUE TITLE
Using custom data feed with resolution of tick to add and remove securities causes blocking of all new data subscriptions

### ISSUE THREAD

**Issue by bmello4688** [QuantConnect/Lean#5737]
#### Expected Behavior
Should be able to add new data subscription from other data subscription events

#### Actual Behavior
New data subscriptions are blocked because the existing data subscription cycles too fast to allow for new data subscriptions to be added.

#### Potential Solution
I noticed that in most places, Tick resolution gets changed behind the scenes to Second resolution. Applying this change fixes the problem. 

#### Reproducing the Problem
In live mode, I was using a remote file read which was taking ~100ms, You could probably use a local file read too. I'm not sure if rest calls are fast enough. Just make sure to set the resolution to tick. I was also using the C# style of having a separate OnData method with my custom data class passed in. My remote file read was of a collection type. AddEquity to SPY or something else when custom data class returns.

#### System Information
Windows 10
VS2019

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey!

> New data subscriptions are blocked because the existing data subscription cycles too fast to allow for new data subscriptions to be added.

Mind expanding on what's the issue here? There is no blocking in live trading, 

>  Tick resolution gets changed behind the scenes to Second resolution

Don't think this is a valid solution, Lean is trusting on the user knowing what's the right resolution for it's custom data. Tick will behave as real time.
