### ISSUE TITLE
Library Request: RiskFolio

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5745]
#### Expected Behavior
Supports [Riskfolio-Lib](https://riskfolio-lib.readthedocs.io/en/latest/index.html)
[Riskfolio-Lib](https://riskfolio-lib.readthedocs.io/en/latest/index.html) is a library for making portfolio optimization and quantitative strategic asset allocation in Python made in Peru 🇵🇪. Its objective is to help students, academics and practitioners to build investment portfolios based on mathematically complex models with low effort. It is built on top of CVXPY and closely integrated with pandas data structures.

#### Actual Behavior
Not supported.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Added by https://github.com/QuantConnect/Lean/pull/6558
