### ISSUE TITLE
RemoveSecurity does not unsubscribe symbol from data queue for Option Contracts

### ISSUE THREAD

**Issue by bmello4688** [QuantConnect/Lean#5748]
#### Expected Behavior

When removing securities, there should at least be an option to unsubscribe from the data queue so resources are not wasted on a symbol we do not want to track

#### Actual Behavior

Unsubscribe is never called, data is still queued for the symbol.

#### Potential Solution

The symbol needs to be removed from the data subscriptions. Something like this:

//Unsubscribe Symbol from data feed
SubscriptionManager.SubscriptionDataConfigService.Remove(symbol);

#### Reproducing the Problem

Remove a symbol after adding one and you will notice the unsubscribe methods will not be called in the data queue handler

#### System Information

Windows 10
VS 2019

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
From https://github.com/QuantConnect/Lean/pull/5750

> Hey @bmello4688!
The removal should already be handled internally, please provide an algorithm reproducing the issue so we can figure out where is the bug in the existing implementaiton

**Comment by bmello4688** [comment]
Hi @Martin-Molinero 

I did some investigation. The problem has to do with option contracts. Even with some test code that I added. There are really two problems. 

-  The option contract symbols never reach the data queue handler anyways. 
-  The underlying symbol is created in multiple universes. The options contract universe and an equity universe.

I think removal of the underlying symbol is not working because of the multiple universes, but I am not sure. If I remove from all universes. It still doesn't work.

It is very easy to reproduce. I'm just not sure the best way to solve the problem though. I added the a regression test that shows the problem. I am running it in live mode and setting breakpoints in the subscribe and unsubscribe events in the data queue handler.

I added the test to the #5750 branch

**Comment by Martin-Molinero** [comment]
Hey @bmello4688!

Thanks for providing the reproducing algorithm!
- The removal of symbols in the universes respect the `UniverseSettings.MinimumTimeInUniverse` value, setting it to `TimeSpan.Zero` allows you to add and remove immediately, default value is a day.
- There is a catch regarding the underlying symbol, removing the option contract does not remove the underlying _automatically_ (while it does add it), but calling `RemoveSecurity(_contract.Underlying);` will work. There was a bug here see https://github.com/QuantConnect/Lean/pull/5798 depending on which universe was enumerated first it would behave differently, in the PR it's directly removing the security from all universes
