### ISSUE TITLE
Clean exit

### ISSUE THREAD

**Issue by benjaminthedonkey** [QuantConnect/Lean#575]
This might  be a very basic question but.. is there a way to clean exit the algorithm execution in live mode?. I mean, I want to stop the execution but in a way that all finalize/cleanup methods get executed. Like "OnEndOfAlgorithm()".   Thanks.

**Comment by mchandschuh** [comment]
The algorithm has access to a `Quit(string message = "")` method that you can call. This will gracefully terminate execution and optionally write a message. The message is nice to use as a reason for the exit.

**Comment by benjaminthedonkey** [comment]
That is great.  But what if I have to stop it in the middle of the execution ?.  Wouldn't be nice to capture the ctrl + c event and do a clean exit  as well?.

**Comment by mchandschuh** [comment]
Have a look at the command handlers.  You could issue a stop command via a file.
