### ISSUE TITLE
Crypto algorithm error - No conversion rate for the following cash

### ISSUE THREAD

**Issue by dominiclapointe** [QuantConnect/Lean#5751]
Hi all,

I am quite new to lean.io and trying to get started with a minimal setup to trade crypto. This simple code keep throwing the below error. Even the BasicTemplateCryptoAlgorithm does throw the same error. 

I did validate and the data seems to exists if looking here : https://www.quantconnect.com/data/tree/crypto/bitfinex/minute/btcusdt

Is that error normal or some error got introduced in the AddCrypto at some point? 

Thank you

#### Expected Behavior

Get the market data for BTCUSDT in algo using AddCrypto("BTCUSDT", Resolution.Minute);

#### Actual Behavior

ERROR:: Failed to assign conversion rates for the following cash: USDT,BTC. Attempting to request daily resolution history to resolve conversion rate

#### Reproducing the Problem

```
public override void Initialize()
        {
            SetStartDate(2020, 10, 07);  //Set Start Date
            SetEndDate(2020, 10, 08);    //Set End Date
            SetCash("USDT", 1000);           //Set Strategy Cash

            SetBrokerageModel(Brokerages.BrokerageName.Bitfinex, AccountType.Cash);
            AddCrypto("BTCUSDT", Resolution.Minute);      
        }

        /// <summary>
        /// OnData event is the primary entry point for your algorithm. Each new data point will be pumped in here.
        /// </summary>
        /// <param name="data">Slice object keyed by symbol containing the stock data</param>
        public override void OnData(Slice data)
        {
            var rsi = RSI("BTCUSDT", 14, Indicators.MovingAverageType.Simple);

            if (rsi <= 35)
            {
                MarketOrder("BTCUSDT", 0.0001);
            }
            else
            {
                if (Portfolio.Invested == true && Portfolio.CashBook["BTCUSDT"].Amount > 0)
                {
                    MarketOrder("BTCUSDT", -0.0001);
                }
            }
        }
```

#### System Information

Lean master branch running on windows 10 and VS 2022 preview 1

#### Checklist

- [x ] I have completely filled out this template
- [x ] I have confirmed that this issue exists on the current `master` branch
- [x ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x ] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @dominiclapointe! Is the data available locally for lean to use? By default Lean will ask for the last 10 minutes bars prior to the start date of the algorithm to get the conversion rate, if it doesn't work it will use daily resolution. My guess is that there is no data for `(2020, 10, 07) - 10min` locally

**Comment by dominiclapointe** [comment]
Hum would make sense I guess. My expectation was that  lean would fetch the data based on the given date.

Is there a way to get the data through an API or I have to gather all the data manually and put it in a specific folder?

Thank you

**Comment by Martin-Molinero** [comment]
> Is there a way to get the data through an API

Yeah! Take a look at https://www.youtube.com/watch?v=Iedf4x4Bnj4 & https://www.youtube.com/watch?v=faazkn8BIv0 more info at https://www.lean.io/docs/lean-cli

Closing since this isn't an issue of lean

**Comment by dominiclapointe** [comment]
Not to complain, lean seems so far quite the best quant product out there but, the free tier of quantconnect (commercial product) allow for gathering this data for free while the lean.io open source plateform charge in order to get this data? 

Do you have any documentation on how to plug our data provider and make it works seamlessly with lean.io? Like, is there a way to call binance API (only crypto in my case), map it to whatever entity lean.io uses behind the hood and be able to use the QCAlgorythm?

Thank you
