### ISSUE TITLE
Lean data - New data cant be used

### ISSUE THREAD

**Issue by dominiclapointe** [QuantConnect/Lean#5755]
Hi all,

Ive been paying for some data from QuantConnect using the API as we can see on the screenshot 
![image](https://user-images.githubusercontent.com/47004797/125109603-9515d000-e0b1-11eb-8703-2c3754347acb.png)
![image](https://user-images.githubusercontent.com/47004797/125109634-9cd57480-e0b1-11eb-8eac-8e6238d3230c.png)

When trying to use any of those, it doesnt work... as it sayd there is no data...

#### Expected Behavior

Be able to run backtest using either ADAUSDT or DOGEUSDT

#### Actual Behavior

![image](https://user-images.githubusercontent.com/47004797/125109837-d9a16b80-e0b1-11eb-9b07-5c25fb9c5e1a.png)

#### Reproducing the Problem

```
public override void Initialize()
        {
            SetTimeZone("UTC");
            SetStartDate(2021, 04, 24); // Set Start Date
            SetEndDate(2021, 04, 25); // Set Start Date

            SetAccountCurrency("USDT");
            SetCash(100000); // Set Strategy Cash

            SetBrokerageModel(Brokerages.BrokerageName.Bitfinex, AccountType.Cash);
            SetBenchmark("ADAUSDT");
            
            var ada= AddCrypto("ADAUSDT", Resolution.Minute, Market.Bitfinex).Symbol;
        }

        /// OnData event is the primary entry point for your algorithm. Each new data point will be pumped in here.
        /// Slice object keyed by symbol containing the stock data
        public override void OnData(Slice data)
        {
            if (!Portfolio.Invested)
            {
                SetHoldings("ADAUSDT", 1);
                Debug("Purchased Stock");
            }
        }
```
#### System Information

Windows 10, lean, version 1.0.31

#### Checklist

- [x ] I have completely filled out this template
- [ x] I have confirmed that this issue exists on the current `master` branch
- [ x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @dominiclapointe!
Can ignore that error message, if just means lean failed to find a data point in the last 10minutes from current time, can happen for more illiquid assets. I've opened a [PR](https://github.com/QuantConnect/Lean/pull/5771) increasing the look back period to 60 minutes and replaced the error message for Trace instead.
The provided algorithm works correctly, only comment is you should  `SetBenchmark("ADAUSDT");` after adding the crypto asset `AddCrypto("ADAUSDT", Resolution.Minute, Market.Bitfinex)` else Lean is supposing it's an equity instead.

**Comment by dominiclapointe** [comment]
Thanks for the quick feedback! Will add the SetBenchmark and test it again tonight ;)
