### ISSUE TITLE
Algorithms using Quandl data don't work anymore

### ISSUE THREAD

**Issue by marcograss** [QuantConnect/Lean#5757]
#### Expected Behavior

We should be able to use data from Quandl like before.

#### Actual Behavior

Any backtest with quandl data gives the following error.
`During the algorithm initialization, the following exception has occurred: Object reference not set to an instance of an object.`

#### Potential Solution

Maybe the recent changes introduced this regression.
After fixing it would be better to add a regression test for this issue.

#### Reproducing the Problem

Run `ANY` backtest in the cloud using Quandl, for example https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/QuandlImporterAlgorithm.py the very basic QuandlImporterAlgorithm.py

You will get the error I mentioned before.

#### System Information

Latest lean on quantconnect cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @marcograss!
Thanks for the report, it's a bug we introduced last night, a fix has been pushed already version `12283`, sorry for the inconvenience 👍
