### ISSUE TITLE
Research notebook crash on api.ReadBacktest().Charts request

### ISSUE THREAD

**Issue by LouisSzeto** [QuantConnect/Lean#5789]
#### Expected Behavior
Retrieve Chart data from backtest cache by using api.ReadBacktest().Charts in notebook

#### Actual Behavior
The notebook crashes when running the command `.Charts`

#### Potential Solution
N/A

#### Reproducing the Problem
in notebook:
```
backtest = api.Backtest(int(projectID), string(backtestCode))
chart = backtest.Charts
```

#### System Information
N/A

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @LouisSzeto! mind adding that's the call stack/error being shown?

**Comment by LouisSzeto** [comment]
Hi @Martin-Molinero, that is the call stack. No error message was shown, only pop up saying the notebook crashed and needed to be restarted

**Comment by AlexCatarino** [comment]
I was able to reproduce the issue with AlphaStream SDK too:
https://www.quantconnect.com/terminal/processCache/?request=embedded_backtest_98ad7e8802a3c8b870f5dac1c466a041.html

```python
from clr import AddReference
AddReference('QuantConnect.AlphaStream')
from QuantConnect.AlphaStream import *
from QuantConnect.AlphaStream.Models import *
from QuantConnect.AlphaStream.Requests import *

# Define the clientId and API access token:
clientId  = ""
token     = ""

client = AlphaStreamRestClient(AlphaCredentials(clientId, token))

# GetAlphaList didn't cause an issue
print(', '.join(client.GetAlphaList()))

# SearchAlphas() led to kernel death
request = SearchAlphasRequest()
request.ExcludedTags = ['hidden']
alphas = client.SearchAlphas(request)
```

**Comment by Martin-Molinero** [comment]
> backtest = api.Backtest(int(projectID), string(backtestCode))
chart = backtest.Charts

In this case, can confirm the issue is reproducing when a `QuantBook` instance hasn't been initialized yet, adding `qb = QuantBook()` at the top avoids the issue. Believe this is due to the QB owing the initialization of different components, these should be moved outside of `QB()` and called automatically on start 💯
