### ISSUE TITLE
Order was rounded

### ISSUE THREAD

**Issue by benjaminthedonkey** [QuantConnect/Lean#579]
I just had a serious problem with a couple of orders submitted to Oanda.  Scenario : buy market order filling price was  0.9671 ,  the limit order was calculated to be  0.9681  ( 10 pips above entry level )   and the stop market order was  0.9651 ( 20 pips below entry level ).  BUT both  limit and stop orders were rounded to  0.9700 before submitted  to the broker "To meet brokerage precision requirements" according to the log... Notice that both orders ended up above the entry level... leaving the trade with no stop loss.  I'm not sure were is the problem, but I certainly  don't  believe that this is an Oanda limitation.

**Comment by AlexCatarino** [comment]
In fact, Oanda has this limitation. For instance, if you submit a limit order at 0.967111111, Oanda will not accept it.
In order to round both of your orders to 0.970, the symbol [fractional pip (pipette)](https://www.oanda.com/forex-trading/learn/intro-to-currency-trading/conventions/pips) must be 0.001.
 Is the symbol *JPY?

**Comment by StefanoRaggi** [comment]
Guessing the symbol is USDCHF given the 0.96xx price, order prices should be rounded to the 5th decimal place before being sent to Oanda. 
The rounding precision is determined by entries in the symbol-properties-database.csv file.
If it was rounded to 0.9700, it looks like the entry was not found and a default value of 0.01 was used.

Please check you have the latest version:
https://github.com/QuantConnect/Lean/blob/master/Data/symbol-properties/symbol-properties-database.csv#L178

**Comment by benjaminthedonkey** [comment]
Stefano is right as rain. Thanks. I guess I  had an old version of that file. If I might make a comment, having a default value of 0.01 doesn't sound like a good idea for FX. I think Lean is  awesome, but the  limitation of not being able to open orders with  take profit and stop loss values has real scary consequences. How hard would be to implement it ? ( for live mode at least )

**Comment by jaredbroad** [comment]
Can you please try updating the symbol properties db file and try it again
in backtesting? It should work fine for those orders

**Comment by benjaminthedonkey** [comment]
Thanks Jared. That was the problem. All I'm saying is orders with take profit and stop loss would be a desirable functionality. I'm willing to dedicate some time to try to implement it if someone points me in the right direction.

**Comment by jaredbroad** [comment]
Thanks Ben, do you mean as a single contingent order type? eg. The stoploss
only executes if the limit/market order does?

This would be cool functionality; please join the slack group and we can
brainstorm it: http://qnt.co/slack

**Comment by jaredbroad** [comment]
Closing as was issue with old symbol-properties-database.json
