### ISSUE TITLE
TrailingStopRiskManagementModel Only Handles Long Positions

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5790]
#### Expected Behavior
`TrailingStopRiskManagementModel` handles risk for both long and short positions.

#### Actual Behavior
`TrailingStopRiskManagementModel` only handles risk for long positions.

#### Potential Solution
Implement logic to handle risk for short positions.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by davidackroyd99** [comment]
Please could I be assigned to this issue?
