### ISSUE TITLE
ToolBox throws exceptions on simple data fetch from Binance

### ISSUE THREAD

**Issue by bitbehz** [QuantConnect/Lean#5794]
#### Expected Behavior
When using ToolBox for downloading data from Binance with the following simple arguments
```
--app=BinanceDownloader --from-date=20210701-00:00:00 --to-date=20210701-12:00:00 --resolution=Hour --tickers=BTCUSDT
```
`BinanceDataDownloader` should download and finish without any errors.

#### Actual Behavior
`BinanceBrokerage` throws two unnecessary exceptions inside `BinanceDownloaderProgram.DataDownloader` method.

The first exception throws at  line 184 of  WebSocketClientWrapper.cs
```C#
protected virtual void OnClose(WebSocketCloseData e)
{
    Log.Trace($"WebSocketClientWrapper.OnClose(): Connection closed (IsOpen:{IsOpen}, State:{_client.State}): {_url}");
    Closed?.Invoke(this, e);
}
```
`_client.State` causes the exception because _client is null.

The second exception throws at  line 358 of BinanceRestApiClient.cs
```C#
 public void StopSession()
{
    if (string.IsNullOrEmpty(SessionId))
    {
        throw new Exception("BinanceBrokerage:UserStream. listenKey wasn't allocated or has been refused.");
    }
...
```
`SessionId` is null and it should be because no call is made with API keys. But exception throws anyway.

#### Potential Solution
The first exception has a simple fix:
```c#
Log.Trace($"WebSocketClientWrapper.OnClose(): Connection closed (IsOpen:{IsOpen}, State:{_client?.State}): {_url}");
```

For the second exception may be throwing an exception is not necessary at all :
```C#
public void StopSession()
{
    if (!string.IsNullOrEmpty(SessionId))
    {
       var request = new RestRequest(UserDataStreamEndpoint, Method.DELETE);
      request.AddHeader(KeyHeader, ApiKey);
      request.AddParameter(
          "application/x-www-form-urlencoded",
          Encoding.UTF8.GetBytes($"listenKey={SessionId}"),
          ParameterType.RequestBody
      );
      ExecuteRestRequest(request);   
    }           
}
```

#### Reproducing the Problem
```
QuantConnect.ToolBox.exe --app=BinanceDownloader --from-date=20210701-00:00:00 --to-date=20210701-12:00:00 --resolution=Hour --tickers=BTCUSDT
```

There is no test available for `Brokerages`

#### System Information
N/A

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by bitbehz** [comment]
I can contribute to this if accepted.

**Comment by Martin-Molinero** [comment]
Thanks for the report @bitbehz! Stefano went ahead with the fix since we were already working on Binance improvements
