### ISSUE TITLE
Fasterflect missing: Research notebook kernel crash with Resolution function parameter

### ISSUE THREAD

**Issue by biiiipy** [QuantConnect/Lean#5805]
#### Actual Behavior
Jupyter Notebooks kernel crashes when passing `Resolution` as function parameter

#### Reproducing the Problem
using latest quantconnect/research:latest image: 
`Digest: sha256:d331233160ce690fd000d7810c0cbb8c6a139088633071b13e4d7827d738cdaa`

run cli:
```
lean research "test"
```

in a notebook **create** and **execute** a cell with python code:
```
def fetch(resolution):
    qb = QuantBook()
    qb.AddEquity("SPY")
    history = qb.History(qb.Securities.Keys, 360, resolution)
    return history

fetch(Resolution.Daily)
```

result:
`The kernel for research.ipynb appears to have died. It will restart automatically.`

log:
```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Fasterflect, Version=3.0.0.0,
Culture=neutral, PublicKeyToken=38d18473284c1ca7'. The system cannot find the file specified.

File name: 'Fasterflect, Version=3.0.0.0, Culture=neutral, PublicKeyToken=38d18473284c1ca7'
   at Python.Runtime.FieldObject.tp_descr_get(IntPtr ds, IntPtr ob, IntPtr tp)
```

#### System Information
Docker For Windows (latest)

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @biiiipy!
Thanks for the report, we will fix it ASAP

**Comment by Martin-Molinero** [comment]
Can confirm this issue is similar to https://github.com/QuantConnect/Lean/issues/5789, there is an initialization dependency with creating a `qb = QuantBook()` instance, placing `qb = QuantBook()`before calling `fetch(Resolution.Daily)` solves this issue, tested locally and in the cloud. Initialization should be moved outside of QB() and called automatically on start 💯
