### ISSUE TITLE
Multi strategy trading

### ISSUE THREAD

**Issue by xbotuk** [QuantConnect/Lean#5818]
Can you support multiple strategy trading against the same broker, i.e. trade multiple longs and shorts open independently against the same broker?

For example Strategy S1 going 2 Long, then after some point Strategy S2 going 1 short, then strategy S3 going 2 short, and they exit at their respective times as necessary. Even though the broker sees the net positions, but the Lean platform can manage and track them independently and accurately.

**Comment by Martin-Molinero** [comment]
Hey @xbotuk!

> the Lean platform can manage and track them independently and accurately.

Lean engine doesn't support this at the moment. Although we are working on something similar for alpha streams, consuming multiple strategies and manage them independently using the portfolio construction model & some logic in the algorithm. See example at https://github.com/QuantConnect/Lean/pull/5770/files#diff-6890b26dd9ff34192c56db09a2d4a38f55cfecf7aed1b7ebc6f1a9479a2fca6bR49

**Comment by jaredbroad** [comment]
https://github.com/QuantConnect/Lean/issues/6968
Coming 2023
