### ISSUE TITLE
RelativeDailyVolume EnableAutomaticIndicatorWarmUp

### ISSUE THREAD

**Issue by jovuribe** [QuantConnect/Lean#5835]
#### Expected Behavior

When EnableAutomaticIndicatorWarmUp is set to True, no warm-up should be needed.

#### Actual Behavior

Does not warm up correctly

#### Potential Solution

Changing the resolution in Indicator.cs -> RelativeDailyVolume -> WarmUpindicator to a fixed Resolution of Resolution.Daily

#### Reproducing the Problem

Run C# or Python algorithm with EnableAutomaticIndicatorWarmUp set to True

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Remove the WarmUpPeriod Provider for the indicator in the meantime.
