### ISSUE TITLE
[TESTS] OneTimeSetUp: System.TypeInitializationException : The type initializer for 'Delegates' threw an exception.

### ISSUE THREAD

**Issue by IlshatGaripov** [QuantConnect/Lean#5837]
#### Reproducing the Problem
I am not able to run none of the tests within QuantConnect sln after rebased the branch to the latest master (after migration to NET5)
When I run any of unit tests I got an exception being thrown:

Message: 
    OneTimeSetUp: System.TypeInitializationException : The type initializer for 'Delegates' threw an exception.
      ----> System.MissingMethodException : Failed to load symbol PyDictProxy_New
      ----> System.ComponentModel.Win32Exception : The specified procedure could not be found.

![image](https://user-images.githubusercontent.com/37403501/128713758-564b88b8-19fe-4aae-a52c-1b430b9c17e4.png)

Debugging it further leads me down here 

![image](https://user-images.githubusercontent.com/37403501/128712990-c6c15a08-9fe0-42d7-b298-4e0c0e3cc489.png)

Please can anyone suggest a way around of this, it seems I fell little lost with this error, thanks!

#### System Information
Windows10, VisualStudio 2019, Version 16.10.4

#### Checklist

- [ ] I have completely filled out this template
- [ X] I have confirmed that this issue exists on the current `master` branch
- [ X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ X] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @IlshatGaripov!
Setting up pythonNet has changed since net5.0, believe you are missing to set `PYTHONNET_PYDLL` see https://github.com/QuantConnect/Lean/tree/master/Algorithm.Python

**Comment by IlshatGaripov** [comment]
Great, that worked! Thank you @Martin-Molinero
