### ISSUE TITLE
Installation on Mac/Linux

### ISSUE THREAD

**Issue by datatalking** [QuantConnect/Lean#5845]
#### Expected Behavior

1. install the VS code and have it run

#### Actual Behavior

1. VS code took 147 minutes to install
2. QuantConnect ran into immediate .NET bugs saying 114 programs needed to be installed... why do I need #F?
3. I've had to click "install" eight times so far for multiple screens of "packages"... why can't I just click "install" once?
4. 

#### Potential Solution

1. Make something that doesn't use a slow and buggy IDE.
2. Compile something out of modern software like java, or webbased solution

#### Reproducing the Problem

1. the problem is I'm working on almost three hours of waiting for VScode to install, why are we installing an IDE to run algorithmic trading platform. Why did you not compile something on its own? Why not make something out of Java or Webbased. .NET is not known for being stable nor computationally efficent.
2. Once VScode installs its another 40+ minutes of loading, updating, restarting. I feel like I'm backdooring the Pentagon.
3. I updated and installed all the packages it says to, then restarted VScode, tried updating it and no change. it doesn't run
4. It tells me my .NET is out of date... which is weird because its been updating and running now for over three hours. Why hasn't it updated .NET? 

#### System Information

3.2 GHz Quad-Core, 32 GB 1600 MHz DDR3, Catalina MacOs

`
Building QuantConnect.Lean.Launcher (Debug)
Build started 8/9/2021 4:39:53 PM.
__________________________________________________
Project "/Users/user_machine/sbox/test/Lean/Logging/QuantConnect.Logging.csproj" (Build target(s)):

Target GetReferenceAssemblyPaths:
    /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(1232,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v5.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK.
Done building target "GetReferenceAssemblyPaths" in project "QuantConnect.Logging.csproj" -- FAILED.

Done building project "QuantConnect.Logging.csproj" -- FAILED.

Build FAILED.

/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(1232,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v5.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK.
    0 Warning(s)
    1 Error(s)

Time Elapsed 03:14:01.36

========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Build: 1 error, 0 warnings`

**Comment by Martin-Molinero** [comment]
Hey @datatalking,

> VS code took 147 minutes to install
> Make something that doesn't use a slow and buggy IDE

This isn't related to lean, the IDE being used is up to the user. You don't even need an IDE if you don't want to use one.

> Why did you not compile something on its own?

From the issue description I suggest using https://www.quantconnect.com/ or maybe even https://github.com/QuantConnect/lean-cli for local development.

Hope it helps!

**Comment by datatalking** [comment]
I followed the instructions which clearly say to install the IDE for mac, which is VS code.

I downloaded it, installed it and got errors, how is this not releated to Lean... I tried to install it locally and it would not run.
