### ISSUE TITLE
Documentation Links 404

### ISSUE THREAD

**Issue by EmergentCybernetics** [QuantConnect/Lean#5854]
#### Expected Behavior
Documentation links to load.

#### Actual Behavior
Getting 404 or home page

#### Reproducing the Problem
Any links here are dead:
https://www.lean.io/docs/

For example:
https://www.lean.io/docs/key-concepts/developing-in-the-ide
https://www.lean.io/docs/algorithm-framework/overview
https://www.lean.io/tutorials
etc...

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment]
Hi @EmergentCybernetics,
These links are currently disabled because they will point to the docs v2 that are not available yet. For the current documentation, please visit https://www.quantconnect.com/docs.
