### ISSUE TITLE
Add option to turn off simulated option assignment

### ISSUE THREAD

**Issue by 0x0a11c0de** [QuantConnect/Lean#5857]
According to Jared Broad. QuantConnect [will not be adding SPX weeklies options data any time soon](https://www.quantconnect.com/forum/discussion/10199/optionchainprovider-and-weekly-options/p1/comment-31298). This makes backtesting strategies that use SPX weeklies impossible (unless you want to source your own data locally). A reasonable substitute is to backtest on SPY data instead.

However, because of the simulated option assignment, that is also impossible. SPX algorithms can assume no early assignment because SPX weeklies are European. The simulated option assignment makes those algorithms fail. Can we please get an option to turn off simulated option assignment so SPX traders have a way to backtest? It's not a perfect solution, but it's better than not being able to backtest our algorithms at all.

**Comment by Martin-Molinero** [comment]
Should be fixed by https://github.com/QuantConnect/Lean/pull/6697, also SPXW are available see https://github.com/QuantConnect/Lean/pull/6849

**Comment by Chocksy** [comment]
@Martin-Molinero how can we change the SPY option data though to act like a cash index SPX? That was the main thing here but i don't think the PRs fixed this they just expanded the SPX behaviour.
