### ISSUE TITLE
Make all historical data on crypto instruments available within online platform QC

### ISSUE THREAD

**Issue by IlshatGaripov** [QuantConnect/Lean#5861]
#### Expected Behavior
internal job that checks all currencies from available crypto exchanges and downloads historical data at the end of the day

#### Actual Behavior
Backtesting for many crypto pairs is not available in the online terminal

#### Potential Solution
Create a job that uploads historical data for all the crypto assets, that also makes sure existing pairs are still traded/quoted

#### Checklist

- [ ] I have completely filled out this template
- [ ] I have confirmed that this issue exists on the current `master` branch
- [ ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @IlshatGaripov!
Mind expanding which crypto pairs are missing for the supported markets? This is a data bug really, they should all be there 💯

**Comment by IlshatGaripov** [comment]
Hi @Martin-Molinero 
for example, take even the most common, from this list 
https://polygon.io/blog/consolidated-realtime-crypto-feed/
trying to run a strategy with **AddSecurity(SecurityType.Crypto, "BCHUSD", Resolution.Minute);**

returns an error in QC UI 
![image](https://user-images.githubusercontent.com/37403501/130773766-6ed31ec3-8b5c-45c8-88be-23e639c4f852.png)

The same is for DASH,
