### ISSUE TITLE
Exception running WIP Brokerage

### ISSUE THREAD

**Issue by FrankC01** [QuantConnect/Lean#5865]
#### Expected Behavior
That the shell Brokerage implementation we (@rterbush and I) are working on runs without error

#### Actual Behavior
Receive this exception
```C#
20210819 09:59:15.378 ERROR:: Engine.Run(): Error running algorithm System.ArgumentException: Brokerage must be of type BacktestingBrokerage for use wth the BacktestingTransactionHandler
   at QuantConnect.Lean.Engine.TransactionHandlers.BacktestingTransactionHandler.Initialize(IAlgorithm algorithm, IBrokerage brokerage, IResultHandler resultHandler) in /Users/frankc01/sb/Lean/Engine/TransactionHandlers/BacktestingTransactionHandler.cs:line 44
   at QuantConnect.Lean.Engine.Engine.Run(AlgorithmNodePacket job, AlgorithmManager manager, String assemblyPath, WorkerThread workerThread) in /Users/frankc01/sb/Lean/Engine/Engine.cs:line 300
```

#### Reproducing the Problem
This is coming from our Lean fork: https://github.com/SignalBuilders/Lean/tree/brokerage-5826-rithmic-exchange where I've defined the RithmicBrokerage and RithmicBrokerageFactory by trying to follow the (seems out of date and incomplete) https://www.quantconnect.com/tutorials/open-source/brokerage-development-guide

It builds fine `dotnet build` from root of Lean fork
I run with
```
cd sb/Lean/Launcher/bin/Debug
dotnet QuantConnect.Lean.Launcher.dll >> ~/leanout.log 2>&1
```

#### System Information
macos Big Sur

#### Checklist

- [x] I have completely filled out this template
- [ ] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by FrankC01** [comment]
Any input/support for this?

Thanks

**Comment by Martin-Molinero** [comment]
Hey @FrankC01! Have you tried using `"transaction-handler": "QuantConnect.Lean.Engine.TransactionHandlers.BrokerageTransactionHandler",`, suggest reviewing other brokerage configurations at https://github.com/QuantConnect/Lean/blob/master/Launcher/config.json#L193

**Comment by FrankC01** [comment]
I am using other implementation to reverse engineer how to implement a new brokerage. Here is my environment:
```json
    "live-rithmic": {
      "live-mode": true,
      // the rithmic brokerage requires the BrokerageTransactionHandler
      "live-mode-brokerage": "RithmicBrokerage",
      "data-queue-handler": "RithmicBrokerage",
      //"data-queue-handler": "QuantConnect.Lean.Engine.DataFeeds.Queues.LiveDataQueue",
      "setup-handler": "QuantConnect.Lean.Engine.Setup.BrokerageSetupHandler",
      "result-handler": "QuantConnect.Lean.Engine.Results.LiveTradingResultHandler",
      "data-feed-handler": "QuantConnect.Lean.Engine.DataFeeds.LiveTradingDataFeed",
      "real-time-handler": "QuantConnect.Lean.Engine.RealTime.LiveTradingRealTimeHandler",
      "transaction-handler": "QuantConnect.Lean.Engine.TransactionHandlers.BrokerageTransactionHandler"
    }
```

However; I still get `Error running algorithm System.ArgumentException: Brokerage must be of type BacktestingBrokerage`

**Comment by Martin-Molinero** [comment]
Hey @FrankC01, that error is only possible if you are using the `BacktestingTransactionHandler` see https://github.com/QuantConnect/Lean/blob/5d762d16b2ec7bd48fd766b772b0921862deda22/Engine/TransactionHandlers/BrokerageTransactionHandler.cs#L141 & https://github.com/QuantConnect/Lean/blob/5d762d16b2ec7bd48fd766b772b0921862deda22/Engine/TransactionHandlers/BacktestingTransactionHandler.cs#L44 . Closing for now since this isn't an issue in Lean, my guess is there must be something else wrong in your fork or environment

**Comment by FrankC01** [comment]
Hi @Martin-Molinero I appreciate that this is not a "bug" in Lean but more so issues with trying to develop a Broker.

Looking at the other implementations does not cover nuances like the TransactionHandlers.... and the [Broker Development](https://www.quantconnect.com/tutorials/open-source/brokerage-development-guide) documentation is woefully lacking in this regard.

Is there a better, up to date, resource I could benefit from?

**Comment by Martin-Molinero** [comment]
Hey @FrankC01!

>  Broker Development documentation is woefully lacking in this regard.

Sorry about that we are aware and will work on improving it shortly 👍

**Comment by FrankC01** [comment]
Hi @Martin-Molinero 

Will check out the latest as per your suggestion.

Happy to hear the docs are being worked on... any ETA on that?

Thanks
