### ISSUE TITLE
Runtime error live trading implementation with InteractiveBrokers: disconnection from api server

### ISSUE THREAD

**Issue by cub-** [QuantConnect/Lean#587]
Hello,

When I tried to deploy live with InteractiveBrokers, lean lost connection to api as soon as the algorithm started. IB threw "Not connected" error 504 . I'm running on Win8, TWS 957, ibController 3.2.0, lean engine v2.2.0.2

However, I can see lean did establish connection with TWS from the gui. Is it only a problem with TWS version 957? Also tested on Gateway 957 but unfortunately it threw the same error.

Log:
[Lean runtime error log.txt](https://github.com/QuantConnect/Lean/files/507485/Lean.runtime.error.log.txt)

Before I received "Divide by zero" error similar with this issue #177 so I commented out [https://github.com/QuantConnect/Lean/blob/master/Engine/AlgorithmManager.cs#L653](url) Since the connection was lost, the portfolio value = 0. 

Any thought is very appreciated, thanks.

**Comment by cub-** [comment]
divide by 0 issue fixed #586 thanks to @AlexCatarino

**Comment by michaelsrew** [comment]
can be closed...... :)

**Comment by jaredbroad** [comment]
Thanks :)
