### ISSUE TITLE
Bug with when calling SubscriptionDataSource for SubscriptionTransportMedium.Rest with headers

### ISSUE THREAD

**Issue by antoinedray** [QuantConnect/Lean#5883]
#### Expected Behavior

The header param in `SubscriptionDataSource` constructor is supported/functionning and has a Python-compatible typing.

A usage as such should thus work:

```python
class PrivateRESTDataReader(PythonData):

    def GetSource(self, config, date, isLiveMode: bool):
        tkn = os.getenv("TKN")
        iso_date = date.isoformat()
        source = "https://some_url.com"
        return SubscriptionDataSource(source, SubscriptionTransportMedium.Rest, 0, [{"Authorization": f"Bearer {tkn}"}])

    def Reader(self, config, line: str, date, isLiveMode: bool):
        # [...]
```

#### Actual Behavior

The lean engine exposes the following constructor for the `SubscriptionDataSource` which should allow users to create custom readers to make rest api calls to API with headers (useful to access private APIs secured with Bearer tokens for example).

The constructor is currently defined as follow (`.../site-packages/QuantConnect/Data/__init__.pyi`):

```python
class SubscriptionDataSource(System.Object, System.IEquatable[QuantConnect_Data_SubscriptionDataSource]):
    """Represents the source location and transport medium for a subscription"""

   # [...]

    @typing.overload
    def __init__(self, source: str, transportMedium: QuantConnect.SubscriptionTransportMedium, format: QuantConnect.Data.FileFormat, headers: System.Collections.Generic.IEnumerable[System.Collections.Generic.KeyValuePair[str, str]]) -> None:
        """
        Initializes a new instance of the SubscriptionDataSource class with SubscriptionTransportMedium.Rest
        including the specified header values
        
        :param source: The subscription's data source location
        :param transportMedium: The transport medium to be used to retrieve the subscription's data from the source
        :param format: The format of the data within the source
        :param headers: The headers to be used for this source
        """
        ...
```

In light of this constructor definition, my implementation of a custom data reader calling a Bearer token-secured API was the following:

```python
class PrivateRESTDataReader(PythonData):

    def GetSource(self, config, date, isLiveMode: bool):
        tkn = os.getenv("TKN")
        iso_date = date.isoformat()
        source = "https://some_url.com"
        return SubscriptionDataSource(source, SubscriptionTransportMedium.Rest, 0, [{"Authorization": f"Bearer {tkn}"}])

    def Reader(self, config, line: str, date, isLiveMode: bool):
        # [...]
```

Yet running my algorithm with such implementation gives me the following error:

```
20210827 18:55:49.836 ERROR:: <>c__DisplayClass1_0.<CreateAndScheduleWorker>b__0(): Subscription worker task exception ...
Python.Runtime.PythonException: TypeError : No constructor matches given arguments: (<class 'str'>, <class 'int'>, <class 'int'>, <class 'list'>)
  File "/LeanCLI/main.py", line 34, in GetSource
    return SubscriptionDataSource(source, SubscriptionTransportMedium.Rest, 0, [{"Authorization": f"Bearer {tkn}"}])
```

This error seems to derive from an incorrect typing of the header parameter defined in the constructor, yet it is unclear how only the typing gives this error.

#### Potential Solution

I am unsure but does changing the typing of the header parameter will fix the above error? Should a more Python-native typing should be used (a dict is more generally used as headers typing).

Is the header param in `SubscriptionDataSource` constructor is really supported?

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Thanks for the report @antoinedray! Seems to be a bug in pythonNet method resolution, we will fix it ASAP
