### ISSUE TITLE
Enable Override of OptionStrategyPositionGroupBuyingPowerModel in Portfolio.PositionGroups

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5888]
#### Expected Behavior
Be able to override `OptionStrategyPositionGroupBuyingPowerModel` in `Portfolio.PositionGroups` to disable buying power verification and let the brokerage refuse the order.

#### Actual Behavior
It's not possible to customize the buying power models of `Portfolio.PositionGroups`

#### Potential Solution
N/A

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Duplicate
