### ISSUE TITLE
Bybit Integrated Support

### ISSUE THREAD

**Issue by RowanHarley** [QuantConnect/Lean#5898]
I've noticed that while Binance, Okex and Bitfinex all have support with Lean, there seems to be nothing for Bybit. Is this in the pipeline, or would integration with Bybit at this stage prove too difficult a task? I would be more than happy to help integrate it once it's nothing too difficult.

**Comment by arodus** [comment]
Hi @jaredbroad, I would also be interested in the ByBit Brokerage and started working on it. Is there any more complete documentation than the one in the doc https://www.quantconnect.com/tutorials/open-source/brokerage-development-guide?

From what I've seen so far it also seems that not only the brokerage needs to be created but multiple changes in the core need to be made, for example adding the symbols and market hours or is there another way to do that from the brokerage?

Any help or additional doc from your side would be appreciated.

**Comment by wayneadams** [comment]
@arodus , did you pick this up?

**Comment by glaiveVII** [comment]
any updates @arodus ?

**Comment by symbion6** [comment]
Is there any news on this? Bybit is currently the #5 crypto exchange by volume, trading over 350 million a day. It's growing fast and I'm pretty sure there are more Bybit traders that would flock to QuantConnect when it's available to trade with.

Currently, the lack of this makes me move to another trading engine. That's pretty sad. Especially considering that I read in one of your support tickets that it takes about 80 hours to make it work.

Same goes for KuCoin. 

Kraken is nice to have...but the fees are rediculously high compared to ByBit and KuCoin.

Please make an effort to stay ahead of the game for crypto traders.

**Comment by arodus** [comment]
Hi folks, I've put this project aside until Bybit stabilizes its API and provides the features required. When I first started working on this project they just released the preview of v3 and now we're at v5 🙈 
I picked up this project again recently and finished major parts of the integration. There is some more work to do but I think it's possible to test it soon. I'd highly appreciate it if you could help testing and provide early feedback. 

**Until then it would be helpful to know what are the most important products in bybit for you:**
1️⃣ Spot
2️⃣ Perp Futures
3️⃣ Inverse Futures Perp&Contracts
4️⃣ Options

**Comment by symbion6** [comment]
That's great news. I'm mainly interested in the USDT perpetual contracts, the "linear" category in the v5 api.

**Comment by jaredbroad** [comment]
- Expanding to perps. @jhonabreul

**Comment by Martin-Molinero** [comment]
- Todo: Live wizard addition @gaviles
```
	"bybit-api-secret"
	"bybit-api-key"
	"bybit-api-url"
		"https://api.bybit.com"
		[PAPER] "https://api-testnet.bybit.com" 
	"bybit-websocket-url"
		"wss://stream.bybit.com"
		[PAPER] "wss://stream-testnet.bybit.com"
	"bybit-vip-level"
		"VIP0",
		"VIP1",
		"VIP2",
		"VIP3",
		"VIP4",
		"VIP5",
		"SupremeVIP",
		"Pro1",
		"Pro2",
		"Pro3",
		"Pro4",
		"Pro5"
	"live-holdings"
```

**Comment by Martin-Molinero** [comment]
Bybit is now available both in the QC cloud and through the CLI. We've implemented  crypto margin & cash spot trading, USDT perpetual futures.
Pending:
- USD perpetual futures (inverse), WIP at https://github.com/QuantConnect/Lean.Brokerages.ByBit/pull/6
- USDC perp futures
- Expiring (non perp) futures


Special thanks to @arodus for his contributions

**Comment by jaredbroad** [comment]
Thank you @arodus 🙏 Huge contribution
