### ISSUE TITLE
I can't find the tutorial of LEAN.

### ISSUE THREAD

**Issue by 630362055** [QuantConnect/Lean#5910]
![image](https://user-images.githubusercontent.com/25970108/132426146-51b0edb2-8d43-4f85-a61e-efc97092b26e.png)
Can anyone give me some links to learn how to use LEAN? Thanks a lot!

**Comment by Martin-Molinero** [comment]
Hey @630362055!
Have you taken a look at https://www.lean.io/docs/lean-cli/tutorials/installation/installing-pip suggest reviewing these too https://www.youtube.com/playlist?list=PLD7-B3LE6mz61Hojce6gKshv5-7Qo4y0r. Docs are WIP, for installing Lean repo itself, and building manually etc, check out https://github.com/QuantConnect/Lean#installation-instructions please.
Hope these cover what you are looking for!
