### ISSUE TITLE
What's the difference between Lean and Lean CLI

### ISSUE THREAD

**Issue by 630362055** [QuantConnect/Lean#5911]
I have tried my best to install Lean locally but failed. My anaconda is python 3.8.8 and I created a virtual env with Python 3.6.8 which is used for Lean. And I add the virtual env path to the system env variable. When I run C# algo in VS, It works correctly. But when I run the python algo, failed with error
`20210908 21:05:15.800 ERROR:: Loader.TryCreatePythonAlgorithm():  System.TypeInitializationException: The type initializer for 'Delegates' threw an exception.
 ---> System.MissingMethodException: Failed to load symbol PyDictProxy_New
 ---> System.ComponentModel.Win32Exception (127): 找不到指定的程序。
   --- End of inner exception stack trace ---
   at Python.Runtime.Platform.WindowsLoader.GetFunction(IntPtr hModule, String procedureName)
   at Python.Runtime.Runtime.Delegates.GetFunctionByName(String functionName, IntPtr libraryHandle)
   at Python.Runtime.Runtime.Delegates..cctor()
   --- End of inner exception stack trace ---
   at Python.Runtime.Runtime.Delegates.get_Py_IsInitialized()
   at Python.Runtime.Runtime.Py_IsInitialized()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs, ShutdownMode mode)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs, ShutdownMode mode)
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs, ShutdownMode mode)
   at Python.Runtime.PythonEngine.Initialize()
   at QuantConnect.Python.PythonInitializer.Initialize() in C:\Users\63036\Desktop\LEAN\Lean-master\Common\Python\PythonInitializer.cs:line 45
   at QuantConnect.AlgorithmFactory.Loader.TryCreatePythonAlgorithm(String assemblyPath, IAlgorithm& algorithmInstance, String& errorMessage) in C:\Users\63036\Desktop\LEAN\Lean-master\AlgorithmFactory\Loader.cs:line 171
20210908 21:05:15.826 ERROR:: Engine.Run():  QuantConnect.Lean.Engine.Setup.AlgorithmSetupException: During the algorithm initialization, the following exception has occurred: Loader.TryCreatePythonAlgorithm(): Unable to import python module ../../../Algorithm.Python/BasicTemplateFrameworkAlgorithm.py. The type initializer for 'Delegates' threw an exception.
   at QuantConnect.Lean.Engine.Setup.BacktestingSetupHandler.CreateAlgorithmInstance(AlgorithmNodePacket algorithmNodePacket, String assemblyPath) in C:\Users\63036\Desktop\LEAN\Lean-master\Engine\Setup\BacktestingSetupHandler.cs:line 104
   at QuantConnect.Lean.Engine.Engine.Run(AlgorithmNodePacket job, AlgorithmManager manager, String assemblyPath, WorkerThread workerThread) in C:\Users\63036\Desktop\LEAN\Lean-master\Engine\Engine.cs:line 116
20210908 21:05:15.827 TRACE:: JOB HANDLERS:
20210908 21:05:15.827 TRACE::          DataFeed:     QuantConnect.Lean.Engine.DataFeeds.FileSystemDataFeed
20210908 21:05:15.828 TRACE::          Setup:        QuantConnect.Lean.Engine.Setup.ConsoleSetupHandler
20210908 21:05:15.828 TRACE::          RealTime:     QuantConnect.Lean.Engine.RealTime.BacktestingRealTimeHandler
20210908 21:05:15.828 TRACE::          Results:      QuantConnect.Lean.Engine.Results.BacktestingResultHandler
20210908 21:05:15.829 TRACE::          Transactions: QuantConnect.Lean.Engine.TransactionHandlers.BacktestingTransactionHandler
20210908 21:05:15.829 TRACE::          Alpha:        QuantConnect.Lean.Engine.Alphas.DefaultAlphaHandler
20210908 21:05:15.829 TRACE::          ObjectStore:  QuantConnect.Lean.Engine.Storage.LocalObjectStore
20210908 21:05:15.830 TRACE:: DefaultAlphaHandler.Exit(): Exiting...
20210908 21:05:15.831 TRACE:: DefaultAlphaHandler.Exit(): Ended
20210908 21:05:15.831 TRACE:: BacktestingResultHandler.Exit(): starting...
20210908 21:05:15.832 TRACE:: BacktestingResultHandler.Exit(): Saving logs...
20210908 21:05:15.834 TRACE:: StopSafely(): waiting for 'Result Thread' thread to stop...
20210908 21:05:15.836 ERROR:: Algorithm.Initialize() Error: During the algorithm initialization, the following exception has occurred: Loader.TryCreatePythonAlgorithm(): Unable to import python module ../../../Algorithm.Python/BasicTemplateFrameworkAlgorithm.py. The type initializer for 'Delegates' threw an exception. Stack Trace: During the algorithm initialization, the following exception has occurred: Loader.TryCreatePythonAlgorithm(): Unable to import python module ../../../Algorithm.Python/BasicTemplateFrameworkAlgorithm.py. The type initializer for 'Delegates' threw an exception.
 During the algorithm initialization, the following exception has occurred: Loader.TryCreatePythonAlgorithm(): Unable to import python module ../../../Algorithm.Python/BasicTemplateFrameworkAlgorithm.py. The type initializer for 'Delegates' threw an exception.
20210908 21:05:15.837 TRACE:: Debug: Your log was successfully created and can be retrieved from: C:\Users\63036\Desktop\LEAN\Lean-master\Launcher\bin\Debug\BasicTemplateFrameworkAlgorithm-log.txt
20210908 21:05:15.837 TRACE:: BacktestingResultHandler.Run(): Ending Thread...
20210908 21:05:15.948 TRACE:: Config.GetValue(): regression-update-statistics - Using default value: False
20210908 21:05:15.951 TRACE::
STATISTICS:: Fitness Score 0
STATISTICS:: Kelly Criterion Estimate 0
STATISTICS:: Kelly Criterion Probability Value 0
STATISTICS:: Sortino Ratio 0
STATISTICS:: Return Over Maximum Drawdown 0
STATISTICS:: Portfolio Turnover 0
STATISTICS:: Total Insights Generated 0
STATISTICS:: Total Insights Closed 0
STATISTICS:: Total Insights Analysis Completed 0
STATISTICS:: Long Insight Count 0
STATISTICS:: Short Insight Count 0
STATISTICS:: Long/Short Ratio 100%
STATISTICS:: Estimated Monthly Alpha Value $0
STATISTICS:: Total Accumulated Estimated Alpha Value $0
STATISTICS:: Mean Population Estimated Insight Value $0
STATISTICS:: Mean Population Direction 0%
STATISTICS:: Mean Population Magnitude 0%
STATISTICS:: Rolling Averaged Population Direction 0%
STATISTICS:: Rolling Averaged Population Magnitude 0%
STATISTICS:: OrderListHash d41d8cd98f00b204e9800998ecf8427e
20210908 21:05:15.952 TRACE:: BacktestingResultHandler.SendAnalysisResult(): Processed final packet
20210908 21:05:15.953 TRACE:: Engine.Run(): Disposing of setup handler...
20210908 21:05:15.953 TRACE:: Engine.Main(): Analysis Completed and Results Posted.
Engine.Main(): Analysis Complete.
20210908 21:05:15.954 TRACE:: Config.GetValue(): close-automatically - Using default value: False
Engine.Main(): Press any key to continue.`

Or another error (no module encodings)
I don't want to uninstall the anaconda, because the base env is important for me(work env).
So I give up run Lean locally and want to use Lean CLI instead.
Is there any big difference between these?
Is there something Lean can do but Lean CLI can't?

**Comment by jmerle** [comment]
I'll copy the [comment](https://www.quantconnect.com/forum/discussion/12305/what-039-s-the-difference-between-lean-and-lean-cli/p1/comment-36159) I just posted to the same question on the forums:

LEAN is the algorithmic trading engine, the CLI is the recommended way to run it locally. You can find a list of the CLI's features on [GitHub](https://github.com/QuantConnect/lean-cli#highlights), as well as in its [documentation](https://www.lean.io/docs/lean-cli/getting-started/lean-cli).

The only thing that comes to mind that is in LEAN that is not available in the CLI at the moment are many of the programs in the [ToolBox](https://github.com/QuantConnect/Lean/blob/master/ToolBox/README.md) project. The random data generator in there is already exposed through the [`lean data generate`](https://www.lean.io/docs/lean-cli/tutorials/local-data/generating-random-data) command, but if you need any of the other programs in there you'll have to run LEAN manually and move the downloaded/parsed data to the CLI's data directory.
