### ISSUE TITLE
Can Lean download data locally from quantconnect?

### ISSUE THREAD

**Issue by 630362055** [QuantConnect/Lean#5914]
There are many data download tools in toolbox. Can these tools be used to download data from quantconnect?

**Comment by 630362055** [comment]
Toolbox is good, I downloaded the data from binance, but the kline data just includes ohlcv, there is more information in binance rest API like usdt volume or buy taker volume. My English is not good, sorry.
`[
    [
        1499040000000,      # Open time
        "0.01634790",       # Open
        "0.80000000",       # High
        "0.01575800",       # Low
        "0.01577100",       # Close
        "148976.11427815",  # Volume
        1499644799999,      # Close time
        "2434.19055334",    # Quote asset volume
        308,                # Number of trades
        "1756.87402397",    # Taker buy base asset volume
        "28.46694368",      # Taker buy quote asset volume
        "17928899.62484339" # Can be ignored
    ]
]`

**Comment by 630362055** [comment]
![image](https://user-images.githubusercontent.com/25970108/132616501-f4d8cf94-4a7e-4d0d-b7f6-64d1e81984a5.png)

**Comment by 630362055** [comment]
Is there a good way to download all the symbols?
![image](https://user-images.githubusercontent.com/25970108/132616889-acf53e1f-5920-4f55-a02b-525760ed4785.png)
Rather than type every symbol to the cmd. Write a python program to do this?

**Comment by 630362055** [comment]
Or Is there any way when running strategy it automatically downloads the data that the strategy need

**Comment by Martin-Molinero** [comment]
> Or Is there any way when running strategy it automatically downloads the data that the strategy need

Hey! yes, you can use the `ApiDataProvide`r, and download the data on the fly from QC.com (with a fee). Can setup this manually or using the CLI (plenty of docs and videos for this last one 👌) 

> Is there a good way to download all the symbols?
> Rather than type every symbol to the cmd. Write a python program to do this?

Think you can provide a list of symbols?
