### ISSUE TITLE
Datadownload toolbox error

### ISSUE THREAD

**Issue by 630362055** [QuantConnect/Lean#5915]
`C:\Users\63036\Desktop\LEAN\Lean-master\ToolBox\bin\Debug>QuantConnect.ToolBox.exe --app=MBXDL --from-date=20210301-00:00:00 --tickers=ADAUSDT --resolution=Minute
20210909 04:20:56.822 TRACE:: Config.GetValue(): debug-mode - Using default value: False
20210909 04:20:56.822 TRACE:: Config.Get(): Configuration key not found. Key: results-destination-folder - Using default value:
20210909 04:20:56.823 TRACE:: Config.Get(): Configuration key not found. Key: plugin-directory - Using default value:
20210909 04:20:56.825 TRACE:: Config.Get(): Configuration key not found. Key: composer-dll-directory - Using default value:
20210909 04:20:56.838 TRACE:: Composer(): Loading Assemblies from C:\Users\63036\Desktop\LEAN\Lean-master\ToolBox\bin\Debug\
20210909 04:20:56.867 TRACE:: Config.Get(): Configuration key not found. Key: log-handler - Using default value: CompositeLogHandler
20210909 04:20:56.897 TRACE:: Config.Get(): Configuration key not found. Key: data-directory - Using default value: ../../../Data/
20210909 04:20:56.898 TRACE:: Config.Get(): Configuration key not found. Key: version-id - Using default value:
20210909 04:20:56.898 TRACE:: Config.Get(): Configuration key not found. Key: cache-location - Using default value: ../../../Data/
20210909 04:20:56.916 TRACE:: Config.Get(): Configuration key not found. Key: map-file-provider - Using default value: LocalDiskMapFileProvider
20210909 04:20:56.923 TRACE:: Config.Get(): Configuration key not found. Key: binance-api-url - Using default value: https://api.binance.com
20210909 04:20:56.923 TRACE:: Config.Get(): Configuration key not found. Key: binance-websocket-url - Using default value: wss://stream.binance.com:9443/ws
20210909 04:20:56.929 TRACE:: Config.GetValue(): binance-maximum-websocket-connections - Using default value: 0
20210909 04:20:56.931 TRACE:: BrokerageMultiWebSocketSubscriptionManager(): WebSocket connections will be restarted every: 23:45:00
20210909 04:24:14.636 ERROR:: BinanceDownloaderProgram.DataDownloader():  System.Exception: BinanceBrokerage.GetHistory: request failed: [0] , Content: , ErrorMessage: An error occurred while sending the request.
   at QuantConnect.Brokerages.Binance.BinanceRestApiClient.GetHistory(HistoryRequest request)+MoveNext() in C:\Users\63036\Desktop\LEAN\Lean-master\Brokerages\Binance\BinanceRestApiClient.cs:line 316
   at QuantConnect.Brokerages.Binance.BinanceBrokerage.GetHistory(HistoryRequest request)+MoveNext() in C:\Users\63036\Desktop\LEAN\Lean-master\Brokerages\Binance\BinanceBrokerage.cs:line 319
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at QuantConnect.ToolBox.BinanceDownloader.BinanceDownloaderProgram.DataDownloader(IList`1 tickers, String resolution, DateTime fromDate, DateTime toDate) in C:\Users\63036\Desktop\LEAN\Lean-master\ToolBox\BinanceDownloader\BinanceDownloaderProgram.cs:line 57`

**Comment by 630362055** [comment]
![image](https://user-images.githubusercontent.com/25970108/132622479-f1f48a4d-2a82-481b-ad6b-11f8613d9428.png)

**Comment by 630362055** [comment]
![image](https://user-images.githubusercontent.com/25970108/132622608-d34d0dd3-512b-4c3c-bb01-714a2e7951dc.png)

**Comment by Martin-Molinero** [comment]
Hey! From the last image it looks like you were able to solve it?
