### ISSUE TITLE
Library Request SharpLearning.XGBoost + Upgrade ML.Net

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5916]
#### Expected Behavior
Supports SharpLearning.XGBoost
Updade ML.Net to the latest version.

#### Actual Behavior
Does not support SharpLearning.XGBoost. It is available in a separate nuget package, so we didn't get it when we added `SharpLearning` with #5536.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by craigp318** [comment]
This library would be very helpful (or an alternative C# xgb library). 

How does one get prioritization for this request?
