### ISSUE TITLE
differet backtest speed between LEAN and LEAN CLI

### ISSUE THREAD

**Issue by 630362055** [QuantConnect/Lean#5917]
LEAN CLI C#  84k /s
![image](https://user-images.githubusercontent.com/25970108/132738159-f2ec8012-4473-4898-8f82-867855a3b74d.png)

LEAN CLI PYTHON 59k /s
![image](https://user-images.githubusercontent.com/25970108/132738264-1d8f2e29-0de4-4d1e-a8b8-acde355a68b8.png)

LEAN with visual studio 2019 18k/s and the backtest result is different
![image](https://user-images.githubusercontent.com/25970108/132738427-cb90f273-948a-4bde-8c48-922603960881.png)

How to speed up local LEAN backtesting

**Comment by 630362055** [comment]
It's much better when i use the cmd to run the QuantConnect.Lean.Laucher.exe
![image](https://user-images.githubusercontent.com/25970108/132812540-2370fe7c-d6c5-4908-9913-f6bfdf91d9d0.png)
But the backtest result is a little different compared with the result using LEAN CLI

**Comment by 630362055** [comment]
When using release with visual studio and run in cmd, The speed has become faster
![image](https://user-images.githubusercontent.com/25970108/132817534-16b58959-ac34-4503-a5af-8ab9149e2100.png)

**Comment by Martin-Molinero** [comment]
> When using release with visual studio and run in cmd, The speed has become faster

Yeah! that was probably it 💯
