### ISSUE TITLE
Does Lean work better on Windows？

### ISSUE THREAD

**Issue by 630362055** [QuantConnect/Lean#5928]
When I run lean locally on ubuntu, the backtest speed is lower than that of the Lean CLI. Is this true？

**Comment by Martin-Molinero** [comment]
Hey @630362055!
The Lean CLI is running the lean images see https://github.com/QuantConnect/Lean/blob/master/Dockerfile base image is ubuntu focal currently. Performance is a tricky subject, _many_ factors can affect, that being said there should not be any significant different between local ubuntu and the CLI
