### ISSUE TITLE
Library data request: adding lemmatizers for NLP libraries

### ISSUE THREAD

**Issue by LouisSzeto** [QuantConnect/Lean#5939]
#### Expected Behavior
N/A

#### Actual Behavior
Lemmatizers from WordNet@NLTK, spaCy, Pattern@GenSim are not accessible, although these libraries are supported. This hinders the development of NLP within LEAN environment.

#### Potential Solution
Download the additional data from the libraries and store them in LEAN for access.
```
# WordNet@NLTK
import nltk
nltk.download("wordnet")

# spaCy
python -m spacy download en
```
Add support to Pattern library

#### Reproducing the Problem
```
# WordNet@NLTK
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()      # no downloaded data package "wordnet"
lemmatizer.lemmatize("XXXXX")

# Parallel@GenSim
import gensim
gensim.utils.lemmatize("XXXXX")            # no library support "Pattern"

# spaCy
import spacy
nlp = spacy.load('en')         # no downloaded data package "en"
doc = nlp(u"XXXXX")
for token in doc:
    token.lemma
```

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
> Pattern@GenSim

Pattern only supports python 3.6 https://github.com/clips/pattern

**Comment by Martin-Molinero** [comment]
> import spacy
> nlp = spacy.load('en')

It's no longer 'en' but `en_core_web_md or en_core_web_sm`
