### ISSUE TITLE
Binance live algorithm in paper account will not warmup indicators (so never ready)

### ISSUE THREAD

**Issue by voidale** [QuantConnect/Lean#5941]
#### Expected Behavior
I expect the indicators for Binance broker: Paper-trading in live trading to be ready

#### Actual Behavior
It's never ready and seems like it uses live data to warm up so it gonna take forever

#### Reproducing the Problem
Any algorithm in live mode with paper broker, all indicators are not ready (no warmup).

#### System Information
Quantconnect

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @voidale!
Is warmup enabled? An algorithm reproducing the issue and the logs are needed for these kind of issues.

Warmup is drive by a history request to the brokerage, it could potentially be that the requested history configuration is not supported by the brokerage or if they failed for some reason (see https://github.com/QuantConnect/Lean/blob/master/Brokerages/Binance/BinanceBrokerage.cs#L303), these should be seen in the logs

**Comment by voidale** [comment]
@Martin-Molinero I've debugged it there are no logs or issues, it's just false (IsReady()) but it shouldn't be because in backtest it runs fine, and live is keep on console log not ready for hours... I think that should be obvious it doesn't work. The same algorithm runs fine with Bitfinex as a broker (no changes).
