### ISSUE TITLE
Unusual performance drop when using consolidators with python

### ISSUE THREAD

**Issue by ArthurAsenheimer** [QuantConnect/Lean#5955]
#### Expected Behavior

Indicator updates using user-defined consolidators are executed at similar speed as automatic updates using RegisterIndicator.

#### Actual Behavior

User-defined consolidators results in a performance drop of ~70% despite identical workload.

#### Potential Solution

Review python wrapper for consolidators.

#### Reproducing the Problem

Original report: https://www.quantconnect.com/forum/discussion/12399/tradebarconsolidator-causes-big-performance-drop/p1

Python version: 
```Python
class PyConsolidatorSpeedTest(QCAlgorithm):

    def Initialize(self):
        self.SetStartDate(2010, 1, 1)  
        self.SetEndDate(2020, 1, 1)
        self.SetCash(100000) 
        
        spy = self.AddEquity("SPY", Resolution.Minute).Symbol
        self.sma = SimpleMovingAverage(100)
        
        selectUserDefinedConsolidator = True
        
        if selectUserDefinedConsolidator:
            consolidator = TradeBarConsolidator(1)
            consolidator.DataConsolidated += self.OnDataConsolidated
            self.SubscriptionManager.AddConsolidator(spy, consolidator)
        else:
            self.RegisterIndicator(spy, self.sma, Resolution.Minute)
            
        
    def OnDataConsolidated(self, sender, bar):
        self.sma.Update(bar.EndTime, bar.Close)
        

    def OnData(self, data):
        if not self.Portfolio.Invested and self.sma.IsReady:
            self.SetHoldings("SPY", 1)
```

#### Results

with RegisterIndicator (i.e. `selectUserDefinedConsolidator = False`):
![image](https://user-images.githubusercontent.com/68070194/135417355-558a8ddc-4de2-4ba5-b42c-0224f341c300.png)

with user-defined consolidator (i.e. `selectUserDefinedConsolidator = True`):
![image](https://user-images.githubusercontent.com/68070194/135417310-69a9c768-2661-4219-bdc9-9a6b783829c8.png)

C# version:

```C#
namespace QuantConnect.Algorithm.CSharp
{
    public class UpgradedAsparagusParrot : QCAlgorithm
    {
    	private SimpleMovingAverage _sma;

        public override void Initialize()
        {
            SetStartDate(2010,1,1);
            SetEndDate(2020,1,1);
            SetCash(100000);     
            
			var spy = AddEquity("SPY", Resolution.Minute).Symbol;
            _sma = new SimpleMovingAverage(100);
            
            bool selectUserDefinedConsolidator = true;
            
            if (selectUserDefinedConsolidator)
            {
            	var consolidator = new TradeBarConsolidator(TimeSpan.FromMinutes(1));
            	consolidator.DataConsolidated += OnDataConsolidated;
            	SubscriptionManager.AddConsolidator(spy, consolidator);
            }
            else
            {
            	RegisterIndicator(spy, _sma, Resolution.Minute);
            }
        }
        
        private void OnDataConsolidated(object sender, TradeBar bar)
        {
        	_sma.Update(bar.EndTime, bar.Close);
        }

  
        public override void OnData(Slice data)
        {
            if (!Portfolio.Invested && _sma.IsReady)
            {
                SetHoldings("SPY", 1);
            }
        }

    }
}
```

#### Results

with RegisterIndicator (i.e. `selectUserDefinedConsolidator = false`):
![image](https://user-images.githubusercontent.com/68070194/135417564-787f784b-f2d9-4f45-9343-d56a7cfedba5.png)

with user-defined consolidator (i.e. `selectUserDefinedConsolidator = true`):
![image](https://user-images.githubusercontent.com/68070194/135418199-ea5ccf0f-20c2-4b13-b14b-c6fc0fb630d5.png)

<br />

#### Questions
Are the numbers above in the range of your expectations? To me, the performance drop of about 70% does seem large. Do you see any way to speed up consolidators for Python and bring it a bit closer to C# speed?  

<br />
<br />

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
The remaining difference is likely the callbacks and triggering in python. No further work planned.
