### ISSUE TITLE
Library request: OR-Tools - Google Optimization Tools

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5959]
#### Expected Behavior
Supports Google Optimization Tools (a.k.a., [OR-Tools](https://github.com/google/or-tools)) is an open-source, fast and portable software suite for solving combinatorial optimization problems.

It's available for both Python and C#.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
C# `Google.OrTools` has been added to QC cloud
