### ISSUE TITLE
Cannot Create Report with Futures

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5961]
#### Expected Behavior
Be able to generate a report from a backtest that trades futures.

#### Actual Behavior
The following exception is thrown:
```
'Unable to locate exchange hours for Future-ice-QC-UNIVERSE-USERDEFINED-ICE-FUTURE'
```

#### Reproducing the Problem
Run the Report using the following file [5ac74121a862e65e71fcaddd66d8edec.json](https://www.dropbox.com/s/qk8tm99zj9jp97s/5ac74121a862e65e71fcaddd66d8edec.json?dl=1) generated at QuantConnect Cloud. 

Note.: I generated another file with a B&H SPY algorithm, and I could generate the report locally. 

#### System Information
QuantConnect Cloud (the report request does generate a report) and locally.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jhonabreul** [comment]
This has already been fixed at some point. Generated reports with the linked json file as well as with other algorithms trading futures without issues.

Example:
- [JSON file](https://github.com/QuantConnect/Lean/files/9427304/e69e1374597977512dfec6475553d4d4.zip)
- [Generated report](https://github.com/QuantConnect/Lean/files/9427307/Report.zip)
