### ISSUE TITLE
Invalid Syntax Unknown Error

### ISSUE THREAD

**Issue by kerrca** [QuantConnect/Lean#5973]
Hello, I am currently experiencing a syntax error on these lines of code

if len(otm_puts) > 0:
        contract = sorted(sorted(otm_puts, key = lambda x: abs((x.ID.Date = self.Time).days - self.DTE)),
                                            key = lambda x: self.underlyingPrice - X.ID.StrikePrice)[0]

  I am currently new to quant connect and am therefore unable to spot the error in my syntax. Help would be much appreciated. TY! TY!

Rest of Code if Relevant

from datetime import timedelta
from QuantConnect.Data.Custom.CBOE import *
class TransdimensionalModulatedProcessor(QCAlgorithm):
    def Initialize(self):
        self.SetStartDate(2020, 10, 1)
        self.SetEndDate(2021, 10, 1)
        self.SetCash(100000)
        self.equity = self.AddEquity("SPY", Resolution.Minute)
        self.equity.SetDataNormalizationModa(DataNormalizationMode.Raw)
        self.vix = self.AddData(CBOE, "VIX").Symbol
        self.rank = 0
        self.contract = str()
        self.contractadded = set()
        self.DaysBeforeExp = 2
        self.DTE = 25
        self.OTM= 0.01
        self.loopbackIV = 150
        self.IVlvl = 0.5
        self.percentage = 0.9
        self.options_alloc = 90
        self.Scheduel.On(self.DataRules.EveryDay(self.symbol), \
                self.TimeRules.AfterMarketOpen(self, symbol, 30), \
                self.Plotting)
        self.Schedule.ON(self.DataRules.Everyday(self,symbol), \
                self.TimeRules.AfterMarketOpen(self, symbol, 30), \
                self.VIXRank)
        self.SetWarmup(timedelta(self.loopbackIV))
        
        
    def VIXRank(self):
        history = self.History(CBOE, self.vix, self.loopbackIV, Resolution.Daily)
        self.rank = ((self.Securities[self.vix].Price - min(history[:-1]["low"])) / (max(hisory[:-1]["high"]) - min(history[:-1]["low"])))
    def OnData(self, data):
        if self.IsWarmingUp:
            return
    
    if not self.Portfolio[self.symbol].Invested:
        self.SetHoldings(self.symbol, self.percentage)
        
    if self.rank > self.IVlvl:
        self.Buyput(data)
    
    if self.contract:
        if(self.contract.ID.Date - self.Time) <= timedelta(self.DayBeforeExp):
            self.Liquidate(self.contract)
            self.Log("closed; too close to expiration")
            self.contract = str()
            
def BuyPut(self, data):
    if self.contract == str():
        self.contract = self.OptionsFilter(data)
        return
    elif not self.Portfolio[self.contract].Invested and data.ContainsKey(self.contract):
        self.Buy(self.contract, round(self.Portfolio[self.symbol].Quantity / self.options_alloc))
        
def OptionsFilter(self, data):
    contracts = self.OptionChainProvider.GetOptionContractList(self,symbol, data.Time)
    self.underlyingPrice = self.Securities[self.symbol].Price
    otm_puts = [i for i in contracts if i.ID.OptionRight == OptionRight.put and
                                        self.underlyingPrice - i.ID.Strikeprice > self.OTM * self.underlyingPrice and   
                                        self.DTE - 8 < (i.ID.Data - date.Time).days < self.DTE + 8]
                                        
    if len(otm_puts) > 0:
        contract = sorted(sorted(otm_puts, key = lambda x: abs((x.ID.Date = self.Time).days - self.DTE))),
                                            key = lambda x: self.underlyingPrice - X.ID.StrikePrice)[0]
    if contract not in self.contractsAdded:
            self.contractsAdded.add(contract)
            self.AddOptionContract(contract, Resolution.Minute)
        return contract
    else:
        return str()
        
def Plotting(self):
    self.Plot("Vol Chart", "Rank", self.rank)
    self.Plot("vol Chart", "lvl", self.IVlvl)
    self.Plot("Data Chart", self.symbol, self.Securities[self.symbol].close)
    
    option_invested = [x.Key for x in self.Portfolio if X.Value.Invested and X.Value.Type == SecurityType.Option]
    if option_invested:
        self.Plot("Data Chart", "Strike", option_invested[0].ID.StrikePrice)
        
def OnOrderEvent(self, orderEvent):
    self.Log(str(orderEvent))

**Comment by Martin-Molinero** [comment]
Hey @kerrca!

Suggest splitting that line into multiple operations to find the issue. Please post these type of issues in [qc.com/forums](https://www.quantconnect.com/forum) 

Maybe:
```python
        pepe = sorted(otm_puts, key = lambda x: abs(x.ID.Date = self.Time).days - self.DTE)
        contract = sorted(pepe, key = lambda x: self.underlyingPrice - X.ID.StrikePrice[0])
```

> from QuantConnect.Data.Custom.CBOE import *

There shouldn't be a need to import CBOE, can remove this line 👍, it's moved now to `QuantConnect.DataSource` which is imported automatically, see https://github.com/QuantConnect/Lean.DataSource.CBOE/blob/master/CBOE.cs
