### ISSUE TITLE
Ability to specify failure handler for live algorithms

### ISSUE THREAD

**Issue by basicmatrix** [QuantConnect/Lean#598]
When a live running algorithm fails because of a critical error, the algorithm is immediately stopped without liquidating positions and an email notification is sent. I propose adding the ability to create handler functions for these situations that allow the algorithm to be restarted, execute some code, or at the very least liquidate positions based on conditional criteria.

In my case, the failure happens because of a bug in a history function that I have no control over, but will hopefully be fixed soon. These types of failures have the potential to cause serious issues for short term trades leaving investments in the market unintentionally. Adding failure / recovery functionality would help to mitigate the issues for critical algorithms trading on the second.

**Comment by jaredbroad** [comment]
Implemented as OnEndOfAlgorithm(); any orders are placed with best effort approach but cannot be guaranteed due to broker disconnections etc.
