### ISSUE TITLE
StopLimit order StopTriggered flag not being set from brokerage

### ISSUE THREAD

**Issue by AdalyatNazirov** [QuantConnect/Lean#5982]
#### Expected Behavior

Allow changing `StopTriggered` via `OrderEvent`

#### Actual Behavior

Currently `StopTriggered` property is internal so cannot be updated from external projects directly, including new brokerages.

#### Potential Solution

N/A

#### Reproducing the Problem

Submit `StopLimit` order

#### System Information

N/A

#### Checklist

- [ ] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Duplicate of  https://github.com/QuantConnect/Lean/issues/4285
