### ISSUE TITLE
Library request: Microsoft.Data.Analysis

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5993]
#### Expected Behavior
Supports [Microsoft.Data.Analysis](https://www.nuget.org/packages/Microsoft.Data.Analysis/). This package contains easy-to-use and high-performance libraries for data analysis and transformation, such as [DataFrame](https://devblogs.microsoft.com/dotnet/an-introduction-to-dataframe/).

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by omidkrad** [comment]
Can `Microsoft.Data.Analysis` namespace be whitelisted, please?

**Comment by Martin-Molinero** [comment]
`Microsoft.Data.Analysis 0.19.1` has been added to QC cloud

**Comment by omidkrad** [comment]
Great. Also need to add it to the docs:
- https://www.quantconnect.com/docs/v2/lean-cli/projects/libraries/third-party-libraries
- https://www.quantconnect.com/docs/v2/local-platform/development-environment/packages-and-libraries
- https://www.quantconnect.com/docs/v2/writing-algorithms/key-concepts/libraries
