### ISSUE TITLE
[Feature] Create MFI Indicator

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#6]
Create an "MoneyFlowIndex" indicator class and the associated "MFI" helper method in the QCAlgorithm base class. See introduction to indicators - https://lean.quantconnect.com/docs#topic9.html

Add the associated tests to Tests project under /Indicators to confirm the Money Flow Index values match up with the data provided in Tests/TestData/spy_mfi.txt file.

**Comment by mattmast** [comment]
Now that I got the CCI done, I'm start working on this one.

**Comment by jaredbroad** [comment]
Legend @mattmast! The CCI looks great! We're going to deploy to beta today and run some tests and then push CCI live Monday :)

**Comment by mattmast** [comment]
I'm am starting to test out the MFI indicator and noticed through some debugging the factor files.  I was wondering what is the purpose of the factor files in the Data directory?

**Comment by jaredbroad** [comment]
Over time stocks sometimes split, and pay dividends to the equity holders. There are two ways of modelling this behavior in the market; 1) by increasing holdings, and paying the dividends to your account, or 2) by adjusting the price of the asset so historically its a smooth continuous line. Lean currently uses the second method - scaling the price of the assets backwards as needed. Potentially we can also use this data to inject the dividends cash payments into algorithm account directly however it would be an approximation as we only have one dates for the dividend payment(there are several). The asset charts should line up with Yahoo and (many others) who also use adjusted prices

**Comment by mattmast** [comment]
That makes sense. 

I'm pretty close on getting the MFI done. Here's a diff if you want to start taking a look.  I cleaned up a few other things and looking forward to any feedback.  I still want to clean up some minor things and add some more tests.  

https://github.com/mattmast/Lean/compare/master...mattmast:indicators/mfi-indicator

**Comment by mchandschuh** [comment]
Started messing around with markdown:

#### General comments
Overall I think the code looks great.  Thanks for patching up a few things too!  I've added an issue to check other indicators for Reset and add tests for each Reset.  

You'll want to merge in the latest as there are some changes to the CompositeIndicator which now work on a push system (events from the Left and Right) vs the previous explicit manual system (internally CompositeIndicator calls Left.Update and Right.Update). If you have any questions about these changes, don't hesitate to ask me!

As always, thanks for the contributions!!

#### Line specific comments
[line](https://github.com/mattmast/Lean/compare/master...mattmast:indicators/mfi-indicator#diff-9e3ddbe9b7a72bce5965b4d4695436f5R84) - I think we can do this in the ComputeNextValue function and get the same behavior without the extra internal indicator.
[line](https://github.com/mattmast/Lean/compare/master...mattmast:indicators/mfi-indicator#diff-ee8535859b28b353a60eeb731312a97bR71) - These are great changes, thanks!
[line](https://github.com/mattmast/Lean/compare/master...mattmast:indicators/mfi-indicator#diff-6b158590ad7ec92c9ef989b617ce8d8dR59) - Looks great!
[line](https://github.com/mattmast/Lean/compare/master...mattmast:indicators/mfi-indicator#diff-852e8ffaac50f7e9cf6f6c3fc1dc6fa5R185) - Learned something new here! Actually didn't know you could specify those flags, awesome!

**Comment by brandonros** [comment]
Could this be added to Python please? :)
