### ISSUE TITLE
Library request: River

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6001]
#### Expected Behavior
Supports [River](https://github.com/online-ml/river). River is a framework for incremental and online learning and suits the case of algorithmic trading very well, because how the data evolves at the stock market is basically online learning. Note that river is the succeeder of scikit-multiflow, while mutliflow is no longer maintained.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
`River` was added in the last foundation update https://github.com/QuantConnect/Lean/pull/6677
