### ISSUE TITLE
Support TAKE PROFIT order types

### ISSUE THREAD

**Issue by AdalyatNazirov** [QuantConnect/Lean#6007]
#### Expected Behavior

Support new order types - TAKE PROFIT and TAKE PROFIT LIMIT (see FTX)

#### Actual Behavior

Not supported

#### Potential Solution

N/A

#### System Information

N/A

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by alexpvpmindustry** [comment]
ftx is dead...
this issue may be closed. @jaredbroad
