### ISSUE TITLE
Library Dependency Bug: Jaxlib Pytree for RiskParityPortfolio 

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6033]
#### Expected Behavior
RiskParityPortfolio is imported sucessfully. 

#### Actual Behavior
```
ImportError : cannot import name 'pytree' 
```

#### Potential Solution
Review Jax library installation,

#### Reproducing the Problem
```python
import riskparityportfolio as rp
#from jaxlib import pytree
 
class AllWeather(QCAlgorithm):
    def Initialize(self):
        pass
```
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Fixed by https://github.com/QuantConnect/Lean/pull/6558
