### ISSUE TITLE
Implements Crypto Universe Selection

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6049]
#### Expected Behavior
Be able to fetch the crypto-currency pairs that are available for a given exchange/brokerage. 

#### Actual Behavior
Users need to add the universe manually. They cannot add symbols that are not present in the SPDB or it will raise an exception.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Solved by https://github.com/QuantConnect/Lean.DataSource.CryptoCoarseFundamentalUniverse
