### ISSUE TITLE
Adds PyObject Overload for Methods in SecurityTransactionManager

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6054]
#### Expected Behavior
Be able to retrieve orders with certain characteristics in Python:
```python
orders = self.Transactions.GetOrders(lambda x: x.Symbol == self.symbol)
```
#### Actual Behavior
No python equivalent for the `Func<Order, bool>` overload. 

#### Potential Solution
Add the PyObject method overload. 

#### Reproducing the Problem
Use the following statement to find all orders of a given symbol
```python
orders = self.Transactions.GetOrders(lambda x: x.Symbol == self.symbol)
```
throws the exception
`TypeError : No method matches given arguments for GetOrders: ()`

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Duplicate of https://github.com/QuantConnect/Lean/issues/4514
