### ISSUE TITLE
OnData not called when using AddUniverse and self.UniverseSettings.Resolution = Resolution.Hour

### ISSUE THREAD

**Issue by danyg** [QuantConnect/Lean#6060]
#### Expected Behavior
When `AddUniverse` is used with one callback and `self.UniverseSettings.Resolution = Resolution.Hour` the `OnData` method should be called hourly in the same manner is with other resolution when using lean locally in backtest

#### Actual Behavior
OnData is not called when using `AddUniverse` with one callback and `self.UniverseSettings.Resolution = Resolution.Hour` only locally it works just fine on quantconnect backtest nodes as it can be seen here [Backtest ran on quantconnect nodes](https://www.quantconnect.com/reports/b2a798ba9014a8da27b222630656a038)

#### Potential Solution
Use Minute resolution and limit execution every hour on OnData, but this diminishes efficiency and increases backtest run time by a factor of 60

#### Reproducing the Problem
- Using leancli `lean, version 1.0.71`
- create new project in python
- populate main.py with following code
```python
from AlgorithmImports import *


class Bugreport(QCAlgorithm):
    _ondatacalls = 0

    def Initialize(self):
        self.SetStartDate(2021, 4, 1)  # Set Start Date
        self.SetEndDate(2021, 5, 1)  # Set End Date
        self.SetCash(100000)  # Set Strategy Cash

        self._selection = []

        self.UniverseSettings.Resolution = Resolution.Hour
        self.AddUniverse(self._coarse_selection)

    def _coarse_selection(self, coarse):
        if len(self._selection) == 0:
            self._selection = [Symbol.Create(
                "BTCUSD", SecurityType.Crypto, Market.Bitfinex)]
        return self._selection

    def OnData(self, data):
        """OnData event is the primary entry point for your algorithm. Each new data point will be pumped in here.
            Arguments:
                data: Slice object keyed by symbol containing the stock data
        """
        self._ondatacalls += 1
        self.Debug("On Data " + str(self._ondatacalls))
        if not self.Portfolio.Invested:
            each_percent = 1/len(self._selection)
            for symbol in self._selection:
                self.SetHoldings(symbol, each_percent)
            self.Debug("Purchased Stock")
        if self.Portfolio.Invested:
            self.Liquidate()
            self.Debug("Sold Stock")
```
- run a backtest
- You'll see there is no orders created
- Change `self.UniverseSettings.Resolution = Resolution.Hour` to other resolutions and you'll see that orders get created and you can find `On Data` traces in the logs

Might be duplicate with #4527 

#### System Information
lean, version 1.0.71
Using Windows 10 (21H1 19043.1237) with WSL 2 (Ubuntu 20.04)

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @danyg!
Since this works in the cloud just fine (just tested it) I believe this is because you do not have the hour resolution data available locally? You should be able to use the lean CLI to download the data at runtime or pre download it too (*downloading the data has a fee)
