### ISSUE TITLE
DelistingEventsProvider queues delisting event after delisting date

### ISSUE THREAD

**Issue by C-SELLERS** [QuantConnect/Lean#6062]
#### Expected Behavior

DelistingEventProvider would queue a delisting event on the given delisting date 

#### Actual Behavior

DelistingEventsProvider queues delisting event after delisting date. 

I.E. `BasicTemplateIndexOption` has a expiration on 1/15. The DelistingEventProvider will not generate the actual delisting event (Not warning) until a date after 1/15 is sent through its `GetEvents`

#### Potential Solution

Both the warning and actual delisting can be yielded one after the other by the same trigger. Because they will be queued in the SynchronizingEnumerator before processing anyways.

This looks something like 

```
            if (!_emittedEvents && _config.Symbol == eventArgs.Symbol &&  eventArgs.Date >= DelistingDate.Value.Date)
            {
                _emittedEvents = true;
                
                // Create our warning first, set to emit at 12AM the date of delisting
                var price = eventArgs.LastBaseData?.Price ?? 0;
                yield return new Delisting(
                    eventArgs.Symbol,
                    DelistingDate.Value.Date,
                    price,
                    DelistingType.Warning);
                
                // Create our actual delisting event, delisted at midnight of the delisting day.
                // Causes liquidation of the assets
                yield return new Delisting(
                    eventArgs.Symbol,
                    DelistingDate.Value.Date.AddDays(1),
                    price,
                    DelistingType.Delisted);
         
            }
  ```

#### Reproducing the Problem

- Run BasicTemplateIndexAlgorithm with end date set to 1/15 (The day of expiry)
- Place a breakpoint in `DelistingEventProvider.GetEvents()` 
- Notice that the DelistingEvent does not get created and yielded.

Also important TODO when fixing this issue, check that the delisting event actually gets emitted in this case (algo ends on 1/15, contract expires 1/15). It should not only be created on 1/15, but should be emitted in a timeslice even if the algo ends that day.

#### System Information

N/A

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by C-SELLERS** [comment]
Related to our delisting changes in #6059 

Delistings are now liquidated on delisting event not based on warnings.

**Comment by jaredbroad** [comment]
Review with a backtest the delisting date with the current version of code
