### ISSUE TITLE
Default Dates for Research Notebooks

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#6078]
Research notebooks shouldn't silently return empty arrays when making history requests without QB.SetStartDate() being set. We should throw if trying to make a history request, or set some default dates like backtesting does when the notebook starts.

#### Expected Behavior
Reasons provided why history request returns empty for research.

#### Actual Behavior
Silently empty.

#### Potential Solution
Debug messages or a throw on no QB dates.

#### Reproducing the Problem
![image](https://user-images.githubusercontent.com/2243225/143370715-1329014a-52fa-4c04-b3c3-c0a80f17e8b9.png)
 
#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
- Review default CLI/Local notebook, set the dates to dates where we have sample data and add a comment about available sample data/data download/a link to docs
