### ISSUE TITLE
Lean sends history requests for universe symbols

### ISSUE THREAD

**Issue by mchandschuh** [QuantConnect/Lean#609]
One solution is replacing all (maybe most?) references in `QCAlgorithm.History.cs` to `Security.Keys` with a reference to something like:
```csharp
private ICollection<Symbol> NonUniverseSymbols
{
    get { return Securities.Keys.Where(symbol => !UniverseManager.ContainsKey(symbol)).ToList(); }
}
```
Another wonder is if users are attempting to create indicators and orders against these universe symbols.

If it's more than an issue with just sending history requests for universe symbols then perhaps some more thought is needed here.

**Comment by jaredbroad** [comment]
Just adding notes:

WarmUp or History requests based on timespan which return history for ALL symbols; can attempt to return history for fake non-real symbols like the "qc-universe-equity-usa" universe subscription symbol. Using the filter above could help only submit requests for real assets.

**Comment by StefanoRaggi** [comment]
I looked at all references to `QCAlgorithm.Securities` and I can't find any cases in which universe symbols could be added to it. Universe symbols are added to `QCAlgorithm.UniverseManager`.

**Comment by mchandschuh** [comment]
Don't we define a 'canonical' security object for universes? I would expect
this canonical object to make its way into the Securities collection some
how, just not sure how.

**Comment by StefanoRaggi** [comment]
When creating a universe, the canonical security object is created and a Subscription for it as well, the security is added to the UniverseManager but not to the Securities collection. On the other hand, members of the universe ("normal" securities) do get added to the Securities collection.

**Comment by mchandschuh** [comment]
Gotcha. I'm not sure of another mechanism for the symbols to end up at the
history server.

**Comment by jaredbroad** [comment]
Closing while await more data.
