### ISSUE TITLE
algorithm-type-name configuration is ignored

### ISSUE THREAD

**Issue by omidkrad** [QuantConnect/Lean#6116]
Looks like `algorithm-type-name` in config.json is really ignored. It's kind of confusing, the algorithm engine looks for one single class in `algorithm-location` that is derived from `QCAlgorithm` and will use that regardless of what is set in `algorithm-type-name`. If there are multiple algo classes in the assembly then the engine will fail, regardless of if the specific one is set in `algorithm-type-name` or not.

My expected behavior is that:
- If `algorithm-type-name` is a fully qualified name and it's found, then use it and ignore any other QCAlgorithm subclasses in the assembly.
- If `algorithm-type-name` is only the class name (namespace not specified) and there is only one such type available, then use it and ignore any other QCAlgorithm subclasses in the assembly.
- If multiple `algorithm-type-name` types are found under different namespaces then fail with an error.
- If `algorithm-type-name` is not found, but there is a single QCAlgorithm available, then log it properly and use it.
- Else fail with an error.

**Comment by Martin-Molinero** [comment]
Hey @omidkrad!
It's handled by https://github.com/QuantConnect/Lean/blob/master/Common/Extensions.cs#L2041 used by the `BrokerageSetupHandler/BacktestingSetupHandler`, are you using some custom setup handler? we will need more details to find the bug/missconfiguration, steps to reproduce, which error are you seeing?

**Comment by omidkrad** [comment]
Hi Martin, OK l started debugging it, and it turns out my config settings were messed up. Indeed the loader is handling it close to what I explained above. I'm closing this issue. Thank you.
