### ISSUE TITLE
Adds More Options to Field Class

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6117]
#### Expected Behavior
Be able to use more attributes than those that are available, e.g. BidPrice.

#### Actual Behavior
`BidPrice` options is not available.

#### Potential Solution
Potentially `BidPrice` with `Field.BidClose`. It will give additional 10 fields because of `Bid` and `Ask`. 
Or the selectors of the indicators could accept a lambda function.  

#### Reproducing the Problem
`SMA(symbol, 9, Resolution.Minute, Field.BidPrice)`

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
We could add more helper funcs at `Field.cs`  but believe that's not enough though might cause some issues, for example when calling `SMA(**equity symbol**, 9, Resolution.Minute, Field.BidPrice)` default equity data feed into the indicator will be trade information. We could potentially detect that the given func requires quote information, how? we could make the field static and check references,
