### ISSUE TITLE
 C# Overloads of GetFundamental Do Not Return the TimeStamped data

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6121]
#### Expected Behavior
`GetFundamental` overloads for C# do not return the timestamped data.

#### Actual Behavior
`GetFundamental` overloads for C# returns the timestamped data.
The private method `GetAllFundamental` returns `Dictionary<DateTime, DataDictionary<dynamic>>`, but the Key part of the dictionary is dropped and the methods return `DataDictionary<dynamic>>`.

#### Potential Solution
N/A. 

#### Reproducing the Problem
```csharp
#load "../Initialize.csx"
#load "../QuantConnect.csx"

using QuantConnect;
using QuantConnect.Data;
using QuantConnect.Algorithm;
using QuantConnect.Research;
var qb = new QuantBook();
var spy = qb.AddEquity("AAPL");
var symbol = spy.Symbol;

var startTime = new DateTime(2017, 1, 1);
var endTime = DateTime.Now;
var marketCap = qb.GetFundamental(symbol, "CompanyProfile.MarketCap", startTime, endTime);

// Need to use obsolete Time
foreach (var x in marketCap.TakeLast(5))
{
    Console.WriteLine($"{x.Time} : {x[symbol]}");
}
```
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jhonabreul** [comment]
Closing since this is not actually a bug:

Just like some of the methods in the History API, the time in the `BaseData` (`BaseData.EndTime`) should be used instead of the obsolete `DataDictionary.Time`.

```charp
foreach (var xin marketCap.TakeLast(5))
{
    var data = x[symbol];
    Console.WriteLine($"{data.EndTime} : {data}");
}
```

**Comment by jhonabreul** [comment]
Closing since this is not actually a bug:

Just like some of the methods in the History API, the time in the `BaseData` (`BaseData.EndTime`) should be used instead of the obsolete `DataDictionary.Time`.

```charp
foreach (var xin marketCap.TakeLast(5))
{
    var data = x[symbol];
    Console.WriteLine($"{data.EndTime} : {data}");
}
```
