### ISSUE TITLE
Cannot Calculate Order Fee for Futures If USD is Not in the Cashbook

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6130]
#### Expected Behavior
Be able to calculate the order fee even without USD in the CashBook.

#### Actual Behavior
A live deployment with only HKD in the Cashbook failed to place an order because USD was not found in your cash book.
```
2021-12-23 04:31:00 New Order Event: Time: 12/23/2021 04:31:00 OrderID: 1 EventID: 1 Symbol: HSI30Z21 Status: New Quantity: 1 Message: Error executing margin models
2021-12-23 04:31:05 Order Error: id: 1, Error executing margin models: This cash symbol (USD) was not found in your cash book.
```
#### Potential Solution
N/A

#### Reproducing the Problem
```python
class TestNoUSD(QCAlgorithm):

    def Initialize(self):
        future = self.AddFuture(Futures.Indices.HangSeng, Resolution.Minute)
        future.SetFilter(lambda x : x.FrontMonth())
    def OnData(self, slice):
        if self.Portfolio.Invested: return
        for chain in slice.FuturesChains.Values:
            for contract in chain.Contracts.Values:
                if self.Portfolio.Invested: continue
                self.MarketOrder(contract.Symbol, 1)
```
The account cannot have USD. e.g.:
```
Symbol Quantity Conversion = Value in HKD
HKD: $ 1000000.00 @ 1.00 = $1000000.00
-------------------------------------------------
CashBook Total Value: $1000000.00
```
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
IB fee reference at https://www.interactivebrokers.com/en/index.php?f=commission&p=futures1
