### ISSUE TITLE
Library request: gurobipy

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6149]
#### Expected Behavior
[gurobipy](https://pypi.org/project/gurobipy/) i is a mathematical optimization software library for solving mixed-integer linear and quadratic optimization problems.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
Closing while awaiting vendor response.
