### ISSUE TITLE
Update EmaCrossAlphaModel to Warm Up Indicator

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6167]
#### Expected Behavior
The `EmaCrossAlphaModel` is not warming up its indicators.

#### Actual Behavior
All indicators are warmed up as soon as possible.

#### Potential Solution
Add
```csharp
algorithm.WarmUpIndicator(added.Symbol, fast, _resolution);
algorithm.WarmUpIndicator(added.Symbol, slow, _resolution);
```
at lines 107 and 108 of `EmaCrossAlphaModel.cs` and change to `EmaCrossAlphaModel.py`

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Auguschd** [comment]
I‘dbe interested in taking this one
