### ISSUE TITLE
Rename GDAX to Coinbase

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6174]
#### Expected Behavior
Lean should reference Coinbase instead of GDAX.
Edit: Coinbase Pro became Coinbase Advanced Trade and the wallets (Coinbase and Coinbase Pro) were unified.

#### Actual Behavior
The brokerage, fee, market refers to GDAX.

#### Potential Solution
Rename the classes using Coinbase. 

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by DerekMelchin** [comment]
Also include the `GDAXOrderProperties` class
