### ISSUE TITLE
Historical Data Requests for Daily Data Don't Return the Target Quantity with Tick Subscription

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6179]
#### Expected Behavior
The response of historical data requests should not depend on the subscription resolution.

#### Actual Behavior
Historical data requests for daily data don't return the target quantity with tick subscription.

#### Reproducing the Problem
```python
class HistoryBug(QCAlgorithm):

    def Initialize(self):
        self.SetStartDate(2021, 10, 28)
        self.SetEndDate(2021, 10, 28)
        self.SetCash(100000) # Set Strategy Cash
        self.symbol = self.AddEquity("F", Resolution.Tick).Symbol

    def OnData(self, data):
        history = self.History([self.symbol], 10, Resolution.Daily)
        assert(history.loc[self.symbol]["close"].count() == 10)
```
The history has 9 elements instead of 10.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closing for now since this is due to a data issue.

**Comment by yul** [comment]
hmm, you sure? it works correctly if you set
`        self.symbol = self.AddEquity("F", Resolution.Minute).Symbol
`

**Comment by Martin-Molinero** [comment]
> you sure? it works correctly if you set

Hey Yul! We've addressed the data issue and the reported algorithm now returns 10 data points:

```python
class HistoryBug(QCAlgorithm):

    def Initialize(self):
        self.SetStartDate(2021, 10, 28)
        self.SetEndDate(2021, 10, 28)
        self.SetCash(100000) # Set Strategy Cash
        self.symbol = self.AddEquity("F", Resolution.Tick).Symbol

    def OnData(self, data):
        history = self.History([self.symbol], 10, Resolution.Daily)
        self.Quit(history.loc[self.symbol]["close"].count() == 10)
```
