### ISSUE TITLE
LEAN Timezone issue

### ISSUE THREAD

**Issue by gvickh** [QuantConnect/Lean#618]
Hello
I have some discussion with Alexandre Catarino in QuantConnect community about LEAN timezone related issue. Alexandre suggests to open a ticket and here it is. Beside the (potential) problem, I am also making a few suggestions as well. 

A. LEAN chart display time issue
An example will be easier to describe the situation. 

Take the default "SPY" security data (2013/10/7) comes standard with LEAN download.
 
We know "SPY" started at 9:30am New York time that day (and every trading day indeed). Furthermore, assume the user operates at Shanghai/UTC+8 timezone, so the timezone setting of the host OS where LEAN is running is UTC+8.

We could express 9:30am NY time interchangeably in other timezones and they all mean the same instant of time. 
**9:30am NY = 13:30 UTC = 21:30 Shanghai/UTC+8**

So if we put that "SPY" data into LEAN and plot a chart of price using one of the three timezones we specified above, the chart should either starts at 9:30am,  13:30 or 21:30 depends on which one of the three timezones is specified in the algorithm.  Chart starts at any other time/timezone combinations would considered as incorrect. 

Currently various combinations of settings in LEAN will lead to chart starting time others than what described above. I have performed an analysis and tabulate the result in the following community question, please refer that for details.

[Discussion Forum: Different behavior for custom data plot using QC in cloud and desktop](https://www.quantconnect.com/forum/discussion/1457/different-behavior-for-custom-data-plot-using-qc-in-cloud-and-desktop)

B. cut the tie of chart display with timezone setting of the host OS where LEAN is running.  In other word, change host OS timezone should not have any effect on chart display.

C. inconsistency between LEAN and QuantConnect. Same algorithm running on LEAN and QuantConnect with have different chart display. 

D. need documentation on where time zone could be set inside LEAN ( e.g. SetTimeZone, AddData, SecurityExhange, etc) and how they affect the algorithm and chart display. Also suggestion on default setting or best practice of how they should be set.

E. legend/label in chart showing the current timezone. Current it is hard to tell especially if you have multiple streams of data from different timezone. Making users very confusing and hard to collaborate across multiple timezone. This is especially true if you clone/receive an algorithm created by somebody else

F. allow user to specify chart display timezone they preferred (Or is that already a setting serving that purpose?)

**Comment by jaredbroad** [comment]
Thanks for reporting @gvickh, this is addressed in PR #751. All charting is now stored in UTC making it ignore the OS timezone. QuantConnect/Embedded charts are forced into -5 Hours offset from UTC this is not configurable at this time but we may consider it given user demand.
