### ISSUE TITLE
Enable the Algorithm to Know its Runtime Mode

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6192]
#### Expected Behavior
`QCAlgorithm` is aware of being used in live mode, optimization, and backtest (in QC Cloud or locally).

#### Actual Behavior
It's only possible to determine whether the algorithm is running in backtesting or live mode with the `QCAlgorithm.LiveMode` boolean member. Other runtime modes were not needed before the implementation of Optimization and Lean-CLI.

#### Potential Solution
N/A

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Solved by https://github.com/QuantConnect/Lean/pull/7337
