### ISSUE TITLE
GetMaximumOrderQuantityForTargetBuyingPower Does Not Compute the Right Quantity for Binance Coins

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6198]
#### Expected Behavior
`GetMaximumOrderQuantityForTargetBuyingPower` calculate the right quantity for all securities and markets.

#### Actual Behavior
`GetMaximumOrderQuantityForTargetBuyingPower` doesn't calculate the right quantity for Binance symbols.

#### Potential Solution
N/A
The problem probably comes from the fact that Binance changes fees in the base currency. `GetMaximumOrderQuantityForTargetBuyingPower` discounts the fee in the account currency to get the right buying power, but does not reflect it in the order quantity, so when the fees are applied, there is a mismatch between the pair quantity and the base currency in the cashbook.

#### Reproducing the Problem
```csharp
namespace QuantConnect.Algorithm.CSharp {
    public class BasicTemplateCryptoAlgorithm : QCAlgorithm {
        public override void Initialize() {
            SetAccountCurrency("USDT");
            SetBrokerageModel(BrokerageName.Binance);

            SetStartDate(2018, 5, 1); // Set Start Date
            SetEndDate(2018, 5, 5); // Set End Date
            SetCash(100000);

            AddCrypto("BTCUSDT", Resolution.Hour);
        }

        public override void OnData(Slice data) {
            if (!Portfolio.Invested) {
                SetHoldings("BTCUSDT", 1);

                var quantity = Portfolio["BTCUSDT"].Quantity;
                var amount = Portfolio.CashBook["BTC"].Amount;
                if (quantity != amount)  {
                    throw new Exception($"BTCUSTD Quantity doesn't match BTC Amount: {quantity} != {amount}");
                }
            }
        }
    }
}
```
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by ikamanu** [comment]
🙏

**Comment by Martin-Molinero** [comment]
Hey! 
Believe `GetMaximumOrderQuantityForTargetBuyingPower` is working as expected, the underlying issue seems to be because it's using `AccountType.Margin` by default, using `AccountType.Cash` instead has the expected behavior.
At the moment because it's using Margin trading, we do not reduce the virtual position `Portfolio["BTCUSDT"]` size because of fees but we do deduct the fees to the portfolio `Portfolio.CashBook["BTC"]`

**Comment by ikamanu** [comment]
Since we will have systems that use Margin, that would benefit from using a similar qty calculation, will this be implemented for Margin as well?  If not, please explain the rationale.
