### ISSUE TITLE
Add commissions and fees to OrderEvent

### ISSUE THREAD

**Issue by bizcad** [QuantConnect/Lean#62]
I am trying to get what amounts to a brokerage confirmation to be reported in my algo so I can compute the actual cost of the transaction/order.  Right now I am doing it through the OnOrderEvent method overriding the virtual QCAlgorithm event as follows. 

```
    public override void OnOrderEvent(OrderEvent orderEvent)
    {
        base.OnOrderEvent(orderEvent);
        var direction = orderEvent.Direction;
        var qty = orderEvent.FillQuantity;
        var price = orderEvent.FillPrice;
        var tradevalue = qty*price;
        var security = Securities[orderEvent.Symbol];
        var projectedFees = security.Model.GetOrderFee(qty, price);
        var orderNet = tradevalue + projectedFees;
    }
```

This method is not very satisfactory because things like exchange fees may not be included in the  GetOrderFee method on the parent.  The response from the broker should have those fees.  
# 

Dredging through the IBClient code on line 4498 of https://github.com/krs43/ib-csharp/blob/master/Krs.Ats.IBNet/IBClient.cs are the lines:

 orderState.Commission = ReadDoubleMax();
orderState.MinCommission = ReadDoubleMax();
orderState.MaxCommission = ReadDoubleMax();
orderState.CommissionCurrency = ReadStr();

So it appears that IB's OrderState object (https://github.com/krs43/ib-csharp/blob/master/Krs.Ats.IBNet/OrderState.cs) has the commission and fees which can be obtained thorough the IncomingMessage.OpenOrder in ProcessMessage(IncomingMessage msgId) starting on line 3835

Also I have found a CommissionReport object at https://www.interactivebrokers.com/en/software/api/api.htm

Nick Stein

**Comment by jaredbroad** [comment]
Awesome thank you Nick, we just made all the IB code public. If you'd like to see this sooner you could add a property to the OrderEvent object and populate its value when the order data is passed back from Interactive Brokers. This would be a nice tidy pull request :+1: 

The OrderEvent is created here: 
https://github.com/QuantConnect/Lean/blob/master/Brokerages/InteractiveBrokers/InteractiveBrokersBrokerage.cs#L543

**Comment by jaredbroad** [comment]
https://github.com/QuantConnect/Lean/blob/cc46cd367f5a0c415e6ac2462b903a27a86eedcb/Common/Orders/OrderEvent.cs#L53
Implemented!
