### ISSUE TITLE
Enable Downloading Machine Learning (Binary) Files

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6205]
#### Expected Behavior
Be able to upload machine learning models that are trained locally.

#### Actual Behavior
Not supported. Users need to use the `Download` method that returns a `string` object.

#### Potential Solution
Add `DownloadFile` method to ObjectStore:
`bool DownloadFile(string key, string url);`
it could use the featured implemented by #6164. 

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Let's discuss API naming when we get there - this seems like an easy feature to add.

**Comment by alexpvpmindustry** [comment]
seems like this is implemented with ObjectStore.ReadBytes.
https://www.lean.io/docs/v2/lean-engine/class-reference/classQuantConnect_1_1Storage_1_1ObjectStore.html#a5a6c41b2faffcc48a3fd166eee1d50a2
if so, this issue can be closed.
@jaredbroad

**Comment by AlexCatarino** [comment]
QuantConnect users can upload any file format using Lean CLI:
https://www.quantconnect.com/docs/v2/lean-cli/object-store
We can view the storage here:
https://www.quantconnect.com/docs/v2/cloud-platform/object-store

Once the file is stored, we can load the mode using the path. [E.g.](https://www.quantconnect.com/docs/v2/writing-algorithms/machine-learning/popular-libraries/hmmlearn#08-Load-Models):
```python
path = self.ObjectStore.GetFilePath(<key>);
self.model = joblib.load(file_name)
```
