### ISSUE TITLE
No History Method Overload For Python that Accepts Fill Forward and Extended Market Hours Arguments

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6211]
#### Expected Behavior
Be able to ask for extended market hours during a historical data request even if the subscriptions do not for Python.

#### Actual Behavior
The overload is only available for C#:

#### Potential Solution
- Add regression algorithm asserting behavior
- Add the following overload and review for any other missing overload for python
```csharp
public PyObject History(PyObject symbols, DateTime start, DateTime end, Resolution? resolution = null, bool? fillForward = null, bool? extendedMarket = null)
```

#### Reproducing the Problem
```python
class HistoryBug(QCAlgorithm):

    def Initialize(self):
        self.SetStartDate(2022, 1, 14)
        self.SetCash(100000)
        self.spy = self.AddEquity("SPY", Resolution.Tick).Symbol


    def OnData(self, data):
        slices = self.History([self.spy], self.Time-timedelta(1), self.Time, Resolution.Minute, True, True)
```
`slices` should be a pandas DataFrame, but it's `IEnumerable<Slice>`.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by j-usti-n** [comment]
I'm interested in claiming this issue!
