### ISSUE TITLE
Set "Automatically delete head branches" in repo settings

### ISSUE THREAD

**Issue by v-karbovnichy** [QuantConnect/Lean#6224]
There are 120+ stale branches from all the PRs that had been merged to this repo. It's hard to see if the bug fix was merged or not, because most of those PRs were merged via squash commits to the `master` branch. 

Nobody needs them, they are garbage.

I suggest enabling setting "Automatically delete head branches" in repo Settings > General page (scroll down to the bottom)
![image](https://user-images.githubusercontent.com/7301634/154678692-b8d20f8a-b37c-4679-a9a7-19adb7f8dd11.png)

The above behavior is not destructive, you can restore any branch back inside of the PR manually if needed -- there is a special button for that after the last "merge" comment in PR.

**Comment by Martin-Molinero** [comment]
Hey @v-karbovnichy! This is already enabled 👍
