### ISSUE TITLE
Clean up stale branches

### ISSUE THREAD

**Issue by v-karbovnichy** [QuantConnect/Lean#6225]
There are 120+ stale branches from all the PRs that had been merged to this repo. It's hard to see if the bug fix was merged or not, because most of those PRs were merged via squash commits to the `master` branch. 

Nobody needs them, they are garbage.

I suggest deleting most of them. It is easily can be done by going to this page https://github.com/QuantConnect/Lean/branches/stale
and deleting those branches that have corresponding PR merged.
And also deleting any of those that are 2+ years old, as I doubt anyone will continue development on them.

Or maybe I am missing something, and all of those 128 branches are not stale?

Also I suggest installing this free bot from GitHub Marketplace, it can help to automatically clean up things:
https://github.com/marketplace/stale

**Comment by Martin-Molinero** [comment]
Hey @v-karbovnichy! I've removed some of the branches which weren't required 🚀
