### ISSUE TITLE
Add CultureInfo in CoarseUniverseGeneratorProgram

### ISSUE THREAD

**Issue by creatidy** [QuantConnect/Lean#6228]
#### Expected Behavior

Artificially generated coarse CSV files should always use dot in decimal numbers.

#### Actual Behavior

In my local Windows environment comma are used for numeric values instead of a dot, so artificially generated coarse CSV files had too many commas and were unable to be properly parsed.

#### Potential Solution

Option a)
Apply rules according to the page:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated

Eg. use the `ToString(CultureInfo.Invariant)` in:
Line 268: `ToolBox / CoarseUniverseGenerator / CoarseUniverseGeneratorProgram.cs`
```
            // sid,symbol,close,volume,dollar volume,has fundamental data,price factor,split factor
            var coarseFileLine = $"{sidContext.SID},{ticker.ToUpperInvariant()},{tradeBar.Close.Normalize()},{tradeBar.Volume.Normalize()},{Math.Truncate(dollarVolume)},{hasFundamentalData},{priceFactor},{splitFactor}";
```

~Option b) (works for me, but I'm not C# programmer)~
~Add in the constructor:~
~`Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo ("en-US");`~

#### Reproducing the Problem

1. Windows: Change the default decimal separator form dot to comma
2. Run `ToolBox / CoarseUniverseGenerator / CoarseUniverseGeneratorProgram.cs`
3. Coarse CSV files had too many commas and are unable to be properly parsed by Lean

#### System Information

The bug is specific to my local environment and probably doesn't affect other users.
OS: Windows 11
Localization: PL

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by j-usti-n** [comment]
I'm interested in claiming this issue! Currently working on a fix!
