### ISSUE TITLE
Library request: Riskfolio-Lib

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6230]
#### Expected Behavior
[Riskfolio-Lib](https://riskfolio-lib.readthedocs.io/en/latest/) is a library for making portfolio optimization and quantitative strategic asset allocation in Python

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by KlausGlueckert** [comment]
Hi @AlexCatarino, is there any plans to include this package soon?

**Comment by Martin-Molinero** [comment]
Added by https://github.com/QuantConnect/Lean/pull/6558
