### ISSUE TITLE
Improve Option OTM Expiration Message

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6231]
#### Expected Behavior
If an option expires worthless, the "fill" price should be zero, and the message should not be only OTM but also contain the underlying price, so we know why it has expired worthless.

#### Actual Behavior
The fill price is the strike price and the order tag is only OTM:
![Capture](https://user-images.githubusercontent.com/6889033/155197001-58c0aa68-3e5f-4e92-9e19-6e9708621f96.png)

#### Potential Solution
N/A

#### Reproducing the Problem
TBA

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by DerekMelchin** [comment]
Maybe the Type column should be empty too since it's not actually exercising the option. The option expired.
