### ISSUE TITLE
Add missing stable coins for currency conversions

### ISSUE THREAD

**Issue by zhuzw0528** [QuantConnect/Lean#6244]
#### Expected Behavior
backtesting  binance  cypto  

#### Actual Behavior
Can't place an order

#### Potential Solution
- Add all crypto exchanges missing stable coins to be added at https://github.com/QuantConnect/Lean/blob/master/Common/Currencies.cs#L116

#### Reproducing the Problem
 def Initialize(self):  
    self.SetStartDate(2018, 5, 2)  
    self.SetEndDate(2021, 5, 4)  
    self.SetCash("USDT",200000, Decimal(1))            
    self.SetBrokerageModel(BrokerageName.Binance, AccountType.Cash)

    self.btcusdtSymbol = self.AddCrypto("BTCUSDT", Resolution.Hour, Market.Binance).Symbol

def OnData(self, data):
     if self.Time.hour <= 5: 
        self.SetHoldings("BTCUSDT", 1)

     elif self.Time.hour > 5: 
         self.Buy("BTCUSDT", 1) 

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @zhuzw0528!
It works correctly for me in qc.com, where was this run? The data should be available for it to work correctly

I used
```python
class SwimmingBrownHornet(QCAlgorithm):
    def Initialize(self):  
        self.SetStartDate(2018, 5, 2)  
        self.SetEndDate(2021, 5, 4)  
        self.SetCash("USDT",200000) 
        self.SetBrokerageModel(BrokerageName.Binance, AccountType.Cash)
        self.AddCrypto("BTCUSDT", Resolution.Hour, Market.Binance)

    def OnData(self, data):
        if not self.Portfolio.Invested:
            self.SetHoldings("BTCUSDT", 0.1)
```

We are missing stable coins to be added at https://github.com/QuantConnect/Lean/blob/master/Common/Currencies.cs#L116 which I think can cause some issues too

**Comment by zhuzw0528** [comment]
I use The master branch code. It happens when I debug locally。when i use self.Buy(xxxx ) in OnData method. It reports an error: BTCUSDT: requires USDT to have a non-zero conversion rate。 when I use the SwimmingBrownHornet algorithm you provide, The local result is all 0。
![123](https://user-images.githubusercontent.com/75722895/157581365-22962513-8c1f-4973-8777-0272f6ae1a4c.png)

**Comment by Martin-Molinero** [comment]
Hey @zhuzw0528,
Do you have the data available locally? the data isn't available locally out of the box, using the API data provider it can be downloaded to run locally with a fee, or can use the lean CLI to download it too. There are a few tutorials/videos about this
