### ISSUE TITLE
Library request: technical-analysis-charts

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6261]
#### Expected Behavior
[technical-analysis-charts](https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/?feature=technical-analysis-charts) is a free, powerful & perfect for your most demanding users. Loaded with features for complete technical analysis. Next-gen web charting that beats the desktop experience.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by ari62** [comment]
Looks like a javascript library

**Comment by Martin-Molinero** [comment]
Closing for now, `Technical Analysis Charts` is not open source, his brother `Lightweight Charts` is, it's a javascript library
