### ISSUE TITLE
Library request: Qiskit, Pennylane, and Ocean

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6269]
#### Expected Behavior
- [Qiskit [kiss-kit]](https://qiskit.org/) is an open-source SDK for working with quantum computers at the level of pulses, circuits, and application modules.

- [PennyLane](https://pennylane.ai/) is a cross-platform Python library for differentiable programming of quantum computers. Train a quantum computer the same way as a neural network. We already support PennyLane, so it's an update and we probably need to install
```
pip install pennylane-qiskit
```
to work with Qiskit.

- [Ocean](https://docs.ocean.dwavesys.com/en/stable/) software is a suite of tools [D-Wave Systems](https://www.dwavesys.com/) provides on the [D-Wave GitHub repository](https://github.com/dwavesystems) for solving hard problems with quantum computers.

**Note**: PennyLane supports Python 3.7 or newer, so we need to upgrade the Python version in Lean.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by speQtrum** [comment]
Thank you Alex
