### ISSUE TITLE
Can't Register `OpenInterestConsolidator` for Automatic Updates

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6289]
#### Expected Behavior

We can automatically update the `OpenInterestConsolidator` with the `SubscriptionManager`.

#### Actual Behavior

We can't automatically update the `OpenInterestConsolidator` with the `SubscriptionManager`. 

#### Potential Solution

N/A

#### Reproducing the Problem

Run 
```
from AlgorithmImports import *

class EmotionalSkyBlueManatee(QCAlgorithm):

    def Initialize(self):
        self.SetStartDate(2020, 10, 12)  # Set Start Date
        self.SetCash(100000)  # Set Strategy Cash
        self.future = self.AddFuture(Futures.Metals.Gold, Resolution.Tick)
        self.future.SetFilter(0, 90)
        self.symbol = self.future.Symbol

    def consolidation_handler(self, sender, bar):
        self.Quit("Received consolidated bar!")

    def OnSecuritiesChanged(self, changes):
        for security in changes.AddedSecurities:
            if security.Symbol != self.symbol:
                consolidator = OpenInterestConsolidator(1)
                consolidator.DataConsolidated += self.consolidation_handler
                self.SubscriptionManager.AddConsolidator(security.Symbol, consolidator)
```
We get
> Runtime Error: ArgumentException : Type mismatch found between consolidator and symbol. Symbol: GC25X20 does not support input type: Tick. Supported types: Tick,Tick.

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
This is happening because currently open interest subscriptions are handled as internal subscriptions
