### ISSUE TITLE
`OrderTicket` doesn't have an `UpdateTriggerPrice` method

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6295]
#### Expected Behavior

We can update the trigger price of limit if touched orders with an `UpdateTriggerPrice` method, just like we can use `UpdateTag`, `UpdateQuantity`, `UpdateLimitPrice`, `UpdateStopPrice` to update order fields.

#### Actual Behavior

There is no `UpdateTriggerPrice` method. 

#### Potential Solution

Implement the `UpdateTriggerPrice` method. 

#### Reproducing the Problem

Try updating the trigger price of a limit if touched order. Currently, you need to create an `UpdateOrderFields` object.

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Jns234** [comment]
Hello, i'd like to handle the issue
