### ISSUE TITLE
LastPriceFillModel is no longer needed

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6305]
#### Expected Behavior

The repo only contains fill models that are necessary.

#### Actual Behavior

The repo contains the LastPriceFillModel, but it's no longer necessary. [The comments in the source code](https://github.com/QuantConnect/Lean/blob/master/Common/Orders/Fills/LatestPriceFillModel.cs#L24-L25) say
> This fill model is provided because currently the data sourced for Crypto is limited to one minute snapshots for Quote data.

This is no longer true.

#### Potential Solution

GDAX/Coinbase Pro is the only brokerage model using the LastPriceFillModel. Update the GDAX/Coinbase Pro brokerage model to use the same fill model as the other Crypto brokerage models.

#### Reproducing the Problem

Compare the source code comment above to the resolutions displayed in the [Coinbase Pro Crypto Price Data listing](https://www.quantconnect.com/datasets/coinbase-pro-crypto-price-data).

#### System Information

N/A

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/6705
