### ISSUE TITLE
Throwing exception creating a TradeBarConsolidator

### ISSUE THREAD

**Issue by DavidThielen** [QuantConnect/Lean#6315]
#### Expected Behavior
To be able to create a TradeBarConsolidator at any time

#### Actual Behavior
The TradeBarConsolidator (FuncPeriodSpecification func) constructor will throw an exception depending on what time of day it is constructed.

#### Potential Solution
Remove the func check in the constructor. If removed, all unit tests still pass.

#### Reproducing the Problem
Call any time where DateTime.Now < 9:30am or on a day the exchange is closed (Sat/Sun).

#### System Information
N/A

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

First off, when called day by day it passes in a time of 9:00 and expects a return of 9:30-16:00. If 9:00 was used instead of Now in the constructor test, it would throw the exception.

Second, this is a random test that will pass/fail depending on the time of day the program starts up. If there's an expected case where the returned CalendarInfo should be the previous or next day, the DateTime passed in should be a hard-coded value.

Third, the documentation is silent on this issue. Which leads to the conclusion that it's return the CalendarInfo for the DateTime.Date passed in and the time component is irrelevant.

I think step #1 is determine what day the func should return for a passed in date that is before market open, during the market, and after market close. Second, it should state explicitly what DateTimeKind is expected. For NASDAQ is it East Coast Time or UTC? And if it uses Kind.Local, is that the exchange time zone or the server's time zone?

And then step #2, if you do want a test, should pass in a hard coded DateTime, not DateTime.Now.

**Comment by Martin-Molinero** [comment]
Hey @DavidThielen! 
Would you please add some algorithm code reproducing the issue your experiencing?
The `FuncPeriodSpecification` is trying to assert the `expiryFunc()` call is returning the **start of the bar**, there are at least a couple of problems with how it's implemented though:
- time zones, it's using `DateTime.Now` which is local time zone and ignores data TZ
- there's a race condition because it's calling `DateTime.Now` twice, there could be a difference between the first and second call

**Comment by DavidThielen** [comment]
Hi @Martin-Molinero 
Duplicating the error is not an issue of specific code, it's an issue of when that code is called. And to that, first there's a question about what is expected from this func as it's not documented. Specifically, assuming all NY times and for the NYSE, what day should the func return for:

- A passed in time of 9:00am
- A passed in time of 10:00am
- A passed in time of 4:30pm
- A passed in time of Saturday

Because the func is supposed to return the CalendarInfo for a trading day - but which day for each of these cases.

And the next question is, what timezone? Is it DateTimeKind.Local and everything is set to the local time of the exchange this is for? Or is it UTC? And if UTC, then what is going on if say you're doing this for the New Zealand stock exchange? The timezone issue needs to be documented, even if it's "we ignore it."

When running after the initial construction it passes in a time of 9:00am every Monday - Friday. So I think it is expecting a CalendarInfo for the same Date passed in. But that is an assumption (and one that will fail that constructor test).

Also, that test is bad. Using DateTime.Now is totally random which is rarely a good idea for parameter checking. If my guess is right about what it is expecting, the test should be 9:00am for a hardcoded day when the market was open. A day every market everywhere in the world was open. And then assert that the returned CalendarInfo is for the same Date.

**Comment by Martin-Molinero** [comment]
Hey @DavidThielen!
I've pushed a PR fixing the documentation and the randomness of the assertion, hope it's clearer now

**Comment by DavidThielen** [comment]
Hi @Martin-Molinero 
What you did for the check will work so that's good.
But I believe it's inaccurate because when running, it passes in 9:00am M-F and so I think it is expecting 9:30 - 16:00 of the same day.
Also, you didn't document what DateTimeKind the DateTime is for. Is it UTC or East Coast?

**Comment by Martin-Molinero** [comment]
> I believe it's inaccurate because when running, it passes in 9:00am M-F and so I think it is ex

Hey! the `TZ` passed in is of the data itself, in Lean the exchange time zone, which for example for USA equities is NewYork. 
Generically for _any_ provided DateTime the method expects the theoretical start of the bar time

**Comment by DavidThielen** [comment]
@Martin-Molinero I assumed the TZ was as you said. But you should add that to the documentation.
