### ISSUE TITLE
Add remove/unregister indicator algorithm helper method

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6335]
#### Expected Behavior

The RsiAlphaModel creates manual indicators, since we can't assume the universe is fixed.

#### Actual Behavior

The RsiAlphaModel creates automatic indicators.

#### Potential Solution

Update the RsiAlphaModel to use manual indicators (use the `RelativeStrengthIndicator` constructor)

#### Reproducing the Problem

View the RsiAlphaModel source code
https://github.com/QuantConnect/Lean/blob/aaba566954e995053eb97656b05e06a3984fc9fb/Algorithm.Framework/Alphas/RsiAlphaModel.py#L84

#### System Information

N/A

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Transforming this issue into a more generic missing feature/bug: indicators created through the helper methods at `QCAlgorithm.Indicators.cs` do not have an equivalent helper method to remove/unregister these indicators

**Comment by jaredbroad** [comment]
- At the indicator's creation time, save a reference to the consolidator in the indicator base class. 
 - Create UnregisterIndicator and use its reference to the consolidator to unsubscribe it from events.

**Comment by Martin-Molinero** [comment]
See related https://github.com/QuantConnect/Lean/issues/7092 https://github.com/QuantConnect/Lean/issues/7089
