### ISSUE TITLE
Fatal Unhandlen Exception with Ray Init Method

### ISSUE THREAD

**Issue by varuk** [QuantConnect/Lean#6338]
#### Expected Behavior

Ray library works without breaking

#### Actual Behavior

calling ray.init() throws error

#### Reproducing the Problem

`class Algo(QCAlgorithm):
	def Initialize(self):
		import ray
		ray.init()`

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @varuk! this has been fixed with the latest foundation update, see https://github.com/QuantConnect/Lean/pull/6558

**Comment by Martin-Molinero** [comment]
Reopening because initializing `ray` seems to be causing a segmentation fault when python is shutting down

**Comment by Martin-Molinero** [comment]
Hey! 
It seems `ray` needs to be shutdown explicitly too, see the following working example
```
# region imports
from AlgorithmImports import *
# endregion

import ray
class AlertBlackGoshawk(QCAlgorithm):

    def Initialize(self):
        self.SetStartDate(2021, 3, 6)  # Set Start Date
        self.SetCash(100000)  # Set Strategy Cash
        self.AddEquity("SPY", Resolution.Minute)
        ray.init()

    def OnData(self, data: Slice):
        if not self.Portfolio.Invested:
            self.SetHoldings("SPY", 0.33)

    def OnEndOfAlgorithm(self):
        ray.shutdown()
```
