### ISSUE TITLE
Improperly being Margin Called when selling option spreads

### ISSUE THREAD

**Issue by mattmcwaters** [QuantConnect/Lean#6341]
When selling a bear put spread (Sell put with strike higher than a put you buy, same quantity and expiration), we hedge ourselves by buying a put against the one we are selling. Our risk is limited and we expect to have no margin calls if our margin remaining is above the maximum loss dictated by the difference between the credit and debit of the strategy.

However, we still see margin calls when using strategies like this in QC. See backtest below:
https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_84f70b9a9b7dfcb74ee1575dc5fe1287.html

**Comment by Martin-Molinero** [comment]
Hey @mattmcwaters!
It seems the margin calls are for the underlying SPY equity, the options are getting executed. Maybe related to this other issue https://github.com/QuantConnect/Lean/issues/5857 . Mind expanding on what behavior would you expect to be seeing?

**Comment by Martin-Molinero** [comment]
>he real issue is that we are even considering automatically assigning an option strategy like a credit or debit spread, which would never happen with IBKR or any respected brokerage due to the limited finite risk.

Right, I see the point now 👍 

> Should I edit the issue to reflect the true root cause or make a new one?

No it's okay as is 👌 the comments are enough I think
