### ISSUE TITLE
Add Adjustment PriceScaleFactor to Tick/TradeBar Objects

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#64]
Allow converting adjusted prices back to the raw price by adding a method and value for the conversion factor. Thanks @AlexCatarino

**Comment by AlexCatarino** [comment]
If nobody is taking this assignment, I could do it.
Any suggestions on what the best solution would be?
I suggest we should add a private value _pricescalefactor that would store the last PriceScaleFactor that comes form SubscriptionDataConfig class internally and a method for the conversion "AdjustedToRaw" that could be called by the user at OnData or automatically on SetHolding.

**Comment by jaredbroad** [comment]
Thank you Alex - if you help it will get done much faster! Agree on first half of implementation; 
1>  _priceScaleFactor private variable in Tick and TradeBar objects; which is set on creation of the objects in the Reader() method.
2> Expose public property PriceScaleFactor in the Tick/TradeBar objects.

Just curious; why is the conversion method there? How will you use the raw prices? This will help me understand the use case. We don't have the dividend data so raw prices won't reflect full situation or share splits

**Comment by AlexCatarino** [comment]
I proposed the conversion method instead of exposing the public PriceScaleFactor, so that calculations would be done inside the object. If you think it's better to expose the property and the user make the calculations (value = value / PriceScaleFactor) in his algorithm, fine.

Raw prices would be used for allocations and sending orders (as discussed here: https://www.quantconnect.com/forum/discussion/109/adjusted-pricing#Item_5).

I was thinking about it... if we use raw prices for orders, we would also be using "raw" quantities. If there's a split/inplit while we're in a position, we would have to account the change in quantity when exiting.

**Comment by jaredbroad** [comment]
I see... Its not ideal to do it this way; I'd recommend this would be part of a broader update of the dividend and share split system. The algorithm and portfolio essentially has two modes -- adjusted or raw which goes deep into the portfolio / holdings models. 

We can make a setting in the algorithm which controls the mode: so it will increase the quantity when the shares split instead of adjusting the price. The downside is the dividend modelling will be inaccurate as we just don't have that data. We're talking with a data vendor and when we can afford will purchase the dataset.

**Comment by AlexCatarino** [comment]
How do you do the factor files inside the factor_files folder? I thought you had the dividends and share split data and calculate the factor with the closing price around these events.
Anyway, do we wait for the dataset and talk about this implementation when we have it?

**Comment by jaredbroad** [comment]
We have share split but not dividends (the cash dividend payments can't be reverse engineered from the price factor files). I think its a good idea to do this change but if the data isn't there we just can't pay the cash into the algorithm's account.

Steps: 
> Pull latest QC build to be sure working from latest,
> Add setting method: Algorithm.SetDataNormalizationMode()
> Create enum
DataNormalization.Raw, DataNormalization.Adjusted, DataNormalization.TotalReturn,
> Add the data normalization as private variable in algorithm, locked after initialization, and add mode to subscription config, init the configs with this setting.
> In the subscription data reader / tradebar / tick reader methods take the config; use the DataNormalization enum to decide if you apply the price factors. Where we update the price factors  you could potentially apply the split math as well.

I think its safe for you to assume we have the dividend data, invent a data format for it, and pre-populate the sample data files with real data from Yahoo/Google. Over the next few months we'll source large scale real data from the vendors and upload it to the QC cloud.

Its a big update! :) Glad to have your help. We're pushing an update now which converts SubscriptionDataConfigs to classes. With this change you'll have everything you need to start the steps above.

**Comment by mchandschuh** [comment]
DataNormalizationMode has been created. The scale factors still aren't on Tick/TradeBar instances though.

**Comment by jaredbroad** [comment]
No demand
