### ISSUE TITLE
Algorithm Helpers

### ISSUE THREAD

**Issue by jdvachal** [QuantConnect/Lean#640]
I think it would be of use for some helper methods for common calculations.

Initially I propose HL2, HLC3 and OHLC4 but would also implement any others that the community wants.

I am opening this issue for some discussion on the best location for these helpers.

My two thoughts are:
1 - A new namespace - QuantConnect.Indicators.Helpers
2 - Add to the existing QuantConnect.Indicators namespace and just located the helpers in a new Helpers folder inside that project.

Suggestions?

**Comment by jaredbroad** [comment]
Welcome @jdvachal! Would these be static methods on IBars? like bar.HL2()? Are there any other helpers you could think of? (what other helpers could we make other than the IBar ones?)

**Comment by StefanoRaggi** [comment]
@jdvachal The calculations you mentioned are available as static properties in the `Field` class here: https://github.com/QuantConnect/Lean/blob/master/Common/Field.cs

All indicator constructors have an optional `selector` argument, where you can pass the desired `Field` property.
 
Some usage examples can be found in these sample algorithms:
https://github.com/QuantConnect/Lean/blob/master/Algorithm.CSharp/IndicatorSuiteAlgorithm.cs
https://github.com/QuantConnect/Lean/blob/master/Algorithm.CSharp/DailyAlgorithm.cs

If you have any additions to suggest, please let us know, or even better, submit a PR :)
