### ISSUE TITLE
Library Update Request: CatBoost

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6434]
#### Expected Behavior
Supports v. 0.24

#### Actual Behavior
Supports v. 0.23.2

#### Potential Solution
Update [CatBoost](https://pypi.org/project/catboost/).

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by alexander-myltsev** [comment]
Thank you!

Please, update to most recent version which is [1.0.6](https://pypi.org/project/catboost/1.0.6/) if possible.

**Comment by Martin-Molinero** [comment]
Updated to 1.0.6 by https://github.com/QuantConnect/Lean/pull/6558
