### ISSUE TITLE
Optional Default Parameter for GetParameter

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#6449]
#### Expected Behavior
GetParameter takes a default arg.

#### Actual Behavior
GetParameter only allows specifying name

#### Potential Solution
Adding an optional arg to GetParameter
![image](https://user-images.githubusercontent.com/2243225/176462057-87cd69fa-8f40-419b-b8f0-94b168e6a414.png)
 
#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
> It would be nice to have number overloads to avoid the type conversions in the algorithm.

See https://github.com/QuantConnect/Lean/pull/6452#discussion_r910433048
