### ISSUE TITLE
MapFile.SafeMapFileRowRead() NullReferenceException when file exists

### ISSUE THREAD

**Issue by superichmann** [QuantConnect/Lean#6476]
#### Expected Behavior
file contents should be retreived

#### Actual Behavior
20220712 14:14:45.831 ERROR:: MapFile.SafeMapFileRowRead(): File: \Data\equity\usa\map_files\aapl.csv System.NullReferenceException: Object reference not set to an instance of an object.
   at QuantConnect.Extensions.ReadLines(IDataProvider dataProvider, String file)+MoveNext() in \Common\Extensions.cs:line 3123
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at QuantConnect.Data.Auxiliary.MapFile.SafeMapFileRowRead(String file, String market, SecurityType securityType, IDataProvider dataProvider) in \Common\Data\Auxiliary\MapFile.cs:line 238

#### Potential Solution
After calling Path.Combine replace \\\\ with /

#### Reproducing the Problem
Get latest lean version from github
open on vs 2022
create console project
call the following function
`Symbol lolS = Symbol.Create("AAPL", SecurityType.Equity, Market);`
look for errors

#### System Information
windows 10

**Comment by Martin-Molinero** [comment]
Hey @superichmann! 
Sounds like the IMapFileProvider needs to be initialized, the data provider is null. Will keep this issue open so we improve the exception message, we can add a null check and throw a nicer exception pointing to the missing initialization of the map file provider.
This is not happening using Lean launcher executable right?

**Comment by Martin-Molinero** [comment]
Hi @superichmann!

> I don't see this exception issue when using lean cli, but when using data folder stuff such as saving new data I see this exception 

Right, the IMapFileProvider needs to be initialized in those use cases too, for example https://github.com/QuantConnect/Lean/blob/master/Tests/TestGlobals.cs#L24 . 
Mind point to exactly what use case reproduces this bug in lean master, what command/entrypoint/configuration is required to reproduce this? or is it a separate custom project/code? Solution is the same though, like done by TestGlobals
