### ISSUE TITLE
question about Python support

### ISSUE THREAD

**Issue by mit10000** [QuantConnect/Lean#6495]
First thanks for the awesome project.
Question about Python support in 
[https://github.com/QuantConnect/Lean/tree/master/Algorithm.Python#python-autocomplete-imports]()
In this sentence

> Copy and paste the imports found [here](https://github.com/QuantConnect/Lean/issues#python-autocomplete-imports) to the top of your project file to enable autocomplete.

What is the **"your project file"** ? Could you please give an example?
Is it Lean/Algorithm.Python/BasicTemplateFrameworkAlgorithm.py in the standard testing case?

**Comment by jaredbroad** [comment]
Hey, we think this is old and will update it today; you should only need:
`from AlgorithmImports import *`
at the top of all your files.

**Comment by mit10000** [comment]
Thanks for your help @jaredbroad !
