### ISSUE TITLE
RSI is not working as it is on TradingView

### ISSUE THREAD

**Issue by borseno** [QuantConnect/Lean#6506]
#### Expected Behavior
I would expect RSI on TradingView and in Lean, with absolutely the same parameters and candle prices, to be the same.

Here is a screenshot of TradingView RSI (period: 10, Resolution: Hour, MovingAverageType.Simple, BTCUSDT) (=~23) 
![image](https://user-images.githubusercontent.com/33373431/180610046-f729613e-1af6-4b9f-a5ad-0b0bb2c0f2d5.png)

The value of such an indicator at such point of time at such market (with such candles history) is ~23.

#### Actual Behavior
I have downloaded and verified that the data fully matches the data on tradingview.

Then I set-up the same indicator: RSI (period: 10, Resolution: Hour, MovingAverageType.Simple, BTCUSDT)

And it produces me this value: 38.47

(The log is: 20220723 16:09:54.208 TRACE:: Log: 30.06.2022 20:00:00 RSI: (38.47717))

#### Potential Solution
I see a lot of complaints about RSI in various issues. I think that it needs to be re-written. If we don't come to the solution in this issue, I could write my own version and submit it to you guys. But for now, I'd like to ask you if you know what the problem is, maybe you can help.

#### Reproducing the Problem
Here is the code that fully reproduces it:
https://github.com/borseno/QuantConnect.Lean.RSI.Issue

I have implemnted an algorithm that initializes RSI in the way I described above, and logged its value at a particular point of time. The result is 38, but it is expected that it is 23.

#### System Information
Windows 10, unactivated
Intel Core i5
Geforce 1080

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by borseno** [comment]
> Hi @borseno ,
> 
> TradingView's RSI uses an exponential moving average in its calculations (I couldn't find a way to set another moving average) while you have selected `MovingAverageType.Simple` in LEAN. Please try using `MovingAverageType.Exponential` instead.
> 
> Could you please provide the RSI values from TradingView? All indicators in LEAN are verified against indicators of third-party software, so we can plug your data into the unit test and verify it.

Hi @AlexCatarino 

I have explicitly selected SMA type of moving average on trading view. 

LEAN Engine: Binance, period: 10, SMA, BTCUSDT, 30.06.2022 20:00:00 UTC = 38.47
TradingView: Binance, period: 10, SMA, BTCUSDT, 30.06.2022 20:00:00 UTC = 25.38

**Comment by borseno** [comment]
In order to select SMA in Lean, you should click on the gear button on the line where the data about indicator settings is written (the line where its written RSI 10 SMA)

**Comment by AlexCatarino** [comment]
Hi @borseno ,

Could you please provide the RSI values from TradingView? All indicators in LEAN are verified against indicators of third-party software, so we can plug your data into the unit test and verify it.

**Comment by borseno** [comment]
> Hi @borseno ,
> 
> Could you please provide the RSI values from TradingView? All indicators in LEAN are verified against indicators of third-party software, so we can plug your data into the unit test and verify it.

I wrote them above.

LEAN Engine: Binance, period: 10, SMA, BTCUSDT, 30.06.2022 20:00:00 UTC = 38.47
TradingView: Binance, period: 10, SMA, BTCUSDT, 30.06.2022 20:00:00 UTC = 25.38

**Comment by borseno** [comment]
That message means that TradingView indicator gives 25.38 value for the Binance exchange, RSI period: 10, moving average type: SMA, symbol: BTCUSDT, the date: 30.06.2022 the time: 20:00:00 UTC

**Comment by borseno** [comment]
Where as the same setup in LEAN produces value of RSI to be 38.47.

**Comment by borseno** [comment]
If that doesnt make sense, please specify what other data do you need ?

**Comment by ArthurAsenheimer** [comment]
Hey @borseno 
I think we have a misunderstanding. 
`RSI(period, MovingAverageType.Simple) != SMA(RSI)
`
The argument MovingAverageType specifies how the RSI values are computed. TradingView, on the other hand, always uses MovingAverageType.Wilders which is also the default in LEAN. The SMA in TradingView means something else, they just apply the SMA on the RSI values. Does that make sense? 

If you want to reproduce this in LEAN you can do 

```Python
rsi = RelativeStrengthIndex(period)       # here default MovingAverageType.Wilders 
rsi_sma = IndicatorExtensions.SMA(rsi, 10)
```

The values will match those from TradingView 100% as you can see in the screenshot below. 
![image](https://user-images.githubusercontent.com/68070194/180958737-10368e39-c575-401f-902f-a4c1ca77a19d.png)

You can reproduce it by cloning this [backtest](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_73fd6b0e210698664ab1564e62309e35.html).

**Comment by borseno** [comment]
> Hey @borseno I think we have a misunderstanding. `RSI(period, MovingAverageType.Simple)` != `SMA(RSI) ` The argument MovingAverageType specifies how the RSI values are computed. TradingView, on the other hand, always uses `MovingAverageType.Wilders` which is also the default in LEAN. The SMA in TradingView means something else here, they just apply the SMA on the RSI values. Does that make sense?
> 
> If you want to reproduce this in LEAN you can do
> 
> ```python
> rsi = RelativeStrengthIndex(period)       # here default MovingAverageType.Wilders 
> rsi_sma = IndicatorExtensions.SMA(rsi, 10)
> ```
> 
> The values match those from TradingView 100% as you can see in the screenshot below. ![image](https://user-images.githubusercontent.com/68070194/180958737-10368e39-c575-401f-902f-a4c1ca77a19d.png)
> 
> You can reproduce it by cloning this [backtest](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_73fd6b0e210698664ab1564e62309e35.html).

Hi,
Thank you for the info.
It gets closer, but not quite identical.
Also, I see the difference between SMA of RSI and RSI itself on the tradingview chart, and we are referring exactly to RSI.
I have just tried to do the following: 

```
_rsi = RSI(symbol, 14, MovingAverageType.Wilders, RESOLUTION);
_rsiSma = IndicatorExtensions.SMA(_rsi, 10);
```

And now, the result that I get in the algorithm is: 
20220726 10:26:53.367 TRACE:: Log: 30.06.2022 20:00:00 RSI: (27,062684046284538373260956008)

Meaning that _rsiSma value at 20:00:00 UTC on 30.06.2022 on Binance.com crypto exchange with the symbol BTCUSDT on spot gives the value 27,062684046284538373260956008.

But, if I open tradingview at that particular moment of time (Binance, BTCUSDT, 30.06.2022, 20:00:00 UTC, Spot) I will get the following results:
![image](https://user-images.githubusercontent.com/33373431/180985462-f208117c-4ab6-4710-bac5-16da274d8e76.png)

1. purple line value is equal to 22.92:
2. yellow line value is equal to 26.76 (closer to the value that I got from lean - 27,06)

Here is what the lines represent in the settings: 
![image](https://user-images.githubusercontent.com/33373431/180985879-6ff5ce7b-4eff-4199-b2ae-8db377d69b49.png)

RSI is the purple line, MA (SMA) of RSI is the yellow one.

So, yellow indeed is closer (26.76 | 27,06 vs 22.92 | 27,06)

But it's not the same, meaning that the math is different. I think that even tiny difference should not be tolerated

Here is my chart: https://www.tradingview.com/chart/SqkM2Caf/?symbol=BINANCE%3ABTCUSDT

**Comment by borseno** [comment]
I have added a new commit according to your suggestion: https://github.com/borseno/QuantConnect.Lean.RSI.Issue/commit/322b32d5db45a6c7a6b309256addadaf5b34667f

**Comment by borseno** [comment]
You might see that I am doing RSI with period of 14 and not 10. I have tried both. And 14 is closer. I also see in the code of tradingview, that they do 14 anyway and then apply period on top of it, so I think thats what we need to do: RSI of 14 and SMA of 10

**Comment by AlexCatarino** [comment]
Thank you for the help, @ArthurAsenheimer .

Hi @borseno ,
To compare the indicators, we need a time series of pricing data (the input) and the indicator values (the output) like this file: [spy_with_indicators.txt](https://github.com/QuantConnect/Lean/blob/master/Tests/TestData/spy_with_indicators.txt). All indicators in Lean are validated against other platforms with unit tests. Here is the unit test for RSI: [RelativeStrengthIndexTests](https://github.com/QuantConnect/Lean/blob/master/Tests/Indicators/RelativeStrengthIndexTests.cs) that uses [spy_with_indicators.txt](https://github.com/QuantConnect/Lean/blob/master/Tests/TestData/spy_with_indicators.txt).

I have looked at TradingView's RSI implementation, and I don't think it's different from Lean's. At least not different enough to explain a big difference (25.38 vs 38.47). 

I want to understand the problem because we have improved our documentation (see [Differences From Third-Party Indicators](https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/key-concepts#11-Differences-From-Third-Party-Indicators)) to address the systematic complaints about indicators.

**Comment by borseno** [comment]
Looks like 

```_rsi = RSI(symbol, 10, MovingAverageType.Wilders, RESOLUTION);``` Is working the same as on the tradingview.
