### ISSUE TITLE
Can get historical tick data with a period-based history request

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6508]
#### Expected Behavior

If we request historical tick data by passing an integer argument, we get an error
```
self.History[Tick](spy, 10, Resolution.Tick)
```

#### Actual Behavior

If we request historical tick data with an integer argument and omit the `resolution` argument, we can get tick data
```
self.History[Tick](spy, 10)
```

#### Potential Solution

N/A

#### Reproducing the Problem

Run
```
class SquareGreenPigeon(QCAlgorithm):

    def Initialize(self):
        self.SetStartDate(2021, 1, 24)  # Set Start Date
        self.SetCash(100000)  # Set Strategy Cash

        spy = self.AddEquity("SPY", Resolution.Tick).Symbol
        history = self.History[Tick](spy, 10)
        self.Debug(f"1: {len(list(history))}")

        history = self.History[Tick](spy, 10, Resolution.Tick)
        self.Debug(f"2: {len(list(history))}")
```
You get
> During the algorithm initialization, the following exception has occurred: History functions that accept a 'periods' parameter can not be used with Resolution.Tick in History.cs:line 374 History functions that accept a 'periods' parameter can not be used with Resolution.Tick
1: 7117

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
See for example the following https://github.com/QuantConnect/Lean/blob/master/Algorithm/QCAlgorithm.History.cs#L374 checks the resolution at the start but if null it will fetch the Tick resolution after the initial `if`
![image](https://user-images.githubusercontent.com/18473240/182967420-39c8aa3a-77a1-4966-8fcf-1d5e36948381.png)
