### ISSUE TITLE
plots of backtesting results

### ISSUE THREAD

**Issue by mit10000** [QuantConnect/Lean#6510]
After running backtesting with algorithm such as MACDTrendAlgorithm, I got statistics on terminals, seems log files are  in
LEAN/Lean/Launcher/bin/Debug/
MACDTrendAlgorithm-log.txt
MACDTrendAlgorithm-order-events.json
MACDTrendAlgorithm.json

Is there any tool to plot these log files and get report? Thanks.

**Comment by Martin-Molinero** [comment]
Hey!
Not at the moment sorry, the GUI was deprecated. We've recently migrated the whole cloud to now run VSCode -- and we're preparing the same VSCode technology to run locally in your desktop.

**Comment by alphaDev23** [comment]
Is there any update on the VSCode GUI running on the desktop?
