### ISSUE TITLE
Future Contract Marked as Non-Tradable Has Data In Slice.FutureChains

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6525]
#### Expected Behavior
If a futures' contract is marked as non-tradable, it shouldn't have data in the `Slice.FutureChains` object and vice-versa.

#### Actual Behavior
If a futures' contract is marked as non-tradable has data in `Slice.FutureChains` object.

#### Potential Solution
N/A

#### Reproducing the Problem
The following algorithm selects `ZC14U21` (expiry 2021-09-14) on 2021-06-15 08:38:00. It shouldn't be filtered out since the filter selects contracts up to 120 days, and this contract expires in 30 days:

```python
from AlgorithmImports import *
class HipsterBlackFrog(QCAlgorithm):

    def Initialize(self):
        self.SetStartDate(2021, 5, 18)
        self.SetEndDate(2021, 6, 30)
        self.ZC = self.AddFuture(Futures.Grains.Corn, Resolution.Minute)
        self.ZC.SetFilter(0, 120)
        self.sessionStartMM = 518

    def OnData(self, data: Slice):
        if self.sessionStartMM == data.Time.hour * 60 + data.Time.minute:
            for chain in data.FutureChains.Values:
                contract = next(contract for contract in chain
                    if contract.Expiry.month in [9])

            if contract:
                if not self.Securities[contract.Symbol].IsTradable:
                    self.Log(f'{self.Time} :: {contract.Symbol.Value}/{contract.Symbol.ID.Date:%y%m%d} is not tradable, but we have data in the FutureChains')
                    return
                self.MarketOrder(contract.Symbol, 1, False) 
                self.MarketOrder(contract.Symbol, -1, False)
```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by kfwojton** [comment]
Odd question, can I just assign myself to this issue and just start working on it?

**Comment by dshulman** [comment]
Hi Martin,

I'm completing a futures issue study and will be sending the results to
Alex when I'm done.  I think that the non-tradable issue is related to a
number of things.  But, you will find that when a continuous future has a
rollover, the expiring Future is marked non-tradable even though it is
still an active and tradable Future until it's actual expiration.

Dave

**Comment by Martin-Molinero** [comment]
This issue no longer reproduces in master, believe it was fixed recently by https://github.com/QuantConnect/Lean/pull/6692
