### ISSUE TITLE
Inconsistency for `Symbol.ID` when using `QuantConnect.Api` services

### ISSUE THREAD

**Issue by ArthurAsenheimer** [QuantConnect/Lean#6568]
#### Expected Behavior

The mapping between `Symbol` and `Symbol.ID` is always unambiguous. 

#### Actual Behavior

The mapping between `Symbol` and `Symbol.ID` is **not** unambiguous in connection with API services.
 For instance, when using `api.ReadBacktestOrders(projectId, backtestId)` I get the following dataframe: 

![image](https://user-images.githubusercontent.com/68070194/186087723-68c293e4-080a-4cd7-a861-d0e3f8ac97c1.png)

As you can see in the screenshot the Symbol-ID of SPY is shown as 'SPY 2T'. This doesn't seem right to me. The correct Symbol-ID for SPY is actually 'SPY R735QTJ8XC9X'. The same applies to other tickers. 

Also, when comparing the symbol `spy1 = qb.AddEquiry('SPY').Symbol` with `spy2 = SymbolCache.GetSymboL('SPY 2T')`, we can see that they don't represent the same Symbol objects. 

![image](https://user-images.githubusercontent.com/68070194/186088739-2ba2e371-06af-4867-8398-571b7b6f1152.png)

This caused unexpected errors in some of my regression tests. I think a Symbol should always map to the same `Symbol.ID` string and vice versa. 

#### Reproducing the Problem

Run this [backtest](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_bd02d5f8ca4540983450e25a4265568a.html). Then open the research environment, replace project ID and backtest ID accordingly and execute the research notebook. 

#### System Information

QC Cloud

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @ArthurAsenheimer!
I've just run this in QC cloud and it seems to be working correctly, is this still happening for you?
![image](https://user-images.githubusercontent.com/18473240/186244364-d252ef6a-9994-4529-96d7-52b85203956d.png)

**Comment by ArthurAsenheimer** [comment]
Hey @Martin-Molinero,
Yes, the problem still exists. 

![image](https://user-images.githubusercontent.com/68070194/186334764-34b8dda4-3a46-4f8d-a038-1e169a224cd5.png)

**Comment by ArthurAsenheimer** [comment]
FYI, I have created a support ticket on this and shared the related project with @AlexCatarino. Hope that helps to reproduce the bug at your end.

**Comment by Martin-Molinero** [comment]
Hey @ArthurAsenheimer! 
Thanks for the report, we've found the underlying issue and have solved it 👍
Just to be clear it wasn't research but that specific backtest result that was faulty, re running the backtest should fix it now, sorry for the inconvenience.
