### ISSUE TITLE
History Request for Tick Does Not Include Trades

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6573]
#### Expected Behavior
Historical data requests for Tick data should include both Trades and Quotes.

#### Actual Behavior
Historical data requests for Tick data only includes Quotes.

#### Potential Solution
N/A

#### Reproducing the Problem
```csharp
namespace QuantConnect.Algorithm.CSharp {
    public class HistoryTickAlgorithm : QCAlgorithm {
        public override void Initialize() {
            SetStartDate(2013, 10, 07);
            SetEndDate(2013, 10, 11);
            var symbol = AddEquity("SPY", Resolution.Tick).Symbol;

            var trades = History<Tick>(symbol, TimeSpan.FromDays(1), Resolution.Tick)
                .Where(x => x.TickType == TickType.Trade).ToList();

            if (trades.Count == 0)
                throw new Exception("No trades");
        }
    }
}
```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by ikamanu** [comment]
💯
