### ISSUE TITLE
`LiveAlgorithmSettings.cs` is missing brokerages

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6587]
#### Expected Behavior

We can deploy live algorithm via the QC API for every supported brokerage in cloud.

#### Actual Behavior

[LiveAlgorithmSettings.cs](https://github.com/QuantConnect/Lean/blob/master/Common/Api/LiveAlgorithmSettings.cs) only has definitions for 6 of the supported brokerages, so we can't deploy live algorithm via the QC API for every supported brokerage.

#### Potential Solution

Add class definitions for the missing brokerages.

#### Reproducing the Problem

See https://github.com/QuantConnect/Lean/blob/master/Common/Api/LiveAlgorithmSettings.cs

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by DerekMelchin** [comment]
The `GDAXLiveAlgorithmSettings` and `TradierLiveAlgorithmSettings` constructors also need an `environment` argument, like how the `OandaLiveAlgorithmSettings` has.

**Comment by Martin-Molinero** [comment]
Closing as we are going to be moving API support to the lean CLI
