### ISSUE TITLE
Review futures market hours data base holidays

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6610]
#### Expected Behavior

Futures contracts are added and removed from the universe based on the `SetFilter` arguments.

#### Actual Behavior

Futures contracts can sometimes be added and removed from the universe, without respecting the `SetFilter` arguments.

#### Potential Solution

N/A

#### Reproducing the Problem

Run this backtest
https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_85086e18feae4ee173d857efa901db56.html

It uses `SetFilter(0, 184)`. On 2016-12-25, contracts are removed from the universe even though they fall within the filter settings. The next day, the contracts are added back to the universe.

![image](https://user-images.githubusercontent.com/38889814/188033897-00b25dc5-4813-4e54-bbe1-4f0cd7d8366d.png)

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
The future chains are driven by the contracts available in the data itself, for 2016-12-25 we have a tiny quote file (few contracts) but it most probably must of been a holiday but it is not defined in the MHDB for the `Future-comex-SI` entry. We should review missing future holidays in the MHDB 👍

**Comment by Martin-Molinero** [comment]
Generically to avoid duplicating `holidays/early close/late open` information we could evaluated storing them just in the null entry `Future-cme-[*]` per asset type & market

**Comment by Martin-Molinero** [comment]
- On requesting the market hours for a symbol we merge that specific symbols entries & it's base `{SecurityType}-{Market}` entries
