### ISSUE TITLE
Index error with Futures data reader

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6613]
#### Expected Behavior

We can run basic Futures algorithms without errors.

#### Actual Behavior

We get 
> Error invoking SI UNT495KXTPR1 data reader. Line: 1 Error: Index was outside the bounds of the array.

#### Potential Solution

N/A

#### Reproducing the Problem

Run these backtests:
- [Silver](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_7f6b15de3a6b26b2ee8df099f748c7c4.html)
- [Gold](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_59f7cb350d2e99bb0e69ef10016c2c39.html)
- [Copper](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_365e647912ef364a927ba55921e77ccb.html)

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
We've reprocessed the related date ranges, this issue has been solved.
