### ISSUE TITLE
Implement BinanceUS Fee Model

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6619]
#### Expected Behavior
Support BinanceUS Fee Model.

#### Actual Behavior
Use Binance Fee Model for both Binance and Binance US

#### Potential Solution
[Binance US Trading Fee Structure](https://www.binance.us/en/fee/schedule) adjust BinanceUSBrokerageModel to return a new Binance US fee model, see if we can reuse `BinanceFeeModel` as base and maybe just override the tier values

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Client request

**Comment by jaredbroad** [comment]
Closing as Binance US shutdown.....

**Comment by Martin-Molinero** [comment]
Closing for now
