### ISSUE TITLE
Time period consolidators have unpredictable consolidation schedules

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6624]
#### Expected Behavior

If we create a time period consolidator to create x-minute bars, the x-minute slices start at midnight.

#### Actual Behavior

If we create a time period consolidator to create x-minute bars, the start time of the first x-minute bar seems random.

#### Potential Solution

Make the schedule of time period consolidators start at midnight.

#### Reproducing the Problem

Run
```
qb = QuantBook()
symbol = qb.AddEquity("SPY").Symbol

consolidator = TradeBarConsolidator(timedelta(minutes=17))
def consolidation_handler(sender: object, consolidated_bar: TradeBar) -> None:
    print(f"Consolidated bar: {consolidated_bar.Time} - {consolidated_bar.EndTime}")
consolidator.DataConsolidated += consolidation_handler

start_time = datetime(2021, 1, 1, 0, 0) - timedelta(minutes=1)
while start_time < datetime(2021, 1, 1, 1, 0):
    start_time += timedelta(minutes=1)
    trade_bar = TradeBar(start_time, symbol, 1, 1, 1, 1, 1, timedelta(minutes=1)) # The datetime is Time, not EndTime
    #print(f'Updating with data {start_time} to {start_time + timedelta(minutes=1)}')
    consolidator.Update(trade_bar)
```
You get
> Consolidated bar: 2020-12-31 23:44:00 - 2021-01-01 00:01:00
Consolidated bar: 2021-01-01 00:01:00 - 2021-01-01 00:18:00
Consolidated bar: 2021-01-01 00:18:00 - 2021-01-01 00:35:00
Consolidated bar: 2021-01-01 00:35:00 - 2021-01-01 00:52:00

In this case, the first consolidated bar spans 17-minutes, but it only consolidated 1 1-minute bar. 

Maybe the consolidator constructors should also check if the day can be evenly divided by the time period. For instance if `1440 % minutes != 0`, throw an error. This way, members will know if the last consolidated bar in a day will be a smaller size than the rest of the bars the consolidator creates.

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
What is the goal of a normal use case? (not QB manufactured)

The TB consolidator is designed to count the minute bars; there are other period based ones who look for specific periods in the data vs the number of bars. The randomness is due to whether there's a bar each minute and when you start the bar.

It would be helpful to know a real-world goal to define the problem better and see if there's an existing solution. 

Closing for now till more information, happy to reopen.
