### ISSUE TITLE
BaseCollection Datasets Aren't Structured Well in DataFrames

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6630]
#### Expected Behavior

If we make a history request for a dataset that uses BaseCollection, the DataFrame has columns for each data property.

#### Actual Behavior

If we make a history request for a dataset that uses BaseCollection, the DataFrame just has a `data` column, which is a list.
![image](https://user-images.githubusercontent.com/38889814/190815145-4e80b26d-ad50-4d7b-825d-4b3ec118806d.png)

#### Potential Solution

If the custom type is BaseCollection, iterate it to build the DataFrame rows.

#### Reproducing the Problem

```
qb = QuantBook()
symbol = qb.AddEquity("AAPL").Symbol
dataset_symbol = qb.AddData(QuiverCongress, symbol).Symbol
qb.History(dataset_symbol, datetime(2022, 1, 1), datetime(2022, 9, 15))
```

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hm this should be covered already by https://github.com/QuantConnect/Lean/blob/master/Algorithm/QCAlgorithm.Python.cs#L1575 `TryCleanupCollectionDataFrame` might need checking out why isn't it not working for this case
