### ISSUE TITLE
Feature request: Debug using ipdb

### ISSUE THREAD

**Issue by vdun** [QuantConnect/Lean#6635]

**Comment by Martin-Molinero** [comment]
Hey @vdun! Thanks for the suggestion. 
We already support various methods, we will skip `ipdb` for now because doesn't seem to be actively maintained, last update 2021/references up to python 3.8.

**Comment by vdun** [comment]
I added 'ipdb' to the project with the command `lean library add 'myProject' 'ipdb'`
But putting the line `import ipdb; ipdb.set_trace()` inside my code and running `lean backtest "myProject"` I do not see the debugging prompt back ?
