### ISSUE TITLE
ApiDataProvider Hour, Daily Data Refresh For Delisted Assets

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#6645]
Hour and daily data do not get re-downloaded when it's out of date. Ideally, the CLI should check the age of the file / the last date of the daily data and decide if we need to attempt to download it again. 

This should factor in the listing status of securities; if out of date and delisted don't attempt to download again.

**Comment by Martin-Molinero** [comment]
> This should factor in the listing status of securities; if out of date and delisted don't attempt to download again.

Keeping issue open to address this part which currently is not taken into account by the ApiDataProvider

**Comment by jaredbroad** [comment]
Closing as ticker reuse and only having the file path means we have to download to ensure the daily data again to ensure have latest. Need a symbol and a date to know for sure whether to download. 

Need to update the API FIle provider to take a symbol or date.
