### ISSUE TITLE
Inconsistent results of `History()` for continuous Futures

### ISSUE THREAD

**Issue by ArthurAsenheimer** [QuantConnect/Lean#6649]
#### Expected Behavior

We get the same result for history requests regardless of whether a Future was added with `Resolution.Tick` or `Resolution.Second`.

#### Actual Behavior

The result depends on the resolution that was passed as an argument in `qb.AddFuture()`. 

#### Reproducing the Problem

Clone [this project](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_c9b26c8387cf4ad440fcbd678c6be3bb.html) and execute the research notebook cells. 

![image](https://user-images.githubusercontent.com/68070194/191719809-8127e34c-0b64-4b80-b521-0ae489edb2db.png)

When we add the Future with `Resolution.Tick` and execute the same history request we get: 

![image](https://user-images.githubusercontent.com/68070194/191720150-325ce3d7-dd88-4718-8a2a-67cad4208703.png)

Obviously there are a lot of data points missing (407 rows vs 600 expected). 

Note, it seems that only data points with time > 16:00 are affected. Maybe this helps to find the cause of this issue. Could be related to the definition of market hours. 

#### System Information

QC Cloud 

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by gmwhipple** [comment]
Any updates? Will this be getting fixed anytime in the near future?

**Comment by Martin-Molinero** [comment]
Hey!
Sorry for the delay here, the difference is due to fill forwarding being enabled, which doesn't apply for tick resolution, believe there is no issue here, see 
![image](https://user-images.githubusercontent.com/18473240/217548034-d409bee6-60de-4d85-97b4-2008c7a1c2d9.png)
