### ISSUE TITLE
Refactor `OrderDirection`

### ISSUE THREAD

**Issue by ArthurAsenheimer** [QuantConnect/Lean#6660]
#### Expected Behavior

`OrderDirection.Buy` belongs to the Enum member with value 1 and `OrderDirection.Sell` belongs to the Enum member with value -1. 

#### Actual Behavior

![image](https://user-images.githubusercontent.com/68070194/192802715-cfaefb5c-0fbb-41b5-8f82-102c44d93af4.png)

This is counterintuitive and doesn't follow the pattern of `InsightDirection`. 

#### System Information

QC Cloud

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @ArthurAsenheimer! This is a good idea but sadly it's not backwards compatible with existing algorithm results

**Comment by ArthurAsenheimer** [comment]
👌

**Comment by jaredbroad** [comment]
I wish we thought of this when we created the enum. Great idea though!
