### ISSUE TITLE
PortfolioStatistics is missing Sortino Ratio

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6665]
#### Expected Behavior

Backtest.TotalPerformance.PortfolioStatistics contains Sortino Ratio

#### Actual Behavior

Backtest.TotalPerformance.PortfolioStatistics doesn't contain Sortino Ratio

#### Potential Solution

Add Backtest.TotalPerformance.PortfolioStatistics.SortinoRatio

#### Reproducing the Problem

N/A

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by DerekMelchin** [comment]
We can't currently add the Sortino Ratio to PortfolioStatistics because the name "Sortino Ratio" is reserved for AlphaRuntimeStatistics. A solution would be to rename the Sortino Ratio in AlphaRuntimeStatistics to something like "Scaled Sortino Ratio". 

This name may be more fitting anyways because the Sortino Ratio in AlphaRuntimeStatistics uses [CompoundingAnnualPerformance](https://github.com/QuantConnect/Lean/blob/f47775338c251e49bca53d2860dd8bca90dcce7b/Common/Statistics/Statistics.cs#L443-L453) (with [365 days](https://github.com/QuantConnect/Lean/blob/78a9d2566fbf30ec125c0e7195e169b81a17cc04/Common/Statistics/FitnessScoreManager.cs#L102-L121)) as the numerator. In contrast, the **Sharpe** ratio in PortfolioStatistics uses [AnnualPerformance](https://github.com/QuantConnect/Lean/blob/f47775338c251e49bca53d2860dd8bca90dcce7b/Common/Statistics/Statistics.cs#L462-L465) (with 252 days) as the numerator. If we add Sortino ratio to PortfolioStatistics, it would likely use the same numerator as the Sharpe ratio, which would cause the current regression tests to fail.

**Comment by Martin-Molinero** [comment]
Duplicated of https://github.com/QuantConnect/Lean/issues/5594
