### ISSUE TITLE
Crypto Order Fee Does Not Respect Lot Size When Necessary

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6666]
#### Expected Behavior
When the order fee currency is the crypto pair's base currency, the order fee must respect the lot size since the security quantity respects the lot size.

#### Actual Behavior
Crypto Order Fee does not respect lot size when necessary. In this case, the algorithm cannot close the position.
Example:
Buy 0.00006111 BTCUSD @ 19066 -> Quantity: 0.00006098778
When we place an order to sell 0.00006098778 of BTCUSD, it's rounded down to respect the lot size
Sell 0.00006098 BTCUSD @ 19063 -> Quantity: 0.00000000778
We cannot sell the residual because it's smaller than the lot size.

#### Potential Solution
Adapt the `ModifiedFillQuantityOrderFee` to handle this case, or fix fee models individually.
If the fee is lower than the lot size, we can assume the lot size like [Kraken](https://support.kraken.com/hc/en-us/articles/201893638-How-trading-fees-work-on-Kraken):
_There is a minimum trade fee entered as the minimum amount as per precision on that pair being traded. This impacts trades of small value that may not have the decimal precision needed to create a ledger entry._

#### Reproducing the Problem
```csharp
namespace QuantConnect.Algorithm.CSharp {
    public class HyperActiveYellowGreenViper : QCAlgorithm {
        private Symbol _symbol;

        public override void Initialize() {
            SetStartDate(2022, 9, 25);
            SetEndDate(StartDate.AddDays(1));
            SetCash(100);
            SetBrokerageModel(BrokerageName.Bitfinex);
            _symbol = AddCrypto("BTCUSD", market: Market.Bitfinex).Symbol;
        }

        public override void OnData(Slice data) {
            if (!Portfolio.Invested) {
                MarketOrder(_symbol, 0.00006111);
                return;
            }

            var quantity = Portfolio[_symbol].Quantity;
            if (quantity == 0) return;
            MarketOrder(_symbol, -quantity);
        }
    }
}
```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jhonabreul** [comment]
This is and excerpt of a support chat with Bitfinex:

> (03:51:02) | Agustina: Hi, thank you for contacting Bitfinex Live Support. My name is Agustina how can I help you today?
> (03:51:17) | Visitor 95578125: Hi there
> (03:51:30) | Visitor 95578125: I have a question about fees and lot size and how Bitifnex handles it
> (03:51:52) | Agustina: ok
> (03:52:21) | Visitor 95578125: Lets say I place market order with quantity 0.00006111 for BTCUSD
> (03:52:31) | Visitor 95578125: The fee would be 0.00000012222
> (03:52:57) | Visitor 95578125: I will get 0.00061097778, right? But that is not respecting the lot size for the security which is 0.00000001
> (03:53:50) | Agustina: Please allow me a moment to look into your inquiry.
> (03:54:34) | Visitor 95578125: thank you
> (04:01:13) | Agustina: It's due to User Interface, what you see is the rounded number, but in the backend it is calculated with the precise number by our system.
> (04:04:02) | Visitor 95578125: But if the lot size is something like 0.001, you can trade 0.0012?
> (04:09:31) | Agustina: That's not possible. Here you have the minimum size rquired https://api.bitfinex.com/v1/symbols_details
> (04:09:49) | Agustina: All above the minimum will be ok
> (04:14:00) | Visitor 95578125: If the fee is not respecting the lot size, then what will happen?
> (04:14:09) | Visitor 95578125: The fees will get rounded to the lot size?
> (04:15:10) | Agustina: The fees will not be rounded, there will be charged as normal
> (04:16:27) | Visitor 95578125: So the fees are not calculated in the base currency?
> (04:17:53) | Visitor 95578125: If I buy 0.006 BTCUSD and the price is 100 and the fee is 0.2%, the fee is calculated ass 0.000012 BTC or 0.002 USD?
> (04:19:39) | Agustina: You can choose in which currency you will be charged in this link: https://setting.bitfinex.com/account#fees
> (04:25:46) | Agustina: The fee calculation is correct, it depends on what you choose in your settings which one would be paid.

It seems the fees are not rounded but they are charged normally

**Comment by jhonabreul** [comment]
This is an excerpt of a chat with Binance support. According to them, there is no rounding off involved in the fee calculations

<img width="351" alt="image" src="https://user-images.githubusercontent.com/25215064/203381945-beff1202-7728-4ec1-8e33-0e055eea1ff0.png">
