### ISSUE TITLE
Add Method That Converts Value to Static Class Attribute Name

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6668]
#### Expected Behavior
Be able to find the class attribute given the value.

#### Actual Behavior
If we make a history request of Fundamental data in Python, we will get the code (e.g. 101) instead of a string representation of `MorningstarSectorCode.BasicMaterials`, so we need to rely on external sources to find the correspondence.

It would be a nice-to-have feature for data visualization.

#### Potential Solution
N/A

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Believe this issue is no longer valid since it has been addressed in the last Fundamental refactor push
<img width="799" alt="image" src="https://github.com/QuantConnect/Lean/assets/18473240/d81c00bc-0f48-421a-8ceb-db09962e3953">
