### ISSUE TITLE
Improve Memory Handling in Research Notebook

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6681]
#### Expected Behavior
The Research Environment has a garbage-collecting feature.

#### Actual Behavior
The Research Environment doesn't have a garbage-collecting feature. If we use data from History requests, we can't dispose of it to free memory up and continue to run the same notebook.

```python
import gc
import psutil

# instantiate thq quantbook
qb = QuantBook()

# load equity symbol_ids from the object store and add them to the quantbook
symbol_ids = '''AMD,NVDA,AMZN,META,GOOGL,GOOG,SHOP,OXY,
RBLX,MU,XOM,BABA,GM,PLUG,SQ,ORCL,PYPL,DVN,CVX,COIN,JPM,
SLB,AFRM,SBUX,LI,TSM,MRVL,DIS,UAL,MS,ROKU,NEE,U,APA,EQT,
CVNA,PDD,QCOM,AA,RCL,COP,FDX,BA,LVS,PENN,CRM,UPST,ABNB,
SCHW,GE,WMT,NKE,AMAT,AR,DOW,MOS,ON,RUN,DT,PG,MPC,MMM,DASH,
RTX,ASAN,DOCU,ZIM,JD,WDC,ARRY,FTNT,BTU,ENVX,AIG,OKTA,GIS,
BYND,TWLO,NET,TMUS,FISV,MET,MCHP,SE,LTHM,W,VLO,CVS,IBM,PM,
TJX,DDOG,RRC,BX,WYNN,CTVA,ZM,CZR,TTD,Z,CHWY,GME,RIO,PSX,BHP,
CTSH,MTCH,DD,EOG,PBF,ADI,OVV,APP,AXP,EXPE,CF,ADM,COF,YUMC,
LYB,OKE,FSLR,AEM,BLDR,ETSY,CNQ,DLTR,PVH,NOVA,EMR,NUE,AEP,
ICE,S,SPR,PGR,NTR,FANG,LAC,BBY,APH,MAR,STX,HLT,MP,BE,DUK,
ANET,HES,MNST,TTE,CPRI,LYV,BIDU,SPLK,CHK,PRU,SWKS,STLD,CC,SYY,RNG'''.split(',')

for symbol_id in symbol_ids:
    qb.AddEquity(symbol_id)

# define a function (closure) to perform the history request
def history_function(qb):
    df_history = qb.History(
        qb.Securities.Keys,
        datetime(2010, 1, 1),
        datetime(2022, 1, 1),
        Resolution.Daily,
    )
    print(f"Dataframe size: {df_history.memory_usage().sum() / 1e6:.1f} MB")
    del df_history

print(
    f"Memory usage before calling the function: {psutil.virtual_memory().used / 1e9:.3f} / "
    f"{psutil.virtual_memory().total / 1e9:.1f} GB "
    f"({psutil.virtual_memory().percent}%)"
)

# run the function with the history request and subsequently collect the garbage
history_function(qb)
gc.collect()

print(
    f"Memory usage after calling the function: {psutil.virtual_memory().used / 1e9:.3f} / "
    f"{psutil.virtual_memory().total / 1e9:.1f} GB "
    f"({psutil.virtual_memory().percent}%)"
)

# delete the quantbook and subsequently collect the garbage
del qb
gc.collect()

print(
    f"Memory usage after deleting the qb: {psutil.virtual_memory().used / 1e9:.3f} / "
    f"{psutil.virtual_memory().total / 1e9:.1f} GB "
    f"({psutil.virtual_memory().percent}%)"
)
```
Result:
```
Memory usage before calling the function: 37.296 / 135.0 GB (28.6%)
Dataframe size: 15.2 MB
Memory usage after calling the function: 38.463 / 135.0 GB (29.5%)
Memory usage after deleting the qb: 38.463 / 135.0 GB (29.5%)
```
We can see there is no significant or no drop in memory consumption. It's sort of expected because Python's `gc.collect` doesn't collect garbage for C# objects.

#### Potential Solution
N/A 

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by cperotlsq** [comment]
From a user perspective: if one has a notebook that performs a large history request that results in ~500MB of data in the Python namespace, but the history request ends up allocating ~10GB of memory in the backend, this can leave the user with very little usable RAM to continue working in the notebook. Is there any way to get around this, @Martin-Molinero, @AlexCatarino? 

It seems the only way to do so is to save the resulting data to the object store, restart the kernel, re-run all of the notebook up to history request, and then load the resulting data from the object store, which isn't very convenient.

**Comment by Martin-Molinero** [comment]
Hey @cperotlsq!
We've been working on this, and pushed a few improvements at https://github.com/QuantConnect/Lean/pull/6700.
Another workaround to avoid having to restart the kernel is:
```
from System import *
for x in range(0, 40):
    GC.Collect()
```

**Comment by cperotlsq** [comment]
Hey @Martin-Molinero, thanks for looking into this and implementing some improvements! I do start to see the memory usage decrease after running this, but it takes some time for it to do so, and not necessarily to the level it would be without restarting the kernel and loading the corresponding data from the object store. Nonetheless, this is an improvement :)

I am curious, why do we need to collect the garbage 40 times?

**Comment by Martin-Molinero** [comment]
Hey!
> thanks for looking into this and implementing some improvements!

Thanks for the report :), we will circle back to this again soon and push another improvement.

> not necessarily to the level it would be without restarting the kernel

Yes, this is somewhat expected, it's created the QB, loaded 4k securities, loaded map/factor files, object store, etc.

> I am curious, why do we need to collect the garbage 40 times?

Not 100% sure, it's what it takes roughly, it's a progressive operation. Think it's somewhat related to the GC settings we are using

**Comment by jaredbroad** [comment]
- Potentially adding a way to clear or disable the hour and daily caches.

**Comment by Martin-Molinero** [comment]
- In the static constructor of the QuantBook we can trigger a timer every 20 second to perform a GC.Collect operation
