### ISSUE TITLE
Library request: TALib (.NET)

### ISSUE THREAD

**Issue by tactevo** [QuantConnect/Lean#6689]
[TALib](https://sourceforge.net/projects/ta-lib/) is a technical analysis library that includes some indicators that are not part of the QuantConnect standard indicator set, for instance **Hilbert Transform - Dominant Cycle Period**.    The Python library for TALib is already available in Lean, but the .NET library is not.

It is understood that adding the TALib c# library to Lean would not, in and of itself, make TALib indicators available as a Lean Indicator.  Using TALib with Lean would require additional bridge/wrapper work by individual developers to be useful.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
We can add the library but couldn't make the bridge. Ideally, the required indicators would be ported into the streaming LEAN format which is supported deeper by the engine with consolidators and different data types, and Fields. 

If there are other TA's not in LEAN indicator format already please add them as separate issues and they're great first issues for new team members or contributors.

**Comment by jaredbroad** [comment]
https://github.com/QuantConnect/Lean/issues/7026
https://github.com/QuantConnect/Lean/issues/7027
Replacing request with these two issues above.
