### ISSUE TITLE
Depth / Candle Charts using TradeBar

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#669]
Create an intuitive way for users to create candle charts using a TradeBar object for better custom plotting.

Reference: [Plot minute candle stick](https://www.quantconnect.com/forum/discussion/1582/plot-minute-candle-stick).

**Comment by jandykwan** [comment]
two years, any update?

**Comment by worthy7** [comment]
Jusssst coming around to wanting this too. Any progress?

**Comment by fera0013** [comment]
Any news on this issue?

**Comment by ttodua** [comment]
Strange that it is not supported. So much needed feature.

**Comment by jacektrocinski** [comment]
Any updates on this?

**Comment by nicbyron** [comment]
Just invested a lot of time learning this platform assuming that doing something as simple as charting price candles would be part of the platform, and I would be able to do this to visually verify my algorithm is doing what I want it to do... only to find this isn't possible and now I have no idea how I will verify if it's working how I want it to except for getting the charts elsewhere and then checking the points manually, which is obviously beyond tedious. 

Why is there no update on this?

**Comment by raymond-holmboe** [comment]
any update on this?

**Comment by GitTorres** [comment]
Ready for this feature in 2022 :)

**Comment by kipi999** [comment]
Issue created in 2016 and still no solution? I don't know how other users can work without this fundamental feature. How can we make sure that we won't wait next 5 years for it? Guess I will have to move back to MetaTrader :/

**Comment by paryas** [comment]
Any ETA on this? This is one of the most important and fundamental features for any team/company to start developing their own strategy. I do understand the difficulty of implementing this, but lack of this feature is preventing many traders to switch to this platform. My company is browsing different platforms to move from the MT4 and so far this is a BLOCKER for us to switch to QuantConnect

Thanks

**Comment by wesleyfsmith** [comment]
This is also something I would really like to see, would help a lot with visual confirmation of trades

**Comment by rafael-or** [comment]
Come on Guys 6 Years and this is very helpful when visualising if the strategy is working as it should or not. Let's put some effort into this shaw we?

**Comment by bskdany** [comment]
> Ready for this feature in 2022 :)

yeah you wish, we're getting to 2023 and still nothing

**Comment by jaredbroad** [comment]
Sorry guys charting is high on the list including trade overlay for Q1-Q2 🙏 Thank you for your insane patience.

**Comment by DukeBot18** [comment]
Is there anyway to chart different resolution candle charts yet, I'd like to make sure my values for custom indicators are correct and a visual inspection is important.

**Comment by jaredbroad** [comment]
@DukeBot18 @lorenzolashkiba @bskdany @rafael-or @wesleyfsmith @paryas @kacperg95 @GitTorres @raymond-holmboe @nicbyron @ttodua @jacektrocinski @fera0013 @worthy7 @jandykwan Candlesticks Shipped! 🎉🎉 Thank you for your patience. You can see the API documentation here: https://www.quantconnect.com/docs/v2/writing-algorithms/charting#06-Plot-Candlestick
