### ISSUE TITLE
Of Indicator Extension Doesn't Follow Order of Operations for Updates

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6708]
#### Expected Behavior

If we create an `Of` indicator extension and then `Update` it, it updates the RHS indicator with the `input` and then updates the LHS indicator with the output of the RHS indicator.

#### Actual Behavior

If we create an `Of` indicator extension and then `Update` it, it updates the LHS indicator with the `input`.

#### Potential Solution

Change the `Update` behavior of the `Of` indicator extension so that it follows the correct order of operations.

#### Reproducing the Problem

Run [this backtest](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_c84a4f811174dae57674129032221946.html). We get 
> Samples: ROC=0; MAX=10; indicator=10

[This backtest ](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_55f613f85549ea7f02fee918dda4c54f.html) also highlights the issue.

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
>If we create an Of indicator extension 

`Of` is not creating a new indicator but returning the given one. In this case `indicator` is the maximum indicator instance, which is the one that will be receiving the update calls, believe this is to allow chaining it further. See https://github.com/QuantConnect/Lean/blob/master/Indicators/IndicatorExtensions.cs#L51

```
        public override void Initialize()
        {
            var roc = new RateOfChange(1);
            var max = new Maximum(10);
            var indicator = (max).Of(roc);
            
            for(var i = 0; i < 10; i++)
            {
                indicator.Update(new DateTime(), 1m);
            }

            Quit($"Samples: ROC={roc.Samples}; MAX={max.Samples}; indicator={indicator.Samples}");
        }
```
