### ISSUE TITLE
Library request: pytables

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6711]
[PyTables](https://www.pytables.org/) is a package for managing hierarchical datasets and designed to efficiently and easily cope with extremely large amounts of data.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed in favor of https://github.com/QuantConnect/Lean/issues/6901.
Both fastparquet and pytables are prerequisites for pandas [to_parquet](https://pandas.pydata.org/pandas-docs/version/1.1/reference/api/pandas.DataFrame.to_parquet.html) and [to_hdf](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_hdf.html) respectively.
