### ISSUE TITLE
Library request: DoubleML

### ISSUE THREAD

**Issue by cperotlsq** [QuantConnect/Lean#6716]
Hello QC Team,

Would it be possible to get [DoubleML](https://github.com/DoubleML/doubleml-for-py) in the QC environment? The Python package DoubleML provides an implementation of the double / debiased machine learning framework of [Chernozhukov et al. (2018)](https://doi.org/10.1111/ectj.12097). It is built on top of [scikit-learn](https://scikit-learn.org/) (Pedregosa et al., 2011).

Thanks in advance,
Cameron

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/7028
