### ISSUE TITLE
Enable Custom OptionStrategyPositionGroupBuyingPowerModel

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6721]
#### Expected Behavior
Be able to customize a `PositionGroupBuyingPowerModel` to not block orders due to insufficient buying power models for strategies that are not implemented.

#### Actual Behavior
Insufficient buying power messages for strategies that are not implemented.

#### Potential Solution
N/A. 
Ideally, we should cover all strategies.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
Isn't the work around here using a NullMarginModel which would disable the margin checks entirely?
