### ISSUE TITLE
Minimum stop/limit and entry order distance

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#673]
Some brokerages limit how close stop and limit orders can be opened to the current market price.
This feature would prevent users from placing invalid order orders in live mode and improve reality modelling.

**Comment by mchandschuh** [comment]
@AlexCatarino  -- is this handled by `IBrokerageModel.CanSubmitOrder` ?

**Comment by AlexCatarino** [comment]
@mchandschuh , it is not.
This is the sort of message we would get:
```
Order rejected: Order price too far from market price :1.35639 vs 1.36128 affected Order: Sell 1000 Limit @ 1.3627” is a message generated from the strategy.
```
I don't know whether it is still an issue in live trading since I couldn't find any reference of this in FXCM or other supported brokerages.

**Comment by StefanoRaggi** [comment]
The maximum allowed order distance from market price seems to be a brokerage-specific setting or rule, apparently undocumented, so I don't think we can model it.
