### ISSUE TITLE
Unable to Get Order Id with Async Market Orders 

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#6736]
It would be nice if async market orders return the order id before triggering an order event. 

#### Expected Behavior
Market orders would take 10ms to fill. 

#### Actual Behavior
Market orders taking 0ms to fill

#### Potential Solution
 - 

#### Reproducing the Problem
#region imports
from AlgorithmImports import *
#endregion
import copy

class TrailingStopLoss(QCAlgorithm):
    
    def Initialize(self):
        self.SetStartDate(2022, 11, 1)
        self.SetEndDate(2022, 11, 1)
        self.SetCash(100000)
        self.equity = self.AddEquity("QQQ", Resolution.Second)
        self.symbol = self.equity.Symbol
        self.Consolidate(self.symbol, timedelta(minutes=1), self.minConsolidator)

        # ignore fees for now
        self.equity.SetFeeModel(ConstantFeeModel(0))

        #self.Schedule.On(self.DateRules.EveryDay(self.symbol), 
        #    self.TimeRules.Every(timedelta(seconds=1)),
        #    self.closePosition)

        self.trade_count = 0
        self.Count = 0
        self.con_count = 0
        self.last_order = 'None'
        self.ticket = None

    # NOTE: consolidator event is called BEFORE the onData in case they both need to
    # be called
    # a TraderBar object is passed in
    def minConsolidator(self, bar):
        if self.trade_count < 3:
            # buy
            self.ticket = self.MarketOrder(self.symbol, 100, True)
            self.Debug(f"{self.Time}: BUY: {bar.Price}, orderId: {self.ticket.OrderId}")
            self.last_order = 'Buy'
            self.trade_count += 1

    def OnData(self, data):
        return

        if self.symbol not in data:
            return

        if not data.Bars.ContainsKey(self.symbol):
            return

        # close a previous order if there is one
        if self.Portfolio[self.symbol].Invested:
            if self.Time.second > 58:
                self.Debug(f"{self.Time}: close QQQ,{self.Securities[self.symbol].BidPrice}, {self.Securities[self.symbol].AskPrice}")
                self.Liquidate(self.symbol)
        return

    def OnOrderEvent(self, orderEvent):
        if self.ticket is not None:
            self.Debug(f"{self.Time}: OnOrder: ticket.orderId: {self.ticket.OrderId}, event.orderId: {orderEvent.OrderId}, status: {orderEvent.Status}")
        else:
            self.Debug(f"{self.Time}: OnOrder: self.ticket is None, event.orderId: {orderEvent.OrderId}, status: {orderEvent.Status}")

LOGS
----

2022-11-01 09:31:00: OnOrder: self.ticket is None, event.orderId: 1, status: 1
2022-11-01 09:31:00: OnOrder: self.ticket is None, event.orderId: 1, status: 3
2022-11-01 09:31:00: BUY: 281.69, orderId: 1

2022-11-01 09:32:00: OnOrder: ticket.orderId: 1, event.orderId: 2, status: 1
2022-11-01 09:32:00: OnOrder: ticket.orderId: 1, event.orderId: 2, status: 3
2022-11-01 09:32:00: BUY: 281.28, orderId: 2

2022-11-01 09:33:00: OnOrder: ticket.orderId: 2, event.orderId: 3, status: 1
2022-11-01 09:33:00: OnOrder: ticket.orderId: 2, event.orderId: 3, status: 3
2022-11-01 09:33:00: BUY: 281.6, orderId: 3
 
#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by HaakonFlaaronning** [comment]
I have encountered the same problem with limit orders in paper trading (not so much during backtesting). The ticket should at least be returned before a Filled order status enters OnOrderEvent for that ticket. In my opinion, the ticket should be available before any event for that ticket is fired in OnOrderEvent (including New, Submitted, Invalid etc).

**Comment by Martin-Molinero** [comment]
- Add `OrderTicket Ticket { get; set; }` to the order event to be set by the BrokerageTransactionHandler when handling order events, this way the user/algorithm does not need to worry about matching order event to ticket
