### ISSUE TITLE
Library Request https://github.com/leon-thomm/Ryven

### ISSUE THREAD

**Issue by QuantDeveloperUSA** [QuantConnect/Lean#6739]
#### Expected Behavior
Allow the usage of Ryven to build scripts visually 
#### Actual Behavior

Library Not Available

#### Potential Solution

Add the library

#### Reproducing the Problem

Does not apply

#### System Information

Does not apply

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Thank you for the issue. Due to the CLI nature of the foundation, we cannot support this library.
