### ISSUE TITLE
Library Request: Jupyter Dash

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6741]
[Plotly's Jupyter Dash](https://github.com/plotly/jupyter-dash) makes it easy to develop Plotly Dash apps interactively from within Jupyter environments (e.g. classic Notebook, JupyterLab, Visual Studio Code notebooks, nteract, PyCharm notebooks, etc.).

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
@SnoozeThis Until October 2023

**Comment by SnoozeThis** [comment]
I don't understand what you want to wait for (unknown domain Until; auto-detection temporarily failed). See https://snoozethis.com/commands/ for examples.

**Comment by jaredbroad** [comment]
@SnoozeThis wait for 6 months

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/WOLgtJK_Wmw) I will wait until Fri, 01 Sep 2023 15:25:46 UTC and then reassign to you.

**Comment by SnoozeThis** [comment]
Resolved.
