### ISSUE TITLE
Runtime Statistics Currency Conversion and Formating

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6742]
#### Expected Behavior

If we set the account currency to BTC, the runtime statistics are valued in BTC and have the same number of as decimals as BTC.

#### Actual Behavior

If we set the account currency to BTC, the runtime statistics have the BTC currency symbol, but the value and rounding is the same as dollars.

#### Potential Solution

N/A

#### Reproducing the Problem

Run [this backtest](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_cb805e612e8577647945ae48f06429da.html). The Equity runtime statistic is `₿100,005.88`.

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
>If we set the account currency to BTC, the runtime statistics have the BTC currency symbol, but the value and rounding is the same as dollars.

By default the initial cash is set to 100K of the account currency, the shared algorithm has 100k BTC and 100K USD which is ~5 BTC extra, 
![image](https://user-images.githubusercontent.com/18473240/201766502-8394a669-87e2-472e-b936-0a24f19e8ec3.png)

**Comment by jaredbroad** [comment]
Seems odd the `self.SetCash("USD", 100000)`  would result in 100K BTC. If not a bug in runtime statistics, then seems like a bug in setting cash.
