### ISSUE TITLE
Missing Arguments for History Template Functions

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6750]
#### Expected Behavior

We can call 
```
self.History[TradeBar](self.symbol, datetime(2021, 5, 1), datetime(2021, 5, 4), Resolution.Minute, extendedMarket=True)
```
without error.

#### Actual Behavior

We get
> During the algorithm initialization, the following exception has occurred: Trying to dynamically access a method that does not exist throws a TypeError exception. To prevent the exception, ensure each parameter type matches those required by the 'int'>) method. Please checkout the API documentation.
  at Initialize
    history = self.History[TradeBar](self.symbol in main.py: line 10
 No method matches given arguments for History: (<class 'QuantConnect.Symbol'>, <class 'datetime.datetime'>, <class 'datetime.datetime'>, <class 'int'>)

But we can use
```
self.History(self.symbol, datetime(2021, 5, 1), datetime(2021, 5, 4), Resolution.Minute, extendedMarket=True)
```
without error.

#### Potential Solution

N/A

#### Reproducing the Problem

https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_b1047f9d35eeeb1aa8580f764e31869b.html

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jhonabreul** [comment]
It seems there are missing overloads in the C# API:

```csharp
IEnumerable<TradeBar> History(Symbol symbol, DateTime start, DateTime end, Resolution? resolution = null, 
    bool? fillForward = null, bool? extendedMarket = null, DataMappingMode? dataMappingMode = null,
    DataNormalizationMode? dataNormalizationMode = null, int? contractDepthOffset = null);
    
IEnumerable<T> History<T>(Symbol symbol, DateTime start, DateTime end, Resolution? resolution = null, 
    bool? fillForward = null, bool? extendedMarket = null, DataMappingMode? dataMappingMode = null,
    DataNormalizationMode? dataNormalizationMode = null, int? contractDepthOffset = null);

IEnumerable<DataDictionary<T>> History<T>(IEnumerable<Symbol> symbols, DateTime start, DateTime end, 
    Resolution? resolution = null, bool? fillForward = null, bool? extendedMarket = null, 
    DataMappingMode? dataMappingMode = null, DataNormalizationMode? dataNormalizationMode = null,
    int? contractDepthOffset = null);
```

**Comment by ArthurAsenheimer** [comment]
The same applies to other arguments such as `fillForward`. 
I'd like to use `self.History[TradeBar](symbol, start, end, resolutio, fillForward=True)` but got the same error as describe by @DerekMelchin .
