### ISSUE TITLE
MOC fill price for Daily and Tick resolution mismatch

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6770]
#### Expected Behavior

If we submit a MOC order, the fill price should be the same, regardless of the data resolution.

#### Actual Behavior

The fill price of MOC orders is different depending on if we use daily data or tick data.

#### Potential Solution

N/A

#### Reproducing the Problem

If we [backtest with daily data](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_a413041123e01375a4f279d484885e42.html), the orders fill as expected.

If we [backtest with regular trading hours tick data](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_8505be59501a430a76c40e329ca25779.html), the order tag says
> No trade  with the OfficialClose or ClosingPrints flag for data that does not  include extended market hours. Fill with last Trade data.

If we [backtest with extended market hours tick data](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_17dcf2b0b979e1ba06a71ed6d98da463.html), the order tag says
> No trade with the OfficialClose or ClosingPrints flag within the 1-minute timeout. Fill with last Trade data.

#### System Information

QC Cloud.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
- Review fill model to determine why didn't it find the official close tick (even when using extended market hours)
