### ISSUE TITLE
Leverage not working anymore

### ISSUE THREAD

**Issue by stefan-j** [QuantConnect/Lean#678]
I am unsure how regularly changes are pushed to QuantConnect. However, recently leverage isn't working as usual anymore. 

Buying on margin with both SetHoldings (with arg > 1) and MarketOrder worked on the 5th Jan. Since today SetHoldings seems to have no effect with (arg > 1) and MarketOrder results in a invalid order. I have set the leverage via SetLeverage as well without success.

[Example backtest](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_cc5cf84484811315b311fb5cef0a64c7.html) where SetHoldings(5) results in the same behavior as SetHoldings(1). Changing it to MarketOrder(16000) would result in the order getting filled the same as MarketOrder(8000). On the Oanda brokerage it would result in an invalid order.

**Comment by stefan-j** [comment]
I'm not exactly sure what the changes where, but the leverage defaults to 1 in the initialization (or after).  From a glance this seems to have been introduced in the merging of PR #675 in commit fe58550f447b7d5a6e8645e40f4a026e6690b5f3 .

The workaround I'm currently using is to set the leverage manually _after_ the initialization.

**Comment by jaredbroad** [comment]
Thanks @stefan-j -- fixed in #679
