### ISSUE TITLE
Delisting assets handling

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#6790]
#### Expected Behavior

- In live trading & backtesting, delisted assets are set as untradable and delisted when appropriate 
#### Actual Behavior

- Currently only for backtesting we are setting untradable/delisted securities
- Missing `SecurityChanges` algorithm call
- Note positions are being set to 0/liquidated as expected
- Open positions?
See https://github.com/QuantConnect/Lean/pull/6059 &  https://github.com/QuantConnect/Lean/pull/5203

#### Potential Solution

- Review live brokerage IB delisting handling and timing to correctly handle this. 
#### Reproducing the Problem

N/A
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by DerekMelchin** [comment]
Related to this issue, we see in [this example](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_9e23b4b8b84a6af571e199550f552720.html) that we are warned about SCG delisting on 2018-12-31, but then SCG is present in the fundamental universe selection function the next day

![image](https://github.com/QuantConnect/Lean/assets/38889814/cf52b7d5-e985-43cc-ad04-82bde791018b)

**Comment by Martin-Molinero** [comment]
Double check https://github.com/QuantConnect/Lean/pull/7573 has solve the original issue



> Related to this issue, we see in [this example](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_9e23b4b8b84a6af571e199550f552720.html) that we are warned about SCG delisting on 2018-12-31, but then SCG is present in the fundamental universe selection function the next day
> 
> ![image](https://private-user-images.githubusercontent.com/38889814/301322090-cf52b7d5-e985-43cc-ad04-82bde791018b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMzkwOTIsIm5iZiI6MTcwNzIzODc5MiwicGF0aCI6Ii8zODg4OTgxNC8zMDEzMjIwOTAtY2Y1MmI3ZDUtZTk4NS00M2NjLWFkMDQtODJiZGU3OTEwMThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDE2NTk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2OWU2OTcyYTdlMjYxNTFlNDRhODE2Mjg2ZWFiMzNiNjNjNDlkYjZkYjkxMTg0MTRmOTFhZjAwYmRmNjY2NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MQmYXsk6-2F6smBXpyN7BLB2h7E2FNFNuuuT8HN8D-k)

We can directly adjust coarse selection not to add assets which are going tot be delisted in 24/48 hours

**Comment by Martin-Molinero** [comment]
Original issue has been solved, with https://github.com/QuantConnect/Lean/pull/7774 live equity delisting will be driven by mapfiles.
Leaving this issue open so we tackle live delisting on announcement/before it happens. Which would allow us to tackle DM comment above for coarse too.
