### ISSUE TITLE
Null Holdings In Live Packet

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6801]
#### Expected Behavior
Live results packet should not have null holdings:

#### Actual Behavior
Live results packet with null holdings leading to empty Holdings Tab:

![Console](https://user-images.githubusercontent.com/6889033/207666814-d99259ae-ebdc-438c-bcb6-0bf17b4aa41d.png)

![View](https://user-images.githubusercontent.com/6889033/207666868-63e2d654-b941-4b96-b652-7350ee767aae.png)

#### Potential Solution
N/A

#### Reproducing the Problem
Private support report. I wasn't able to reproduce the issue with a simple algorithm. The algorithm uses universe selection and daily resolution data, and it's deployed to IBKR paper.

#### System Information
QuantConnect Cloud

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Closing since this was due to the host running out of memory.
