### ISSUE TITLE
AddData is returing SecurityType = 0, which means we cannot live trading

### ISSUE THREAD

**Issue by melkayam92** [QuantConnect/Lean#6808]
I'm trying to run locally the lean-cli with Interactive broker + custom data feed. 

#### Expected Behavior
I'm trying to add custom data:

`
self.symbol_SPY_min = self.AddData(
            YahooDataLive, "SPY", Resolution.Minute, TimeZones.Utc
        )
`

Which works for me, but when trying to buy with this: 

`self.MarketOrder(self.symbol_SPY_min, 1)`

I'm getting an error that this is unsupported type base.

#### Actual Behavior
I'm getting an error that this is unsupported type base.

#### Potential Solution
I tried to find ways to override the secuirty type, but no success

**Comment by Martin-Molinero** [comment]
Hey @melkayam92!
Suggest not creating a custom data type but just directly use `AddEquity()` and place the data in the expected location in the data folder.

**Comment by choesy** [comment]
Hi, could you please elaborate on the AddEquity() with custom data? Because I have the same problem but with using crypto data that is hosted on github in raw file.

**Comment by Martin-Molinero** [comment]
Hey @choesy! Please take a look at our documentation https://www.quantconnect.com/docs/v2/writing-algorithms/importing-data/key-concepts
