### ISSUE TITLE
Beta in backtest report was not accurate

### ISSUE THREAD

**Issue by LouisSzeto** [QuantConnect/Lean#6810]
#### Expected Behavior
Beta should be the covariance between benchmark and portfolio series. For a replicated portfolio of SPY, with benchmark SPY, the beta and any rolling beta should be very close to 1.

#### Actual Behavior
The rolling beta plot was not following the above logic. Example in [this forum post](https://www.quantconnect.com/forum/discussion/14579/spy-market-beta-on-backtest-near-0/p1).

#### Potential Solution
The [report charting method for beta](https://github.com/QuantConnect/Lean/blob/3c6ae2f1e7cdccb0d47d6e0a9bef6216f8f41443/Report/ReportCharts.py#L644) should follow the report metric and beta indicator calculation

#### Reproducing the Problem
https://www.quantconnect.com/forum/discussion/14579/spy-market-beta-on-backtest-near-0/p1

#### System Information
N/A

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
- Report generator has it's own implementation of the statistics, see `Rolling.cs` in the report project, we could replace these by the same statistics classes used in backtest see `StatisticsBuilder` & `PortfolioStatistics`
