### ISSUE TITLE
Consolidate method doesn't provide correct bar type

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6814]
#### Expected Behavior

If we call
```
self.Consolidate(self.symbol, timedelta(minutes=1), TickType.Quote, self.consolidation_handler)
```
we get QuoteBar objects in the consolidation handler.

#### Actual Behavior

We get TradeBar objects.

#### Potential Solution

- Fix consolidator resolve for Tick resolution see https://github.com/QuantConnect/Lean/blob/master/Algorithm/QCAlgorithm.Python.cs#L1241. Is this a typo or on purpose -> review blame
- Add regression algorithm reproducing issue in master C#/Py

#### Reproducing the Problem

https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_a6028adc0e76218827cb02848032976c.html

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
See https://github.com/QuantConnect/Lean/pull/6876#issuecomment-1412752381
