### ISSUE TITLE
Liquidate Method Does Not Have Asynchronous and OrderProperties Option

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6818]
#### Expected Behavior
The `Liquidate` method can place asynchronous orders not set the order properties.

#### Actual Behavior
`Liquidate` once place synchronous orders or set their properties.

#### Potential Solution
Option 1: The signature of the order methods in QCAlgorithm has the asynchronous parameter before the tag, so we should not add a parameter at the end. Instead, we need more method overloads. 
Option 2: If the first argument is `null`, Liquidate should be asynchronous.

#### Reproducing the Problem
N/A. I noticed that a live algorithm wanted to open and close positions asynchronously. While there is an option using market orders to open the positions, it used Liquidate to close them and the orders were synchronous.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
- Obsolete current `List<int> Liquidate(Symbol symbolToLiquidate, string tag)` -> remove optional args
	- Create new
		- `List<OrderTicket> Liquidate(PyObject symbols, bool asynchronous = false, string tag = "Liquidated", IOrderProperties orderProperties = null)`
			- internally can resolve 'symbols' even if it's 1 instance or N, see & use `ConvertToSymbolEnumerable`
		- `List<OrderTicket> Liquidate(IEnumerable<Symbol> symbols, bool asynchronous = false, string tag = "Liquidated", IOrderProperties orderProperties = null)`
		- `List<OrderTicket> Liquidate(Symbol symbol = null, bool asynchronous = false, string tag = "Liquidated", IOrderProperties orderProperties = null)`
			- the new `Liquidate()` target
	- All the liquidate methods should share the same core implementation
	- Should all new tests for all these new methods C# & Py
	
Note: this will be a breaking change because of the return type changing, from List<int> to List<OrderTicket>
