### ISSUE TITLE
Inaccurate equity margin requirement for limit order

### ISSUE THREAD

**Issue by LouisSzeto** [QuantConnect/Lean#6846]
#### Expected Behavior
Based on the [description of IB](https://www.interactivebrokers.com/en/trading/margin-stocks.php), the margin requirement of equities should be based on the stock value to be purchased, not the current value of the stock.
i.e. `min{current / limit price} * quantity * margin factor` should be required for limit order when checking submitted order

#### Actual Behavior
`current value of stocks * quantity * margin factor` is required for limit order

#### Reproducing the Problem
https://www.quantconnect.com/forum/discussion/14666/limitorder-requires-margin-based-on-current-close-price-not-on-limit-price/p1
backtest: https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_4531fc381d219373d9293f0a38e43feb.html
The expected behavior was tested on IB. 

#### System Information
NA

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by dhilgarth** [comment]
I'm no longer sure this is actually a bug. I tested it in a live account on Interactive Brokers and the margin requirement was always more or less the same, no matter the limit price I entered:

Limit 150:
![image](https://user-images.githubusercontent.com/1180105/211551437-76088b1f-341d-4487-8d67-00b8616dfb23.png)

Limit 15:
![image](https://user-images.githubusercontent.com/1180105/211551463-d04b985e-5b40-41e4-94f6-c7fabd24d91e.png)

**Comment by Martin-Molinero** [comment]
Hey!

> I'm no longer sure this is actually a bug. I tested it in a live account on Interactive Brokers and the margin requirement was always more or less the same, no matter the limit price I entered:

Yes we found the same behavior, we were actually using entry price for margin calculation back in 2019 and we fixed it to use current asset value, take a look at the refactor which has a detailed explanation and examples https://github.com/QuantConnect/Lean/pull/3768.
Will close the issue for now 👌
