### ISSUE TITLE
Feature request: Coarse selection following ETF Constituent Universe

### ISSUE THREAD

**Issue by LouisSzeto** [QuantConnect/Lean#6848]
#### Expected Behavior
To allow coarse universe selection within/after ETF constituent universe selection.

#### Actual Behavior
Only the following overloading is provided:
```
Universe QuantConnect.Algorithm.QCAlgorithm.AddUniverse (
 Universe universe,
 Func<IEnumerable<FineFundamental>, IEnumerable<Symbol>> fineSelector
)
```
and no `Volume` property for ETF constituent object.

#### Potential Solution
(1) provide the overloading
```
Universe QuantConnect.Algorithm.QCAlgorithm.AddUniverse (
 Universe universe,
 Func<IEnumerable<CoarseFundamental>, IEnumerable<Symbol>>coarseSelector
)
```
or

(2) Add a `Volume` property to ETF constituent object.

#### Reproducing the Problem
NA

#### System Information
NA

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Please provide more information about the underlying issue
