### ISSUE TITLE
BacktestingChainProvider Requires Minute Resolution Data

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6853]
#### Expected Behavior
The `BacktestingChainProvider` uses available data to determine the available option contracts. if the minute is not available.

#### Actual Behavior
The `BacktestingChainProvider` only tries to use minute data to determine the available option contracts.

#### Potential Solution
N/A

#### Reproducing the Problem
Run `BasicTemplateOptionsHourlyAlgorithm` for a period that has hourly data but not minute data.
Ref.: Community Forum Post: [LEAN CLI Options Backtest Requires Minute Data Despite Hour Resolution](https://www.quantconnect.com/forum/discussion/14698/lean-cli-options-backtest-requires-minute-data-despite-hour-resolution)

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by nathanmargaglio** [comment]
Do we have a general outline for how we can go about resolving this? I can give it a shot if I can get some direction.
