### ISSUE TITLE
Crypto Future Fee Model

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6856]
#### Expected Behavior
CryptoFuture fee structure is different from crypto-spot.

#### Actual Behavior
We use the same maker/taker rates for CryptoFuture and Crypto.

#### Potential Solution
- Create new `BinanceFuturesFeeModel` to be used by `BinanceFuturesBrokerageModel.GetFeeModel` override
- Create new `BinanceCoinFuturesFeeModel` to be used by `BinanceCoinFuturesBrokerageModel.GetFeeModel` override
- For each apply maker/taker fees as specified by Binance https://www.binance.com/en/fee/futureFee. Maker and taker rate fees can be arguments and we default to tier 1
- Add unit tests for each

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by MarcellThoth** [comment]
Thanks Alex! Great! Looking forward to this.
