### ISSUE TITLE
`GetOptionContractList` Doesn't Work Well With Weekly Index Options

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6872]
#### Expected Behavior

We can use `GetOptionContractList` to get a list of weekly Index Option contracts

#### Actual Behavior

If we use 
```
self.OptionChainProvider.GetOptionContractList(underlying_index_symbol, self.Time)
```
we get standard contracts and no weekly contracts.

If we use 
```
canonical_symbol = Symbol.CreateCanonicalOption(underlying_index_symbol, "SPXW", Market.USA, "?SPXW")
self.OptionChainProvider.GetOptionContractList(canonical_symbol, self.Time)
```
we get standard and weekly contracts.

#### Potential Solution

Add a target option overload
```
GetOptionContractList(underlying_index_symbol, "SPXW", self.Time)
```

#### Reproducing the Problem

https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_3077084cfe997ccd41f8076981d24eeb.html

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
`SPXW` have weeklies and the normal monthly contracts (see https://github.com/QuantConnect/Lean/blob/master/Common/Securities/IndexOption/IndexOptionSymbol.cs#L73) https://www.cboe.com/tradable_products/sp_500/spx_weekly_options/specifications. Closing issue for now
IB ref
![image](https://user-images.githubusercontent.com/18473240/217826543-03aa9222-3562-40cf-8cd4-f8c08253af2d.png)
![image](https://user-images.githubusercontent.com/18473240/217826570-530cab3d-f2ee-49d5-9ca1-b9877271b79e.png)
