### ISSUE TITLE
Library request: Tabulator

### ISSUE THREAD

**Issue by ArthurAsenheimer** [QuantConnect/Lean#6896]
[Tabulator](https://tabulator.info/) is an easy to use interactive table generation JavaScript library. It allows you to create interactive tables in seconds from any HTML Table, JavaScript Array or JSON formatted data. Tabulator is packed with useful features including filters, sorting, grouping, formatting, editing, callbacks, CSS styling, row selection and many more. 

Tabulator is open source and [can be used in connection with Panel](https://pyviz-dev.github.io/panel/reference/widgets/Tabulator.html).  Link to GitHub repository: [tabulator](https://github.com/olifolkerd/tabulator#npm-installation).  

#### Potential Solution

```
npm install tabulator-tables --save 
```

#### Reproducing the Problem

Run the code below: 

```Python
import datetime as dt
import numpy as np
import pandas as pd
import panel as pn

np.random.seed(7)
pn.extension('tabulator', css_files=[pn.io.resources.CSS_URLS['font-awesome']])

df = pd.DataFrame({
    'int': [1, 2, 3],
    'float': [3.14, 6.28, 9.42],
    'str': ['A', 'B', 'C'],
    'bool': [True, False, True],
    'date': [dt.date(2019, 1, 1), dt.date(2020, 1, 1), dt.date(2020, 1, 10)],
    'datetime': [dt.datetime(2019, 1, 1, 10), dt.datetime(2020, 1, 1, 12), dt.datetime(2020, 1, 10, 13)]
}, index=[1, 2, 3])

tabulator_formatters = {
    'float': {'type': 'progress', 'max': 10},
    'bool': {'type': 'tickCross'}
}

pn.widgets.Tabulator(df, formatters=tabulator_formatters)
```

**Output**:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
File /opt/miniconda3/lib/python3.8/site-packages/IPython/core/formatters.py:972, in MimeBundleFormatter.__call__(self, obj, include, exclude)
    969     method = get_real_method(obj, self.print_method)
    971     if method is not None:
--> 972         return method(include=include, exclude=exclude)
    973     return None
    974 else:

File /opt/miniconda3/lib/python3.8/site-packages/panel/viewable.py:616, in Viewable._repr_mimebundle_(self, include, exclude)
    613     loaded = hv.extension._loaded
    615 if config.comms in ('vscode', 'ipywidgets'):
--> 616     widget = ipywidget(self)
    617     if hasattr(widget, '_repr_mimebundle_'):
    618         return widget._repr_mimebundle_(include=include, exclude=exclude)

File /opt/miniconda3/lib/python3.8/site-packages/panel/io/notebook.py:384, in ipywidget(obj, **kwargs)
    367 def ipywidget(obj: Any, **kwargs: Any):
    368     """
    369     Returns an ipywidget model which renders the Panel object.
    370 
   (...)
    382     Returns an ipywidget model which renders the Panel object.
    383     """
--> 384     from jupyter_bokeh.widgets import BokehModel
    386     from ..pane import panel
    387     model = panel(obj, **kwargs).get_root()

ModuleNotFoundError: No module named 'jupyter_bokeh'
Tabulator(formatters={'float': {'type': 'progre...}, value=   int  float s...)
```

Note, the output indicates that the error occurs due to the missing module `jupyter_bokeh` (refer to #6895). However, even with `jupyter_bokeh` installed, we would still get an error due to the missing Tabulator library. 

On my local machine where I have Tabulator installed, the output looks as follows: 

![AnimationTabulatorPanel](https://user-images.githubusercontent.com/68070194/214325710-19cb0b48-f304-41bb-8200-d706dd9da061.gif)

#### System Information

QC Cloud 

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Excellent library; we're updating the foundation images now and will include them this week.
