### ISSUE TITLE
add IndexOption-india to market hour database

### ISSUE THREAD

**Issue by Amol-Gupta** [QuantConnect/Lean#6908]
#### Expected Behavior

IndexOption-india should be present in market hour database

#### Potential Solution

Add IndexOption-india to market hour databse
#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closing for now since it's not supported
