### ISSUE TITLE
New broker to be added. Pepperstone

### ISSUE THREAD

**Issue by groombridgedevelopment** [QuantConnect/Lean#6910]
Hi, I am told to submit a ticket here for any new broker suggestions. Have you guys thought about adding Pepperstone to the brokers supported? If not, I am looking adding it myself.

**Comment by groombridgedevelopment** [comment]
Hi, Any updates here?

**Comment by jaredbroad** [comment]
Guide to contributing brokerages - https://www.quantconnect.com/docs/v2/lean-engine/contributions/brokerages/setting-up-your-environment would be another new repo.
