### ISSUE TITLE
Iron Condor is not supported by `OptionStrategies`

### ISSUE THREAD

**Issue by LouisSzeto** [QuantConnect/Lean#6917]
#### Expected Behavior
`OptionStrategies.IronCondor` is supported for easy abstracted usage.
Reference: https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/option-strategies/iron-condor

#### Actual Behavior
It is not supported.

#### Potential Solution
`OptionStrategies.IronCondor(symbol, farOtmPutStrike, nearOtmPutStrike, nearOtmCallStrike, farOtmCallStrike, expiry)`
where `farOtmPutStrike` < `nearOtmPutStrike` < `nearOtmCallStrike` < `farOtmCallStrike`. Basically like 2 Strangles with opposite direction.

`OptionStrategies.IronCondor(symbol, nearLegStrikeFromATM, farLegStrikeFromATM, expiry)`
It would be great if one of the overloads has only 2 strike arguments since for the basic version, the width between the 2 OTM calls should be the same as the 2 OTM puts, in which their distance between ATM contract should also be the same.

#### Reproducing the Problem
NA

#### System Information
NA

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jhonabreul** [comment]
Closed by #7305
