### ISSUE TITLE
Missing `___LiveAlgorithmSettings` class for some brokerages

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6920]
#### Expected Behavior

We can use the `CreateLiveAlgorithm` to deploy algorithms for all the supported brokerages.

#### Actual Behavior

We only have `BitfinexLiveAlgorithmSettings`, `GDAXLiveAlgorithmSettings`, `InteractiveBrokersLiveAlgorithmSettings`, `OandaLiveAlgorithmSettings`, `DefaultLiveAlgorithmSettings`, and `TradierLiveAlgorithmSettings`

#### Potential Solution

Add classes for the missing brokerages

#### Reproducing the Problem

N/A

#### System Information

N/A

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closing as we are going to be moving API support to the lean CLI
