### ISSUE TITLE
`ReadLiveAlgorithm` silently fails 

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6926]
#### Expected Behavior

`ReadLiveAlgorithm` works as expected.

#### Actual Behavior

`ReadLiveAlgorithm` silently fails, so `.Success` is always false.
Input:
```
{"projectId":13944816,"deployId":"L-fb4326db82fce5057b27d3c27b52fbc2"}
```
Result:
```
{"errors":["Invalid argument"],"success":false}
```

#### Potential Solution

N/A

#### Reproducing the Problem

Call `ReadLiveAlgorithm` and then access the `.Success` property of the result.

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closing as we are going to be moving API support to the lean CLI
