### ISSUE TITLE
Automatically Add Alt Dataset When Requesting Alt Universe

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#6935]
#### Expected Behavior
When using alternative data universe the underlying symbol AND the alternative data should be added to the algorithm. Its a little counter intuitive to only add the equity prices

#### Actual Behavior
Only price data added when doing a universe subscription for alt data.

#### Potential Solution
Add the alt data for the symbol instead of forcing the user to do it in OnSecuritiesChanged()

#### Reproducing the Problem
```
# region imports
from AlgorithmImports import *
# endregion

class ChainedUniverseAlgorithm(QCAlgorithm):

    coarse = None
    universe_coarse = None
    universe_twitter = None

    def Initialize(self):
        self.SetCash(100000)
        self.SetStartDate(2023, 1, 2)
        self.universe_coarse = self.AddUniverse(self.CoarseFilterFunction)
        self.universe_twitter = self.AddUniverse(QuiverQuantTwitterFollowersUniverse, "QuiverQuantTwitterFollowersUniverse", Resolution.Daily, self.FollowerSelection)

    def CoarseFilterFunction(self, coarse: List[CoarseFundamental]) -> List[Symbol]:
        sorted_by_dollar_volume = sorted(coarse, key=lambda x: x.DollarVolume, reverse=True) 
        self.coarse = [c.Symbol for c in sorted_by_dollar_volume[:100]]
        return Universe.Unchanged

    def FollowerSelection(self, alt_coarse: List[QuiverQuantTwitterFollowersUniverse]) -> List[Symbol]:
        self.followers = [d.Symbol for d in alt_coarse if d.Followers > 200000 and d.WeekPercentChange > 0]
        return list(set(self.coarse) & set(self.followers))

    def OnSecuritiesChanged(self, changes):
        for added in changes.AddedSecurities:          ### IDEALLY NOT REQUIRED.
            self.AddData(QuiverQuantTwitterFollowers, added.Symbol) 

    def OnData(self, data):
        # Prices in the slice from the universe selection
        # Alternative data in slice from OnSecuritiesChanged Addition
        # for ticker,bar in data.Bars.items():
        #     pass
        for dataset_symbol, data_point in data.Get(QuiverQuantTwitterFollowers).items():
            self.Debug(f"{dataset_symbol} followers at {data.Time}: {data_point.Followers}")

```

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
- Review & test example algorithm:
    - returning both underlying & custom data symbol in the selection of `FollowerSelection`
    - using universe extensions chain operations to avoid keeping state on the algorithm and making the selection delay shorter
