### ISSUE TITLE
Brokerage Models Support More Order Types than the Brokerage Implementation

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6937]
#### Expected Behavior

The brokerage models only let us create orders that the respective brokerage integration supports.

#### Actual Behavior

- The [ZerodhaBrokerageModel](https://github.com/QuantConnect/Lean/blob/master/Common/Brokerages/ZerodhaBrokerageModel.cs) lets us create orders of any order type, but the [ZerodhaBrokerage](https://github.com/QuantConnect/Lean.Brokerages.Zerodha/blob/master/QuantConnect.ZerodhaBrokerage/ZerodhaBrokerage.cs#L514:L531) only supports a subset of the order types.
- The [TradierBrokerageModel](https://github.com/QuantConnect/Lean/blob/master/Common/Brokerages/TradierBrokerageModel.cs) lets us create orders of any order type except MOO and MOC, but the [TradierBrokerage](https://github.com/QuantConnect/Lean.Brokerages.Tradier/blob/master/QuantConnect.TradierBrokerage/TradierBrokerage.cs#L1450:L1469) only supports market, limit, stop limit, and stop market orders.

There may be other brokerages with this issue

#### Potential Solution

- Update the `CanSubmitOrder` of each brokerage model to reflect the supported order types of the brokerage integration.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

**Comment by abhi-kr-2100** [comment]
First time contributor here. I would like to work on this issue.

While updating each `CanSubmitOrder` will work, I'm thinking of validating the order type the same way time in force is being validated inside `CanSubmitOrder`: https://github.com/QuantConnect/Lean/blob/master/Common/Brokerages/ZerodhaBrokerageModel.cs#L106

Do you see any issues with this approach?

**Comment by abhi-kr-2100** [comment]
I've added a pull request to address this issue. I found that some brokerage models do validate orders; in those cases, I've not verified if they validate orders correctly. I couldn't find the implementations of some others.

Aside: The different models implement `CanSubmitOrder` quite differently. There should be a refactoring.
