### ISSUE TITLE
Future Fill Model Should Fill Stop Market Order Outside Market Hours

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6948]
#### Expected Behavior
Futures fill model fills stop market orders outside market hours.

#### Actual Behavior
Futures fill model doesn't fill stop market orders outside market hours. it inherits this behavior from the `FillModel`.

#### Potential Solution
Implement `StopMarketFill` in the `FutureFillModel` to override the default behavior.

#### Reproducing the Problem
```csharp
namespace QuantConnect.Algorithm.CSharp
{
    public class GeekyYellowKangaroo : QCAlgorithm
    {
        private OrderTicket _ticket;
        public override void Initialize()
        {
            SetStartDate(2023, 2, 1);
            
            var future = AddFuture(Futures.Indices.NASDAQ100EMini, 
                extendedMarketHours:true);

            Schedule.On(DateRules.Today, TimeRules.At(19,0),
            () => 
            {
                MarketOrder(future.Mapped, 1);
                _ticket = StopMarketOrder(future.Mapped, -1, future.Price*0.999m);
            });
        }

        public override void OnData(Slice slice)
        {
            if (_ticket == null || _ticket.Status != OrderStatus.Submitted) return;
            var stopPrice = _ticket.Get(OrderField.StopPrice);
            var bar = Securities[_ticket.Symbol].Cache.GetData<TradeBar>();
            if (stopPrice > bar.Low) Log($"{stopPrice} -> {bar.Low}");
        }
    }
}
```

The log will show that the low is lower than the stop price, but 7 pm is extended market hours. The order is filled when the market opens (RTH) on Feb 6th.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by connorjohnlind** [comment]
Any timeline on this fix? I'm totally blocked by this.
