### ISSUE TITLE
Unable to start an algorithm when there's an Oanda StopMarketOrder order open

### ISSUE THREAD

**Issue by benletchford** [QuantConnect/Lean#6965]
#### Expected Behavior

You're able to start an algorithm even with a StopMarketOrder open (works for LimitOrder)

#### Actual Behavior

<img width="650" alt="Screenshot 2023-02-14 at 9 06 51 PM" src="https://user-images.githubusercontent.com/6703966/218951216-f9cda4bb-6795-4749-a561-ce4055391e0e.png">

#### Potential Solution

Translate the Oanda `MarketIfTouchedOrder` order object to `StopMarketOrder` correctly (ref: https://github.com/QuantConnect/Lean.Brokerages.OANDA/blob/3fda74d210e7b73fce6e12f6db74aa7c58605702/QuantConnect.OandaBrokerage/OandaRestApiV20.cs#L623) 

I've opened a PR for this [here](https://github.com/QuantConnect/Lean.Brokerages.OANDA/pull/6)

#### Reproducing the Problem

Have an open StopMarketorder when deploying your algorithm.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by benletchford** [comment]
I've opened a PR against Lean.Brokerages.OANDA [here](https://github.com/QuantConnect/Lean.Brokerages.OANDA/pull/6).

**Comment by Martin-Molinero** [comment]
Thanks for the fix @benletchford! It's available in production starting from lean version `15136`

**Comment by benletchford** [comment]
Confirmed that it's fixed the issue!

Thanks for being awesome :)

<img width="969" alt="Screenshot 2023-02-16 at 11 54 12 AM" src="https://user-images.githubusercontent.com/6703966/219230048-bc0b9b3f-7cc1-481a-b815-a607c02a6162.png">
