### ISSUE TITLE
Review Fill Model: Limit Fill

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6973]
#### Expected Behavior
[Limit Orders](https://www.interactivebrokers.com/en/index.php?f=593):

>Step 1 – Enter a Limit Buy Order
>XYZ stock has a current Ask price of 34.00 and you want to use a Limit order to buy 100 shares when the market price falls to 33.50.
>You create the Limit order as shown above.
>Step 2 – Order Transmitted, Market Price Begins to Fall
>As soon as you transmit your Limit order, the market price of XYZ stock begins to fall.
>Step 3 – Market Price Falls to Limit Price, Order Filled
>The market price of XYZ continues to fall until it touches your Limit Price of 33.50. Your order for 100 shares is filled.
>where the market price is the market offer.

#### Actual Behavior
`FillModel.LimitFill` uses **quote** data to trigger the order.

#### Potential Solution
Remove the `FillModel.GetPrices` logic and write the `LimitFill` method to use `Tick.Trade` or `TradeBar` properties. We need to create unit tests that cover all scenarios and security types. For instance, Forex and CFD don't have trade data.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Community issue here: https://github.com/QuantConnect/Lean/issues/963

Closing the original issue to track here in a centralized way linked to our research and PRs (https://github.com/QuantConnect/Lean/issues/4567)
