### ISSUE TITLE
Implements Correlation as Lean Indicator

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6983]
#### Expected Behavior
Lean supports Correlation as a Lean Indicator which takes a Symbol object, a benchmark Symbol, and a look-back period. 

#### Actual Behavior
Not supported. See #83

#### Potential Solution
Implement this indicator. 

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by LouisSzeto** [comment]
[spy_qqq_corr.csv](https://github.com/QuantConnect/Lean/files/10822689/spy_qqq_corr.csv)

**Comment by LouisSzeto** [comment]
[spy_qqq_corr.csv](https://github.com/QuantConnect/Lean/files/13114332/spy_qqq_corr.csv)
columns: "SPY close" "QQQ close" "annual correlation"

script:
```
import talib

qb = QuantBook()

spy = qb.AddEquity("SPY", Resolution.Daily).Symbol
qqq = qb.AddEquity("QQQ", Resolution.Daily).Symbol

history = qb.History([spy, qqq], datetime(1998, 1, 1), datetime(2023, 2, 23))

close = history.loc[spy].close

# Assumes no risk free rate
history2 = pd.concat([close, history.loc[qqq].close], axis=1).dropna()
history2.columns = [spy, qqq]

corr = history2.rolling(252).corr().unstack(1)[spy][qqq].dropna().to_frame()
corr.columns = ["corr"]
corr["spy close"] = close
corr["qqq close"] = history2.iloc[:, 1]
corr = corr.iloc[:, [1, 2, 0]].dropna()
corr.to_csv("spy_qqq_corr.csv", header=False)
```
