### ISSUE TITLE
Implement Alpha Indicator

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6985]
#### Expected Behavior
Lean supports Alpha as a Lean Indicator which takes a Symbol object, a benchmark Symbol, and a look-back period. 

#### Actual Behavior
Not implemented. See #83.

#### Potential Solution
 - Implement Alpha Indicator in a similar way to Beta

Follow this interface:
```
A(Symbol target, Symbol reference, int period, Resolution? resolution = null)
Alpha(Symbol target, Symbol reference, int period)
Alpha(string name, Symbol target, Symbol reference, int period)
```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by LouisSzeto** [comment]
This one doesn't have a talib implementation, but it could be as easy as `alpha = return - riskfree rate - beta()`, in which can be done with our existing indicators:
Return : `RateOfChange(1)`
Beta: `Beta(same window)`
Risk free rate can be implemented as an arbitrary number, or from some benchmark return series.

**Comment by LouisSzeto** [comment]
[qqq_alpha.csv](https://github.com/QuantConnect/Lean/files/10822653/qqq_alpha.csv)
[spy_alpha.csv](https://github.com/QuantConnect/Lean/files/10822654/spy_alpha.csv)

**Comment by anbe6083** [comment]
Hi there, I'm interested in taking this on. Please be patient with me, as I'm new to this project 😃 

Taking a look in `QuantConnect.Benchmarks`, I see two classes, `FuncBenchmark` and` SecurityBenchmark`, are these appropriate classes to use to calculate the benchmark return? Both have an Evaluate method and seem so, but just wanted to clarify.

**Comment by alexander-myltsev** [comment]
@LouisSzeto I don't understand your notation :) By chance, expand it, please. Better, if you know the code implementation, share, please.

**Comment by LouisSzeto** [comment]
[spy_alpha.csv](https://github.com/QuantConnect/Lean/files/13114233/spy_alpha.csv)
Columns: "SPY close" "benchmark(QQQ) close" "alpha"

[qqq_alpha.csv](https://github.com/QuantConnect/Lean/files/13114234/qqq_alpha.csv)
Columns: "QQQ close" "benchmark(SPY) close" "alpha"

script:
```
import talib

qb = QuantBook()

spy = qb.AddEquity("SPY", Resolution.Daily).Symbol
qqq = qb.AddEquity("QQQ", Resolution.Daily).Symbol

history = qb.History([spy, qqq], datetime(1998, 1, 1), datetime(2023, 2, 23))

close = history.loc[spy].close

# Assumes no risk free rate
history2 = pd.concat([close, history.loc[qqq].close], axis=1).dropna()
history2.columns = [spy, qqq]

alpha_spy = (ret.loc[history2.index, spy] - talib.BETA(history2[spy], history2[qqq], 252).values * ret.loc[history2.index, qqq]).to_frame()
alpha_spy["spy close"] = close
alpha_spy["qqq close"] = history2.iloc[:, 1]
alpha_spy = alpha_spy.iloc[:, [1, 2, 0]].dropna()
alpha_spy.to_csv("spy_alpha.csv", header=False)

alpha_qqq = (ret.loc[history2.index, qqq] - talib.BETA(history2[qqq], history2[spy], 252).values * ret.loc[history2.index, spy]).to_frame()
alpha_qqq["qqq close"] = history2.iloc[:, 1]
alpha_qqq["spy close"] = close
alpha_qqq = alpha_qqq.iloc[:, [1, 2, 0]].dropna()
alpha_qqq.to_csv("qqq_alpha.csv", header=False)
```
