### ISSUE TITLE
Implements Hilbert Transform Indicator

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6986]
#### Expected Behavior
Lean supports Hilbert Transform indicator

#### Actual Behavior
Not supported. See #83.

#### Potential Solution
Implement the Hilbert Transform Indicator:

> The Hilbert Transform Indicator was authored by John Ehlers. The Hilbert Transform itself, is an all-pass filter used in digital signal processing. By using present and prior price differences, and some feedback, price values are split into their complex number components of real (inPhase) and imaginary (quadrature) parts. The user may change the input (midpoint), and period length. This indicator’s definition is further expressed in the condensed code given in the calculation below.

Source: https://www.motivewave.com/studies/hilbert_transform_indicator.htm

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by LouisSzeto** [comment]
There are 6 talib indicators
[spy_ht_trendline.csv](https://github.com/QuantConnect/Lean/files/10812718/spy_ht_trendline.csv)
[spy_ht_dcperiod.csv](https://github.com/QuantConnect/Lean/files/10812719/spy_ht_dcperiod.csv)
[spy_ht_trendmode.csv](https://github.com/QuantConnect/Lean/files/10812720/spy_ht_trendmode.csv)
[spy_ht_dcphasor.csv](https://github.com/QuantConnect/Lean/files/10812721/spy_ht_dcphasor.csv)
Phasor component has 2 series (time/in phase/quadrature)
[spy_ht_sine.csv](https://github.com/QuantConnect/Lean/files/10812722/spy_ht_sine.csv)
Sine wave also has 2 series (time/real part/imaginary part)
[spy_ht_dcphase.csv](https://github.com/QuantConnect/Lean/files/10812724/spy_ht_dcphase.csv)

**Comment by alexander-myltsev** [comment]
Seems like correct C# implementation, right? 

https://github.com/ooples/OoplesFinance.StockIndicators/blob/be83f40b547301aae7d0196b1255f4eed38d61e9/src/Calculations/Ehlers.cs#L3781-L3823

**Comment by alexander-myltsev** [comment]
Please, review https://github.com/alexander-myltsev/Lean/tree/feature-hilbert-transform
