### ISSUE TITLE
Implements Time Series Forecast (TSF)

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6988]
#### Expected Behavior
Lean support the Time Series Forecast (TSF) Indicator.

#### Actual Behavior
Not supported. See #83.

#### Potential Solution
> The Time Series Forecast is a smoothing functions that works by preforming linear least squares regression over a moving window. It then uses the linear model to predict the value for the next bar.

Source: https://tulipindicators.org/tsf

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by krutik2966** [comment]
@jaredbroad, I am interested in working on this issue.
