### ISSUE TITLE
[Feature] Create CCI Indicator

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#7]
Create an "CommodityChannelIndex" indicator class and the associated "ATR" helper method in the QCAlgorithm base class. See introduction to indicators - https://lean.quantconnect.com/docs#topic9.html

Add the associated tests to Tests project under /Indicators to confirm the Commodity Channel Index values match up with the data provided in /Tests/TestData/spy_with_cci.txt file.

**Comment by mchandschuh** [comment]
great code!! thanks for the effort!!

**Comment by mattmast** [comment]
Thanks! I didn't realize my push would end up here with referencing the issue.  Still new to github and contributing and what not.

**Comment by mattmast** [comment]
Hi Jared,
Where was the data exported from for the spy_with_cci.txt file?  I'm getting slightly different results in the 3rd or 4th decimal places.

**Comment by mchandschuh** [comment]
We export the data using http://www.freestockcharts.com/'s export chart data feature.

I wouldn't worry about that level of error. You can submit the pull request and Jared or I will take a peek.

**Comment by jaredbroad** [comment]
Close with #7f340a56dd299a6233427d73d6231fc7520419aa
