### ISSUE TITLE
Tests for Base Security Class (Security object)

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#70]
Security class is fundamental entity representing an asset object in Lean. For the long term future of Lean we need solid tests which cover this object to ensure future changes don't break current behavior.

Following test-driven-design we must break testing units into their smallest components. For Security we need to test each property and method, and that changes to its internals, then make sure its still behaving.

To test Security we propose the following steps, first create a security test file in the tests project.

1. Init Security object with configuration object and update its holdings to a known state.

2. Test simple properties: e.g. Test security.Symbol is same as config.Symbol which constructed it. (Symbol, Type, Resolution, IsFillForward, IsExtendedMarketHours, SubscriptionDataConfig, MarginModel.Leverage == Leverage initializer, 

3. Test holdings properties behave as expected: HoldStock,Invested true when long or short, 

3. Test Methods:  Updating the security with price data causes the price property to change.

4. SetLeverage() command updates the security.Leverage value.

5. Test constructor - Verify the state of the internal initialization is as expected (e.g. Cache == typeof SecurityCache() class for each of the objects initialized in the constructor)

**Comment by AnObfuscator** [comment]
Is anyone working on this? If not, I could take this on.

**Comment by mchandschuh** [comment]
No one is currently working on this, please do!
