### ISSUE TITLE
Library request: memory_profiler

### ISSUE THREAD

**Issue by ArthurAsenheimer** [QuantConnect/Lean#7021]
The python module [memory_profiler](https://github.com/pythonprofilers/memory_profiler) can be used for monitoring memory consumption of a process as well as line-by-line analysis of memory consumption for python programs. 

Bonus: After installing the module, you can use the magic commands `%memit` and `%mprun` to track the memory consumption in Jupyter Notebooks. 

Demo: 
![image](https://user-images.githubusercontent.com/68070194/221942110-5c8a11a5-c309-46c1-b67b-65a9ed773d2e.png)

This can be helpful in QuantConnect's Research environment if we get a memory overflow error. This module can help us to determine the crucial pieces of the code. 

#### System Information

QC Cloud

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Thank you Arthur - I understand the need, but ideally, I'd like to solve this more systematically with a UX element similar to how Google Colab notebooks have the resource bars at the top.
