### ISSUE TITLE
Dominant Cycle Period Indicator

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#7027]
#### Expected Behavior
 - Create Dominant Cycle Period Indicator.  https://www.google.com/search?q=dominant+cycle+period+indicator
 - Generate test data with TA Lib

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by LouisSzeto** [comment]
Refer to "[spy_ht_dcperiod.csv](https://github.com/QuantConnect/Lean/files/10812719/spy_ht_dcperiod.csv)" in https://github.com/QuantConnect/Lean/issues/6986#issuecomment-1441554170

**Comment by Rog2Z** [comment]
Hoping to give this a go as first issue.

**Comment by Rog2Z** [comment]
Is this ticket still relevant? It seems the Hilbert Transform Dominant Cycle Period was completed in this PR? https://github.com/QuantConnect/Lean/pull/7148

**Comment by LouisSzeto** [comment]
@Rog2Z  Hilbert Transform in https://github.com/QuantConnect/Lean/pull/7197
