### ISSUE TITLE
private static IOptionStrategyLegPredicateReferenceValue CreateReferenceValue

### ISSUE THREAD

**Issue by TesoraFinancial** [QuantConnect/Lean#7051]
#### Expected Behavior
No Exception

#### Actual Behavior
throw new NotSupportedException("Expressions containing references to both parameters " +
                        "(legs and positions) on the same side of an equality operator are not supported."
                    );

#### Reproducing the Problem
1. Git Pull
2. UPdate config,.json (set data path)
3. Compile in Visual Studio 2022
4. F5 - run in debug
5. Exception is thrown
6. In OptionStrategyDefintion.cs IOptionStrategyLegPredicateReferenceValue CreateReferenceValue, Line 189

#### System Information
Windows, Visual Studio Enterprise 2022 (64-bit), Version 17.4.4

**Comment by Martin-Molinero** [comment]
Hey @TesoraFinancial!
Please provide and algorithm reproducing the issue so we can fix this asap

**Comment by TesoraFinancial** [comment]
Config.json : 
  "environment": "backtesting", // "live-paper", "backtesting", "live-interactive", "live-interactive-iqfeed"
  "algorithm-type-name": "BasicTemplateFrameworkAlgorithm",
  "algorithm-language": "CSharp",
  "data-folder": "C:\\Repos\\Lean\\Data\\",
  "debugging": true,
  "debugging-method": "VisualStudio",

Stack Trace 
>	QuantConnect.Common.dll!QuantConnect.Securities.Option.StrategyMatcher.OptionStrategyLegPredicate.CreateReferenceValue(System.Linq.Expressions.Expression legsParameter, System.Linq.Expressions.Expression positionParameter, System.Linq.Expressions.Expression expression) Line 189	C#
 	QuantConnect.Common.dll!QuantConnect.Securities.Option.StrategyMatcher.OptionStrategyLegPredicate.Create(System.Linq.Expressions.Expression<System.Func<System.Collections.Generic.IReadOnlyList<QuantConnect.Securities.Option.StrategyMatcher.OptionPosition>, QuantConnect.Securities.Option.StrategyMatcher.OptionPosition, bool>> expression) Line 143	C#
 	[External Code]	
 	QuantConnect.Common.dll!QuantConnect.Securities.Option.StrategyMatcher.OptionStrategyLegDefinition.OptionStrategyLegDefinition(QuantConnect.OptionRight right, int quantity, System.Collections.Generic.IEnumerable<QuantConnect.Securities.Option.StrategyMatcher.OptionStrategyLegPredicate> predicates) Line 53	C#
 	QuantConnect.Common.dll!QuantConnect.Securities.Option.StrategyMatcher.OptionStrategyLegDefinition.Create(QuantConnect.OptionRight right, int quantity, System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression<System.Func<System.Collections.Generic.IReadOnlyList<QuantConnect.Securities.Option.StrategyMatcher.OptionPosition>, QuantConnect.Securities.Option.StrategyMatcher.OptionPosition, bool>>> predicates) Line 176	C#
 	QuantConnect.Common.dll!QuantConnect.Securities.Option.StrategyMatcher.OptionStrategyDefinition.CallLeg(int quantity, System.Linq.Expressions.Expression<System.Func<System.Collections.Generic.IReadOnlyList<QuantConnect.Securities.Option.StrategyMatcher.OptionPosition>, QuantConnect.Securities.Option.StrategyMatcher.OptionPosition, bool>>[] predicates) Line 242	C#
 	QuantConnect.Common.dll!QuantConnect.Securities.Option.StrategyMatcher.OptionStrategyDefinitions.OptionStrategyDefinitions() Line 133	C#
 	[External Code]	
 	QuantConnect.Common.dll!QuantConnect.Securities.Option.StrategyMatcher.OptionStrategyDefinitions.AllDefinitions.get() Line 43	C#
 	QuantConnect.Common.dll!QuantConnect.Securities.Positions.OptionStrategyPositionGroupResolver.OptionStrategyPositionGroupResolver(QuantConnect.Securities.SecurityManager securities) Line 36	C#
 	QuantConnect.Common.dll!QuantConnect.Securities.Positions.PositionManager.PositionManager(QuantConnect.Securities.SecurityManager securities) Line 67	C#
 	QuantConnect.Common.dll!QuantConnect.Securities.SecurityPortfolioManager.SecurityPortfolioManager(QuantConnect.Securities.SecurityManager securityManager, QuantConnect.Securities.SecurityTransactionManager transactions, QuantConnect.Interfaces.IOrderProperties defaultOrderProperties) Line 87	C#
 	QuantConnect.Algorithm.dll!QuantConnect.Algorithm.QCAlgorithm.QCAlgorithm() Line 160	C#
 	QuantConnect.Algorithm.CSharp.dll!QuantConnect.Algorithm.CSharp.BasicTemplateFrameworkAlgorithm.BasicTemplateFrameworkAlgorithm() Line 85	C#
 	[External Code]	
 	QuantConnect.AlgorithmFactory.dll!QuantConnect.AlgorithmFactory.Loader.TryCreateILAlgorithm(string assemblyPath, out QuantConnect.Interfaces.IAlgorithm algorithmInstance, out string errorMessage) Line 274	C#
 	QuantConnect.AlgorithmFactory.dll!QuantConnect.AlgorithmFactory.Loader.TryCreateAlgorithmInstance(string assemblyPath, out QuantConnect.Interfaces.IAlgorithm algorithmInstance, out string errorMessage) Line 139	C#
 	QuantConnect.AlgorithmFactory.dll!QuantConnect.AlgorithmFactory.Loader.TryCreateAlgorithmInstanceWithIsolator.AnonymousMethod__0() Line 370	C#
 	QuantConnect.Common.dll!QuantConnect.Util.WorkerThread..ctor.AnonymousMethod__7_0() Line 62	C#
 	[External Code]

**Comment by TesoraFinancial** [comment]
IOptionStrategyLegPredicateReferenceValue CreateReferenceValue
expression: $p.Strike - (.Call $legs.get_Item(1)).Strike == (.Call $legs.get_Item(1)).Strike - (.Call $legs.get_Item(0)).Strike
Expressions containing references to both parameters (legs and positions) on the same side of an equality operator are not supported.

*This may be the reason:
        public static OptionStrategyDefinition ButterflyCall { get; }
            = OptionStrategyDefinition.Create("Butterfly Call",
                OptionStrategyDefinition.CallLeg(+1),
                OptionStrategyDefinition.CallLeg(-2, (legs, p) => p.Strike >= legs[0].Strike,
                                                     (legs, p) => p.Expiration == legs[0].Expiration),
                OptionStrategyDefinition.CallLeg(+1, (legs, p) => p.Strike >= legs[1].Strike,
                                                     (legs, p) => p.Expiration == legs[0].Expiration,
                                                     (legs, p) => p.Strike - legs[1].Strike == legs[1].Strike - legs[0].Strike)
            );

**Comment by TesoraFinancial** [comment]
Hi Martin,

In the OptionStrategyDefintions.cs file, the ButterflyCall, ShortButteryflyCall, ButterflyPut, ShortButterflyPut methods add into the strategy:

1. Parameters and Legs on the same side of the equation (fails the creation process checks)
2. Defines multiple entries for p.Strike (fails the creation process due to failing “Single”)


Please let me know when I can pull the updated code.  I would supply the fix, but I have just started with the product and don’t have the background to make the change.


Thanks,
Chris

**Comment by Martin-Molinero** [comment]
Hi Chris,
It seems the exception you mention is already handled by the code, does not seem like a bug per se, see https://github.com/QuantConnect/Lean/blob/master/Common/Securities/Option/StrategyMatcher/OptionStrategyLegPredicate.cs#L165. Is it causing issues though? Please provide an algorithm showing the bug so we can solve it asap.

**Comment by Martin-Molinero** [comment]
Hi Chris,
Closing the issue for now based on last comment. Please re open/comment with more details if you think otherwise.
