### ISSUE TITLE
SetWarmup on live instance not processing datapoints

### ISSUE THREAD

**Issue by stefan-j** [QuantConnect/Lean#706]
I'm using SetWarmup to warmup my algorithm.
Recently (today and yesterday), when starting the algorithm as a live instance, I'm receiving:

```
Algorithm Id:(-) completed in 3485.03 seconds at 0k data points per second. Processing total of 4 data points
```

Before that, the message logged (on the 13th) read:

```
Algorithm Id:(-) completed in 33810.98 seconds at 0k data points per second. Processing total of 16,530 data points.
```
(I purposefully removed the algorithm Id)

I'm not really sure if this is significant or not. Coincidentally my algo did no trades yesterday, which lead me to the logs.

The message
`0k data points per second` might also want to be updated to per minute. I'm guessing it works fine for daily data but not for anything below.

Feel free to close this issue if I'm misinterpreting something!

**Comment by stefan-j** [comment]
This is from another algorithm that I tried to run as a live instance:

```
Runtime Error: System.TimeoutException: The history request took too long to process. History requests have a 0 minute timeout. at QuantConnect.Lean.Engine.Engine.Run (QuantConnect.Packets.AlgorithmNodePacket job, System.String assemblyPath) [0x00765] in <6fb4435fe9f940a2bb8fe1c1c546decf>:0 Stack Trace: System.TimeoutException: The history request took too long to process. History requests have a 0 minute timeout. at QuantConnect.Lean.Engine.Engine.Run (QuantConnect.Packets.AlgorithmNodePacket job, System.String assemblyPath) [0x00765] in <6fb4435fe9f940a2bb8fe1c1c546decf>:0
```

All of the instances are for OANDA.

**Comment by jaredbroad** [comment]
Morning @stefan-j! This is a quantconnect.com related ticket and can't be debugged here. Please submit a support ticket using the tab in the IDE.

**Comment by stefan-j** [comment]
Wil do! Thanks
