### ISSUE TITLE
Oanda FxTrade Certificate TrustFailure

### ISSUE THREAD

**Issue by stefan-j** [QuantConnect/Lean#708]
When using the Oanda FxTrade API (api-fxtrade.oanda.com) I get the following error message in `public T MakeRequest<T>` in `OandaBrokerage.Rest.cs`

```
TrustFailure

Error: TrustFailure (The authentication or decryption has failed.)
System.Net.WebException: Error: TrustFailure (The authentication or decryption has failed.) ---> System.IO.IOException: The authentication or decryption has failed. ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: Invalid certificate received from server. Error code: 0xffffffff800b010a
```

With custom debugging on the WebException.

The odd thing is that the practice api (api-fxpractice.oanda.com) seems to be working fine.

I'm currently using custom certificate validation as a workaround to ignore the error. 

EDIT: This occurs on two different linux machines, in different locations. I'm not sure if it is Mono related or if something is wrong with the certificate store.

EDIT2: I'm not really even sure if this is a LEAN issue, maybe someone can verify?

**Comment by jameschch** [comment]
I ran into a bug in mono related to certificate validation a few weeks back. The workaround recommended was to add this in the constructor:

```
System.Net.ServicePointManager.ServerCertificateValidationCallback += (o, certificate, chain, errors) => true;
System.Security.Cryptography.AesCryptoServiceProvider b = new System.Security.Cryptography.AesCryptoServiceProvider();
```

I believe there was a new mono build that might have addressed the issue, so it's worth updating. I have run on windows for the time being but planned to try switching back this weekend. @jaredbroad confirmed at the time this shouldn't affect QC.

**Comment by jameschch** [comment]
Can confirm am able to connect during closed market with above workaround and mono version:

Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)

**Comment by jaredbroad** [comment]
Thanks @jameschch, closing issue.
