### ISSUE TITLE
Crypto Margin Issues When Starting an Algorithm With Coin Holdings

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#7157]
#### Expected Behavior

If we have enough USDT to buy a Crypto pair that has USDT as the quote currency, the order is submitted without error.

#### Actual Behavior

In the following algorithm, we have 5048 USDT and try to spend 4946 USDT to buy 11.49434056 BCH, but we get 
> Order Error: ids: [2], Insufficient buying power to complete orders (Value:[4950.0378]), Reason: Id: 2, Initial Margin: 4962.90546952278992, Free Margin: 4935.098960895920593157.

#### Potential Solution

N/A

#### Reproducing the Problem

```
public class KrakenMarginErrorAlgorithm : QCAlgorithm
{
    private bool _ordered = false;
    public override void Initialize()
    {
        SetStartDate(2022, 1, 1);
        SetEndDate(2022, 1, 10);

        SetTimeZone(TimeZones.Utc);

        SetBrokerageModel(Brokerages.BrokerageName.Kraken, AccountType.Margin);

        SetAccountCurrency("USDT");

        SetCash("USD", 0);
        SetCash("USDT", 0);
        SetCash("BTC", 0.21638839119558914m);
        
        foreach (var ticker in new[] { "BTCUSDT", "BCHUSDT" })
        {
            AddCrypto(ticker, Resolution.Daily);
        }
    }

    public void LogState(int n)
    {
        Debug($"{n}. MarginRemaining: {Portfolio.MarginRemaining}; TotalMarginUsed: {Portfolio.TotalMarginUsed}; BTC: {Portfolio.CashBook["BTC"].Amount}; USDT: {Portfolio.CashBook["USDT"].Amount}; BCH: {Portfolio.CashBook["BCH"].Amount}");
    }

    public override void OnData(Slice slice)
    {
        if (_ordered)
        {
            return;
        }
        _ordered = true;

        LogState(1);
        MarketOrder("BTCUSDT", -0.10927458);
        LogState(2);
        Debug($"{11.49434056} BCHUSDT will cost {11.49434056m * slice["BCHUSDT"].Price} USDT");
        MarketOrder("BCHUSDT", 11.49434056);
        LogState(3);
    }
}
```

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closing issue for now because while using margin account type lean will respect margin used/available above cash book state, which is what's used with cash account types instead.
