### ISSUE TITLE
`qb.AddFutureContract` unable to receive futures contract.

### ISSUE THREAD

**Issue by jeremytanjianle** [QuantConnect/Lean#7195]
#### Expected Behavior
Running the code below for futures research on Quantconnects Research environment.
```
future = qb.AddFuture(
    Futures.Currencies.JPY, 
    Resolution.Daily,
    dataNormalizationMode = DataNormalizationMode.Raw,
    dataMappingMode = DataMappingMode.LastTradingDay,
    contractDepthOffset = 0
)

# subscribe to the contracts
for year in range(2009,2023):
    contract_symbols = qb.FutureChainProvider.GetFutureContractList(future.Symbol, datetime(year, 1, 1))
    for contract_symbol in contract_symbols:
        # print(f"{contract_symbol.Value}: {contract_symbol.ID.Date}")
        qb.AddFutureContract(contract_symbol, fillDataForward = False)
```
This code has worked fine prior on 17th March 2023, and it returns no error.

#### Actual Behavior

However, as of 19th March, it returns the following error. I've double checked that this line is indeed a FuturesContract, which I've always been using.
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[5], line 12
     10 for year in range(2009,2023):
     11     contract_symbols = qb.FutureChainProvider.GetFutureContractList(future.Symbol, datetime(year, 1, 1))
---> 12     for contract_symbol in contract_symbols: qb.AddFutureContract(contract_symbol, fillDataForward = False)

TypeError: No method matches given arguments for AddFutureContract: (<class 'QuantConnect.Symbol'>)
```
#### Potential Solution

Revert to previous LEAN version, but I am unable to do that on the QC research environment. 

#### Reproducing the Problem

Run mentioned code on QC's research environment.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @jeremytanjianle!
The issue you are seeing is because the parameter `fillDataForward` has been renamed to `fillForward` for normalization of the API. For more information see https://www.quantconnect.com/forum/discussion/15074/algorithm-api-normalization-and-parameters-renaming/p1, sorry for the inconvenience caused.
