### ISSUE TITLE
Multi-symbol Tick history request missing data 

### ISSUE THREAD

**Issue by jhonabreul** [QuantConnect/Lean#7198]
#### Expected Behavior

`History<T>` methods that take either no symbol or multiple symbols, when `T=Tick`, return every tick for each symbol.

#### Actual Behavior

`History<T>` methods that take either no symbol or multiple symbols, when `T=Tick`, return only one tick for each symbol.

See https://github.com/QuantConnect/Lean/pull/7191#discussion_r1171550565

#### Potential Solution

Make `GetDataTypedHistory<T>(IEnumerable<HistoryRequest> requests)` handle the Tick special case as `GetDataTypedHistory<T>(IEnumerable<HistoryRequest> requests, Symbol symbol)` does, so it can include every tick for each symbol.

#### Reproducing the Problem

```c#
var symbol = AddEquity("SPY").Symbol;
var start = new DateTime(2013, 10, 07, 15, 30, 0);
var end = start.AddHours(1);

var history1 = History<Tick>(symbol, start, end, Resolution.Tick);
var history2 = History<Tick>(new[] { symbol }, start, end, Resolution.Tick);
```

`hisotry2` will have less ticks than `history1` because it wil only include one tick per fetched slice.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by prasadsom** [comment]
Isn't [this](https://github.com/QuantConnect/Lean/blame/master/Tests/Algorithm/AlgorithmHistoryTests.cs#L138) test cover this, and seems to be working? Or I misunderstood bug ?
