### ISSUE TITLE
Error buying and then selling bull call and bear put spreads

### ISSUE THREAD

**Issue by vguruv** [QuantConnect/Lean#7205]
#### Expected Behavior
Should be able to buy and then sell bull call and bear put spreads

#### Actual Behavior
Get: Backtest Handled Error: Order Error: id: 6, Error executing margin models: Unable to create group for orders: [5,6]

#### Potential Solution
This may be related to issue #6891 or #7054 or #7184 
Source of error may be: https://github.com/QuantConnect/Lean/blob/761ea2571ac9ed5fbb5d22304b81baa36e9f70df/Common/Securities/Positions/OptionStrategyPositionGroupResolver.cs#L60

#### Reproducing the Problem
`

    public class BuyThenSellSpreadsError : QCAlgorithm
    {
        private Symbol symbol;
        private int step;
        private decimal atm_strike;
        OptionStrategy bullCallSpread;
        OptionStrategy bearPutSpread;

        public override void Initialize()
        {
            SetStartDate(2022, 1, 1);
            SetEndDate(2022, 2, 1);
            SetCash(500000);
            var option = AddOption("SPY", Resolution.Minute);
            symbol = option.Symbol;
            option.SetFilter(universe => universe.Strikes(-10, 10).Expiration(0, 1));
            step = 1;
        }

        public override void OnData(Slice data)
        {
            // we will only execute the 2 steps: 
            // 1. buy bear put and bull call spreads
            // 2. sell the spreads bought in step 1
            if (step > 2)
            {
                return;
            }

            var chain = data.OptionChains.get(symbol, null);
            if (chain == null || !chain.Any())
            {
                return;
            }

            if (step == 1)
            {
                atm_strike = chain.OrderBy(x => Math.Abs(x.Strike - chain.Underlying.Price)).ToList()[0].Strike;
            }

            var contracts = (from i in chain where i.Strike == atm_strike select i).ToList();
            if (contracts.Count == 0)
            {
                return;
            }

            // step 1: buy 1 atm bull call and bear put spreads
            if (step == 1)
            {
                // buy spreads
                bullCallSpread = OptionStrategies.BullCallSpread(symbol, atm_strike, atm_strike + 1, Time.Date);
                Buy(bullCallSpread, 1);

                bearPutSpread = OptionStrategies.BearPutSpread(symbol, atm_strike, atm_strike - 1, Time.Date);
                Buy(bearPutSpread, 1);
                step += 1;
            }
            else if (step == 2)
            {
                // step 2: attempt to sell the spreads bought in step1 - error occurs: 
                // Backtest Handled Error: Order Error: id: 6, Error executing margin models: Unable to create group for orders: [5,6]
                Sell(bullCallSpread, 1);
                Sell(bearPutSpread, 1);
                step += 1;
            }
        }

        public override void OnEndOfAlgorithm()
        {
            foreach (var x in Portfolio)
            {
                if (x.Value.Invested)
                {
                    Log("{x.Key} :: {x.Value.Quantity}");
                }
            }
        }

        public override void OnOrderEvent(OrderEvent orderEvent)
        {
            var order = Transactions.GetOrderById(orderEvent.OrderId);
            if (orderEvent.Status == OrderStatus.Filled)
            {
                Debug("{self.Time}: {order.Type}: {orderEvent}");
            }
        }
    }
`

#### Checklist

- [X ] I have completely filled out this template
- [ X] I have confirmed that this issue exists on the current `master` branch
- [ X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X ] I have provided detailed steps to reproduce the issue

**Comment by Idogon** [comment]
@jhonabreul I still experience the exact same issue in the cloud environment when using Python, while using LEAN engine tagged master-v15546 which the solution seems to be merged into. 
Any ideas on why this still happens?

**Comment by jhonabreul** [comment]
Hi @Idogon, I haven't been able to reproduce the issue neither locally nor in the cloude. Can you please share an algorithm so I can look into it?

I'm leaving an algorithm here for reference: https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_623479a438ef55149cae7fcd67363e30.html

**Comment by Idogon** [comment]
Hi @jhonabreul 
Thank you for the detailed reproduced example. 
I have updated your example to use basic margin, alongside bullPutSpread, and it indeed fails again. 
I'm copy-pasting the reproducing code here as I did not find how to share it the same way you did.
As you can see below, the entire exposure is minimal of $40K for the entire bull put spread position, so even the minor usage of margin would cause such an error.

Thank you for your help!

from AlgorithmImports import *
import QuantConnect

class LiquidatingMultipleOptionStrategiesRegressionAlgorithm(QCAlgorithm):
    def Initialize(self):
        self.SetStartDate(2015, 12, 23)
        self.SetEndDate(2015, 12, 25)
        self.SetCash(1000000)

        equity = self.AddEquity("GOOG")
        option = self.AddOption("GOOG")
        option.SetFilter(lambda universe: universe.Strikes(-3, 3).Expiration(0, 180))

        self.SetBrokerageModel(BrokerageName.InteractiveBrokersBrokerage, AccountType.Margin)

        self._symbol = option.Symbol
        self._done = False

    def OnData(self, slice):
        if self._done:
            return

        chain = slice.OptionChains.get(self._symbol)
        if chain is None:
            return

        calls = [x for x in chain if x.Right == OptionRight.Call]
        calls = [x for x in calls if x.Expiry == calls[0].Expiry]
        calls = sorted(calls, key = lambda x: x.Strike)

        puts = [x for x in chain if x.Right == OptionRight.Put]
        puts = [x for x in puts if x.Expiry == puts[0].Expiry]
        puts = sorted(puts, key = lambda x: x.Strike, reverse = True)

        if len(calls) < 2 or len(puts) < 2:
            return

        if not self.Portfolio.Invested:
            # self._bullCallSpread = OptionStrategies.BullCallSpread(self._symbol, calls[0].Strike, calls[1].Strike, calls[0].Expiry)
            # self.Buy(self._bullCallSpread, 3)

            self._BullPutSpread = OptionStrategies.BullPutSpread(self._symbol, puts[0].Strike, puts[-1].Strike, puts[0].Expiry)
            self.Buy(self._BullPutSpread, 100)
            self.SetHoldings("GOOG", 1)
        else:
            #self.Sell(self._bullCallSpread, 3)
            self.Sell(self._BullPutSpread, 100)
            self._done = True

    def OnEndOfAlgorithm(self):
        if not self._done:
            raise Exception("Expected the algorithm to have bought and sold a Bull Call Spread and a Bear Put Spread.")

        if self.Portfolio.Invested:
            raise Exception("The spreads should have been liquidated by the end of the algorithm")

**Comment by jhonabreul** [comment]
Hi @Idogon 
I am sharing a backtest using a copy-paste of your algorithm: https://www.quantconnect.com/reports/1065a8065b0db3771048fa24ab5073b2
The only thing I did was commenting the last check in `OnEndOfAlgorithm` since at the end the algorithm still has the equity bought using `self.SetHoldings("GOOG", 1)`. But other than that, the algorithm is running, you can see the 5 orders, all of them filled: 2 for the pull put spread purchase, 1 for the equity purchase and 2 for the spread liquidation.

Please let me know if you are having a different issue when running your algorithm.

**Comment by jhonabreul** [comment]
Sorry, wrong URL. Here it is: https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_1065a8065b0db3771048fa24ab5073b2.html

Glad it is resolved!
