### ISSUE TITLE
How to run demo algorithm again and again

### ISSUE THREAD

**Issue by MadhavanVenkatesh** [QuantConnect/Lean#7288]
#### Expected Behavior

I want run the algorithm I have written again and again without calling the engine everytime.

#### Actual Behavior

I have to run engine again and again to call the algorithm

#### Reproducing the Problem

I have put engine.Run() in for loop and disposed the worker thread after the loop is completed but getting the error in order.Type as seen below in attachment
![share app issue](https://github.com/QuantConnect/Lean/assets/91518043/596a7d84-f5e4-495f-86bc-24162c08b76a)

#### Checklist

- [ ] I have completely filled out this template
- [ ] I have confirmed that this issue exists on the current `master` branch
- [ ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @MadhavanVenkatesh!
Lean isn't currently built to run multiple times in a loop in the same instance, many things can go wrong. 

> I want run the algorithm I have written again and again without calling the engine everytime.

Suggest running the algorithm as an optimization instead, that would do the trick 👍
