### ISSUE TITLE
local backtest failed-data-request.txt file with wrong entries

### ISSUE THREAD

**Issue by cjbd** [QuantConnect/Lean#7303]
#### Expected Behavior

failed-data-request.txt should list all missing files
#### Actual Behavior

failed-data-request.txt has wrong list of files, e.g.

```
/equity/usa/daily/erus.zip
/equity/usa/daily/efnl.zip
/equity/usa/daily/aaxj.zip
/equity/usa/daily/gaf.zip
/equity/usa/daily/aud.zip
/equity/usa/daily/bund.zip
/equity/usa/daily/ewq.zip
/equity/usa/daily/enzl.zip
/equity/usa/daily/ivv.zip
/equity/usa/daily/icol.zip
/equity/usa/daily/eidoewi.zip
/equity/usa/daily/ewj.zip
/equity/usa/daily/eww.zip
/equity/usa/daily/epi.zip
/equity/usa/daily/ewh.zip
/equity/usa/daily/ezu.zip
/equity/usa/daily/and.zip
/equity/usa/daily/ech.zip
/equity/usa/daily/ewz.zip
/equity/usa/daily/chib.zip
/equity/usa/daily/ewp.zip
/equity/usa/daily/ewc.zip
/equity/usa/daily/aia.zip
/equity/usa/daily/ewl.zip
/equity/usa/daily/argt.zip
/equity/usa/daily/gxc.zip
/equity/usa/daily/norwewy.zip
/equity/usa/daily/ewk.zip
/equity/usa/daily/egpt.zip
/equity/usa/daily/ewd.zip
/equity/usa/daily/ewo.zip
/equity/usa/daily/braq.zip
/equity/usa/daily/adru.zip
```

`/equity/usa/daily/eidoewi.zip` and `/equity/usa/daily/norwewy.zip` are obviously wrong, it should be:

```
/equity/usa/daily/eido.zip
/equity/usa/daily/ewi.zip
/equity/usa/daily/norw.zip
/equity/usa/daily/ewy.zip
```
#### Reproducing the Problem

in local environment with not enough data, backtest strategy from library: [BETA FACTOR IN COUNTRY EQUITY INDEXES](https://www.quantconnect.com/learning/articles/investment-strategy-library/beta-factor-in-country-equity-indexes), then check failed-data-request.txt file from backtest result

#### System Information

host: ubuntu linux 20, docker: pulled from official repo, LEAN Engine v2.5.0.0
#### Checklist

- [ * ] I have completely filled out this template
- [ * ] I have confirmed that this issue exists on the current `master` branch
- [ * ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ *  ] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @cjbd!
Thanks for the report, the algorithm has a typo it's missing 2 `,`, we will fix it ASAP

![image](https://github.com/QuantConnect/Lean/assets/18473240/0fab6d68-2129-4cef-b066-48eab87de695)

**Comment by cjbd** [comment]
@Martin-Molinero , thanks for the update
