### ISSUE TITLE
Continuous Contract Data Isn't Working

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#7323]
#### Expected Behavior

- The `Mapped` property of a Future object is not None
- We get `SymbolChangedEvents` in OnData

#### Actual Behavior

- The `Mapped` property is None
- We don't get `SymbolChangedEvents` in OnData

#### Potential Solution

N/A

#### Reproducing the Problem

https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_3fe00e4632180fc139f203d3700875fe.html

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Thanks for the report @DerekMelchin! Issue was a bad node missing map files
