### ISSUE TITLE
Expand IB to Support CFD Products

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#7347]
#### Expected Behavior
LEAN supports a CFD brokerage.

#### Actual Behavior
With OANDA moving European clients to OANDA TWS; and that entity not supporting API's, they can no longer use LEAN.

#### Potential Solution
Add another broker or expand IB support to handle CFDs. 

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Related https://github.com/QuantConnect/Lean.Brokerages.InteractiveBrokers/issues/10

**Comment by marcokrueger** [comment]
Would love to see this! Europeans can't trade US ETFs because of tax reasons. So no SPY, QQQ, etc. IB offers them and other ETFs/stocks as CFD which is the only way to trade them.

**Comment by j-mcgregor** [comment]
bump

**Comment by DaveMitten** [comment]
double bump

**Comment by mopechowski** [comment]
triple bump ;-)

**Comment by jaredbroad** [comment]
https://github.com/QuantConnect/Lean.Brokerages.InteractiveBrokers/issues/10

Scheduling this for W1-W2 of March 2024
