### ISSUE TITLE
Customization of Reports / Display Parameters Used in Backtest Statistics

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#7350]
Backtests know about their parameters but don't record them in the backtest result. Ideally store the KVP in the result, include it in the backtest overall statistics, and the report generated.

**Comment by Martin-Molinero** [comment]
- Backtest: Lean is storing the parameters in the result object ref https://github.com/QuantConnect/Lean/pull/6878. 
TODO: pending to be displayed. CC: @gaviles
<img width="440" alt="image" src="https://github.com/QuantConnect/Lean/assets/18473240/f8790877-5e07-4a98-a01a-e214de8a5b2d">
