### ISSUE TITLE
Weekly consolidation doesn't occur until Tuesday at midnight

### ISSUE THREAD

**Issue by mmlin** [QuantConnect/Lean#7356]
#### Expected Behavior

I'd like to make trading decisions on the weekend based on the weekly bar that just closed. I tried using the TradeBarConsolidator with the Calendar.Weekly specifier, expecting that the consolidator would run as soon as it's updated with the final bar of the week which is typically Saturdays at midnight.

#### Actual Behavior

The consolidation doesn't occur until the following Tuesday at midnight (i.e. while receiving Monday's trade bar)

#### Potential Solution

Would be nice if there were a consolidator that could consolidate at the close of the final bar instead of after receiving data for the next consolidated bar. Another potential solution would be to give a way to forcibly consolidate any pending bars which could be scheduled over the weekend.

#### Reproducing the Problem

Here's an example to demonstrate the issue in the research environment. Notice the sequence of events.

```
class Data:
    def __init__(self):
        self.consolidator = TradeBarConsolidator(Calendar.Weekly)
        self.consolidator.DataConsolidated += self.consolidate
    
    def consolidate(self, sender: object, consolidated_bar: TradeBar) -> None:
        print(consolidated_bar.EndTime, consolidated_bar.EndTime.weekday(),
              consolidated_bar.Close, '<- consolidated bar')

qb.AddEquity('TSLA')
history = qb.History[TradeBar]('TSLA', 50, Resolution.Daily)
data = Data()

for bar in history:
    print(bar.EndTime, bar.EndTime.weekday(), bar.Close)
    data.consolidator.Update(bar)
```

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @mmlin!
Thanks for the report, there's already an associated issue for this behavior https://github.com/QuantConnect/Lean/issues/5457, we will try to solve it asap.
As a work around, you could rely on scheduled events for now, calling `consolidator.Scan(time)` will cause it to flush any working bars when the time is right.
Will close this issue since it's a duplicate

**Comment by mmlin** [comment]
Thanks for the workaround, and for upgrading the priority of that original
issue.

-Mike
