### ISSUE TITLE
Upgrade Microsoft.ML Libraries

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#7378]
#### Expected Behavior
Support Microsoft.ML 2.

#### Actual Behavior
We have the following libraries.
```
Microsoft.ML                         1.7.1
Microsoft.ML.CpuMath                 1.7.1
Microsoft.ML.DataView                1.7.1
Microsoft.ML.Ensemble                0.19.1
Microsoft.ML.FastTree                1.7.1
Microsoft.ML.LightGbm                1.7.1
Microsoft.ML.Mkl.Components          1.7.1
Microsoft.ML.OnnxRuntime             1.12.1
Microsoft.ML.TensorFlow              1.7.1
Microsoft.ML.TimeSeries              1.7.1
```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Available in the QC cloud starting from lean version `15769`
