### ISSUE TITLE
Support C# plotting libraries + Update Plot.NET from 3.0.1 to latest. 

### ISSUE THREAD

**Issue by gmwhipple** [QuantConnect/Lean#7389]
#### Expected Behavior
support Xplot and Oxyplot C# libraries in the research environment (jupyter notebooks)
Update Plotly.NET.

#### Actual Behavior

using XPlot.Plotly;
using OxyPlot;
using OxyPlot.Series;

(17,7): error CS0246: The type or namespace name 'XPlot' could not be found (are you missing a using directive or an assembly reference?)

(18,7): error CS0246: The type or namespace name 'OxyPlot' could not be found (are you missing a using directive or an assembly reference?)

#### System Information
cloud environment, using futures so has to be in the cloud.

#### Checklist

- [x ] I have completely filled out this template
- [x ] I have confirmed that this issue exists on the current `master` branch
- [x ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Note will skip the following:
- `Xplot` is no longer maintained and suggests using `Plotly`. 
- Do not think `Oxyplot` would be compatible with Lean research: supports `WPF, Windows 8, Windows Phone, Windows Phone Silverlight, Windows Forms, Silverlight, GTK#, Xwt, Xamarin.iOS, Xamarin.Android, Xamarin.Forms and Xamarin.Mac.` please correct me if I'm wrong

**Comment by Martin-Molinero** [comment]
Reopening so we can revisit adding newer version of plotly see https://github.com/plotly/Plotly.NET/issues/409
