### ISSUE TITLE
Models Set For Option and Future Chain Are Applied to Contracts

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#7397]
#### Expected Behavior
If I set a model to the chain object, contracts also have this model:

```python
# Initialize
self.future = self.AddFuture("ES")
self.future.SetFillModel(CustomFillModel())

# OnData
fill_model = self.Securities[self.future.Mapped].FillModel   # fill_model is a CustomFillModel obj
```

#### Actual Behavior
We need to use a security initializer to achieve the desired behavior or `fill_model` is not a `CustomFillModel` object.

#### Potential Solution
N/A

#### Reproducing the Problem
```python
# region imports
from AlgorithmImports import *
# endregion

class CalculatingBrownKangaroo(QCAlgorithm):

    def Initialize(self):
        self.SetStartDate(2022, 1, 20)
        self.future = self.AddFuture("ES")
        self.future.SetFillModel(CustomFillModel())

    def OnData(self, data: Slice):
        fill_model = self.Securities[self.future.Mapped].FillModel
        self.Quit(str(type(fill_model)))

class CustomFillModel(FillModel):
    pass
```

`Quit` prints: _Quit(): <class 'QuantConnect.Orders.Fills.FutureFillModel'>_

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Easy to overlook especially for futures.
