### ISSUE TITLE
Add a LinearWeightedMovingAverage Indicator

### ISSUE THREAD

**Issue by bizcad** [QuantConnect/Lean#74]
I need a WMA for a Algo I am writing, so I have written a WMA.  This issue is so that I can make a branch and pull request to add the WMA to the project while tesing the contributor workflow.  

When the WMA indicator is created, the user provides a period (an int) and optionally a name (a string).  The WeightedMovingAverage is derived from WindowIndicator<IndicatorDataPoint> as are most of the indicators. The constructor calls the base class constructor which creates the RollingWindow of period length.  

This version of the WMA computes the average as a [linear weighted moving average] (http://en.wikipedia.org/wiki/Moving_average).

**Comment by mchandschuh** [comment]
Awesome idea Nick! If I could make a suggestion, I think we could define something a little more general. I'm envisioning a generic `WeightedAverageIndicator` which could be made up of two indicators, a `weight` and an `indicator`.  In this way we could define a volume weighted average price easily by using the volume as the weight and the price as the indicator to be weighted.  I'm thinking of syntax like the following:

```C#
Identity close = Identity("SPY", ((TradeBar)x).Close);
Identity volume = Identity("SPY", ((TradeBar)x).Volume);
int period = 14;
MovingAverageType type = MovingAverageType.Simple;
var vawp = new WeightedAverageIndicator(close, volume, period, type);
```

So the `WeightedAverageIndicator` could expose two indicator properties, the raw indicator and the weight indicator:

```C#
private readonly IndicatorBase<IndicatorDataPoint> _smoother;

public IndicatorBase<IndicatorDataPoint> Indicator { get; private set; }
public IndicatorBase<IndicatorDataPoint> Weight { get; private set; }

public WeightedAverageIndicator(
    IndicatorBase<IndicatorDataPoint> indicator, 
    IndicatorBase<IndicatorDataPoint> weight, 
    int period, 
    MovingAverageType type = MovingAverageType.Simple
    )
{
    Indicator = indicator;
    Weight = weight;
    _smoother = type.AsIndicator(period);
}
```

And then in the Update method, multiple `Indicator` and `Weight` together and put the result into `_smoother`. The output would be the value of the `WeightedAverageIndicator`.

Thoughts?

**Comment by mchandschuh** [comment]
Also, we have a type called a `CompositeIndicator<T>` which combines two indicators to make a new one. If possible, we could derive from this type and get access to his goodies. He handles push updates, so in this way, if the `weight` changes or if the `indicator` changes, our new `WeightedAverage` will automatically compute his next value.

**Comment by bizcad** [comment]
I also had thought of varying the weighting for other types of  weightings.  I had not thought of WVAP, and I like it.  I had considered a formula that would use weights other than linear, so the user could specify the weighting for each of the periods.  I will experiment with the composite tomorrow.  

It might be better to not do too much in one indicator, but have a separate indicators that each just does one thing because of separation of concerns.  Maybe the name of this indicator should be LinearWeightedMovingAverage?  Here is my implementation of the ComputeNextValue so far:
<pre>
        /// <summary>
        /// Computes the next value for this indicator from the given state.
        /// </summary>
        /// <param name="window">The window of data held in this indicator</param>
        /// <param name="input">The input value to this indicator on this time step</param>
        /// <returns>A new value for this indicator</returns>
        protected override decimal ComputeNextValue(IReadOnlyWindow<IndicatorDataPoint> window, IndicatorDataPoint input)
        {
            decimal numerator = 0m;
            long denominator = 0;

            // Compute the denominator as factorial.  
            // This computation has to be done each time in case 
            //    we have not reached the IsReady state.
            for (int i = 0; i <= window.Size; i++)
            {
                denominator += i;
            }

            // our first data point just return identity
            if (window.Size == 1)
            {
                return input.Value;
            }
            long index = window.Size;
			
			// If the indicator is not ready, the WMA will still be correct
			//  because the numerator has the minimum of the Size (number of
			//  entries or the Samples (the allocated space)
            long minSizeSamples = (long)Math.Min(window.Size, window.Samples);
            for (long i = 0; i < minSizeSamples; i++)
            {
                decimal x = (index--*window[(int) i]);
                numerator += x;
            }
            //System.Diagnostics.Debug.WriteLine(string.Format("WMA = {0}", (smooth/denominator)));
            return numerator / denominator; 
        }
</pre>

**Comment by mchandschuh** [comment]
Nick, I now understand exactly what you're going for. I'll open up another issue for the generic `WeightedAverage` which is a different concept.  This is a great addition. I like the name [Linear Weighted Moving Average](http://www.marketoracle.co.uk/Article38383.html). Please also add an entry to the `MovingAverageType

**Comment by bizcad** [comment]
I have 
1.  changed the name to LinearWeightedMovingAverage, 
2.  added the type, 
3.  commited my branch and pushed to my origin
4.  fetched the upstream
I think I am ready to do the pull request.  I hope I did not mess anything up.

**Comment by bizcad** [comment]
Oh shucks!  I just realized that I changed the Engine\config.json from BasicTemplateAlgorithm to IndicatorSuiteAlgorithm and I do not know what to do now.

**Comment by mchandschuh** [comment]
You should be able to make a change and push it back the same way you did
before and the pull request *should* automatically update.  If it doesn't
auto-update don't worry about it, I can pull it down before I merge and
revert the change.

**Comment by bizcad** [comment]
I cannot seem to push to the origin.  I get the following message:
<code>
C:\Users\Nick\Documents\Visual Studio 2013\Projects\Lean>git push origin iss
4/Add-a-WMA-Indicator
Username for 'https://github.com': bizcad
Password for 'https://bizcad@github.com':
To https://github.com/bizcad/Lean.git
 ! [rejected]        issue-74/Add-a-WMA-Indicator -> issue-74/Add-a-WMA-Indi
r (non-fast-forward)
error: failed to push some refs to 'https://github.com/bizcad/Lean.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.</code>

When I look at my origin on github, it says I am 23 updates behind the upstream (you).  I cannot figure out how to get those changes into my github account so I can push from my local repo.  The local repo seems to be up do date with the upstream.

**Comment by mchandschuh** [comment]
Nick,

You'll need to use the following:

git fetch
git merge origin/master

If there are merge conflicts you'll need to resolve them. Here's some
related documentation:

http://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

Also, I would recommend a mergetool. There's a free one called Meld.

http://meldmerge.org/

Configuring Meld with your local git:

http://stackoverflow.com/questions/12956509/how-to-set-meld-as-git-mergetool

Let me know if you need any more help!

-Michael
