### ISSUE TITLE
Can't get Lean to build

### ISSUE THREAD

**Issue by ShayanJa** [QuantConnect/Lean#740]
I'm running on OSX  and i keep getting the error that, 'jwtoken' could not be found. How do others get around this?

**Comment by jaredbroad** [comment]
Welcome @ShayanJa; can you please post more information so people can help you debug.

What IDE / C# engine are you using? Can you post the full build logs? Did you follow the readme guide for setup on iOS? 

Closing this for now but post back with updates and we can reopen
