### ISSUE TITLE
Alternative options data providers

### ISSUE THREAD

**Issue by bobobo1618** [QuantConnect/Lean#742]
So AlgoSeek's pricing, at a minimum $1k purchase or $600 for 6 months, is probably out of reach (or painful) for many of us.

Going by OPRA's vendor list, the only affordable option I came up with was [ActiveTick](http://www.activetick.com/ActiveTick/Contents/Default.aspx), which is $58.20 monthly for API access needed to extract data. API should make live data doable but needs work on their end for historical (they let you grab tick data for a particular option but you need to know the strike and expiry in advance, they don't let you list them). Lacks Open Interest.

I tried to check IQFeed but there were 502 and 500 responses during signup and I couldn't find anything conclusive on their end.

The reasons I'm bringing this up as an issue instead of just sending a PR myself are:
- I'm not sure if I'm missing other providers.
- I think it'd be a good idea to get in touch with ActiveTick to see if they could fix up the API on their end and I'm not sure if someone more "official" should do it rather than a random user (if it came from someone "official" maybe they'd do the work and give you an affiliate program or something).

**Comment by jaredbroad** [comment]
ActiveTick are notorious for not replying. I'm not even sure they are in business anymore. We did reach out a while back to make an open source connector to them but they never replied.

Unfortunately options data is just expensive and there is no hack around that. Even QuantConnect doesn't provide live streaming data - we rely on the option trader having an interactive brokers connection and data subscription.

We are investigating providing the data QC uses for backtesting available for download on a per-day basis. Perhaps that would be interesting for you?

**Comment by bobobo1618** [comment]
> ActiveTick are notorious for not replying. I'm not even sure they are in business anymore.

Ah, fair enough, I wasn't aware of that.

> We are investigating providing the data QC uses for backtesting available for download on a per-day basis. Perhaps that would be interesting for you?

That sounds good but I'd really want to download multiple days. I'm not looking for a way to bootstrap a live algorithm, I'm looking for a way to backtest while offline or if something happens to QuantConnect's online services (without paying $XXXX for data).

**Comment by jaredbroad** [comment]
LEAN breaks files down into days; we provide fx and cfd data free through quantconnect.com/data that you can use for backtesting. If there's demand we can serve options and futures data the same way to provide easy backtesting locally on a per symbol-day basis. Closing this for now as not relevant to LEAN code base but will circle back soon.
