### ISSUE TITLE
[Python environment]

### ISSUE THREAD

**Issue by countif** [QuantConnect/Lean#7429]
#### Expected Behavior

It supposed to run successfully after I changed some variables of config.json to 
  "environment": "backtesting", // "live-paper", "backtesting", "live-interactive", "live-interactive-iqfeed"

  // algorithm class selector
  "algorithm-type-name": "BasicTemplateFrameworkAlgorithm",

  // Algorithm language selector - options CSharp, Python
  "algorithm-language": "Python",

  //Physical DLL location
  "algorithm-location": "../../../Algorithm.Python/BasicTemplateFrameworkAlgorithm.py",

  //"algorithm-location": "QuantConnect.Algorithm.CSharp.dll",
  //"algorithm-location": "../../../Algorithm.Python/BasicTemplateFrameworkAlgorithm.py",

#### Actual Behavior

It reported some bugs .
20230809 23:36:51.038 ERROR:: Loader.TryCreatePythonAlgorithm():  Python.Runtime.BadPythonDllException: Runtime.PythonDLL was not set or does not point to a supported Python runtime DLL. See https://github.com/pythonnet/pythonnet#embedding-python-in-net
 ---> System.MissingMethodException: Failed to load symbol Py_IncRef: dlsym(RTLD_DEFAULT, Py_IncRef): symbol not found
   at Python.Runtime.Platform.PosixLoader.GetFunction(IntPtr dllHandle, String name)
   at Python.Runtime.Runtime.Delegates.GetFunctionByName(String functionName, IntPtr libraryHandle

#### Reproducing the Problem

download the project and change the config.json.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by countif** [comment]
I have installed the conda and modified PYTHONNET_PYDLL . It seems the path is empty when it tried to load Python DLL

**Comment by Martin-Molinero** [comment]
Hey @countif!
Sorry we can't give support for direct local installations of Lean project (too many variables, making it very complex). Suggest instead using our lean cli tool which makes it much easier, please take a look at our [documentation](https://www.quantconnect.com/docs/v2/) for detailed information.
