### ISSUE TITLE
VS Code Doesn't Recognize CandlestickSeries Method in AlgorithmImports Package

### ISSUE THREAD

**Issue by creatidy** [QuantConnect/Lean#7433]
I encountered a minor issue while working in VS Code. Everything seems to be working as expected, but there's an anomaly with IntelliSense/auto-complete related to the CandlestickSeries method. It appears that VS Code doesn't recognize the method, which might be due to its absence from the AlgorithmImports package.

#### Expected Behavior
VS Code should recognize the CandlestickSeries method when the appropriate QuantConnect packages are imported, providing auto-complete or IntelliSense information for it.

#### Actual Behavior
VS Code does not recognize the CandlestickSeries method, making it necessary to add # type: ignore comments to suppress type warnings from the linter.

#### Potential Solution
Ensure that the CandlestickSeries method is included in the AlgorithmImports package and that there are no discrepancies that might prevent IntelliSense from recognizing it.

#### Reproducing the Problem
Open a new QC algorithm project in VS Code.
Implement the following code snippet in the Initialize method:
```
# Indicators charts
self.indicators_chart = Chart("Indicators", ChartType.Stacked)
self.AddChart(self.indicators_chart)

# Indicators series
self.asset_series = CandlestickSeries(self.benchmark_symbol)  # type: ignore
self.indicators_chart.AddSeries(self.asset_series)  # type: ignore
```
Notice that VS Code does not recognize CandlestickSeries.

#### System Information
lean 1.0155
QuantConnect extension to VS Code: v0.1.776

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @creatidy!
This is probably due to the stubs getting outdated, please run `pip install --upgrade quantconnect-stubs` to get the latest stubs

**Comment by Martin-Molinero** [comment]
Thanks for the report @creatidy. The stubs generation is failing, so they are outdated, we will fix it asap 👍
