### ISSUE TITLE
Library Request: functime.ai

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#7437]
#### Expected Behavior
Support functime in the QC cloud https://github.com/descendant-ai/functime

#### Actual Behavior
Not supported

#### Potential Solution
When functime changes license; onboard to QC LEAN foundation
 
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by topher-lo** [comment]
@jaredbroad https://github.com/descendant-ai/functime/blob/main/LICENSE Apache 2.0 💯

**Comment by jaredbroad** [comment]
Thanks @topher-lo! We'll include in the next foundation update

**Comment by Martin-Molinero** [comment]
Hey @topher-lo! We are currently looking into adding `functime` to the lean foundation 🙌
It's being a bit tricky due to the hard requirements causing it to be incompatible with other libraries in the same environment. We were wondering if the current version requirements could be relax? Thank you
```
    "flaml==2.0.2",
    "polars==0.19.8",
    "scikit-learn==1.2.2",
```

**Comment by topher-lo** [comment]
Thanks for bringing this up! We have to pin polars unfortunately (the previous versions are less stable). But sklearn and flaml can be loosened.

Is there more information I can use to debug this issue?

**Comment by Martin-Molinero** [comment]
Hey @topher-lo!
> We have to pin polars unfortunately (the previous versions are less stable). But sklearn and flaml can be loosened.

Thank you, specially minor releases. polars already has a 0.19.9 release for example. Maybe something like the following?
```
    "flaml >=2.0.2, <3",
    "polars>=0.19.8, < 1",
    "scikit-learn>=1.2.2, < 2",
```

> Is there more information I can use to debug this issue?

Please take a look at the referenced PR https://github.com/QuantConnect/Lean/pull/7522 . I was able to add functime.ai but it's the only library limiting the `scikit-learn` version bump, which is **widely** used

**Comment by topher-lo** [comment]
This should work. We will get change out before the weekend! :D excited to be part of the foundation

**Comment by topher-lo** [comment]
Done https://github.com/neocortexdb/functime/blob/main/pyproject.toml#L35

**Comment by Martin-Molinero** [comment]
Hey @topher-lo! Could you please release the new package to pypi so we can consume it?

**Comment by topher-lo** [comment]
[v0.8.4](https://github.com/neocortexdb/functime/actions/runs/6615022210) will be uploaded in 15-20 minutes.
