### ISSUE TITLE
Library Request: auto-sklearn

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#7470]
#### Expected Behavior
[auto-sklearn](https://automl.github.io/auto-sklearn/master/index.html) is an automated machine learning toolkit and a drop-in replacement for a scikit-learn estimator.

#### Actual Behavior
Not supported

#### Potential Solution
Onboard to QC LEAN foundation
 
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
`auto-sklearn` requires `scikit-learn<0.25.0 and >=0.24.0`, from 2021, causing compatibility issues with other libraries. The library itself hasn't been updated since over 1 year

**Comment by Martin-Molinero** [comment]
Closing for now, until `auto-sklearn` dependencies are soften for `scikit-learn`, see https://github.com/automl/auto-sklearn/issues/1597
