### ISSUE TITLE
Custom data subscription not working with the same symbol from multiple exchanges

### ISSUE THREAD

**Issue by arodus** [QuantConnect/Lean#7495]
#### Expected Behavior

All the custom data subscriptions are properly working and 4 data entries are available in each slice (see repro example)

#### Actual Behavior

Custom data subscriptions for the same symbol from multiple exchanges are not working as expected. The custom data subscription is not created for every symbol but only the first one and is being reused by the others. 

#### Potential Solution

I don't have enough information on backward compatibility and the initial design reasons to make a proper suggestion to fix it. 
Not using the US market but the same market as in the source symbol seems to work, but this might have further implications I'm not aware of. Especially after reading https://github.com/QuantConnect/Lean/pull/3484

#### Reproducing the Problem

```csharp
public class Test : QCAlgorithm
{
    public override void Initialize()
    {
        SetStartDate(2023, 01, 1); // Set Start Date
        SetEndDate(new DateTime(2023, 01, 01).AddMinutes(2)); // Set Start Date
        SetAccountCurrency("USDT", 10000);

        var market1 = AddCryptoFuture("BTCUSDT", Resolution.Minute, Market.Bybit, false);
        var data1 = AddData<MyCustomData>(market1.Symbol, Resolution.Minute, DateTimeZone.Utc, false);

        var market2 = AddCryptoFuture("BTCUSDT", Resolution.Minute, Market.Binance, fillForward: false);
        var data2 = AddData<MyCustomData>(market2.Symbol, Resolution.Minute, DateTimeZone.Utc, false);
    }


    public override void OnData(Slice slice)
    {
        // I'm expecting 4 data entries here but it's always only 3
        // It seems like the symbol being created is the same for both custom data subscriptions as it's created for the US market
        // Registering the data source using the ticker instead of the underlying symbol works but that way we're loosing the market information 
        // in the BaseData making reading the data more complicated. 
        // Another solution would be to use a different data type per symbol as the data type because the final symbol consists of {underlying_ticker}.{data_type_name}

        Log($"Data: {slice.Count} Expected: 4");
    }
}
```
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by arodus** [comment]
@Marinovsky @Martin-Molinero
It seems this bug is only partially fixed and/or there seems to be an additional issue:

1. The data timezone of the custom data seems to be always `America/New_York` this might be related to still using the USA market here: https://github.com/QuantConnect/Lean/blob/844602c04a6cf2fb9a77f6401705950a770180f5/Algorithm/QCAlgorithm.Python.cs#L266

2.
This example will still not work, in this case it's the same exchange but a different security type. 
```csharp
var market1 = AddCryptoFuture("BTCUSDT", Resolution.Minute, Market.Bybit, false);
var data1 = AddData<MyCustomData>(market1.Symbol, Resolution.Minute, DateTimeZone.Utc, false);

var market2 = AddCrypto("BTCUSDT", Resolution.Minute, Market.Bybit, fillForward: false);
var data2 = AddData<MyCustomData>(market2.Symbol, Resolution.Minute, DateTimeZone.Utc, false);
```

**Comment by Martin-Molinero** [comment]
Hey @arodus!
Whops yes nice catch about 1, reopening so we address it 👍. Regarding 2, I don't think that use case is currently supported, suggest maybe using inheritance to add `CryptoCustomData : MyCustomData` & `CryptoFutureCustomData : MyCustomData` believe that would do the trick

**Comment by arodus** [comment]
Amazing thank you. The workaround works for me :)
