### ISSUE TITLE
Add a WeightedAverage Indicator

### ISSUE THREAD

**Issue by mchandschuh** [QuantConnect/Lean#75]
Check out the discussion on the [LWMA issue](https://github.com/QuantConnect/Lean/issues/74) about weighted indicators and how it could be composed. This would allow things like VWAP to be easily defined.

**Comment by jaredbroad** [comment]
To clarify: this means an indicator building block which takes multiple components and finds the weighted average of them using supplied weights.

```C#
var closeSPY = Identity("SPY", Field.Close);
var volumeSPY = Identity("SPY", Field.Volume);
// e.g. 14 Period VWAP
var vwap = closeSPY.WeightedBy(volumeSPY, 14); 
```

This should be an extension method which returns another indicator.

**Comment by jaredbroad** [comment]
Completed by commit 32770af
