### ISSUE TITLE
Futures Early Close Removing The Entire Day

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#7501]
#### Expected Behavior
The algorithm receives data until the early close and then resumes when the market opens.

#### Actual Behavior
The algorithm with ES is skipping the entire day. E.g Jan 16th 2012
Accoring to the MHDB [market-hours-database.json#L20590](https://github.com/QuantConnect/Lean/blob/master/Data/market-hours/market-hours-database.json#L20590), it should trade until 12 PM.

#### Reproducing the Problem
```python
# region imports
from AlgorithmImports import *
# endregion

class DeterminedTanGaur(QCAlgorithm):
    def Initialize(self):
        self.SetStartDate(2012, 1, 12)
        self.SetEndDate(2012, 1, 19)
        self.future = self.AddFuture(
            Futures.Indices.SP500EMini, 
            Resolution.Minute,
            dataMappingMode=DataMappingMode.OpenInterest,
            extendedMarketHours=True
        )

    def OnData(self, data):
        if self.Time.day in [15, 16, 17]:
            self.Plot(self.future.Symbol, 'Price', self.future.Price)
```

The plot shows a gap during the 16th.

We have the data: [20120116_es_minute_trade_201203_20120316.csv](https://www.quantconnect.com/data/file/future/cme/minute/es/20120116_trade.zip/20120116_es_minute_trade_201203_20120316.csv)

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by cperotlsq** [comment]
Hey @AlexCatarino, @Martin-Molinero, @Marinovsky, I think this issue might have been closed prematurely as the PR seems to only fix one date (the one originally used as an example).

I took the list of CME holidays from the [market-hours-database.json](https://github.com/Marinovsky/Lean/blob/059db1323f1bee198d573fe61fca9960d144a0e8/Data/market-hours/market-hours-database.json#L466-L720) and then intersected that with the early close days given by pandas market calendars. This yields a total of 169 more dates from 1998 through 2024 that are marked as holidays but pandas market calendars says are early close days (see screenshot below).

Maybe we can reopen the issue and look more into this?

Thanks,
Cameron

![Screenshot_2023-10-10_11-42-55](https://github.com/QuantConnect/Lean/assets/107538247/19741af6-9976-4e60-8fb4-1bf84f2168a9)
