### ISSUE TITLE
Order Events Serialization in Live Trading

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#7502]
#### Expected Behavior
The order events are correctly timestamped.

#### Actual Behavior
Oanda:
The Orders Tab (from serialized objects) shows the same timestamp for all order events of a canceled order: 
![capture_orders](https://github.com/QuantConnect/Lean/assets/6889033/aba11770-d507-4ffb-8a3d-0b3ebdb90ec2)

We can see the following order event:

```json
{
                    "algorithm-id": "L-39c02c8878467c2e5cd1e35062007a33",
                    "direction": "buy",
                    "fill-price": null,
                    "fill-price-currency": "JPY",
                    "fill-quantity": null,
                    "id": "L-39c02c8878467c2e5cd1e35062007a33-7-3",
                    "is-assignment": 0,
                    "order-event-id": 3,
                    "order-fee-amount": null,
                    "order-fee-currency": null,
                    "order-id": 7,
                    "quantity": 10,
                    "status": "canceled",
                    "symbol": "USDJPY 8G",
                    "symbol-value": "USDJPY",
                    "stop-price": 148.95699999999999,
                    "time": 1695731340,                                       // <-- this is the order time, not the event time
                    "timestamp": 1695731340
                }
```

While we can read in the logs that the events happens at different times
![capture_log](https://github.com/QuantConnect/Lean/assets/6889033/3982b8a9-8826-4ac5-8d89-235f366c8dc2)

In another case (QC Paper), the order status doesn't match the last event status:
![capture_old](https://github.com/QuantConnect/Lean/assets/6889033/912779fa-80a8-4950-86e0-25bd4b5df601)

#### Potential Solution
N/A

#### Reproducing the Problem
```python
# region imports
from AlgorithmImports import *
# endregion

class OrderEventsSerializationAlgorithm(QCAlgorithm):

    def Initialize(self):
        self.SetStartDate(2023, 10, 4)
        self.next = self.StartDate
        self.equity = self.AddEquity("SPY")

    def OnData(self, data: Slice):
        if list(self.Transactions.GetOrders()):
            if self.Time > self.next:
                self.Transactions.CancelOpenOrders()
            return

        self.LimitOrder(self.equity.Symbol, 1, self.equity.Price * .5)
        self.next = self.Time + timedelta(minutes=3)
```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jhonabreul** [comment]
This might be a frontend issue:

If you see the order events in the Orders tab after deploying and without closing the algo/browser, the order events are shown with the right timestamps. The table is scrambled though, the order events for the current order (placed at 2023-10-17 09:54:00) are under the first shown order (from another deployment).

![image](https://github.com/QuantConnect/Lean/assets/25215064/e54d1ce2-86d0-4fd9-8859-9946d2cc615f)

After closing and reopening the algorithm, the events are under the right order, but the timestamps are changed, showing the time at which the order was placed for all events.

![image](https://github.com/QuantConnect/Lean/assets/25215064/82305db5-aae4-46e8-b0cd-6a8d2e6b889c)

Also note how some of the events information is no longer shown after reopening the session: there are no tags, prices or quantities.

There could be a difference on the rendering of streamed order events shown right when they happen and the browser receives and renders them, and the stored events fetched when the live trading tab is open.

**Comment by gaviles** [comment]
Found that time in the object was expected as a string not timestamp, and updated the handler to support both.

Live:


![Image](https://github.com/QuantConnect/Lean/assets/3958194/cda37e38-f502-4583-b7bb-8499d3a40982)

Backtest:



![Image](https://github.com/QuantConnect/Lean/assets/3958194/2f7b80fe-abc4-4e58-b445-51e48c59ada5)

**Comment by gaviles** [comment]
Deployed fix in code environment:
https://github.com/QuantConnect/code.quantconnect.com/commit/ebb3374d57e659476712e8dbeefedc391cbaf4ec#diff-4ba72eaf787786de2fae94c9cd63f00ee6173fb0bbf39a357d30d0ca41198e48R298

Deployed fix in the API:
https://github.com/QuantConnect/template.quantconnect.com/pull/2966/files
https://github.com/QuantConnect/template.quantconnect.com/pull/2966/files
