### ISSUE TITLE
Use Market Hours Database To Help Define Futures' Expiration Dates

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#7506]
#### Expected Behavior
Use MHDB to help define futures' expiration dates. For example, holidays move the expiration one day back.

#### Actual Behavior
VIX Futures, for example, use the `USHoliday` class. This class has hardcoded holidays.

#### Potential Solution
Remove `USHoliday` and use always MHDB (see Futures.Indices.BloombergCommodityIndex in FutureExpirationFunctions.cs#L425).

#### Reproducing the Problem
We can see an incorrect contract in the dataset:
![capture](https://github.com/QuantConnect/Lean/assets/6889033/a8cff94a-fd71-4639-a9d7-21d38bf79add)
and live algorithms adds Juneteenth 2024:
> Runtime Error: No security definition has been found for the request. Origin: [Id=18] Subscribe: VX19M24 (FUT VIX USD CFE 202406**19** 0 ) 

#### Checklist

- [ ] I have completely filled out this template
- [ ] I have confirmed that this issue exists on the current `master` branch
- [ ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/Lean/pull/7605
