### ISSUE TITLE
Universe Subscription Speed Review

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#7553]
- Make universe smarter to not include its data in the slice.
 - Move universe selection to the data stack, removing stateful option selections. 
 - Removing ZipEntry universes and replacing with CSV versions for speed. 

Possibly related: (https://www.quantconnect.com/forum/discussion/10071/increasing-slowness-with-large-universe-option-backtests/p1)

**Comment by Martin-Molinero** [comment]
- Revisit the decision of keeping delisted securities in the Securities collection. When trading options the security count can grow significantly for a long running backtest causing a CPU/RAM overhead

**Comment by jaredbroad** [comment]
Completed by https://github.com/QuantConnect/Lean/pull/7573
