### ISSUE TITLE
Library Update: OpenAI and LangChain

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#7560]
#### Expected Behavior
openai==1.1.2
langchain==0.0.332

#### Actual Behavior
[openai==0.28.1](https://github.com/QuantConnect/Lean/blob/master/DockerfileLeanFoundation#L203C5-L203C19)
[langchain==0.0.316](https://github.com/QuantConnect/Lean/blob/master/DockerfileLeanFoundation#L227)

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by faisalanjum** [comment]
Can you use a more stable version of the OpenAI library? I believe they recently updated the library to 1.2.2

**Comment by faisalanjum** [comment]
Hi, could you please update these libraries to their latest versions?

**Comment by faisalanjum** [comment]
@Martin-Molinero Please update them using the latest libraries here: https://pypi.org/project/openai/#history and https://pypi.org/project/langchain/#history . Thanks

**Comment by faisalanjum** [comment]
@Martin-Molinero - While you are at it, can you please also install the latest version of LangGraph which is closely related to LangChain. Many Thanks!
