### ISSUE TITLE
ApiDataProvider throws error

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#7565]
#### Expected Behavior

`lean backtest "projectName" --download-data` runs without error

#### Actual Behavior

> 20231110 22:50:04.273 ERROR:: BaseResultsHandler.GenerateStatisticsResults(): BaseResultsHandler.GenerateStatisticsResults(): Error generating statistics packet
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: ApiDataProvider.Fetch(): No price found for alternative/interest-rate/usa/interest-rate.csv

#### Potential Solution

N/A

#### Reproducing the Problem

Use this project
```
class EncryptTest(QCAlgorithm):

    def Initialize(self):
        # Locally Lean installs free sample data, to download more data please visit https://www.quantconnect.com/docs/v2/lean-cli/datasets/downloading-data
        self.SetStartDate(2023, 10, 1)  # Set Start Date
        self.SetEndDate(2023, 11, 1)  # Set End Date
        self.SetCash(100000)  # Set Strategy Cash
        self.AddEquity("TSLA", Resolution.Daily)
        self.AddEquity("AAPL", Resolution.Daily)

    def OnData(self, data: Slice):
        """OnData event is the primary entry point for your algorithm. Each new data point will be pumped in here.
            Arguments:
                data: Slice object keyed by symbol containing the stock data
        """
        if not self.Portfolio.Invested:
            self.SetHoldings("TSLA", 1)
            self.Debug("Purchased Stock")
```
and run
```
lean backtest "projectName" --download-data
```

#### System Information

Windows 11

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Issue has been solved 👍
