### ISSUE TITLE
URGENT!!! Continuous futures History calls returning 0 data points for certain futures

### ISSUE THREAD

**Issue by gmwhipple** [QuantConnect/Lean#7571]
#### Expected Behavior
future.Symbol to work in futures history calls for every symbol

#### Actual Behavior
Futures.Indices.Dow30EMini, Futures.Grains.Corn, Futures.Grains.SoybeanOil, Futures.Grains.Wheat, Futures.Financials.Y2TreasuryNote,  Futures.Financials.Y30TreasuryBond, Futures.Financials.Y5TreasuryNote, Futures.Financials.Y10TreasuryNote all return length of 0 data from history calls. whereas other futures actually return data. this started happening last week.

#### Potential Solution
n/a

#### Reproducing the Problem
Run this for each future one by one and see how it only works for some: 

#load "../Initialize.csx"
#load "../QuantConnect.csx"
#r "../Plotly.NET.dll"
using QuantConnect;
using QuantConnect.Data;
using QuantConnect.Data.Market;
using QuantConnect.Securities;
using QuantConnect.Securities.Future;
using QuantConnect.Algorithm;
using QuantConnect.Research;
using System;
using System.Linq;
using System.Data;
using System.Collections.Generic;
using System.Runtime;
using System.Diagnostics;
using Newtonsoft.Json;
using System.Threading.Tasks;
using Plotly.NET;
using Plotly.NET.LayoutObjects;
using static Plotly.NET.StyleParam;
using Microsoft.AspNetCore.Html;
var qb = new QuantBook();

DateTime startDate = new DateTime(2022, 6, 19);
DateTime endDate = new DateTime(2022, 7, 19);
var startDate2 = startDate;
var endDate2 = endDate;

List<string> futuresContracts = new List<string> {
    //Futures.Indices.SP500EMini,       // ES
    //Futures.Indices.NASDAQ100EMini,   // NQ
    //---Futures.Indices.Dow30EMini,       // YM
    //Futures.Indices.Russell2000EMini, //RTY
    //Futures.Metals.Gold,      // GC
    //Futures.Metals.Copper,            // HG
    //Futures.Metals.Silver,    // SI
    Futures.Grains.Corn,              // ZC, cbot
    //---Futures.Grains.Soybeans,          // ZS
    ////Futures.Grains.SoybeanMeal,       // ZM
    //----Futures.Grains.SoybeanOil,        // ZL
    //----Futures.Grains.Wheat,             // ZW
    //----Futures.Financials.Y2TreasuryNote,   //CBOT 
    //----Futures.Financials.Y30TreasuryBond,
    //----Futures.Financials.Y5TreasuryNote, // ZF
    //-----Futures.Financials.Y10TreasuryNote,
    //Futures.Energies.CrudeOilWTI,     // CL
    //Futures.Energies.NaturalGas,      // NG, nymex
    //Futures.Energies.HeatingOil,      // HO
    //Futures.Energies.Gasoline,        // RB
};

Dictionary<string, Future> futureSecurities = futuresContracts.ToDictionary(
    contract => contract,
    contract => qb.AddFuture(contract, Resolution.Minute,
                             dataNormalizationMode: DataNormalizationMode.Raw,
                             dataMappingMode: DataMappingMode.OpenInterest,
                             contractDepthOffset: 0));

    
List<Dictionary<string, object>> allOrders = new List<Dictionary<string, object>>();

foreach (var future in futureSecurities.Values)
{
    DateTime currentDate = startDate;
    while (currentDate < endDate)
    {

    
        var minuteOHLC = qb.History(future.Symbol, currentDate, currentDate.AddDays(1), Resolution.Minute);
        Console.WriteLine($"Length of minuteOHLC for symbol {future.Symbol}: {minuteOHLC.Count()}");

        currentDate = currentDate.AddDays(1);
    }
}

#### System Information
MacOS/Chrome . using Quantconnect cloud

#### Checklist

- [x ] I have completely filled out this template
- [ x] I have confirmed that this issue exists on the current `master` branch
- [ x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ x] I have provided detailed steps to reproduce the issue

**Comment by gmwhipple** [comment]
Issue seems to be transient. randomly futures will stop working, and then start working again. For example Corn now returns only a few data points on tick resolution data, all others return 100K+ data points for each day

`// Define start and end dates
DateTime startDate = new DateTime(2022, 6, 19);
DateTime endDate = new DateTime(2022, 6, 23);
var startDate2 = startDate;
var endDate2 = endDate;

List<string> futuresContracts = new List<string> {
    //Futures.Indices.SP500EMini,       // ES
    //Futures.Indices.NASDAQ100EMini,   // NQ
    //Futures.Indices.Dow30EMini,       // YM
    //Futures.Indices.Russell2000EMini, //RTY
    //Futures.Metals.Gold,      // GC
    //Futures.Metals.Copper,            // HG
    //Futures.Metals.Silver,    // SI
    Futures.Grains.Corn,              // ZC, cbot
    //Futures.Grains.Soybeans,          // ZS
    ////Futures.Grains.SoybeanMeal,       // ZM
    //-----Futures.Grains.SoybeanOil,        // ZL
    //----Futures.Grains.Wheat,             // ZW
    //Futures.Financials.Y2TreasuryNote,   //CBOT 
    //----Futures.Financials.Y30TreasuryBond,
    //----Futures.Financials.Y5TreasuryNote, // ZF
    //-----Futures.Financials.Y10TreasuryNote,
    //Futures.Energies.CrudeOilWTI,     // CL
    //Futures.Energies.NaturalGas,      // NG, nymex
    //Futures.Energies.HeatingOil,      // HO
    //Futures.Energies.Gasoline,        // RB
};


Dictionary<string, Future> futureSecurities = futuresContracts.ToDictionary(
    contract => contract,
    contract => qb.AddFuture(contract, Resolution.Tick,
                             dataNormalizationMode: DataNormalizationMode.Raw,
                             dataMappingMode: DataMappingMode.OpenInterest,
                             contractDepthOffset: 0));

    
List<Dictionary<string, object>> allOrders = new List<Dictionary<string, object>>();


foreach (var future in futureSecurities.Values)
{
    DateTime currentDate = startDate;
    while (currentDate < endDate)
    {

        var minuteOHLC = qb.History<Tick>(future.Symbol, currentDate, currentDate.AddDays(1), Resolution.Tick);
        //var minuteOHLC = qb.History(Futures.Grains.Corn, currentDate, currentDate.AddDays(1), Resolution.Minute);
        Console.WriteLine($"Length of minuteOHLC for symbol {future.Symbol}: {minuteOHLC.Count()}");


        currentDate = currentDate.AddDays(1);
    }
}
`

![Screen Shot 2023-11-14 at 2 49 14 PM](https://github.com/QuantConnect/Lean/assets/12890514/6b0b4a7b-e7d6-4ba9-b40c-989b3de0c585)

**Comment by gmwhipple** [comment]
Same code but for silver. (ignore the minuteOHLC name, this is using ticks) 
![Screen Shot 2023-11-14 at 2 52 01 PM](https://github.com/QuantConnect/Lean/assets/12890514/ed6f320f-73c1-4f5b-b922-b88f20c0651b)

**Comment by Martin-Molinero** [comment]
Hey @gmwhipple! Thank you for the report, this has been fixed
