### ISSUE TITLE
Cloud Research Notebooks fail to restart

### ISSUE THREAD

**Issue by gmwhipple** [QuantConnect/Lean#7572]
#### Expected Behavior
clicking "restart" at the top of the notebook will interrupt current process and allow me to run the notebook as if it was fresh with no problems

#### Actual Behavior
the notebook seems to interrupt but the cell that was running during the restart becomes corrupted and can no longer be executed. displays a square symbol in place of the play button. upon clicking the square the notebook displays a waiting symbol infinitely. 

#### Potential Solution
only solution is to stop the research node and close out of the project, then re open the project.

#### Reproducing the Problem
run this code, then click "restart" while it is still running:

#load "../Initialize.csx"

#load "../QuantConnect.csx"
#r "../Plotly.NET.dll"
using QuantConnect;
using QuantConnect.Data;
using QuantConnect.Data.Market;
using QuantConnect.Securities;
using QuantConnect.Securities.Future;
using QuantConnect.Algorithm;
using QuantConnect.Research;
using System;
using System.Linq;
using System.Data;
using System.Collections.Generic;
using System.Runtime;
using System.Diagnostics;
using Newtonsoft.Json;
using System.Threading.Tasks;
using Plotly.NET;
using Plotly.NET.LayoutObjects;
using static Plotly.NET.StyleParam;
using Microsoft.AspNetCore.Html;

var qb = new QuantBook();

// Define start and end dates
DateTime startDate = new DateTime(2022, 6, 19);
DateTime endDate = new DateTime(2022, 6, 25);
var startDate2 = startDate;
var endDate2 = endDate;

List<string> futuresContracts = new List<string> {
    //Futures.Indices.SP500EMini,       // ES
    Futures.Indices.NASDAQ100EMini,   // NQ
    //---Futures.Indices.Dow30EMini,       // YM
    //Futures.Indices.Russell2000EMini, //RTY
    //Futures.Metals.Gold,      // GC
    //Futures.Metals.Copper,            // HG
    //Futures.Metals.Silver,    // SI
    //-----Futures.Grains.Corn,              // ZC, cbot
    //---Futures.Grains.Soybeans,          // ZS
    ////Futures.Grains.SoybeanMeal,       // ZM
    //----Futures.Grains.SoybeanOil,        // ZL
    //----Futures.Grains.Wheat,             // ZW
    //----Futures.Financials.Y2TreasuryNote,   //CBOT 
    //----Futures.Financials.Y30TreasuryBond,
    //----Futures.Financials.Y5TreasuryNote, // ZF
    //-----Futures.Financials.Y10TreasuryNote,
    //Futures.Energies.CrudeOilWTI,     // CL
    //Futures.Energies.NaturalGas,      // NG, nymex
    //Futures.Energies.HeatingOil,      // HO
    //Futures.Energies.Gasoline,        // RB
};

Dictionary<string, Future> futureSecurities = futuresContracts.ToDictionary(
    contract => contract,
    contract => qb.AddFuture(contract, Resolution.Tick,
                             dataNormalizationMode: DataNormalizationMode.Raw,
                             dataMappingMode: DataMappingMode.OpenInterest,
                             contractDepthOffset: 0));

    
List<Dictionary<string, object>> allOrders = new List<Dictionary<string, object>>();

foreach (var future in futureSecurities.Values)
{
    DateTime currentDate = startDate;
    while (currentDate < endDate)
    {

        var minuteOHLC = qb.History<Tick>(future.Symbol, currentDate, currentDate.AddDays(1), Resolution.Tick);
        //var minuteOHLC = qb.History(Futures.Grains.Corn, currentDate, currentDate.AddDays(1), Resolution.Minute);
        Console.WriteLine($"Length of minuteOHLC for symbol {future.Symbol}: {minuteOHLC.Count()}");

        currentDate = currentDate.AddDays(1);
    }
}

#### System Information
Chrome V119.0.6045.123 (x86_64)
MacOS

#### Checklist

- [x ] I have completely filled out this template
- [ x] I have confirmed that this issue exists on the current `master` branch
- [ x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @gmwhipple! Thank you for the report, please contact support directly to handle these issues that are not related to a lean core issue.
