### ISSUE TITLE
Dynamic Symbol Properties

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#7584]
#### Expected Behavior
Symbol Properties can be changed. 
More specifically: brokerages can change symbol properties on the fly. E.g. minimum order size. If the order minimum increases, orders will fail. Some brokerages provide this information via API, so LEAN could update them once per day.

#### Actual Behavior
Symbol properties are not configurable.

#### Potential Solution
N/A

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
A daily automated reprocessor of the current static implementation should be sufficient.  

This would be updated via scheduled GitHub action and pushed to the CDN bucket.

**Comment by Martin-Molinero** [comment]
#### Potential Solution

- Add new setting for SPDB & MHDB update period, default to daily
- Through the `LiveTradingRealTimeHandler`, like done by the MHDB, we can trigger the SPDB refresh which reloads the file & updates the securities `SymbolProperties`
