### ISSUE TITLE
Improve ETFConstituentsUniverseSelectionModel

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#7590]
#### Expected Behavior
We can create an `ETFConstituentsUniverseSelectionModel` with the following overload:
```python
model = ETFConstituentsUniverseSelectionModel("SPY")
```
and receive all Symbol.

#### Actual Behavior
We need to provide a Symbol object:
```python
model = ETFConstituentsUniverseSelectionModel( Symbol.Create("SPY", SecurityType.Equity, Market.USA) , self.UniverseSettings)
```

or add SPY first to benefit from implicit conversion:
```python
self.AddEquiy("SPY")
model = ETFConstituentsUniverseSelectionModel("SPY", self.UniverseSettings)
```

We also need to define a filter function:
```python
model = ETFConstituentsUniverseSelectionModel("SPY", self.UniverseSettings,
            lambda constituents: [x.Symbol for x in constituents])
```

Otherwise we get an exception:
```
Object reference not set to an instance of an object. in Extensions.cs:line 2703
```

because the callback method (filter function) is null.

We should default to all.

#### Reproducing the Problem
It doesn't subscribe to data:
https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_5e45319f3eaa92a1c0f75726cfa3482d.html

```python
# region imports
from AlgorithmImports import *
# endregion

class CalculatingGreenGaur(QCAlgorithm):

    def Initialize(self):
        self.SetStartDate(2023, 6, 1)
        self.SetEndDate(2023, 7, 1)
        self.SetCash(1000000)
        self.SetUniverseSelection(ETFConstituentsUniverseSelectionModel("SPY", self.UniverseSettings))
        self.SetAlpha(ConstantAlphaModel(InsightType.Price, InsightDirection.Up, timedelta(minutes = 20), 0.025, None))
        self.SetPortfolioConstruction(EqualWeightingPortfolioConstructionModel())
```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by DerekMelchin** [comment]
If we omit the filter func arg, we still get the error
https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_0a060d8ca44dfa6c0e14db5fcc8763d8.html
