### ISSUE TITLE
Implied Volatility and Greek Indicators

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#7611]
#### Expected Behavior

Lean has built-in indicators for IV and Greeks.

Here are the inputs to calculating each indicator:
- Implied Volatility
  - The market price of the option.
  - The underlying stock price.
  - The strike price.
  - The time to expiration.
  - The risk-free interest rate.
- Delta
  - Stock price
  - Option premium
- Gamma
  - Stock price
  - Option premium
  - Time to expiration
- Vega
  - Stock price
  - Option premium
  - Time to expiration
- Theta
  - Stock price
  - Time to expiration
  - The risk-free interest rate.
  - Strike price
- Rho
  - Strike price
  - The risk-free interest rate.
  - Time to expiration

#### Actual Behavior

No built-in indicators

#### Potential Solution

N/A

#### Reproducing the Problem

N/A

#### System Information

N/A

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
- [ ] Indicators implemented and pull requested with test data.
 - [ ] Research report created
 - [ ] Documentation written coding the third party sources and plots of the vol smiles.
