### ISSUE TITLE
Net 9 Migration

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#7612]
#### Expected Behavior

- Migrate to Net 8 which is long term support: all repos, images
#### Actual Behavior

- Using Net 6
#### Potential Solution

N/A
#### Reproducing the Problem

N/A
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment]
We might want to do this with the Python upgrade.  
https://devguide.python.org/versions/
[pythonnet supports 3.12](https://github.com/pythonnet/pythonnet/pull/2249), so can LEAN.

**Comment by Martin-Molinero** [comment]
Net 9 is released
