### ISSUE TITLE
InteractiveBrokersShortableProvider Provides the Borrowing Cost

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#7614]
#### Expected Behavior
InteractiveBrokersShortableProvider provides the borrowing cost (and rebate fee).
since this data is available. E.g:
```
#SYM|CUR|NAME|CON|ISIN|REBATERATE|FEERATE|AVAILABLE|
AAPL|USD|APPLE INC|265598|XXXXXXX31005|5.0700|0.2500|10000000|
```
The borrowing cost to short AAPL is 0.25% per year (`FEERATE` column).

#### Actual Behavior
Not supported.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Adding both Borrowing Cost and Rebate Fee.

 - Check to see if Axos includes this information; if so we have a pattern of 2 and we can extend the shortable provider with 2 new fields on that interface.  
  - Extend the IBKR Shortable reader to parse that data.
  - Default to Nullable properties so they're not required.
