### ISSUE TITLE
Slice FutureChain Does Not Have Elements of FutureChainProvider

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#7628]
#### Expected Behavior
`Slice.FutureChain` has the elements of `FutureChainProvider` for a given date that obeys the filter criteria.

#### Actual Behavior
Sometimes, the `Slice.FutureChain` is empty, and we can get contracts from the `FutureChainProvider`. 
The `Slice.FutureChain` should never be empty if the filter range has more than 3 months (200 days).

#### Potential Solution
N/A

#### Reproducing the Problem
```python
# region imports
from AlgorithmImports import *
# endregion

class VirtualBlueDuck(QCAlgorithm):

    def Initialize(self):
        self.SetStartDate(2010, 1, 1)
        self.SetEndDate(self.StartDate.replace(year=self.StartDate.year+1))
        self.SetCash(100000)
        future = self.AddFuture("NQ")
        future.SetFilter(0, 200)
        self.symbol = future.Symbol
        self.day = 0

    def OnData(self, data: Slice):
        if not (data.Bars and data.QuoteBars):
            return
        if self.day == self.Time.day or self.Time.hour < 10:
            return
        chain = data.FutureChains.get(self.symbol)
        if chain: return
        symbols = self.FutureChainProvider.GetFutureContractList(self.symbol , self.Time)
        symbols = [x for x in symbols if 0 <= (x.ID.Date-self.Time).days < 200]
        if symbols:
            symbols = sorted(symbols, key=lambda x: x.ID.Date)
            msg = f'Empty chain on {self.Time}: Chain Provider: '
            msg += ','.join([f'{x.ID.Date:%Y%m%d}->{x.Value}' for x in symbols])
            self.Log(msg)    
        self.day = self.Time.day
```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by ashutoshrana171** [comment]
I backtested the same code again but saw no output with an empty chain for "data.FutureChains.get(self.symbol)"
Found contracts for each day using FutureChains.

![image](https://github.com/QuantConnect/Lean/assets/62750665/76ea89e2-104b-47af-8fc8-3b69adf6dd2c)
