### ISSUE TITLE
OptionFilterUniverse filter by option price

### ISSUE THREAD

**Issue by doudoujay** [QuantConnect/Lean#7641]
It would be nice to have the option filter universe filter by option price (ask, bid, mid, last).

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @doudoujay! Thanks for the report, we are going to tackle this soon at https://github.com/QuantConnect/Lean/issues/3083, we will add price/volumes/pre calculated greeks & underlying price
