### ISSUE TITLE
Unnecessary data requirements for MOO order

### ISSUE THREAD

**Issue by superichmann** [QuantConnect/Lean#7661]
#### Expected Behavior
MOO Order should be executed and filled.

#### Actual Behavior
MOO Order is not executed and filled.

#### Reproducing the Problem
Create a strat with one ticker on Daily resolution.
Call `s = AddEquity("SPY", Resolution.Daily).Symbol;`
call `Schedule.On(DateRules.EveryDay(s), TimeRules.AfterMarketOpen(s, -6), func);` on initialize
send a `MarketOnOpenOrder` from `func` and save the ticket.
inspect the ticker later that day or have a look at order-events json file.
the orders are only submitted but not filled.

Change the resolution to Minute and re run the strat.
the orders are now submitted and filled although minute data is **not needed** for the daily strat.

#### System Information
windows
c#

maybe the issue is related to the fact that daily bars are at midnight and we don't have the open price until the day has actually ended. but on backtesting it is possible to get this value in some manner at the end of day or at the end of the strat.
in live the value is returned from the broker after the order is filled.

**Comment by Martin-Molinero** [comment]
Hey @superichmann!
Market on open orders are expected to be filled on the open of the next day. Suggest visiting our documentation for more [information](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/order-types/market-on-open-orders).

**Comment by superichmann** [comment]
@Martin-Molinero yes I know. for backtesting purposes: can you confirm that sending a MARKET order at the start of the day  is similar to MOO order?

**Comment by AlexCatarino** [comment]
Hi @superichmann ,
Market-on-open orders participate in the opening auction and are filled with the opening price (the result of the opening auction). On the other hand, market orders are filled according to the counterparts in the order book. In a backtest, we assume market orders are immediately filled with the bid or ask, so sending the market order at the start of the day is not similar to MOO orders.

This difference is explained in the Docs.
- [MOO](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/order-types/market-on-open-orders#01-Introduction)
- [MKT](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/order-types/market-orders#01-Introduction)
