### ISSUE TITLE
Custom Settlement Models for Python

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#7676]
#### Expected Behavior

We can create custom settlement models in Python

#### Actual Behavior

There isn't currently a Python wrapper for it. There is also no SetSettlementModel method.

#### Potential Solution

N/A

#### Reproducing the Problem

https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_2d622e84fd6ace5ff1786db168bfcf2a.html

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Should be solved by https://github.com/QuantConnect/Lean/pull/7672
