### ISSUE TITLE
Add FDUSD-Quoted Crypto Pairs

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#7692]
#### Expected Behavior
The following pairs are listed for Binance:
- "ADAFDUSD"
- "LTCFDUSD"
- "DOTFDUSD"
- "MATICFDUSD"
- "SHIBFDUSD"
- "AVAXFDUSD"
- "FILFDUSD"
- "LTCFDUSD"
- "ATOMFDUSD"
- "BCHFDUSD"
- "ALGOFDUSD"
- "FTMFDUSD"
- "LINKFDUSD"
- "NEARFDUSD"
See https://www.binance.com/api/v3/exchangeInfo

#### Actual Behavior
Some of these pairs are not included.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by starteleport** [comment]
Hi! As an original requestor, I'd like to handle this issue myself and submit a PR.
