### ISSUE TITLE
Paper trading > feature request 

### ISSUE THREAD

**Issue by LA-TRDR** [QuantConnect/Lean#7731]
#### Expected Behavior
data from brokers live / real account, trades by the bot, stats into QuantConnect. Without demo / test account by the broker. 
Data without the trades can be deleted immediately. Data with trades after some timelike in 24 (?) hours, in case its too capacious, after review and analyse.

#### Actual Behavior
demo accounts have no real situations from the live markets + brokers test their things and the price looks manipulated many times. Some crypto exchanges offer test environments, which looks weird compared to real market environments. Majority of crypto exchanges are too small so cannot get adequate market behaviour as well...  

#### Potential Solution
see "expected behavior"

#### Checklist

- [ ] I have completely filled out this template
- [ ] I have confirmed that this issue exists on the current `master` branch
- [ ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @LA-TRDR! Lean supports paper brokerage with any live data feed set, even if the brokerage does not have paper trading. Suggest taking a look at our documentation which covers both QC cloud & local use cases https://www.quantconnect.com/docs/v2/

**Comment by LA-TRDR** [comment]
Thank you, Found thisone: https://www.quantconnect.com/docs/v2/cloud-platform/live-trading/brokerages/quantconnect-paper-trading#01-Introduction    Seems my vision/requirmeents exactly:"Paper Trading lets you run live, real-time [data feeds] into your algorithm but execute trades using fictional capital. Instead of your orders being routed to an exchange when you're paper trading, your order fills are simulated. "  Thank you for that

**Comment by LA-TRDR** [comment]
Thank you,

As I understand I can get data (volume) from multiple crypto sources
simultaneously for the same /one ticket / pair / instrument?

https://www.quantconnect.com//docs/v2/lean-cli/live-trading/brokerages/quantconnect-paper-trading#01-Introduction


[image: image.png]

OKX gonna be available soon?

Thnx,

L.



Kontakt Martin-Molinero ***@***.***>) kirjutas kuupäeval K,
31. jaanuar 2024 kell 01:01:
