### ISSUE TITLE
CalculateOrderQuantity returns negative number

### ISSUE THREAD

**Issue by superichmann** [QuantConnect/Lean#7765]
#### Expected Behavior
returned value should be a positive number or 0.

#### Actual Behavior
returned value is negative 

#### Potential Solution
Maybe LEAN should already see that there is a closing order for the original order (I do submit it before setting the new one) and treat it as an available funds for the new order.

#### Reproducing the Problem
set `equity.SetBuyingPowerModel(new SecurityMarginModel(4m));`
send MOC order with 1 as the target parameter for CalculateOrderQuantity.
day after - send MOO order closing the first order.
as well send MOO order for the same day and the same ticker with 1 as the target parameter for CalculateOrderQuantity.

result from CalculateOrderQuantity will have minus value, causing a short on the ticker. (which was not the intention).

If this is the expected behavior, please tell me why :).

#### System Information
latest lean on windows 10

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @superichmann! Please take a look at our [documentation](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/position-sizing), position sizing is not trivial. `CalculateOrderQuantity` can return a negative amount to adjust the position to the target requested percentage.

**Comment by superichmann** [comment]
cool @Martin-Molinero thanks for the clarification.

Would setting target 0.5 fix my issue?
