### ISSUE TITLE
Plot SeriesType.Scatter does not work

### ISSUE THREAD

**Issue by vguruv** [QuantConnect/Lean#7771]
#### Expected Behavior

Plot SeriesType.Scatter expected to work as in sample code https://www.quantconnect.com/docs/v2/writing-algorithms/charting#05-Examples

#### Actual Behavior

Plot SeriesType.Scatter does not work and fails with browser console error:
ERR [Extension Host] {"success":false,"error":"Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'QuantConnect.ScatterChartPoint' because the type requires a JSON object (e.g. {\"name\":\"value\"}) to deserialize correctly.\nTo fix this error either change the JSON to a JSON object (e.g. {\"name\":\"val
 

#### Reproducing the Problem

https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_bc14ce54f78e8b0db856a7356d04ff17.html

#### System Information

Chrome Latest

#### Checklist

- [x ] I have completely filled out this template
- [x ] I have confirmed that this issue exists on the current `master` branch
- [ x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Thank you for the report @vguruv, we will fix this asap
