### ISSUE TITLE
"NQX" index option is not accessible through slice object.

### ISSUE THREAD

**Issue by ashutoshrana171** [QuantConnect/Lean#7801]
#### Expected Behavior
We should get OptionChains from the slice object for "NQX" -> weekly contracts for the underlying index "NDX"
Reference: https://www.quantconnect.com/datasets/algoseek-us-index-options

#### Actual Behavior
We do not get OptionChains for "NQX" for all timeframes and for all resolutions but we get data using `OptionChainProvider.GetOptionContractList(option.Symbol, time)`. 
Note: We get data for all other index options using both slice object and OptionChainProvider.GetOptionContractList()

#### Potential Solution
We have the data which is confirmed by data from `OptionChainProvider.GetOptionContractList(option.Symbol, time)`. Could be a mapping issue for "NQX".

#### Reproducing the Problem
Attaching the [backtest](https://www.quantconnect.com/terminal/processCache/?request=embedded_backtest_f2290a8aaff3cad293a649771d34a12e.html) for reference.

![image](https://github.com/QuantConnect/Lean/assets/62750665/82fd4cfd-7dd3-4f6e-9736-25e493556b9d)
data.OptionChains.get() for "NQX" is always empty.

Data for NQX is available when we use:
```
self = QuantBook()
index_symbol = self.AddIndex("NDX").Symbol
option = self.AddIndexOption(index_symbol, "NQX")
option.SetFilter(lambda universe: universe.IncludeWeeklys().Strikes(-2, 2).Expiration(0, 30))
time = datetime(2023, 6, 1)
symbols = self.OptionChainProvider.GetOptionContractList(option.Symbol, time)
self.History(symbols[:5], time, time+timedelta(2), Resolution.Daily, fillForward=False)
```
![image](https://github.com/QuantConnect/Lean/assets/62750665/15cbc898-a8a9-4bd3-bb78-8ee04c0364ed)

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by jmullen** [comment]
I pulled past this change and still unable to get a valid OptionsChain with NQX in back testing.

**Comment by jmullen** [comment]
[Update] It looks like the chain is there, just the Greeks aren't populated (and I am filtering on Greeks)

**Comment by Martin-Molinero** [comment]
> [Update] It looks like the chain is there, just the Greeks aren't populated (and I am filtering on Greeks)

Hey @jmullen! please share some code/project reproducing the issue and we will take a look
