### ISSUE TITLE
Unable to start Lean. Several errors.

### ISSUE THREAD

**Issue by demo055** [QuantConnect/Lean#7809]
network: lean_cli
Package source with Name: Package source 1 added successfully.
The template "Solution File" was created successfully.
The template "Class Library" was created successfully.
  Determining projects to restore...
  Writing /tmp/tmpSIbtmO.tmp
info : Adding PackageReference for package 'QuantConnect.InteractiveBrokersBrokerage' into project '/ModulesProject/ModulesProject.csproj'.
info : Restoring packages for /ModulesProject/ModulesProject.csproj...
info : Installed QuantConnect.InteractiveBrokersBrokerage 2.5.16263 from /Modules with content hash be45djqbvyAF/eOkxxrxBGlEx5fYAOeSXkK+a/4pIpBCKKpDobv/2nJa0ZtDpFrLe3IKJCGnjccTZve18FZUGw==.
info : Package 'QuantConnect.InteractiveBrokersBrokerage' is compatible with all the specified frameworks in project '/ModulesProject/ModulesProject.csproj'.
info : PackageReference for package 'QuantConnect.InteractiveBrokersBrokerage' version '2.5.16263' added to file '/ModulesProject/ModulesProject.csproj'.
info : Committing restore...
info : Generating MSBuild file /Compile/obj/ModulesProject/ModulesProject.csproj.nuget.g.props.
info : Generating MSBuild file /Compile/obj/ModulesProject/ModulesProject.csproj.nuget.g.targets.
info : Writing assets file to disk. Path: /Compile/obj/ModulesProject/project.assets.json
log  : Restored /ModulesProject/ModulesProject.csproj (in 613 ms).
  Determining projects to restore...
  Writing /tmp/tmpnYStF9.tmp
info : Adding PackageReference for package 'QuantConnect.InteractiveBrokersBrokerage.ToolBox' into project '/ModulesProject/ModulesProject.csproj'.
info : Restoring packages for /ModulesProject/ModulesProject.csproj...
info : Installed QuantConnect.InteractiveBrokersBrokerage.ToolBox 2.5.16263 from /Modules with content hash rKvqIK9uTzhYbkdoAK5uVrwA//EB76SrbWt5NiIpMUohyPvGgByMLrhJALSgEyR1qUnyqb1P3ji/QiGqsx0XGg==.
info : Package 'QuantConnect.InteractiveBrokersBrokerage.ToolBox' is compatible with all the specified frameworks in project '/ModulesProject/ModulesProject.csproj'.
info : PackageReference for package 'QuantConnect.InteractiveBrokersBrokerage.ToolBox' version '2.5.16263' added to file '/ModulesProject/ModulesProject.csproj'.
info : Committing restore...
info : Writing assets file to disk. Path: /Compile/obj/ModulesProject/project.assets.json
log  : Restored /ModulesProject/ModulesProject.csproj (in 589 ms).
20240222 10:53:19.965 TRACE:: Config.Get(): Configuration key not found. Key: plugin-directory - Using default value:
20240222 10:53:19.971 TRACE:: Composer(): Loading Assemblies from /Lean/Launcher/bin/Debug
20240222 10:53:20.001 TRACE:: Python for .NET Assembly: Python.Runtime, Version=2.0.25.0, Culture=neutral, PublicKeyToken=5000fea6cba702dd
20240222 10:53:20.025 TRACE:: Config.Get(): Configuration key not found. Key: version-id - Using default value:
20240222 10:53:20.065 TRACE:: Config.Get(): Configuration key not found. Key: cache-location - Using default value:
20240222 10:53:20.066 TRACE:: Engine.Main(): LEAN ALGORITHMIC TRADING ENGINE v2.5.0.0 Mode: DEBUG (64bit) Host: cdrex
20240222 10:53:20.071 TRACE:: Engine.Main(): Started 10:53 AM
20240222 10:53:20.076 TRACE:: Config.Get(): Configuration key not found. Key: lean-manager-type - Using default value: LocalLeanManager
20240222 10:53:20.093 TRACE:: JobQueue.NextJob(): Selected /LeanCLI/main.py
20240222 10:53:20.170 TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-capacity - Using default value: 120
20240222 10:53:20.171 TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-time-interval-minutes - Using default value: 1440
20240222 10:53:20.171 TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-refill-amount - Using default value: 18
20240222 10:53:20.173 TRACE:: Config.GetValue(): storage-limit - Using default value: 10737418240
20240222 10:53:20.173 TRACE:: Config.GetValue(): storage-permissions - Using default value: 3
20240222 10:53:20.180 TRACE:: Config.Get(): Configuration key not found. Key: data-channel - Using default value:
20240222 10:53:20.180 TRACE:: Config.Get(): Configuration key not found. Key: python-venv - Using default value:
20240222 10:53:23.168 TRACE:: Config.Get(): Configuration key not found. Key: data-permission-manager - Using default value: DataPermissionManager
20240222 10:53:23.176 TRACE:: Config.GetValue(): streamed-chart-limit - Using default value: 12
20240222 10:53:23.177 TRACE:: Config.GetValue(): streamed-chart-group-size - Using default value: 3
20240222 10:53:23.187 TRACE:: Config.GetValue(): zip-data-cache-provider - Using default value: 10
20240222 10:53:23.189 TRACE:: Config.Get(): Configuration key not found. Key: fundamental-data-provider - Using default value: CoarseFundamentalDataProvider
20240222 10:53:23.192 TRACE:: AlgorithmManager.CreateTokenBucket(): Initializing LeakyBucket: Capacity: 120 RefillAmount: 18 TimeInterval: 1440
20240222 10:53:23.192 TRACE:: Config.GetValue(): algorithm-manager-time-loop-maximum - Using default value: 20
20240222 10:53:23.205 TRACE:: Engine.Run(): Resource limits '0' CPUs. 2147483647 MB RAM.
20240222 10:53:23.205 TRACE:: TextSubscriptionDataSourceReader.SetCacheSize(): Setting cache size to 71582788 items
20240222 10:53:23.206 TRACE:: Config.GetValue(): consumer-batching-timeout-ms - Using default value: 0
20240222 10:53:23.243 TRACE:: Config.GetValue(): downloader-data-update-period - Using default value: 7
20240222 10:53:23.452 ERROR:: MarketHoursDatabaseJson.Convert():  System.ArgumentException: An item with the same key has already been added. Key: 7/3/2000 12:00:00 AM
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at QuantConnect.Util.LinqExtensions.ToDictionary[K,V](IEnumerable`1 enumerable) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Common/Util/LinqExtensions.cs:line 38
   at QuantConnect.Util.MarketHoursDatabaseJsonConverter.MarketHoursDatabaseEntryJson.Convert(Entry underlyingEntry, Entry marketEntry) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Common/Util/MarketHoursDatabaseJsonConverter.cs:line 308
   at QuantConnect.Util.MarketHoursDatabaseJsonConverter.MarketHoursDatabaseJson.Convert() in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Common/Util/MarketHoursDatabaseJsonConverter.cs:line 102
20240222 10:53:23.457 TRACE:: Config.GetValue(): algorithm-creation-timeout - Using default value: 90
20240222 10:53:23.461 TRACE:: PythonInitializer.Initialize(): start...
PythonEngine.Initialize(): clr GetManifestResourceStream...
20240222 10:53:23.717 TRACE:: PythonInitializer.Initialize(): ended
20240222 10:53:23.719 TRACE:: AlgorithmPythonWrapper(): Python version 3.8.16 (default, Jan 17 2023, 23:21:03)
[GCC 11.2.0]: Importing python module main
20240222 10:53:27.512 TRACE:: AlgorithmPythonWrapper(): main successfully imported.
20240222 10:53:27.515 TRACE:: AlgorithmPythonWrapper(): Creating IAlgorithm instance.
20240222 10:53:27.670 TRACE:: Config.GetValue(): mute-python-library-logging - Using default value: True
20240222 10:53:27.672 TRACE:: LocalObjectStore.Initialize(): Storage Root: /Storage. StorageFileCount 9999999. StorageLimit 10240MB
20240222 10:53:27.673 TRACE:: LiveTradingDataFeed.GetDataChannelProvider(): will use DataChannelProvider
20240222 10:53:27.674 TRACE:: BrokerageSetupHandler.CreateBrokerage(): creating brokerage 'InteractiveBrokersBrokerage'
20240222 10:53:27.680 TRACE:: Config.GetValue(): ib-response-timeout - Using default value: 300
20240222 10:53:27.680 TRACE:: Config.GetValue(): ib-no-submission-orders-response-timeout - Using default value: 10
20240222 10:53:27.681 TRACE:: Config.GetValue(): ib-combo-order-fill-timeout - Using default value: 30
20240222 10:53:27.705 ERROR:: Engine.Run():  System.MissingMethodException: Method not found: 'Int32 QuantConnect.Globals.get_UserId()'.
   at QuantConnect.Brokerages.InteractiveBrokers.InteractiveBrokersBrokerage.b()
   at QuantConnect.Brokerages.InteractiveBrokers.InteractiveBrokersBrokerage.a(IAlgorithm A_0, IOrderProvider A_1, ISecurityProvider A_2, IDataAggregator A_3, IMapFileProvider A_4, String A_5, String A_6, Int32 A_7, String A_8, String A_9, String A_10, String A_11, String A_12, String A_13, Boolean A_14, Nullable`1 A_15)
   at QuantConnect.Brokerages.InteractiveBrokers.InteractiveBrokersBrokerage..ctor(IAlgorithm algorithm, IOrderProvider orderProvider, ISecurityProvider securityProvider, IDataAggregator aggregator, IMapFileProvider mapFileProvider, String account, String host, Int32 port, String ibDirectory, String ibVersion, String userName, String password, String tradingMode, String agentDescription, Boolean loadExistingHoldings, Nullable`1 weeklyRestartUtcTime)
   at QuantConnect.Brokerages.InteractiveBrokers.InteractiveBrokersBrokerageFactory.CreateBrokerage(LiveNodePacket job, IAlgorithm algorithm)
   at QuantConnect.Lean.Engine.Setup.BrokerageSetupHandler.CreateBrokerage(AlgorithmNodePacket algorithmNodePacket, IAlgorithm uninitializedAlgorithm, IBrokerageFactory& factory) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/Setup/BrokerageSetupHandler.cs:line 136
   at QuantConnect.Lean.Engine.Engine.Run(AlgorithmNodePacket job, AlgorithmManager manager, String assemblyPath, WorkerThread workerThread) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/Engine.cs:line 133
20240222 10:53:27.706 TRACE:: JOB HANDLERS:
         DataFeed:             QuantConnect.Lean.Engine.DataFeeds.LiveTradingDataFeed
         Setup:                QuantConnect.Lean.Engine.Setup.BrokerageSetupHandler
         RealTime:             QuantConnect.Lean.Engine.RealTime.LiveTradingRealTimeHandler
         Results:              QuantConnect.Lean.Engine.Results.LiveTradingResultHandler
         Transactions:         QuantConnect.Lean.Engine.TransactionHandlers.BrokerageTransactionHandler
         Object Store:         QuantConnect.Lean.Engine.Storage.LocalObjectStore
         History Provider:
         Brokerage:
         Data Provider:        QuantConnect.Lean.Engine.DataFeeds.DefaultDataProvider

20240222 10:53:27.708 ERROR:: Algorithm.Initialize() Error: Method not found: 'Int32 QuantConnect.Globals.get_UserId()'. Stack Trace: Method not found: 'Int32 QuantConnect.Globals.get_UserId()'.
 Method not found: 'Int32 QuantConnect.Globals.get_UserId()'.
20240222 10:53:27.709 TRACE:: LiveTradingResultHandler.Run(): Ending Thread...
20240222 10:53:27.711 TRACE:: StopSafely(): Waiting for 'Result Thread' thread to stop...
20240222 10:53:27.713 TRACE:: LiveTradingResultHandler.SendFinalResult(): Starting...
20240222 10:53:27.755 TRACE:: LiveTradingResultHandler.SendFinalResult(): Finished storing results. Start sending...
20240222 10:53:27.755 TRACE:: LiveTradingResultHandler.SendFinalResult(): Ended
20240222 10:53:27.755 TRACE:: Engine.Run(): Disposing of setup handler...
20240222 10:53:27.756 TRACE:: BrokerageSetupHandler.Setup(): did not find any data queue handler to dispose
20240222 10:53:27.756 TRACE:: Engine.Main(): Analysis Completed and Results Posted.
Engine.Main(): Analysis Complete.
20240222 10:53:27.757 TRACE:: Engine.Main(): Packet removed from queue: L-3849070657
20240222 10:53:27.757 TRACE:: LeanEngineSystemHandlers.Dispose(): start...
20240222 10:53:27.758 TRACE:: LeanEngineSystemHandlers.Dispose(): Disposed of system handlers.
20240222 10:53:27.758 TRACE:: LeanEngineAlgorithmHandlers.Dispose(): start...
20240222 10:53:27.758 TRACE:: BrokerageSetupHandler.Setup(): did not find any data queue handler to dispose
20240222 10:53:27.760 TRACE:: LeanEngineAlgorithmHandlers.Dispose(): Disposed of algorithm handlers.
20240222 10:53:27.761 TRACE:: StopSafely(): Waiting for 'CpuPerformance' thread to stop...
20240222 10:53:27.761 TRACE:: PythonInitializer.Shutdown(): start
20240222 10:53:30.891 TRACE:: PythonInitializer.Shutdown(): ended
20240222 10:53:30.891 TRACE:: Program.Main(): Exiting Lean...
Error: Something went wrong while running 'trader' in the 'lean-cli' environment, the output is stored in 'trader\live\2024-02-22_11-53-13'

**Comment by Martin-Molinero** [comment]
Hey @demo055! Please pull the latest lean image `docker pull quantconnect/lean`

**Comment by demo055** [comment]
> Hey @demo055! Please pull the latest lean image `docker pull quantconnect/lean`

Thank you very much. Solved. Why I thought, that LEAN is updating itself automatically?

**Comment by Martin-Molinero** [comment]
> > Hey @demo055! Please pull the latest lean image `docker pull quantconnect/lean`
> 
> Thank you very much. Solved. Why I thought, that LEAN is updating itself automatically?

Glad it worked! Yes, it checks for updates once every day I believe, not every time so it doesn't affect performance
