### ISSUE TITLE
Brokerage error 'Method not found: 'Int32 QuantConnect.Globals.get_UserId()' refrains bot from starting up

### ISSUE THREAD

**Issue by symbion6** [QuantConnect/Lean#7813]
#### Expected Behavior
Lean Engine starts up correctly, like it has done for me in the past 9 months.

#### Actual Behavior
Lean Engine fails to start and instead crashes with this error:
```

Algorithm.Initialize() Error: Method not found: 'Int32 QuantConnect.Globals.get_UserId()'. Stack Trace: System.MissingMethodException: Method not found: 'Int32 QuantConnect.Globals.get_UserId()'.
   at QuantConnect.BybitBrokerage.BybitBrokerage.d()
```
   
This is happening for both BybitBrokerage and KrakenBrokerage.
It's happening on my VM and on my local environment.
And it's happening even before my algorithm is loaded, so it has nothing to do with that.

It has been running for months without problems and - without changing ANYTHING - it suddenly started producing this error. Seems like an error in the brokerage package(s).

So my bot is not working anymore, at all and that could potentially be very costly.

#### Potential Solution
Make it work again.

#### Reproducing the Problem
Not sure how / if someone else can reproduce it; I can reproduce it on every attempt to start the bot. And the way I start the bot or the contents of my configs has stayed 100% the same compared to when it worked before.

#### System Information
MacOS
I have a QuantConnect Researcher account.

#### Checklist
- [V] I have completely filled out this template
- [V] I have confirmed that this issue exists on the current `master` branch --> USING LATEST LEAN CONTAINER, UPGRADED IT USING 'lean live --upgrade' TO BE SURE 
- [V] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [See above] I have provided detailed steps to reproduce the issue

#### Log:
[log.txt](https://github.com/QuantConnect/Lean/files/14379091/log.txt)

**Comment by Martin-Molinero** [comment]
Hey @symbion6! Sorry about that, please pull the latest lean image `docker pull quantconnect/lean`
