### ISSUE TITLE
Yahoo data downloader failing

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#7834]
#### Expected Behavior

- CI not failing, data sources extracted
#### Actual Behavior

See https://github.com/QuantConnect/Lean/pull/7833
#### Potential Solution

- We should extract yahoo into it's own data source and fix it
#### Reproducing the Problem

N/A
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Recommend we just remove this as they change their API constantly. Data has become very affordable now I don't think we should recommend risking quality/stability for free data.
