### ISSUE TITLE
Parquet Error When Accessing Fundamentals

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#7891]
#### Expected Behavior

This algorithm runs without error
```
class HipsterFluorescentPinkBaboon(QCAlgorithm):

    def Initialize(self):
        self.SetStartDate(2019, 1, 1)
        self.SetEndDate(2019, 2, 1)
        self.SetCash(100000)
        self.AddUniverse(self.select_symbols)

    def select_symbols(self, fundamental):
        for f in fundamental:
            f.ValuationRatios.SustainableGrowthRate
        return []
```

#### Actual Behavior

```
Runtime Error: N7parquet38ParquetInvalidOrCorruptedFileExceptionE (message: 'Invalid: Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.')
  at select_symbols
    f.ValuationRatios.SustainableGrowthRate
 in main.py: line 14 (Open Stack Trace)
```

#### Potential Solution

N/A

#### Reproducing the Problem

Run algo above

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Thank you for the report, the issue has been fixed
