### ISSUE TITLE
Absence of fundamental data in Many tickers in backtest

### ISSUE THREAD

**Issue by ashutoshrana171** [QuantConnect/Lean#7892]
#### Expected Behavior
In backtest the algorithm should give correct fundamental values.

#### Actual Behavior
For a lot of securities in backtest the algorithm does not give fundamental values.
One example: the ticker "AFTY" gives correct fundamental data during Live but not in the backtest. The fundamental values are either 0 or nan during the backtest. This creates discrepancy in universe selection in backtest and live.

1) Backtest mode values:
<img width="816" alt="image" src="https://github.com/QuantConnect/Lean/assets/62750665/1b96f47b-8bbd-45fd-9c1e-525313d0d74f">

2) Live mode values:
<img width="673" alt="image" src="https://github.com/QuantConnect/Lean/assets/62750665/afc4d690-cb92-4a5b-b7a8-3eafc69a0ab1">

3) We can access correct data in research environment by calling History method:
<img width="326" alt="image" src="https://github.com/QuantConnect/Lean/assets/62750665/893629e0-e7d7-4ffc-ba57-79aafe993e94">

#### Reproducing the Problem
We can run this code in backtest and live mode to check for the bug.
```
# region imports
from AlgorithmImports import *
# endregion

class SmallCapsScreener(QCAlgorithm):
    def Initialize(self):
        self.SetCash(10000)
        self.SetStartDate(2024,3,1)
        self.UniverseSettings.Resolution = Resolution.Daily
        self.AddUniverse(self.FundamentalFilterFunction)
        self.SetWarmup(20)

    def FundamentalFilterFunction(self, fundamental: List[Fundamental]) -> List[Symbol]:
        selected = [x for x in fundamental if x.Symbol.Value == "AFTY"]
        self.Log(f" { [x.Symbol.Value for x in selected]} | MarketCap: {[x.MarketCap for x in selected]} | DollarVolume {[x.DollarVolume for x in selected]} | Price: {[x.Price for x in selected]} | Time: {self.Time}")
        return []
```

#### System Information
QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Thank you for the report, the issue has been fixed starting from lean engine version `16336`.
To clarify, `AFTY` does not have fundamental data but just coarse data set, that's why market cap is 0, expected, dollar volume/price are available 👍. 

> does not have fundamental data

The boolean `HasFundamentalData` can be used to determine this.
