### ISSUE TITLE
Change Sell Method to check for negative amounts

### ISSUE THREAD

**Issue by bizcad** [QuantConnect/Lean#79]
The Sell methods all call the Order method, which in turn call the MarketOrder method.  The MarketOrder method creates a new MarketOrder type which derives from the Order type.  If the Quantity property is > 0 the OrderDirection is set to Buy and if the Quantity < 0, the OrderDirection is set to Sell.  

So in an algo, when I called Sell(_symbol, 100m), QuantConnect executed a Market buy order.  This method name seems counter intuitive to me.  When an algorithm writer calls the Sell method, (s)he would expect the algo to try and sell the security.  

I believe the 4 Sell methods should check the sign of the quantity and convert it to negative, so that the method will always try to execute a Sell.  The logic should be
<pre>
        public int Sell(string symbol, decimal quantity)
        {
            var qty = quantity;
            if (quantity > 0)
            { 
                 qty = qty * -1;
            }
            return Order(symbol, qty);
        }
</pre>

If all agree, I would be happy to make this change and will do a fork, pull for the issue.

**Comment by jaredbroad** [comment]
Thanks @bizcad, good suggestion, please issue a pull request with the fix. You might want to use Math.Abs instead to reduce if branching :)
