### ISSUE TITLE
Deadlock in algorithm when using a custom security initializer

### ISSUE THREAD

**Issue by yuriyarabskyyPro** [QuantConnect/Lean#7925]
#### Actual Behavior

I was running constantly into a deadlock situation in which the algorithm just randomly stops running and hangs. And I managed to pinpoint it to the exact lines in the code.

#### Reproducing the Problem

1. Use a custom security initializer like this:

<img width="388" alt="Screenshot 2024-04-16 at 13 48 44" src="https://github.com/QuantConnect/Lean/assets/111812399/309f2bc2-98e6-4b1a-84e4-dfa0ebb0d84d">

2. In your algorithm code access for instance the TotalPortfolioValue.

And now here is how it comes to a deadlock between the `ResultThread` and `IsolatorThread`:

**ResultThread**

For some reason even though the fee model is one of the predefined classes implemented in c#, it still goes through the `PythonWrapper` when calculating the fees and because of that it acquires the `Python.GIL()` mutex. The result thread updates the trade statistics and at some point requires the `_totalPortfolioValueLock`.

<img width="918" alt="Screenshot 2024-04-16 at 12 47 32" src="https://github.com/QuantConnect/Lean/assets/111812399/d8a05e06-eb47-479f-a1ea-6016474a7946">

**IsolatorThread**

The `IsolatorThread` runs the algorithm code and if you access at some point `TotalPortfolioValue` or any other statistic, then it also needs the `_totalPortfolioValueLock`. And when the python code is called, it is of course also wrapped in the `Python.GIL()` lock.

<img width="1218" alt="Screenshot 2024-04-16 at 12 46 23" src="https://github.com/QuantConnect/Lean/assets/111812399/ad5b8852-6b34-47d2-8a14-998539bb7c6d">

This leads to a deadlock. And I don't know what is the best way to solve this. Maybe you have some thoughts.
Here is also the call stack when the deadlock happens:

<img width="999" alt="Screenshot 2024-04-16 at 13 52 11" src="https://github.com/QuantConnect/Lean/assets/111812399/10433d5f-898d-40ad-8494-78603734c016">

#### System Information

I think it's independent from the system, but I'm running it on Ubuntu 22.04.2. And I've made sure to pull the latest `master` branch version.

#### Potential solution

If the fee model wouldn't go through the `PythonWrapper`, there wouldn't be a deadlock. This would work for cases in which the fee model is actually not in python, but for python custom fee model initializers this would need to be fixed differently.

Another solution would be to not include fees in the `UnrealizedProfit` calculation, which would then remove the dependency on any custom python code execution in the `ResultThread` as far as I understand.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Thank you for the detail report @yuriyarabskyyPro! We will look into it 👍
