### ISSUE TITLE
Portfolio/Securities Missing Symbols On Contract Rollovers

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#7997]
#### Expected Behavior

When a futures contract rollover occurs, the old symbol is in `portfolio` and the new symbol is in `securities`.

#### Actual Behavior

Sometimes the old symbol isn't in `portfolio` and sometimes the new symbol isn't in `securities`

#### Potential Solution

N/A

#### Reproducing the Problem

https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_0d751a800d550e01fdb48e193cd90ace.html

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
This issue has the same nature of https://github.com/QuantConnect/Lean/issues/7868

**Comment by jhonabreul** [comment]
Re-opening it since not 100% the same as #7868
