### ISSUE TITLE
Duplicate "Energies" Futures Ticker Shortcut to Energy

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#8009]
#### Expected Behavior
Energy isn't countable should not use plural in shortcut.
Futures.Energy.BRENT_CRUDE, 

#### Actual Behavior
Futures.Energies.BRENT_CRUDE, 

Duplicate the energy shortcuts to make it backward compatible.

#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Reopening after reverting associated PR which was breaking pep8 support, see issue https://github.com/QuantConnect/Lean/issues/8080 . 
`self.add_future(Futures.Energy.BRENT_CRUDE)` use case should continue to work, should add unit test asserting this
