### ISSUE TITLE
C# iterator methods are not executed but do compile without errors

### ISSUE THREAD

**Issue by slorion** [QuantConnect/Lean#8019]
#### Expected Behavior

Using C# iterator methods (`yield return`) should work per the language specification.

#### Actual Behavior

There is no compilation error when there is an iterator method, but the method is apparently not executed at runtime and breakpoints are not hit when debugging. In my project for example, open orders are canceled with the first version, but not with the second.

```
private void CancelOpenLimitOrders()
{
    var openOrderTickets = this.Portfolio.Transactions.GetOpenOrderTickets(t => t.OrderType == OrderType.Limit);
    foreach (OrderTicket orderTicket in openOrderTickets) {
        orderTicket.Cancel(tag: $"{orderTicket.Get<decimal>(OrderField.LimitPrice):F4}");
    }
}
```

```
private IEnumerable<OrderTicket> CancelOpenLimitOrders() 
{
	var openOrderTickets = this.Portfolio.Transactions.GetOpenOrderTickets(t => t.OrderType == OrderType.Limit);
	foreach (OrderTicket orderTicket in openOrderTickets) {
		orderTicket.Cancel(tag: $"{orderTicket.Get<decimal>(OrderField.LimitPrice):F4}");
		yield return orderTicket;
	}
}
```

#### Reproducing the Problem

See above example. From my limited testing, any iterator method present in the `QCAlgorithm` class is not executed.

#### System Information

Tested with VS Code online.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @slorion! Believe this might be a misunderstanding on how IEnumerables work, they need to be enumerated to be executed, try `CancelOpenLimitOrders.ToList()` or `.ToArray()` adding `using System.Linq;`

**Comment by slorion** [comment]
Oh that's right! I forgot about that. Thank you 👍
