### ISSUE TITLE
Option Strategy Margin Error

### ISSUE THREAD

**Issue by LouisSzeto** [QuantConnect/Lean#8032]
#### Expected Behavior
Option Strategy Margin follows [CBOE](https://www.cboe.com/us/options/strategy_based_margin/) & [IB](https://www.interactivebrokers.com.hk/en/trading/margin-options.php) requirements.

#### Actual Behavior
Buying Power Model of the following `OptionStrategies` is not:
- `NakedCall`, `NakedPut`: 
  - short: 
    - Stock Options: Call/Put Price + Maximum ((20% * Underlying Price - Out of the Money Amount), (10% * Underlying Price))
    - Index Options: Call/Put Price + Maximum ((15% * Underlying Price - Out of the Money Amount), (10% * Underlying Price))
  - long: 0
- `ShortCallCalendarSpread`, `ShortPutCalendarSpread`:
  - 0

#### Potential Solution
Amend `OptionStrategyPositionGroupBuyingPowerModel` for corresponding strategies

#### Reproducing the Problem
Refer to `OptionStrategyPositionGroupBuyingPowerModel`

#### System Information
NA

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Current strategies margin were defined & tested against IB actual margin requirements, some are an approximation with some expected small degree of error.
Please share a specific case that the error is off significantly for these strategies so we can fix and test against it
