### ISSUE TITLE
Improve Conversion Error Message for Python

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#8042]
#### Expected Behavior
The error message informs the developer why the conversion failed and the expected type.

#### Actual Behavior
If a method returns an unexpected type, the error message is not very helpful.

#### Potential Solution
N/A

#### Reproducing the Problem
```python
class AdaptableSkyBlueHornet(QCAlgorithm):
    def initialize(self):
        self.add_equity("SPY")
        self.add_alpha(MyAlpha())

class MyAlpha(AlphaModel):
    def update(self, _, slice):
        return
```
The error message is `Runtime Error: 'NoneType' object is not iterable`
The problem is that alpha should return a list (iterable) of Insight. Calling `return` without an object in Python is the same as `return None`.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
The first issue to fix is a better stack trace for debugging all future versions of this error.

**Comment by Martin-Molinero** [comment]
We can continue to spread out the usage of our BasePythonWrapper helper class, this class can catch failures on properties/method/etc calls adding in more information of what is expected where did the issue happen. He can detect if the failure is while running python code or, like in the case of this issue, while converting the output returned to the expected type

<img width="365" alt="image" src="https://github.com/QuantConnect/Lean/assets/18473240/20a6bda8-c239-4758-9679-793bc6997b74">
