### ISSUE TITLE
Chronos: Learning the Language of Time Series

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#8065]
See https://github.com/amazon-science/chronos-forecasting

**Comment by Martin-Molinero** [comment]
> At this time this codebase is intended only for research / reproducibility purposes. Chronos will be actively maintained and developed within [AutoGluon-TimeSeries](https://github.com/autogluon/autogluon), already in progress here: https://github.com/autogluon/autogluon/pull/3978
 
 See https://github.com/amazon-science/chronos-forecasting/issues/10, this has be completed and autogluon already supports chronos

**Comment by rasmus-oejvind** [comment]
Confused. Does QC support the autogluon library?

**Comment by Martin-Molinero** [comment]
Hey @rasmus-oejvind! `autogluon` library is planned to soon be supported in the cloud as a virtual env on top of the default env, due to it's special dependency requirements
