### ISSUE TITLE
symbol_properties.minimum_price_variation incorrect for Australian Dollar Futures (6A) Futures

### ISSUE THREAD

**Issue by neovicent** [QuantConnect/Lean#8104]
#### Expected Behavior

Future: Australian Dollar Futures
Exchange Ticker:  6A
Minimum Price Variation: 0.00005

References:
[https://www.cmegroup.com/markets/fx/g10/australian-dollar.contractSpecs.html](url)

#### Actual Behavior

Future: Australian Dollar Futures
Exchange Ticker:  6A
Minimum Price Variation: 0.0001

Minimum price variation is incorrect for Australian Dollar Futures (6A)
#### Potential Solution

Adjust the corresponding values in [symbol properties database](https://github.com/QuantConnect/Lean/blob/master/Data/symbol-properties/symbol-properties-database.csv) (line 226).

#### Reproducing the Problem

qb = QuantBook()
print(qb.AddFuture("6A").SymbolProperties.MinimumPriceVariation))

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by keshavdalmia10** [comment]
Hi @Martin-Molinero , I would like to work on this.
