### ISSUE TITLE
cvxpy library error log

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#8109]
#### Expected Behavior

We can `import cvxpy` in the research environment without error.

#### Actual Behavior

> CVXPY) Jun 26 02:46:45 PM: Encountered unexpected exception importing solver GLOP:
RuntimeError('Unrecognized new version of ortools (9.9.3963). Expected < 9.8.0. Please open a feature request on cvxpy to enable support for this version.')

#### Potential Solution

N/A

#### Reproducing the Problem

Run `import cvxpy` in the research env

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
We can see these 2 logs, not the library is still functional 
```
(CVXPY) Jun 26 04:29:24 PM: Encountered unexpected exception importing solver GLOP:
RuntimeError('Unrecognized new version of ortools (9.9.3963). Expected < 9.8.0. Please open a feature request on cvxpy to enable support for this version.')
(CVXPY) Jun 26 04:29:24 PM: Encountered unexpected exception importing solver PDLP:
RuntimeError('Unrecognized new version of ortools (9.9.3963). Expected < 9.8.0. Please open a feature request on cvxpy to enable support for this version.')
```
