### ISSUE TITLE
Implement Zero Lag Exponential Moving Average

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#8118]
#### Expected Behavior
Supports Zero Lag Exponential Moving Average (see [talipp implementation](https://github.com/nardew/talipp/blob/main/talipp/indicators/ZLEMA.py))

Refer to [LEAN Engine > Contributions > Indicators](https://www.quantconnect.com/docs/v2/lean-engine/contributions/indicators).

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by femtotrader** [comment]
Hi @AlexCatarino 

I'm trying to implement ZLEMA but I'm locked with one problem

I need to convert

https://github.com/nardew/talipp/blob/a19ded8af6694ec167656cf757a0879ce7f41db9/talipp/indicators/ZLEMA.py#L43

to C#

I did

https://github.com/QuantConnect/Lean/pull/8138/files#diff-edf47006da5bce0ac9f2b4e4587a8675871e16db96e286514940976a9eeb4fd2R79

but I don't know how I can get historical input values ie input values at "end - lag"

Kind regards
