### ISSUE TITLE
Implements Vortex Indicator

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#8132]
#### Expected Behavior
Supports Vortex Indicator (see [talipp implementation](https://github.com/nardew/talipp/blob/main/talipp/indicators/VTX.py)).

Refer to [LEAN Engine > Contributions > Indicators](https://www.quantconnect.com/docs/v2/lean-engine/contributions/indicators).

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by keshavdalmia10** [comment]
Hi, I would like to work on this.

**Comment by keshavdalmia10** [comment]
Hi, @AlexCatarino, @Martin-Molinero almost done. Have a few doubts

**Comment by keshavdalmia10** [comment]
Hi, @AlexCatarino , @Martin-Molinero i have raised the PR. If any changes required please tell.
