### ISSUE TITLE
Library Request: Kats

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#8133]
[Kats](https://github.com/facebookresearch/Kats) is a toolkit to analyze time series data, a lightweight, easy-to-use, and generalizable framework to perform time series analysis. Time series analysis is an essential component of Data Science and Engineering work at industry, from understanding the key statistics and characteristics, detecting regressions and anomalies, to forecasting future trends. Kats aims to provide the one-stop shop for time series analysis, including detection, forecasting, feature extraction/embedding, multivariate analysis, etc.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Requires pandas < 2 https://github.com/facebookresearch/Kats/blob/main/requirements.txt. Seems to have multiple install issue too, was develop with py 3.8/3.9 target
