### ISSUE TITLE
Exit due to missing 'get_BrokerageData()' method when using Kraken brokerage

### ISSUE THREAD

**Issue by symbion6** [QuantConnect/Lean#8142]
#### Expected Behavior
Lean Engine starts normally, using Kraken brokerage.

#### Actual Behavior
During startup, Lean Engine stumbles upon the following error and exits:

> 2024-07-04T13:03:54.7382832Z ERROR:: Engine.Run():  System.MissingMethodException: Method not found: 'System.Collections.Generic.Dictionary`2<System.String,System.String> QuantConnect.Packets.LiveNodePacket.get_BrokerageData()'.
>    at QuantConnect.Brokerages.Kraken.KrakenBrokerageFactory.CreateBrokerage(LiveNodePacket job, IAlgorithm algorithm)
>    at QuantConnect.Lean.Engine.Setup.BrokerageSetupHandler.CreateBrokerage(AlgorithmNodePacket algorithmNodePacket, IAlgorithm uninitializedAlgorithm, IBrokerageFactory& factory) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/Setup/BrokerageSetupHandler.cs:line 134
>    at QuantConnect.Lean.Engine.Engine.Run(AlgorithmNodePacket job, AlgorithmManager manager, String assemblyPath, WorkerThread workerThread) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/Engine.cs:line 133

#### Reproducing the Problem
Start Lean Engine with Kraken as Brokerage

#### System Information
Ubuntu Server LTS 

#### Checklist
- [V] I have completely filled out this template
- [V] I have confirmed that this issue exists on the current `master` branch
- [V] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [V] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @symbion6! Sorry for the inconvenience, believe just pulling the latest lean image will solve this issue 👍  `docker pull quantconnect/lean`
