### ISSUE TITLE
Library Request: alpaca-py

### ISSUE THREAD

**Issue by ganeshvenepally** [QuantConnect/Lean#8166]
alpaca-py is required for me replicate trades from my alpaca account to IBKR from quantconnect.

Checklist:

I have completely filled out this template
I have confirmed that this issue exists on the current master branch
I have confirmed that this is not a duplicate issue by searching issues
I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment]
Hi @ganeshvenepally ,
QuantConnect doesn't allow REST API POST calls to third parties.

We are working on supporting Alpaca: 
https://github.com/QuantConnect/Lean.Brokerages.Alpaca
