### ISSUE TITLE
Library Request: Cbc

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#8202]
[Cbc (Coin-or branch and cut)](https://github.com/coin-or/Cbc) is an open-source mixed integer linear programming solver written in C++. It can be used as a callable library or using a stand-alone executable. It can be used in a wide variety of ways through various modeling systems, packages, etc.

[pyomo](https://github.com/QuantConnect/Lean/issues/6980) uses this solver

```python
from pyomo.contrib import appsi
self.log(appsi.solvers.Cbc().available())
```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by eemelipa** [comment]
When can this be made available?

Currently there is no solver available on the platform so Pyomo cannot be used at all.

I'm happy to provide further information or help if needed. The cbc solver is available in many linux package installers so that shouldn't be a blocker

**Comment by Martin-Molinero** [comment]
Hey @eemelipa! We are currently working on a new lean foundation atm, will be released soon! You can subscribe to this issue for updates
