### ISSUE TITLE
Unable to connect to Binance Spot Testnet

### ISSUE THREAD

**Issue by jimmychu0807** [QuantConnect/Lean#8206]
#### Expected Behavior
After getting an API Key and Secret from [Binance Spot Testnet](https://testnet.binance.vision/), I am able to connect to Binance Spot Testnet

#### Actual Behavior
When deploying to live in the following dialog box:

<img width="592" alt="Screenshot 2024-07-17 at 19 09 25" src="https://github.com/user-attachments/assets/ba5db03b-761e-4fcd-82f9-10c171e2eb18">

If I choose **Demo** in the Environment setting, I get the following error:

<img width="521" alt="Screenshot 2024-07-17 at 19 12 00" src="https://github.com/user-attachments/assets/af0a2d15-f7f7-4250-adda-85f89fb72d71">

If I choose **Real** in the Environment setting, then I get the following:

<img width="521" alt="Screenshot 2024-07-17 at 19 19 06" src="https://github.com/user-attachments/assets/02cc1fbe-7ab5-4063-a28e-f51fb8f5f12d">

#### Potential Solution
Need to check the Binance integration

#### Reproducing the Problem
Duplicate the steps above

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @jimmychu0807! Just testing this and can't reproduce the issue ur experiencing locally or in QC cloud, it might of been some down time from binance spot testnet, please re test 👍. If u still experience the issue please contact QC cloud support.
