### ISSUE TITLE
Set Error function as virtual so that custom log location can be used

### ISSUE THREAD

**Issue by superichmann** [QuantConnect/Lean#8230]
#### Expected Behavior
Error function can be overridden by the user so that logs could be sent to a database.

#### Actual Behavior
`cannot override inherited member 'QCAlgorithm.Error(Exception)' because it is not marked virtual, abstract, or override`	error

#### Potential Solution
Set `Error` as `public virtual`

#### Reproducing the Problem
add this code into an algorithm
```
  public override void Error(Exception error)
  {
    base.Error(error);
  }
```
build, see error
#### System Information
windows 10

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @superichmann! Seems like a custom result handler might do the trick generically
