### ISSUE TITLE
Library Request: vectorbt

### ISSUE THREAD

**Issue by ASRagab** [QuantConnect/Lean#8234]
[vectorbt](https://vectorbt.dev/) It's a performant vectorized backtesting framework, useful for running backtests from the research environment, where you want to quickly validate hypotheses prior to the LEAN platform. 

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
Sorry not planned. I'd prefer to put efforts into making our own vectorized backtest support.
