### ISSUE TITLE
Visual Studio for Mac is retiring Aug 31 2024

### ISSUE THREAD

**Issue by kevinwheeler** [QuantConnect/Lean#8237]
[The installation instructions for MacOS users](https://github.com/QuantConnect/Lean?tab=readme-ov-file#macos) uses Visual Studio. Visual Studio for mac is going away soon, however.

**Comment by keshavdalmia10** [comment]
Hi @kevinwheeler, the installation instructions of visual studio code are given in the Readme. Even I use vscode in my mac.

**Comment by kevinwheeler** [comment]
Hey @keshavdalmia10! The only vs code instructions I see are in a link to a different page off of the main readme. IE the main readme says:

This section will cover how to install lean locally for you to use in your environment. Refer to the following readme files for a detailed guide regarding using your local IDE with Lean:

[VS Code](https://github.com/QuantConnect/Lean/blob/master/.vscode/readme.md)
[VS](https://github.com/QuantConnect/Lean/blob/master/.vs/readme.md)

Anyhow, the MacOS section of the main readme should probably just contain a link to the vs code instructions. Or the MacOS section of the readme should be deleted. Right now it just serves as a distraction and leads in the wrong direction. Or at the very least the MacOS section could say that using visual studio is a legacy option and recommend the reader goes to the vs code instructions.

**Comment by bug-or-feature** [comment]
I can pick this up. I'm a new user/contributor, and a Mac user
