### ISSUE TITLE
CalculateOrderQuantity doesn't work well with Futures

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#8240]
#### Expected Behavior

`self.calculate_order_quantity(self._future.mapped, 1)` returns a quantity that will lead to 100% exposure.

#### Actual Behavior

`self.calculate_order_quantity(self._future.mapped, 1)` returns a quantity that leads to 5000% exposure!

To get 100% exposure, I need to manually calculate it with
```
quantity = int(
    self.portfolio.total_portfolio_value 
    / data[self._future.mapped].price 
    / self._future.symbol_properties.contract_multiplier
)  
```

#### Potential Solution

N/A

#### Reproducing the Problem

https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_f232637a48b2d905bf2052ea076699a5.html

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Marinovsky** [comment]
Hey @DerekMelchin !

It seems that the method `CalculateOrderQuantity()` is actually returning the expected value. I used the algorithm you sent and placed a market order with the quantity obtained from `calculate_order_quantity(future, 1)`. After the order was filled, this was the margin used and the total portfolio value:
![image](https://github.com/user-attachments/assets/a13fd374-b07b-4713-91df-063219933392)

`CalculateOrderQuantity()` is returning the order quantity to achieve the target, taking into account the margin. Meanwhile, exposure depends on the holdings value which is different from the margin:
![image](https://github.com/user-attachments/assets/cc880593-8698-4d30-8abb-f4a052aa10fa)
