### ISSUE TITLE
Pass absoute_holdings_value instead of absolute_holdings_cost

### ISSUE THREAD

**Issue by mopoku** [QuantConnect/Lean#8292]
https://github.com/QuantConnect/Lean/blame/eeeb310438db37c62eb019c2997fbd4159bcf5d6/Algorithm.Framework/Risk/TrailingStopRiskManagementModel.py#L48

I think it was meant to pass absoute_holdings_value instead of absolute_holdings_cost to the HoldingState constructor.

**Comment by Martin-Molinero** [comment]
Hey @mopoku! Mind clarifying why do u think so? Both C# and python implementations are using cost, seems intended. Is the model not working as expected? please share details of any issue if any and how to reproduce, so we can solve it asap
