### ISSUE TITLE
RogersSatchellVolatility and rsv are unavailable using Python

### ISSUE THREAD

**Issue by femtotrader** [QuantConnect/Lean#8296]
#### Expected Behavior

RogersSatchellVolatility and self.rsv should be available using Python

#### Actual Behavior

RogersSatchellVolatility and self.rsv are unavailable using Python

See https://www.quantconnect.com/forum/discussion/17820/can-039-t-find-self-rsv-rogers-satchell-volatility-in-python/p1

#### Reproducing the Problem

Write a Python algorithm from default template.

Try to access self.zlema ... it's available
Try to access self.rsv it's not available

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

Related: #8144 #8183

**Comment by Martin-Molinero** [comment]
Hey @femtotrader!
It is available, just the [stubs](https://pypi.org/project/quantconnect-stubs/)/autocomplete were just out of date, a new version is now out though, will be available in the cloud shortly
