### ISSUE TITLE
Improve Error Messages When No Data Subscription

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#8299]
#### Expected Behavior
An informative error letting the user know no data set subscription and failing gracefully.

#### Actual Behavior
Fails with random error depending on dataset / data not found.
https://www.quantconnect.com/research/17886/copying-congress-trades/p1/comment-49680

#### Potential Solution
DataType.SubscriptionRequired =True
DataType.RootFolder = "../alt../ congress"
Static: If SubscriptionRequired  AND folder not found: throw "Dataset was not detected. Do you have an active subscription?"

Updating all the datasets to include the path and subscription requirement.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Marinovsky** [comment]
After comparing the json raw response for data prices with the `GetSource()` implementation of some data sources I found the following data types do not have an entry in the json response for data prices (Surprisingly, all of them are universes):
- QuiverQuantCongressUniverse
- QuiverWikipediaUniverse
- QuiverWallStreetBetsUniverse
- SmartInsiderIntentionUniverse
- SmartInsiderTransactionUniverse
- BrainSentimentIndicatorUniverse
- BrainStockRankingUniverse
- BrainCompanyFilingLanguageMetricsUniverse
- QuiverCNBCsUniverse 
- QuiverGovernmentContractUniverse
- QuiverLobbyingUniverse

Besides, I found that the entry for ExtractAlphaInnovationModel was off. Both the path and the regex are off:
![image](https://github.com/user-attachments/assets/6e60bc3c-6fca-4dba-90d5-fa4e4d799e97)
![image](https://github.com/user-attachments/assets/c2c21018-44bb-4895-b2d7-6db6f3f0ee8f)

**Comment by Martin-Molinero** [comment]
Solved by updating dataset specification

**Comment by cdiaz9719** [comment]
This is a valuable improvement. While working on my custom dataset integration (DailySentimentScore), I also ran into similar ambiguous “data not found” messages when testing local CSV feeds without active subscriptions.

Adding a clearer exception for missing dataset subscriptions — or even logging the expected path vs. actual lookup — would make debugging new dataset implementations much smoother.

Great suggestion, and I’d be happy to help test or validate messaging once it’s implemented.
