### ISSUE TITLE
[Feature] Alpha / Beta / R-Squared / Correlation / Covariance indicators

### ISSUE THREAD

**Issue by talaikis** [QuantConnect/Lean#83]
Rolling alpha/ beta indicators. Probably along with covariance and correlation. As part of flexible portfolio management ranks and relationships.

Alpha and beta are the most overlooked professional indicators in the so called popular "technical analysis".

**Comment by jaredbroad** [comment]
Continuation from https://github.com/QuantConnect/Lean/issues/84

**Comment by Martin-Molinero** [comment]
MAMA & FAMA WIP at https://github.com/QuantConnect/Lean/pull/2987

**Comment by jaredbroad** [comment]
- Closing as multiple issues in 1.
 - Will created dedicated issues with 1 for each indicator.
