### ISSUE TITLE
Cannot debug a boolean

### ISSUE THREAD

**Issue by ahmadsaadat** [QuantConnect/Lean#8305]
#### Expected Behavior

I would like to see booleans supported in debug logging.

#### Actual Behavior

When i run: 
`self.debug("------->" + self.portfolio.invested)`
I get this error: 
`20240908 01:00:33.242 ERROR:: Extensions.SetRuntimeError(): Extensions.SetRuntimeError(): RuntimeError at 10/07/2013 04:00:00 UTC. Context: OnData 
Python.Runtime.PythonException: can only concatenate str (not "bool") to str
  File "/LeanCLI/main.py", line 19, in on_data
    self.debug("------->" + self.portfolio.invested)`

#### Potential Solution
A potential hack for the developer is to override the debug method it in their subclass. 
However, it would be much more efficient if the library could handle this, this would help the developer write cleaner code.

#### System Information

2020 Mac Book Pro
macOS: 14.6.1

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by ArthurAsenheimer** [comment]
Hi @ahmadsaadat
The error message is actually quite clear here. You're trying to concatenate a string with a boolean which is not supported in Python. Just replace the line with 
```Python 
self.debug(f"------> {self.portfolio.invested}") 
```
That should fix it.

**Comment by Martin-Molinero** [comment]
Correct, this is the behavior of python itself, another potential solution is using `str()`
```
>>> a = "test"
>>> b = False
>>> a + b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can only concatenate str (not "bool") to str
>>> a + str(b)
'testFalse'
>>>
```
