### ISSUE TITLE
Operation took longer than 15 seconds.

### ISSUE THREAD

**Issue by investorlifelong** [QuantConnect/Lean#8307]
Start getting this error today:

Algorithm.Initialize() Error: InteractiveBrokersBrokerage.Connect(): Operation took longer than 15 seconds. Stack Trace: InteractiveBrokersBrokerage.Connect(): Operation took longer than 15 seconds.: StackTrace: InteractiveBrokersBrokerage.Connect(): Operation took longer than 15 seconds.

Please advise what was changed to limit to this defaut 15 seconds? how to specify the timeout greater than 15 seconds?

Thanks

**Comment by Martin-Molinero** [comment]
Hey @investorlifelong!
Sorry to hear your having issues, please share details on how to reproduce this issue here or with support. I just tested IB in quantconnect cloud and locally and it's working correctly using latest engine version.
