### ISSUE TITLE
Operation took longer than 15 seconds. 

### ISSUE THREAD

**Issue by investorlifelong** [QuantConnect/Lean#8308]
Don't just close the ticket.
Please let me know how to overwrite this 15 seconds which should be some default settings? I would need a longer time for initialization.

**Comment by Martin-Molinero** [comment]
Hey @investorlifelong! We've detected a faulty build and disabled it, please test using version `16616` the issue should be fixed, sorry for the inconvenience

**Comment by investorlifelong** [comment]
I am deploying on prod env. there is no version 16616 I can sepcify. are you saying, the production env is restored back to the good version?

**Comment by Martin-Molinero** [comment]
> I am deploying on prod env. there is no version 16616 I can sepcify. are you saying, the production env is restored back to the good version?

yes, correct
