### ISSUE TITLE
Library Request: scikit-garden

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#8314]
[Scikit-garden](https://scikit-garden.github.io/) or skgarden (pronounced as skarden) is a garden for scikit-learn compatible trees.

Test:

```python
from sklearn.datasets import load_boston
boston = load_boston()
X, y = boston.data, boston.target

### Use MondrianForests for variance estimation
from skgarden import MondrianForestRegressor
mfr = MondrianForestRegressor()
mfr.fit(X, y)
y_mean, y_std = mfr.predict(X, return_std=True)

### Use QuantileForests for quantile estimation
from skgarden import RandomForestQuantileRegressor
rfqr = RandomForestQuantileRegressor(random_state=0)
rfqr.fit(X, y)
y_mean = rfqr.predict(X)
y_median = rfqr.predict(X, 50)
```

Gives us:

> ImportError: 
`load_boston` has been removed from scikit-learn since version 1.2.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
`scikit-garden` does not seem to compile correctly (even using unreleased repo version) and does not seem to be maintained. Latest release is from 2017 ref https://pypi.org/project/scikit-garden/. Created issue https://github.com/scikit-garden/scikit-garden/issues/117
