### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by MinhTamNT** [QuantConnect/Lean#8325]
Today I just called the API from another get ticker in Vietnam, I also used the add_equity function notation and step-by-step instructions in the documentation. Why is on_data not working in my locality?  I use pycharm to run the Algorithm.
![image](https://github.com/user-attachments/assets/69e28c2a-3bec-4c21-84bf-ddefe9b91fc5)
![image](https://github.com/user-attachments/assets/cfa4eb91-137c-48bc-b652-e800360cc741)
![image](https://github.com/user-attachments/assets/7f260c8e-884b-4749-a1bf-f72d81f48a37)

- Python 3.12
- pycharm : lastes version

Thanks for reading

**Comment by Martin-Molinero** [comment]
Hey @MinhTamNT! The data probably isn't there, please review our documentation for details https://www.quantconnect.com/docs/v2/, locally you can use the lean cli to download the data preemptively or on the fly

**Comment by MinhTamNT** [comment]
> Hey @MinhTamNT! The data probably isn't there, please review our documentation for details https://www.quantconnect.com/docs/v2/, locally you can use the lean cli to download the data preemptively or on the fly

Hey, @Martin-Molinero !!!!!  So let me ask more carefully, if I am in the Vietnamese market, I want to call the API to get Vietnamese stocks so I can automatically trade in the Vietnamese market with Vietnamese stocks, does your side support it? I run your code in Python and use pycharm but when I run it, there are some things like the on-data function that don't work, you can see my picture above. Sorry, I have to ask. I'm a student, and I want to learn about it. Thank you for reading. Wishing you good health
