### ISSUE TITLE
A new Universe Selection Algorithm based on last weeks Momentum analysis

### ISSUE THREAD

**Issue by AnshulYADAV007** [QuantConnect/Lean#834]
Hello Everyone,

I want to design and implement an algorithm for Universe Selection. I would love to get some inputs from the community as to what should be the approach towards building such an algorithm. I am new to the world of finance and QuantConnect, thus any help will be profoundly appreciated.

Thanks

**Comment by jaredbroad** [comment]
Welcome @Anshul, this discussion is more appropriate in the QC forums. The open source issue list is more for reporting bugs and planning feature.

If you find a bug in the LEAN open source please let us know here. Other wise quantconnect.com/forum is a great place for algorithm and finance discussion.
