### ISSUE TITLE
Research Env Monthly Universe Selection

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#8353]
#### Expected Behavior

When we run universe selection with `date_rule==qb.date_rules.month_start()`, the filter function is called at the start of every month.

#### Actual Behavior

The filter function skips some months.

#### Potential Solution

N/A

#### Reproducing the Problem

This project shows the difference between backtesting and research
https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_554ea30c837d921ca7dacfdce4f84a77.html

![image](https://github.com/user-attachments/assets/640193d3-27df-401a-8747-7ac1f168fe4d)

![image](https://github.com/user-attachments/assets/c20cab2a-2ac7-497c-9a55-c107c3cf7bfa)

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
> date_rule==qb.date_rules.month_start()

I think probably this can be a weekend and does not match the actual data dates, have you tried with `qb.date_rules.month_start()` passing the symbol? so it takes into account market hours @DerekMelchin

**Comment by DerekMelchin** [comment]
It still skips some months
![image](https://github.com/user-attachments/assets/cde13adf-0626-430d-aaf5-fcfe772e8492)
