### ISSUE TITLE
Alpha indicator unneeded error

### ISSUE THREAD

**Issue by superichmann** [QuantConnect/Lean#8379]
`The target and reference symbols cannot be the same.` but actually they yes can be. 
This throws exception which if unhandled will crash the algorithm.
Maybe remove this error type since its not really an exception?

**Comment by Martin-Molinero** [comment]
Hey @superichmann! Please share how to reproduce the issue so we can take a closer look

**Comment by AlexCatarino** [comment]
Hi @superichmann ,
If the target and reference are the same, Beta is always 1, and Alpha is always 0, aren't they?

**Comment by AlexCatarino** [comment]
It's a reason to crash because it doesn't make sense to add an indicator with a known constant value.
If we don't throw an exception, the user will ask us, " Why is alpha always zero?" So we throw an exception to let them know.
