### ISSUE TITLE
Support TA-lib

### ISSUE THREAD

**Issue by gururise** [QuantConnect/Lean#84]
The TA-Lib library has over 200 technical indicators.  It is also open source and supports c# (I think): http://ta-lib.org/

Could this library be integrated to allow for more indicators and technical analysis?

**Comment by jaredbroad** [comment]
Thanks @gururise, TA Lib C# integration is definitely something we should implement! 

We liked how deeply we could integrate custom built indicators, and how extensible we could make them. By writing the indicator from the ground up we could also make them faster and implemented with online techniques. Perhaps rolling our TA Lib can come in a few steps:

1. Basic support for TA Lib through C# Library addition to project.
2. Wrappers around TA Lib functions which integrate some indicators into the Lean Engine's native system.

**Comment by jaredbroad** [comment]
Only remaining indicators are; some remaining because they require stock data from two input assets (pattern not supported by default indicator framework at the moment)
 - BETA
 - CORREL
 - HT
 - LINREG
 - MAMA 
 - FAMA
 - SAREXT
 - STOCHRSI
 - TSF

**Comment by mchandschuh** [comment]
You should be able to use multiple data sources using the composite
indicator. Have a look at the math extensions (such as Over() ).

**Comment by jaredbroad** [comment]
Bulk of TA completed; remaining indicators put in dedicated "multi-source" issue.
