### ISSUE TITLE
Inconsistent Multiple OnData Calling Order Between Strats

### ISSUE THREAD

**Issue by superichmann** [QuantConnect/Lean#8408]
#### Expected Behavior
Different strategies should call the OnData methods at the same order.

#### Actual Behavior
Different strategies call the OnData method with seemingly random order.

#### Potential Solution
I have no idea.

#### Reproducing the Problem
Create a C# strat with two custom data types (create their classes in separate files) in addition to daily TradeBar.
Create an OnData function to each of them (total:3)
Create another similiar strat (just a different file and name)
Log the order in which OnData functions are called.
See different ordering.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey!
Seems like some bug in the algorithms or the custom data, lean is expected to be deterministic if the input is so too. Hundreds of algos are run in CI every time including custom data. We can't debug this without more information/details on how to reproduce the issue in a simple way, suggest trying to to this first and the issue might go away I'd guess
