### ISSUE TITLE
Does it work on M1/M2 chips?

### ISSUE THREAD

**Issue by nadomani** [QuantConnect/Lean#8414]
Is docker working natively on Arm or with rosetta? (I want to connect with IB)

#### Checklist

- [ ] I have completely filled out this template
- [ ] I have confirmed that this issue exists on the current `master` branch
- [ ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @nadomani! for ARM we do not have support for IB at the moment, but believe x64 emulation might work using latest docker versions and chips. Ref https://www.quantconnect.com/docs/v2/lean-cli/live-trading/brokerages/interactive-brokers#02-Deploy-Local-Algorithms
