### ISSUE TITLE
Warning: fill at stale price. Binance Futures

### ISSUE THREAD

**Issue by o-nazaruk** [QuantConnect/Lean#8417]
#### Expected Behavior
Data for accurate fills must be present. 

#### Actual Behavior
Data is missing (please see screenshots), warning message appears. Attached cases are just a small selection of occurrences
<img width="910" alt="Screenshot 2024-11-18 at 11 19 23" src="https://github.com/user-attachments/assets/8d670bcf-ba5c-407a-8b60-7ec2ed1d5286">
<img width="900" alt="Screenshot 2024-11-18 at 11 20 43" src="https://github.com/user-attachments/assets/07ffb8c7-7a16-4e4e-a921-de21477c0163">

#### Potential Solution
Could be a data issue, so having enough data should work

#### Reproducing the Problem
Trying to backtest these (or some other) symbols during specific time periods (orders must be placed)

#### System Information
QuantConnect's Cloud backtest

**Comment by Martin-Molinero** [comment]
Hey @o-nazaruk! Yes, sorry for the inconvenience, this is a data issue, please report it at https://www.quantconnect.com/datasets/binance-cryptofuture-price-data
