### ISSUE TITLE
Getting net6.0 error after net9.0 update in local live

### ISSUE THREAD

**Issue by qt1729** [QuantConnect/Lean#8476]
#### Expected Behavior

I am running CLI **lean live my_project** locally and expect it to launch live session with Binance brokerage for me.

#### Actual Behavior

Getting the following error: 

> Error: Invalid option(s):
> -f net6.0
>    'net6.0' is not a valid value for -f. The possible values are:
>       net9.0           - Target net9.0
>       netstandard2.0   - Target netstandard2.0
>       netstandard2.1   - Target netstandard2.1

#### Potential Solution

I guess with the update to net9.0 we didn't install dot net 6.0 sdk, but it is still required by the 3rd party dependencies.

#### Reproducing the Problem

1. Create a simple (blank) strategy
2. Install lean locally as suggested in the guidance pages. This will download the latest lean image, latest lean brokerages, etc
3. run lean live my_project
4. specify all the brokerage parameters to be stored. 

The error appears. 
I confirm that the issue exists if I run it with different brokerages as well. Tested with Kraken. so I guess it is not brokerage specific, but related to the update.

To test the issue I updated the latest lean again: 
pip install --upgrade lean

lean version: 1.0155

#### System Information

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

#### Checklist

- [x] I have completely filled out this template
- [] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
>lean version: 1.0155

Hey @qt1729! Sorry for the inconvenience, we released net9 support. The version your using of the lean CLI is very old, please update to the latest version `1.0.211` which has multiple improvements.
