### ISSUE TITLE
Scale factor.

### ISSUE THREAD

**Issue by benjaminthedonkey** [QuantConnect/Lean#848]
On class  QuantConnect.Util.LeanData, the Scale function is using integer 10000.   A typical  FX quote would have five digits after the decimal point. I think this rounding is doping the last digit.

**Comment by jaredbroad** [comment]
In LEAN master scale factors are only applied to equities, options and futures. You may have an old build which had that issue. https://github.com/QuantConnect/Lean/blob/5542e6cd9c741bb77ddf5a092fef96b67d8b0d56/Common/Util/LeanData.cs#L91
