### ISSUE TITLE
Add Fisher Transform indicator

### ISSUE THREAD

**Issue by bizcad** [QuantConnect/Lean#85]
The Fisher transform is a mathematical process which is used to convert any data set to a modified data set whose Probability Distribution Function is approximately Gaussian.  Once the Fisher transform is computed, the transformed data can then be analyzed in terms of it's deviation from the mean.

The equation is y = .05 * ln [ 1 + x / 1 -x ] where
x is the input
y is the output
ln is the natural logarithm

The Fisher transform has much sharper turning points than other indicators such as MACD

For more info, read chapter 1 of Cybernetic Analysis for Stocks and Futures by John F. Ehlers or
Bing for USING THE FISHER TRANSFORM

**Comment by mchandschuh** [comment]
Reopening as this is still a useful feature to have. Here's a link to the previously proposed implementation: https://github.com/bizcad/Lean/blob/5993a0ab496cc96ed1d0178f1d5a7be044be7747/Indicators/FisherTransform.cs

Thanks @bizcad for doing the leg work on this!! I think it just needs some cleanup. Also, an input normalizer would be nice, since it expects values in the (-1,1) range.

**Comment by bizcad** [comment]
I dropped the issue because I thought you were not interested.  I would be happy to clean up anything you want.  Please just let me know.  I thought I was done when I removed the try/catch blocks.

The EMAlike calculation for value1 in the code is the normalizer for the price in the last {period} bars. If you rename my test file spy_fisher_minutes.txt to csv, you can see value1 in column U is between -1 and 1.  Just in case of any outliers, my implementation also checks to make sure the newly calculated value1 is between -0.9999 and +0.9999.

In addition to Ehlers book on page 6, here is my reference to the 
<a href="https://en.wikipedia.org/wiki/Fisher_transformation">Fisher Transform on Wikipedia</a>

I also dropped the PR and the fork of my github origin on github/Bizcad/Lean.  I needed to get my origin synced with the upstream/master so I could update my experimental project where I write and test indicators and algos before I do a PR.  So I will need to reproduce my work; which is not a big deal.

**Comment by AlexCatarino** [comment]
Hi @bizcad, if you don't have the time, I could take a look at this indicator.
After we have all the "TA-Lib" indicators on Lean, I think, the natural move would be to implement "exotic" indicators like "Ehler's".

**Comment by bizcad** [comment]
@Alex  I have it already done as both Fisher and InverseFisher.  I do not have tests for them however.
[FisherTransform.zip](https://github.com/QuantConnect/Lean/files/216094/FisherTransform.zip)

If this link does not work contact me at nicholasstein@cox.net

**Comment by jaredbroad** [comment]
Completed by #569d5af
