### ISSUE TITLE
Hull Moving Average

### ISSUE THREAD

**Issue by realcake** [QuantConnect/Lean#855]
I have found an interesting new indicator, the [Hull Moving Average](https://alanhull.com/hull-moving-average). It's pretty powerful, as it has much less lag compared to other moving averages. I would love to see it implemented into QC.

**Comment by Jay-Jay-D** [comment]
Hey @realcake, I made [this implementation](https://www.quantconnect.com/forum/discussion/589/hull-moving-average-implementation) using extension methods.

I also found in my old files another [implementation as indicator](https://gist.github.com/Jay-Jay-D/8a8bdd83e4deabf4fe86827d600deeeb), for sure it needs some refactoring.

**Comment by Jay-Jay-D** [comment]
#873
