### ISSUE TITLE
Slice to have Resolution

### ISSUE THREAD

**Issue by Worthy7** [QuantConnect/Lean#871]
Can we add "Resolution" to Slices and QuoteBars please.
If we subscribe to one security at two resolutions, then we cannot differentiate them easily when OnData is called.

**Comment by jaredbroad** [comment]
Slices are short for a "time slice" -- this is a point moment in time container of the time step's data including past/fill-forward data & shouldn't have a resolution. 

Currently the way to get two resolutions of data is to ask for the [lower resolution and use a consolidator](https://github.com/QuantConnect/Lean/blob/master/Algorithm.CSharp/DataConsolidationAlgorithm.cs#L66) to build the higher bar you need and trigger the event handler. Its about 2 lines of code :) 

In the future we may add ability to directly AddSecurity() for 2 resolutions but this will need to be carefully thought out as it will break millions of algorithms :).

**Comment by Worthy7** [comment]
Its 2 lines of code and a lot of unnecessary CPU. I did see a way to grab "TimePeriod" actually which did the trick. Thanks!
