### ISSUE TITLE
Add an Ichimoku indicator

### ISSUE THREAD

**Issue by nii236** [QuantConnect/Lean#88]
There has been talk of adding in TA-Lib integration, which is all well and good. In my spare time I'll be attempting to implement the ichimoku indicator which is what I use in graph based trading. With luck I'll be able to get it working in LEAN and do it all algorithmically.

**Comment by jaredbroad** [comment]
Thank you @nii236! Lets keep this issue for a Lean naitive implementation of the Ichimoku Indicator; and if you're keen please submit separate issue for TA Lib integration.

**Comment by nii236** [comment]
@jaredbroad: Of course, I wasn't clear in my original post. What I meant was TA Lib integration was being considered by TA Lib itself did not support ichimoku indicators. Hence this issue was made specifically for an ichimoku indicator.

**Comment by nii236** [comment]
I've completed a (pull request)[https://github.com/QuantConnect/Lean/pull/126] regarding this issue which was merged a couple of days ago.
