### ISSUE TITLE
Feature:  ALMA moving average

### ISSUE THREAD

**Issue by michaelsrew** [QuantConnect/Lean#883]
If you find some time one day there is a moving average which trader can use in IB TWS: 
arnaud legoux moving average
[https://www.interactivebrokers.com/en/software/tws/usersguidebook/technicalanalytics/arnaudlegoux.htm](https://www.interactivebrokers.com/en/software/tws/usersguidebook/technicalanalytics/arnaudlegoux.htm)
from:
[http://www.arnaudlegoux.com/index.html](http://www.arnaudlegoux.com/index.html)
There is also an C# implementation on his website which could be adapted.
It would be interesting to play around with that new stuff with your data.
thanks :)

**Comment by jaredbroad** [comment]
Can you please attach the example data of the daily SPY + ALMA generated in TWS/TS? This will be used for the test set.

**Comment by Jay-Jay-D** [comment]
I take it

**Comment by Jay-Jay-D** [comment]
This is my [Excel implementation](https://docs.google.com/spreadsheets/d/1PoFqUP4w9o6JZMuH1Cx8y3Lvi0bPLDpsbAUBs13_1vE/edit?usp=sharing) of the ALMA, I'll use this data in the tests unless @michaelsrew gives us data from TWS.

**Comment by michaelsrew** [comment]
wow i didn't expect it so fast. thanks again. I only wanted to play around with some new stuff and also they are writing that this moving average is the new thing working better that others(ema,..)
back to reality: i am not good with that trading tool(tws) from ib. If i would now how to provide you that data  you will get it by tomorrow. I've seen that Jay-Jay-D started testing his implementation from the 22.2.2013 SPY daily values and they are quite ok compared with the line drawed by the chart-trader in tws. I could write down some values what i see from the charting tool. i am a beginner sorry :(

**Comment by michaelsrew** [comment]
Starting jay-jay-d's data on 22 February 2013 i took around 41 spy day close values starting at this specific date to have something to compare. The alma moving average parameters used in TWS are the same values as he used for his test [ALMA(9,0.85,6.0)]. This
[alma.xlsx](https://github.com/QuantConnect/Lean/files/974340/alma.xlsx)

 file contains only IB SPY daily Close values and the corresponding alma values to compare/test.
If you need more data i will get you some more of tws.
thanks!

**Comment by Jay-Jay-D** [comment]
@michaelsrew I compare the data you shared with the data in the Excel implementation and the results are very different. As you can see in [this plot](https://drive.google.com/open?id=1q2t_8mcUDUxotG--vy_7KCaNwNfyCx1cUbXFm_m2ZM8), the ALMA from TWS has a lot of lag, and it cannot be explained with differences in the closes prices.  

Can you please check the parameters in the ALMA formula? please make sure that:
- **windows size** (period) = 9
- **sigma** = 6 
- **offset** = 0.85

If the parameters are correct and the data is still the same, well that means one of the implementations is wrong.

**Comment by herrold** [comment]
Differences with IB Close data and those from other data vendors are always causing questions on the TWS-API mailing list, and have been causing questions for the last decade.  As EOL data is being used,  it would be sensible perhaps to use daily High or Low instead, as those should not vary materially, save when the O or C is one of those values

Alternately, just using an agreed common dataset rather than retrieving what _should_ match any particular date, should permit bisecting out where the variance is coming from

**Comment by Jay-Jay-D** [comment]
>Alternately, just using an agreed common dataset rather than retrieving what should match any particular date, should permit bisecting out where the variance is coming from.

Agree, the data set used to test the indicators is available [here](https://github.com/QuantConnect/Lean/blob/master/Tests/TestData/spy_ohlcv.txt). @michaelsrew, can you run the ALMA in TWS with this data and share the results?

**Comment by michaelsrew** [comment]
Hi, first sorry for that typo. There is a small bounce in the red alma line which is my typo mistake. This value 
155.84	155.9	0.06	**154.901**	155.5872882
should be
155.84	155.9	0.06	**153.901**	155.5872882
Second: i don't know how to enter given values to test their alma moving average in tws. What i see i can only play inside charts with it. But i don't think i have to test it. 

Below is your calculated alma with the IB alma values compared with the IB-TWS alma chart.
![almacompare](https://cloud.githubusercontent.com/assets/22957504/25713764/16c941ba-30f6-11e7-94ad-dc9ac8c35991.png)

What you can see in that picture is that beside my typo its the correct alma moving average line what IB is giving me to play around (red line in both charts [jay-day-d's and IB's])

But jay-jay-d's implementation of the alma moving average (green line in the above chart) is not phase shifting some how at the turning points.
Comparing it to the pictures i see in google of the alma moving average where no phase shift can be seen in the pictures i would say his implementation is the right one.
You can see it clearly that his implementation is lagging behind the spy values which is consistent with the other implementations of alma seen on google. Please do your own math at this point. Maybe its wrong what i think.
But i would see the student at IB which implemented the alma moving average is also the quality management officer. The alma moving average has two moving average the article says. One from left to right and the other from right to left. Maybe there is somewhere a wrong + or - why the line is starting to shift when the values starting to count more at turning points.
If someone has good connections to IB please create an ticket.
Thanks for the implementation jay-jay-d.
Please leave it like it is in quantconnect.
thanks people for the fast implementation.

**Comment by Jay-Jay-D** [comment]
Well done @michaelsrew and thanks for your analysis!

@jaredbroad, I think this issue can be closed now.

**Comment by Jay-Jay-D** [comment]
#890

**Comment by michaelsrew** [comment]
hi thanks
maybe i got a little confused at this article:
[https://tradingsim.com/blog/5-strategies-day-trading-arnaud-legoux-moving-average/](url)

where it says:
The Arnaud Legoux moving average attempts to bridge this gap and thus is expected to show both responsiveness and smoothness at the same time. Interestingly, the Arnaud Legoux moving average applies the moving average twice, once from left to right and the other from right from left with the process said to eliminate price lag or phase shift significantly, a problem that is common to the traditional moving averages.

that article why i got interested into alma......
@Jay-Jay-D 
@herrold 
still interesting as no one saw at IB that this is never used because is wrong? so maybe not that new but not that used...and maybe promising...

**Comment by michaelsrew** [comment]
ok so after thinking a little bit about that stuff it seems that IBs implementation is laging to much behind. The inventor of this moving average compares his MA with the hull moving average that it works better and smoother where he provides the comparison below. You can see that it almost behaves like the hull moving average. But that is not like IB's implementation behave :(.
![hullvsalma](https://cloud.githubusercontent.com/assets/22957504/25728007/b2770f4e-312c-11e7-8d7a-25a83fe5f6a5.png)

maybe a ticket wouldn't be so wrong...

**Comment by edlang** [comment]
6 year necromancy...

@michaelsrew @jaredbroad @herrold did you ever get a response from IB? I'm also puzzled by the difference between popular implementations, and theirs.
