### ISSUE TITLE
Options Templates in Python

### ISSUE THREAD

**Issue by orenyomtov** [QuantConnect/Lean#904]
I see that there are a few options templates in C#:

https://github.com/QuantConnect/Lean/blob/master/Algorithm.CSharp/BasicTemplateOptionStrategyAlgorithm.cs
https://github.com/QuantConnect/Lean/blob/master/Algorithm.CSharp/BasicTemplateOptionTradesAlgorithm.cs
https://github.com/QuantConnect/Lean/blob/master/Algorithm.CSharp/BasicTemplateOptionsAlgorithm.cs
https://github.com/QuantConnect/Lean/blob/master/Algorithm.CSharp/BasicTemplateOptionsFilterUniverseAlgorithm.cs
https://github.com/QuantConnect/Lean/blob/master/Algorithm.CSharp/BasicTemplateOptionsHistoryAlgorithm.cs

But I find none written in Python.

Is it even possible to write options strategies in Python?

If so, I would love to see a written example (template), or to get a push in the right direction on how to "translate" the C# written templates into Python.

**Comment by jaredbroad** [comment]
Addressed in PR #905
