### ISSUE TITLE
Add public property WorkingBar to TradeBarConsolidatorBase<T>

### ISSUE THREAD

**Issue by StefanoRaggi** [QuantConnect/Lean#91]
Hi everyone, 
I am evaluating Lean for my algo development and so far I like it very much.

In my first intraday algorithm I am using the TickConsolidator to build minute bars from tick data and I need to access the current bar (in progress) from the OnData(ticks) method.
Unfortunately the current consolidating bar is accessible only in the DataConsolidated event which is fired only at the end of the chosen period. 

Adding the following in TradeBarConsolidatorBase.cs would be enough for me:

        /// <summary>
        /// Gets the current 'workingBar'.
        /// </summary>
        public TradeBar WorkingBar
        {
            get { return _workingBar; }
        }

Am I right or is there a better way and if ok do you need a pull request for this small change ?

Thanks
Stefano

**Comment by jaredbroad** [comment]
Welcome @StefanoRaggi! Thank you for the suggestion, and I'm glad you're enjoying Lean!

That suggestion looks great; but perhaps the only caveat would be that it allows the user to modify the state of the working bar - and corrupt the potential output. Perhaps a better solution would be to return a clone of the working bar, making the Consolidator more robust.

Cloning a working bar is pretty simple with our underlying extensions: you just need to use baseData.Clone().

    /// <summary>
    /// Gets the current 'workingBar'.
    /// </summary>
    public TradeBar WorkingBar
    {
        get { return _workingBar.Clone(); }
    }

**Comment by StefanoRaggi** [comment]
I agree 100% with your suggestion to clone the bar, I only needed read access to it anyways.

I am currently working on the Consolidator (I found a bug in tick aggregation due to issue #90, so will fix both at the same time).

Thanks
Stefano
