### ISSUE TITLE
Which data can the AlgoSeekOptionsConverter handle?

### ISSUE THREAD

**Issue by orenyomtov** [QuantConnect/Lean#912]
I'm thinking of purchasing options data to use with [AlgoSeekOptionsConverter](https://github.com/QuantConnect/Lean/tree/master/ToolBox/AlgoSeekOptionsConverter) from[ AlgoSeek](https://www.algoseek.com/equity-options/).

Which of the following formats can it handle?
![image](https://cloud.githubusercontent.com/assets/168856/26003717/2bb1c790-373c-11e7-8123-52451f608cda.png)

**Comment by jaredbroad** [comment]
It is generated with raw Trades and Quotes data.
