### ISSUE TITLE
Assembly errors building on Mac OSX

### ISSUE THREAD

**Issue by gaffney** [QuantConnect/Lean#914]
Hello

I had to fix about 5-6 assembly errors when attempting to build on Mac OSX.  It does not appear to me these were Mac-specific considering they were straight up missing libraries in the packages.config files, for example `NodaTime` in `Api/packages.config`. Please try **building from scratch**.

Current master of Lean; Mac OSX 10.11.6; Xamarin Studio 6.1.2/44

**Comment by jaredbroad** [comment]
This has been addressed in recent commits. Please pull down master and follow the instructions in ReadMe to put the right DLL in place.  https://github.com/QuantConnect/Lean/pull/989
