### ISSUE TITLE
Missing Chinkou Span in Ichimoku Kinko Hyo indicator

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#919]
In Lean, Ichimoku Kinko Hyo indicator has the following members ("sub indicators"):
- Kijun Sen
- Tenkan Sen
- Senkou Span

The Chinkou Span is missing.
Chikou Span (green line): This is called the lagging line. It is today’s closing price plotted 26 periods behind. ([source](
http://www.babypips.com/school/elementary/common-chart-indicators/ichimoku-kinko-hyo.html))

**Comment by jcandan** [comment]
+1

**Comment by mchandschuh** [comment]
Could use the `Delay` indicator to achieve this.
