### ISSUE TITLE
Universe Selection Optimizations

### ISSUE THREAD

**Issue by Worthy7** [QuantConnect/Lean#933]
Hi there.
I would like to improve/optimize the way UniverseSelection works.
This is my scenario:
a) I have some criteria for stock selection I would like to make, against all stocks.
b) It relies on fundamental data (stuff in FineFundamentals).
c) It runs out of RAM at around 200-250 coarse selected Symbols using the online backtested.
d) I cannot download the fundamental data from the site, so I cannot run this on my own machine - (so I cannot debug it to improve the code, as well as not being able to use my 16gb machine)

1) For starters, what is taking up so much ram? After each call to the fundamental data, is it saving the data somewhere in memory? If so, why?  I feel like it is loading in ALL of the fundamental for a symbol, when I may only be requesting one or two properties.

2) Since a portfolio would only need refreshing say every, month, 6 months, 12 months, I feel a lot of the "Universe Selecting" that happens is entirely just wasted CPU cycles when we define a portfolio size.
For example, lets say I want to make a robo-manager which will include up to 10 stocks of some given criteria, and they must be held for at least 6 months.
When we have 10 from our coarse and fine selection, it can essentially fast-forward 6 months from when the first stock was added, reassess that stock, if it is still valid, allow it to stay another 6 months (and fast-forward again to the next time it needs to "reassess the portfolio".

**Comment by jaredbroad** [comment]
- There was a few cycles of universe selection we were able to optimize out recently in the subscription management.

 - The universe selection logic happens each tick at a maximum; each day at a minimum. There could be a chance to do it less but it isn't a large amount of work. Most of the work is from actually streaming and synchronizing thousands of files.

 - We've measured the objects internally and there is no leak; they are genuinely using that much RAM to hold all the data we're sending into the algorithm.
