### ISSUE TITLE
SubscriptionTransportMedium - unnecessary enum?

### ISSUE THREAD

**Issue by gminorcoles** [QuantConnect/Lean#940]
Hi,
 I am attempting to extend LEAN to allow adding data for backtesting from a SQL database. I notice that when you create the SubscriptionDataSource, you need to pass in the enum value for the transport medium. This enum seems brittle and adds another point of variation when extending the system. I added "SQL" as one of the enumerated values, to my local copy of the code. I don't know LEAN codebase very well but as I try to do things I am making note of the places where I encounter pain.

**Comment by andrewhart098** [comment]
Hey @gminorcoles - One potential way to use Lean with a database is to create a custom IDataProvider (SQLDataProvider) and tell Lean to use it by changing the "data-provider" config option to the class you create.

**Comment by gminorcoles** [comment]
Hi @andrewhart098. I have the CollectionSubscriptionDataSourceReader code open right now with the intention of doing what you suggest. The existing readers only know that each line is a string, so I definitely need to extend at the datasource reader level. 

If I had a more complete understanding of all the types of data that are spoken by LEAN I could think of how one might employ a serialization tool like flatbuffers, protocol buffers, thrift, etc to create more of an ORM kind of approach where schemas are all defined in IDL and then built into external assemblies. You would need to worry about lowest common denominator schema, for data that is mean to be consumed by the system, for P&L and such.

**Comment by jaredbroad** [comment]
Hello @gminorcoles; it is a little confusing I agree but has a purpose:

Essentially we're trying to represent the physical mode of transfer for the data. How the data is transmitted to LEAN and build in tools which handle those means of communication. E.g. SQL would actually be named pipes; or local DNS.

The stack tree branches a few times there but as Andrew points out the IDataProvider is the way for now.

**Comment by gminorcoles** [comment]
@jaredbroad I get it, it's not too confusing. Just figured I would comment on it, since how to connect custom data sources seems like a core topic.

**Comment by andrewhart098** [comment]
> The existing readers only know that each line is a string, so I definitely need to extend at the datasource reader level.

Could you just format the data returned from your SQL queries as a comma separated list of values in the IDataProvider?

**Comment by jaredbroad** [comment]
Closing as no specific direction to consider / misunderstanding of the requirements.
