### ISSUE TITLE
Add Directory of Daily csv price files - requires adding a "market? and creating a directory named after market?

### ISSUE THREAD

**Issue by gminorcoles** [QuantConnect/Lean#951]
I have a few hundred csv files that contain global equity prices from FactSet, which I extracted from their SQL database. These files live in c:\data\equities\daily\factset. If I am understanding LEAN correctly, when I try to load data, LEAN, implicitly relies on the data directory having a certain structure which relies on the data frequency enum and the Market static class? 

Market is an odd beast. "usa" is a market, as is "oanda" and "CBOT". Does that mean "factset" must become a market too? It does not make a lot of sense to me.

**Comment by gminorcoles** [comment]
A comment - I tried adding a market using the Market.Add(string,int) method. But this data does not flow through to the DefaultBrokerage, which is  used to validate the available markets using its dictionary of markets which are hardcoded, not referencing Market.cs at all. So to add a market, and to try to add data for that market, will not work unless you edit the code in DefaultBrokerage and add to the list of hardcoded markets, and recomplile.

**Comment by jaredbroad** [comment]
Correct adding an additional international exchange/country requires recompiling the code. It also requires setting up your market hours and for completeness figuring out the execution to a brokerage. We'll look into Market.Add() that seems like an oversight.  LEAN is currently configured for us-equities, forex, us-options, us-futures and cfd.

Factset is a large company so I'm not sure what of their data you're referring to but I assume it is just like MorningStar fundamentals data. You can follow that data as an example.

Market is a way of distinguishing different tradable contracts. All USA equities are the same contracts just traded on different exchanges. 

Yes we use the data structure provided by the GetSource() method which is read by the Reader() method.

**Comment by gminorcoles** [comment]
We can neglect the "factset" part, just custom equities data provider B. The data is in csv files and contains a couple of fields that are not known in the LEAN format. I created a custom data class but there is no way that I can figure out to call AddData using a custom class that also allows me to set the SecurityType.

**Comment by AlexCatarino** [comment]
@gminorcoles, it looks like a question about [Importing Custom Data](https://www.quantconnect.com/docs#Importing-Custom-Data). Could you please email support (support@quantconnect.com) with more information so that we can help you?

**Comment by gminorcoles** [comment]
ok I sent an email from my work address, coming from quantitative.com
