### ISSUE TITLE
ImmediateFillModel limit order fill price assumption very optimistic

### ISSUE THREAD

**Issue by 4real** [QuantConnect/Lean#963]
I'm not really talking about the fact that the order is assumed immediately filled when there is a price match (which is the point of the class), but the price at which the fill takes place:

```
// fill at the worse price this bar or the limit price, this allows far out of the money limits
// to be executed properly
fill.FillPrice = Math.Min(prices.High, order.LimitPrice);
```

More likely, when we're dealing with not frequently traded stocks, the order will in reality be filled at the limit price, which can differ significantly from the high point of the next bar. So it's possible to write an intraday algorithm that trades on the distortion caused by ImmediateFillModel... Why is this a problem when volume is ignored? Because even if you make a simple modification to a copy of ImmediateFillModel to e.g. ignore trades below a certain volume the fill price problem remains, and the later you detect issues like these the more time you waste.

What's problematic about the code in question: The Min/Max allows one case to be properly handled (that otherwise would be pessimistically dealt with) but makes another case very common for limit orders (order remaining passive in limit book) optimistically erroneously dealt with. I much prefer pessimism over optimism because the latter leads to untradable algorithms.

Suggested fix:
```
fill.FillPrice = order.LimitPrice;
```
Alternatively, if keeping old behavior for immediate fills is important, make some logic to determine if this is the first bar a fill could have occurred, and if so apply old fill price function.

Decided to post this directly here rather than on forum since it's a straightforward fix if accepted.

Petter

**Comment by jaredbroad** [comment]
Tracking this here https://github.com/QuantConnect/Lean/issues/6973
