### ISSUE TITLE
RollingWindow is not thread safe (is it supposed to be?)

### ISSUE THREAD

**Issue by AnObfuscator** [QuantConnect/Lean#97]
I was taking a look at this file:
https://github.com/QuantConnect/Lean/blob/master/Indicators/RollingWindow.cs

It appears that QuantConnect.Indicators.RollingWindow starts to be thread safe (with locks around Add, GetEnumerator, and Reset), but also allows unguarded reading and modifying the underlying list data structure without locks. *If* this thread is intended to be used with multiple threads, this is a serious risk.

**Comment by mchandschuh** [comment]
Indeed this could cause concurrency issues, modifying the other operations to be performed within the same lock should alleviate these concerns.  Other suggestions are welcome.

**Comment by AnObfuscator** [comment]
If locking overhead is a performance risk, this might be a useful class:
https://msdn.microsoft.com/en-us/library/system.threading.readerwriterlockslim(v=vs.110).aspx

I've used the Java equivalent with great success in the past.

**Comment by mchandschuh** [comment]
Wonderful idea, locking overhead with this type usually isn't an issue, but there's no reason to not design it with that in mind. Thank you.

**Comment by AnObfuscator** [comment]
Here's my fixed version:
https://github.com/AnObfuscator/Lean/commit/41d6112cee85be70620609517eacf75512c5519b

I can send a pull request if you like.

**Comment by mchandschuh** [comment]
Please do, code looks great! Thanks for taking the time to do this!!

**Comment by AnObfuscator** [comment]
https://github.com/QuantConnect/Lean/pull/100
