### ISSUE TITLE
live-interactive mode: Ability to accept GoodTillDate and DurationValue in QC orders for IB

### ISSUE THREAD

**Issue by mayurbakhai** [QuantConnect/Lean#971]
I wanted to set a time for the orders to expire after specific time or after certain duration in IB's paper trading account. 

In `InteractiveBrokersBrokerage.cs` I noticed that when QC order is converted to an `IB.Api.Order` in `ConvertOrder` method, TimeInForce was set to GoodTillCancel. I changed those values in `IBPlaceOrder` method to accept `IBApi.Order.Tif = IB.TimeInForce.GoodTillDate` and `IBApi.Order.GoodTillDate = order.Time.ToLocalTime().AddSeconds(30).ToString("yyyyMMdd HH:mm:ss");` which says order would expire 30sec after order was created. That worked in IB's paper trading account.

I am wondering if there's a way QC orders could accept `OrderDuration.Custom` and `DurationValue` through the `LimitOrder/MarketOrder` and other order types used in the algo using QCAlgorithm API which could then be used to set IBApiOrder when converting QC orders. Hope that makes sense. 

I may be wrong in the way I'm using QC orders but I don't see a way of achieving what I described above. Would appreciate if you could take a look.

**Comment by mchandschuh** [comment]
GTD was merged in https://github.com/QuantConnect/Lean/pull/2032
