### ISSUE TITLE
On premises job queue

### ISSUE THREAD

**Issue by lnaie** [QuantConnect/Lean#983]
Hi,

I'm seeing that the default implementation of IJobQueueHandler (JobQueue) works with the cloud platform, completely hiding the internals. Is there a local/desktop/on-premises implementation of IJobQueueHandler that's able to use some sort of ESB backend?

Thanks

**Comment by jaredbroad** [comment]
The LEAN project is intended to be perfect for an individual / start up fund. If a larger organization would like to use LEAN we prefer they work with QuantConnect and we form a service agreement. If this fits your case please get in touch at support@quantconnect.com and we can discuss how we can best help your company.
