### ISSUE TITLE
[Crypto] Enable Currency Abbreviations with More than 3 Characters

### ISSUE THREAD

**Issue by lnaie** [QuantConnect/Lean#996]
In the crypto-currency market there are coins with more than 3 chars. Check this out: https://coinmarketcap.com/all/views/all/.

I'm not sure if it's already supported deep down in the pipeline, but it should.

**Comment by jaredbroad** [comment]
Great point thank you @lnaie

**Comment by lnaie** [comment]
Could somebody pin point the work that has to be done and maybe the files/abstractions affected by this change?

**Comment by viliwonka** [comment]
I have already done this. Should I push the changes?

**Comment by jaredbroad** [comment]
@viliwonka That would be awesome! I've made a branch for you "crypto-symbol-length" -- if possible can you PR it there for review

**Comment by viliwonka** [comment]
Ok, let me work this one out, never worked with branches.

**Comment by viliwonka** [comment]
Ok excuses for me being complete noob with GitHub here, but I wasn't able to open PR with committing code, I will continue with it tomorrow.
