### ISSUE TITLE
[Crypto] Add Orderbook Support to LEAN

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#997]
Build a full order book using quote ticks, trades and make it available on the Crypto security type.

**Comment by ajaye2** [comment]
Are there any updates on when this will be completed?

**Comment by jaredbroad** [comment]
Closing this as its not top of priority right now -- and if when implemented would be done for the whole stack not just crypto.

**Comment by jaredbroad** [comment]
Reopening to gauge community interest - would be implemented for the entire stack when data is available. 

With plan focused on aggregate order book level streamed not the full book.

**Comment by Martin-Molinero** [comment]
Potential solution plan
```
TickType.Quote => Best bid/ask price & qtty
	- bool TopOfBook { get; set; } = true;
Security.OrderBook => cache.OrderBook
	- lean engine does the tracking
```

**Comment by ikamanu** [comment]
Yes please.  🙏

**Comment by multidis** [comment]
Would be helpful +1

**Comment by code-gif** [comment]
Yes please
